### ISSUE TITLE
🐛 [BUG] Internal Server Error ("manifest unknown")

### ISSUE THREAD

**Issue by c7274864** [alexbelgium/hassio-addons#1000]
### Description

Hello

Error install 

Internal Server Error ("manifest unknown")

![Capture d'écran 2023-09-23 041416](https://github.com/alexbelgium/hassio-addons/assets/143031506/0acbf12b-a608-4af1-b29a-8e247dfe84ca)
![Capture d'écran 2023-09-23 041516](https://github.com/alexbelgium/hassio-addons/assets/143031506/2cddf464-0c50-490d-8f60-7eb7a5369345)

![Capture d'écran 2023-09-23 041610](https://github.com/alexbelgium/hassio-addons/assets/143031506/57c9de0b-3d91-41bc-8540-6c07d1c056f2)

Merci 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
`Can't install ghcr.io/alexbelgium/portainer-amd64:2.19.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.19.1&fromImage=ghcr.io%2Falexbelgium%2Fportainer-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by DmytroKorniienko** [comment]
Same for Proxmox haos VM

**Comment by Ovenlade** [comment]
Same error on a Generic x86-64 Home Assistant Operating System (on a NUC)
I got the error on updating these add ons:
- Joplin 2.13.1 
- Nextcloud 27.1.1

**Comment by CAB426** [comment]
The 2.19.1 image does not exist, that is what is causing this error.  Could be something failed in the build pipeline and the image didn't make it but the metadata was updated.  Thinks there is an update but no image with that tag exists.

**Comment by alexbelgium** [comment]
All daily build failed I’ll solve that today

**Comment by alexbelgium** [comment]
Seems like there is an issue with codenotary that makes a timeout on all build. Alas it seems external to my repo

**Comment by c7274864** [comment]
Hello

Resolved by me

![Capture d'écran 2023-09-23 193837](https://github.com/alexbelgium/hassio-addons/assets/143031506/8a50763b-d8ae-40bb-aefa-f6093d92fd44)
![Capture d'écran 2023-09-23 194006](https://github.com/alexbelgium/hassio-addons/assets/143031506/a8d1356d-8c5e-42da-9d7d-9bcab030c656)

**Comment by alexbelgium** [comment]
Yes, all builds are up now ! I’ll close this unless someone has again a specific issue. Thanks all
