### ISSUE TITLE
[Plex NAS] Mount external drive by label

### ISSUE THREAD

**Issue by zoiv** [alexbelgium/hassio-addons#101]
First, thank you for these addons that are easy to add in home assistant.

I had some issues when trying to mount an external drive where my movies are stored. I had to mount it through the docker terminal but when I do any update or if there is a change in the partition location (sdb1 to sdc1 for example). I just saw in the last update of plex docker there is the possibility to mount drives by labels. Would it be possible to add this parameter to the configuration page in home assistant, in order to auto mount the drives by label ?

**Comment by alexbelgium** [comment]
Hi! All my code is adapted so you just need to type the label in the addon option instead of sda1, for example, for it to work :)

Thanks for using the addons!

**Comment by zoiv** [comment]
In my case the _localdisks_ option doesn't appear in the user interface, and if I modify the yaml config, it also doesn't work. Any clue ?

**Comment by alexbelgium** [comment]
Oups, hehe I didn't add the addon option just the code :) a new version is pushed! The disk will be mounted to /mnt/sda1 or /mnt/mylabel depending on if you use disk id (sda1 here) or label (mylabel here)

**Comment by zoiv** [comment]
Thank you so much for your quick answer ! I look forward to test it

**Comment by alexbelgium** [comment]
Is it working?

**Comment by zoiv** [comment]
Yes it works thank you !
