### ISSUE TITLE
[Omada controller] ignore “beta” version

### ISSUE THREAD

**Issue by ankushg** [alexbelgium/hassio-addons#1010]
### Description

Looks like the upstream image added a beta tag, and that’s taking priority as the “latest” version

IMO that should be ignored

### Reproduction steps

```bash
N/a
```

### Addon Logs

```bash
N/a
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, it's just the name ; under the hood it is always the "latest" tag

**Comment by ankushg** [comment]
> Hi, it's just the name ; under the hood it is always the "latest" tag 

Makes sense. It would be nice if it showed as  `x.y-arm64-2023-09-22` instead of  `beta-arm64-2023-09-22` though so we can see what the underlying version of Omada is

**Comment by ms-zlab** [comment]
For me there is also a platform change in the version: amd64 to arm64
But I am running on amd64, not arm64.

**Comment by axute** [comment]
For me there is also a platform change in the version: amd64 to arm64
But I am running on amd64, not arm64.

**Comment by alexbelgium** [comment]
Yes, it's all cosmetic it doesn't change the image itself but not optimal. I'll check what I can do, thanks!

**Comment by alexbelgium** [comment]
Ok it's done, from next version (next saturday) it will be as proposed "5-12-2023-xx-xx" with updates when the 5.12 tag has new versions pushed

**Comment by ankushg** [comment]
Thanks for being on top of this!

**Comment by pbvdven** [comment]
@alexbelgium How do i keep my current configuration i just updated the addon but now its setting up like new controller?

**Comment by alexbelgium** [comment]
Argh I will have to check if it has moved the data folder... Or is it normal when upgrading to 5.12? Not sure as I don't use this app i'll have to check

**Comment by pbvdven** [comment]
> Argh I will have to check if it has moved the data folder... Or is it normal when upgrading to 5.12? Not sure as I don't use this app i'll have to check

I dont know i just moved to omada im using it like 1 week now its my first update of omada but the current version is  5.12.7  beta-arm64-2023-09-22 and i lost all the data when upgrading to 5.12-2023-10-06 (2023-10-06) so both 5.12. I do think it normally should keep data between but im not sure there is also no backup restore in the app it self only site/controller migration. i cant believe they will let you setup your controller every time it updates and you have to reconfigure your network every time. so im no real help it looks like it uses a docker volume instead of a folder in custom_addons like your other addons do. ive i can do anything to help let me know. thanks for your time and quick response as always

**Comment by bezigebever** [comment]
Same problem here. Upgrade removes all config...
I tried to restore the backup, which crashed my whole system. I had to do a full reboot...
Restore not possible, so I am in big trouble now !

**Comment by pbvdven** [comment]
> Same problem here. Upgrade removes all config... I tried to restore the backup, which crashed my whole system. I had to do a full reboot... Restore not possible, so I had to revert to a snapshot (running on ESXi).

i also did a restore in home assistant but it took a while at first i also thought it failed but eventually i got my config back.

**Comment by axute** [comment]
I confirm, last update discarded the entire configuration. Now try to restore a backup...

**Comment by axute** [comment]
restore the backup works, but the docker image was not in the backup (samba backup addon).
I restored the docker image `ghcr.io/alexbelgium/omada-amd64:beta-arm64-2023-09-22`
(pulled via portainer container - `apk update &&  apk add --no-cache docker-cli`).

**Comment by alexbelgium** [comment]
Thanks ; your data is not lost it is just that my code is not executing at start. I'll correct that now and should get back everything (hopefully)

**Comment by bezigebever** [comment]
> restore the backup works, but the docker image was not in the backup (samba backup addon). I restored the docker image `ghcr.io/alexbelgium/omada-amd64:beta-arm64-2023-09-22` (pulled via portainer container - `apk update && apk add --no-cache docker-cli`).

@axute this is probably also why my restore got blocked, I also use Sambe backup addon... Any idea why the image is not in the backup ? 
I use hassos, so don't hink I can manipulate the docker image myself...

**Comment by alexbelgium** [comment]
Just update to the latest i've pushed. As it is a new version it will download again. Or with haos you can still use docker commands with the ssh web terminal addon

**Comment by axute** [comment]
> > restore the backup works, but the docker image was not in the backup (samba backup addon). I restored the docker image `ghcr.io/alexbelgium/omada-amd64:beta-arm64-2023-09-22` (pulled via portainer container - `apk update && apk add --no-cache docker-cli`).
> 
> @axute this is probably also why my restore got blocked, I also use Sambe backup addon... Any idea why the image is not in the backup ? I use hassos, so don't hink I can manipulate the docker image myself...

Unfortunately, I don't know exactly why the image isn't there or is being downloaded again. But he told me exactly which image could not be found when I wanted to start the addon after the restore.
I also use hassos and you could manipulate the images, but I don't have that either. I think they are both third party plugins, you would have to contact the developers.

**Comment by bezigebever** [comment]
Just ran the update, but can't login anymore with my local accout, luckily have cloud access enable.
Even after password reset, which works, login gives bad password...

**Comment by axute** [comment]
> Just update to the latest i've pushed. As it is a new version it will download again. Or with haos you can still use docker commands with the ssh web terminal addon

I installed the latest update, worked. 

Thank you for the quick repair and response. 👍

**Comment by alexbelgium** [comment]
> Just ran the update, but can't login anymore with my local accout, luckily have cloud access enable.
> Even after password reset, which works, login gives bad password...
> I've returned to my snapshot and can login again.

Update again from your snapshot, it should work again. I've added set -e which allows the addon to fail in case of errors but in this case it failed silently

**Comment by ChriKn** [comment]
Hi,
I also got both updates (last one applied yesterday) and seem to have lost my configuration.
Is there a recommended way to get it back (if possible) ?
I am using a dedicated HAOS machine
