### ISSUE TITLE
✨ [REQUEST] Mealie: Add yaml config for environmentla variables for email configurations

### ISSUE THREAD

**Issue by bobloadmire** [alexbelgium/hassio-addons#1011]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Mealie

### Is your feature request related to a problem? Please describe

can't configure email settings via GUI after install, can't configure them in the YAML config either

### Describe the solution you'd like

Enable configuring email config variables as described in mealie documentation:

Variables | Default | Description
-- | -- | --
SMTP_HOST | None | Required For email
SMTP_PORT | 587 | Required For email
SMTP_FROM_NAME | Mealie | Required For email
SMTP_AUTH_STRATEGY | TLS | Required For email, Options: 'TLS', 'SSL', 'NONE'
SMTP_FROM_EMAIL | None | Required For email
SMTP_USER | None | Required if SMTP_AUTH_STRATEGY is 'TLS' or 'SSL'
SMTP_PASSWORD | None | Required if SMTP_AUTH_STRATEGY is 'TLS' or 'SSL'

AFAIK this isn't possible, I tried just adding them to the YAML config, no dice, also gui has not options.

**Comment by alexbelgium** [comment]
Hi, indeed I've put this config.yaml system to be able to add custom env variables! Normally the location (that you correctly have found in /config/addons_config/mealie) should be described in the startup log - or else I should add it.

I've added a wiki page to describe this : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables
