### ISSUE TITLE
🐛 [Seafile] seafile has disappeared from the list

### ISSUE THREAD

**Issue by gsieben** [alexbelgium/hassio-addons#1017]
### Description

Seafile is no longer shown in the add button list. 

### Reproduction steps

```bash
1. Just reload the plugin list, listed be the add button
2. Since yesterday seafile is missing in the list. 

Maybe its related to th "udev": true update in the config file. I can't try a fix because the config is immediately overwritten when reloading. 

GG
```

### Addon Logs

```bash
No logs
```

### Architecture

armv7

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, thanks for sharing ; I confirm it has disappeared here too but I don't understand why, the config seems valid...

**Comment by alexbelgium** [comment]
Corrected, thanks for noticing!

**Comment by gsieben** [comment]
Thanks for the super fast response Alexandre. Unfortunately it does not work for me. The day before yesterday the package was still there. I had to uninstall it again. And then it was not listed anymore. I have deleted the whole chache. But it does not appear. Don't understand why either. It actually looks good.

**Comment by alexbelgium** [comment]
Sorry doesn't work here too ;) I thought it was that but probably not. I'll check again for other config.json erros

**Comment by alexbelgium** [comment]
Confirmed to be working now :) I had corrected the first instance and there were two

**Comment by gsieben** [comment]
Yes, now it works again. Thank you very much. And thank you for your great work here.
