### ISSUE TITLE
🐛 [Emby NAS] After update to version 4.8.0.49-2, addon stops after 1m

### ISSUE THREAD

**Issue by rqmartins73** [alexbelgium/hassio-addons#1018]
### Description

After updated to version 4.8.0.49-2 the addon starts but as last message says "FATAL: Addon will stop in 1m to prevent damages to your system", and after ~1m it indeed stops.

Had to roll back..

Regards.

### Reproduction steps

```bash
1. Update
2. Start
```

### Addon Logs

```bash
[14:13:54] FATAL: Addon will stop in 1m to prevent damages to your system
```

### OS

HAos

**Comment by alexbelgium** [comment]
Could you please post your log, thanks

**Comment by rqmartins73** [comment]
Hi.
Here it is, i just changed the sensitive information. This is all it gets.

Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Emby NAS
 A free Software Media System that puts you in control of managing and streaming your media
-----------------------------------------------------------
 Add-on version: 4.8.0.49-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
PGID='0'
PUID='0'
cifsdomain='xxx'
cifspassword='xxx'
cifsusername='xxx'
networkdisks='//xxx.yyy.aaa.zzz/Musica, //xxx.yyy.aaa.zzz/Videos, //xxx.yyy.aaa.zzz/Emby_Backups, //xxx.yyy.aaa.zzz/Fotos_Eu, //xxx.yyy.aaa.zzz/Camera, //xxx.yyy.aaa.zzz/MRMSG9'
silent='false'
Timezone set from Etc/UTC to Europe/Lisbon
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
[14:21:26] WARNING: ------------------------
[14:21:26] WARNING: This is a new code, please report any issues on https://github.com/alexbelgium/hassio-addons
[14:21:26] WARNING: ------------------------
Mounting smb share(s)...
... using domain mydomain
... using PUID 0 and PGID 0
... mounting //xxx.yyy.aaa.zzz/Musica
[14:21:26] INFO: ... //xxx.yyy.aaa.zzz/Musica successfully mounted to /mnt/Musica with options ,uid=0,gid=0,iocharset=utf8,domain=mydomain
... mounting //xxx.yyy.aaa.zzz/Videos
[14:21:26] INFO: ... //xxx.yyy.aaa.zzz/Videos successfully mounted to /mnt/Videos with options ,uid=0,gid=0,iocharset=utf8,domain=mydomain
... mounting //xxx.yyy.aaa.zzz/Emby_Backups
[14:21:27] INFO: ... //xxx.yyy.aaa.zzz/Emby_Backups successfully mounted to /mnt/Emby_Backups with options ,uid=0,gid=0,iocharset=utf8,domain=mydomain
... mounting //xxx.yyy.aaa.zzz/Fotos_Eu
[14:21:27] INFO: ... //xxx.yyy.aaa.zzz/Fotos_Eu successfully mounted to /mnt/Fotos_Eu with options ,uid=0,gid=0,iocharset=utf8,domain=mydomain
... mounting //xxx.yyy.aaa.zzz/Camera
[14:21:27] INFO: ... //xxx.yyy.aaa.zzz/Camera successfully mounted to /mnt/Camera with options ,uid=0,gid=0,iocharset=utf8,domain=mydomain
... mounting //xxx.yyy.aaa.zzz/MRMSG9
[14:21:27] INFO: ... //xxx.yyy.aaa.zzz/MRMSG9 successfully mounted to /mnt/MRMSG9 with options ,uid=0,gid=0,iocharset=utf8,domain=mydomain
[14:21:27] FATAL: Addon will stop in 1m to prevent damages to your system

And after one minute:

s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111

**Comment by alexbelgium** [comment]
Thanks very much - indeed a failure in my code as everything mounts correctly
I've modified the conditions to stop the addon and will push a new version (version -4)

Here is the commit : https://github.com/alexbelgium/hassio-addons/commit/73929258af5f7cbf3531828df13a8ba8fb25bd8a

**Comment by rqmartins73** [comment]
> Thanks very much - indeed a failure in my code as everything mounts correctly I've modified the conditions to stop the addon and will push a new version (version -4)
> 
> Here is the commit : [7392925](https://github.com/alexbelgium/hassio-addons/commit/73929258af5f7cbf3531828df13a8ba8fb25bd8a)

Thanks to you Alexandre!
Regards.

**Comment by alexbelgium** [comment]
Thanks to you for commenting and providing the infos! I'm improving the codes to be more reliable and usually test them on my own system, but as ever then there is always some systems specificities that I need to take into account to make sure it works successfuly ;-)

**Comment by rqmartins73** [comment]
HI Alexandre,

-5 is still stopping, same logs.

**Comment by alexbelgium** [comment]
Hi, I see sorry it seemed I didn't pushed the right update ;-)

**Comment by alexbelgium** [comment]
That's why people say multitasking is bad ;-)

**Comment by rqmartins73** [comment]
-6 Working! All good.

Thanks mate. A restfull and relax rest of the day.
Regards.

**Comment by alexbelgium** [comment]
Great thanks! have a nice evening
