### ISSUE TITLE
✨ [REQUEST] qBit Manage

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#1019]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

qBit Manage ( https://hub.docker.com/r/bobokun/qbit_manage ). This tool will help manage tedious tasks in qBittorrent and automate them. Tag, categorize, remove Orphaned data, remove unregistered torrents and much much more. 

### Is your feature request related to a problem? Please describe

Related to qBittorrent but is more of an ease of use than a problem.

### Describe the solution you'd like

An easy way to automate qBittorrent, useful when used in combination with the 'arr' family and any media server. Below is from the docker page:

This is a program used to manage your qBittorrent instance such as:

    Tag torrents based on tracker URLs
    Update categories based on save directory
    Remove unregistered torrents (delete data & torrent if it is not being cross-seeded, otherwise it will just remove the torrent)
    Automatically add [cross-seed](https://github.com/mmgoodnow/cross-seed) torrents in paused state. *Note: cross-seed now allows for torrent injections directly to qBit, making this feature obsolete.*
    Recheck paused torrents sorted by lowest size and resume if completed
    Remove orphaned files from your root directory that are not referenced by qBittorrent
    Tag any torrents that have no hard links outisde the root folder
    Apply share limits based on groups filtered by tags/categories and allows optional cleanup to delete these torrents and contents based on maximum ratio and/or time seeded
    RecycleBin function to move files into a RecycleBin folder instead of deleting the data directly when deleting a torrent
    Built-in scheduler to run the script every x minutes. (Can use --run command to run without the scheduler)
    Webhook notifications with [Notifiarr](https://notifiarr.com/) and [Apprise API](https://github.com/caronc/apprise-api) integration

**Comment by alexbelgium** [comment]
Hi, actually I can implement it if you want :-) You reminded me this thing and I've added it in the next generation of the addon

**Comment by hacshacdgacs** [comment]
Oh that would be perfect, thank you

**Comment by alexbelgium** [comment]
Implemented!

**Comment by UnderclassAmigo** [comment]
Hey, just wondering if the qbitmanage portion auto updates or if it only does so when the whole addon is updated? Thanks

**Comment by alexbelgium** [comment]
Hi, just at build time
