### ISSUE TITLE
🐛 [autobrr] Can't update

### ISSUE THREAD

**Issue by celynw** [alexbelgium/hassio-addons#1029]
### Description

I have version `1.30.0`, trying to update to `1.31.0`. Shortly after pressing update from within Home Assistant, a banner appears at the bottom of the page with the error:

> Error updating Autobrr: Can't install ghcr.io/alexbelgium/autobrr-aarch64:1.31.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.31.0&fromImage=ghcr.io%2Falexbelgium%2Fautobrr-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

I think this error has been happening for quite a while (although I'm a little suspicious nobody else has reported it yet). I have tried just waiting and trying again later, or another day. I've also tried resetting my system etc., but all other addons including other addons from this repository update fine. Something upstream, perhaps?

Thanks!

### Reproduction steps

```bash
1. See that the 'Settings' page has an orange (1) notification (or higher).
1. Go to the Settings page. See that Autobrr has an update available
1. Try updating.
1. Encounter the error
```

### Addon Logs

```bash
N/A, not related to running of addon
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks! It just means that the build was not successful. A rebuild is now ongoing let's see how that goes

**Comment by celynw** [comment]
It worked! Thanks!
(I must have accidentally had this on auto-update so I didn't notice)
