### ISSUE TITLE
scrutiny no access to hdd

### ISSUE THREAD

**Issue by mcflexus** [alexbelgium/hassio-addons#103]
hello, i just installed scrutiny to monitor my ssd but no drive shows up in the gui. there seems to be some changes in the way addons may acces devices. if you've already installed the addon for a while it'll probably still work but for a new installation it doesn't. i found an issue that describes the problem and solution: [https://github.com/home-assistant/supervisor/issues/3194](url)

here`s the add-on log: [scrutiny log.txt](https://github.com/alexbelgium/hassio-addons/files/7652836/scrutiny.log.txt)

**Comment by alexbelgium** [comment]
Hi, thanks for the first investigation idea! To be sure : is your mapped device "/dev/nvme0"? Is it a special device, as it doesn't follow the sd*x (ex : sda1) structure?

**Comment by alexbelgium** [comment]
I've pushed a new version allowing "/dev/nvme0"

**Comment by mcflexus** [comment]
good morning and thank you for the fast response. i use an intel nuc10 wich has an nvme ssd. as nvme doesn't use sata i think it's called nvme in dev. i installed the addon and i can confirm it is working now! only thing is, scrutiny now shows 2 nvme0 and the first one is empty.
<img width="1099" alt="nvme0" src="https://user-images.githubusercontent.com/3852381/144702372-87472263-a92d-4b9a-a250-1c8acfcb71e3.png">

**Comment by alexbelgium** [comment]
Strange I seem to remember this from some time ago... Not sure what was the solution...

**Comment by mcflexus** [comment]
yes, reinstallation of the addon fixed it.

**Comment by alexbelgium** [comment]
Glad it worked! Enjoy
