### ISSUE TITLE
ARPSpoof Cant install this as addon, receive an error

### ISSUE THREAD

**Issue by JBakers** [alexbelgium/hassio-addons#1031]
### Description

When installing from addon store:

`Can't install ghcr.io/alexbelgium/arpspoof-amd64:1.0.0-2: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/alexbelgium/arpspoof-amd64:1.0.0-2/json: Not Found ("No such image: ghcr.io/alexbelgium/arpspoof-amd64:1.0.0-2")`

![arpspoof](https://github.com/alexbelgium/hassio-addons/assets/13487054/13bd7cdc-163f-4d54-9ec6-86dc47d7aac4)

### Reproduction steps

```bash
1. Go to 'Add-on Sore'
2. Click on 'Arp Spoof'
3. Click on Install
4. See error
```

### Addon Logs

```bash
Logboek Details (FOUT)
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 16:44:21 (7 occurrences)
Last logged: 17:04:22

Failed to to call /addons/db21ed7f_arpspoof/install - Can't install ghcr.io/alexbelgium/arpspoof-amd64:1.0.0-2: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/alexbelgium/arpspoof-amd64:1.0.0-2/json: Not Found ("No such image: ghcr.io/alexbelgium/arpspoof-amd64:1.0.0-2")
```

### Architecture

amd64

### OS

HAos, Virtual Machine

**Comment by alexbelgium** [comment]
And yet here it is... https://github.com/alexbelgium/hassio-addons/pkgs/container/arpspoof-amd64/53903324?tag=1.0.0-2 So it seems there is an issue with HA supervisor

**Comment by JBakers** [comment]
So weird, I rebooted before I made this report.
Rebooted the VM and the server itself and still nothing.

Restored a backup I made a few hours ago and all is good...

**Comment by alexbelgium** [comment]
Well indeed having a backup at have is always useful as I also had quite some weird issues also sometimes... Glad it worked again for you!
