### ISSUE TITLE
🐛 [Tandoor Recipes] is broken in pushed 1.5.6-test_ssl builds.

### ISSUE THREAD

**Issue by dcossey014** [alexbelgium/hassio-addons#1032]
### Description

Like a moron, I had the switch for 'Auto update' set to 'on'.  The docker container updated and most of the functionality is broken.  Recipes no longer display, 'Space Settings' show no users, etc.  I can go into 'Admin' Menu from the User drop down list and see that everything should be there, but the Tandoor Webpage doesn't display anything. 

### Reproduction steps

```bash
1. Go to 'Settings > Add-ons > Tandoor Recipes'
2. Click on 'Update' and let everything update.  After update is complete, login to Tandoor.


3.  Errors:  Clicking Tandoor in upper left redirects to 127.0.0.1:8081 instead of NGINX address and configured port.
4.  Search page shows no recipes.
5. Space Settings show no Users.
```

### Addon Logs

```bash
Apologies, already restored from backup and do not have the logs.  Can't be without this server for too long or wife gets annoyed.  However, logs did show the usual GET requests and 200 responses when trying to view the Search pages.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, thanks! I see the issue, i'll revert to previous version

**Comment by starbuck93** [comment]
Will hassio see the revert as an update? I've already updated to 1.5.6-test_ssl (14-10-2023).

**Comment by autoneub** [comment]
Running this in home assistant and also auto updated. 
Add-on version: 1.5.6
 System: Home Assistant OS 10.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.10.1
 Home Assistant Supervisor: 2023.10.0
--------------------------------------
When navigating to the ip with port, I get nothing. Page won’t load. 
Unfortunately I don’t have a backup other than a full HA backup. 
I’ll resort to this if necessary. Happy to provide logs. I’m not seeing anything that looks weird though.
