### ISSUE TITLE
🐛 [Jellyfish NAS] port 8920 not ilstening with HTTPS

### ISSUE THREAD

**Issue by bilogic** [alexbelgium/hassio-addons#1037]
### Description

The configure shows a HTTPS port, but it isn't opened

### Reproduction steps

```bash
1. Go to any device on the network and `telnet <ip-address> 8920`
2. Expected to connect, but connection refused
```

### Addon Logs

```bash
n/a
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by alexbelgium** [comment]
Hi, have you opened the port by mapping it in the addons options and enabled https in the app?

**Comment by bilogic** [comment]
Oh there is a separate setting in the app? Let me try, never use jellyfin before. Only trying because it is so easy to install with your add on

**Comment by alexbelgium** [comment]
Well I'm not using it either, so not really sure...

The documentation is not clear : 
- Jellyfin talks about the port bind but not how to enable it : https://jellyfin.org/docs/general/networking/#port-bindings
- LSIO doesn't talk about it : https://github.com/search?q=repo%3Alinuxserver%2Fdocker-jellyfin%208920&type=code

**Comment by bilogic** [comment]
I managed to get SSL setup, but after using HTTPS, jellyfin in the sidebar doesn't load anymore. It gives a `502 bad gateway`.

**Comment by alexbelgium** [comment]
Great job! How did you do it? If you had time to give a short description it might help future users ;)

I see probably it forces jellyfin to use ssl so I need to adapt the ingress script. I'll look at it

**Comment by bilogic** [comment]
Sure, happy to. Is there a file I can directly write to?

**Comment by alexbelgium** [comment]
Thanks very much! I've put a placeholder in the Readme : https://github.com/alexbelgium/hassio-addons/blob/master/jellyfin/README.md#enable-ssl

I'll look how to customize the ingress nginx
