### ISSUE TITLE
✨ [REQUEST] Stirling-PDF

### ISSUE THREAD

**Issue by SandaleZ** [alexbelgium/hassio-addons#1038]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

https://github.com/Frooodle/Stirling-PDF?ref=noted.lol

https://hub.docker.com/r/frooodle/s-pdf 

### Is your feature request related to a problem? Please describe

Thx for your great HA Addon 

### Describe the solution you'd like

Thx for your great HA Addon

**Comment by alexbelgium** [comment]
Hi, there is a very nice one here : https://github.com/[jdeath/homeassistant-addons](https://github.com/jdeath/homeassistant-addons)

He has a great collection that complements mine I would really recommend it
