### ISSUE TITLE
🐛 [Qbittorrent] version 4.6.0 - external ip data leak with openvpn

### ISSUE THREAD

**Issue by BeachyHeadCode** [alexbelgium/hassio-addons#1049]
### Description

After this update the external ip is leaking.

### Reproduction steps

```bash
Set up openvpn and enable it. Review Qbittorrent info log and compare to external IP address.
```

### Addon Logs

```bash
No logs to provide.
```

### OS

HAos

**Comment by SoccerCore11** [comment]
I'm getting the following errors after updating to the latest QBitorrent and HA. Not sure if related.

```
[20:26:27] INFO: Starting NGinx...
nginx: [emerg] bind() to 172.30.33.3:8099 failed (98: Address in use)
2023/10/28 20:26:27 [emerg] 2162#2162: bind() to 172.30.33.3:8099 failed (98: Address in use)
2023/10/28 20:26:27 [emerg] 2162#2162: bind() to 172.30.33.3:8099 failed (98: Address in use)
nginx: [emerg] bind() to 172.30.33.3:8099 failed (98: Address in use)
[28/Oct/2023:20:26:28 -0400] 404 192.168.50.19, 172.30.32.1(172.30.32.2) POST /api/v2/search/results HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0)
2023/10/28 20:26:27 [emerg] 2162#2162: bind() to 172.30.33.3:8099 failed (98: Address in use)
nginx: [emerg] bind() to 172.30.33.3:8099 failed (98: Address in use)
2023/10/28 20:26:27 [emerg] 2162#2162: bind() to 172.30.33.3:8099 failed (98: Address in use)
nginx: [emerg] bind() to 172.30.33.3:8099 failed (98: Address in use)
```

**Comment by alexbelgium** [comment]
Could you please post the full startup log, it is much more complicated to help otherwise. I've also reverted the previous version for the moment. Thanks

**Comment by alexbelgium** [comment]
> Downgrading the app now has an error for the open vpn:
> 
> ```
> 
> [migrations] started
> [migrations] no migrations found
> 
> -----------------------------------------------------------
>  Add-on: Qbittorrent
>  qBittorrent is a bittorrent client
> -----------------------------------------------------------
> ───────────────────────────────────────
> 
>       ██╗     ███████╗██╗ ██████╗ 
>       ██║     ██╔════╝██║██╔═══██╗
>       ██║     ███████╗██║██║   ██║
>       ██║     ╚════██║██║██║   ██║
>       ███████╗███████║██║╚██████╔╝
>       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
> 
>    Brought to you by linuxserver.io
> ───────────────────────────────────────
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> 
> User UID:    ****
> User GID:    ****
> ───────────────────────────────────────
> 
>  Add-on version: 4.5.5
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 11.1  (aarch64 / yellow)
>  Home Assistant Core: 2023.10.5
>  Home Assistant Supervisor: 2023.10.1
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums
> -----------------------------------------------------------
>  Provided by: https://github.com/alexbelgium/hassio-addons 
> -----------------------------------------------------------
>  Defining permissions for main user : 
> User UID: ****
> User GID : ****
> -----------------------------------------------------------
> Local Disks mounting...
> [09:51:43] INFO: Mounting sda1 of type ext4
> [09:51:44] INFO: Execute /config/addons_autoscripts/qbittorrent.sh if existing
> [09:51:44] INFO: ... no script found
> [09:51:45] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
> [09:51:46] INFO: Downloads can be found in /media/downloads
> [09:51:47] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
> [09:51:47] INFO: WEBUI username set to admin
> [09:51:47] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
> [09:51:48] INFO: Default username/password : admin/adminadmin
> [09:51:48] INFO: Configuration can be found in /config/addons_config/qBittorrent
> [09:51:49] INFO: Configuring openvpn
> [09:51:49] INFO: openvpn correctly set, qbittorrent will run tunnelled through openvpn
> Using interface binding in the qBittorrent app
> ... deleting previous interface settings
> ... binding tun0 interface in qBittorrent configuration
> /etc/cont-init.d/93-openvpn.sh: line 89: 8
> 52: syntax error in expression (error token is "52")
> cont-init: warning: some scripts exited nonzero
> s6-rc: warning: unable to start service legacy-cont-init: command exited 1
> /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
> /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
> ```

It is the exact same add-on as before as it did not rebuild, so the issue would be due to the ha update. I'll check

**Comment by EtienneMD** [comment]
Can confirm I am having the exact same issue on reversion. The update to 4.6 must have messed with the add-on or openvpn config files. Will have a look if I get a chance next week if not fixed by then.

**Comment by EtienneMD** [comment]
Issue lies in the qBittorrent.conf file, probably in the proxy section. If you have a backup of your config, this file should be included. Either do a full config restore or extract the necessary file from the backup and overwrite the faulty config.

**Comment by alexbelgium** [comment]
I've corrected this error in the latest version. However, the VPN seems to work : qbittorrent is channeled through openvpn, and the ip in the log shows that the vpn is working. I did have however to update the config file I'm using. So please try to update to the latest version (5.6.0_WITHOUT_VPN), and paste a full log after startup in case of issue. Thanks

**Comment by alexbelgium** [comment]
That's strange, for me it starts normally. This message is usually when the system is shutting down while still trying to raise s6 services I think. What is the log just before this message? Thane

**Comment by alexbelgium** [comment]
Hi, I don't understand your message. I've just updated qbittorrent, and here is my log using freevpn. This last line is especially important as it shows the ip in tun0. The script also checks that your normal ip is different than the one from tun0. That's why the log is important, as it is not possible to identify issues wihtout it.

```
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
 Add-on version: 4.6.0-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.5
 Home Assistant Supervisor: 2023.10.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-folders.sh: executing
/etc/cont-init.d/00-global_var.sh: executing
DNS_server='8.8.8.8,1.1.1.1'
PGID='0'
PUID='0'
SavePath='/mnt/NAS/downloads'
Username='XXXXXXXXXXXXXXXXXXX'
certfile='fullchain.pem'
cifspassword='XXXXXXXXXXXXXXXXXXX'
cifsusername='XXXXXXXXXXXXXXXXXXX'
customUI='vuetorrent'
keyfile='privkey.pem'
localdisks='NAS'
openvpn_config='file.ovpn'
openvpn_enabled='true'
openvpn_password='959050202'
openvpn_username='freeopenvpn'
ssl='false'
whitelist='XXXXXXXXXXXXXXXXXXX'
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-local_mounts.sh: executing
---------------------------------------------------
[13:13:17] INFO: Available Disks for mounting :
NAME        LABEL    SIZE FSTYPE RO
└─sda1      XXXXXXXXXXXXXXXXXXX1.8T ext4    0
└─sdb1      XXXXXXXXXXXXXXXXXXX1.8T ext4    0
---------------------------------------------------
Supported fs :  ext3 ext2 ext4 squashfs vfat msdos f2fs fuseblk ntfs3 exfat btrfs xfs
Inspired from : github.com/dianlight
---------------------------------------------------
Local Disks mounting...
... NAS is a device by label
[13:13:17] INFO: Mounting NAS of type ext4
[13:13:17] INFO: Success! NAS mounted to /mnt/NAS
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Load environment variables from /config/addons_config/qbittorrent/config.yaml if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/addons_autoscripts/qbittorrent.sh if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
... no script found, exiting
/etc/cont-init.d/30-nginx.sh: executing
/etc/cont-init.d/90-dns_set.sh: executing
[13:13:19] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
/etc/cont-init.d/91-qbittorrent_configuration.sh: executing
[13:13:19] INFO: Downloads can be found in /mnt/NAS/downloads
[13:13:19] INFO: Whitelisted subsets will not require a password : XXXXXXXXXXXXXXXXXXX
[13:13:19] INFO: WEBUI username set to admin
[13:13:19] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
[13:13:21] INFO: Default username/password : admin/adminadmin
[13:13:21] INFO: Configuration can be found in /config/addons_config/qBittorrent
/etc/cont-init.d/93-openvpn.sh: executing
[13:13:21] INFO: Configuring openvpn
[13:13:22] INFO: openvpn correctly set, qbittorrent will run tunnelled through openvpn
Using interface binding in the qBittorrent app
... deleting previous interface settings
... binding tun0 interface in qBittorrent configuration
... adding route-nopull to your config.ovpn
 
Starting the upstream container
 
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

[custom-init] No custom files found, skipping...
2023-11-01 13:13:23 OpenVPN 2.6.6 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
2023-11-01 13:13:23 library versions: OpenSSL 3.1.4 24 Oct 2023, LZO 2.10
2023-11-01 13:13:23 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-11-01 13:13:23 TCP/UDP: Preserving recently used remote address: [AF_INET]XXXXXXXXXXXXXXXXXXX
2023-11-01 13:13:23 Attempting to establish TCP connection with [AF_INET]XXXXXXXXXXXXXXXXXXX
2023-11-01 13:13:23 TCP connection established with [AF_INET]XXXXXXXXXXXXXXXXXXX
2023-11-01 13:13:23 TCPv4_CLIENT link local: (not bound)
2023-11-01 13:13:23 TCPv4_CLIENT link remote: [AF_INET]XXXXXXXXXXXXXXXXXXX
2023-11-01 13:13:23 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2023-11-01 13:13:23 VERIFY OK: depth=1, O=64fb4adcd10e761180851414, CN=64fb4adcd10e761180851418
2023-11-01 13:13:23 NOTE: --mute triggered...
2023-11-01 13:13:24 6 variation(s) on previous 3 message(s) suppressed by --mute
2023-11-01 13:13:24 [64fb4aded10e761180851426] Peer Connection Initiated with [AF_INET]XXXXXXXXXXXXXXXXXXX
2023-11-01 13:13:36 Options error: option 'redirect-gateway' cannot be used in this context ([PUSH-OPTIONS])
2023-11-01 13:13:36 NOTE: --mute triggered...
2023-11-01 13:13:36 1 variation(s) on previous 3 message(s) suppressed by --mute
2023-11-01 13:13:36 TUN/TAP device tun0 opened
2023-11-01 13:13:36 /sbin/ip link set dev tun0 up mtu 1500
2023-11-01 13:13:36 /sbin/ip link set dev tun0 up
2023-11-01 13:13:36 /sbin/ip addr add dev tun0 XXXXXXXXXXXXXXXXXXX
2023-11-01 13:13:36 /etc/openvpn/up.sh tun0 1500 0 XXXXXXXXXXXXXXXXXXX 255.255.255.0 init
2023-11-01 13:13:36 Initialization Sequence Completed
2023-11-01 13:13:36 Data Channel: cipher 'AES-128-GCM', peer-id: 0, compression: 'stub'
2023-11-01 13:13:36 NOTE: --mute triggered...
WebUI will be started shortly after internal preparations. Please wait...
Connection to localhost (127.0.0.1) 8080 port [tcp/http-alt] succeeded!
[ls.io-init] done.
[13:13:37] INFO: Starting NGinx...
[13:13:38] INFO: VPN is up and running with ip 185.154.12.64, based in country : NL
```

**Comment by SoccerCore11** [comment]
It's working fine for me now with 4.6.0-2. 
@BeachyHeadCode you might want to enable "anonymous mode" and specify a specific network adapter (for me 'tun0') within your qBittorrent settings so that if the VPN fails, it doesn't fall back to your ISP connection.

**Comment by alexbelgium** [comment]
Strange. Honestly I would recommend that you either restore an older backup and update, or just remove all data and reinstall a clean version (which means uninstalling the addon and deleting the folder /config/addons_config/qbittorrent). The addon should not be able to run without executing the banners & other visual text in the logs which should take at least 10-30 seconds to run
