### ISSUE TITLE
🐛 [calibre-web] Cannot login

### ISSUE THREAD

**Issue by klassm** [alexbelgium/hassio-addons#1050]
### Description

For some reason the login is no longer possible - the login button does not do anything. This used to work in a version before the most recent one - however, already there I had issues on Android. Now it seems to be consistently not working -.-

### Reproduction steps

```bash
1. Go to 'calibre-web'
2. Try to login
3. The login never succeeds, it does not seem to react when clicking on the login button

Looking at the dev console, I have a pending request on
`https://***/api/hassio_ingress/.../login?next=%2Fapi%2Fhassio_ingress%...` - which eventually gets a 504 gateway timeout.
```

### Addon Logs

```bash
2023/10/29 14:07:23 [error] 1633#1633: *135 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.30.32.2, server: db21ed7f-calibre-web, request: "POST /login?next=/api/hassio_ingress/eFAUr7jcvkoex4NjjHOZQiEwfHe1-CcHG45FOwXYQso/ HTTP/1.1", upstream: "http://127.0.0.1:8083/login?next=/api/hassio_ingress/eFAUr7jcvkoex4NjjHOZQiEwfHe1-CcHG45FOwXYQso/", host: "*", referrer: "https://*/api/hassio_ingress/eFAUr7jcvkoex4NjjHOZQiEwfHe1-CcHG45FOwXYQso/login?next=%2Fapi%2Fhassio_ingress%2FeFAUr7jcvkoex4NjjHOZQiEwfHe1-CcHG45FOwXYQso%2F"
[29/Oct/2023:14:07:23 +0100] 504 193.30.133.7, 172.30.33.3, 172.30.32.1(172.30.32.2) POST /login?next=/api/hassio_ingress/eFAUr7jcvkoex4NjjHOZQiEwfHe1-CcHG45FOwXYQso/ HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
```

### Architecture

armv7

### OS

HAos

**Comment by klassm** [comment]
Opening the web interface directly (e.g. $IP:8083), I can successfully login. So it seems to be something with the HAS addon ingress...

**Comment by klassm** [comment]
Looking at the logs and playing around with curl, it somehow tries to post the login to http://127.0.0.1:8083/login?next=/api/hassio_ingress/BsY4lc-R3XWKITT9ZrilPgaA9Pq7iFtdhOj1u0UYaFA/ - which fails, as the addon actually runs on port 8084.

**Comment by klassm** [comment]
It works when replacing the proxy config to
proxy_set_header Connection $http_connection;
PR incoming.

**Comment by alexbelgium** [comment]
Thanks very much! I have much less time for add-ons that I don't use for the moment and really appreciate that you found the solution
