### ISSUE TITLE
🐛 [Calibre Can't startup/ memory leak

### ISSUE THREAD

**Issue by JeffersonBledsoe** [alexbelgium/hassio-addons#1052]
### Description

After upgrading from the previous latest to the latest version of Calibre, I can no longer start the app. Additionally, the error seems to cause a memory leak, leading to the restarting of my device.

### Reproduction steps

```bash
1. Start up addon
2. Wait for initialising process to get part of the way through
```

### Addon Logs

```bash
Obt-Message: Xinerama extension is not present on the server
time="2023-10-30T02:39:00.835591659Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
failed to start daemon: Devices cgroup isn't mounted
time="2023-10-30T02:39:10.942190935Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
failed to start daemon: Devices cgroup isn't mounted
```
```


### Architecture

armv7

### OS

HAos

**Comment by klassm** [comment]
When directly opening the Calibre url in the browser (e.g. $IP:8083) the login works (for some reason). So it really seems to be related to the plugin / ingress config.

**Comment by alexbelgium** [comment]
Should be good in latest version pushed I've tested on my system

**Comment by JeffersonBledsoe** [comment]
Thanks for looking at this so quickly! I'm not getting the error noted in the issue anymore. I'll close this as completed for now and re-open if I see any more errors/ memory problems over time
