### ISSUE TITLE
🐛 [Sonarr/Radarr] Blank screen after setting up Forced Authentication

### ISSUE THREAD

**Issue by antonio1475** [alexbelgium/hassio-addons#1054]
### Description

With Sonarr v4 and Radarr v5, Forced Authentication was enabled.

> https://wiki.servarr.com/sonarr/faq-v4#forced-authentication
> https://wiki.servarr.com/radarr/faq#forced-authentication

After setting this up in any of the options, Sonarr/Radarr displays a blank screen or connection error (127.0.0.1 Refused to connect). I don't know if this is an Ingress thing or something else.
These addons were updated to v4 & v5 during October. 

Setting AuthenticationMethod to None in config.xml made the WebUI to show again, but you're forced to set up Authentication again. **The only workaround was to set it to External via config.xml, but I don't think it's the right option.**

### Reproduction steps

```bash
1. Update Sonarr or Radarr
2. Open addon's WebUI
3. Set up Authentication (you're forced to)
4. Refresh the page or exit, open WebUI again, either via local address or external domain
5. See blank screen
```

### Addon Logs

```bash
Logs didn't indicate anything out of the ordinary, and I didn't copy them.
I can reproduce the whole thing to get logs if you cannot reproduce it.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, thanks for sharing. Actually is "external" is such a bad idea ? I mean when we connect with ingress the authentification is indeed managed externally by HA itself ?

**Comment by antonio1475** [comment]
> Hi, thanks for sharing. Actually is "external" is such a bad idea ? I mean when we connect with ingress the authentification is indeed managed externally by HA itself ?

You're most likely right. The documentation and forums mention External being an advanced thing, but of course don't have HA in mind, which covers external authentication...

However, please note that **External is not an option in the Sonarr/Radarr UI and can only be set by manually** editing the config/addons_config/sonarrconfig.xml and restarting the addon.

So, **potentially, anyone who updates your Sonarr/Radarr/xxxrr addons will be forced to set an Authentication Method and after that, the addons won't "open" in any way**. Unless it was just me, because interestingly, Prowlarr which doesn't have Ingress (https://github.com/alexbelgium/hassio-addons/issues/879) seems to work with Authentication enabled. 😅

**Comment by alexbelgium** [comment]
Hi, well actually I've implemented the automatic setting of the "external" option that disables authentification. For people who needs authentification, they should disable ingress through a specific setting in the addon options. A big disclaimer in the log should hopefully make that explicit for users. I'm testing it currently

**Comment by antonio1475** [comment]
Awesome! Thank you.
I guess I'll close the issue since the update is out, although I haven't tested it personally since I already had manually set it to External. 😄
