### ISSUE TITLE
✨ [REQUEST] ChangeDetection.io WEBDRIVER_URL environment variable

### ISSUE THREAD

**Issue by Kokbo** [alexbelgium/hassio-addons#1057]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

ChangeDetection.io

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

ChangeDetection.io has the capability to use watch JavaScript changes. For this to function, you need to give it a URL of a network connection that is running a WebDriver+Chrome server. Normally, this can be done by setting 'WEBDRIVER_URL' var in the docker environment variables, but it would be nice to be able to enter this URL in the add-on's configuration options (same BASE_URL, TZ, etc).

**Comment by alexbelgium** [comment]
Hi, you can add any ENV variables that you want to my addons by following this guide : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables

Hope this helps

**Comment by Kokbo** [comment]
Thanks, didn't know this feature.

**Comment by alexbelgium** [comment]
Please let me know if it worked - but indeed I had implemented it for users flexibility and to avoid to many options in addons

**Comment by Kokbo** [comment]
Doesn't seem to recognize the environment variable:

`/etc/cont-init.d/01-custom_script.sh: executing
[11:03:53] INFO: Execute /config/addons_autoscripts/changedetection.io.sh if existing
[11:03:53] INFO: ... script found, executing
/./config/addons_autoscripts/changedetection.io.sh: line 1: WEBDRIVER_URL:: command not found
Error : /etc/cont-init.d/01-custom_script.sh exiting 127`

Just checked the LinuxServer image, but it seems the environment variable isn't available.

**Comment by alexbelgium** [comment]
Yup, I made a mistake : actually the path is"/config/addons_config/$slug/config.yaml"

So inside this file you should have : 
```yaml
WEBDRIVER_URL: "url"
```

**Comment by Kokbo** [comment]
Now it doesn't find the yaml.

[11:27:15] INFO: Execute /config/addons_autoscripts/changedetection.io.sh if existing
[11:27:15] INFO: ... no script found

I've put the env var in  /config/addons_config/changedetection.io/config.yaml.

If I look in 01-custom_script.sh, it says it looks for it in /config/addons_autoscripts/"${slug}".sh. Also tried it there but then i get the same error as before (/./config/addons_autoscripts/changedetection.io.sh: line 1: WEBDRIVER_URL:: command not found
Error : /etc/cont-init.d/01-custom_script.sh exiting 127).

**Comment by alexbelgium** [comment]
Actually the correct script that would be used is 01-config_yaml.sh (01-custom_script.sh is used to execute custom scripts). If the first script is not there probably i'll need to push a new version as it would mean this script was not added at time of creation

**Comment by Kokbo** [comment]
Yeah there's no config.yaml in /config/addons_config/changedetection.io/

**Comment by alexbelgium** [comment]
I've launched a new build to include my latest scripts. It should now run the "01-config_yaml.sh" script that will go read the config.yaml file that you need to create manually in the folder /config/addons_config/changedetection.io/

Sorry for that I have too much addons and I don't use 80% of them so they can have different level of versions of my base scripts

**Comment by Kokbo** [comment]
Thanks Alexbelgium for the prompt replies and fix! Cheers!
