### ISSUE TITLE
Request - Arpspoof

### ISSUE THREAD

**Issue by gieljnssns** [alexbelgium/hassio-addons#106]
If you have some time, can you make an addon of this arpspoof container?
https://github.com/t0mer/Arpspoof-Docker
I have now installed this container through the portainer addon, but now I have an unsupported installation since I use HAOS.

https://community.home-assistant.io/t/cut-internet-temporarily-in-a-device-in-your-lan/20000/64

**Comment by alexbelgium** [comment]
Hi, I pushed a first version of the addon. I'm not sure what the ENV variables should be, but I added them as addon options. I would be very interested in your feedback!

**Comment by alexbelgium** [comment]
could you please add more details about the ENV variables ? as perhaps we could make their filling automatic if it is things like the HA ip or the HA network device

**Comment by gieljnssns** [comment]
Thanks a lot.
I've installed your addon, stopped  the old container and I can still bock my daughters phone from internet.

**Comment by alexbelgium** [comment]
And I suppose that blocking your daughter phone from internet was the expected outcome ;-)
Did you install the version with autodiscovery of the INTERFACE_NAME, or did you type it manually ? I just pushed the code

**Comment by gieljnssns** [comment]
<img width="905" alt="Schermafbeelding 2021-12-07 om 15 44 26" src="https://user-images.githubusercontent.com/17234951/145050225-081b1a52-251c-4215-a40f-a1e0e3dafa27.png">

I've filled in the same as I did in container with portainer

<img width="1061" alt="Schermafbeelding 2021-12-07 om 15 45 47" src="https://user-images.githubusercontent.com/17234951/145050570-5574a70c-be74-45e5-a323-f2b031006df2.png">

**Comment by gieljnssns** [comment]
Did it manual

**Comment by alexbelgium** [comment]
Perfect, thanks. I'll just add an option in the next version to autofill the interface name, if that can help some people. Enjoy!

**Comment by Stooovie** [comment]
How do I enter multiple devices that I'd like to block? Thanks.

**Comment by gieljnssns** [comment]
I have this file
https://github.com/gieljnssns/My-Hassio-config/blob/master/config/devices/switch/internet_acces_kids.yaml

**Comment by gieljnssns** [comment]
I have this file
https://github.com/gieljnssns/My-Hassio-config/blob/master/config/devices/switch/internet_acces_kids.yaml

**Comment by Stooovie** [comment]
Thanks. I see you used to use Adguard Home for this purpose, is Arpspoof more reliable? I'm asking because it's very intermittent for me, connections usually ultimately break through the kill switch at some point.
