### ISSUE TITLE
✨ [REQUEST] Upgrade QBitorrent to use VueTorrent 2.0.0

### ISSUE THREAD

**Issue by bilogic** [alexbelgium/hassio-addons#1064]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

QBitorrent

### Is your feature request related to a problem? Please describe

Dark/light mode does not follow OS

### Describe the solution you'd like

Upgrade VueTorrent to 2.0.0 for auto dark/light mode https://github.com/WDaan/VueTorrent/issues/1261

**Comment by alexbelgium** [comment]
Mmh I wonder if auto mode works in docker! I can try but just afraid of breaking things ;)

**Comment by alexbelgium** [comment]
Implemented

**Comment by bilogic** [comment]
thanks!

**Comment by bilogic** [comment]
for some reason, magnet don't open in QBitorrent anymore both on Windows and Mac.
