### ISSUE TITLE
✨ [REQUEST] Firefly: ingress support 

### ISSUE THREAD

**Issue by SrPeterr** [alexbelgium/hassio-addons#1065]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

[fireflyiii](https://github.com/alexbelgium/hassio-addons/tree/master/fireflyiii)

### Is your feature request related to a problem? Please describe

Not a problem, new feature

### Describe the solution you'd like

Hi!
Will it be possible to add ingress support? 
I would love to add it to my sidebar, Im using SSL so right now its a bit of a problem :(

**Comment by financelurker** [comment]
I'd also love if that AddOn would use the ssl certificate provided by the Let's Encrypt AddOn so I could connect to it through https and not have it's unencrypted http port exposed...

**Comment by financelurker** [comment]
And I guess this is a duplicate to https://github.com/alexbelgium/hassio-addons/issues/425 ?

**Comment by alexbelgium** [comment]
> I'd also love if that AddOn would use the ssl certificate provided by the Let's Encrypt AddOn so I could connect to it through https and not have it's unencrypted http port exposed...

Hi, this is a different request but actually the recommended way to use ssl is through an addon named nginx proxy manager that manages it in a global way and not addon per addon. Here is a very short non tested wiki on that, don't hesitate to complete it if it works ;-) https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-ssl

**Comment by alexbelgium** [comment]
Indeed, thanks I'll close it. Indeed there is low probability that firefly supports ingress due to embedded security features that are not compatible with the way the ingress proxy works
