### ISSUE TITLE
✨ [REQUEST] Support HACS

### ISSUE THREAD

**Issue by pohly** [alexbelgium/hassio-addons#1066]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

I am interested in your Tandoor integration as I have Tandoor already installed on the same machine as HomeAssistant. When I checked how to enable your repo, I found that it doesn't seem to work with my install method (containers inside podman, managed by systemd).

I am using [HACS](https://hacs.xyz/) to manage additional add-ons for HomeAssistant. Have you considered supporting that? See https://hacs.xyz/docs/publisher.

### Is your feature request related to a problem? Please describe

Need Home Assistant OS or supervised installation to use this repository.

### Describe the solution you'd like

Support HACS.

**Comment by alexbelgium** [comment]
Hi, hacs is for integrations, it does not support add-ons. Sorry. Best way for you is to manually install the add-ons if you didn't use HA but i'm pretty all add-ons wil not be compatible
