### ISSUE TITLE
✨ [REQUEST] Upgrade QBitorrent

### ISSUE THREAD

**Issue by bilogic** [alexbelgium/hassio-addons#1067]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

QBittorrent

### Is your feature request related to a problem? Please describe

Yes, reported 2 bugs

https://github.com/WDaan/VueTorrent/issues/1291
https://github.com/WDaan/VueTorrent/issues/1292

### Describe the solution you'd like

Update image to include these fixes

https://github.com/WDaan/VueTorrent/issues/1293
https://github.com/WDaan/VueTorrent/issues/1294

**Comment by alexbelgium** [comment]
Hi, vuetorrent I updated upon add-on restart

**Comment by bilogic** [comment]
Ah great thanks!
