### ISSUE TITLE
🐛 [Flexget] Not getting updated

### ISSUE THREAD

**Issue by DDanii** [alexbelgium/hassio-addons#1071]
### Description

Auto updater didn't updated Flexget in last 5 months.

### Reproduction steps

```bash
The updater updated it to a strange version number, but I don't see why It is a problem for it.
```

### Addon Logs

```bash
I don't have those :D
```

**Comment by DDanii** [comment]
It looks like fixed, thank you

**Comment by alexbelgium** [comment]
Thanks, I corrected the updater json file
