### ISSUE TITLE
✨ [REQUEST] New Addon - SignalK 

### ISSUE THREAD

**Issue by tingles2233** [alexbelgium/hassio-addons#1075]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Addon is for SignalK

Website: http://signalk.org/

SignalK is centric around a common boat/yacht communications protocol. 

Interest: 
There have been numerous threads on other forums asking for this to become an addon. Here are some of the threads. 

Current State: 
SignalK can be installed directly on linux/arm
SignalK already has a formal docker image(perhaps will help with addon creation?) 
SignalK has connectors already built on it to transfer data into HA entities/sensors etc via MQTT this works great, however you still need signalk to be a mediator, and because it does not run as an addon on HASS it requires an additional device running signalk. 

Links: 

Docker Image: 
https://github.com/SignalK/signalk-server/tree/master/docker 
https://hub.docker.com/r/signalk/signalk-server/tags

GitHub Project: 
https://github.com/SignalK/signalk-server/tree/master/

Interest from others asking for this to be an addon:
https://community.home-assistant.io/t/connecting-to-signalk-server-marine-data-exchange-format/246391
https://community.home-assistant.io/t/homeassistant-integrations-for-a-boat/378857
https://community.home-assistant.io/t/nmea-2000-to-ha/84134
https://community.home-assistant.io/t/bridging-signalk-server-nmea-and-home-assistant-using-signalk-mqtt-bridge-and-mosquitto-mqtt/642640

### Is your feature request related to a problem? Please describe

The problem is that signalk is used by many individuals who have boats and it is the only software opensource to my knowledge that converts/reads NEMA2000 communications protocols and can convert it into other formats for general use such as with Node Red/MQTT/HA.  

See above on more details about the problem. 

### Describe the solution you'd like

I would like signalk to be an HASS Addon so that I and many others can stop running additional devices just to run signalk with home assistant. 

I feel it should be an "easy" (IMO, but limited HASS programing knowledge on my end) to take the existing docker setup and modify it where/as needed to make it usable by HASS as an addon. 

I would be willing to also work and maintain this with some guidance to help spread the load in the long run on maintaining it.

**Comment by alexbelgium** [comment]
Hi, first build pushed!

**Comment by tingles2233** [comment]
Awesome! Kick ass! 

Installed seemed to go well. Will do some testing on functionality over the next 24-48 hours and report back.

**Comment by tingles2233** [comment]
Did some testing this evening, all is working well except... 

When installing an addon within Signalk it reboots following installation, HA is I believe detecting this as the Addon has stopped and killing the container/marking it as stopped?

Here is the log from within the Addon (There is nothing mentioned in supervisor logs about it): 

`Settings file does not exist, using empty settings
Could not parse security config
ENOENT: no such file or directory, open '/home/node/.signalk/security.json'
Could not parse security config
ENOENT: no such file or directory, open '/home/node/.signalk/security.json'
Could not parse security config
ENOENT: no such file or directory, open '/home/node/.signalk/security.json'
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
signalk-server running at 0.0.0.0:3000

GET /admin/ 200 19.578 ms - 562
GET /admin/main.js 304 8.315 ms - -
GET /@signalk/vesselpositions/remoteEntry.js 304 38.257 ms - -
GET /admin/79.js 304 8.610 ms - -
GET /admin/784.js 304 9.089 ms - -
GET /admin/316.js 304 4.857 ms - -
GET /admin/270.js 304 4.808 ms - -
GET /skServer/plugins 401 4.789 ms - 91
GET /skServer/loginStatus 200 2.065 ms - 183
GET /skServer/security/access/requests 401 2.055 ms - 91
GET /skServer/addons 304 39.601 ms - -
GET /admin/fonts/Simple-Line-Icons.3826fa1cb2348dd93948a50cbd2b8fb6.woff2 304 31.049 ms - -
GET /skServer/appstore/available 401 2.010 ms - 91
GET /signalk 304 7.351 ms - -
GET /admin/fonts/fa-solid-900.1551f4f60c37af51121f106501f69b80.woff2 304 7.501 ms - -
GET /skServer/webapps 200 38.287 ms - -
GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 304 6.722 ms - -
GET /admin/img/favicon.ico 304 3.760 ms - -
POST /skServer/enableSecurity 200 259.452 ms - 16
GET /skServer/loginStatus 200 2.205 ms - 167
GET /admin/img/favicon.ico 304 4.502 ms - -
GET /admin/ 200 3.134 ms - 562
GET /admin/main.js 304 2.416 ms - -
GET /@signalk/vesselpositions/remoteEntry.js 304 6.898 ms - -
GET /admin/79.js 304 9.931 ms - -
GET /admin/784.js 304 7.144 ms - -
GET /admin/316.js 304 2.152 ms - -
GET /admin/270.js 304 2.182 ms - -
GET /skServer/plugins 401 3.335 ms - 91
GET /skServer/webapps 304 11.557 ms - -
GET /skServer/addons 304 14.603 ms - -
GET /admin/fonts/Simple-Line-Icons.3826fa1cb2348dd93948a50cbd2b8fb6.woff2 304 11.220 ms - -
GET /skServer/appstore/available 401 2.198 ms - 91
GET /skServer/loginStatus 200 1.897 ms - 167
GET /signalk 304 17.431 ms - -
GET /skServer/security/access/requests 401 1.637 ms - 91
GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 304 1.708 ms - -
GET /admin/fonts/fa-solid-900.1551f4f60c37af51121f106501f69b80.woff2 304 1.664 ms - -
GET /admin/img/favicon.ico 304 2.240 ms - -
POST /signalk/v1/auth/login 200 240.827 ms - 157
GET /skServer/plugins 304 32.851 ms - -
GET /skServer/security/access/requests 304 9.131 ms - -
GET /skServer/loginStatus 200 7.749 ms - 203
GET /skServer/addons 304 76.725 ms - -
GET /skServer/webapps 304 74.279 ms - -
GET /signalk 304 69.418 ms - -
GET /admin/img/favicon.ico 304 11.064 ms - -
GET /skServer/appstore/available 200 1307.970 ms - -
POST /skServer/appstore/install/@meri-imperiumi/signalk-logbook/0.7.0 200 880.712 ms - 45
stdout: 
added 15 packages, and audited 16 packages in 6s

stdout: 
found 0 vulnerabilities

stderr: npm
stderr:  notice 
npm notice New patch version of npm available! 10.2.3 -> 10.2.4
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
npm notice Run `npm install -g npm@10.2.4` to update!
npm notice 

POST /skServer/appstore/install/@signalk/signalk-node-red/3.0.2 200 804.382 ms - 39
stdout: 
added 302 packages, and audited 318 packages in 55s

stdout: 
44 packages are looking for funding
  run `npm fund` for details

stdout: 
11 vulnerabilities (2 low, 9 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

PUT /skServer/restart 200 11.091 ms - 13
 
Starting the upstream container
 `

That is the end of the log and the addon in HA is marked as stopped ready to be started. 

Starting the addon in HA does boot up as expected. 

Can we stop HA from marking it as stopped?

**Comment by alexbelgium** [comment]
That's strange, I can't replicate. I can install plugins very well. Example of installation

´´´
GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 304 10.702 ms - -
GET /skServer/security/access/requests 304 7.901 ms - -
GET /admin/fonts/fa-solid-900.1551f4f60c37af51121f106501f69b80.woff2 304 4.535 ms - -
GET /admin/img/favicon.ico 304 23.334 ms - -
GET /skServer/appstore/available 200 1428.298 ms - -
POST /skServer/appstore/install/@signalk/aisreporter/1.1.0 200 903.161 ms - 34
stdout: 
added 4 packages, and audited 5 packages in 5s

stdout: 
found 0 vulnerabilities

stderr: npm
stderr:  
stderr: notice
stderr:  

stderr: npm
stderr:  
stderr: notice
stderr:  New patch version of npm available! 10.2.3 -> 10.2.4
npm
stderr:  notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
npm notice Run `npm install -g npm@10.2.4` to update!
npm notice 

GET /admin/ 200 5.557 ms - 562
GET /@signalk/vesselpositions/remoteEntry.js 304 10.356 ms - -
GET /admin/main.js 304 4.296 ms - -
GET /admin/79.js 304 13.567 ms - -
```

**Comment by mgrouch** [comment]
More discussion is here

https://github.com/SignalK/signalk-server/issues/1374

**Comment by mgrouch** [comment]
Now each SignalK path needs to be mapped to
HA sensor.
Here is a list of SignalK paths

https://github.com/bareboat-necessities/my-bareboat/blob/master/homeassistant/signalk-paths.txt

Example mapping to MQTT:

https://github.com/bareboat-necessities/my-bareboat/blob/master/homeassistant/configuration.yaml

Subscribe topic:

 +/+/#

Victron add-on can be coded similarly

**Comment by mgrouch** [comment]
Do I understand this correctly that this add-on starts SignalK inside HA infrastructure?

Thats now what I would be looking for. 

I’d need HA add-on (or something else) which would discover SignalK installations via mDNS
and map all SignalK paths to HA sensors.

And HA dashboard for sensors.

**Comment by alexbelgium** [comment]
Hi, indeed this addon starts the signalk-server container within HA ! 

I am not using it however, so not sure about integration in HA sensor. I guess you would need to create custom sensors that fetch the information from the addon url. This can't be done from the addon part : it would be the job of a custom "integration" that is managed differently in HA and that I don't know how to do.

For example, I have an addon from the scrutiny addon, but sensors had to be mapped manually through this way of working : https://github.com/alexbelgium/hassio-addons/tree/master/scrutiny#integration-in-home-assistant

**Comment by tingles2233** [comment]
Hi @alexbelgium, 

An easier way to test instead of installing an addon is when you initiate a in signalk reboot( I believe this is also triggered post addon install so same process)

To do this here are the steps. 

Log into the signalk Web portal (Port 3000)
2) Click login on the top right
2a) On first login you will be prompted to create an admin account( Example: admin/admin)
2b) Second login you will be able to log in using this admin account. 
3) Click on "Restart" in the top right corner. 
![image](https://github.com/alexbelgium/hassio-addons/assets/58663637/919e997d-fba3-45be-8278-d2a3aa98d946)

4) Upon reboot you will find that the HA addon for signalk has "stopped" and is ready to be started. 

![image](https://github.com/alexbelgium/hassio-addons/assets/58663637/5431171e-16aa-4fa4-b025-5f2e3fcd5797)


Hope this helps get you to the same spot.

**Comment by alexbelgium** [comment]
Hi, why don't you restart the addon instead of restarting the server from within? I think this is normal behavior for a docker container

**Comment by alexbelgium** [comment]
Another way could be to check the "watchdog" feature - perhaps it would try to restart the addon automatically when it detects it has stopped due to the server restart!

**Comment by tkurki** [comment]
Hi, SK server main contributor here.

The server process exiting to restart is by design. Normally it is managed by systemd or Docker that take care of starting it back up.

How does HA manage add on processes? Like if a container’s process crashes?

**Comment by alexbelgium** [comment]
Hi, nice meeting you. Actually HA uses an optional feature called the "watchdog" (disabled by default as in the screenshot above) to restart automatically an addon if it fails an healthcheck test. The only requirement is for an healthcheck to be available in the dockerfile.

What my addon is doing is globally just a shell around the official signalk-server container, with the data path modified to a remanent location within HA (/config). So the default behaviors should still apply.

**Comment by alexbelgium** [comment]
Actually this gave me an idea : I've now put an instruction to restart the addon in case of crash. Should take care of this situation by default without needing to use the watchdog !

**Comment by tingles2233** [comment]
@tkurki & @alexbelgium - Thank-you for the input and changes. 

I have updated my version to the latest published "2.4.1-3". 

Will do some further testing this evening but first impressions I do see the HA addon stop but it does restart automatically even without Watchdog enabled. 

Fingers crossed.

**Comment by tingles2233** [comment]
Sorry for the delay as I was tied up with a personal matter. 

@tkurki & @alexbelgium - Have done fairly extensive testing and all seems to be working as expected. 

@tkurki - I believe this may be for you. I have a questions in regards to upgrading SignalK in this container. I believe what home assistant will do is swap the container between versions but keep the persistent configuration and data on a separate disk. Will this cause any issues with signal k during the upgrade process. 

For example if we don`t follow the "upgrade" button within signal k and simply rebuild the container with the new version, will this cause data issues? Will Signalk detect and update/change any data schema changes automatically or will these steps be missed as it did not follow the signalk upgrade process?

Thanks in advance!

Matt

**Comment by tkurki** [comment]
The server update mechanism is not active when the server is running in Docker, simply marked by an [environment variable](https://github.com/SignalK/signalk-server/blob/f61360d67f5b7805bb9de42ab8deaa92e8d0413e/docker/Dockerfile#L37). You do get the prompt about a new version, but also a message saying _The server is running as a Docker container. You need to pull a new server version from Container registry to update_. What should that say in HA? We could introduce one more env parameter to trigger HA specific instructions.

All settings data (including installed plugins and their data) is under `/home/node/.signalk` and we have so far been backwards compatible with settings.

**Comment by alexbelgium** [comment]
Hi, thanks for the info, this seems perfectly compatible with the way of working of my add-ons : I have a script that runs each Saturday comparing the current version of the add-on with the latest version released on your repo. If there is a discrepancy, it pushes a new addon version based on whatever image has the "latest" tag. Therefore, it should always stay up to date with a latency of max 7 days.

Regarding data retention I modified the data directory to be in one of the remanent location in homeassistant (HA doesn't allow mounting specific folders as in docker) which takes care of keeping data safe in between updates and restarts

**Comment by tingles2233** [comment]
Thanks @tkurki and @alexbelgium 

That sounds like it shouldn`t be an issue. 

So far over the past two weeks with multiple reboots, changes, etc all has been working well. Appreciate the input and work from both of you. 

I think we can proceed to close this issue and I`ll update/create new one should I encounter any issues.
