### ISSUE TITLE
Paperless

### ISSUE THREAD

**Issue by Fritzandreasx** [alexbelgium/hassio-addons#1078]
### Description

with the update to 2.0.0b1-3 folder and file are deleted with startup
/config/addons_config/paperless_ng/config.yaml

couldnt find out where to store alternativ config

see log:

### Reproduction steps

```bash
1.update to paperless version 2.0.0b1-3
2. restart
3. see paperless add on logg
4. folder and config file is deleted (always)
```

### Addon Logs

```bash
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Paperless NGX
 Scan, index and archive all your physical documents
-----------------------------------------------------------
 Add-on version: 2.0.0b1-3
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/addons_config/paperless_ng/config.yaml'
OCRLANG='deu eng'
PAPERLESS_CONSUMPTION_DIR='/mnt/dokumentenverwaltung/neue_dokumente'
PAPERLESS_DATA_DIR='/mnt/dokumentenverwaltung/data'
PAPERLESS_MEDIA_ROOT='/mnt/dokumentenverwaltung/media'
PAPERLESS_OCR_MODE='skip_noarchive'
PGID='0'
PUID='0'
TZ='Berlin'
certfile='chain.pem'
cifsdomain='19***'
cifspassword='***'
cifsusername='***'
keyfile='privkey.pem'
networkdisks='//******/dokumentenverwaltung'
ssl='false'
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
[08:47:35] WARNING: ------------------------
[08:47:35] WARNING: This is a new code, please report any issues on https://github.com/alexbelgium/hassio-addons
Mounting smb share(s)...
[08:47:35] WARNING: ------------------------
... using domain ***.31
... using PUID 0 and PGID 0
... mounting //192.168.178.31/dokumentenverwaltung
[08:47:36] INFO: ... //****/dokumentenverwaltung successfully mounted to /mnt/dokumentenverwaltung with options ,uid=0,gid=0,iocharset=utf8,domain=****
/etc/cont-init.d/01-config_yaml.sh: executing


---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
PAPERLESS_OCR_LANGUAGE='eng'
PAPERLESS_OCR_MODE='skip'
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/paperless-ng.sh if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
... no script found, exiting
/etc/cont-init.d/20-migration_config.sh: executing
Migrating /homeassistant/addons_config/paperless_ng
mv: cannot stat '/homeassistant/addons_config/paperless_ng/media': No such file or directory
mv: cannot stat '/homeassistant/addons_config/paperless_ng/consume': No such file or directory
mv: cannot stat '/homeassistant/addons_config/paperless_ng/*': No such file or directory
/etc/cont-init.d/31-nginx.sh: executing
/etc/cont-init.d/99-run.sh: executing
[07:47:39] INFO: Defining variables
[07:47:45] INFO: Defining database
[07:47:45] INFO: Using sqlite as database driver
[07:47:45] INFO: Starting redis
[07:47:45] INFO: Starting nginx
592:C 20 Nov 2023 07:47:45.311 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
592:C 20 Nov 2023 07:47:45.312 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=592, just started
592:C 20 Nov 2023 07:47:45.312 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
592:M 20 Nov 2023 07:47:45.315 * monotonic clock: POSIX clock_gettime
592:M 20 Nov 2023 07:47:45.316 * Running mode=standalone, port=6379.
592:M 20 Nov 2023 07:47:45.317 # Server initialized
592:M 20 Nov 2023 07:47:45.317 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
592:M 20 Nov 2023 07:47:45.319 * Ready to accept connections
[07:47:45] INFO: Initial username and password are admin. Please change in the administration panel of the webUI after login.
 
Starting the upstream container
 
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
```

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, I've added in the changelog that HA has changed how config mounting is managed. This means that it is not using anymore the /config main folder, so all your files & data were migrated from `/config/addons_config/paperless_ng` to it's own internal `/config`.

This new `/config` folder can be accessed using my filebrowser or cloudcommander addons by going in the folder /addon_configs/xxxxx-paperless_ng

I know this is confusing but it's the new HA way of working so it's more sustainable this way...

I see that you are using externally mounted /mnt folders, which means that your data was actually not migrated. However, your config.yaml was automatically. This means that your path `CONFIG_LOCATION='/config/addons_config/paperless_ng/config.yaml'` should be changed to ``CONFIG_LOCATION='/config/config.yaml`. I'll check if I can do that automatically from within the addon code

```
MAJOR CHANGE : new HA config logic implemented. Files are now located in the addon config file, that can be accessed from the addon_configs folder from my filebrowser or cloudcommander addons. Migration of data, custom configs, and custom scripts should be automatic. Please be sure to update all your links however ! For more information, see here : https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/
```

**Comment by Fritzandreasx** [comment]
Thank you for you quick respone.
I found the config file
how can I make sure the mounts are used and the date is also used?

**Comment by alexbelgium** [comment]
Could you try setting the CONFIG_LOCATION to /config/config.yaml and check if it is now working? In parallel I'm checking on my side too. Thanks!

**Comment by Fritzandreasx** [comment]
setting the config_Location worked.

But no old data is used.
Plain new installation

integrating the mounts would be the next step.

Log:

[34mPAPERLESS_TIKA_GOTENBERG_ENDPOINT='http://**:3000'[0m
[34mPAPERLESS_FILENAME_FORMAT_REMOVE_NONE='true'[0m
[34mPAPERLESS_ADMIN_USER='***'[0m
[34mPAPERLESS_ADMIN_PASSWORD='***'[0m
[34mPAPERLESS_OCR_SKIP_ARCHIVE_FILE='always'[0m
[34mPAPERLESS_OCR_PAGES='5'[0m
[34mPAPERLESS_WORKER_TIMEOUT='3000'[0m
[34mPAPERLESS_CONSUMER_DELETE_DUPLICATES='true'[0m
[34mPAPERLESS_CONSUMER_RECURSIVE='true'[0m
[34mPAPERLESS_CONSUMER_SUBDIRS_AS_TAGS='true'[0m
[34mPAPERLESS_CONSUMER_POLLING='600'[0m
/etc/cont-init.d/01-custom_script.sh: executing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
[32mExecute /config/paperless-ng.sh if existing[0m
[32m---------------------------------------------------------[0m
[32m... no script found, exiting[0m
/etc/cont-init.d/20-migration_config.sh: executing
/etc/cont-init.d/31-nginx.sh: executing
/etc/cont-init.d/99-run.sh: executing
[10:07:18] INFO: [32mDefining variables[0m
[10:07:24] INFO: [32mDefining database[0m
[10:07:24] INFO: [32mUsing sqlite as database driver[0m
[10:07:24] INFO: [32mStarting redis[0m
[10:07:24] INFO: [32mStarting nginx[0m
682:C 20 Nov 2023 10:07:24.945 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
682:C 20 Nov 2023 10:07:24.946 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=682, just started
682:C 20 Nov 2023 10:07:24.946 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
682:M 20 Nov 2023 10:07:24.947 * monotonic clock: POSIX clock_gettime
682:M 20 Nov 2023 10:07:24.948 * Running mode=standalone, port=6379.
682:M 20 Nov 2023 10:07:24.949 # Server initialized
682:M 20 Nov 2023 10:07:24.949 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
682:M 20 Nov 2023 10:07:24.950 * Ready to accept connections
[10:07:24] INFO: [32mInitial username and password are admin. Please change in the administration panel of the webUI after login.[0m
 
[0;32mStarting the upstream container[0m
 
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Running Django checks
System check identified no issues (0 silenced).
Did not create superuser, a user admin already exists
Executing /usr/local/bin/paperless_cmd.sh
2023-11-20 10:07:33,431 INFO Set uid to user 0 succeeded
2023-11-20 10:07:33,436 INFO supervisord started with pid 1
2023-11-20 10:07:34,441 INFO spawned: 'gunicorn' with pid 771
2023-11-20 10:07:34,447 INFO spawned: 'celery' with pid 772
2023-11-20 10:07:34,454 INFO spawned: 'celery-beat' with pid 773
2023-11-20 10:07:34,465 INFO spawned: 'consumer' with pid 774
2023-11-20 10:07:34,479 INFO spawned: 'celery-flower' with pid 775
Checking if we should start flower...
2023-11-20 10:07:34,556 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Not starting flower
2023-11-20 10:07:35,566 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-11-20 10:07:35,566 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-11-20 10:07:35,567 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-11-20 10:07:35,568 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-11-20 10:07:35,568 INFO exited: celery-flower (exit status 0; expected)
[2023-11-20 09:07:39,672] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /config/consume
[2023-11-20 09:07:40 +0000] [771] [INFO] Starting gunicorn 21.2.0
[2023-11-20 09:07:40 +0000] [771] [INFO] Listening at: http://[::]:8000 (771)
[2023-11-20 09:07:40 +0000] [771] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2023-11-20 09:07:40 +0000] [771] [INFO] Server is ready. Spawning workers
[2023-11-20 09:07:40,719] [INFO] [celery.beat] beat: Starting...
 
 -------------- celery@db21ed7f-paperless-ng v5.3.1 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.1.59-x86_64-with-glibc2.36 2023-11-20 09:07:40
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         paperless:0x7fb4c61a23d0
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . documents.tasks.bulk_update_documents
  . documents.tasks.consume_file
  . documents.tasks.index_optimize
  . documents.tasks.sanity_check
  . documents.tasks.train_classifier
  . documents.tasks.update_document_archive_file
  . paperless_mail.mail.apply_mail_action
  . paperless_mail.mail.error_callback
  . paperless_mail.tasks.process_mail_accounts

[2023-11-20 09:07:41,137] [INFO] [celery.worker.consumer.connection] Connected to redis://localhost:6379//
[2023-11-20 09:07:41,189] [INFO] [celery.apps.worker] celery@db21ed7f-paperless-ng ready.

**Comment by Fritzandreasx** [comment]
tika and Gotenberg are also not working
I roled back to previus version untill there is a solution.

**Comment by alexbelgium** [comment]
> tika and Gotenberg are also not working I roled back to previus version untill there is a solution.

was it internal TIKA and Gotenberg or it was a reference to external services ? It seems the new docker image only supports external services : https://docs.paperless-ngx.com/configuration/#tika

**Comment by Fritzandreasx** [comment]
Hi,

Tika and Gotenberg run in Docker on synology. In 2 seperate Containers.
No changes made there.
I just defined the acces points.

Alexandre ***@***.***> schrieb am Mo. 20. Nov. 2023 um 16:53:

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version everything should work now! And I've tested creating a new account on a mounted local drive.

For Tika and Gotenberg you should go with my addon Filebrowser in the folder /addon_configs/db21ed7f_paperless_ng, open the file config.yaml, and add inside :

```
#============================#
# ALEXBELGIUM'S ENV INJECTOR #
#============================#
#
# All env variables set in this file will be enabled in the app
# This allows enabling more options that normally available in the addon options
# This file must be filled according to the yaml format. If the format is invalid, the addon will note an error. To validate your yaml, you can use the free online tool http://www.yamllint.com/

# EXAMPLE of the format (you need to remove the # for it to become active)
# TZ: Europe/Paris
PAPERLESS_TIKA_ENABLED: true
PAPERLESS_TIKA_ENDPOINT: "yoururl:port"
PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "yoururl:port"
PAPERLESS_OCR_LANGUAGE: eng
PAPERLESS_OCR_MODE: skip

```

**Comment by Fritzandreasx** [comment]
HI,

all up and working with the new version.

Thank you for your work.

kind regards

Andreas Fritz

Am Di., 21. Nov. 2023 um 12:58 Uhr schrieb Alexandre <
***@***.***>:
