### ISSUE TITLE
🐛 [JellyFin] Latest build has an invalid manifest 

### ISSUE THREAD

**Issue by fliphess** [alexbelgium/hassio-addons#1082]
### Description

Hey Alex! 

I think the latest release of the JellyFin addon has a failed build or a failed push to the registry. 
Both when installing in Hass, or when testing on the cli, I get an invalid manifest error. 

### Reproduction steps

See: 
```
docker pull ghcr.io/alexbelgium/jellyfin-amd64:10.8.12-4
```

Which returns:
```
Error response from daemon: manifest unknown
```

Testing which tags exist in the registry, show the `-4` tag is not present (yet): 

```
$ skopeo list-tags docker://ghcr.io/alexbelgium/jellyfin-amd64 | grep 10.8.12
        "10.8.12",
        "10.8.12-2"
```

I've checked the pipelines that ran in the last few hours and didn't see anything building the new tag for JellyFin, so I think the pipeline never ran.

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks! Actually I had a major mess up today and reset the github HEAD at a previous commit losing one month of data ;) hopefully I was able to retrieve the data from one of the forks but uploading again all the files launched rebuilds that  may have failed. I'll launch the build now, thanks
