### ISSUE TITLE
🐛 [Immich] not working with v1.88

### ISSUE THREAD

**Issue by digitaljamie** [alexbelgium/hassio-addons#1084]
### Description

The latest v1.88.x of Immich has introduced breaking changes

The ports to be forwarded have changed.
I think it means that port 3001 should be used instead of 8080. [See here](https://github.com/immich-app/immich/discussions/5086#discussioncomment-7592300). According to the 1.88 release announcement, "All requests will now need to be forwarded to ip:2283 (external port) or immich-server:3001 (internal port)."
The add-on will not work until this is fixed.

### Reproduction steps

```bash
1. Update to v1.88.x
2. Cannot access UI on port 8080
```

### Addon Logs

```bash
-
```

**Comment by HerrBeef** [comment]
for me even after the change to 3001 it doesn't work. which port do i have to configure in homeassistant and reverse proxy?

**Comment by renaiku** [comment]
I installed this addon for the first time 2 hours ago, and I can't access the web interface also.

I also had to manually create the following folders and files because errors were thrown:

![image](https://github.com/alexbelgium/hassio-addons/assets/17033907/56f71440-18a2-4c83-a146-2bab6ccf66cb)

**Comment by jdumeez** [comment]
Same problem since update, including errors on the mkdir error for .reverse-geocoding…

**Comment by alexbelgium** [comment]
Tried a new version with port 2283 to see. Or I'll revert to the previous version of the add-on

**Comment by renaiku** [comment]
Still not working for me. And you @jdumeez ?

**Comment by alexbelgium** [comment]
Actually the upstream version I'm based on from imagegenius is still using 8080 as port... https://github.com/imagegenius/docker-immich I'll revert to the previous version of the addon it will be safer ;-)

**Comment by renaiku** [comment]
Ok thank you @alexbelgium 

Do you think the errors of folders and files creations in the /config folder are linked to that ?

**Comment by alexbelgium** [comment]
Well not sure, I'll try to go back to the initial config and look if I can find a solution

**Comment by alexbelgium** [comment]
really? and webui works too?

**Comment by jdumeez** [comment]
Yep, everything works again. Just updated hour add-on to the latest, gave my home assistant a reboot as well and it was back up and running. I do use port 8181 but don’t think that should matter

**Comment by alexbelgium** [comment]
Well that's unexpected :-) but an happy conclusion nevertheless ;-) then I'll avoid touching anything more, thanks for the feedbacks!

**Comment by renaiku** [comment]
Ok, I deleted postgres and immich add-ons and now it is working.

My idea why it works now:

during the install of the first immich, it created the data in postgres like the user and it blocked after there each time I retried.

I manually created the files requested by immich because it doesn't have admin access in the config folder.

**Comment by renaiku** [comment]
> No, v1.88.1-3 still doesn't seem to work for me on port 3001. I've tried changing the port in the add-on settings to 8080 and 8181, neither worked. There are no errors in the logs, so Immich is running, it just can't be accessed

No errors in postgres?

**Comment by alexbelgium** [comment]
The latest version I've pushed (-5) starts on my system without errors

**Comment by no3z** [comment]
Well, latest 1.88.1-6 is not working for me. Accessing `homeassistant:8181` refuses to connect.

I did manage to make 1.88.1-3 work after rebooting the whole system. But I am unable to make current version work.

**Comment by jdumeez** [comment]
Same as no3z. I got -3 to work, but it broke again on -6

**Comment by alexbelgium** [comment]
Ok, I've reverted the port to 8080, let's see if that does it

**Comment by no3z** [comment]
New -7 is working on my setup!

**Comment by alexbelgium** [comment]
Great !!! Now everything should be back on track thanks all for your patience and support

**Comment by jdumeez** [comment]
For me everything back up and running with -7. Thx Alex!!
