### ISSUE TITLE
🐛 [Paperless] Add on not running, due to  issue with config causing it to exit

### ISSUE THREAD

**Issue by Valve90210** [alexbelgium/hassio-addons#1090]
### Description

I know you've been having issues with the updates to Paperless, so I'm sure it's related but this morning I tried to access paperless webui but it couldn't be reached, so I check in HAOS and found the addon was not running. 

I've tried starting it but it keeps stopping. 

### Reproduction steps

```bash
1. Go to Paperless addon
2. Click on Start
3. Looking in the log, it tries to start but then fails and exits
4.
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Paperless NGX
 Scan, index and archive all your physical documents
-----------------------------------------------------------
 Add-on version: 2.0.0.1-6test2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/config.yaml'
OCRLANG='ENG FRA GER'
PAPERLESS_OCR_MODE='skip'
PGID='0'
PUID='0'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='false'
Timezone set from Etc/UTC to Europe/London
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
mkdir: cannot create directory ‘/config/config.yaml’: File exists
Load environment variables from /config/config.yaml/config.yaml if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no config file, creating one from template. Please customize the file in /config/config.yaml/config.yaml before restarting.
mkdir: cannot create directory ‘/config/config.yaml’: File exists
cp: cannot stat '/config/config.yaml/config.yaml': Not a directory
sed: can't read /tempenv: No such file or directory
sed: can't read /tempenv: No such file or directory
sed: can't read /tempenv: No such file or directory
... no env variables found, exiting
```

**Comment by alexbelgium** [comment]
Thanks, version -6 solves that

**Comment by alexbelgium** [comment]
Hopefully :) that's the issue of multitasking

**Comment by Valve90210** [comment]
I've updated but it's still having the same issue...

Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Paperless NGX
 Scan, index and archive all your physical documents
-----------------------------------------------------------
 Add-on version: 2.0.0.1-6test6
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/config.yaml'
OCRLANG='ENG FRA GER'
PAPERLESS_OCR_MODE='skip'
PGID='0'
PUID='0'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='false'
Timezone set from Etc/UTC to Europe/London
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Load environment variables from /config/config.yaml if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no config file, creating one from template. Please customize the file in /config/config.yaml before restarting.
cp: cannot overwrite directory '/config/config.yaml' with non-directory
cp: -r not specified; omitting directory '/config/config.yaml'
sed: can't read /tempenv: No such file or directory
sed: can't read /tempenv: No such file or directory
sed: can't read /tempenv: No such file or directory
... no env variables found, exiting

**Comment by Valve90210** [comment]
I've updated to version 8 and I'm still having the same issue, with the same error in the log. :/

**Comment by Valve90210** [comment]
Updated to version 9 and still having the exact same issue?

I had a thought though, could it be to do with me saving to a network drive on a NAS? I think I set that up from within the UI but has that changed now?

**Comment by alexbelgium** [comment]
Exactly the same error ? Could you please try :
- Update to latest (v11)
- With filebrowser, go in /addon_configs/db21ed7f_paperless_ng and delete any folder or file called config.yaml ; then restart and check if there is an issue
- if this still doesn't work, set your CONFIG_LOCATION to /config/paperless instead of /config/config.yaml, the restart ?

As it should not occur... I had the same error, updated to latest, then it went away...

Thanks !

**Comment by Valve90210** [comment]
Sorry, I wasn't home yesterday to test but I've just given it a go....

I updated to the latest version and deleted a config.yaml folder which contained a config.yaml file.

Restarted the addon and it seems to be working. It took a long while to initially load into the webui but now it's just as quick as it used to be and restarted my HA box, the addon restarted and is accessible! :) 

Fingers crossed this had sorted it. I can only imagine how much work this has been for you, very much appreciated!!
