### ISSUE TITLE
🐛 [MyElectricalData] Add-on version 0.9.2-3 fails to start

### ISSUE THREAD

**Issue by chocomega** [alexbelgium/hassio-addons#1091]
### Description

The addon fails to start when `config.yaml` contains:

```
offpeak_hours_0: '3H00-8H00;13H30-16H30'
offpeak_hours_1: '3H00-8H00;13H30-16H30'
etc...
```
I guess it is caused by the semicolon, cf logs.
Reverting to 0.9.2 works fine.
0.9.2-3 can start if the off-peak hours settings are removed.

### Reproduction steps

```bash
1. Go to 'Settings, Add-ons, MyElectricalData'
2. Click on 'Start'
3. Scroll down to last log line
4. See error
```

### Addon Logs

```bash
/.//etc/cont-init.d/99-run.sh: line 16: 13H30-16H30: command not found
```

### Architecture

aarch64

**Comment by alexbelgium** [comment]
I've tried to push a new version please let me know how it goes

**Comment by ilyadel** [comment]
"... config file has an invalid yaml format. Please check the file in /config/myelectricaldata/config.yaml. Errors list above."
still broken on 0.9.2-5

**Comment by Smockey37** [comment]
Hello,Same problem on my side.
try to comment offpeak_hour : same result.

**Comment by buchnoun** [comment]
same for me, still not fixed with 0.9.2-5

**Comment by alexbelgium** [comment]
Thanks, I'll check today

**Comment by jlc71710** [comment]
Same problem for me : 0.9.2.3 is not working
I upgrade to 0.9.2.4 and it's ok but after last uptdate (today) to 0.9.2.5 the problem apear again so 
I downgrade to 0.9.2.4 and it's ok again

**Comment by alexbelgium** [comment]
Should be good with -6
