### ISSUE TITLE
[REQUEST] Persist Portainer Oauth

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#1095]
I use Portainer and have it set up with my own custom Google Oauth. This addon does not currently support this as a restart clears the settings. Can the current addon be changed to allow these settings to persist?

_Originally posted by @tkdrob in https://github.com/alexbelgium/hassio-addons/issues/873#issuecomment-1826204672_

**Comment by alexbelgium** [comment]
Would you have a guide on makeing a custom google oauth? I can't replicate your setting so not sure that the direction of implement I've done would work - thanks!

**Comment by tkdrob** [comment]
> Hi @tkdrob Would you have a guide on makeing a custom google oauth? I can't replicate your setting so not sure that the direction of implement I've done would work - thanks!

https://www.home-assistant.io/integrations/google_mail This should provide you the needed information to set a custom OAuth provider. Let me know if you need anything else.

**Comment by alexbelgium** [comment]
Hi, so I've tested and actually oauth is permanent on my side even after reboot. Could you please post your full startup log and addon options (probably put xxx instead of passwords just in case) ? Thanks

**Comment by tkdrob** [comment]
Looks like I also used to change something with the admin account. Leaving it alone does not seem to trigger an overwrite. Maybe you can include an option to change the admin account name?

**Comment by alexbelgium** [comment]
Actually the only thing that should trigger a database overwrite should be each time that you change the password in the addon options. It is compared to the previous password, and if different the database is reset to take into account the password change

**Comment by tkdrob** [comment]
Then that's the reason, thanks

**Comment by tkdrob** [comment]
I had to restart the host machine and the oauth is now gone. I am not sure if anything else changed between actively testing this and the restart.
