### ISSUE TITLE
🐛 Immich write permissions

### ISSUE THREAD

**Issue by josiah-eichelman** [alexbelgium/hassio-addons#1097]
### Description

Immich Add-on is unable to create folder due to permission errors. I believe this is causing the metadata service to fail which causes the front end pictures to not load.

![image](https://github.com/alexbelgium/hassio-addons/assets/60556524/1c61a233-eb9b-4a97-bd75-00bf293faa6f)

### Reproduction steps

```bash
1. Install Immich Addon
2. Install Postgress Addon
3. Start both addons, and look at Immich logs
```

### Addon Logs

```bash
[Nest] 1353  - 11/26/2023, 1:36:42 AM   ERROR [MetadataService] Unable to initialize reverse geocoding: Error: EACCES: permission denied, mkdir '/config/.reverse-geocoding-dump/'
Error: EACCES: permission denied, mkdir '/config/.reverse-geocoding-dump/'
    at Object.mkdirSync (node:fs:1379:3)
    at Object.init (/app/immich/server/node_modules/local-reverse-geocoder/index.js:673:10)
    at /app/immich/server/dist/infra/repositories/metadata.repository.js:53:46
    at new Promise (<anonymous>)
    at MetadataRepository.init (/app/immich/server/dist/infra/repositories/metadata.repository.js:52:16)
    at MetadataService.init (/app/immich/server/dist/domain/metadata/metadata.service.js:72:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AppService.init (/app/immich/server/dist/microservices/app.service.js:93:9)
    at async bootstrap (/app/immich/server/dist/microservices/main.js:15:5)
```

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks! I see it writes in a folder where it shouldn't. I'll look what can be done

**Comment by josiah-eichelman** [comment]
I'm rather new to Add-on dev for HA, is this simply a config path that needs changed? (I tried looking through the config.json but didn't see anything). Or is this something that needs changed on the Immich settings?

**Comment by alexbelgium** [comment]
Actually it was on my end I found a solution

**Comment by jdumeez** [comment]
Hey alex on 1.88.2 -2 the mkdir permission error is still present for me. 
Still see this in the logs 

Nest] 1548  - 11/27/2023, 7:24:38 PM   ERROR [MetadataService] Unable to initialize reverse geocoding: Error: EACCES: permission denied, mkdir '/data/.reverse-geocoding-dump/'

**Comment by alexbelgium** [comment]
I forgot the actual solution :)

**Comment by jdumeez** [comment]
this is working for me! Thx Alex

**Comment by alexbelgium** [comment]
Thanks for the feedback!
