### ISSUE TITLE
✨ [REQUEST] Transmission UI new version

### ISSUE THREAD

**Issue by Meister1977** [alexbelgium/hassio-addons#1098]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Transmission 

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

As I see the frontend used in this add-on is not developed anymore. The last version is from 2020.
(https://github.com/ronggang/transmission-web-control/releases)

As I see, there is a fork, which is continuously developed.
https://github.com/transmission-web-control/transmission-web-control

(I found that here: https://github.com/ronggang/transmission-web-control/issues/625 )

I do not know, how I can fork a new addon from your version and change the UI source to this, but if you have some time, maybe you can change the source of the UI in your addon. If you can create a beta test version, I may check that. Thanks!

**Comment by alexbelgium** [comment]
Hi, it works only one issue : everything is in chinese by default :-)

**Comment by alexbelgium** [comment]
I've set the code, but I'm sorry as everything is in chinese by default until selected otherwise I'm not sure we should implement it... Except if you find another way - thanks

**Comment by alexbelgium** [comment]
Implemented in the main addon

**Comment by Meister1977** [comment]
Thanks!
It is still loading in Chinese, so maybe somehow it should be force to English. But I could change it to Hungarian, so for me, it is good. Thanks again. 

(I opened a ticket there to handle better the language of the browser, or build an English version too.)
https://github.com/transmission-web-control/transmission-web-control/issues/170

**Comment by alexbelgium** [comment]
On my system it is now working! I'll post on the other thread too
