### ISSUE TITLE
✨ [REQUEST] Nextcloud - Video Preview / Thumbnail Support

### ISSUE THREAD

**Issue by LuckyTriple7** [alexbelgium/hassio-addons#1099]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Nextcloud 27.1.4

### Is your feature request related to a problem? Please describe

The video preview in the browser does not work, no thumbnails are generated.

![image](https://github.com/alexbelgium/hassio-addons/assets/60685158/917c08d4-f8d1-455f-990f-24e812753ac6)

### Describe the solution you'd like

In order for the video preview to work, ffmpeg must be installed. I have not found a way to do this.

**Comment by alexbelgium** [comment]
Hi, in the addon option "additional_apps" could add ffmpeg ? It should be `inotify-tools,gcompat,ffmpeg` and check the log at start to see if it installs correctly. Thanks!

**Comment by LuckyTriple7** [comment]
I have already tested this with the following options:
_inotify-tools,ffmpeg,imagemagick,ghostscript_
Also with the entry _inotify-tools,gcompat,ffmpeg_
does not work either. According to the LOG, everything is fine.

`/etc/cont-init.d/99-add_packages.sh: executing
[08:28:07] INFO: Installing additional apps :
... inotify-tools
... gcompat
... ffmpeg
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
... installing apps : fulltextsearch
Installing OCR
[08:28:25] INFO: OCR Language installed : deu
/etc/cont-init.d/99-trusted_domains.sh: executing
[08:28:27] INFO: Currently set trusted domains :
192.168.178.200:9999
cloud.gizmohome.cloud
192.168.2.1
[08:28:28] INFO: Trusted domains set in the configuration. Refreshing domains.
[08:28:28] INFO: ... removing previously added trusted domain (except for first one created)
System config value trusted_domains => 2 deleted
System config value trusted_domains => 3 deleted
System config value trusted_domains => 4 deleted
System config value trusted_domains => 5 deleted`

**Comment by alexbelgium** [comment]
Thanks then likely an additional step would be needed beyond installing the app. Perhaps there is additional infos in the nextcloud documentation ?

**Comment by LuckyTriple7** [comment]
I fond this:
https://github.com/nextcloud/docker/issues/1432

Must Add someting to the config.php.
But i think i cannot access this file ?

`'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\MarkDown',
    2 => 'OC\\Preview\\OpenDocument',
    3 => 'OC\\Preview\\PDF',
    4 => 'OC\\Preview\\MSOffice2003',
    5 => 'OC\\Preview\\MSOfficeDoc',
    6 => 'OC\\Preview\\Image',
    7 => 'OC\\Preview\\Photoshop',
    8 => 'OC\\Preview\\TIFF',
    9 => 'OC\\Preview\\SVG',
   10 => 'OC\\Preview\\Font',
   11 => 'OC\\Preview\\MP3',
   12 => 'OC\\Preview\\Movie',
   13 => 'OC\\Preview\\MKV',
   14 => 'OC\\Preview\\MP4',
   15 => 'OC\\Preview\\AVI',
 )`

**Comment by alexbelgium** [comment]
The only way to access that I know is using the portainer app : https://github.com/alexbelgium/hassio-addons/wiki/Portainer to access files within the container

**Comment by LuckyTriple7** [comment]
Thanks for the info. I have just tried, but I have not found a way to do this with Portainer. Maybe it would be easier to make the config.php for Nextcloud available in a share which can then be easily edited.

**Comment by LuckyTriple7** [comment]
I have solved it :-)
The config.php can be found under:
/data/config/www/nextcloud/config/

Edited with nano.
Added the following lines:

'preview_ffmpeg_path' => '/usr/bin/ffmpeg',
'enable_previews' => true,
'enabledPreviewProviders' =>
array (
0 => 'OC\\Preview\\TXT',
1 => 'OC\\Preview\\MarkDown',
2 => 'OC\\Preview\\OpenDocument',
3 => 'OC\\Preview\\PDF',
4 => 'OC\\Preview\\Image',
5 => 'OC\\Preview\\TIFF',
6 => 'OC\\Preview\\SVG',
7 => 'OC\\Preview\\Font',
8 => 'OC\\Preview\\MP3',
9 => 'OC\\Preview\\Movie',
10 => 'OC\\Preview\\MKV',
11 => 'OC\\Preview\\MP4',
12 => 'OC\\Preview\\AVI',
),

AddOn restarted, video preview works !

**Comment by alexbelgium** [comment]
Yes! Congratulations! Do you think everyone might benefit from that ? As you've confirmed it works, I could look to have it implemented by default in the addon code (either as an option if there is any downside to it, or as a default feature) !

Thanks for the details on how you made it work :-)

**Comment by LuckyTriple7** [comment]
Yes, I think everyone could use this option. Problems can occur on older hardware. So maybe with the option to deactivate it. FFMPEG must also be installed:

addition_apps: inotify-tools,gcompat,ffmpeg,imagemagick

**Comment by alexbelgium** [comment]
Thanks very much! I'll add it now :-)

**Comment by alexbelgium** [comment]
Thanks! I don't see the logic, but I'll try with it at the end ;-) it will auto correct for other users, as my code first deletes those values, then recreates them
