### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by rjgout** [alexbelgium/hassio-addons#110]
Hi,

is it possible to install a add-on multiple times? Why I need it: Readarr can only add ebooks or audio books per author. I want from one author the ebook and the audiobook. I read that Readarr can't handle that. That you need e second instance for that. 
So is it possible to create a second readarr. Thanks.

Love what you are doing by the way, it makes my life a lot easier.

**Comment by alexbelgium** [comment]
Hi, thanks very much! HA does not allow to install two instances, but an hack exists. If you add my repo twice, once with https://github.com/alexbelgium/hassio-addons and once with https://github.com/alexbelgium/hassio-addons/ ou will be able to install two versions!

**Comment by rjgout** [comment]
It works like a charm. Thanks for the tip.

**Comment by rjgout** [comment]
The installation went well. I changed the port. But it seems to look at the same config file. Any way that the docker can make an own config file?

**Comment by alexbelgium** [comment]
Could you please try the latest version I've pushed? it should allow setting the config location from the addon options

**Comment by rjgout** [comment]
I got an error updating it. So I removed it. Now I get an error installing it. 
![C6E467D4-EC60-48BE-B10B-5C05696374B7](https://user-images.githubusercontent.com/59642233/145584951-49bf5a76-432b-4987-96bd-578003ffb349.png)

**Comment by alexbelgium** [comment]
Yup, error on my part. I've updated a v3

**Comment by rjgout** [comment]
Installation works again. The config setting does nothing. 
![9471A93F-B643-484D-8DF6-8B7F5FAB0821](https://user-images.githubusercontent.com/59642233/145587532-6b7a6527-3180-4d8e-9ef0-31bcc0d05ae2.png)
![197D5A3C-667B-4C01-816E-2D5E2B1A480E](https://user-images.githubusercontent.com/59642233/145587545-d20a2e89-7cb2-4a19-845d-6f773d6a2f8c.png)

**Comment by alexbelgium** [comment]
Multitasking is not my greatest strength ;-) I used the variable in lower case instead of upper case. Version -3 will perhaps work!

**Comment by alexbelgium** [comment]
Again a typo, v4 pushed

**Comment by rjgout** [comment]
My man!! It works. I changed the port in the network section. I starts. Then I changed it in readarr itself. That killed it.

**Comment by alexbelgium** [comment]
Perfect! Thanks for the feedback!

**Comment by rjgout** [comment]
Hi, I noticed that the config location was removed. Can you add that back?

**Comment by alexbelgium** [comment]
Hi, indeed this doesn't seem on purpose. Would you have an example? Thanks

**Comment by rjgout** [comment]
What do you mean? Would you like me to provide a screenshot?

**Comment by rjgout** [comment]
Aha, my mistake. It's about Radarr.

**Comment by alexbelgium** [comment]
Are you sure there was an option to customize data path? Even if I look back in January there didn't seem to be such an option : https://github.com/alexbelgium/hassio-addons/blob/3ab7ea1de53d53d744757700f51077ee2c08bb03/radarr/config.json

Except for a very few addons, all configs are in /config/addons_config/* it is much easier... Custom locations induced other unexpected issues

**Comment by rjgout** [comment]
You made a change in dec 10th. I don't remember when it started to fail. I use two instances, one for movies and one for children movies. Both are configured in Overseerr. Then when a request comes, it goes to the right folder for Plex to monitor.

**Comment by nkm8** [comment]
Sorry to revive an old thread, but can you please clarify how to run 2 separate instances of an addon with a different config folder? The trick to install the repo twice worked - and now I can install 2 copies of any addon. However, I am specifically interested in sonarr and radarr - but without a way to change/customize where the config data is stored, wouldn't the second instance of these addons clash with the existing, running copy that is already using `/config/addons_config/sonarr`?

**Comment by alexbelgium** [comment]
Hi, Indeed... It is possible to install the repo twice by adding a slash or not at the end but this won't help with the data folder. It will work only for addons in which the folder can be customized, or is internal in the add-on...

**Comment by nkm8** [comment]
Ok, thank you for the clarification. 

If anyone else stumbles on this - my solution was to leverage another repository that has the addons I wanted to duplicate: https://github.com/evilmarty/hassio-addons/tree/master/sonarr

The only catch is this other repository doesn't map the same folder shares into the addon containers. As a workaround, I leveraged the new HAOS network mount capability to share the required folders between the containers.
