### ISSUE TITLE
❓ [Paperless] How to run document_renamer command

### ISSUE THREAD

**Issue by fvgarrel** [alexbelgium/hassio-addons#1101]
Hello, I've recently updated the filename format for my documents and now I want to use the document_renamer command from paperless through the Home Assistant addon to organize all documents into the new format. Could you guide me on how to execute this command with the Home Assistant addon?

**Comment by alexbelgium** [comment]
Hi, you can execue custom commands using portainer : https://github.com/alexbelgium/hassio-addons/wiki/Portainer

**Comment by fvgarrel** [comment]
Thanks, that worked 👍🏼
