### ISSUE TITLE
[REQUEST] Transmission-OpenVPN: NordVPN Settings

### ISSUE THREAD

**Issue by tutorempire** [alexbelgium/hassio-addons#1102]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Transmission_OpenVPN

### Is your feature request related to a problem? Please describe

The NordVPN VPN provider has several useful options that can be set via environment variables, such as the country to be connected to, as well as the server type. 

As far as I can tell, there is currently no way to pass arbitrary environment values in the config, which makes transmission-openvpn connect to the closest server in the country I am in, which is not what i want. 

<img width="743" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/15877139/99de9a7b-566f-45af-b440-463c9d660985">

### Describe the solution you'd like

Please allow the setting and editing of the following environment variables to be passed to the transmission-openvpn container:

NORDVPN_COUNTRY
NORDVPN_CATEGORY
NORDVPN_PROTOCOL
NORDVPN_SERVER

These can all be settable as optional strings.

Alternatively, please allow some way to pass arbitrary env values to the container.

Thank you so much!!

**Comment by tutorempire** [comment]
Documentation for provider-specific settings:

https://haugene.github.io/docker-transmission-openvpn/provider-specific/

**Comment by alexbelgium** [comment]
Hi, you can add any custom env variables to my add-ons by following this guide: https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables

**Comment by tutorempire** [comment]
Thanks so much!

I'm attempting to follow the guide, I don't see a config.yaml file in any of the directories mentioned for transmission-openvpn

I do see a config.yaml in the Filebrowser addon:

<img width="531" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/15877139/69318e59-119c-4485-93ba-81bd3c5e2e3b">

I see an empty one in /config: 

<img width="536" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/15877139/426e0651-1bda-4bf2-af1c-364bfaca0add">

But nothing in the transmission_openvpn directory:

<img width="536" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/15877139/c807fe93-cf64-4887-a02c-6abeee576b3e">

or the transmission directory:

<img width="635" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/15877139/95711d8c-3dcc-4c7f-860b-f22fe0a5f186">

I've started the addon multiple times, and even tried putting a config.yaml file in /config/addons_config/transmission_openvpn , but no luck with it reading the files / variables.

Am I missing something obvious?

**Comment by alexbelgium** [comment]
Hi, sorry you are doing everything right but it seems that last build was so old (2 months) that the config.yaml code was not yet implemented. I'll push a new version now. In the log there will be a line starting with 01-config_yaml.sh that will say where the config file can be found (likely where you had created the folder).

Thanks very much for having taken the time for that it should work now !

**Comment by tutorempire** [comment]
Thank you so much - this works!

One more issue/request, related to this. I would like to use the proxy built into this container. 

I tried to start it by adding

WEBPROXY_ENABLED: true
WEBPROXY_PORT: 8118

in the config.yaml file, but it also requires the port above to be mapped out, which as far as I can tell, I can't do via the config.yaml file. 

Also, from the log file, it looks like it trying to bind to the wrong address so this might require a bit of work:

<img width="722" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/15877139/0fc62433-1f64-4765-bbe3-c86cdcb0949c">

Should this be a separate feature request?

**Comment by alexbelgium** [comment]
Hi, what is the benefit of this proxy? I can simply map this port as an addon option if this would be useful for all users ?

**Comment by tutorempire** [comment]
The proxy allows you to use the OpenVPN tunnel created by docker-transmission-openvpn as a web proxy. 

In my case, I use the proxy to be able to watch tv/etc from the U.S. even though I'm currently abroad, while using the same VPN tunnel for transmission. I have this running in a docker on my Windows desktop, but I'd much rather have it on my hass.io server.

Most VPN providers also limit the number of concurrent logins, so using the same VPN tunnel for transmission + any number of local proxy clients makes it easier as multiple computers in a home could use the hass.io server as a web proxy to connect to services in other countries without having to install a VPN client on them, be mindful of the number of simulatenous connections, etc.

Here's the relevant info: https://haugene.github.io/docker-transmission-openvpn/web-proxy/

I don't see any obvious disadvantages to enabling it by default, aside from having a service running that someone may not expect, but it's *not* enabled by default in the base docker package, and I would assume that most people don't know about this 'extra' feature.

**Comment by alexbelgium** [comment]
Hi, added! I've enabled it by default by with an optional config

**Comment by alexbelgium** [comment]
Thanks very much for the detailed explanation! I've pushed a new version hopefully it should solve the issue

**Comment by tutorempire** [comment]
Fantastic, everything seems to work as expected now! Thanks!
