### ISSUE TITLE
🐛 [Spotweb] not able to retrieve older spots

### ISSUE THREAD

**Issue by marcokreeft87** [alexbelgium/hassio-addons#1106]
### Description

Spotweb add on is not able to retrieve older spots

### Reproduction steps

```bash
1. Go to 'Config > settings > retrieve'
2. Set the date for 'Retrieve spots after' to for example November 1, 2009 like the text says to do to get everything after FTD
3. Click on 'change'
4. Click on retrieve or do a command line retrieve in docker

The older spots are not retrieved, only spots after last retrieve.
```

### Addon Logs

```bash
root@db21ed7f-spotweb:/app$ /usr/bin/php retrieve.php
Last retrieve: 2023-11-30 10:26:02
Retrieving new Spots from server reader.xsnews.nl...
Appr. Message count:    2241533
First message number:   7156827
Last message number:    9398360
Current article number: 9398356

Retrieving 9398356 till 9398361 (parsed: 4, in DB: 1, signed: 3, invalid: 0, rtntn.skip: 0, mod: 1, full: 0, total: 5) in 0.08 seconds
Processed a total of 5 spots
Finished retrieving spots.

Calculating how many spots are new, done.
Last retrieve: 2023-11-30 10:36:45
Retrieving new comments from server reader.xsnews.nl...
Appr. Message count:    13872741
First message number:   11655127
Last message number:    25527868
Current article number: 25527843

Retrieving 25527843 till 25527869, found 26 comments in 0.03 seconds
Processed a total of 26 comments
Finished retrieving comments.

Last retrieve: 2023-11-30 10:36:46
Retrieving new reports from server reader.xsnews.nl...
Appr. Message count:    171731
First message number:   34829
Last message number:    206560
Current article number: 206560

Processed a total of 0 reports
Finished retrieving reports.

Failed loading XML: 
Non-fatal: Updating black/whitelist failed, most likely unreachable!
```
```


### Architecture

_No response_

### OS

HAos

**Comment by alexbelgium** [comment]
strange ; not sure what could then cause the issue... Hi @woutercoppens are you still using this addon? Do you have an issue on what could be the issue?

**Comment by woutercoppens** [comment]
![2023-11-30 18_33_36-SpotWeb - Settings](https://github.com/alexbelgium/hassio-addons/assets/7490279/1716f38d-7924-4d07-a869-b6c14d31457f)

These are my settings. 

What is the retention of your usenet provider?

**Comment by marcokreeft87** [comment]
> ![2023-11-30 18_33_36-SpotWeb - Settings](https://github.com/alexbelgium/hassio-addons/assets/7490279/1716f38d-7924-4d07-a869-b6c14d31457f)
> 
> These are my settings. 
> 
> What is the retention of your usenet provider? 

I have xsnews, so 3000 I think? But like I said the jgeusebroek image does work. Just this add on doesn't work. It saves the date picked in the settings but doesn't display it correctly and doesn't get older spots, only new spots.

**Comment by woutercoppens** [comment]
https://www.xsnews.nl/nl-eur/index.html 
2750 days.

**Comment by marcokreeft87** [comment]
> https://www.xsnews.nl/nl-eur/index.html 
> 2750 days. 

Ah thnx! But still, with the other docker image it works. When I look in the database, the date in the settings is saved correctly.

**Comment by marcokreeft87** [comment]
Yeah that's probably the difference here. I want to get the spots for more than 3 years back when I just installed the add on. You only have spots since you installed the add on, correct?

**Comment by woutercoppens** [comment]
The oldest spot I have: 01/02/2010.
That is more then 11 years ago.  I have my doubts that these are still fully online.

**Comment by woutercoppens** [comment]
strange

**Comment by marcokreeft87** [comment]
I'll try and reinstall it tomorrow hopefully it helps

**Comment by alexbelgium** [comment]
Thanks very much for you support @woutercoppens

**Comment by marcokreeft87** [comment]
I did, that's where the log comes from I posted above

**Comment by marcokreeft87** [comment]
I unchecked the white and black list option. The blacklist error is gone now but still no older spots. Even after dropping the database and reinstall the add-on :(

**Comment by llewy** [comment]
Try this:

php upgrade-db.php --clear-cache
php upgrade-db.php --reset-db
php retrieve.php

**Comment by marcokreeft87** [comment]
I think this is working! But Im gonna let it finish retrieving before confirming haha

**Comment by woutercoppens** [comment]
You said that it works with the official docker version. Which image are you referring to?

**Comment by marcokreeft87** [comment]
I currently use the jgeusebroek version. That was the only docker version for a long time

**Comment by llewy** [comment]
It works for me on this addon but than crashes on a reboot. There is something wrong with the app/cache folder or it’s permissions. See the other bug about images.

**Comment by llewy** [comment]
`21:31:14] INFO: Existing database, checking health with upgrade-db....
[21:31:14] INFO: Existing database, clearing cache with upgrade-db
[21:31:14] INFO: to fix potential cache corruption...
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /app/bin/upgrade-db.php on line 206
PHP Warning:  rename(/app/cache,/app/cache2): Cross-device link in /app/bin/upgrade-db.php on line 206
PHP Warning:  mkdir(): File exists in /app/bin/upgrade-db.php on line 210
PHP Warning:  unlink(/app/cache2): No such file or directory in /app/bin/upgrade-db.php on line 19
Validating cache content, items 0 to 1000, done. `

**Comment by alexbelgium** [comment]
> > It works for me on this addon but than crashes on a reboot. There is something wrong with the app/cache folder or it’s permissions. See the other bug about images.
> 
> You also have to chmod on the cache folder for the images to work with the spots

Hi, easy enough path is /app/cache ? I'll add it to add-on code

**Comment by marcokreeft87** [comment]
> > > It works for me on this addon but than crashes on a reboot. There is something wrong with the app/cache folder or it’s permissions. See the other bug about images.
> > 
> > You also have to chmod on the cache folder for the images to work with the spots
> 
> Hi, easy enough path is /app/cache ? I'll add it to add-on code

Yes that's the one

**Comment by marcokreeft87** [comment]
I guess I'll just use the jgeusebroek version.

**Comment by jodur** [comment]
Any solution for this problem? I aslo retrieve spot maximum 1 month old. The data setting doesn't seems to be stored when is change it trough te webinterface. Also tried to modifie the date in Mariadb->settings->retrieve_newer_than and set it to 1701558000 (linux epoch Tuesday, January 1, 2019 10:39:37 AM) . This also doesn't have any effects

**Comment by jodur** [comment]
Did some testing further. After settting the value for the date <settings->retrieve_newer_than> in database and issued the command : `php retrieve --retro` the older post are now showing up. Could it be a issue with the anonymous user?
