### ISSUE TITLE
Nexcloud SSL

### ISSUE THREAD

**Issue by rjgout** [alexbelgium/hassio-addons#111]
I am getting the following error when I start nextcloud:

nginx: [emerg] cannot load certificate "/ssl/nextcloud/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/ssl/nextcloud/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

The only change I made was the trusted domain.

**Comment by alexbelgium** [comment]
Thanks, I'll look at it

**Comment by alexbelgium** [comment]
could you please post your full log? thanks

**Comment by zimmra** [comment]
Not the original poster of this, but I am encountering it as well. 
[_addon_db21ed7f_nextcloud_ocr_logs.txt](https://github.com/alexbelgium/hassio-addons/files/7689996/_addon_db21ed7f_nextcloud_ocr_logs.txt)

**Comment by alexbelgium** [comment]
Thanks, I'll look at it ASAP

**Comment by alexbelgium** [comment]
OK I've pushed a version that solves it. It's due to a new logic that I applied to all addons so all addons next update might fail... I'll correct that this weekend. Could you please confirm if the new version works? Thanks

**Comment by rjgout** [comment]
I now have version 23.0.0-2

This is my log:

[log.txt](https://github.com/alexbelgium/hassio-addons/files/7692481/log.txt)

And then this one keeps repeating:

nginx: [emerg] cannot load certificate "/ssl/nextcloud/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/ssl/nextcloud/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by zimmra** [comment]
I was able to successfully install with the update

**Comment by alexbelgium** [comment]
Thanks for the feedback!

**Comment by rjgout** [comment]
I used studio code server to create te folders. Under ssl /nextcloud/keys
Now it works.

**Comment by alexbelgium** [comment]
oh sorry I saw the info that it was working and not your message. I'll adapt the correct immediately to automatically create the folders, thanks!
