### ISSUE TITLE
Firefly III Data Import Tool, update to version v1.3.12 not possible, stuck at v.1.3.8

### ISSUE THREAD

**Issue by Ovenlade** [alexbelgium/hassio-addons#1110]
### Description

1. There are no updates available in Home Assistant.

2. According to home assistant de current version is v.1.3.9

3. When going to my URL of the Firefly III Data Import Tool it says v1.3.8

4. According to this github page the newest version should be v1.3.12

5. Removing the add-on within Home Assistant and installing it again does not resolve this

### Reproduction steps

```bash
1. Go to: Settings -> System -> Updates -> ticking: 'show skipped updates' -> no updates are available

2. See image 01

3. see image 02

4. see image 03

5. Settings -> Add-ons -> Selecting the add on Firefly III Data Import Tool -> [remove] -> install again
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Firefly iii Data Importer
 Data importer for Firefly III (separate addon)
-----------------------------------------------------------
 Add-on version: 1.3.9
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
AUTO_IMPORT_SECRET='...'
AN_POST_AUTOIMPORT='true'
CAN_POST_FILES='true'
CONFIG_LOCATION='/config/addons_config/fireflyiii_data_importer/config.yaml'
FIREFLY_III_ACCESS_TOKEN='...'
FIREFLY_III_URL='192.168.2.10:3473'
Updates='hourly'
Timezone set from Etc/UTC to Europe/Amsterdam
/etc/cont-init.d/01-config_yaml.sh: executing
Load environment variables from /config/addons_config/fireflyiii_data_importer/config.yaml if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/addons_autoscripts/fireflyiii-data-importer.sh if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
... no script found, exiting
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/98-fix.sh: executing
Fix for Nordigen
/etc/cont-init.d/99-run.sh: executing
[12:16:08] INFO: Configurations were found in /config/addons_config/fireflyiii_data_importer/configurations, they will be loaded.

[12:16:09] INFO: hourly updates

Starting periodic command scheduler: cron.
[12:16:09] INFO: Automatic updates were requested. The files in /config/addons_config/fireflyiii_data_importer/import_files will be imported hourly.
[12:16:09] INFO: Please wait while the app is loading !
Now in entrypoint.sh for Firefly III Data Importer
Script:        1.6 (2022-02-17)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  317
Build date:    01-09-2023 18:06:24 UTC
Now parsing _FILE variables.
done!
Firefly III data importer v1.3.8
PHP: cli 8.2.9 Linux
Will now run Apache web server:
[Sat Dec 02 12:16:12.573429 2023] [mpm_prefork:notice] [pid 340] AH00163: Apache/2.4.56 (Debian) configured -- resuming normal operations
[Sat Dec 02 12:16:12.573484 2023] [core:notice] [pid 340] AH00094: Command line: 'apache2 -D FOREGROUND'
127.0.0.1 - - [02/Dec/2023:12:16:16 +0100] "GET /health HTTP/1.1" 200 1105 "-" "curl/7.74.0"
```

### Architecture

amd64

### OS

HAos

**Comment by Ovenlade** [comment]
![03 version according to github hassio-addons](https://github.com/alexbelgium/hassio-addons/assets/139609087/f9b0ec34-5aaa-4d0f-8236-2be16bfa0754)
![02 version according to live service url](https://github.com/alexbelgium/hassio-addons/assets/139609087/c4d2f7bc-9d69-47ea-8c9a-8dc5e47d27f2)
![01 importer version according to HA](https://github.com/alexbelgium/hassio-addons/assets/139609087/8c5d79fb-03d2-43a6-89a9-0ef39392fa43)

**Comment by alexbelgium** [comment]
Hi, this is strange on my repo there is version `1.3.12` of the data importer : https://github.com/alexbelgium/hassio-addons/blob/90c03e57729b70b28a5be15913c18ff1c6ba0be3/fireflyiii_data_importer/config.json#L98

When I go in my addon store I see vers 1.3.12
![image](https://github.com/alexbelgium/hassio-addons/assets/44178713/5d96b2d8-4eaa-4d31-a530-7fb7fd65f525)

Perhaps something is stuck on your HA system...

**Comment by Ovenlade** [comment]
If other people see the up te date version, something must be wrong with my installation. 

Is there any way to remove the add-on and start fresh installing it again?

**Comment by sbonn13** [comment]
Everything is fine with my installation. Current version: 1.3.12 
Seems it might be a local issue.

**Comment by Ovenlade** [comment]
I found a solution to my problem. Things point to a problem with my configuration but I am not entirely sure.

There are two urls for this repository:
https://gitee.com/hassio/alexbelgium-addons -> old version of the add-on
https://github.com/alexbelgium/hassio-addons -> newest version of the add-on

I only had the first in use and I just added the second one and installed the newest version of the add-on. 
It's already up and running. :)

I would recommend to check if the first repository is up to date if being supported at all.

(I tried everything I could to refresh on the first repository on my end, I did not know the right command to do this beyond the obvious such as rebooting and checking for updates.)

**Comment by alexbelgium** [comment]
Hi, thanks! Gitee likely is a rip-off of github : I have not set it up, and have never used it... So it is likely a fake site just hope it didn't inject malwares... Great to know that however !!!

**Comment by Ovenlade** [comment]
Thanks for that information. If that's being the case I'd rather migrate my add-ons to the real repository!

Thanks for your time and all you effort to set this repository up. The add-ons you are providing make a real nice and easy way to set up a home server with all kinds of cool stuff.
