### ISSUE TITLE
🐛 [Nextcloud] Avoid logging to  system console

### ISSUE THREAD

**Issue by dd310** [alexbelgium/hassio-addons#1116]
### Description

I recently noticed that the Nextcloud addon is flooding the HAOS CLI with messages (screenshot included).

See also:

home-assistant/addons/pull/3018
home-assistant/addons/issues/3013

![image](https://github.com/alexbelgium/hassio-addons/assets/17815448/1c5596d9-2cb3-4d9c-9c3d-f342b40cddb2)

### Reproduction steps

```bash
1. Open the Home Assistant OS CLI
```

### Addon Logs

```bash
Nothing to report
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, the fix is already done it is an issue affecting all linuxserver based add-ons. Now we just need to wait for the next automatic update from my add-ons and the corrective corrective code will be  applied. I'll do it now for nextcloud

**Comment by alexbelgium** [comment]
https://github.com/alexbelgium/hassio-addons/issues/1111#issuecomment-1840393211
