### ISSUE TITLE
✨ [REQUEST] [epicgamesfree] Change url in Notification 

### ISSUE THREAD

**Issue by vinnie1234** [alexbelgium/hassio-addons#1124]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

epicgamesfree

### Is your feature request related to a problem? Please describe

In the notification I recieve in Discord the url is http://localhost:4001/zpllvw, but it's not localhost for me

### Describe the solution you'd like

Make it possible (or make it clear how) to change the url in this notification!

**Comment by czerwony03** [comment]
Change webPortalConfig.baseUrl value in config:
```
    "webPortalConfig": {
        "baseUrl":"http://192.168.0.192:3000"
    },
```

**Comment by vinnie1234** [comment]
I think I was sleeping or something, how did I miss that. Thans!
