### ISSUE TITLE
❓ [Portainer] Data gone after upgrade to 2.19.4

### ISSUE THREAD

**Issue by EpicLPer** [alexbelgium/hassio-addons#1128]
**Name:**
Portainer

**Log Information:**
```
 Add-on version: 2.19.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (amd64 / qemux86-64)
 Home Assistant Core: 2023.12.1
 Home Assistant Supervisor: 2023.11.6
```

**Reason for Issue:**
I've upgraded to the latest 2.19.4 version, after trying to access it all my data is gone and it's showing me the "New Portainer installation" or "Restore from backup" screen. I think this is related to the fact HA has changed a lot of underlying things and moving Addon configurations into their respective directories. This has failed once already for me for NodeRed and I had to restore from a backup.
Is this a known issue? If so, how can I restore my data? Thanks already for your help!

**Comment by EpicLPer** [comment]
I've now restored to 2.19.3 via the HA Restore function which brought back all my data. I've now backed up everything via the Portainer settings to import again after updating.

I've noticed in the logs that after updating to 2.19.4 it shows `... password changed, database reseted. Previous version stored in /data/portainer.old`, maybe this behavior should be changed to prevent accidental deletion of data especially in case HA changes some things around and makes addons believe settings have been changed.

**Comment by alexbelgium** [comment]
Hi, there is no particular reason for that : I have not implemented on this addon the new HA config logic, nor done any code change... Except remove the file /etc/cont-init.d/00-aaa_portainer_install.sh that was not executed on boot anyway

As all data is stored in /data, if they ask you to reconfigure you should probably restore a backup. What is strange is that I can't replicate : update went smoothly on my system, and the database is created at addon start.

Before restoring your backup, could you add a full startup log? Thanks

**Comment by EpicLPer** [comment]
Wanted to edit my previous comment to post some more findings which could potentially help but you posted before, so here's a new one :)

One additional info I found: I've noticed in older backup tar files from HA it shows "empty" in the `portainer_password`, however in the newest/latest backup file that file simply has no content. The only thing that changed was me updating HA to the latest 2023.12.1 version, so maybe it somehow changed the config option from an "empty" password to an actual empty one?

**Comment by alexbelgium** [comment]
Thanks very much for this investigation. It doesn't really make sense as my code puts "empty" if the password is null. The only way it could fail is if "null" is detected as a value. So I've modified the code to replace "null" by "empty". Let's see how that goes

https://github.com/alexbelgium/hassio-addons/blob/f4cfbad0bcaf5e3bb37a4b838a75f7a219cc93b0/portainer/rootfs/etc/services.d/portainer/run#L38-L40

**Comment by alexbelgium** [comment]
Hi, does this still occur? Or I can close it ?

**Comment by EpicLPer** [comment]
Oh, sorry! Seems to be solved already, and especially with the latest update making an automated backup was a good idea :)
Thanks!

**Comment by alexbelgium** [comment]
Thanks ! Have nice end of the year holidays !

**Comment by EpicLPer** [comment]
You too thanks :D
