### ISSUE TITLE
[Issue] Photoprism broken not starting after update

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#113]
Hi,

It looks like after the last update photo prism is broken.

ounting smb share(s)...
[18:30:39] INFO: ... //192.168.1.25/NAS successfully mounted to /mnt/NAS with options 
scripts/99-run.sh: executing
/00-banner.sh
./scripts/99-run.sh: /./00-banner.sh: /usr/bin/with-contenv: bad interpreter: No such file or directory
exit 0
/92-local_mounts.sh
./scripts/99-run.sh: /./92-local_mounts.sh: /usr/bin/with-contenv: bad interpreter: No such file or directory
exit 0
/92-smb_mounts.sh
./scripts/99-run.sh: /./92-smb_mounts.sh: /usr/bin/with-contenv: bad interpreter: No such file or directory
exit 0
[18:30:39] INFO: Please wait 1 or 2 minutes to allow the server to load

**Comment by alexbelgium** [comment]
Thanks I'll look at it

**Comment by alexbelgium** [comment]
It should rework in the latest version :)

**Comment by deku-m** [comment]
Works again thx

**Comment by alexbelgium** [comment]
Great thanks!
