### ISSUE TITLE
Backup considerations

### ISSUE THREAD

**Issue by baflo** [alexbelgium/hassio-addons#1134]
Hi @alexbelgium 

I lately adopted the postgres addon (and many more) and wonder how you considered backups. Actually, I wonder for all addon, but postgres seems to require special care when backing up: https://www.postgresql.org/docs/current/backup.html

I found that the addon config allows for ["cold" backups](https://developers.home-assistant.io/docs/add-ons/configuration#:~:text=hot%20or%20cold.%20If%20cold%2C%20the%20supervisor%20turns%20the%20add%2Don%20off%20before%20taking%20a%20backup%20(the%20pre/post%20options%20are%20ignored%20when%20cold%20is%20used).), i.e. the supervisor would shut down the container before taking backups.

Best wishes

**Comment by alexbelgium** [comment]
Hi, thanks excellent idea! I've added the code
