### ISSUE TITLE
⚠️ [Immich] Breaking change next release

### ISSUE THREAD

**Issue by hydazz** [alexbelgium/hassio-addons#1138]
Thought I would give you a heads up that once https://github.com/imagegenius/docker-immich/pull/248 is merged, instances will stop working, people will need to update their postgres image to pgvector

**Comment by alexbelgium** [comment]
Thanks very much!

**Comment by alexbelgium** [comment]
I don't think postgres supports automatic database updates, so would this means I would need to create an addon for the postgres vector image, and users would have to recreate their databases using the new vector database addon ?

**Comment by hydazz** [comment]
no migration is needed just have to swap out the container for `tensorchord/pgvecto-rs:pg14-v0.1.11` - there should be images for postgres 14/15/16, if keeping the same version, no recreation needed (which is easier said then done when you dont have to work within the restrictions of haos)

**Comment by alexbelgium** [comment]
Great thanks!

**Comment by pafnow** [comment]
Hi,
Is this issue preventing the upgrade of the addon to the last version of immich ?

**Comment by hydazz** [comment]
I would assume so, every instance would break unless the postgres container is changed to vector.rs

**Comment by alexbelgium** [comment]
I've updated the postgres image, if there is no reported issues the immich image will be updated next saturday
