### ISSUE TITLE
✨ [REQUEST] Authentik, Authelia or keycloak

### ISSUE THREAD

**Issue by jdumeez** [alexbelgium/hassio-addons#1149]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

I would like to request one of the popular add-ons to be available for identity and access management. (to introduce 2FA for example to the immich app) 

https://www.authelia.com/
https://www.keycloak.org/
https://goauthentik.io/

### Is your feature request related to a problem? Please describe

No 2FA for some of the add-ons 

### Describe the solution you'd like

An authentication add-on

**Comment by PaulAmor** [comment]
To avoid replication I suggest instead https://github.com/BenoitAnastay/authelia-home-assistant-addon and we close this ticket.

**Comment by alexbelgium** [comment]
Thanks! Indeed he has great addons

**Comment by jdumeez** [comment]
Thx for linking his repo!
