### ISSUE TITLE
[Qbittorrent] random ovpn is NOT used as advertised in changelog

### ISSUE THREAD

**Issue by Stooovie** [alexbelgium/hassio-addons#1150]
### Description

4.6.2_29 states in the changelog

`Feat : if no ovpn is referred in the option, it will use a random one from the openvpn folder (from https://github.com/Trigus42/alpine-qbittorrentvpn)`

but that's not the case 
![IMG_8097](https://github.com/alexbelgium/hassio-addons/assets/10572373/ad6b5430-8479-4991-94b8-48c32588879a)
![IMG_8096](https://github.com/alexbelgium/hassio-addons/assets/10572373/36ee683b-d72d-40bd-ad8e-52d19f67bee5)
![IMG_8098](https://github.com/alexbelgium/hassio-addons/assets/10572373/777ac287-9ddf-47a2-ae0c-3b1cfc43ad98)

### Reproduction steps

```bash
1) have ovpn file with different name than config.ovpn
```

### Addon Logs

```bash
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by alexbelgium** [comment]
Thanks very much! I see... Actually the current code copies the oven file to /etc/openvpn/config.ovpn before execution, which is why the error message is wrong. It is a relicate from an old code, I'll change that behavior.

Regarding the main issue it seems like I misnamed the folder when doing the check. Actually the worst is that it did work when I tested it but I guess a last minute "improvement" before commit did that ! I'll push a new version

**Comment by alexbelgium** [comment]
I've pushed a new version that could have a breaking change for you : previously, all lines with auth-user-pass were ignored and replaced by the addon username & password. However, if we accept random ovpn files we should accept that they could have different authentification. As such, in the new version, `auth-user-pass` fields are used as long as the referenced file exists.

I mention that as it is used by default by mullvad - so either you have kept the mullvad credentials file and it will use it (and not the addon username & password), or if you have deleted this file or commented out the line it will instead use the addon username & passwords.

This will allow for example to switch randomly between VPN credentials alongside ovpn files

**Comment by alexbelgium** [comment]
Actually it's version -36 :-)

**Comment by Stooovie** [comment]
37 😅 working again, thanks!

**Comment by alexbelgium** [comment]
Thanks! But actually you could have kept the file named `mullvad_prg_something.ovpn`, it should work with any filename. For example, you could even download different mullvad config files from different locations, and have an automation to restart the addon every day or couple days. Each time it would use a different ovpn file and therefore a different country. Not sure what it would achieve, but you know, it would work ;-)
