### ISSUE TITLE
❓ [Filebrowser] Docker healthcheck cert validity on 127.0.0.1 ?

### ISSUE THREAD

**Issue by encryptix** [alexbelgium/hassio-addons#1155]
**Which addon?**

Filebrowser

name: Question
about: Should the docker health check ignore certificate validity when using https?
title: ''
labels: ''
assignees: ''

---

**Which addon?**

Filebrowser

**Addon or app?**

Addon

**Describe the solution you'd like**

Given the health check uses 127.0.0.1, is it intentional that when using https it is also checking cert validity?

https://github.com/alexbelgium/hassio-addons/blob/master/filebrowser/Dockerfile#L111
` CMD curl --fail "http://127.0.0.1:${HEALTH_PORT}${HEALTH_URL}" &>/dev/null || curl --fail "https://127.0.0.1:${HEALTH_PORT}${HEALTH_URL}" &>/dev/null || exit 1`

I first noticed this when the addon did not behave correctly at startup in HA (it would go red and then green again). Looking closer finds that docker lists it has unhealthy:

` c5e9b6dcf6a0   ghcr.io/alexbelgium/filebrowser-aarch64:2.23.0_10                "/usr/bin/env /ha_en…"   5 minutes ago   Up 5 minutes (unhealthy)   0.0.0.0:8087->8080/tcp, :::8087->8080/tcp                                                                                      addon_db21ed7f_filebrowser` 

Replicating the curl in the container:

 curl -vvI https://127.0.0.1:8080 
`curl: (60) SSL: no alternative certificate subject name matches target host name '127.0.0.1'`

Passing -k returns a valid check.

**Describe alternatives you've considered**
There are a few:
- Can be ignored
- Use http rather than https
- Switch to my own domain so certificate is valid although this may not be supported either https://github.com/letsencrypt/boulder/issues/137#issuecomment-112236543
- Searched for flags that could be passed to curl via environment variables.

**Additional context**

**Comment by alexbelgium** [comment]
Thanks very much for the detailed troubleshooting and solving including evaluated options! I've implemented your -k solution when enabling https in the latest version

**Comment by encryptix** [comment]
Thank you.

Docker is showing it as healthy now.
