### ISSUE TITLE
🐛 NextCloud 404 for many UI files

### ISSUE THREAD

**Issue by lonevvolf** [alexbelgium/hassio-addons#1158]
### Description

Just created a fresh installation on a Home Assistant Yellow, and the entire web UI seems to be non-functional due to 404 on all the JS files:

```
GET https://homeassistant.local:8099/core/js/oc.js?v=0fc25577 net::ERR_ABORTED 404 (Not Found)
dashboard/:34 
      
GET https://homeassistant.local:8099/js/core/merged-template-prepend.js?v=0fc25577-0 net::ERR_ABORTED 404 (Not Found)
```

Logs confirm the same:
```
2024/01/07 12:40:46 [error] 1412#1412: *5 open() "/app/www/public/core/js/oc.js" failed (2: No such file or directory), client: 172.30.32.1, server: _, request: "GET /core/js/oc.js?v=0fc25577 HTTP/2.0", host: "homeassistant.local:8099"
2024/01/07 12:40:46 [error] 1412#1412: *5 open() "/app/www/public/js/core/merged-template-prepend.js" failed (2: No such file or directory), client: 172.30.32.1, server: _, request: "GET /js/core/merged-template-prepend.js?v=0fc25577-0 HTTP/2.0", host: "homeassistant.local:8099"
```

The backend seems fine, since I can connect via the iOS app, etc.  Only the web UI seems affected.

### Reproduction steps

```bash
1. Install Addon in HA 2024.1.2
2. Go through initial setup
3. Open web UI
```

### Addon Logs

```bash
2024/01/07 12:40:46 [error] 1412#1412: *5 open() "/app/www/public/core/js/oc.js" failed (2: No such file or directory), client: 172.30.32.1, server: _, request: "GET /core/js/oc.js?v=0fc25577 HTTP/2.0", host: "homeassistant.local:8099"
2024/01/07 12:40:46 [error] 1412#1412: *5 open() "/app/www/public/js/core/merged-template-prepend.js" failed (2: No such file or directory), client: 172.30.32.1, server: _, request: "GET /js/core/merged-template-prepend.js?v=0fc25577-0 HTTP/2.0", host: "homeassistant.local:8099"
```

### Architecture

armv7

### OS

HAos

**Comment by Rockshox93** [comment]
Same for me, fresh install on HASSos with MariaDB, webUI is totally broken.

**Comment by alexbelgium** [comment]
Hi, only armv7 is broken? Linuxserver has alas discontinued this architecture I had it as legacy but probably will need to adapt it...

**Comment by Rockshox93** [comment]
Here is my System:

## System Information

version | core-2024.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1366
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 219.4 GB
disk_used | 16.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.14.2), Tailscale (0.13.1), InfluxDB (4.8.0), Terminal & SSH (9.8.1), File editor (5.7.0), Paperless-ngx (1.0.0), OneDrive Backup (2.2.4), AdGuard Home (5.0.1), MariaDB (2.6.1), Nextcloud (28.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5. Januar 2024 um 14:10
-- | --
current_recorder_run | 7. Januar 2024 um 12:13
estimated_db_size | 222.02 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by lonevvolf** [comment]
> Hi, only armv7 is broken? Linuxserver has alas discontinued this architecture I had it as legacy but probably will need to adapt it...

Unsure - this was on a Home Assistant Yellow with rPi Compute module.  But it looks like the @Rockshox93 has it on x64 as well.

**Comment by alexbelgium** [comment]
Thanks! For amrv7 it would be normal as  linuxserver's container (on which my add-on is based) totally changed its logic after dropping armv7 support, and I just forgot about it. However it is not logical for aarch64 as it works on my system... I'll try a new install on a virtual env system. Just to be sure @Rockshox93 could you please check at the beginning of the add-on log (when starting it) the arch mentioned? Thanks! 

Regarding armv7 @lonevvolf, you likely have a 32bit ha os system installed even if your hardware supports 64bit... I would highly recommend to upgrade to a 64 bit version of HA os it is very well worth the trouble as many add-ons are slowly dropping  armv7 support.

**Comment by alexbelgium** [comment]
Mmh it looks very much like an upstream error : https://github.com/linuxserver/docker-nextcloud/issues/403 I'll look how to update my add-on. Thanks for raising it!

**Comment by lonevvolf** [comment]
> Regarding armv7 @lonevvolf, you likely have a 32bit ha os system installed even if your hardware supports 64bit... I would highly recommend to upgrade to a 64 bit version of HA os it is very well worth the trouble as many add-ons are slowly dropping armv7 support.

Here's the system info - I had assumed armv7 due to the rPi hardware.

Version | core-2024.1.2
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.6
Operating System Family | Linux
Operating System Version | 6.1.63-haos-raspi
CPU Architecture | aarch64

**Comment by alexbelgium** [comment]
Thanks very much! Indeed the issue was upstream, i'll look for an update to clean erroneous files

**Comment by alexbelgium** [comment]
Should be good in latest version! Please let me know

**Comment by Rockshox93** [comment]
Fixed for me, thank you for being so fast!
