### ISSUE TITLE
can not mount local hdd sda/b4

### ISSUE THREAD

**Issue by xpokor02** [alexbelgium/hassio-addons#116]
Hi 
unfortunaly I can't mount hdd by label imho it is because you have only 1/2 in config.json my device is sda4 or sdb4 it chages with reboots.
Thanks

**Comment by alexbelgium** [comment]
Hi, which addon? I'll add up to 4 then

**Comment by xpokor02** [comment]
right now sonarr but I suspect it will be same in others thanks

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version for sonarr. Go the others, you just need to first refresh all repos, then rebuild. Now sda3, 4 and sdb3, 4 will also mount!

**Comment by xpokor02** [comment]
It works now thanks
