### ISSUE TITLE
🐛 [Baikal] Can't update to version 0.9.4+msmtpfix

### ISSUE THREAD

**Issue by TomaszDom** [alexbelgium/hassio-addons#1162]
### Description

When I try to update to version 0.9.4+msmtpfix I am getting this message:
> Can't install ghcr.io/alexbelgium/baikal-amd64:0.9.4+msmtpfix: 400 Client Error for http+docker://localhost/v1.43/images/create?tag=0.9.4%2Bmsmtpfix&fromImage=ghcr.io%2Falexbelgium%2Fbaikal-amd64&platform=linux%2Famd64: Bad Request ("invalid tag format")

I don't think `0.9.4+msmtpfix` is an acceptable tag?

### Reproduction steps

```bash
1. Go to HAOS Updates 
2. Click on Update when presented with option to update to Baikal 0.9.4+msmtpfix
3. See error
```

### Addon Logs

```bash
> Can't install ghcr.io/alexbelgium/baikal-amd64:0.9.4+msmtpfix: 400 Client Error for http+docker://localhost/v1.43/images/create?tag=0.9.4%2Bmsmtpfix&fromImage=ghcr.io%2Falexbelgium%2Fbaikal-amd64&platform=linux%2Famd64: Bad Request ("invalid tag format")
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Fixed! Thanks

**Comment by TomaszDom** [comment]
Are you sure it's fixed? I still have the same version available to update and it's the same error.

**Comment by TomaszDom** [comment]
I think you need to bump the version so a correct version shows up.

**Comment by alexbelgium** [comment]
On version -4?

**Comment by alexbelgium** [comment]
You're right sorry, done
