### ISSUE TITLE
🐛 [sponsorblockcast] Type in default categories

### ISSUE THREAD

**Issue by hkrob** [alexbelgium/hassio-addons#1165]
### Description

There is a typo in the default categories
"into" should be "intro" (with an r)

### Reproduction steps

```bash
This is the current default:
'''
CSS_CATEGORIES: sponsor, into, outro, selfpromo
'''
```

### Addon Logs

```bash
Not needed
```

### Architecture

aarch64, amd64, armv7

### OS

HAos, Virtual Machine

**Comment by alexbelgium** [comment]
Thanks! Updated
