### ISSUE TITLE
✨ [REQUEST] Paperless-NGX Update to 2.3.2

### ISSUE THREAD

**Issue by nstrelow** [alexbelgium/hassio-addons#1166]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Paperless-NGX

### Is your feature request related to a problem? Please describe

I would like to use the newest version.

### Describe the solution you'd like

Update to the newest version in this file: https://github.com/alexbelgium/hassio-addons/blob/master/paperless_ngx/updater.json

There is probably the fancy updater bot that could do that ^^

Thanks a lot for all the addons 😁

**Comment by alexbelgium** [comment]
Hi! The automated updater runs every saturday morning it will be good in a couple days

**Comment by nstrelow** [comment]
Got it, seems like it was a very recent update then 👍
