### ISSUE TITLE
✨ [REQUEST]  Paperless-NGX Ingress support

### ISSUE THREAD

**Issue by nstrelow** [alexbelgium/hassio-addons#1167]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

 Paperless-NGX

### Is your feature request related to a problem? Please describe

It's easier to access via home assistant from outside my network

### Describe the solution you'd like

Ingress mode 😁 If it's not too much work

**Comment by alexbelgium** [comment]
Hi, if I remember correctly the security put in place in paperless-ngx prevent using ingress... it's an issue with many more evoluted apps such as this one !

**Comment by nstrelow** [comment]
ah i see
so this other addon is probably doing something hacky: https://github.com/BenoitAnastay/paperless-home-assistant-addon/tree/e8e07c0b719f8e74a604b34a821c8ff37194c619

actually, I think you need to set your ORIGIN URL there, to prevent getting a CORS error when logging in.

**Comment by alexbelgium** [comment]
thanks i didn't knew about this add-on how very it does not seem to support ingress either as has not ingress line in its config

**Comment by alexbelgium** [comment]
Thanks indeed he has a very nice add-on with great skills!

**Comment by BenoitAnastay** [comment]
> actually, I think you need to set your ORIGIN URL there, to prevent getting a CORS error when logging in.

I use the HA API to get internal, external URL and IPs (https://github.com/BenoitAnastay/paperless-home-assistant-addon/blob/a1c4d7904f108692f75ae46ed1d9be4f08eec0fe/paperless-ngx/rootfs/etc/s6-overlay/s6-rc.d/init-paperless/run)

But on my instance Nabu Casa Cloud URL isn't set on `external_url`, I don't know if it's a bug of the API

**Comment by BenoitAnastay** [comment]
So on my last PR I've made all fix but actualy Home Assistant doesn't set it's external URL to cloud_url, so I'll try to fix that on core

**Comment by alexbelgium** [comment]
Thanks ; I've set a deprecation notice on my addon and recommend my users to move to yours
