### ISSUE TITLE
✨ [REQUEST] addons_updater support for ghcr.io images without github releases

### ISSUE THREAD

**Issue by jdeath** [alexbelgium/hassio-addons#1168]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

addons_updater

### Is your feature request related to a problem? Please describe

Would like support to handle ghcr.io images released without corresponding github release. For example, wgeasy (https://github.com/wg-easy/wg-easy) does not have a release published in github, but has release packages available at https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy . Perhaps I set it up incorrectly, but addons_updater is not finding the named releases.  

### Describe the solution you'd like

Would like an option to find numbered releases only published as a package

**Comment by alexbelgium** [comment]
Hi, my addons_updater is based on https://github.com/dvershinin/lastversion that does not support tags without release... Have you looked at https://github.com/linuxserver/docker-wireguard also? Linuxserver is usually a provider of very robust & well templated containers that can easily be converted into hassio addons

**Comment by jdeath** [comment]
Thanks. I understand. wg-easy is way better as has simple graphical interface. It does not get updated too often, so I can manually update the config.json. Thanks for your efforts!

**Comment by alexbelgium** [comment]
Actually would using a released image on dockerhub such as https://hub.docker.com/r/weejewel/wg-easy/tags be an option? The add-on supports updating based on dockerhub versions tags

**Comment by alexbelgium** [comment]
I can also look at implementing my own code to update without existing release. Actually it should be possible by parsing the github page source

**Comment by jdeath** [comment]
They used to do releases at duckerhub, but switched new releases only at ghcr.io (I think development was expanded by a new team)

I put in a request in to have them do a source release on github, and they are considering it. So hopefully that will happen. https://github.com/wg-easy/wg-easy/issues/746

This is probably a niche application, so not worth writing anything specifically.

**Comment by jdeath** [comment]
Wow, thanks for adding this. Can you look at my updater.json, it does not seem to be updating:
https://github.com/jdeath/homeassistant-addons/tree/main/wgeasy/

**Comment by alexbelgium** [comment]
Thanks I see you have v9 it should found v10. I'll check

**Comment by jdeath** [comment]
Thank you. Worked like a charm!

**Comment by alexbelgium** [comment]
Glad it worked!
