### ISSUE TITLE
✨ [REQUEST] Cross-Seed (an app designed to match existing torrents across all trackers) 

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#1169]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Cross-Seed, (definitely a wishlist request, something that only applies to a few people since it's very private tracker based)

### Is your feature request related to a problem? Please describe

cross-seed is an app designed to help you download torrents that you can cross seed based on your existing torrents. It is designed to match conservatively to minimize manual intervention.

cross-seed can inject the torrents it finds directly into your torrent client. Currently, the supported clients are

    rTorrent
    qBittorrent
    Transmission
    Deluge

### Describe the solution you'd like

I was able to get it setup in portainer but was unable to get the mappings to work properly so an addon would be highly appreciated.

**Comment by hacshacdgacs** [comment]
Have managed to get it running myself, closing because it's a very niche request

**Comment by diamant-x** [comment]
> Have managed to get it running myself, closing because it's a very niche request

Did you developed an addon for HA for it?
Care sharing the repo for it?

Thanks!

**Comment by hacshacdgacs** [comment]
No sorry, was just doing so through portainer. I can look into doing so
when I'm back from holiday

**Comment by UnderclassAmigo** [comment]
> > Have managed to get it running myself, closing because it's a very niche request
> 
> Did you developed an addon for HA for it? Care sharing the repo for it?
> 
> Thanks!

Hey there, I tried attempting to set up an add-on but couldn't figure it out. If I can find a guide I'd be willing to give it another go but as of now I'm still just using a portainer container to run it. @diamant-x
