### ISSUE TITLE
✨ [REQUEST] mount a second nvme for all addons with localdisks support

### ISSUE THREAD

**Issue by XneddyX** [alexbelgium/hassio-addons#1180]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

All with localdisks support

### Is your feature request related to a problem? Please describe

I want to mount a second nvme into the addons. But the protocol says:
> Local Disks mounting...
... nvme1n1p1 is a physical device
[15:31:32] INFO: Mounting nvme1n1p1 of type 
mount: permission denied (are you root?)
[15:31:32] FATAL: Unable to mount local drives! Please check the name.

### Describe the solution you'd like

Please add  "/dev/nvme1n1p1" and maybe "/dev/nvme1n1p2", "/dev/nvme1n1p3" ... to all config.json files.

**Comment by alexbelgium** [comment]
Hi, which add-on are you mostly in? To avoid creating a new version of all add-ons. Thanks!

**Comment by alexbelgium** [comment]
I've added it for the version of nextcloud just pushed, please let me know if it works before I transversalize to the others

**Comment by XneddyX** [comment]
Yes i will try it this evening.

**Comment by XneddyX** [comment]
I have an new setup and the 02-mariadb_discovery.sh script is not loading. is it normal? 

> Starting...
> /etc/cont-init.d/00-banner.sh: executing
> 
> -----------------------------------------------------------
>  Add-on: Nextcloud
>  Nextcloud for Homeassistant
> -----------------------------------------------------------
>  Add-on version: 28.0.1-5
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 11.4  (amd64 / generic-x86-64)
>  Home Assistant Core: 2024.1.3
>  Home Assistant Supervisor: 2023.12.0
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums
> -----------------------------------------------------------
>  Provided by: https://github.com/alexbelgium/hassio-addons 
> -----------------------------------------------------------
>  Defining permissions for main user : 
> User UID: 1000
> User GID : 1000
> -----------------------------------------------------------
> /etc/cont-init.d/00-global_var.sh: executing
> Full_Text_Search='false'
> OCR='false'
> OCRLANG='fra'
> PGID='1000'
> PUID='1000'
> additional_apps='inotify-tools'
> certfile='fullchain.pem'
> elasticsearch_server='<ip:port>'
> enable_thumbnails='true'
> keyfile='privkey.pem'
> localdisks='nvme1n1p1'
> trusted_domains='your-domain, your-domain2'
> use_own_certs='false'
> /etc/cont-init.d/00-local_mounts.sh: executing
> ---------------------------------------------------
> [19:03:30] INFO: Available Disks for mounting :
> NAME        LABEL       SIZE FSTYPE   RO
> └─nvme1n1p1 PlexMedia 476.9G ext4      0
> ├─nvme0n1p2              24M squashfs  0
> ├─nvme0n1p3             256M squashfs  0
> ---------------------------------------------------
> Supported fs :  ext3 ext2 ext4 squashfs vfat msdos iso9660
> Inspired from : github.com/dianlight
> ---------------------------------------------------
> Local Disks mounting...
> ... nvme1n1p1 is a physical device
> [19:03:31] INFO: Mounting nvme1n1p1 of type ext4
> [19:03:31] INFO: Success! nvme1n1p1 mounted to /mnt/nvme1n1p1
> /etc/cont-init.d/00-smb_mounts.sh: executing
> /etc/cont-init.d/01-config_yaml.sh: executing
> Setting permissions for the config.yaml directory
> 
> Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
> If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
> ---------------------------------------------------------
> 
> Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
> ... no env variables found, exiting
> [migrations] started
> [migrations] 01-nginx-site-confs-default: skipped
> [migrations] 02-default-location: skipped
> [migrations] done
> Setting permissions for the config.yaml directory
> 
> Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
> If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
> ---------------------------------------------------------
> Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
> 
> ... no env variables found, exiting
> Execute /homeassistant/addons_config/nextcloud-ocr/nextcloud-ocr.sh if existing
> Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
> ───────────────────────────────────────
>   _____ __ __ _____ _____ _____ _____ 
>  |     |  |  |   __|_   _|     |     |
>  |   --|  |  |__   | | | |  |  | | | |
>  |_____|_____|_____| |_| |_____|_|_|_|
>        _____ __ __ _ __    ____  
>       | __  |  |  | |  |  |    \ 
>       | __ -|  |  | |  |__|  |  |
>       |_____|_____|_|_____|____/ 
> 
>   Based on images from linuxserver.io
> ───────────────────────────────────────
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> 
> User UID:    1000
> User GID:    1000
> ───────────────────────────────────────
> Setting user to 1000:1000
> Updating permissions...
> ... Config directory : /data
> ... data directory detected : /share/nextcloud
> ... setting permissions
> ... done
>  
> using keys found in /data/config/keys
> Initializing nextcloud 28.0.1.1 (this can take a while) ...
> Setting permissions
> New nextcloud instance
> Please run the web-based installer on first connect!
> Initializing finished
> After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
> Alternatively, you can apply your own configurations by editing /data/config/www/nextcloud/config/config.php following the documentation:
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
> Starting...
> /etc/cont-init.d/01-config_yaml.sh: executing
> Setting permissions for the config.yaml directory
> 
> Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
> If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
> ---------------------------------------------------------
> Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
> 
> ... no env variables found, exiting
> [custom-init] No custom files found, skipping...
> crond: crond (busybox 1.36.1) started, log level 8
> [ls.io-init] done.

**Comment by alexbelgium** [comment]
> I have an new setup and the 02-mariadb_discovery.sh script is not loading. is it normal? But it looks that the mounting is working.
> 
> > Starting...
> > /etc/cont-init.d/00-banner.sh: executing
> > 
> > ## Add-on: Nextcloud
> > Nextcloud for Homeassistant
> > ## Add-on version: 28.0.1-5
> > You are running the latest version of this add-on.
> > System: Home Assistant OS 11.4  (amd64 / generic-x86-64)
> > Home Assistant Core: 2024.1.3
> > Home Assistant Supervisor: 2023.12.0
> > ## Please, share the above information when looking for help
> > or support in, e.g., GitHub, forums
> > ## Provided by: https://github.com/alexbelgium/hassio-addons
> > ## Defining permissions for main user :
> > User UID: 1000
> > User GID : 1000
> > ## /etc/cont-init.d/00-global_var.sh: executing
> > Full_Text_Search='false'
> > OCR='false'
> > OCRLANG='fra'
> > PGID='1000'
> > PUID='1000'
> > additional_apps='inotify-tools'
> > certfile='fullchain.pem'
> > elasticsearch_server='ip:port'
> > enable_thumbnails='true'
> > keyfile='privkey.pem'
> > localdisks='nvme1n1p1'
> > trusted_domains='your-domain, your-domain2'
> > use_own_certs='false'
> > /etc/cont-init.d/00-local_mounts.sh: executing
> > ## [19:03:30] INFO: Available Disks for mounting :
> > NAME        LABEL       SIZE FSTYPE   RO
> > └─nvme1n1p1 PlexMedia 476.9G ext4      0
> > ├─nvme0n1p2              24M squashfs  0
> > ├─nvme0n1p3             256M squashfs  0
> > ## Supported fs :  ext3 ext2 ext4 squashfs vfat msdos iso9660
> > Inspired from : github.com/dianlight
> > Local Disks mounting...
> > ... nvme1n1p1 is a physical device
> > [19:03:31] INFO: Mounting nvme1n1p1 of type ext4
> > [19:03:31] INFO: Success! nvme1n1p1 mounted to /mnt/nvme1n1p1
> > /etc/cont-init.d/00-smb_mounts.sh: executing
> > /etc/cont-init.d/01-config_yaml.sh: executing
> > Setting permissions for the config.yaml directory
> > ## Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
> > If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
> > Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
> > ... no env variables found, exiting
> > [migrations] started
> > [migrations] 01-nginx-site-confs-default: skipped
> > [migrations] 02-default-location: skipped
> > [migrations] done
> > Setting permissions for the config.yaml directory
> > ## Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
> > If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
> > Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
> > ... no env variables found, exiting
> > Execute /homeassistant/addons_config/nextcloud-ocr/nextcloud-ocr.sh if existing
> > Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
> > ───────────────────────────────────────
> > 
> > |     |  |  |   __|_   _|     |     |
> > |   --|  |  |__   | | | |  |  | | | |
> > |_**|**_|_**| |_| |**_|_|_|_|
> > _____ __ __ _ __    ____
> > | __  |  |  | |  |  |    \
> > | __ -|  |  | |  |**|  |  |
> > |**_**|**___|_|_____|____/
> > Based on images from linuxserver.io
> > ───────────────────────────────────────
> > To support LSIO projects visit:
> > https://www.linuxserver.io/donate/
> > ───────────────────────────────────────
> > GID/UID
> > ───────────────────────────────────────
> > User UID:    1000
> > User GID:    1000
> > ───────────────────────────────────────
> > Setting user to 1000:1000
> > Updating permissions...
> > ... Config directory : /data
> > ... data directory detected : /share/nextcloud
> > ... setting permissions
> > ... done
> > using keys found in /data/config/keys
> > Initializing nextcloud 28.0.1.1 (this can take a while) ...
> > Setting permissions
> > New nextcloud instance
> > Please run the web-based installer on first connect!
> > Initializing finished
> > After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
> > Alternatively, you can apply your own configurations by editing /data/config/www/nextcloud/config/config.php following the documentation:
> > https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
> > https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
> > Starting...
> > /etc/cont-init.d/01-config_yaml.sh: executing
> > Setting permissions for the config.yaml directory
> > ## Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
> > If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
> > Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
> > ... no env variables found, exiting
> > [custom-init] No custom files found, skipping...
> > crond: crond (busybox 1.36.1) started, log level 8
> > [ls.io-init] done.

Not normal indeed I wonder why i'll check

**Comment by alexbelgium** [comment]
Stats again in new version - i don't know why but the scripts fails when executed  with `source`,and succeed when executed with `.`... Well then I've reverted the main script calling the subscripts and everything is working again

**Comment by XneddyX** [comment]
all ist working again and i can see the mount in nextcloud. i you can implement this into Plex, it would be fine. I think we can close this request... thank you very much.
