### ISSUE TITLE
🐛 [plex-meta-manager] Switch to original branch

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#1184]
### Description

Now you use: https://hub.docker.com/r/linuxserver/plex-meta-manager/tags but I expierenced a [bug](https://github.com/meisnate12/Plex-Meta-Manager/issues/1827) and they suggest to switch to the original branch which makes way more sense.
Switch to: [meisnate12/plex-meta-manager](https://hub.docker.com/r/meisnate12/plex-meta-manager)

### Reproduction steps

```bash
NA
```

### Addon Logs

```bash
NA
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Sorry this branch is based on a Python entrypoint and much more complex to use than the linuxserver one, I'll keep the addon on the current upstream image - usually Linuxserver is really fast in updates

**Comment by bruvv** [comment]
Fair point
