### ISSUE TITLE
✨ [REQUEST] Whatsapper

### ISSUE THREAD

**Issue by baldarn** [alexbelgium/hassio-addons#1188]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

I created a mini web proxy for the `whatsapp.js` project. this could be useful to have a whatsapp bot in home assistant!

https://github.com/baldarn/whatsapper

what do you think?

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

add whatsapper to this addons list

**Comment by alexbelgium** [comment]
Hi, it doesn't find the "latest" tag on dockerhub - is it public?
`ERROR: failed to solve: whatsapper/whatsapper:latest: docker.io/whatsapper/whatsapper:latest: not found`

https://github.com/alexbelgium/hassio-addons/actions/runs/7601097640/job/20700121870

**Comment by baldarn** [comment]
mmm will see this today or worst case tomorrow

**Comment by alexbelgium** [comment]
Just pull request a new config version (such as 0.02) and it will rebuild on the repo

**Comment by baldarn** [comment]
let's try if this solves :/

https://github.com/alexbelgium/hassio-addons/pull/1196

**Comment by alexbelgium** [comment]
Thanks, trying build

**Comment by baldarn** [comment]
mmmm still something wrong :/

**Comment by baldarn** [comment]
should fix
https://github.com/alexbelgium/hassio-addons/pull/1200

**Comment by baldarn** [comment]
still not running. It works if `docker run` that... could you give me a hint @alexbelgium ?

**Comment by alexbelgium** [comment]
not sure to understand, the addon doesn't run but docker run does ? I'll check on my system

**Comment by baldarn** [comment]
yes, if you do 
`docker run --name whatsapper -p 3000:3000 baldarn/whatsapper`

it works, but the addon starts and auto shutdown :/

**Comment by baldarn** [comment]
this is the full log

```
-----------------------------------------------------------
 Add-on: Whatsapper
 Whatsapper for Home Assistant
-----------------------------------------------------------
 Add-on version: 2024.1.22
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (amd64 / qemux86-64)
 Home Assistant Core: 2024.1.5
 Home Assistant Supervisor: 2023.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /addon_configs/db21ed7f-whatsapper/config.yaml
---------------------------------------------------------

Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /addon_configs/db21ed7f-whatsapper/whatsapper.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
 
Starting the upstream container
 
Starting...
 
Starting the upstream container

```

**Comment by alexbelgium** [comment]
yes exactly that ; your entrypoint is missing. I've pushed a new version without my entrypoint and we'll see how that goes

**Comment by baldarn** [comment]
hi, why this?

https://github.com/alexbelgium/hassio-addons/commit/42dee1495057962b6cf3a44d928e2a3446054d37

I have an amd64 server :), can't test this :/

**Comment by alexbelgium** [comment]
I removed the wrong one :) corrected

**Comment by baldarn** [comment]
great! it works!

thanks for the assistance!

now I will work on the home assistant integration ;)

**Comment by PiperNigrum** [comment]
Hi, is it possible to support other architectures too?
I have a RP4 and this stuff sounds great ;)

Thanks

**Comment by alexbelgium** [comment]
Hi @baldarn do you have a way to make dockerhub aarch64 builds?

**Comment by baldarn** [comment]
@alexbelgium dunno, never did that. I can try, but tomorrow :)
if you have a quick solution is more that welcome!

**Comment by alexbelgium** [comment]
Only did builds by using someone else code ;-) so not sure how to help here!

**Comment by baldarn** [comment]
hopefully I did it ;)

@alexbelgium can you merge https://github.com/alexbelgium/hassio-addons/pull/1203 ?
@PiperNigrum can you try?

**Comment by PiperNigrum** [comment]
![image](https://github.com/alexbelgium/hassio-addons/assets/16720769/8d626fcc-058e-424b-9a2c-9fa125016211)

It seems to work.
Is it possible to Display the QR-Code in a normal way?

**Comment by baldarn** [comment]
something should be coming ;)
https://github.com/alexbelgium/hassio-addons/pull/1204

**Comment by baldarn** [comment]
@PiperNigrum done.

you can navigate to the path `/qr` and be linked to a qr code visualizer. ;)

**Comment by baldarn** [comment]
let's close this. if more requests arrive other issues will be opened ;)
