### ISSUE TITLE
Local build images fill backup files, possible to exclude docker image?

### ISSUE THREAD

**Issue by MaxWinterstein** [alexbelgium/hassio-addons#119]
Coming from [my own add-on repository](https://github.com/MaxWinterstein/homeassistant-addons/issues/58) I found the same thing here too:

All add-ons, that don't provide pre-build images, have their docker image stored in the backup file.

From maintainer to maintainer, did you find any solution to this?

**Comment by alexbelgium** [comment]
Hi, I escalated that to the HA team here https://github.com/home-assistant/supervisor/issues/3223#issuecomment-988703018 and they said the solution is to avoid local build... ;) easier said than done, as it seems, we need to have only one add per github repo to allow automatic builds to dockerhub.

I think it's possible to build docker images from a single repo subfolder but haven't really looked at it...

My own intermediate solution is that I've created a shell script :
 ```yaml
shell_command:
  repair_images: 'echo "starting repair" && ha su repair && echo "repair done"'
```
And an automation to execute that every Saturday! The HA su repair command removes dangling images...

Happy if you have any other ideas / recommendations / solutions to build docker images from a single repo subfolders!

Have a nice day

**Comment by alexbelgium** [comment]
Oups actually I answered to another problem than the one you describe!

The fact that when local building, it fills space with dangling images and the total available space slowly decreases without any other visible changes.

Regarding the storage of the image in the backup, I've also tried to exclude the image but it doesn't work... My solution is to externalise the addon data in /condif/addon name instead of storing it in /data. But bottom line HA is really pushing us toward docker images automatic builds...

**Comment by MaxWinterstein** [comment]
> Regarding the storage of the image in the backup, I've also tried to exclude the image but it doesn't work... My solution is to externalise the addon data in /condif/addon name instead of storing it in /data, and only backup that and not the addon. But bottom line HA is really pushing us toward docker images automatic builds...

Nice workaround :+1:

I guess the only solution, therefore, is to use pre-build images. Bummer inho.

**Comment by alexbelgium** [comment]
Fully agree. The HA dev are really pushing hard in this direction. Actually, people on HA supervised have several of issue on local builds, and I had to put workarounds in all my dockerfiles. So this will be better once we avoid local builds. My key issue is automatizing images building when we have (like yours or mine) several addons in different folders on a same repo. I think it's still possible to build each folder separately but haven't started looking at it yet... As this still complexifies dev and maintenance.

**Comment by tyjtyj** [comment]
we can run docker image prune --all. 

This will clean up the residue

```
~# docker image prune --all
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
............................................
............................................
Total reclaimed space: 1.461GB
```

**Comment by alexbelgium** [comment]
Thanks Tyjtyj. @MaxWinterstein : be aware we can't migrate from a locally build to an autobuild addon for the moment : https://github.com/home-assistant/supervisor/issues/3414

**Comment by felipecrs** [comment]
FYI this is no longer an issue thanks to https://github.com/home-assistant/supervisor/pull/5974 (unreleased ATM).
