### ISSUE TITLE
✨ [REQUEST] FreeGames Claimer: Expose the env settings in the Addons GUI

### ISSUE THREAD

**Issue by yoshimo** [alexbelgium/hassio-addons#1193]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

FreeGames Claimer

### Is your feature request related to a problem? Please describe

Figuring out available config file settings is a bit annoying, so is editing the env file manually.

### Describe the solution you'd like

The Addon configuration tab inside HA already has things like the vnc port or the modules that should be run exposed, similiar things should be done for the main settings shown on https://github.com/vogler/free-games-claimer#configuration--options

**Comment by alexbelgium** [comment]
Hi, the config env is already exposed here : https://github.com/alexbelgium/hassio-addons/tree/master/free_games_claimer#configuration

Or were you thinking about something else?

**Comment by yoshimo** [comment]
You are not able to see or change them in 
![image](https://github.com/alexbelgium/hassio-addons/assets/17909/0ba34e49-aff3-403a-a610-038ebac1cb87)
It would be helpful to have textboxes for password&usernames or things like "subscribe to the newsletter" and other things

**Comment by alexbelgium** [comment]
Ah, I undertand... this is not possible as too many options exists. And the app itself is not made for that. You need to manually update the ENV file with an add-on such as Filebrowser
