### ISSUE TITLE
🐛 [Mealie] 502 Bad Gateway

### ISSUE THREAD

**Issue by gschmidl** [alexbelgium/hassio-addons#1197]
### Description

Running on Home Assistant Yellow.

Since the update, I get a 502 Bad Gateway error from Mealie.

See the log below - those last two lines continue infinitely.

When trying to load the UI, this also appears (I masked out my duckdns hostname)

```
2024/01/22 12:05:23 [error] 352#352: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.223, server: db21ed7f-mealie, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9925/", host: "xxx:9090"
[22/Jan/2024:12:05:23 +0100] 502 -(192.168.1.223) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
usermod: no changes
2024/01/22 12:05:23 [error] 352#352: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.223, server: db21ed7f-mealie, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9925/", host: "xxx:9090"
[22/Jan/2024:12:05:23 +0100] 502 -(192.168.1.223) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
Switching to dedicated user
usermod: no changes
2024/01/22 12:05:23 [error] 352#352: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.223, server: db21ed7f-mealie, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:9925/favicon.ico", host: "xxx:9090", referrer: "https://xxx:9090/"
[22/Jan/2024:12:05:23 +0100] 502 -(192.168.1.223) GET /favicon.ico HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
```

### Reproduction steps

```bash
1. Start the addon
2. Click "Open UI"
3. See error
```

### Addon Logs

```bash
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------

 Add-on: Mealie (Omni):
 Mealie is a self hosted recipe manager and meal planner built in Vue
-----------------------------------------------------------
 Add-on version: v1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / yellow)
 Home Assistant Core: 2024.1.5
 Home Assistant Supervisor: 2023.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
ALLOW_SIGNUP='false'
PGID='0'
PUID='0'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='true'
Timezone set from Etc/UTC to Europe/Vienna
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/addons_config/mealie/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/mealie/config.yaml
---------------------------------------------------------

Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/mealie/mealie.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/31-nginx.sh: executing
[12:04:13] INFO: Exporting variables
ALLOW_SIGNUP=false
PGID=0
PUID=0
certfile=fullchain.pem
keyfile=privkey.pem
ssl=true
[12:04:15] INFO: config.yaml found in /config/addons_config/mealie/config.yaml, exporting variables
Permissions adapted
[12:04:15] INFO: Starting nginx
[12:04:15] INFO: Starting app
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
```

### Architecture

aarch64

### OS

HAos

**Comment by Rykian** [comment]
Just encountered the same issue. I used another PGID/PUID and it worked again.

**Comment by SeeThisIsMe** [comment]
Same for me too

**Comment by alexbelgium** [comment]
Probably 0 isn't supported anymore i'll switch default to 1000

**Comment by Rykian** [comment]
Maybe you have the same problem as me: #1198

**Comment by GrappaTV** [comment]
> Maybe you have the same problem as me: #1198

If you enter a portnr for the API then it is this portnr that gave me WEB access (not the one defined under Web access....)

**Comment by alexbelgium** [comment]
Thanks i'll look to adapt when i'll have some time!

**Comment by gschmidl** [comment]
> Seems the port of Mealie Web UI changed from 3000 to 9000
> 
> 
> This workes for me for now

What did you set the other one too? :9090 does give me the login window but nothing works, and when I hit F5, I get an SSL error.

**Comment by m4um4u1** [comment]
> > Seems the port of Mealie Web UI changed from 3000 to 9000
> > This workes for me for now
> 
> What did you set the other one too? :9090 does give me the login window but nothing works, and when I hit F5, I get an SSL error.

The other one I put to :9091

**Comment by gschmidl** [comment]
Ok, if I set API to 9090 and the other to 9091, I can go to 9090, but not log in or do anything else. Going to 9090 gives the original 502 error. I'll wait for the next version.

**Comment by JohnnyPicnic** [comment]
Hi all, I made the request to update to the latest version but it appears I failed in fully testing the new version. Probably best to revert to v1.0.0-RC1.1 and have someone who knows what they are doing push v1.0.0

**Comment by alexbelgium** [comment]
The issue is that the code changed to launch the front-end between the omni and this version ; i'll check how to solve it it's not difficult it's just I need to find some time

**Comment by alexbelgium** [comment]
Hi, confirmed to start on my system - please be sure to check that you have kept all data ! I've also added an automatic conversion of users from 0:0 to 1000:1000

**Comment by SeeThisIsMe** [comment]
So can someone please confirm exactly what port should be used? Is it 9090 or 9091 for the web interface field? 

The field for the API port has now disappeared for me so I can't configure that anymore. I tried a few ports for the web interface and I can login and view the recipes, but SSL doesn't work now and i get a security error when using HTTPS saying the site doesn't have a certificate, if i change the protocol to HTTP it works.

**Comment by alexbelgium** [comment]
Hi, 9090 (mapped to 9000) is the web interface ; 9091 ( mapped to 9001) is the https web interface available only if ssl is enabled ; when looking at the docker compose from the 1.0.0 image I don't see anymore an API port referenced

**Comment by SeeThisIsMe** [comment]
Thanks for the reply. I think there is something wrong with the SSL bit. I have it configured as you describe but SSL/HTTPS just will not work :( HTTP does work.

**Comment by alexbelgium** [comment]
Ssl is not supported by Mealie actually (I think) so it's managed through an additional layer of nginx proxy (that's why there is a different port). I'll check how to adapt

**Comment by SeeThisIsMe** [comment]
Thanks, but I'm afraid it doesn't work for me at all now :( tried with ssl enabled and disabled, https and http, and port 9001 and 9000.

**Comment by m4um4u1** [comment]
Maybe I should add here that it workes for me because I'm using a reverse proxy for my ssl. So I'm not sure about the internal ssl stuff. Http works fine though.

In the newest official mealie docker file I only saw one port exposed which is 9000 using an Environment Variable which is APP_PORT I think. I have to recheck on that later.

**Comment by SeeThisIsMe** [comment]
> Thanks, but I'm afraid it doesn't work for me at all now :( tried with ssl enabled and disabled, https and http, and port 9001 and 9000.

Ahh my bad. I missed updating a port forwarding rule with all the port changes. Ssl does now work for me with the latest version using https://url:9090. Thanks!

**Comment by alexbelgium** [comment]
Indeed sorry for the changes but I think in the long term it will be easier for users. Tested with both http and https (once ssl option is activated) and it seems to work!

**Comment by gschmidl** [comment]
Yup, now it works again. Thank you!

**Comment by Scags104** [comment]
Sorry to reopen this but since the update i have not been able to hit this externally. 

Using port 9001 in config
Nginx proxy manager routing externalurl to internal ip:9001
SSL enabled. 

What am i missing? internal IP works fine, cant hit it from external url

Thanks
