### ISSUE TITLE
Update of Photoprism not possible due to ha error message

### ISSUE THREAD

**Issue by sbonn13** [alexbelgium/hassio-addons#120]
In HA Supervisor a warning message appeared at the Photoprism page "[...]/hassio/addon/db21ed7f_photoprism"

> "You have Home Assistant 2021.12.3 installed, to upgrade to this version of the add-on you need at least Home Assistant version ."

Therefore no update is execute. It looks strange as the to-be Home Assistant version is not mentioned in the error message.
Do you have any idea?

My current version of your photoprism AddOn is: 210217-49039368-5 on a Raspberry Pi 4 8GB
Logfile shows:
 Add-on version: 210217-49039368-5
 There is an update available for this add-on!
 Latest add-on version: 20211215
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 7.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.12.3
 Home Assistant Supervisor: 2021.12.2

**Comment by alexbelgium** [comment]
Weird. I added a minimum version requirement in the config (there was none) and pushed a new version, let me know if it works!

**Comment by sbonn13** [comment]
Simple trick, which worked. Yes, everything is great again. Issue solved. Thanks for your assistance.

**Comment by alexbelgium** [comment]
Great, thanks for reporting! Weird issue indeed
