### ISSUE TITLE
[Mealie] PermissionError: [Errno 13] Permission denied: '/config/addons_config/mealie_data/.secret'

### ISSUE THREAD

**Issue by jack5mikemotown** [alexbelgium/hassio-addons#1201]
### Description

When trying to start mealie, I'm now getting this error. The last confirmed version that works for me is v1.0.0-RC. I started experiencing this issue today when I updated to v1.0.0.5. If I downgrade to v1.0.0, I get a different error where it repeats the following line: 

```
Switching to dedicated user
usermod: no changes
```

On v1.0.0, if i change my uid/gid from 0 to 1000, I get the same error as I do on v1.0.0.5 and above.
The full traceback is below:

```Switching to dedicated user

        User uid:    1000
        User gid:    1000
        
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 10, in <module>
    from mealie.core import root_logger
  File "/app/mealie/core/root_logger.py", line 60, in <module>
    logger_config = get_logger_config()
  File "/app/mealie/core/root_logger.py", line 28, in get_logger_config
    settings = get_app_settings()
  File "/app/mealie/core/config.py", line 40, in get_app_settings
    return app_settings_constructor(env_file=ENV, production=PRODUCTION, data_dir=determine_data_dir())
  File "/app/mealie/core/settings/settings.py", line 190, in app_settings_constructor
    **{"SECRET": determine_secrets(data_dir, production)},
  File "/app/mealie/core/settings/settings.py", line 16, in determine_secrets
    if secrets_file.is_file():
  File "/usr/local/lib/python3.10/pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/config/addons_config/mealie_data/.secret'
```

### Reproduction steps

bash
1. Update to v1.0.0 or above
2. Make sure UID/GID is not 0
3. Start the add-on
4. Error appears

### Addon Logs

```bash
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Mealie (Omni):
 Mealie is a self hosted recipe manager and meal planner built in Vue
-----------------------------------------------------------
 Add-on version: v1.0.0
 There is an update available for this add-on!
 Latest add-on version: v1.0.0-7
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 11.4  (amd64 / qemux86-64)
 Home Assistant Core: 2024.1.5
 Home Assistant Supervisor: 2023.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
ALLOW_SIGNUP='false'
PGID='1000'
PUID='1000'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='true'
Timezone set from Etc/UTC to America/New_York
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/addons_config/mealie/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/mealie/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables

... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/mealie/mealie.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/31-nginx.sh: executing
[16:21:15] INFO: Exporting variables
ALLOW_SIGNUP=false
PGID=1000
PUID=1000
certfile=fullchain.pem
keyfile=privkey.pem
ssl=true
[16:21:18] INFO: config.yaml found in /config/addons_config/mealie/config.yaml, exporting variables
Permissions adapted
[16:21:18] INFO: Starting nginx
[16:21:18] INFO: Starting app
Switching to dedicated user

        User uid:    1000
        User gid:    1000
        
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 10, in <module>
    from mealie.core import root_logger
  File "/app/mealie/core/root_logger.py", line 60, in <module>
    logger_config = get_logger_config()
  File "/app/mealie/core/root_logger.py", line 28, in get_logger_config
    settings = get_app_settings()
  File "/app/mealie/core/config.py", line 40, in get_app_settings
    return app_settings_constructor(env_file=ENV, production=PRODUCTION, data_dir=determine_data_dir())
  File "/app/mealie/core/settings/settings.py", line 190, in app_settings_constructor
    **{"SECRET": determine_secrets(data_dir, production)},
  File "/app/mealie/core/settings/settings.py", line 16, in determine_secrets
    if secrets_file.is_file():
  File "/usr/local/lib/python3.10/pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/config/addons_config/mealie_data/.secret'
```

### Architecture

amd64

### OS

HAos, Virtual Machine

**Comment by khaffner** [comment]
I have the same issue. With auto update of the Add-On enabled and it suddenly no longer starting, WAF dropped hard.

**Comment by alexbelgium** [comment]
Ahah I want to keep peace in the house i'll look at it ;) last version didn't help I guess I tried to explicitly set all permissions on the file. Anything special in the log?

**Comment by khaffner** [comment]
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Mealie
 Mealie is a self hosted recipe manager and meal planner built in Vue
-----------------------------------------------------------
 Add-on version: v1.0.0-8
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (amd64 / qemux86-64)
 Home Assistant Core: 2024.1.3
 Home Assistant Supervisor: 2023.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
ALLOW_SIGNUP='true'
DATA_DIR='/config/addons_config/mealie_data'
PGID='1000'
PUID='1000'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='false'
Timezone set from Etc/UTC to Europe/Oslo
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/addons_config/mealie/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/mealie/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables

... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/mealie/mealie.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/31-nginx.sh: executing
[08:27:58] INFO: Exporting variables
ALLOW_SIGNUP=true
DATA_DIR=/config/addons_config/mealie_data
PGID=1000
PUID=1000
certfile=fullchain.pem
keyfile=privkey.pem
ssl=false
[08:27:59] INFO: Checking user type
[08:27:59] INFO: config.yaml found in /config/addons_config/mealie/config.yaml, exporting variables
Permissions adapted
[08:27:59] INFO: Starting nginx
[08:27:59] INFO: Starting app
Switching to dedicated user

        User uid:    1000
        User gid:    1000
        
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 10, in <module>
    from mealie.core import root_logger
  File "/app/mealie/core/root_logger.py", line 60, in <module>
    logger_config = get_logger_config()
  File "/app/mealie/core/root_logger.py", line 28, in get_logger_config
    settings = get_app_settings()
  File "/app/mealie/core/config.py", line 40, in get_app_settings
    return app_settings_constructor(env_file=ENV, production=PRODUCTION, data_dir=determine_data_dir())
  File "/app/mealie/core/settings/settings.py", line 190, in app_settings_constructor
    **{"SECRET": determine_secrets(data_dir, production)},
  File "/app/mealie/core/settings/settings.py", line 16, in determine_secrets
    if secrets_file.is_file():
  File "/usr/local/lib/python3.10/pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/config/addons_config/mealie_data/.secret'

**Comment by alexbelgium** [comment]
I've an idea I'll push a test version in 15 min (once I've fetched my coffee). Unless I can replicate it risks being trial and errors 

I'll check also what changed upstream to try to force 0 usage ; much easier for users

**Comment by alexbelgium** [comment]
mmh I can't find a way to replicate the error, even when chmodding .secret to another user, changing permissions...
I'll try to push again a version that will make a specific debug message on the file

**Comment by alexbelgium** [comment]
argh crazy no reason for that at all as I force permissions on that exact file, and I can't replicate... I'll think about it

**Comment by alexbelgium** [comment]
Please try version -10 with UID and PID 0

**Comment by alexbelgium** [comment]
Restoring does not work as the database is stored in the /config folder ; you therefore need to recover from a backup your /config/addons_config/mealie_data folder ; put it in the current installation, and restart the old version. One day I'll migrate to the new ha config system implemented one month ago but this too could lead to breaking changes 

Are you logged in as Mealie 1.0 sets recipes in private by default according to their changelog?

Btw this is a major change as first time the app goes in release by the Mealie team,  so future updates will be seamless once this one is passed

**Comment by jack5mikemotown** [comment]
> Please try version -10 with UID and PID 0, I've re-enabled it and set it as default again

Updated to v1.0.0-10 and things seems to be working a-ok for me

**Comment by khaffner** [comment]
I "fixed" it on my end by deploying mealie outside of Home Assistant and migrating the data over there.
