### ISSUE TITLE
🐛 [Sonarr] Backup file not found

### ISSUE THREAD

**Issue by norbertjoni** [alexbelgium/hassio-addons#1211]
### Description

I was try to download the backupfile from sonarr (and also radarr) and I got this error on the screen:

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-da4ce6b1687b8d89d64d733d384c8073-4f288a8469d48dbf-00"
}

### Reproduction steps

```bash
1. Go to 'System'
2. Click on 'Backup'
3. Scroll down to 'name of my backup to download'
4. See error
```

### Addon Logs

```bash
[Warn] BackupFileMapper: File /config/addons_config/sonarr/Backups/scheduled/api/hassio_ingress/kBIdrHUyHoWaT4eN-uO1TBgLq8GbJU/sonarr_backup_v4.0.0.751_2024.01.09_20.01.44.zip not found
```

### Architecture

armv7

### OS

HAos

**Comment by norbertjoni** [comment]
I can access the backup file with Filebrowser so winwin..

**Comment by alexbelgium** [comment]
Hi, rename your folder any name than sonarr and it should work ! It is due to a workaround implemented for ingress

**Comment by alexbelgium** [comment]
Hi, rename your folder any name than sonarr and it should work ! It is due to a workaround implemented for ingress
