### ISSUE TITLE
Browserless Chrome: Add on Does not start since 2.1.0 upgrade

### ISSUE THREAD

**Issue by wigster** [alexbelgium/hassio-addons#1212]
### Description

Since the 2.1.0 upgrade the add-on does not start. I have tried uninstalling and installing again.

### Reproduction steps

```bash
1. Install v 2.1.0 of browserless chrome
2. Start
```

### Addon Logs

```bash
exec ./start.sh: exec format error
```

### Architecture

aarch64 -- corrected

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks that's a wrong architecture in the upstream image my addon is based on. I've launched a rebuild if they corrected the issue

**Comment by wigster** [comment]
Hi

Not sure if 2.1.0-2 was supposed to resolve this, but it didn't. I did want to also add that I picked the wrong architecture in the option. It's aarch64 in fact.

**Comment by alexbelgium** [comment]
Hi, probably the upstream maintainer has uploaded a wrong architecture, like amd64 under a aarch64 tag which would create this error... Now we need to wait for him to update his image and I can update my container. Here is the confirmation : https://github.com/browserless/browserless/issues/3803

**Comment by wigster** [comment]
Thanks! I've reverted to 2.0 and will wait. Thanks a lot for maintaining this.

**Comment by alexbelgium** [comment]
Thanks! And you're actually right i'll revert the whole addon as anyway the next upstream update will trigger also an addon update

**Comment by shirou93** [comment]
Hi,

2.1.0-2 have errors:

browserless.io:index Starting metrics collection. +5ms
  browserless.io:error No handler or file found for resource / +0ms
  browserless.io:error No handler or file found for resource / +5s

**Comment by MathiasReker** [comment]
@alexbelgium can you make a new build? 🙏😊

**Comment by shirou93** [comment]
Hi,

2.1.0-3 build still not working.

**Comment by MathiasReker** [comment]
Thank you @alexbelgium 
However the problem still exist. Is it possible to use the old docker image?

**Comment by alexbelgium** [comment]
Hi, I've changed the endpoint to check

**Comment by shirou93** [comment]
Unfortunately errors still occurs.

**Comment by alexbelgium** [comment]
Which error exactly? If `No handler or file found for resource / ` then it is not an error : the url should end with /docs (corrected in webui) and not /.

If the functions of browserless itself you should probably check if it is not due the apps change when going from version 1 to 2

**Comment by shirou93** [comment]
> Which error exactly? If `No handler or file found for resource / ` then it is not an error : the url should end with /docs (corrected in webui) and not /.
> 
> If the functions of browserless itself you should probably check if it is not due the apps change when going from version 1 to 2

Yes. Sorry my mistake V2 was droped selenium support.

**Comment by alexbelgium** [comment]
If everyone prefers i can revert to v1 then just let me all know

**Comment by shirou93** [comment]
> If everyone prefers i can revert to v1 then just let me all know
Thank you but i prefer rewrite my script for V2 :)

**Comment by alexbelgium** [comment]
Perfect! And indeed more sustainable as v1 won't be developed anymore. Thanks!

**Comment by MathiasReker** [comment]
V2 has a bug that makes it impossible to work in my case. I dont find it stable yet. Will it be possible to create another repository for v1? 😁
