### ISSUE TITLE
Mealie

### ISSUE THREAD

**Issue by duczz** [alexbelgium/hassio-addons#1220]
Mealie

Thanks for this repo, does ythis repo support the Security variables too?
https://nightly.mealie.io/documentation/getting-started/installation/backend-config/

**Comment by alexbelgium** [comment]
Hi, any custom variable can be added using this system embedded in all my add-ons : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables

**Comment by duczz** [comment]
Ahhh, perfectly thank your 👍🏻
