### ISSUE TITLE
❓ [addon] Paperless-ngx Network storage save problem 

### ISSUE THREAD

**Issue by bjk201** [alexbelgium/hassio-addons#1222]
**Paperless-ngx**

name: mount and safe data on Synology network drive 

Hello everyone,

I have installed the addon and want all documents and data to be saved on the external hard disk attached to the Synology Nas.

I have entered the data once in /config/config.yaml and under "/addon_configs/db21ed7f_paperless_ng/config.yaml" with the help of the file browser:

CONFIG_LOCATION: /config/config.yaml
OCRLANG: ENG FRA DEU
PAPERLESS_OCR_MODE: skip
PGID: 0
PUID: 0
certfile: fullchain.pem
keyfile: privkey.pem
ssl: false
networkdisks: //192.168.1.XX/usbshare1/HASS/paperless
cifsusername: USERXXX
cifspassword: PWXXXX
PAPERLESS_MEDIA_ROOT: //192.168.1.XX/usbshare1/HASS/paperless/media
PAPERLESS_DATA_DIR: //192.168.1.XX/usbshare1/HASS/paperless/data
PAPERLESS_CONSUMPTION_DIR: //192.168.XX/usbshare1/HASS/paperless/consume
TZ: Europe/Berlin
cifsdomain: //192.168.1.XX

If I now upload a file, it is still saved under addon_configs/db21ed7f_paperless_ng/media/documents/. 

Thank you

**Comment by kolossboss** [comment]
Hi,

you have to mount the network path and then set the mount point for paperless. Looks like this

```
networkdisks: //192.168.1.XX/usbshare1/HASS/paperless
PAPERLESS_MEDIA_ROOT: /mnt/paperless/media
```

**Comment by alexbelgium** [comment]
Addon deprecated, I recommend to use this one : https://github.com/BenoitAnastay/home-assistant-addons-repository
