### ISSUE TITLE
❓ [Postgres] 500 Server Error 

### ISSUE THREAD

**Issue by peeter22** [alexbelgium/hassio-addons#1229]
Postgres

Hi.
I was using the Postgres addon for about 2-3 months without any issue but now I am getting a 500 Server Error at startup

> 
> Failed to start add-on
> 
> 500 Server Error for http+docker://localhost/v1.43/containers/addon_db21ed7f_postgres/json: Internal Server Error ("stat /mnt/data/docker/overlay2/03e49666a5a413dfe95cc1bccbbb28c778cde91fb91166c32d00cf688b539eae: no such file or directory") 

The addon worked out of the box without any setup previously, so I tried to restore default configuration, restoring back an older version as well as completely removing and reinstalling the addon, but nothing helped.

Do you have any idea what should I try ?

**Comment by alexbelgium** [comment]
Argh i had to implement a new extension and fear it might have messed up. I'll test on my system

**Comment by peeter22** [comment]
Unfortunately I only have the version 15.5 backed up. Which I think was working before (not 100% sure) but it is giving the same error.

**Comment by alexbelgium** [comment]
15.5 should have been good (prior the disruptive changes) and database is stored in the addon itself. Do you know what is /mnt/data/docker did you have a specific option defined somewhere in the add-on with that?

Error 500 might be an HA issue and not add-on; you might try going in the terminal add-on and run `ha su repair` or already try just rebooting ha. The command I've described just before is super helpful it deletes dangling images to save place (images stored but actually useless) plus recreate the images used by add-ons to make sure everything works as it should

**Comment by peeter22** [comment]
thanks the repair command has helped not I just need to figure out what happened (or recreate) to the immich database
as I get this error 

2024-02-03 12:26:07.747 CET [277] FATAL:  database "immich" does not exist
