### ISSUE TITLE
🐛 [Postgres] Database size doubled when updating to 15.5-5

### ISSUE THREAD

**Issue by Blendi** [alexbelgium/hassio-addons#1233]
### Description

Since updating the Postgres from 15.5-4 to 15.5-5 the database backup size doubled from around 350mb to 700mb. 

I treid creating a backup via pgadmin tool from my pc and the backup was around 300mb. 

Not sure why, when homeassistant creates backup they takes double of the size after updating to 15.5-5 compared to backup taken when postgres 15.5-4.

Now the Postgress version I have is the last, I updated to 15.5-6. With latest postgress database backups did not change so again is around 700mb same as when postgress was in 15.5-5.

My suspicion is with 15.5-5 something changed and database size increased. Not sure though if this is a normal behavior, something to be expected or if some unnecessary data is duplicated in database.

I will try to do some tests and backup restore immich database in a different machine, will try both haos restore and pgadmin tool restore. I will update when I have resulta 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
Backup from 15.5-4 350MB
Backup from 15.5-5 ~700MB
Backup from 15.5-6 ~700MB
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, the database was moved from /data to /config. It would be interesting if you open your backup with 7zip (for example) and check where the files taking place are located

Thanks!

**Comment by Blendi** [comment]
Hello,

Just did now a comparison and unzipped both backups. Almost all other files in the back did not change in size except from those located in database folder. I see inside database folders pg_notify, pg_subtrans, pg_vector and pg_wal have increased substantially. especially pg_wal has the most increase. I am starting to thing this is something to be expected from the last changes made in immich. I use postgres as the database for my immich add-on.

I better open an incident to Immich (https://github.com/immich-app/immich/issues) as I believe this looks to be related more with immich than with postgres. 
![2024-02-05 13_19_59-C__Users_AC17081_Desktop_db21ed7f_postgres 15 5-6 tar_config_database_](https://github.com/alexbelgium/hassio-addons/assets/3333692/6d50024a-3087-44b1-811b-b4a6daf7650d)

**Comment by alexbelgium** [comment]
Ah, this is indeed quite likely ! Immich is now forcing the usage of pg_vectors... Which honestly is very inconvenient as it seems pinned to a specific version and therefore causing issues for some people.
