### ISSUE TITLE
✨ [REQUEST] Gitea add Configuration for ALLOWED_DOMAINS

### ISSUE THREAD

**Issue by Torpedro1978** [alexbelgium/hassio-addons#1242]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Gitea 

### Is your feature request related to a problem? Please describe

I want to configure a migration (Mirror) from another Gitea instance, to do this, i click 
- top right + (Plus Sign)
- New Migration 

After filling out all the form with my data, i receive the error:
```
You cannot import from disallowed hosts, please ask the admin to check 
ALLOWED_DOMAINS/ALLOW_LOCALNETWORKS/BLOCKED_DOMAINS settings.
```
All that would be required ist to set my domains i wanto to sync with in the app.ini (example *.domain1.org, *.domain2.com)

```
[migrations]
ALLOWED_DOMAINS =*.domain1.org, *.domain2.com

```

### Describe the solution you'd like

Add new fields to the Addon-Configuration, just like the ROOT-URL

- ALLOWED_DOMAINS
- ALLOW_LOCALNETWORKS
- BLOCKED_DOMAINS

**Comment by alexbelgium** [comment]
Hi, you should probably be able to use this procedure to add custom environment variables : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables

**Comment by Torpedro1978** [comment]
But this is a setting in an ini file in a special section
`[migrations]`
I cannot image that an env can translate into an very specific ini setting. 
According th the documentation only a few env are supported:
https://docs.gitea.com/administration/environment-variables

**Comment by Torpedro1978** [comment]
Also when i use your link regarding adding env i cannot find gitea anywhere mentioned there. and also the search feature of  your filebrowser does not find it.

When i look into /addons_config/ or  /homeassistant/addons_config/ i can see 5 of my addons but not gitea! 

I can of course see /mnt/data/supervisor/addons/data/2937404c_gitea which contains the data inside the container (i can see basically the same with portainer).

But editing the app.ini directly inside the container seems to be neither supportet nor working as expexted.

**Comment by morganzion** [comment]
Same here, I want to configure gitea from the host but cannot find the volume/bind mount.

**Comment by alexbelgium** [comment]
Hi, I've added the addon_config folder in latest version. According to documentation all config should be achievable using env variables : https://docs.gitea.com/installation/install-with-docker#managing-deployments-with-environment-variables

**Comment by Torpedro1978** [comment]
Thank you very much!
It's working.
