### ISSUE TITLE
✨ [REQUEST] Baikal - Use alternate image that contains a fix for Home Asistant

### ISSUE THREAD

**Issue by mikedrawback** [alexbelgium/hassio-addons#1245]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Baikal

### Is your feature request related to a problem? Please describe

There is a bug in upstream Baikal with a timezone that makes Home Assistant unable to read calendars from the server. A solution was developed [here](https://github.com/sabre-io/dav/issues/1318#issuecomment-1872627379), but has to be reapplied every time the container restarts or updates.

### Describe the solution you'd like

 @MrAlucardDante has created an alternative docker container that is meant to be a drop in replacement with a fix in place at  ghcr.io/mralucarddante/baikal-docker-hass, with the [source here](https://github.com/MrAlucardDante/baikal-docker-hass).

**Comment by mikedrawback** [comment]
If you are comfortable updating values in the database manually, there is a fix discussed here: [https://github.com/sabre-io/Baikal/issues/1085](https://github.com/sabre-io/Baikal/issues/1085)

**Comment by alexbelgium** [comment]
Hi sorry looks like I completely overlooked this! I can still update the upstream build to the link you provide, should I? Or given that we are 4 versions later did the upstream app incorporate the solution?
