### ISSUE TITLE
🐛 [Nextcloud] NC addon removes Collabora CODE Server when starting

### ISSUE THREAD

**Issue by a0zzy** [alexbelgium/hassio-addons#1261]
### Description

I have been having issues with this forever and I've tried every solution I could come across and I think that it's out of my hands at this point, I've noticed countless other people have this issue too regardless of their installation method but I am wondering if anyone has insight about this.

When I freshly install the Nextcloud Addon and set it up with the MariaDB Addon, I install Nextcloud Office and the proceeding Collabora CODE app but when I go to settings to try and configure nextcloud office I am greeted by the error in the logs provided.

On top of this, when I start nextcloud, everytime I notice that in the logs it says "Remove CODE if installed as not compatible" and it procceeds to remove CODE. Why is this? is it not compatible and why?

I am running Nextcloud with MariaDB on the latest version of both addons and latest home assistant. I am using ports 443 and 80 in order for domain use. Linux 6.1.74-haos x86_64.

Reproduction steps:
1. Install Nextcloud addon and setup with MariaDB
2. Change ports to 443/tcp and 80/tcp
3. Install Nextcloud office and CODE server
Voila you have recreated my situation.

Thank you so much to alexbelgium for creating this addon. It is extremley helpful and suits my needs perfectly. This issue is most likley not associated with the addon but rather nextcloud and collabora.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
[richdocuments] Error: Failed to fetch the Collabora capabilities endpoint: cURL error 7: Failed to connect to homeassistant.local port 8099 after 3 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://homeassistant.local:8099/apps/richdocumentscode/proxy.php?req=/hosting/capabilities
	GET /index.php/settings/admin/richdocuments
	from 192.168.0.241 by ***** at Feb 23, 2024, 8:20:36 AM


[richdocuments] Error: Could not find urlsrc for application/vnd.openxmlformats-officedocument.wordprocessingml.document in WOPI discovery response
	GET /apps/richdocuments/settings/check
	from 192.168.0.241 by ***** at Feb 23, 2024, 8:16:25 AM
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, I think this was the cause : https://github.com/linuxserver/docker-nextcloud?tab=readme-ov-file#collaborative-editing
