### ISSUE TITLE
❓ [Nextcloud] Accessing OCC

### ISSUE THREAD

**Issue by jonnyrider** [alexbelgium/hassio-addons#1268]
Apologies if this is a simple question (with a simple answer!) but how do I access the OCC command through Nextcloud?

I've tried:

`docker exec addon_db21ed7f_nextcloud_ocr sudo -u abc php /config/www/nextcloud/occ files:scan --all`

but all I get back is:

`Could not open file: /config/www/nextcloud/occ`

Thanks in advance for your help!

Jonathan

**Comment by alexbelgium** [comment]
Hi, please try this path : /app/www/public/occ

**Comment by jonnyrider** [comment]
That's great, thank you very much. Knew it would be simple!

**Comment by jonnyrider** [comment]
Apologies, I have one more question. How do I open and edit the crontab? I'm trying to get the below added:

`php /app/www/public/occ preview:pre-generate`

but doing `sudo crontab -e` in Portainer brings up an editor that I can't seem to edit!

Thanks

**Comment by alexbelgium** [comment]
One day I'll expose the full config folder but I fear breaking things ;) currently the crontab is available with portainer in the /data/config/crontab folder I think

**Comment by jonnyrider** [comment]
I agree, I'm constantly scared of breaking it by changing the background!

Can't find it there, but by logging into portainer with the 'abc' user and doing `sudo crontab -e` I get asked for a password but I don't know what it is! Where would I find this?

Thanks

**Comment by jonnyrider** [comment]
Ignore me, was looking at the wrong thing!

I've found the cron.php file but it doesn't look like the one I need. It should apparently look like this:

`*/5 * * * * php /app/www/public/occ preview:pre-generate`

If I can explain what I've trying to do...

I just want to run the below every 5 minutes, and looking online updating the crontab seems the easiest way:

`sudo -u abc php /app/www/public/occ preview:pre-generate`

If only I could find it!
