### ISSUE TITLE
[Request] TP-Link Omada Controller

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#127]
Hi,

I`m wondering if it is possible to add the following:
https://github.com/mbentley/docker-omada-controller

Its the same as Ubiquiti but then for TP-Link.

**Extra tip: (no need for integration but for HACS)**
Also if you use it the integration with HA can be found here:
https://github.com/zachcheatham/ha-omada

**Comment by alexbelgium** [comment]
Hi, I'm off for the moment I'll look at it next week!

**Comment by alexbelgium** [comment]
Hi, an addon already seems to exist here for Omada : https://github.com/MattFryer/Hassio-Addons

**Comment by deku-m** [comment]
Aah didnt notice there is one already there only see that it isn't regular updated as the one i posted but will have a look.

**Comment by alexbelgium** [comment]
Another addon exists for this purpose

**Comment by deku-m** [comment]
Hi Alex,

I know this was closed but could you maybe include this in your repo as the other repo isnt really up to date.
