### ISSUE TITLE
🐛 [Emby NAS] <After Upgrading HA OS to 12.0 andd-on doesn't start>

### ISSUE THREAD

**Issue by rqmartins73** [alexbelgium/hassio-addons#1271]
### Description

Hi Alex,

Hope you are well.

I just updated my HA OS to version 12.0, and after the HA restart the add-on is not starting stating this:

[19:46:51] FATAL: Error, unable to mount //192.168.1.220/Camera to /mnt/Camera with username xxxxxxx, xxxxxxxxx. Please check your remote share path, username, password, domain, try putting 0 in UID and GID
.
.
.
SMB1 disabled -- no workgroup available
[19:46:51] FATAL: Error read : mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg), addon will stop in 1 min
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111

Nothing changed here beside the HA OS upgrade.

Thanks in advance.
Regards.

### Reproduction steps

```bash
Emby NAS Add-on is at Current version: 4.9.0.5
It was working, updated HA OS to 12.0, and now is not.
```

### Addon Logs

```bash
[19:46:51] FATAL: Error, unable to mount //192.168.1.220/Camera to /mnt/Camera with username xxxxxxxx, xxxxxxx. Please check your remote share path, username, password, domain, try putting 0 in UID and GID
.
.
.
SMB1 disabled -- no workgroup available
[19:46:51] FATAL: Error read : mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg), addon will stop in 1 min
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, are you using smbv1? If HA os dropped support for smbv1 then there is no solution...

**Comment by rqmartins73** [comment]
![HAOS12_0_errors](https://github.com/alexbelgium/hassio-addons/assets/83714215/0e7f066c-7181-4348-b1a6-46042294ef0a)
I'm getting also these error attached in the HA OS Console, just in case its related which seems like it...

**Comment by rqmartins73** [comment]
> Hi, are you using smbv1? If HA os dropped support for smbv1 then there is no solution...

No I checked that the snbv1 switch is disabled, I even enable it, try it same error, disable it again, try it, same error.

**Comment by alexbelgium** [comment]
Ah, actually the switch is not used anymore :) the script automatically detects smbv1 and tries to connect to it. I've just kept the switch for "historical reasons" (ie : I forgot to remove it). So if there is an smb1 switch to disable it would be in the system providing the smb share... By us that all in the log? I thought my script tried to troubleshoot smb errors by checking the available versions and such - thanks

**Comment by alexbelgium** [comment]
Could you please post your full log for the smb part? Thanks!

**Comment by rqmartins73** [comment]
Meanwhile I just confirmed and my Windows 10 Pro, which is providing those smb shares, is with the smbv1 disabled.

Sure here it goes:
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Emby NAS
 A free Software Media System that puts you in control of managing and streaming your media
-----------------------------------------------------------
 Add-on version: 4.9.0.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.0  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.3
 Home Assistant Supervisor: 2024.02.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
PGID='0'
PUID='0'
cifsdomain='xxxxxxx'
cifspassword='xxxxxxx'
cifsusername='xxxxxx'
networkdisks='//192.168.1.220/Musica, //192.168.1.220/Videos, //192.168.1.220/Emby_Backups, //192.168.1.220/Camera, //192.168.1.220/MRMSG9, //192.168.1.220/Fotos_Eu'
silent='true'
smbv1='false'
Timezone set from Etc/UTC to Europe/Lisbon
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
Mounting smb share(s)...
... using domain xxxxxxx
... using PUID 0 and PGID 0
... mounting //192.168.1.220/Musica
[20:23:17] INFO: ...... //192.168.1.220/Musica successfully mounted to /mnt/Musica with options rw,file_mode=0775,dir_mode=0775,username=xxxxxx,password=XXXXXXXXXX,nobrl,uid=0,gid=0,iocharset=utf8,domain=xxxxx
... mounting //192.168.1.220/Videos
[20:23:17] INFO: ...... //192.168.1.220/Videos successfully mounted to /mnt/Videos with options rw,file_mode=0775,dir_mode=0775,username=xxxxxx,password=XXXXXXXXXX,nobrl,uid=0,gid=0,iocharset=utf8,domain=xxxxx
... mounting //192.168.1.220/Emby_Backups
[20:23:18] INFO: ...... //192.168.1.220/Emby_Backups successfully mounted to /mnt/Emby_Backups with options rw,file_mode=0775,dir_mode=0775,username=xxxxxx,password=XXXXXXXXXX,nobrl,uid=0,gid=0,iocharset=utf8,domain=xxxxxx
... mounting //192.168.1.220/Camera
...... 192.168.1.220 is confirmed reachable
...... credentials are valid
...... SMB version detected : 3.1
[20:23:20] FATAL: Error, unable to mount //192.168.1.220/Camera to /mnt/Camera with username xxxx, xxxxx. Please check your remote share path, username, password, domain, try putting 0 in UID and GID
[20:23:20] FATAL: Here is some debugging info :

	Sharename       Type      Comment
	---------       ----      -------
	ADMIN$          Disk      Remote Admin
	C$              Disk      Default share
	Camera          Disk      
	Camera_Roll     Disk      
	D$              Disk      Default share
	E$              Disk      Default share
	Emby_Backups    Disk      
	EPSON Stylus Photo R1900 Series Printer   EPSON Stylus Photo R1900 Series
	F$              Disk      Default share
	Fotos           Disk      
	Fotos_Eu        Disk      
	G$              Disk      Default share
	H$              Disk      Default share
	IPC$            IPC       Remote IPC
	Musica          Disk      
	print$          Disk      Printer Drivers
	Studio Lab Array Disk      
	Videos          Disk      
SMB1 disabled -- no workgroup available
[20:23:20] FATAL: Error read : mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg), addon will stop in 1 min
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111

**Comment by alexbelgium** [comment]
Hi, please let me know how this version goes thanks

**Comment by rqmartins73** [comment]
Same error:
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Emby NAS
 A free Software Media System that puts you in control of managing and streaming your media
-----------------------------------------------------------
 Add-on version: 4.9.0.5-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.0  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.3
 Home Assistant Supervisor: 2024.02.0
.
.
.
... mounting //192.168.1.220/Camera
...... 192.168.1.220 is confirmed reachable
...... credentials are valid
...... SMB version detected : 3.1.1
[20:53:06] FATAL: Error, unable to mount //192.168.1.220/Camera to /mnt/Camera with username xxxxx, xxxxxxx. Please check your remote share path, username, password, domain, try putting 0 in UID and GID
[20:53:06] FATAL: Here is some debugging info :

	Sharename       Type      Comment
	---------       ----      -------
	ADMIN$          Disk      Remote Admin
	C$              Disk      Default share
	Camera          Disk      
	Camera_Roll     Disk      
	D$              Disk      Default share
	E$              Disk      Default share
	Emby_Backups    Disk      
	EPSON Stylus Photo R1900 Series Printer   EPSON Stylus Photo R1900 Series
	F$              Disk      Default share
	Fotos           Disk      
	Fotos_Eu        Disk      
	G$              Disk      Default share
	H$              Disk      Default share
	IPC$            IPC       Remote IPC
	Magui           Disk      
	MRMSG9          Disk      
	Musica          Disk      
	print$          Disk      Printer Drivers
	Studio Lab Array Disk      
	Videos          Disk      
SMB1 disabled -- no workgroup available
[20:53:06] FATAL: Error read : mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg), addon will stop in 1 min
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111

**Comment by rqmartins73** [comment]
And those HA OS Console messages I posted before also keep appearing while the add-on is starting.

**Comment by alexbelgium** [comment]
So 3.1 doesn't work, 3.1.1 either, latest version tries 3.11. If it doesn't work i'll try 3.0

**Comment by rqmartins73** [comment]
Try next :)
SMB 3.1 detected, converting to 3.11
...... SMB version detected : 3.11
[21:24:45] FATAL: Error, unable to mount //192.168.1.220/Camera to /mnt/Camera with username

**Comment by rqmartins73** [comment]
Next please :)

... mounting //192.168.1.220/Camera ...... 192.168.1.220 is confirmed reachable ...... credentials are valid SMB 3.1 detected, converting to 3 ...... SMB version detected : 3 [21:43:07] FATAL: Error, unable to mount

**Comment by alexbelgium** [comment]
And you had the same issue in the log about unknown vers ?

**Comment by alexbelgium** [comment]
Btw it's strange that all other shares seem to mount except for the Camera one. Is there any difference on how it's set on the windows system? For example with specific accesses or a different workgroup? Because there is no reason that some smb mounts would work and not this single one...

**Comment by rqmartins73** [comment]
Hi Alex,

Very strange...

The new version didn't started also.
I went investigate and:

I had this in the config:
//192.168.1.220/Musica, //192.168.1.220/Emby_Backup, //192.168.1.220/Camera, //192.168.1.220/MRMSG9, //192.168.1.220/Fotos_Eu

Then I changed to:
//192.168.1.220/Musica, //192.168.1.220/Emby_Backup

And like that the add-on started.
So I went and compare the shares between Musica and Camera, made some changes to the Cameras and tested it with:
//192.168.1.220/Musica, //192.168.1.220/Emby_Backup, //192.168.1.220/Camera
Didn't started.

Because I don't have more time now and wanted to have the add-on up, I decided to give up for now, and changed again to:
//192.168.1.220/Musica, //192.168.1.220/Emby_Backup
But now it's giving the same error on //192.168.1.220/Emby_Backup

Don't know what to tell you...

**Comment by rqmartins73** [comment]
Still on this
Sorry I removed the 's' in the end of Backups and thats why it was not starting with that last change.
Meanwhile I restore 4.9.0.5 with just //192.168.1.220/Musica, //192.168.1.220/Emby_Backups on the config and the add-on started well.
What changed for failling with some shares? The shares I have are all from the same Windows 10 Pro and all shared with the same username...

**Comment by alexbelgium** [comment]
Why do you separate all the smb shares instead of mounting a single one and referring the subfolders in emby
Indeed in don't see why some shares would work and others not, especially with this error code...

**Comment by rqmartins73** [comment]
> Why do you separate all the smb shares instead of mounting a single one and referring the subfolders in emby
> Indeed in don't see why some shares would work and others not, especially with this error code...

Because they all are in different physical disks. The Camera one i.e is from a folder replicated with OneDrive on an HDD mirrored, the Emby_Backups are in an USB SSD disk... All are shares from the Windows PC, I just Shared the different folders I wanted to see in Emby, and it was working perfectly until the HA OS upgrade...
For now I removed from Emby the ones failing, and its working. One thing I noticed is that the Emby error message is exactly the same when the folder is Shared and when it is not Shared.

Let me know if you need anything more.

**Comment by rqmartins73** [comment]
> I see thanks... Sorry I have no idea to help you for the moment. Next weekend I'll perhaps come with a script to test in a faster way other solutions

From my part, no worries and no stress Alex, pretty busy here also.

Let me know in anything I can help.
Have a nice and no stressed week 😉

**Comment by rqmartins73** [comment]
Good-evening Alex,

Today after dinner, I came to play a bit with this, and I found that it is only giving that error when the shared folder is a OneDrive Synced folder on the Windows.
- I shared a folder on the same disk but outside OneDrive folder and it worked. 👍
- I shared another, never before shared, folder inside OneDrive folder and same error.🚨

Then I went to one of my Ubuntu's and tried to mount the same Windows OneDrive Synced Camera folder (that is giving the error in Emby), and success it is mounting, I can now see the Camera folder in my Ubuntu. Which leads me to think that this is definitely not a Windows share issue, I can mount it on Ubuntu through cifs. 👍

Meanwhile on that Ubuntu I shared, the now mounted Camera folder, through smbd/cifs and guess what? :) It mounted on Emby. Already test it and I can see again my photos in Emby. 💪😎

What could have changed on HA OS 12.0 to make Emby to be "mad" at those shares?... 🤔

Have a nice weekend.
Regards.

**Comment by alexbelgium** [comment]
Hi, great job finding the cause, now things don't look that positive : https://superuser.com/questions/1783214/onedrive-smb-access

As for HAos 12 perhaps the issue is that it updated the kernel to https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.16 which states : `smb: client: fix hardlinking of reparse points` and it seems a onedrive folder is a reparse point according to a quick Google search. The solution `Fix this by setting OPEN_REPARSE_POINT in create options for
    SMB2_CREATE request when the source inode is a repase point.` is not really clear...

**Comment by alexbelgium** [comment]
Quick idea : Have you tried sharing a  parent folder and see if onedrive files are still accessible from still the shared smb?
