### ISSUE TITLE
🐛 [Zoneminder] Symbolic Link from container to HA Media folder

### ISSUE THREAD

**Issue by DuchyWare** [alexbelgium/hassio-addons#1274]
### Description

There is configuration options for images_location = /config/addons_config/zoneminder/images which does not seem to work.

I have tried creating zoneminder.sh in the config/addons_autoscripts to create a symbolic link to outside the container which doesn't work:

ln -s /var/cache/zoneminder/events /media/zoneminder/events

Is there any way to add a symbolic link from the zoneminder container to say the shared media directory?

### Reproduction steps

```bash
Trying to create a symbolic link to media directory
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Zoneminder
 A full-featured, open source, state-of-the-art video surveillance software system
-----------------------------------------------------------
 Add-on version: 1.36.33-3
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.2.5
 Home Assistant Supervisor: 2024.02.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-folders.sh: executing
... making sure /config/addons_config/zoneminder exists
... checking permissions
... making symlinks
/etc/cont-init.d/01-custom_script.sh: executing
[15:28:06] INFO: Execute /config/addons_autoscripts/zoneminder.sh if existing
[15:28:06] INFO: ... script found, executing
dos2unix: converting file /config/addons_autoscripts/zoneminder.sh to Unix format...
... making sure /config/addons_config/zoneminder exists
... checking permissions
... making symlinks
... making symlinks1
ln: failed to create symbolic link '/config/addons_config/zoneminder/events': File exists
/etc/cont-init.d/01-custom_script.sh: exiting 1
/etc/cont-init.d/99-run.sh: executing
[15:28:06] INFO: Defining database
[15:28:06] INFO: Using internal database
[15:28:06] INFO: Please wait while the app is loading !

 * Starting MySQL database server service   ...done.
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'zmuser'@'localhost'
 * ZoneMinder dB already exists, skipping table creation.
 * Starting Apache http web server service   ...done.
 * Starting ZoneMinder video surveillance recorder
Database already at version 1.36.12, update skipped.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, two ways :
- either in the config.yaml add `DIR_IMAGES` as env variable according to this https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables
- modify your script to make the symlink between the default folder /var/cache/zoneminder/images2 as in this line : https://github.com/alexbelgium/hassio-addons/blob/4d805eba2f3bc7ac7d4a5c50be39b9f9c3c005dc/zoneminder/rootfs/etc/cont-init.d/00-folders.sh#L32

What it strange is that in theory if you set Images_location it should indeed set it as a symlink according to this code : https://github.com/alexbelgium/hassio-addons/blob/4d805eba2f3bc7ac7d4a5c50be39b9f9c3c005dc/zoneminder/rootfs/etc/cont-init.d/00-folders.sh#L9-L15
