### ISSUE TITLE
❓ [Immich] faster updates possible? 

### ISSUE THREAD

**Issue by blendrik** [alexbelgium/hassio-addons#1277]
Hello alexbelgium! 

I was wondering, if there might be a chance, that the Immich add-on could be updated automatically to the latest version availaible on imagegenius?  Or is it a manual process, that you have to trigger? 

My question comes from the fact, that if one updates the app automatically through the e.g. Play Store, some features may not work if the server and the app differ in versions.

Thanks a lot for your effort!
Cheers

**Comment by alexbelgium** [comment]
Hi, it is auto updated every Saturday, but the dev makes regular breaking changes so even this frequency is already a bit too frequent for me... That's why for example there was a pause for some time as I don't have enough time to follow all the upstream breaking changes

**Comment by blendrik** [comment]
Ok, thanks for the explanation. Auto update every Saturday is perfect.

IMHO: As for the breaking changes, the developers of Immich have a banner on their home page saying:
"⚠️ The project is under very active development. Expect bugs and changes. Do not use it as the only way to store your photos and videos!"

So everyone using your version of Immich should be fully aware of this fact and must not blindly auto update. Everyone should read the Immich changelog beforehand and decide, wether to update or not. Maybe you can put their banner into your Immich add-on, too.

Thanks again.
Your knowledge about making HA-add-ons is worth gold to many people!

**Comment by alexbelgium** [comment]
Good idea I'll add it to the readme! And actually several people have informed upfront of those breaking changes which was super helpful in anticipating and adapting :) I must say the immich users community is pretty adaptable with a fix-it mindset, probably stemming from that same "active dev" mindset ;)
