### ISSUE TITLE
[Feature Request] Wiki.js

### ISSUE THREAD

**Issue by dimmuboy** [alexbelgium/hassio-addons#128]
It will be great to have option for create [Wiki.js](https://js.wiki) addon. It have docker image and I'm already using it on my VPS.

**Comment by alexbelgium** [comment]
Hi, there already seems to be one here : https://github.com/FaserF/hassio-addons

**Comment by dimmuboy** [comment]
> Hi, there already seems to be one here : https://github.com/FaserF/hassio-addons

I don't know about it, thanks a lot :)

**Comment by alexbelgium** [comment]
Glad if it works for you! Merry Christmas
