### ISSUE TITLE
Would you consider adding FlareSolverr?

### ISSUE THREAD

**Issue by almico** [alexbelgium/hassio-addons#129]
It would be useful with some automations 💪

**Comment by alexbelgium** [comment]
Hi, I'll look at it!

**Comment by alexbelgium** [comment]
First build pushed, could you please test? Don't hesitate if you use it to improve the Readme file to help other users! I'm not a user myself so there are some things that might be needed to describe that I do not know. Thanks

**Comment by almico** [comment]
Happy New Year :-) I'll be glad to do it. At the moment, I'm facing a serious issue with your Jackett NAS. It lost all its configuration settings. I'm going to open an issue.

**Comment by almico** [comment]
Sorry! I thought I posted some feedback.
Well... It works as expected 😃 
Thank you!

**Comment by alexbelgium** [comment]
Thanks for the feedback! Enjoy
