### ISSUE TITLE
Can't remove container's filters

### ISSUE THREAD

**Issue by Pulpyyyy** [alexbelgium/hassio-addons#13]
Hello,

It seems filter are broken and reappair after reload
![portainer](https://user-images.githubusercontent.com/32004297/118642218-624f0a00-b7db-11eb-942f-9a831f420dc2.gif)
May the config be mounted as readonly ? I noticed password isn't changed either, whatever i'm setting in the HA panel

Regards

**Comment by alexbelgium** [comment]
Hi, for the password, it's normal you need to change it from the addon options. For the filters... I need to check :)

**Comment by alexbelgium** [comment]
mmh the app was updated to 2.5.0 this night and that broke some elements. I haven't time for the moment but I'll check soon

**Comment by alexbelgium** [comment]
have you tried logging from webUI? http://LOCALIP/9000 ?

**Comment by Pulpyyyy** [comment]
Both errors were present before the 2.5.0 update, I just didn't have time to report it ...
Of course, I changed the password in the HA UI and saved, content of the file `portainer_password `file have been updated accordingly but no effect on the container even after restarting

**Comment by alexbelgium** [comment]
argh... I'll look at that. Btw, it seems that portainer made a mistake with their 2.5.0 version it shouldn't have been released... so I reverted the addon to 2.1.1

I'll look for a cause this evening

**Comment by alexbelgium** [comment]
mmh I could have a cause I'll test it and push it afterwards if it works

**Comment by alexbelgium** [comment]
ok, it seems to work! I've tested removing filters, starting with/without ssl, and changing password.

I've pushed a dev5, if you could test it, it would be great!

Thanks very much for all that, and sorry for the inconveniences and bugs. I haven't got much time to put on those so I greatly appreciate people like you that provide feedback and allow to make things better for everyone

**Comment by alexbelgium** [comment]
Btw, you'll need to change your password for the new version to work (to reset the database)

**Comment by Pulpyyyy** [comment]
Both are solved with dev5 ! Issue can be closed.
My contribution is not so meaningful as your are doing 99% of the job ! But i'll be glad to report anything i coud find.
So thanks to your for porting newer version to HA

Regards

**Comment by alexbelgium** [comment]
Thanks very much!
