### ISSUE TITLE
✨ [REQUEST] Linkwarden

### ISSUE THREAD

**Issue by blackpearlla** [alexbelgium/hassio-addons#1302]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Linkwarden [https://github.com/linkwarden/linkwarden](url) 

Linkwarden is a Bookmark Management System

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

Request for the Linkwarden Addon for Homeassistant

**Comment by amarok77** [comment]
please... armhf

**Comment by alexbelgium** [comment]
Hi, sorry armhf is not supported by the app dev himself : https://github.com/linkwarden/linkwarden/pkgs/container/linkwarden/189027761?tag=v2.5.1

**Comment by alexbelgium** [comment]
I'm trying to build an addon but the app doesn't support sqlite so i'm trying to find a solution

**Comment by b52src** [comment]
could be me but the browser plugin dose not appear to be work in the current version unless im just missing something. 
i have the NEXTAUTH_URL filled out and i can access it from the browser but the extension is throwing back a 404 error trying to find the instance.

**Comment by alexbelgium** [comment]
Hi, I had the same but it was also said for other systems that extension seems broken https://github.com/linkwarden/linkwarden/issues/462

**Comment by b52src** [comment]
> Hi, I had the same but it was also said for other systems that extension seems broken [linkwarden/linkwarden#462](https://github.com/linkwarden/linkwarden/issues/462)

i went ahead and posted details of the issue with the browser extension on that issue page however, not sure about the others interested in this extension but I'm realy just looking for a good bookmark manager that i can deploy as a supported plugin on HA vs doing so unsupported via the portioner addon.  A few days before this one was pushed out i put a request in for LinkAce here(https://github.com/alexbelgium/hassio-addons/issues/1262) which i was previously running via the portioner addon with a working browser extensions(my only complaint on it was that i had to go in and do some work to be able to use it as an iframe in my organizer dashboard and have to redo the work after each update: https://github.com/Kovah/LinkAce/discussions/420). just wanted to note it as may be a good replacement if they cant fix the extension issue.
