### ISSUE TITLE
Jackett creating 2 folders

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#131]
For some reason when installing jackett it creates 2 folders in the HA config dir:
`Jackett`
and
`jackett`
I looked in the installtion files but I cannot find anything weird.
I used the default config:
```yaml
PUID: 0
PGID: 0
```

**Comment by alexbelgium** [comment]
Hi, thanks for reporting. Strange there is no instance of "Jackett" with capital j in my code, it is perhaps in the upstream images. I'll investigate

**Comment by alexbelgium** [comment]
Indeed I had to change an ENV variable from upstream. I've adapted the Dockerfile as such and incremented the version. I took the opportunity to implement your new config location in /config/addons_config/Jackett that way this one is done :) thanks for reporting!

**Comment by alexbelgium** [comment]
I changed my mind, and did not change config location, only remove the unused folder. This will be cleaner to migrate everything at once with your code

**Comment by bruvv** [comment]
perfect thanks for the quick work :) happy holidays! Will try and fix everything coming week.

**Comment by alexbelgium** [comment]
Thanks, happy holidays too ! I think it's a great idea that you have. Let me know if you need anything!
