### ISSUE TITLE
🐛 [Tandoor] config.yaml ENV var overrides not working

### ISSUE THREAD

**Issue by nkm8** [alexbelgium/hassio-addons#1315]
### Description

Following the instructions [from the wiki](https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables#auto-scripting-feature) - I haven't been able to get `config.yaml` overrides working with Tandoor.

Based on the addon logs - and the template file that gets created - it should be located here: `/config/addons_config/tandoor-recipes/config.yaml`

I'm not sure if it is related, but the rest of the Tandoor config files are located in `/config/addons_config/tandoor_recipes/` - note the difference in naming - `tandoor-recipes` vs. `tandoor_recipes`

Please note that if the ENV vars were working/available, this would be an alternate means of using `GUNICORN_MEDIA` as mentioned in [this issue](https://github.com/alexbelgium/hassio-addons/issues/885)

### Reproduction steps

```bash
1. Populate `/config/addons_config/tandoor-recipes/config.yaml` with ENV vars
2. Restart Tandoor addon
3. Observe ENV vars have no affect on addon
```

### Addon Logs

```bash
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/addons_config/tandoor-recipes/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/tandoor-recipes/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, currently `"GUNICORN_MEDIA": "1"` is defined from the global environment variables. It should indeed be overwritten by the `config.yaml` env variables - I do see the discrepancy in the folders name but it's likely because when I initially set up the addon I was using a manual folder and am now using an automatic naming for the config.yaml script... I'll solve that one day

Have you tried setting an other variable (such as `TANDOOR_PORT`) to make the addon fail on purpose and check if the variable is passed ?

**Comment by nkm8** [comment]
I tested with `TANDOOR_PORT=9999` and confirmed that the addon was unaffected - the web UI was still accessible, as usual.

**Comment by alexbelgium** [comment]
Hi, you need to use a yaml format. I tried with `TANDOOR_PORT: 9999` and it worked and the new port was shown in the log

**Comment by nkm8** [comment]
Well - this is embarrassing - great catch! After fixing the YAML syntax, all is well. I can also confirm that I was successfully able to set `GUNICORN_MEDIA: 0`. Combined with configuring nginx correctly, Tandoor is no longer complaining about 'Media Serving' in the System settings. Thanks for all your help!

**Comment by alexbelgium** [comment]
Hi great! Is it something that can be implemented by default in the addon or must be customized for each system? Thanks!

**Comment by nkm8** [comment]
A lot of it may be irrelevant - I think the important part is the `location /media/` block:
```
server {
  server_name recipes.fake.com;

  client_max_body_size 128M;

  listen 443 ssl http2;
  allow  192.168.1.0/24;
  deny   all;
  add_header Strict-Transport-Security "max-age=31536000" always;

  proxy_buffering off;

  location / {
    proxy_pass http://192.168.1.99:8080/;
    proxy_set_header Host $host;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }

  location /media/ {
    alias /mediafiles/;
    client_max_body_size 16M;
  }
}
```
