### ISSUE TITLE
❓ [Calibre & Mealie] Port Conflict (9090)

### ISSUE THREAD

**Issue by LoganJFisher** [alexbelgium/hassio-addons#1316]
**Which addon?**

Calibre & Mealie

**Addon or app?**

Addons

**Describe the solution you'd like**

I would like to be able to run both of these addons without experiencing a port conflict

**Describe alternatives you've considered**

I've considered (and tried) running Calibre using Docker on my NAS instead, but am having some trouble with that. I'd prefer to use a Home Assistant addon.

**Additional context**

I am already running Mealie and have recipes saved to it. I'd very much prefer not to have to uninstall it as part of addressing this issue.

**Comment by alexbelgium** [comment]
Hi, none of the those two addons use host_network so their ports should be customizable from the addon option page. Can you confirm that you have a conflict message even after having changed the published port ?

**Comment by LoganJFisher** [comment]
To be clear, you're suggesting changing the "Calibre wireless connection" from 9090 to a different value? Or do you mean I should change one of the other ports?

**Comment by alexbelgium** [comment]
I mean that in the configuration panel, you change the port (such as 9090 if this is the one making the conflict) to something else, save and reboot

<img width="740" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/44178713/df11d7d5-507f-4276-86ef-b27280cb87f0">
