### ISSUE TITLE
Requestrr

### ISSUE THREAD

**Issue by dumbledorethor** [alexbelgium/hassio-addons#1321]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Requestrr Home Assistant add-on

### Is your feature request related to a problem? Please describe

can the repo change to https://github.com/thomst08/requestrr to get the latest version? also right now my settings get erased with restarting the image

### Describe the solution you'd like

change the repo to https://github.com/thomst08/requestrr

**Comment by alexbelgium** [comment]
Hi, thanks for sharing! I fear that the new repo has a different structure than the linuxserver one so it will require a bit of refactoring before being able to push it in production, I'll look at that

**Comment by dumbledorethor** [comment]
Thank you! i appreciate your time looking in to this! also thank you for all the add ons! I feel like its the best add on repo :).  Also if i can help in anyway i will. i tried making the addon yesterday without success but i feel like i was close.  and the main reason i wanted to move to the new repo was because HA addon would erase all my Requestrr data once the addon was restarted.

**Comment by alexbelgium** [comment]
ahah thanks very much ! currently it is not starting but it's on a very good path. Which data is erased? from what i see there is just a /config folder with files and that's all ?

**Comment by alexbelgium** [comment]
should be good could you please test? the path for config has changed I've put the info in the changelog it must be accessed in /addon_configs/**-requestrr using my Filebrowser addon

**Comment by dumbledorethor** [comment]
thank you so much! it is working perfectly!! i will close this issue.  thanks again!!!
