### ISSUE TITLE
🐛 [SCRUTINY_FA] Addon doesn't respect scheduling option

### ISSUE THREAD

**Issue by flopon** [alexbelgium/hassio-addons#1324]
### Description

Addon doesn't seem to respect the 'Hourly' scheduling option :

![Scrutiny](https://github.com/alexbelgium/hassio-addons/assets/15372515/acce3b9b-1d4e-454f-b881-e21608a4124e)

### Reproduction steps

```bash
1. Select 'Hourly' updates
2. Data collection is still only done daily (or at least only sent to distant collector on daily basis)
```

### Addon Logs

```bash
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Scrutiny (Full Access)
 Scrutiny WebUI for smartd S.M.A.R.T monitoring (Full Access)
-----------------------------------------------------------
 Add-on version: v0.8.0-3
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.3.3
 Home Assistant Supervisor: 2024.03.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 00-global_var.sh: executing... 
COLLECTOR_API_ENDPOINT='http://x.x.x.x:8080'
COLLECTOR_HOST_ID='HAos'
Mode='Collector'
SMARTCTL_COMMAND_DEVICE_TYPE='auto'
TZ='Europe/Paris'
Updates='Hourly'
expose_collector='false'
[cont-init.d] 00-global_var.sh: exited 0.
[cont-init.d] 01-config_yaml.sh: executing... 
[cont-init.d] 01-config_yaml.sh: exited 0.
[cont-init.d] 01-configuration.sh: executing... 
Updating folders structure
mkdir: cannot create directory '/data/config': File exists
[cont-init.d] 01-configuration.sh: exited 1.
[cont-init.d] 01-custom_script.sh: executing... 
[cont-init.d] 01-custom_script.sh: exited 0.
[cont-init.d] 01-timezone: executing... 
[cont-init.d] 01-timezone: exited 0.
[cont-init.d] 32-nginx_ingress.sh: executing... 
[cont-init.d] 32-nginx_ingress.sh: exited 0.
[cont-init.d] 50-cron-config: executing... 
[cont-init.d] 50-cron-config: exited 0.
[cont-init.d] 90-run.sh: executing... 
[19:21:05] WARNING: Collector only mode. WebUI and Influxdb will be disabled
[19:21:05] INFO: Using 'COLLECTOR_API_ENDPOINT' http://x.x.x.x:8080
[cont-init.d] 90-run.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
starting cron
starting scrutiny collector (run-once mode. subsequent calls will be triggered via cron service)
[services.d] done.
2024/03/28 19:21:05 No configuration file found at /opt/scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                                dev-0.8.0
time="2024-03-28T19:21:05+01:00" level=info msg="Verifying required tools" type=metrics

time="2024-03-28T19:21:05+01:00" level=info msg="Executing command: smartctl --scan --json" type=metrics
time="2024-03-28T19:21:05+01:00" level=info msg="Executing command: smartctl --info --json /dev/sda" type=metrics
time="2024-03-28T19:21:05+01:00" level=info msg="Generating WWN" type=metrics
time="2024-03-28T19:21:05+01:00" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
time="2024-03-28T19:21:05+01:00" level=info msg="Collecting smartctl results for sda\n" type=metrics
time="2024-03-28T19:21:05+01:00" level=info msg="Executing command: smartctl --xall --json --device sat /dev/sda" type=metrics
time="2024-03-28T19:21:05+01:00" level=info msg="Publishing smartctl results for 0x5001b448b89cdc90\n" type=metrics
time="2024-03-28T19:21:05+01:00" level=info msg="Main: Completed" type=metrics
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi thanks I'll look at it perhaps the upstream code for durations has changed

**Comment by alexbelgium** [comment]
Thanks! indeed it seems something changed in the code along the way I'll check how to restore it

**Comment by alexbelgium** [comment]
Thanks I see actually the error is `mkdir: cannot create directory '/data/config': File exists` which prevents the collector to be configured. Very strange error though...

Do you have the web terminal app enabled? If yes you could try to run `docker exec addon_db21ed7f_scrutiny_fa rm -r /data/config` then `docker exec addon_db21ed7f_scrutiny_fa mkdir -p /data/config` and restart to see if the error disappeared !

**Comment by flopon** [comment]
Hi.

Thank you trying to investigate on this issue.
Removed the `/data/config` directory using console. Error message vanished, but still no hourly updates
Also tried to uninstall the addon and do a docker cleaning, no more error message too, but still no hourly updates.
For your information, there is nothing in the `/data/config` directory, is the config supposed to be stored here ?

In any case, configuration.sh now seems to execute properly, showing The INFO message regarding Hourly updates :
`[cont-init.d] 01-configuration.sh: executing...`
`Updating folders structure`
`[11:14:18] INFO: Hourly updates`
`[cont-init.d] 01-configuration.sh: exited 0.`

But :
![image](https://github.com/alexbelgium/hassio-addons/assets/15372515/3ee7cea9-9fcb-4221-b893-c3abbc1ca3c1)
![image](https://github.com/alexbelgium/hassio-addons/assets/15372515/e309a2c2-c008-4213-be39-d5494244c1da)

Maybe there is a conflict between your 50-cron-config, and AnalogJ one ?

**Comment by alexbelgium** [comment]
Hi, actually my code uses the AnalogJ one - I just inject the appropriate env variable according to the user selected choice... From your cat command I see that the injection actually works and it is passed to cron... Or is my cron code wrong ? "0 * * * *" should mean that it runs at the 0 minute of every hour... So not sure where the issue could lie...

In /data/config I see a database but that's probably for local systems opposed to yours

https://github.com/alexbelgium/hassio-addons/blob/58d9d75c6f550ebce65005e2608a370151d8f333/scrutiny_fa/rootfs/etc/cont-init.d/01-configuration.sh#L49-L65

**Comment by flopon** [comment]
No, your code is not wrong !

Following my last atempt to cleanup all the thing, and reinstall your addon, it finally start to work as intented just after I sent my previous message.

And I suspect the issue was on AnalogJ side, he has just released an new version, with a fix regarding CRON, not working as expected in the previous version. (see https://github.com/AnalogJ/scrutiny/issues/602)

Thank you in any case !

**Comment by hiagocosta** [comment]
is it possible to set more frequently updates, alike avery 10 minutes or set this manually? 
will be a great update for this addon, since i'm planning to monitor temperature of my disks

**Comment by tismofied** [comment]
> No, your code is not wrong !
> 
> 
> 
> Following my last atempt to cleanup all the thing, and reinstall your addon, it finally start to work as intented just after I sent my previous message.
> 
> 
> 
> And I suspect the issue was on AnalogJ side, he has just released an new version, with a fix regarding CRON, not working as expected in the previous version. (see https://github.com/AnalogJ/scrutiny/issues/602)
> 
> 
> 
> Thank you in any case !

If I am facing the hourly update not triggering, you think I should reinstall the addon ?

**Comment by alexbelgium** [comment]
> is it possible to set more frequently updates, alike avery 10 minutes or set this manually? will be a great update for this addon, since i'm planning to monitor temperature of my disks

Honestly not sure you'll really increase the quality of measurement with nearer measurements due to the inertia of disks? Perhaps this would more show the variability of the measurement more than more precise info about the disks

**Comment by hiagocosta** [comment]
I got the temperature of the disks by this addon, so when the temp increase, it starts a fan to cooling down it, if the disk not decrease the temp, the fan keeps on until the next temp update (then it will be in 1 hour using the less update available)

**Comment by alexbelgium** [comment]
I've added a Quarterly option (every 15 min)

**Comment by hiagocosta** [comment]
Thank you Alex!! I appreciate that!

**Comment by alexbelgium** [comment]
BTW you can also use this guide https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-customisation to execute your own cron with your own timings!

**Comment by hiagocosta** [comment]
sorry,  I tried to add another option like "update once at a minute" but I
couldn't make it work, is there more details on how to change this
customisations?

Em sáb., 2 de nov. de 2024 às 15:13, Alexandre ***@***.***>
escreveu:

**Comment by alexbelgium** [comment]
Ah - my fault now I realize that scutiny doesn't use an external config which enables the whole script injection system... Well ok I'll think of a way to make a customizable cron

**Comment by alexbelgium** [comment]
I've pushed a new feature. if you select "Custom" as "Updates" variable, you can define specific updates in natural language in the "Updates_custom_time" field. Example : select "Custom" as "Updates", then type a custom intervals like "5m", "2h", "1w", or "2mo" to have an update every 5 minutes, or every 2 hours, or evey week, or every 2 months

**Comment by hiagocosta** [comment]
Awesome, thanks for the update! I love all your addons!!!
My choice here is to make my homelab all integrated into the HAOS, and your
work make it possible by all this addons available to use, thank you again
man!!

Em qua., 13 de nov. de 2024 às 05:17, Alexandre ***@***.***>
escreveu:
