### ISSUE TITLE
🐛 [inadyn] Custom provider doesn't seem to be working

### ISSUE THREAD

**Issue by m435tr0d** [alexbelgium/hassio-addons#1334]
### Description

My config is as follows, please see the log output I am receiving. It seems there may be something wrong when using a custom provider but I am not sure:
```
providers:
  - custom_provider: true
    provider: easydns
    username: [redacted]
    password: [redacted]
    hostname: [redacted]
    ddns_server: api.cp.easydns.com
    ddns_path: /dyn/generic.php?hostname=%h&myip=%i
allow_ipv6: true
secure_ssl: true
iface: eth0
iterations: 0
period: 300
forced_update: 300
```
I also note the log output has a {MESSAGE} string in place of an ampersand that is in the path. The ipv6 is valid but the logs say it is not.

### Reproduction steps

```bash
1. Enter the above config
2. Click Start
3. Look at the logs
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Inadyn
 Inadyn is a small and simple Dynamic DNS, DDNS, client with HTTPS support. A large number of dynamic dns providers are supported (https://github.com/troglobit/inadyn#supported-providers). For those that are not, you can use a custom provider as per this project's documentation (https://github.com/nalipaz/hassio-addons/blob/master/README.md)
-----------------------------------------------------------
 Add-on version: 2.12.0-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.4.0
 Home Assistant Supervisor: 2024.03.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
allow_ipv6='true'
forced_update='300'
iface='eth0'
iterations='0'
period='300'
[23:50:18] WARNING: [
  {
    "custom_provider": true,
    "provider": "easydns",
    "username": "[redacted]",
    "password": "[redacted]",
    "hostname": "[redacted]",
    "ddns_server": "api.cp.easydns.com",
    "ddns_path": "/dyn/generic.php?hostname=%h{MESSAGE}myip=%i"
  }
] is an array, skipping
secure_ssl='true'
/etc/cont-init.d/01-config_yaml.sh: executing
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/*-inadyn/inadyn.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
curl: (23) Failure writing output to destination
Error : /etc/cont-init.d/01-custom_script.sh exiting 23
/etc/cont-init.d/99-run.sh: executing
inadyn[201]: In-a-dyn version 2.12.0 -- Dynamic DNS update client.
inadyn[201]: IPv6 address [redacted] is not a valid Internet address.
inadyn[201]: Update forced for alias [redacted], new IP# [redacted]
inadyn[201]: Fatal error in DDNS server response: DDNS server response not OK
inadyn[201]: Error response from DDNS server, exiting!
inadyn[201]: Error code 48: DDNS server response not OK
Error : /etc/cont-init.d/99-run.sh exiting 48
 
Starting the upstream container
```

### Architecture

armv7

### OS

HAos

**Comment by m435tr0d** [comment]
I was able to get it to work by removing the `&myip=%i`. The IP sent to the registrar DYN record was only a IPv4 address, yet the IPv6 address was valid. This only worked because my provider allows me to exclude the second querystring parameter I imagine (they use the IP that called the service).  I still see the error about the invalid IP address in the logs however. That said I think there may be an issue with ampersands

**Comment by alexbelgium** [comment]
Hi, glad you found a way to make it work! Your solution should also help people with similar issues. Enjoy the addon!

**Comment by m435tr0d** [comment]
IMO the issue with the ampersand character causing some weird string `{MESSAGE}` to be populated in the url will rear it's head again. I suggest figuring out why that is happening if you have the bandwidth.

**Comment by m435tr0d** [comment]
One more potential issue is that the IPv6 address is not getting sent to the registrar correctly with this setup which may be because I had to remove the IP address token due to the issue with the ampersand. IPv6 is poised to be the defacto very soon with [many organizations mandating it's use in the very near future](https://sdi.ai/blog/the-federal-ipv6-mandate-what-you-need-to-know/).

**Comment by yogitea** [comment]
@alexbelgium I also see this weird {MESSAGE} added in the URL, where the & character would be... Any idea why that is happening?

**Comment by m435tr0d** [comment]
Circling back to this. I too did find my provider has a dedicated plugin after looking into the manpage for inadyn. Looks like the following worked to get both my IPv4 and IPv6 into my provider and avoid the ampersand character error I was seeing with a custom provider. Hopefully that might help someone else, but custom providers still may be borked in some way which I cannot figure out the issue.

```
providers:
  - provider: easydns.com
    username: [redacted]
    password: [redacted]
    hostname: [redacted]
allow_ipv6: true
secure_ssl: true
iface: eth0
iterations: 0
period: 300
forced_update: 300
```
