### ISSUE TITLE
🐛 [Jellyseer] Port change doesnt work

### ISSUE THREAD

**Issue by HerrBeef** [alexbelgium/hassio-addons#1340]
### Description

It seems like the port change doesnt work with the jellyseer addon. I changed the port from 5055 to 5056 and its still reachable with 5055 and not with 5056. So it's conflicting with the Traccar Addon.

### Reproduction steps

```bash
1. Go to to the Configuration of Jellyseer
2. Enter a different port than 5055
3. Restart addon
4. See that it's still reachable at 5055 instead of new port.
```

### Addon Logs

```bash
not applicable
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, alas this is by design as jellyfin uses the host network for its features which prevents using the port changing system. You should look to change the tracaar port instead

**Comment by alexbelgium** [comment]
Btw the traccar addon uses 8082 as port by default so it should be easy to change
https://github.com/hassio-addons/addon-traccar/blob/main/traccar/config.yaml

**Comment by HerrBeef** [comment]
Hi, okay when it's not possible then this issue can be closed. I have changed the port from traccar. Thanks for the quick answers.
