### ISSUE TITLE
✨ [REQUEST] Baikal to use addon_configs repo

### ISSUE THREAD

**Issue by JeffersonBledsoe** [alexbelgium/hassio-addons#1354]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Baikal

### Is your feature request related to a problem? Please describe

Baikal currently uses the `/config/addons_config` directory. Some of your other addons have already been udated to use the `/addons_config` directory, but this feature is missing from Baikal.
Additionally, the addon doesn't start without creating a `config.yaml` file with a variable in it.

### Describe the solution you'd like

Move to using the Home Assistant addons config

**Comment by alexbelgium** [comment]
Hi, thanks! What is the content of /config/addons_config/baikal ?

**Comment by JeffersonBledsoe** [comment]
It defaults to the env injector template:

```yml
#============================#
# ALEXBELGIUM'S ENV INJECTOR #
#============================#
#
# All env variables set in this file will be enabled in the app
# This allows enabling more options that normally available in the addon options
# This file must be filled according to the yaml format.
# If the format is invalid, the addon will note an error.
# To validate your yaml, you can use the free online tool http://www.yamllint.com/
# You can use env both for the addon, and for bashio. For bashio, use BASHIO_LOG_LEVEL instead of LOG_LEVEL

# EXAMPLE of the format (you need to remove the # for it to become active)
#TZ: Europe/Paris
```

However like this it fails to start as it doesn't find any env variables to set. Uncommenting the `TZ` fixes the startup

**Comment by alexbelgium** [comment]
Thanks! I'll push a new version this afternoon with the addon_config folder and we'll see if it makes a difference

**Comment by JeffersonBledsoe** [comment]
@alexbelgium Seems to work well from the new location, thanks! I also tested doing a fresh install and it now starts up without having to manually create the file, nice work!
