### ISSUE TITLE
🐛 [EPic Games Free] Add-on won't start after latest update 

### ISSUE THREAD

**Issue by LordSimpson** [alexbelgium/hassio-addons#1356]
### Description

Current version: debian-2024-04-26

After update Addon wont start logs only show the below

exec /sbin/tini: exec format error

### Reproduction steps

```bash
1. Go to Addon
2. Click on Start
3. Swap to Log
4. "exec /sbin/tini: exec format error"
```

### Addon Logs

```bash
exec /sbin/tini: exec format error
```

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks! It means the upstream container messed up their architecture :) i'll revert
