### ISSUE TITLE
🐛 [Plex Meta Manager] is now Kometa

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#1357]
### Description

Plex meta manager got rebranded to https://kometa.wiki/en/latest/ config and stuff changed, addon should be renamed and updated

**Comment by kineticscreen** [comment]
I don't know if this is related, but at some point recently all of my overlays have been stripped out, and now the log is littered with 'can't find overlay file' errors. Has the name change broken the functionality for others?

**Comment by bruvv** [comment]
yes the config changed, everything that has `pmm` in the config file should be changed to `default`

**Comment by kineticscreen** [comment]
Yeah not sure what's happened, but something more fundamental has broken since then.

`[2024-05-10 03:30:27,073] [kometa.py:312]             [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/app/pmm/modules/util.py", line 1033, in __init__                                          |
                                                                 |     self.data = self.yaml.load(fp)                                                                 |
                                                                 |                 ^^^^^^^^^^^^^^^^^^                                                                 |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/main.py", line 451, in load               |
                                                                 |     return constructor.get_single_data()                                                           |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                           |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data |
                                                                 |     return self.construct_document(node)                                                           |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                           |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 125, in construct_document |
                                                                 |     for _dummy in generator:                                                                       |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1476, in construct_yaml_map |
                                                                 |     self.construct_mapping(node, data, deep=True)                                                  |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1365, in construct_mapping |
                                                                 |     value = self.construct_object(value_node, deep=deep)                                           |
                                                                 |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object |
                                                                 |     data = self.construct_non_recursive_object(node)                                               |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object |
                                                                 |     for _dummy in generator:                                                                       |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1476, in construct_yaml_map |
                                                                 |     self.construct_mapping(node, data, deep=True)                                                  |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1365, in construct_mapping |
                                                                 |     value = self.construct_object(value_node, deep=deep)                                           |
                                                                 |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object |
                                                                 |     data = self.construct_non_recursive_object(node)                                               |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object |
                                                                 |     for _dummy in generator:                                                                       |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1476, in construct_yaml_map |
                                                                 |     self.construct_mapping(node, data, deep=True)                                                  |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1365, in construct_mapping |
                                                                 |     value = self.construct_object(value_node, deep=deep)                                           |
                                                                 |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object |
                                                                 |     data = self.construct_non_recursive_object(node)                                               |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object |
                                                                 |     for _dummy in generator:                                                                       |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1469, in construct_yaml_seq |
                                                                 |     data.extend(self.construct_rt_sequence(node, data))                                            |
                                                                 |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                             |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1217, in construct_rt_sequence |
                                                                 |     ret_val.append(self.construct_object(child, deep=deep))                                        |
                                                                 |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object |
                                                                 |     data = self.construct_non_recursive_object(node)                                               |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object |
                                                                 |     for _dummy in generator:                                                                       |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1476, in construct_yaml_map |
                                                                 |     self.construct_mapping(node, data, deep=True)                                                  |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1366, in construct_mapping |
                                                                 |     if self.check_mapping_key(node, key_node, maptyp, key, value):                                 |
                                                                 |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                  |
                                                                 |   File "/lsiopy/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 278, in check_mapping_key |
                                                                 |     raise DuplicateKeyError(*args)                                                                 |
                                                                 | ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping                            |
                                                                 |   in "/config/addons_config/plex-data-manager/config.yml", line 66, column 9                       |
                                                                 | found duplicate key "template_variables" with value "{'data': {'starting': 'latest-10', 'ending': 'latest'}}" (original value: "{'data': {'starting': 'latest-10', 'ending': 'latest'}}") |
                                                                 |   in "/config/addons_config/plex-data-manager/config.yml", line 74, column 9                       |
                                                                 |                                                                                                    |
                                                                 | To suppress this check see:                                                                        |
                                                                 |     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys                                   |
                                                                 |                                                                                                    |
                                                                 |                                                                                                    |
                                                                 | During handling of the above exception, another exception occurred:                                |
                                                                 |                                                                                                    |
                                                                 | Traceback (most recent call last):                                                                 |
                                                                 |   File "/app/pmm/kometa.py", line 310, in start                                                    |
                                                                 |     config = ConfigFile(default_dir, attrs, secret_args)                                           |
                                                                 |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           |
                                                                 |   File "/app/pmm/modules/config.py", line 193, in __init__                                         |
                                                                 |     self.data = YAML(self.config_path).data                                                        |
                                                                 |                 ^^^^^^^^^^^^^^^^^^^^^^                                                             |
                                                                 |   File "/app/pmm/modules/util.py", line 1036, in __init__                                          |
                                                                 |     raise Failed(f"YAML Error: {e}")                                                               |
                                                                 | modules.util.Failed: YAML Error: while constructing a mapping                                      |
                                                                 |         in "/config/addons_config/plex-data-manager/config.yml", line 66, column 9                 |
                                                                 |       found duplicate key "template_variables" with value "{'data': {'starting': 'latest-10', 'ending': 'latest'}}" (original value: "{'data': {'starting': 'latest-10', 'ending': 'latest'}}") |
                                                                 |         in "/config/addons_config/plex-data-manager/config.yml", line 74, column 9                 |
                                                                 |                                                                                                    |
                                                                 |       To suppress this check see:                                                                  |
                                                                 |           http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys                             |
                                                                 |                                                                                                    |
                                                                 |                                                                                                    |
[2024-05-10 03:30:27,092] [kometa.py:313]             [CRITICAL] | YAML Error: while constructing a mapping                                                           |
                                                                 |         in "/config/addons_config/plex-data-manager/config.yml", line 66, column 9                 |
                                                                 |       found duplicate key "template_variables" with value "{'data': {'starting': 'latest-10', 'ending': 'latest'}}" (original value: "{'data': {'starting': 'latest-10', 'ending': 'latest'}}") |
                                                                 |         in "/config/addons_config/plex-data-manager/config.yml", line 74, column 9                 |
                                                                 |                                                                                                    |
                                                                 |       To suppress this check see:                                                                  |
                                                                 |           http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys                             |
                                                                 |                                                                                                    |
[2024-05-10 03:30:27,094] [kometa.py:321]             [INFO]     |                                                                                                    |
[2024-05-10 03:30:27,095] [kometa.py:396]             [INFO]     |========================================= Critical Summary =========================================|
[2024-05-10 03:30:27,096] [kometa.py:398]             [INFO]     |                                                                                                    |
[2024-05-10 03:30:27,096] [kometa.py:399]             [INFO]     | Count | Message                                                                                    |
[2024-05-10 03:30:27,096] [kometa.py:400]             [INFO]     |=======|============================================================================================|
[2024-05-10 03:30:27,097] [kometa.py:402]             [INFO]     |     1 | YAML Error: while constructing a mapping                                                   |
[2024-05-10 03:30:27,097] [kometa.py:403]             [INFO]     |                                                                                                    |
[2024-05-10 03:30:27,098] [kometa.py:408]             [INFO]     |====================================================================================================|
[2024-05-10 03:30:27,098] [kometa.py:408]             [INFO]     |                                         Finished 03:30 Run                                         |
[2024-05-10 03:30:27,099] [kometa.py:408]             [INFO]     |                            Version: 1.21.1        Newest Version: 2.0.1                            |
[2024-05-10 03:30:27,099] [kometa.py:408]             [INFO]     |                          Finished: 03:30:27 2024-05-10 Run Time: 0:00:00                           |`

**Comment by neogrinch** [comment]
yes I tried updating my config file, got it partially working, but it still wasn't doing overlays, just skipped them all. So I have moved away from using this addon until it gets (hopefully) updated since I have zero idea how to make this stuff myself, I depend on amazing addon creators like alexbelgium :D

**Comment by akrigator** [comment]
finally unflagged github my account

**Comment by akrigator** [comment]
Transitioning from PMM to Kometa:
1. Install a new kometa addon https://github.com/alexbelgium/hassio-addons/tree/master/kometa
2. Start the new addon and terminate after kometa config folder is created in addon_configs directory
3. Copy content of `config.yml` from plex meta manager addons to the new one
4. Replace `- pmm:` by `- default:` in kometa's `config.yml`
5. Start Kometa addon
6. Uninstall PMM addon

Has been checked on Raspberry 4 under HAOS

**Comment by neogrinch** [comment]
WOOOHOOOO, thank you so much for getting this updated to Kometa, you rock!

**Comment by akrigator** [comment]
i guess that issue may be closed now
