### ISSUE TITLE
❓ WHATSAPPER : Cannot Start in Home Assistant

### ISSUE THREAD

**Issue by siw1973** [alexbelgium/hassio-addons#1358]
https://github.com/alexbelgium/hassio-addons/issues/1358#issuecomment-2080480998

**Comment by alexbelgium** [comment]
Hi, just change the portainer password in the addon options and it will reset its database

**Comment by alexbelgium** [comment]
Data for addons can be stored in different places : /data (within addons) gets deleted when addon is un-installed, but /config is remanent and can only be deleted by using a tool such as my filebrowser addon. Ha had indeed some quirks to know to understand why things behave how they do ;)

**Comment by siw1973** [comment]
> Hi, just change the portainer password in the addon options and it will reset its database

I truly am an idiot.........

With respect to Whatsapper I'm getting the following message on start up 👍 

`TypeError: Cannot read properties of null (reading '1')`

I've found reference to changing the launch arguements here : https://github.com/pedroslopez/whatsapp-web.js/issues/2885

But can't figure out where to do this.

Should I create a new question ?

**Comment by alexbelgium** [comment]
Ah ah, no problem.

For whatsapper dear @baldarn would you have an idea? thanks !

**Comment by baldarn** [comment]
Hi! will try to have a look today ;)

**Comment by siw1973** [comment]
@baldarn Thank you, I can't find an idiots guide to setting this up, if I've missed one let me know and I'll have a go.

**Comment by baldarn** [comment]
the issue seems to be well known. I'll try to solve that and push another version of the addon :/

**Comment by alexbelgium** [comment]
thanks very much!

**Comment by baldarn** [comment]
@alexbelgium we can try to update with this. we could solve the issue :/

**Comment by siw1973** [comment]
Wow, you guys are agile and efficient !Let me know when it's up on HACS and I'll test straight away 👍

**Comment by baldarn** [comment]
@siw1973 not jet, I did an error in the pr for the update :(

**Comment by baldarn** [comment]
still some errors... damn upgrades of libraries and docker images :/

will fix today. I hope :/

**Comment by baldarn** [comment]
@alexbelgium the error seems related to this change

whatsapper/Dockerfile:37

https://github.com/alexbelgium/hassio-addons/commit/a29a371cbc37b3bc89f439eaeaea369e7f430966

error link:
https://github.com/alexbelgium/hassio-addons/actions/runs/8876921382/job/24369467874


what is this needed for? is this necessary?

**Comment by baldarn** [comment]
pr to remove the line

https://github.com/alexbelgium/hassio-addons/issues/1365

**Comment by baldarn** [comment]
the issue should be solved in version 2024.4.29-1

@siw1973 could you give a try? :)

**Comment by siw1973** [comment]
Hi there unfortunatley a same error on Update : 

`Can't install ghcr.io/alexbelgium/whatsapper-amd64:2024.4.29: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=2024.4.29&fromImage=ghcr.io%2Falexbelgium%2Fwhatsapper-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

I even removed the Intergation and then couldn't get it to Install either, has the same error.

**Comment by baldarn** [comment]
mmm strange. that was solved to me. it seems you are updating the old version.

try to update the addons.

**Comment by siw1973** [comment]
I deleted the old Add On  and now can't get it to Install. Anything that may not have been removed ? Disabled the Firewall on the VM host just to make sure.

**Comment by siw1973** [comment]
All OK 👍 

Restarted the whole VM stack and go to the QR code screen.

Thanks for all your help !

**Comment by siw1973** [comment]
Quick one, do I need to do any Port Forwarding as I have 443 in use elsewhere exposed to the Internet ?

I'm not getting anything on https://IP:4000 or HTTP://IP:4000.

**Comment by alexbelgium** [comment]
Manifest unknown just means it can't find the build online :-) either due to build not yet completed or failed ; or due to the HA cache being not refreshed

**Comment by baldarn** [comment]
I'm trying the system locally, but is not working. it seems whatsapp changed his web app and the library that I'm using is still not working for saving the state

see

https://github.com/pedroslopez/whatsapp-web.js/pull/2816

**Comment by siw1973** [comment]
LOL !

I'm the kiss of Doom..... Always late to the party and it's invariably closing down when I arrive !

Thanks again 👍

**Comment by baldarn** [comment]
@siw1973 lol!

I think something will came out in the next days or weeks.

if not, I will consider moving to another library ;)

**Comment by siw1973** [comment]
I modded the title and intial query to not make me look like a total idiot :-)

**Comment by baldarn** [comment]
this could fix things :)

https://github.com/alexbelgium/hassio-addons/pull/1367

**Comment by baldarn** [comment]
@alexbelgium you can close this ;)
