### ISSUE TITLE
ResilioSync🐛 [Addon name] <title>

### ISSUE THREAD

**Issue by UKnau22** [alexbelgium/hassio-addons#1368]
### Description

I installed ResilioSync on HomeAssistant OS 12.2, but when I start the add-on and try to view the logs it fails to fetch them. I uninstalled and reinstalled the add-on several times with the same result.

### Reproduction steps

```bash
1. Go to 'Logs'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
Failed to get add-on logs, Failed to fetch
```

### Architecture

aarch64

### OS

HAos

**Comment by UKnau22** [comment]
Fixed itself on it's own. Maybe an HA update did it...?

**Comment by alexbelgium** [comment]
Sometimes HA is strange and breaks or fixes things unexpectedly... Glad it is now working though!
