### ISSUE TITLE
✨ [birdnet-pi] Ongoing work

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#1371]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Birdnet-pi as legacy alternative to birdnet-go while it is developed

### Is your feature request related to a problem? Please describe

List ongoing work

### Describe the solution you'd like

Todo :
- [x] Structure + symlinks
- [x] Duplicate detection for birdnet.conf
- [x] tmpfs inclusion
- [x] minimum ingress to access stats
- [x] systemctl works
- [x] alignement of pi and caddy UID to allow db access
- [x] correct php to have error message if db read only
- [x] finish and start script to salvage and reused StreamData in temporary folder
- [x] implement translated ebird with labels
- [x] set birdsongs location from addon options
- [x] set terminal password from addon options
- [x] View log doesn't work
- [x] Duplicate options 
- [x] Analysis robust (check new monitoring service works as intended)
- [x] Remove journald to only use /proc
- [x] Correct ebird taxo: https://www.birds.cornell.edu/clementschecklist/wp-content/uploads/2023/12/ebird_taxonomy_v2023-csv.zip
- [x] Test on VM
- [x] Test on supervised 
- [x] cron not running
- [x] enable disk purge
- [x] Add webui for convert species
- [x] Managing authentification in ingress
- [x] Add button to save wav if no detections
- [ ] Ingress broken for terminal, filebrowser and stats
- [ ] Add new graphs from main repo

Improve birndet-pi
- [x] daily_plot.py:101: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
- [x] Have ebirds vs aboutallbirds as an option
- [x] Changed identified bird. Script created. Now would need an icon in the statspage (next to FreqShift which opens a listbox to select the new specie, then execute the script already written with inputs of the mp3 url and the new specie)
- [x] Automatically convert one bird to another ? (dangerous) - based on a text file with ;
- [x] Weekly detections page
- [ ] Create a new sqlite column (or a separate table) with status : CONFIRMED ; UNCONFIRMED ; PROBABLE
- [ ] Increase confidence level needed when raining based on buienradar? Or other app
- [ ] Have a different threshold for rare and usual birds

**Comment by deadrubberboy** [comment]
Hello! Where do I configure an RTSP input? I tried the web interface but the "tools" button says I can't config there. I only see "default" as audio option in the config. 

*I'm running Scrypted add on and can get rtsp rebroadcast from there or direct from Amcrest camera. Neither is "IN" HA currently.

**Comment by alexbelgium** [comment]
Hi ! Ingress isn't working that much for the moment but you can access it fine using ip:port!

**Comment by deadrubberboy** [comment]
Hello! Not sure what "ingress" is. I can access the green page. When I tried "tools" to get to settings the first time I got an error. I got in just now though! I'll see if I can get rtsp configured. Thanks!

**Comment by deadrubberboy** [comment]
Thanks! I made progress. When I go to "spectrogram" I can hear my camera audio. I can actively hear birds chirping too. No detections. 

When I click on "log" from the web interface I see an error "rtsp @ 0xaaaaea3eba00] method SETUP failed: 461 Unsupported Transport".

Any ideas?

**Comment by alexbelgium** [comment]
Well that's great! Now it means (according to chatgpt) that you are using a protocol (either tcp or udp) not supported by ffmpeg, is that an option for you to change the rtsp sound options?

**Comment by deadrubberboy** [comment]
I'm using Scrypted rebroadcast stream. I changed it from "scrypted TCP" to "FFMPEG TCP". Rebooting.

How can I be sure it's saving /reading a file?I see in config the default location is /config/BirdSongs - Do I need to create that folder somewhere?

**Comment by deadrubberboy** [comment]
Should I go by "your" log or the one on web interface (green screen)?

**Comment by deadrubberboy** [comment]
Sorry. I keep peppering you with stuff! Not even sure this is the best format. Sorry, I'm totally new. 

Good news though! I noticed the file reference in the log was ".wav" and the setting for recording was ".mp3". I changed the mp3 pulldown to .wav and rebooted again. There's a detection! Hopefully I got it sorted. Thank you for your work on this and your patience with me specifically!

**Comment by alexbelgium** [comment]
> Should I go by "your" log or the one on web interface (green screen)?

It's the same! It both is stdout

> How can I be sure it's saving /reading a file

Whey the spectrogram you can check that the rtsp stream works. With the log you can see if there is an error. On the first page you would see the spectrogram being analyzed, and detections!

**Comment by alexbelgium** [comment]
> Sorry. I keep peppering you with stuff! Not even sure this is the best format. Sorry, I'm totally new.
> 
> Good news though! I noticed the file reference in the log was ".wav" and the setting for recording was ".mp3". I changed the mp3 pulldown to .wav and rebooted again. There's a detection! Hopefully I got it sorted. Thank you for your work on this and your patience with me specifically!

Great! There is actually no link : the stream is read as a wav, but it is saved as a mp3 (after analysis) for future reading as a very efficient storage method. I would recommend you keep it.

**Comment by deadrubberboy** [comment]
I'm still seeing the error. Must have been unrelated. I'll go back in and change back to mp3. Thank you again.

**Comment by deadrubberboy** [comment]
Does this tell you anything? I see the RTSP error but then still says analyzing audio file?

![CleanShot 2024-05-15 at 16 22 36](https://github.com/alexbelgium/hassio-addons/assets/79318712/62caba74-de02-4865-ad63-afb924bf8a12)

**Comment by deadrubberboy** [comment]
I AM still seeing detection pop up... 🤷‍♂️

![CleanShot 2024-05-15 at 16 27 08](https://github.com/alexbelgium/hassio-addons/assets/79318712/1d7b7a7e-fc47-4386-931f-5c90ba251e5c)

**Comment by deadrubberboy** [comment]
Popped open log again. I guess it's hit and miss?

https://github.com/alexbelgium/hassio-addons/issues/1371#issuecomment-2113374970

**Comment by deadrubberboy** [comment]
Popped open log again and see what looks like a success in the RTSP. I guess it's hit and miss?
![CleanShot 2024-05-15 at 16 43 07](https://github.com/alexbelgium/hassio-addons/assets/79318712/7add2c5d-7476-4ce4-a438-a3a23fc110bf)

**Comment by alexbelgium** [comment]
Well as long as it works :) perhaps your rtsp stream is not stable? You could try with an app that connects to the rtsp stream to see if there is no interruptions in the stream. It could be seen from the live spectrogram too

**Comment by deadrubberboy** [comment]
thinking it's related to the new instructions are Let's Encrypt? I'm installing that add on now. Didn't have before.

**Comment by alexbelgium** [comment]
Hi, sorry for all the versions there was _many_ things to adapt to be able to use ssl while taking into account Homeassistant's and docker limitations... I think it is a permission issue, I encountered the same. The thing is that each time the addon is closed or restarted, all files not yet analyzed are copied in /data/Streamdata, then put back in the analysis queue when the addon is started again.

What I would propose to you : enable the web terminal from the Tools/Service tab, then go to the Web terminal, login with the user "pi" and the password that you put in the addon options, and type : `chown -R pi:pi /tmp/StreamData && chmod -R 777 /tmp/StreamData && echo "done"`

**Comment by alexbelgium** [comment]
> thinking it's related to the new instructions are Let's Encrypt? I'm installing that add on now. Didn't have before.

There is 2 ways to achieve ssl : 
- Have a https url reported in the birdnet.conf + have port 80 mapped to 80 in the addon options : it will use caddy's automatic certificates system to provide ssl. For that, the ssl option must be set to false in the addon options (default)
- Activate the ssl option in the addon options, it will go fetch the certificates from the Let's Encrypt addon and automatically set-up https

**Comment by alexbelgium** [comment]
Btw (sorry for the multiposts) ; in theory a script exists that checks the content of StreamData. when there is more than 100 files ; it will restart services and redo permissions to fix potential issues

The only failure I saw was when the disk is full ; it seems to analyse but actually don't save anything

**Comment by deadrubberboy** [comment]
> Hi, sorry for all the versions there was _many_ things to adapt to be able to use ssl while taking into account Homeassistant's and docker limitations... I think it is a permission issue, I encountered the same. The thing is that each time the addon is closed or restarted, all files not yet analyzed are copied in /data/Streamdata, then put back in the analysis queue when the addon is started again.
> 
> What I would propose to you : enable the web terminal from the Tools/Service tab, then go to the Web terminal, login with the user "pi" and the password that you put in the addon options, and type : `chown -R pi:pi /tmp/StreamData && chmod -R 777 /tmp/StreamData && echo "done"`

Thanks for the quick reply! Did this (had to add sudo to front of that command - got error otherwise). Seems to have fixed it! Will I need to run that whenever there is an update?

Do I need to enable SSL? What are the risks if I don't? I run HA in a VM on an always on MacMini. It has its own (internal/local) IP address. I don't need to access the web interface of Bridnet-Pi outside of home. If I do, I can always do it in the HA app via iPhone/Mac via the Nubocasa link. I pay for the remote access to support them, but rarely use it.

**Comment by alexbelgium** [comment]
I've added this permissions fix in the startup script ; it won't happen again :) that's the good thing about debugging like that on github, once I'm aware I try to find a solution that should avoid the issue for other users or in the future :-)

For ssl it's only recommended if you use it externally... I've put so much effort on it because my domain forces me to use https and it was bugging me not to be able to use it :-)

**Comment by deadrubberboy** [comment]
Thanks again!

**Comment by deadrubberboy** [comment]
Hello again! Got this after today's update. Stopped detecting:

![CleanShot 2024-06-04 at 16 07 08@2x](https://github.com/alexbelgium/hassio-addons/assets/79318712/70cd33c9-3b57-46fe-b1fc-f212932d8a0f)

**Comment by deadrubberboy** [comment]
Bigger section from "your log":


![CleanShot 2024-06-04 at 16 14 14@2x](https://github.com/alexbelgium/hassio-addons/assets/79318712/5b9dc209-bae6-46e6-93d4-9830b8768659)

**Comment by alexbelgium** [comment]
Thanks! Argh I'm sorry. Please try adding PROCESSED_SIZE=0 to your birdnet.conf. I'll revert the change to avoid issue for other users

**Comment by deadrubberboy** [comment]
Happy to help!

And thanks! That (PROCESSED_SIZE=0) seems to have solved it!

**Comment by deadrubberboy** [comment]
Just sent a coffee your way 😉

**Comment by alexbelgium** [comment]
Thanks very much! I tried to readd the Processed folders to be able to retrieve wav file for analysis if we are not happy about detections but it seems something messed out as it doesn'r automatically add the value to the birdnet.conf... And this value is costumizable from the settings page :)

But seeing your issue i'll revert so other people don't lose detections

**Comment by knobunc** [comment]
Something weird happens with the timezone.  It's set correctly in `/etc/timezone` and `$TZ`.  But `/home/pi/BirdNET-Pi/scripts/common.php`uses `timedatectl` and that fails...:
```
# timedatectl show --value --property=Timezone
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

And I have tried setting the timezone in several different areas, but it ends up as UTC rather than America/New_York

**Comment by alexbelgium** [comment]
Thanks! Audio stream not starting automatically is actually the normal feature, as it is not enabled in Birdnet-Pi startup sequence that I saw online... I could indeed add it. I think by default it is disabled to reduce resources usage. Terminal is also inactive by default, more likely for security reasons.

For the time, is it a real issue (= time not correct for observations) or a UI issue (= time not correct in the settings)? On my pi the detections are right but not the settings. I had not thought about it but thanks very much for finding the cause, I'll find a way to get time another way!

**Comment by alexbelgium** [comment]
> Something weird happens with the timezone. It's set correctly in `/etc/timezone` and `$TZ`. But `/home/pi/BirdNET-Pi/scripts/common.php`uses `timedatectl` and that fails...:
> 
> ```
> # timedatectl show --value --property=Timezone
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> ```
> 
> And I have tried setting the timezone in several different areas, but it ends up as UTC rather than America/New_York

Both your points will be corrected in the next build
