### ISSUE TITLE
🐛 [BROWSERLESS-CHROME] Add on on ARM stuck on old version 2.2.0-5

### ISSUE THREAD

**Issue by wigster** [alexbelgium/hassio-addons#1375]
### Description

Whenever a new version of the add on is released, the possibility to upgrade to it on my ARM-based HAOS installation appears briefly -- it fails with an error in the notifications, but I have not managed to write down. Then usually the upgraded version disappears.

ARM chips are currently being offered 2.2.0-5 instead of 2.8.0 -- in the Docker images the arm architecture 2.8.0 is available:

https://github.com/browserless/browserless/pkgs/container/base/211508499?tag=latest

Is there any change of an upgrade? Thanks!

### Reproduction steps

```bash
Release notes show 2.8.0 as latest. No upgrade appears.
```

### Addon Logs

```bash
No relevant log.
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, looks like on github the architectures are broken : https://github.com/browserless/browserless/pkgs/container/chrome/211510936?tag=latest

**Comment by wigster** [comment]
Ah -- is this because there isn't an arm64 chrome but only chromium in the first place?

**Comment by alexbelgium** [comment]
Mmh it probably existed in the past as the build initially succeeded... I'll be away for some time but can try to move to chromium if you want when I'm back

**Comment by wigster** [comment]
That would be great if you could!

**Comment by alexbelgium** [comment]
indeed you are right there is no arm64 in any chrome which makes me wonder what is in the current addon ;-) I'll push a version on chromium but won't be able to support it for some time

**Comment by wigster** [comment]
I have a feeling that they used to just put chromium in the arm64 docker image and with the move to 2.0 at some point they split it into chrome and chromium

**Comment by alexbelgium** [comment]
Please let me know how that goes! I've named it in a strange way to avoid people breaking their install if it doesn't work

**Comment by wigster** [comment]
It seems to work for the scripts I am running. Thanks a lot!
