### ISSUE TITLE
🐛 [linkwarden] Addon is not using the latest version

### ISSUE THREAD

**Issue by axute** [alexbelgium/hassio-addons#1376]
### Description

The Home Assistant Addon is not using the latest image, so the browser extensions don't work.
See here current tags:
https://github.com/linkwarden/linkwarden/pkgs/container/linkwarden/versions?filters%5Bversion_type%5D=tagged
main branch is 7 months old, latest is 15 days old.

Please switch to latest 🙏

### Reproduction steps

```bash
1. Install the HA addon
2. Setup a user
3. Install the chrome extension
4. See error (debug extension, endpoint /api/v1/auth/csrf is 404)
```

### Addon Logs

```bash
not available, because only 404 from the chrome extension.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, I had paused the updates due to the deprecation ; but I removed that flag now so it will update this night!

**Comment by axute** [comment]
I tried the last 3 days, but no update was found.

**Comment by alexbelgium** [comment]
OK I misread and thought it was bitwarden. Sorry. Indeed my linkwarden addon was not set for automatic updates i'll add it now!

**Comment by axute** [comment]
hm for me nothing changed, also can see that you build still from outdated "main": linkwarden/build.yaml (or isn't it used?)

**Comment by alexbelgium** [comment]
Indeed, I pushed a v2 with latest tag

**Comment by axute** [comment]
Thanks so much! The browser extension also works now, thank you :-)

**Comment by alexbelgium** [comment]
Thanks to you!
