### ISSUE TITLE
❓ [Whatsapper] connect error

### ISSUE THREAD

**Issue by i-Nosferatu-i** [alexbelgium/hassio-addons#1382]
Hi. I need help to connect "Whatsapper" to " WhatsApp".
When I try to scan QR (Link a device), WhatsApp gets an error: "Couldn't link device. Try again later."

And I have error about notify
In configuration.yaml:
notify:
      - platform: whatsapper
        name: "whatsapper"
        chat_id: *************@g.us

Developer tools -> CHECK CONFIGURATION
Configuration warnings
Platform error 'notify' from integration 'whatsapper' - Integration 'whatsapper' not found.

**Comment by hiagocosta** [comment]
I'm just installed the latest version (1.0.1) and getting in the same mesaage, how did you fix that?
