### ISSUE TITLE
🐛 [Firefly iii] config.yaml does not seem to be working

### ISSUE THREAD

**Issue by MiroVerleysen** [alexbelgium/hassio-addons#1383]
### Description

As I forgot my password and I have not set up Email correctly i wanted to turn on MAIL_MAILER but it does not seem to have any effect. I turned it on by adding this to the config.yaml file: "MAIL_MAILER: log". As described in these issues: https://github.com/firefly-iii/firefly-iii/issues/4039
https://github.com/firefly-iii/firefly-iii/issues/4127

But I don't get the mailer logs, obviously I restarted the add-on after my changes.

### Reproduction steps

```bash
Used config.yaml

#============================#
# ALEXBELGIUM'S ENV INJECTOR #
#============================#
#
# All env variables set in this file will be enabled in the app
# This allows enabling more options that normally available in the addon options
# This file must be filled according to the yaml format.
# If the format is invalid, the addon will note an error.
# To validate your yaml, you can use the free online tool http://www.yamllint.com/

# EXAMPLE of the format (you need to remove the # for it to become active)
# TZ: Europe/Paris
APP_LOG_LEVEL: debug
MAIL_DRIVER: log
MAIL_MAILER: log
MAIL_LOG_CHANNEL: stack
```

### Addon Logs

```bash
.
```

### Architecture

amd64

### OS

HAos

**Comment by MiroVerleysen** [comment]
I just checked the .env file of the container, the file looks like this. are these single quotation marks allowed in there?

```
APP_KEY='blabla'
CONFIG_LOCATION='/config/addons_config/fireflyiii/config.yaml'
DB_CONNECTION='sqlite_internal'
Updates='weekly'
silent='false'
APP_LOG_LEVEL='debug'
MAIL_DRIVER='log'
MAIL_MAILER='log'
MAIL_LOG_CHANNEL='stack'
MAIL_HOST='smtp.gmail.com'
MAIL_PORT='587'
MAIL_FROM='emailaddr@gmail.com'
MAIL_USERNAME='emailaddr@gmail.com'
MAIL_PASSWORD='blabla'
MAIL_ENCRYPTION='tls'
```

**Comment by alexbelgium** [comment]
Hi, according to this it should : https://stackoverflow.com/questions/71538752/when-are-quotes-needed-in-env-file

However perhaps Firefly doesn't read it... Sorry i'm off for some time so i can't really check for the moment

**Comment by alexbelgium** [comment]
Hi, according to this it should : https://stackoverflow.com/questions/71538752/when-are-quotes-needed-in-env-file

However perhaps Firefly doesn't read it... Sorry i'm off for some time so i can't really check for the moment

**Comment by alexbelgium** [comment]
Actually the real passing of the env variables should be when they are added at the start of the /etc/cont-init.d/99-run.sh file... Then they should be passed to the /usr/local/bin/entrypoint.sh file... Which works as the database connects so I wonder if there is not an interfering variable lost somewhere...

**Comment by alexbelgium** [comment]
I see "MAIL_LOG_CHANNEL: stack" what does it means? In docker containers the stdout output is normally used as /proc/1/fd/1 to send it to the addon logs, I wonder if your logs are not stuck somewhere in the add-on...

**Comment by alexbelgium** [comment]
And if you use Gmail are you using an app key? As default username and password will likely not work if you have 2fa enabled

**Comment by MiroVerleysen** [comment]
I noticed an error saying app_url was missing, so what I did is rebuilding the container using portainer with this env variable along with the mail log vars after which it was working. I will double check whether it is working via the config.yaml file instead of the portainer method I used. 

Thank you for your investigation. I'll keep you updated, for now my issue is solved, got a new password.

**Comment by alexbelgium** [comment]
That's the most important! Glad it worked for you

**Comment by FabriceMethou** [comment]
Hey Guy,
I got the same issue and I'm stuck at the app-url part any guidance ?

**Comment by alexbelgium** [comment]
Hi Fabrice have you tried specifying the app_url in the config.yaml?
