### ISSUE TITLE
🐛 [resiliosync] <2.8.0.1389>

### ISSUE THREAD

**Issue by ovikiss** [alexbelgium/hassio-addons#1392]
### Description

No new 2.8.0.1389 container image.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
Error updating ResilioSync: Can't install ghcr.io/alexbelgium/resiliosync-aarch64:2.8.0.1389

Latest image is old 2.7.3-12.
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks, armv7 deprecated image was messing the build. I've removed it
