### ISSUE TITLE
✨ [REQUEST] Photoprism newer version available

### ISSUE THREAD

**Issue by Rgasd** [alexbelgium/hassio-addons#1394]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Photoprism

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

Hi, there is a newer stable release https://github.com/photoprism/photoprism/releases

can someone pull this to the HA Docker addon ?

**Comment by alexbelgium** [comment]
Hi, updates are every Saturdays

**Comment by Rgasd** [comment]
yes, for plex for example this is true and fine, but maybe the bot for photoprism has a "problem" with updating photoprism , the version is still this build :
Build [231128-f48ff16ef](https://docs.photoprism.app/release-notes/)   [PhotoPrism® CE]

**Comment by alexbelgium** [comment]
Thanks i'll look

**Comment by Rgasd** [comment]
thank you, you fixed it.
btw it is now :
[PhotoPrism® CE]
Build [240518-43a5a28b4](https://docs.photoprism.app/release-notes/)

so it should be directly pushed to Docker: [Upgraded base image from Ubuntu 23.10 to Ubuntu 24.04 LTS]
thx

**Comment by alexbelgium** [comment]
thanks ; not sure why it is not updated automatically I think it is due to their very strange naming nomenclature that is discarded by the tool
