### ISSUE TITLE
🐛 [Jellyfin] DLNA config not found

### ISSUE THREAD

**Issue by hugoKs3** [alexbelgium/hassio-addons#1400]
### Description

Since the last update, I can no longer access Jellyfin from DLNA devices.
When accessing the DLNA config from the web UI there is a infinite spinning wheel and an exception is raised in the logs.
When I look into the config folder of Jellyfin add-on, I do have a dlna.xml file with my parameters.

Could you please assist?

Thank you.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
[ERR] [22] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /System/Configuration/dlna.
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key dlna not found.
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, looks like jellyfin moved dlna to a plug-in https://github.com/jellyfin/jellyfin/issues/11065#issuecomment-1963048235

**Comment by paoloantinori** [comment]
Bug definitely still there in  Version: 10.9.3

**Comment by alexbelgium** [comment]
Hi, according to the link in my post above it seems not to be a bug but the new behavior of jellyfin
