### ISSUE TITLE
[NAVIDROME] Can't read config.json

### ISSUE THREAD

**Issue by Failure404** [alexbelgium/hassio-addons#1417]
### Description

Can't read json from /data/addons/git/db21ed7f/navidrome/config.json: trailing comma is not allowed: line 29 column 4

This happens even though I don't have this addon installed.

### Reproduction steps

```bash
1. Search for updates
2. See the above error in syslog
```

### Addon Logs

```bash
N/A because I don't use this addon.
```

### Architecture

amd64

**Comment by alexbelgium** [comment]
Thanks! I've corrected it and relaunched the build
