### ISSUE TITLE
papermerge how to edit config?

### ISSUE THREAD

**Issue by didiatworkz** [alexbelgium/hassio-addons#142]
Hello @alexbelgium ,

can you tell me how it would be possible to set another parameters in `papermerge.conf.py`?
Especially, I'm looking for the [IMPORT_MAIL_* parameters](https://papermerge.readthedocs.io/en/1.3.0/settings.html#email) to collect all attachments from my Inbox.

Best
didiatworkz

**Comment by alexbelgium** [comment]
Hi didiatworkz, thanks for your interest.

The easiest way to add custom env variables is though the config.yaml situated in /config /addons_config /papermerge.

This won't appear yet, it will be in the next version :) I'm pushing it now. Please let me know how it goes!

>Config.yaml
>Custom env variables can be added to the config.yaml file referenced in the addon options. >Full env variables can be found here : https://papermerge.readthedocs.io/en/v1.4.2/settings.html. It must be entered in a valid yaml format, that will be verified at launch of the addon.

**Comment by alexbelgium** [comment]
Btw, is papermerge really better than paperless-ng or nextcloud? I'm not a user myself but was wondering about the fact of maintaining several apps with the same function ;) thanks for your input!

**Comment by didiatworkz** [comment]
Hello @alexbelgium,

your change not work as aspected..
Did I need any keyword for the yaml file?
```
config:
  xxxxx: xxx
```
Your totally right - I test currently both systems (papermerge and paperless-ng) but I would not say that nextcloud falls into this category. 
But paperless-ng has much more functionality as papermerge for my first opinion.

When I test IMAP import, maybe I can tell you which of the two is better.
Best
didiatworkz

**Comment by alexbelgium** [comment]
Full config exposed, so I'll close the issue. Please let me know how it goes!
