### ISSUE TITLE
🐛 Birdnet-Go

### ISSUE THREAD

**Issue by matthew73210** [alexbelgium/hassio-addons#1424]
### Description

Data not being purged. Looks like the config yaml is missing something. Copied the one from the birdnet-go github but the issues still happens. My folder is now 31 gb, and despite the data folder being mounted to addons, it doesn't appear there 
<img width="1002" alt="Screenshot 2024-06-07 at 5 09 58 PM" src="https://github.com/alexbelgium/hassio-addons/assets/19491784/9b67ddcb-3677-47a8-9d0d-d621d8991a33">

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
2024/06/07 16:59:36 Uploaded clips/2024/06/turdus_merula_98p_20240607T165929Z.wav to Birdweather
2024/06/07 16:59:37 New detection: Eurasian Blackbird with confidence: 0.992637
2024/06/07 16:59:43 Error retrieving clips for removal: invalid parameters: minHours and minClips must be greater than 0
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, what have you used as folder for saving clips in the birdnet-go settings ?

**Comment by matthew73210** [comment]
It just goes to /clips. If i shell into the container, I can find all the files under /data/clips 

Here’s the config part : 

  audio:
    source: "sysdefault"  # audio source to use for analysis
    export:
      enabled: true       # true to export audio clips containing indentified bird calls
      debug: true        # true to enable audio export debug messages
      path: clips/        # path to audio clip export directory
      type: wav           # only wav supported for now
      retention:        
        policy: usage     # retention policy: none, age or usage
        maxage: 30d       # age policy: maximum age of clips to keep before starting evictions
        maxusage: 80%     # usage policy: percentage of disk usage to trigger eviction        
        minclips: 10      # minumum number of clips per species to keep before starting evictions


￼

￼

Cheers for the quick reply

**Comment by alexbelgium** [comment]
So the folder is correctly used I'm not sure what is the issue ?

if purge does not happen alas it would be an issue with the upstream container more than the afin

**Comment by matthew73210** [comment]
Maybe i’m just a tad confused. I thourght that the /data/clips was supposed to appear in /addons/data/ContainerXXX (or something of the sort) as it’s mounted to that dir according to portainer?

Yep re purge probs a confg issue upstream

**Comment by alexbelgium** [comment]
Indeed /data should be mapped to /mnt/data/supervisor/addons/data/*_birdnet-go as you indicate from the screenshot! So /clips would be in that directory
