### ISSUE TITLE
✨ [REQUEST] Photoprism watchdog config

### ISSUE THREAD

**Issue by richard-scott** [alexbelgium/hassio-addons#1427]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Photoprism

### Is your feature request related to a problem? Please describe

Since the last release or two, having the watchdog setting enabled for the Add-on causes HA to restart the addon seemingly at random.

### Describe the solution you'd like

Please can you add a watchdog URL to the config to properly configure this element as I have no idea what it is checking when you do not configure this. Maybe also it would be worth reaching upstream to find out what the default is. I have looked [here](https://developers.home-assistant.io/docs/add-ons/configuration/) and can't see it sets a default.

**Comment by richard-scott** [comment]
I've reported this upstream [here](https://github.com/home-assistant/home-assistant.io/issues/33175), as the default location that the watchdog checks is not documented.

**Comment by alexbelgium** [comment]
Hi, thanks for reporting. My healthcheck is simply :
https://github.com/alexbelgium/hassio-addons/blob/692137463e0432445129b680c910e62734c20ecf/photoprism/Dockerfile#L126

If the line is already included upstream, I'll simply remove it ; and the upstream instruction will take precedence

**Comment by richard-scott** [comment]
Maybe you can put a watchdog element into the config.json file?

**Comment by alexbelgium** [comment]
Well the healthcheck was more flexible for me (and the watchdog element did not exist when I created it) as you can define the start time, the number of retries, ... But it my solution just pushed now (increase timeout) doesn't work I'll try this :-)

**Comment by richard-scott** [comment]
Seems stable now. Thanks.
