### ISSUE TITLE
🐛 [immich] need version 1.106 to make the Android app support it 

### ISSUE THREAD

**Issue by samimasad** [alexbelgium/hassio-addons#1430]
### Description

I had immich android app in auto update , as it get updated it no longer works for HA as it require at least 1.106.0 server while at HA it is at 1.105.1 , there is no way to only uninstall the update or install older version 
I hope new release of the add-on of at least 1.106 will be released 

### Reproduction steps

```bash
1. Go to Android immich
2. it will give error that server verison is not compatable
```

### Addon Logs

```bash
no logs needed
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, updates are every saturday

**Comment by samimasad** [comment]
Hi , 1.160.4 web ui and server port not working, please have a look at changelog for immich as i think it will require more work to make it work again with ha

**Comment by alexbelgium** [comment]
Could you please post your log? Thanks

**Comment by samimasad** [comment]
![UMREACHABLE](https://github.com/alexbelgium/hassio-addons/assets/781021/e7c982a1-9c76-4118-ad64-b710c809a90b)
[Nest] 1393  - 06/15/2024, 6:17:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
[Nest] 1393  - 06/15/2024, 6:17:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 1393  - 06/15/2024, 6:17:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 1393  - 06/15/2024, 6:17:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 1393  - 06/15/2024, 6:17:18 AM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 1393  - 06/15/2024, 6:17:18 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.106.4]

and from immich website
https://github.com/imagegenius/docker-immich/releases
![immich](https://github.com/alexbelgium/hassio-addons/assets/781021/2bcb1ddf-824f-41db-9edb-6bd02ae24c13)

**Comment by alexbelgium** [comment]
Thanks! Actually I use another all-in-one image but they have a solar discussion https://github.com/imagegenius/docker-immich/issues/372

**Comment by samimasad** [comment]
I hope fix will come soon as there is no way to manually set that in HA

**Comment by alexbelgium** [comment]
I've pushed a fix now let's see how that goes. Actually it is possible to set it manually using the portainer add-on, but this version should work

**Comment by Al3XKOoL** [comment]
This break my setup. Now immich addon is missing in the store.
`WARNING (SyncWorker_7) [supervisor.store.data] Can't read /data/addons/git/db21ed7f/immich/config.json: expected str for dictionary value @ data['environment']['IMMICH_PORT']. Got 8080`

**Comment by alexbelgium** [comment]
Ok corrected

**Comment by Al3XKOoL** [comment]
Now work! 
Thx 👍🏼

**Comment by alexbelgium** [comment]
Perfect! And immich starts?

**Comment by Al3XKOoL** [comment]
Fully working for me.
