### ISSUE TITLE
❓ [Firefly III] V6.1.17 is available and fixes interesting bug

### ISSUE THREAD

**Issue by MiroVerleysen** [alexbelgium/hassio-addons#1437]
**Which addon?**

Firefly III

**Addon or app?**

Addon

**Describe the solution you'd like**

v6.1.16 seems to have introduced this issue: [8907](https://github.com/firefly-iii/firefly-iii/issues/8907 ) which makes it basically impossible to add new transactions. Yesterday the repo got updated and the issue should be fixed, though I noticed that hassio-addons got their updates right before that release. Is there a possibility to update this one before next update round?

Than you so much for this amazing project!

**Describe alternatives you've considered**

**Additional context**

**Comment by alexbelgium** [comment]
Done! Thanks for raising it :)

**Comment by MiroVerleysen** [comment]
Hero! Can confirm it is working now.
