### ISSUE TITLE
❓ [addon] Continous writes on database.sqlite

### ISSUE THREAD

**Issue by agners** [alexbelgium/hassio-addons#1440]
I've noticed that this add-on continuously writes an SQLite database, even when idle:

```
root@db21ed7f-joplin:/home/joplin/packages/server# ls -lah /config/addons_config/joplin/ && date
total 540K
drwxrwxrwx 3 joplin joplin 4.0K May 16 02:14 .
drwxr-xr-x 3 root   root   4.0K May 16 00:24 ..
-rwxrwxrwx 1 joplin joplin  642 May 16 00:24 config.yaml
-rwxrwxrwx 1 joplin joplin 524K May 16 02:14 database.sqlite
drwxrwxrwx 2 joplin joplin 4.0K May 16 00:24 resources
Thu May 16 02:14:49 PDT 2024
```

This can cause high wear on eMMC, a user has seen evaluated eMMC wear which likely attributes to this add-on.

Is this expected behavior?

**Comment by alexbelgium** [comment]
Hi, my addon is only a front for joplin's image here https://hub.docker.com/r/florider89/joplin-server ; you would probably have more chance to contact the author here https://github.com/laurent22/joplin

I don't think I can help on the addon point of view
