### ISSUE TITLE
❓ [changedetection.io] Set up browserless-chrome

### ISSUE THREAD

**Issue by zepmo** [alexbelgium/hassio-addons#1442]
Hello,

I have set up Changedetection.io and browser less chrome. Both work fine on their own. However I can’t figure out how to set up Changedetection.io, that it accesses the browser less addon to use the visual selection filter. 

I’m aware that the set up needs to be done within the config.yaml file but I couldn’t find documentation for my specific case. 

Any help is greatly appreciated! 

 System: Home Assistant OS 12.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.5.5
 Home Assistant Supervisor: 2024.06.0

Best regards

**Comment by dgtlmoon** [comment]
Always for reference check our default config https://github.com/dgtlmoon/changedetection.io/blob/master/docker-compose.yml in there you can see which services are needed and which 'environment' configs are needed
