### ISSUE TITLE
@alexbelgium I'm not sure if this is the right place to ask, but it feels like it might be. I followed these two YouTube videos ([Vid-1](https://www.youtube.com/watch?v=CHvBzX41-Ag) and [Vid-2](https://www.youtube.com/watch?v=NHQ5KJf0IiE)) to set up my external hard drive as a mount and Nextcloud. It worked until about two or three weeks ago. When the power goes out and comes back, my Home Assistant system won't start. I think it's stuck because Nextcloud can't start on time, which prevents Home Assistant from booting up. To fix this, I have to remove the hard drive from the thin client, start Home Assistant, reconnect the USB, and restart Nextcloud. This process is too time-consuming and power outages are common here. Any help or workaround would be greatly appreciated.

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#1443]
@alexbelgium I'm not sure if this is the right place to ask, but it feels like it might be. I followed these two YouTube videos ([Vid-1](https://www.youtube.com/watch?v=CHvBzX41-Ag) and [Vid-2](https://www.youtube.com/watch?v=NHQ5KJf0IiE)) to set up my external hard drive as a mount and Nextcloud. It worked until about two or three weeks ago. When the power goes out and comes back, my Home Assistant system won't start. I think it's stuck because Nextcloud can't start on time, which prevents Home Assistant from booting up. To fix this, I have to remove the hard drive from the thin client, start Home Assistant, reconnect the USB, and restart Nextcloud. This process is too time-consuming and power outages are common here. Any help or workaround would be greatly appreciated.
I'm using:
OS Version: Home Assistant OS 12.3
Home Assistant Core: 2024.6.3
Nextcloud: Current version 29.0.2-2

It just stuck here for long:
Updating permissions...
... Config directory : /data
... data directory detected : /media/NEXTCLOUD/nextcloud
... setting permissions

_Originally posted by @iGaneshKumar in https://github.com/alexbelgium/hassio-addons/issues/1429#issuecomment-2175547769_

**Comment by alexbelgium** [comment]
Mmh sorry you're not using my own hdd mount system so not sure how I can really help... I have my own system to mount hdd drives where you put in the localdisk the disk name (physical such as "sda1" or label sur as "NAS") and then it mounts it to /mnt/sda1 or /mnt/NAS.

What it is doing is going at this stage is go through all your Nextcloud files and adapt permissions, so it can be normal that it takes so long ?

On the other hand if the issue is "only" that Nextcloud start too fast ; you could therefore disable the start at boot and create an automation instead ?

**Comment by alexbelgium** [comment]
The addon is already configured to start after boot so I can't do anything from my side

**Comment by alexbelgium** [comment]
Hi, here is a very simple one https://github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-mounting-drives

**Comment by iGaneshKumar** [comment]
This can be closed. I'll address it when I have time. For now, I've set up an automation. Thanks for your help!
