### ISSUE TITLE
🐛 [Birdnet-go] Queue is full!

### ISSUE THREAD

**Issue by thor0215** [alexbelgium/hassio-addons#1449]
### Description

My setup has a rstp audio source and after an hour or so now, the addon logs will show "2024/06/24 10:30:49 Queue is full!"  I searched the Birdnet-go source code and I wasn't able to find where that message would even be coming from.  Not sure how to easily reproduce this, but if I could figure out where the queue is, then I could clear it.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
2024/06/24 10:30:18 Queue is full!
2024/06/24 10:30:19 Queue is full!
2024/06/24 10:30:21 Queue is full!
2024/06/24 10:30:22 Queue is full!
2024/06/24 10:30:24 Queue is full!
2024/06/24 10:30:25 Queue is full!
2024/06/24 10:30:27 Queue is full!
2024/06/24 10:30:28 Queue is full!
2024/06/24 10:30:30 Queue is full!
2024/06/24 10:30:31 Queue is full!
2024/06/24 10:30:33 Queue is full!
2024/06/24 10:30:34 Queue is full!
2024/06/24 10:30:36 Queue is full!
2024/06/24 10:30:37 Queue is full!
2024/06/24 10:30:39 Queue is full!
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi sorry I know much better birdnet-pi and won't be able to help much with the app itself, you should ask on https://github.com/tphakala/birdnet-go how a full queue can be solved

**Comment by thor0215** [comment]
tphakala issued a possible fix in the 
https://github.com/tphakala/birdnet-go/pull/232

**Comment by thor0215** [comment]
Could you make just a couple of modifications to your addon?  I think this issue is related to birdnet-go connecting to the local mqtt addon broker.

In addon config.json file could you add "mqtt:wants" to the services section.
```
  "services": [
    "mysql:want",
    "mqtt:want"
  ],

```

Then similar to your 33-mariadb.sh file, could you add a 33-mqtt.sh file to post mqtt addon info if the addon exists:
```
#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
set -e

# Gives mqtt information

if bashio::services.available 'mqtt'; then
    bashio::log.green "---"
    bashio::log.yellow "MQTT addon is active on your system! Add the MQTT details below to the Birdnet-go config.yaml :"
    bashio::log.blue "MQTT user : $(bashio::services "mqtt" "username")"
    bashio::log.blue "MQTT password : $(bashio::services "mqtt" "password")"
    bashio::log.blue "MQTT broker : tcp://$(bashio::services "mqtt" "host"):$(bashio::services "mqtt" "port")"
    bashio::log.green "---"
fi
```

**Comment by alexbelgium** [comment]
Hi please create a PR and I'll merge it ! thanks for having seen that

**Comment by thor0215** [comment]
I created the pull request. Hopefully I did everything right.

**Comment by alexbelgium** [comment]
Thanks!
