### ISSUE TITLE
[Signal-K addon for Hassio] - Unable to expose additional ports required for signal k

### ISSUE THREAD

**Issue by tingles2233** [alexbelgium/hassio-addons#1456]
### Description

Hello, 

Trying to open up additional data connections to allow data to feed into Signal K addon. 

However I believe home assistant is blocking it at the addon level as the port is a custom port. 

Can we add a field(s) on the home assistant configuration where we configure the other default ports to add a few custom ports?

For example I am trying to open 1459/udp at this point in time. 

Thanks!

### Reproduction steps

```bash
Port show as not open due to Hass blocking it before it gets to the addon.
```

### Addon Logs

```bash
No logs as it is port closed.
```

**Comment by tingles2233** [comment]
Agreed, I would only expose select ports. 

Can we setup 3 custom ports with defaults being the following:

Named Custom 1/2/3: Perhaps starting at 1458udp/1459tcp/1460udp 

Have them setup on the page the same way and they can always be changed to use the end user for which ports they want. 

Is it possible to put a toggle there to enable or disable them?

**Comment by alexbelgium** [comment]
Hi, they will be added but disabled by default. You'll need to allocate manually a port in the add-on options for them to work

**Comment by tingles2233** [comment]
Just wanted to add thanks and it works as expected!

**Comment by alexbelgium** [comment]
Thanks for the feedback! Enjoy!
