### ISSUE TITLE
❓ [Birdnet-Go] WorkingDirectory for Birdnet-GO

### ISSUE THREAD

**Issue by thor0215** [alexbelgium/hassio-addons#1457]
**Birdnet-Go?**

name: Working Directory for Birdnet-Go
about: Suggest an idea for this project

I want to push a change so that the Birdnet-Go working directory is the addon_config folder for the addon.  It's a simple modification to the 99-run.sh, but is there a reason that the working directory is /data.  If not let me know and I'll propose the code change.

Birdnet-Go places everything in the working directory by default unless you change all those paths in the Birdnet-Go config.yaml file. Changing this will allow all Birdnet-Go related files to be put in the addon_config folder automatically.

**Comment by thor0215** [comment]
Code change would be
```
mkdir -p /root/.config/birdnet-go # Make config directory if it does not exist
cd /root/.config/birdnet-go # Change to that directory so birdnet-go uses it as the working directory
/usr/bin/birdnet-go $COMMAND & true
```

**Comment by alexbelgium** [comment]
Hi, I can do better and have it as a custom option location I'll look at it thanks for the proposal and the code

**Comment by alexbelgium** [comment]
Hi, version 5.5.5-5 should be good

**Comment by ghisch** [comment]
Hey 👋  0.5.5-5 gives me the following error:

```
[22:18:39] INFO: Starting app...
2024/07/02 22:18:39 Error loading settings: error initializing viper: fatal error reading config file: While parsing config: yaml: line 25: did not find expected key
```

**Comment by alexbelgium** [comment]
Thanks could you please post the section starting at line 25? Probably an issue with indentation, that's already what I changed between -4 and -5

**Comment by thor0215** [comment]
Here's a screenshot of my config.yaml
[image: image.png]

**Comment by ghisch** [comment]
Indeed this is an indentation issue. The log says line 25, but it's without comment and without blank line. For me it was line 30:
```yaml
realtime:
    audioexport:
    path: /config/clips
``` 
Path must be in realtime.audioexport.
Same issue for output.sqlite.path.

Fixing the indent directly in the file can't work as restarting the addon reset the config file with the wrong indents.

**Comment by thor0215** [comment]
I never had a chance to test your newest version with the bug, so once you
fix this, I can test it out.

**Comment by alexbelgium** [comment]
So two additional blanks, I'll push now thanks

**Comment by alexbelgium** [comment]
All good now I can close it?

**Comment by thor0215** [comment]
Go ahead and close it. I'm on vacation and will test it next week. If
there's still a problem I'll let you know.

**Comment by alexbelgium** [comment]
Let's do that! And happy holidays
