### ISSUE TITLE
Cant upload files more then 100MB using Nextcloud iOS

### ISSUE THREAD

**Issue by poudenes** [alexbelgium/hassio-addons#146]
Hi ALl,

I don't know when this error came in. But I cant upload files from iOS bigger then 100MB.
Now I change the chunk size to 50MB so it will upload in parts... Takes more time and the app must be active.

I restarted nextcloud add-on already but that didn't solve the issue

**Comment by alexbelgium** [comment]
Hi, probably an ios issue, you should raise it to the app dev. I've uploaded 3.7 go last week from desktop without issue in a single file so there is no issue with the addon, or accepts an upload up to 10go

**Comment by alexbelgium** [comment]
I'll close the issue as not related to the addon itself
