### ISSUE TITLE
[seafile] Cant log in

### ISSUE THREAD

**Issue by arievanoosten** [alexbelgium/hassio-addons#1463]
Hi,

I am unable to log in to seafile. If I use the standard config I can go to the login page but it keeps saying that the login details are not correct. I use me@example.com with a_very_secret_password. At some point in the past I installed this addon but uninstalled it again. could that have something to do with it?

**Comment by alexbelgium** [comment]
Hi, you can use my filebrowser add-on and delete the folder /homeassistant/addons_config/seafile to remove previous traces

**Comment by arievanoosten** [comment]
thanks that was the solution

**Comment by alexbelgium** [comment]
Thanks for reporting
