### ISSUE TITLE
🐛 [birdnet-pi] mqtt add

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#1464]
### Description

Add

### Reproduction steps

```bash
Add mqtt
```

### Addon Logs

```bash
Mqtt add-on
```

### Architecture

aarch64

### OS

HAos

**Comment by TheRealFalseReality** [comment]
Thanks for your upkeep on this addon, saves me from having to dig out my spare RPi3B+ with worse performance... I'm currently using the notification setup for MQTT in birdNET-Pi settings, `mqtt://mosquitto:XXXXXX@192.168.XX.XX:1883/birdnet/sightings` and have a rest sensor to parse the payloads. All is well. I just noticed you enabled MQTT discovery in the newest updates. How does that work? Would like to auto-discover sensors via MQTT if that is a better option but don't see anything in the new update, unless you disabled it in `-64` to fix the errors introduced in `-62` and `-63`

**Comment by alexbelgium** [comment]
Mqtt discovery is disabled in the latest version but was not super mature either ;) the idea was that it would publish automatically to the birdnet handle in the same manner as birdnet go, to make it easier for non experts and so that the exact same card template can be used. It will be for the future however ;)

**Comment by alexbelgium** [comment]
The script seems to be working I'll add it in the next update

**Comment by alexbelgium** [comment]
> Thanks for your upkeep on this addon, saves me from having to dig out my spare RPi3B+ with worse performance... I'm currently using the notification setup for MQTT in birdNET-Pi settings, `mqtt://mosquitto:XXXXXX@192.168.XX.XX:1883/birdnet/sightings` and have a rest sensor to parse the payloads. All is well. I just noticed you enabled MQTT discovery in the newest updates. How does that work? Would like to auto-discover sensors via MQTT if that is a better option but don't see anything in the new update, unless you disabled it in `-64` to fix the errors introduced in `-62` and `-63`

Would you have the opportunity to test it in -65 ? Thanks very much!

**Comment by alexbelgium** [comment]
mmh not working yet, not sure why

**Comment by TheRealFalseReality** [comment]
MQTT is just weird, I am only now beginning to understand how it works. I'll take a look this evening!

**Comment by alexbelgium** [comment]
Script works but it seems not to post anything and uses more cpu

**Comment by TheRealFalseReality** [comment]
Updated last night, haven't notice much CPU spike, but I also don't see any new MQTT messages.

**Comment by alexbelgium** [comment]
I've updated the code, and tested on my system. I've aligned the published codes with the ones from homeassistant community forum but of course I can change that ;-) https://community.home-assistant.io/t/displaying-birdnet-go-detections/713611/22
