### ISSUE TITLE
🐛 [BirdNet-Pi] <PulseAudio failing>

### ISSUE THREAD

**Issue by dumbledorethor** [alexbelgium/hassio-addons#1468]
### Description

Seems to be an issue with the mic audio driver

### Reproduction steps

```bash
1. Start BirdNet-Pi addon
2. all errors happen during booting
3. Some of the services do not successfully start
```

### Addon Logs

```bash
log from web terminal:
db21ed7f-birdnet-pi login: pi
Password:
Linux db21ed7f-birdnet-pi 6.6.31-haos-raspi #1 SMP PREEMPT Tue Jun 18 15:12:01 UTC 2024 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
$ alsamixer
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

cannot open mixer: Connection refused


Log from Addon:
+ for i in {1..5}
+ systemctl is-active --quiet birdnet_analysis.service
+ logger '[/home/pi/BirdNET-Pi/scripts/restart_services.sh] birdnet_analysis.service is running'
+ break
... starting livestream

  You can now view your Streamlit app in your browser.

  URL: http://localhost:8501/stats

... using gotty-aarch64 in phpsysinfo
 
 
Starting the upstream container
 
[custom-init] Service files found in /custom-services.d
[custom-init] 00-php_pfm.sh: service detected, copying...
[custom-init] 00-php_pfm.sh: copied
[custom-init] 01-avahi.sh: service detected, copying...
[custom-init] 01-avahi.sh: copied
[custom-init] 02-caddy.sh: service detected, copying...
[custom-init] 02-caddy.sh: copied
[custom-init] 02-nginx.sh: service detected, copying...
[custom-init] 02-nginx.sh: copied
[custom-init] 30-monitoring.sh: service detected, copying...
[custom-init] 30-monitoring.sh: copied
[migrations] started
[migrations] no migrations found
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

[alsa @ 0x55a96e39e0] cannot open audio device default (Connection refused)
default: Input/output error
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────
[custom-init] No custom files found, skipping...
Starting service: php pfm
Starting service: throttlerecording
Starting service: nginx
Starting service: avahi daemon
Found user 'avahi' (UID 104) and group 'avahi' (GID 106).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
Loading service file /etc/avahi/services/http.service.
Joining mDNS multicast group on interface eth0.IPv4 with address 172.30.33.28.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv6 with address ::1.
New relevant interface lo.IPv6 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.30.33.28 on eth0.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
[ls.io-init] done.
Server startup complete. Host name is db21ed7f-birdnet-pi.local. Local service cookie is 3989626392.
Service "BirdNET-Pi db21ed7f-birdnet-pi" (/etc/avahi/services/http.service) successfully established.
Starting service: caddy
{"level":"info","ts":1720286084.6549642,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
{"level":"info","ts":1720286084.6654055,"msg":"adapted config to JSON","adapter":"caddyfile"}
{"level":"info","ts":1720286084.6802664,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1720286084.6810133,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x400050b600"}
{"level":"info","ts":1720286084.701731,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1720286084.703917,"logger":"http.log","msg":"server running","name":"srv1","protocols":["h1","h2","h3"]}
{"level":"info","ts":1720286084.7043908,"logger":"http.log","msg":"server running","name":"srv2","protocols":["h1","h2","h3"]}
{"level":"info","ts":1720286084.7092664,"msg":"autosaved config (load with --resume flag)","file":"/home/pi/.config/caddy/autosave.json"}
{"level":"info","ts":1720286084.7102585,"msg":"serving initial configuration"}
{"level":"info","ts":1720286084.7181191,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/home/pi/.local/share/caddy"}
{"level":"info","ts":1720286084.719227,"logger":"tls","msg":"finished cleaning storage units"}
[birdnet_analysis][ERROR] no more notifications: restarting...
[birdnet_analysis][INFO] handle_reporting_queue done
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

arecord: main:831: audio open error: Connection refused
Starting service: throttlerecording
Starting service: throttlerecording
Starting service: throttlerecording
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, thanks I don't understand as I specifically remove pulseaudio start from the startup... What happens before that in the add-on log? Is it a new error that was not there previously?

**Comment by alexbelgium** [comment]
Ah no OK I have an idea. And `sudo alsamixer`?

**Comment by dumbledorethor** [comment]
yes it seem to happen recently with the updates and here is the log:
-----------------------------------------------------------
 Add-on: BirdNET-pi
 realtime acoustic bird classification system
-----------------------------------------------------------
 Add-on version: 0.13-62
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2024.7.1
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
BIRDSONGS_FOLDER='/media/MediaHDD/BirdSongs'
LIVESTREAM_BOOT_ENABLED='true'
TZ='America/Chicago'
certfile='fullchain.pem'
keyfile='privkey.pem'
pi_password='$4Nikolas'
ssl='false'
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory


Load environment variables from /config/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /addon_configs/db21ed7f-birdnet-pi/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /addon_configs/db21ed7f-birdnet-pi/birdnet-pi.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/01-structure.sh: executing
 
[12:24:46] INFO: Ensuring the file structure is correct :
... creating default files

... BIRDSONGS_FOLDER set to /media/MediaHDD/BirdSongs
... creating default folders ; it is highly recommended to store those on a ssd
... tmpfs detected, using it for StreamData and Processed to reduce disk wear
... set permissions to user pi
... creating symlink
... creating symlink for /media/MediaHDD/BirdSongs/By_Date
... creating symlink for /media/MediaHDD/BirdSongs/Charts
... check permissions
 
/etc/cont-init.d/02-restorestreamdata.sh: executing
[12:25:57] WARNING: Container was stopped while files were still being analysed, restoring them
copied '/data/StreamData/2024-07-05-birdnet-08:50:36.wav.json' -> '/home/pi/BirdSongs/StreamData/2024-07-05-birdnet-08:50:36.wav.json'
removed '/data/StreamData/2024-07-05-birdnet-08:50:36.wav.json'
copied '/data/StreamData/analyzing_now.txt' -> '/home/pi/BirdSongs/StreamData/analyzing_now.txt'
removed '/data/StreamData/analyzing_now.txt'
copied '/data/StreamData/spectrogram.png' -> '/home/pi/BirdSongs/StreamData/spectrogram.png'
removed '/data/StreamData/spectrogram.png'
... done

/etc/cont-init.d/31-checks.sh: executing
 
[12:25:57] INFO: Checking your birndet.conf file integrity
 
/etc/cont-init.d/33-mqtt.sh: executing
/etc/cont-init.d/71-newfeatures.sh: executing
 
[12:25:57] INFO: Adding optional features
 
/etc/cont-init.d/81-modifications.sh: executing
 
[12:25:57] INFO: Adapting webui
... removing System Controls from webui as should be used from HA
... removing Ram drive from webui as it is handled from HA
... correct services to start as pi
... remove embedded pulseaudio
... send services log to container logs
... avoid preselecting options in include and exclude lists
... show container logs in /logs
... caddyfile modifications
... correcting webui paths
 
/etc/cont-init.d/91-nginx_ingress.sh: executing
 
[12:25:58] INFO: Adapting for ingress
... setting up nginx
... ensuring restricted area access
... adapt Caddyfile for ingress
 
/etc/cont-init.d/92-ssl.sh: executing
 
/etc/cont-init.d/99-run.sh: executing
 
[12:25:58] INFO: Setting password for the user pi
... done
 
[12:25:58] INFO: Starting system services
... setting timezone to America/Chicago
... correcting systemctl
... correcting datetimectl
... adapting labels according to birdnet.conf file to en
Archive:  /home/pi/BirdNET-Pi/model/labels_nm.zip
  inflating: /home/pi/BirdNET-Pi/model/labels_en.txt  
Archive:  /home/pi/BirdNET-Pi/model/labels_nm.zip
  inflating: /home/pi/BirdNET-Pi/model/labels_en.txt  
... starting cron
... starting dbus
Starting system message bus: dbus.

[12:25:59] INFO: Starting BirdNET-Pi services
+ my_dir=/home/pi/BirdNET-Pi/scripts
+ sudo systemctl stop birdnet_recording.service
+ services=(chart_viewer.service spectrogram_viewer.service icecast2.service birdnet_recording.service birdnet_analysis.service birdnet_log.service birdnet_stats.service)
+ for i in "${services[@]}"
+ sudo systemctl restart chart_viewer.service
+ for i in "${services[@]}"
+ sudo systemctl restart spectrogram_viewer.service
Setting up watches.
Watches established.
+ for i in "${services[@]}"
+ sudo systemctl restart icecast2.service
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_recording.service
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
Failed to create secure directory (/home/pi/.config/pulse): Permission denied
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

arecord: main:831: audio open error: Connection refused
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_analysis.service
[server][INFO] LOADING TF LITE MODEL...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[server][INFO] LOADING DONE!
[birdnet_analysis][INFO] backlog is 0
[birdnet_analysis][INFO] backlog done
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_log.service

**Comment by dumbledorethor** [comment]
sudo alsamixer pulled up the microphone

**Comment by TheRealFalseReality** [comment]
I get the same error when updating to both versions, `0.13-62` and `0.13-63`. Reverting back to previous version `0.13-61` fixes the issue.

**Comment by alexbelgium** [comment]
Thanks very much I'll check what he's changed

**Comment by alexbelgium** [comment]
I've disabled the two new additions (mqtt publish and check that volume is not zero) please let me know how that goes 

https://github.com/alexbelgium/hassio-addons/commit/586bb1d1b206fa0ff0cbb1bef61e560fcbbd0f45

**Comment by dumbledorethor** [comment]
I am not able to update 
![14207AE7-6E9B-4857-B372-75FFBED7920F](https://github.com/alexbelgium/hassio-addons/assets/159749612/161496e9-219f-4909-bf05-4219494d39af)

**Comment by alexbelgium** [comment]
It just means it was still building, it's good now

**Comment by dumbledorethor** [comment]
It is back working again.  Thank you for all your hard work on these Addons!
