### ISSUE TITLE
Addons updater

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#147]
It worked!
![afbeelding](https://user-images.githubusercontent.com/3063928/148069748-bd7f1e7f-62fa-4faa-a4db-f63ffe026e9e.png)
awesome addon great thinking! If you want I can still offer my server to have the script running (its a oracle cloud instance) if that free's up your pi if needed.
What I was wondering, is it possible to show the name of the addon? Like:
`Updated Jacket to 0.5.0`
For example

**Comment by alexbelgium** [comment]
Thanks for the proposal but it runs with minimum resources and i prefer to keep full control on automatic commits, especially since it uses my personal github API. Good idea, I'll modify the script code to show the addon name.
