### ISSUE TITLE
❓ [changedetection.io] fails after updating to 0.45.25

### ISSUE THREAD

**Issue by RhysMcW** [alexbelgium/hassio-addons#1470]
**changedetection.io?**

**Addon**

I was running v0.45.24 and upgraded to 0.45.25 Sunday evening but after the update it does not seem to start correctly, no web UI available.
I get the following at the end of the addon log
*Starting the upstream container
 
[migrations] started
[migrations] no migrations found
/etc/s6-overlay/s6-rc.d/init-adduser/run: line 10: LSIO_READ_ONLY_FS: unbound variable
s6-rc: warning: unable to start service init-adduser: command exited 1*

I have restored 0.45.24 from the HA backup and it works again, web UI available and functional.
I then re-updated to 045.25 and get the same issue as above again.
I do however see port 5000 listening on my HA, but not able to connect to port 5000 (tried simple telnet to port 5000 from a separate machine), getting a "connection refused".
also from the HA box itself (telnet not available so used ssh to test the connection)
*~ # ssh -p 5000 db21ed7f-changedetection.io.local.hass.io
ssh: connect to host db21ed7f-changedetection.io.local.hass.io port 5000: Connection refused*

I installed Portainer to try have a look around, not that I really know what to look for, and it seems to show that the addon_db21ed7f_changedetection.io" is running, and found the same log as seen from the HA addon log.

![0 45 25 portainer](https://github.com/alexbelgium/hassio-addons/assets/14996001/c5b3432a-f5cc-4457-a063-eac775676e30)

here is the full log from when doing a restart of the addon
*Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Changedetection.io
 web page monitoring, notification and change detection
-----------------------------------------------------------
 Add-on version: 0.45.25
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.7.1
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
PGID='0'
PUID='0'
TIMEOUT='60000'
TZ='Africa/Johannesburg'
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/addons_config/changedetection.io/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/changedetection.io/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables

FETCH_WORKERS='2'
WEBDRIVER_URL='http://db21ed7f-browserless-chrome.local.hass.io:3000'
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/changedetection.io/changedetection.io.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/21-folders.sh: executing
 
Starting the upstream container
 
[migrations] started
[migrations] no migrations found
/etc/s6-overlay/s6-rc.d/init-adduser/run: line 10: LSIO_READ_ONLY_FS: unbound variable
s6-rc: warning: unable to start service init-adduser: command exited 1*

any ideas?

**Comment by alexbelgium** [comment]
Hi, thanks I corrected the other add-ons but not that one. I'll do it now

**Comment by RhysMcW** [comment]
thank you, 0.45.25-2 all good again...
