### ISSUE TITLE
❓[Changedetection.io] [Browserless Chromium] how to connect both?

### ISSUE THREAD

**Issue by aebgit** [alexbelgium/hassio-addons#1471]
❓ [Changedetection.io] [Browserless Chromium] how to connect both?

https://github.com/alexbelgium/hassio-addons/issues/new/choose

**Which addon?**

[Changedetection.io] and [Browserless Chromium] 

name: Documentation
about: to describe clearly how both AddOns shall be configured to work together on Home Assistant OS.
title: ''
labels: ''
assignees: ''

---

**Which addon?**

[Changedetection.io] and [Browserless Chromium] 

**Addon or app?**

I _assume_ there are specific settings required when running both AddOns in Homeassistant OS. At least I was unsuccessful configuring both with the information I could find in both the original projects as well as in the docs for the AddOns and the Wiki.

**Describe the solution you'd like**

A precise (step-by-step) guide on how to configure both AddOns after they are installed on Homeassistant **OS** in order to work together. 

**Describe alternatives you've considered**

I'm stuck with the configuration after having installed both AddOns in Homeassistant OS. 
Both AddOns start successful, however the configuration is unclear. Maybe there is even something obvious I miss.

## Browserless Chromium
- AddOn installed from the repo and successfully started
- access to `http://xxx.xxx.xxx.68:3000/docs` works. I can access the help-pages. (the IP is the LAN IP of my Homeassistant installation)

## Changedetection.io
- AddOn installed from the repo 
- AddOn configuration in HomeAssistant OS, section Options:
```
PGID: 0
PUID: 0
TIMEOUT: "60000"
BASE_URL: http://xxx.xxx.xxx.68:5000/
```
(the IP in the BASE_URL is the LAN IP of my Homeassistant installation, same I used to test access to Browserless Chromium before)
- AddOn started successfully. I can access Changedetection via `http://xxx.xxx.xxx.68:5000/`
- Configured some websites using fetch-method "Basic fast Plaintext"; fetching works and I get eMail notifications for diffs.
- However, I fail to configure use of Browserless Chromium. Here is what I did so far:
- Configured `/homeassistant/addons_config/changedetection.io/config.yaml` to include: `WEBDRIVER_URL: http://xxx.xxx.xxx.68:3000/webdriver`
- Configured a website with method "WebDriver Chrome/Javascript via 'http://xxx.xxx.xxx.68:3000/webdriver'"
- whenever the fetcher runs, it finishes in the changedetection web-frontend with "Exception: Message: Not Found"
- the events from the AddOn log are below:
```
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /api/checknow?uuid=a77b6d95-dbe8-443a-849f-ad895aa5e0ec HTTP/1.1" 302 655 0.008621
2024-07-08 20:13:07.393 | INFO     | changedetectionio.update_worker:run:256 - Processing watch UUID a77b6d95-dbe8-443a-849f-ad895aa5e0ec Priority 1 URL https://changedetection.io/CHANGELOG.txt
2024-07-08 20:13:07.403 | ERROR    | changedetectionio.update_worker:run:469 - Exception reached processing watch UUID: a77b6d95-dbe8-443a-849f-ad895aa5e0ec
2024-07-08 20:13:07.405 | ERROR    | changedetectionio.update_worker:run:470 - Message: Not Found
2024-07-08 20:13:07.407 | DEBUG    | changedetectionio.update_worker:run:562 - Watch a77b6d95-dbe8-443a-849f-ad895aa5e0ec done in 0.01s
2024-07-08 20:13:07.434 | DEBUG    | changedetectionio.model.Watch:history:219 - Reading watch history index for 9b145520-5cbc-4d2a-a496-3f54204e951c
2024-07-08 20:13:07.437 | DEBUG    | changedetectionio.model.Watch:history:219 - Reading watch history index for eebc3a7a-6e90-4287-9af4-4611255a269b
2024-07-08 20:13:07.441 | DEBUG    | changedetectionio.model.Watch:history:219 - Reading watch history index for 79cfd2d1-3608-4a11-a588-ce8a95f878a9
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET / HTTP/1.1" [200 9572 0.040069](tel:200 9572 0.040069)
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/styles/pure-min.css HTTP/1.1" [200 4219 0.008617](tel:200 4219 0.008617)
(414) accepted ('xxx.xxx.xxx.53', 55647)
(414) accepted ('xxx.xxx.xxx.53', 55648)
(414) accepted ('xxx.xxx.xxx.53', 55649)
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/styles/styles.css?v=0.45.25 HTTP/1.1" [200 8454 0.008515](tel:200 8454 0.008515)
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/favicons/site.webmanifest HTTP/1.1" 304 347 0.003894
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/js/csrf.js HTTP/1.1" 304 338 0.004425
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/images/Google-Chrome-icon.png HTTP/1.1" 304 355 0.004688
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 636, in handle_one_response
    write(b'')
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 566, in write
    wfile.flush()
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 383, in send
    return self._send_loop(self.fd.send, data, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 370, in _send_loop
    return send_method(data, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/images/spread-white.svg HTTP/1.1" 304 0 0.006361
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/js/watch-overview.js HTTP/1.1" [200 1210 0.005553](tel:200 1210 0.005553)
(414) accepted ('xxx.xxx.xxx.53', 55650)
(414) accepted ('xxx.xxx.xxx.53', 55651)
(414) accepted ('xxx.xxx.xxx.53', 55652)
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 636, in handle_one_response
    write(b'')
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 566, in write
    wfile.flush()
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 383, in send
    return self._send_loop(self.fd.send, data, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 370, in _send_loop
    return send_method(data, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/images/bell-off.svg HTTP/1.1" 304 0 0.005794
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 636, in handle_one_response
    write(b'')
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 566, in write
    wfile.flush()
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 383, in send
    return self._send_loop(self.fd.send, data, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 370, in _send_loop
    return send_method(data, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/images/pause.svg HTTP/1.1" 304 0 0.005420
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/js/toggle-theme.js HTTP/1.1" [200 1144 0.004956](tel:200 1144 0.004956)
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/images/spread.svg HTTP/1.1" 304 340 0.003503
xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/images/Generic_Feed-icon.svg HTTP/1.1" 304 351 0.004766
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 636, in handle_one_response
    write(b'')
  File "/lsiopy/lib/python3.12/site-packages/eventlet/wsgi.py", line 566, in write
    wfile.flush()
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 383, in send
    return self._send_loop(self.fd.send, data, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/eventlet/greenio/base.py", line 370, in _send_loop
    return send_method(data, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

xxx.xxx.xxx.53 - - [08/Jul/2024 20:13:07] "GET /static/images/bell-off.svg HTTP/1.1" 304 0 0.006620
(414) accepted ('xxx.xxx.xxx.53', 55653)
```

Maybe i'm missing something obvious, I do not know. Any help is appreciated.

Thanks!

**Additional context**

This is specifically about using the AddOns in Homeassistant **OS**.

**Comment by RhysMcW** [comment]
I was having a similar issue, I initially then came across a forum post somewhere that had a line that looked worth trying
In HA use the File Editor addon and edit the Changedetection.io config.yaml
**/homeassistant/addons_config/changedetection.io/config.yaml**
I added the following line to the end of the file

`PLAYWRIGHT_DRIVER_URL: ws://db21ed7f-browserless-chrome.local.hass.io:3000/chromium?launch={"defaultViewport":{"height":720,"width":1280},"headless":false,"stealth":true}&blockAds=true`

and remember to add a blank line at the end of the file too - yaml nuance...
the "_db21ed7f-browserless-chrome.local.hass.io_" hostname I got from the CLI in HA, using arp, but you should also be able to use your HA IP address.
then restart the Changedetection.io addon - after that I was able to use the browser options in Changedetection.io - now have a few pages I'm monitoring and so far they look to be working but will see later as some of the pages required browser steps to click options to display the info I'm interested in.

**Comment by alexbelgium** [comment]
Thanks very much!!! I'll look to add your explanation to the Readme documentation

**Comment by aebgit** [comment]
Thanks to both of you!
I have removed my config from `/homeassistant/addons_config/changedetection.io/config.yaml` and included instead the suggestion from @RhysMcW. I confirm it is working now.

**Comment by ALenfant** [comment]
I had the same issue and I didn't know exactly how to set up the headless chrome hostname
FYI you can fetch it two different ways:
* Easiest: in the UI on the addon page:
![image](https://github.com/user-attachments/assets/a63514f6-027a-4361-a33f-0d8f87461279)

* You can also SSH to the server and run `docker exec -i hassio_dns cat "/config/hosts"`
You'll see a line similar to the following at some point:
`172.30.33.5 2937404c-browserless-chrome 2937404c-browserless-chrome.local.hass.io`
Use what's provided at the end of the line (`2937404c-browserless-chrome.local.hass.io`)

You can just provide `2937404c-browserless-chrome:3000`, no need for the `.local.hass.io` suffix

**Comment by FeikoJoosten** [comment]
Just want to point out, I had the browserless chrome addon running on a different port (3001), and that causes the changedetection.io addon to fail to make a proper connection. 

Yes, I did make sure the port in the config.yaml correctly specified 3001.
After changing the port back to 3000, all worked as intended.
