### ISSUE TITLE
🐛 [birdnet-pi] mqtt broker addon not used

### ISSUE THREAD

**Issue by frostworx** [alexbelgium/hassio-addons#1477]
### Description

Hey!
I still love that addon and even ordered a birdweather puc recently :)

I like your new idea with the mqtt autodetect implementation.
On my setup though the mqtt broker auto-detection doesn't seem to work.
I use emqx broker as addon, which might result in

`bashio::services.available 'mqtt'`

being empty/false and therefore it doesn't get activated.

I'd like to suggest the option to override mqtt settings with optional variables like

```
MQTT_HOST
MQTT_PORT
MQTT_USER
MQTT_PASSWORD
```
_(as fallback for the autodetection)_

and sed those into the helper script when not empty

```
    sed -i "s|%%mqtt_server%%|$MQTT_HOST|g" /helpers/birdnet_to_mqtt.py
    sed -i "s|%%mqtt_port%%|$MQTT_PORT|g" /helpers/birdnet_to_mqtt.py
    sed -i "s|%%mqtt_user%%|$MQTT_USER|g" /helpers/birdnet_to_mqtt.py
    sed -i "s|%%mqtt_pass%%|$MQTT_PASSWORD|g" /helpers/birdnet_to_mqtt.py
```

what do you think?

### Reproduction steps

```bash
1. use https://github.com/hassio-addons/addon-emqx as mqtt broker
2. don't disable mqtt by activating MQTT_DISABLED
3. mqtt broker is not contacted
```

### Addon Logs

```bash
not much to see in the logs, but
when seding mqtt variables into birdnet_to_mqtt.py manually and starting it afterwards, the emqx broker registers a connection
```

### Architecture

amd64

**Comment by alexbelgium** [comment]
Hi, it would be much easier if your broker addon for mqtt was published as a service - the owner should do that in the config.json of the addon

However indeed it's a good idea to have manual MQTT I'll add it now

**Comment by frostworx** [comment]
wow, you're fast! :)
thank you very much!

I'll open an issue on emqx side :)

**Comment by frostworx** [comment]
Thank you for the quick push!

you added the variable options as boolean though and not as string, so I can't test  -70 yet (manual yaml override not allowed :) )

**Comment by alexbelgium** [comment]
Went too fast, corrected :-)

**Comment by frostworx** [comment]
that looks good, I see a connection within emqx _(nothing in HA yet, but I guess I'll have to wait a bit)_

I do not use any authentication in mqtt and therefore left both user and password empty initially.
after having read your if condition I filled both with some dummy creds and it worked.

Thank you very much!

*closing here*

**Comment by alexbelgium** [comment]
Thanks i'll adapt to remove dependency on those

**Comment by frostworx** [comment]
Thanks a lot! :)

**Comment by frostworx** [comment]
sorry for the noise...

The mqtt connection to the broker works fine 
_(visible both in the broker and when manually running `/home/pi/BirdNET-Pi/birdnet/bin/python3 /usr/bin/birdnet_to_mqtt.py` -> `INFO:root:Connected to MQTT Broker!` loop)_

but nothing seems to be sent to the broker, i.e.

`print('Posted to MQTT : ok')`

is never reached.

would be great if you had I hint what I could test.
would this be supposed to work without any further configuration when using the [mosquitto broker addon](https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md)?

*reopening* because I'm not sure if you'd get a notifier when I leave it closed

**Comment by alexbelgium** [comment]
It worked for me with mosquito - i fear it is because it is trying to connect using the username and password and therefore fails. Have you removed those? Your mqtt add-on show a normal connection?

**Comment by alexbelgium** [comment]
You could try to manually remove the line starting with : `mqttc.username_pw_set` in /usr/bin/birdnet_to_mqtt.py

**Comment by frostworx** [comment]
thank you for trying to help!
yes, the addon shows a connection (it did already with the dummy credentials, but also does without)

when running the modified `birdnet_to_mqtt.py` I do see random `Posted to MQTT : ok` _(maybe no bird was detected previously?)_

but unfortunately I still can't see any data both in the broker and in HA.
on broker side the subscriptions topic part is empty, I guess that is the problem.

**Comment by frostworx** [comment]
I created a broker log and can confirm that data is correctly sent to the broker.

```
2024-07-14T19:46:56.496846+02:00 [MQTT] birdnet_mqtt@172.30.33.3:45455 msg: mqtt_packet_received, packet: PUBLISH(Q1, R0, D0, Topic=birdnet, PacketId=5, Payload={"Date": "2024-07-14", "Time": "19:46:40", "ScientificName": "Chloris chloris", "CommonName": "Gr\u00fcnfink", "Confidence": "0.7318", "SpeciesCode": "eurgre1", "ClipName": "Gr\u00fcnfink-73-2024-07-14-birdnet-RTSP_1-19:46:40", "url": "http://en.wikipedia.org/wiki/Chloris_chloris"})
2024-07-14T19:46:56.497001+02:00 [AUTHZ] birdnet_mqtt@172.30.33.3:45455 msg: authorization_module_nomatch, action: PUBLISH(Q1,R0), module: emqx_authz_client_info, topic: birdnet, username: undefined
2024-07-14T19:46:56.497068+02:00 [PUBLISH] birdnet_mqtt@172.30.33.3:45455 msg: publish_to, topic: birdnet, payload: {"Date": "2024-07-14", "Time": "19:46:40", "ScientificName": "Chloris chloris", "CommonName": "Gr\u00fcnfink", "Confidence": "0.7318", "SpeciesCode": "eurgre1", "ClipName": "Gr\u00fcnfink-73-2024-07-14-birdnet-RTSP_1-19:46:40", "url": "http://en.wikipedia.org/wiki/Chloris_chloris"}
2024-07-14T19:46:56.497131+02:00 [MQTT] birdnet_mqtt@172.30.33.3:45455 msg: mqtt_packet_sent, packet: PUBACK(Q0, R0, D0, PacketId=5, ReasonCode=16)
```

no idea why HA doesn't pick it up.
doesn't looks like a addon problem, so closing here again.

sorry for the noise

**Comment by alexbelgium** [comment]
Thanks for the feedback! Glad it works
