### ISSUE TITLE
Jackett: Wrong port for the WebUI

### ISSUE THREAD

**Issue by CharlieBailly** [alexbelgium/hassio-addons#148]
Hi, thanks for all your addons !
I installed Jackett a few days ago, everything was okay, but a recent update changed the web ui port from 9117 to 8889, as we can see in the logs below :
```
Now listening on: http://[::]:8889
Application started. Press Ctrl+C to shut down.
```
But inside the `config.json` file, it is still set to 9117.
I forked the repo and changed port from 9117 to 8889 in `config.json` and it is now working.
Maybe the best solution would be to make Jackett run on 9117 as it was before instead of changing the exposed port.

Thanks in advance.

I am running the latest version of Home Assistant OS on a Raspberry pi 4.

(Also, in the Readme file, there is a little mistake about the webui port : `Webui can be found at <your-ip>:7878.`)

**Comment by alexbelgium** [comment]
Hi,

I'm sorry but the port is still 9117. I've installed a clean instance and here is the log : 
```
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
```

Most probably you have changed the port from the Jackett ui... 
The easiest would be to restore a backup if you have!

Thanks for the readme, I'll update that

**Comment by CharlieBailly** [comment]
Hi,
I checked my config.json file in /config/Jackett and the port was still 9117.
But there was another config.json file in /config/addons_config/Jackett and here the port was not 9117, I deleted that one and it came back to 9117 after addon restart, so you were right I obviously messed up with the port but I really can't remember that.
Sorry for bothering you

**Comment by alexbelgium** [comment]
No problem, glad it worked!
