### ISSUE TITLE
🐛 [Whatsapper] Manifest unknown. Can't update or install.

### ISSUE THREAD

**Issue by Chaoscontrol** [alexbelgium/hassio-addons#1480]
### Description

I tried updating and  I got a weird error. So I decided to uninstall, and reinstall as it felt like a version issue. Trying to install from scratch returns this error. 

```
Can't install ghcr.io/alexbelgium/whatsapper-amd64:1.0: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=1.0&fromImage=ghcr.io%2Falexbelgium%2Fwhatsapper-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
```

### Reproduction steps

```bash
1. Try to install from HACS
2. See error
```

### Addon Logs

```bash
-
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Please retry in 30 min

**Comment by Chaoscontrol** [comment]
It worked now. Thanks!
