### ISSUE TITLE
🐛 [EMBY] BETA tag is enabled, should be stable?

### ISSUE THREAD

**Issue by brietman** [alexbelgium/hassio-addons#1485]
### Description

Looking at https://github.com/alexbelgium/hassio-addons/blob/master/emby/build.json

```
{
  "build_from": {
    "aarch64": "lscr.io/linuxserver/emby:arm64v8-beta",
    "amd64": "lscr.io/linuxserver/emby:amd64-beta",
    "armv7": "lscr.io/linuxserver/emby:arm32v7-4.8.0-beta"
  },
  "codenotary": {
    "signer": "alexandrep.github@gmail.com"
  }
}
```
the beta tag is used. I am not sure which tag can be used. But I think  "lscr.io/linuxserver/emby:amd64" or  "lscr.io/linuxserver/emby:amd64-latest" should be a better build option? Or make seperate addon for the beta version?

### Reproduction steps

```bash
Install addon.
```

### Addon Logs

```bash
not necessary
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, I'm not sure beta to normal is backward compatible and if it would lead to issues for users. However, I never saw any issue with their beta it is rock solid!
