### ISSUE TITLE
Nextcloud nginx gets hung up

### ISSUE THREAD

**Issue by zimmra** [alexbelgium/hassio-addons#149]
Nextcloud eventually hangs, becomes inaccessible, and floods the log with the following message:
```
nginx: [emerg] "ssl_certificate" directive is not allowed here in /data/config/nginx/site-confs/default:48
```
A restart of the addon resolves temporarily.

**Comment by alexbelgium** [comment]
Thanks I'll look at it

**Comment by alexbelgium** [comment]
I've pushed a new version, please let me know if it helps

**Comment by zimmra** [comment]
I'll keep an eye on and update you in the next day or so to see if it happened again, thanks.
