### ISSUE TITLE
🐛 [Codex] Codex v1.6.9 is should not be used.

### ISSUE THREAD

**Issue by ajslater** [alexbelgium/hassio-addons#1491]
### Description

Hi, it's AJ the author of Codex. 
Your configuration relies on Codex v1.6.9 but it was behaving badly on the network and i've removed it from dockerhub and pypi. I'd appreciate it if you would update your config to use [a more recent version](https://hub.docker.com/repository/docker/ajslater/codex).

### Reproduction steps

```bash
Looking at the config here:

https://github.com/alexbelgium/hassio-addons/blob/master/codex/config.json#L109
```

### Addon Logs

```bash
No logs. I've never run HA.
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks! Updated

**Comment by ajslater** [comment]
Thanks!
