### ISSUE TITLE
✨ [ChangeDetection.io] Any chance it's possible to automatically create a sidebar entry?

### ISSUE THREAD

**Issue by igorsantos07** [alexbelgium/hassio-addons#1492]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

ChangeDetection.io

### Is your feature request related to a problem? Please describe

This add-on (from the very few I have) is a bit odd to access - when you press "Open Web UI", it opens a new tab at the server URL, instead of opening it as an iframe of sorts inside the HA interface.

I understand it's because the add-on doesn't use Ingress to embed itself into HA - as, for instance, the official Grocy add-on does.

### Describe the solution you'd like

However, from _my_ point of view, Ingress would not be needed if it's complex to implement (although it would probably increase the add-on rating).

I have a  simpler suggestion, as I don't think a sidebar entry could be automatically created without Ingress: I can submit a small PR to its README explaining how to create a custom dashboard that embed the resulting interface onto HA via an iframe - Settings > Dashboards > Add Dashboard > Webpage.

![image](https://github.com/user-attachments/assets/67a5ad30-e1d8-4db5-aba8-895042c0e5e8)

Not sure if you think this could be useful on other add-ons.

**Comment by alexbelgium** [comment]
Hi, ingress is always tricky to implement... If you indeed proposed an iframe based solution in the Readme it would be gratefully appreciated!

**Comment by igorsantos07** [comment]
Good to know about ingress - I plan to make an add-on from the ground on my free time.... sometime in the next 50 years? :joy:
