### ISSUE TITLE
🐛 [Transmission NAS] Cannot move downloaded data to other CIFS directory

### ISSUE THREAD

**Issue by hiagocosta** [alexbelgium/hassio-addons#1494]
### Description

I have four shared folders on my NAS that is accessible to transmission user, and I'm using SMB/CIFS for sharing.
all the folders are accessible and configured inside the addon, via docker exec I can find the folders and the path is mounted correctly. but when I try to move to another folder when the torrent is downloading or downloaded, it cames to an error and not move any file. only creates some 0kb files on the destination.

### Reproduction steps

```bash
1. download a torrent
2. right click on the torrent go to set location, and choose another CIFS folder
3. if "move data" is NOT selected, it only creates a 0kb file
4. if "move data" is selected, the torrent came to an error: 

[Error text]
Couldn't move '/mnt/Transmission' to '/mnt/Filmes': Unable to copy: Unable to read/write: No such file or directory (2)
```

### Addon Logs

```bash
nothing is showed on the addon logs
```

### Architecture

amd64

### OS

HAos

**Comment by hiagocosta** [comment]
any news about that?

**Comment by alexbelgium** [comment]
Hi sorry I don't really see how to help as the cause could be the addon, the system, or tranmission itself... I'm using the qbittorrent addon and it automatically moves my files from one folder to another after download but I've never tried from one CIFS folder to another.

Perhaps you could use a script to do it instead? I think transmission can execute a script after the download is complete

Perhaps it would be easier if you downloaded to a single CIFS folder, but with subfolders below to manage "downloading" vs "downloaded" ?

**Comment by hiagocosta** [comment]
do you have github link for me to asking them about this issue? I believe it could be something about move one mounted folder to another. they are in the same Filesystem btw

**Comment by hiagocosta** [comment]
Hi Alex, I've changed my client to your version of qbittorrent that it fixed my demand, you can close this ticket.
thank you for all

**Comment by alexbelgium** [comment]
Thanks! sorry I didn't see any potential solution for your initial issue but qbittorrent is a great app too :-)
