### ISSUE TITLE
Nextcloud cannot download english OCR

### ISSUE THREAD

**Issue by zimmra** [alexbelgium/hassio-addons#150]
tesseract-ocr-data-eng is not an available apk package.

If eng is selected as the OCR language it messes up when it attempts to download tesseract-ocr-data-eng upon setup. 

I believe (but have not confirmed) that english is inherently included.

**Comment by alexbelgium** [comment]
Indeed, pretty sure of that. Does ocr still works even this error? You can just remove eng from the addon options of list of languages to install... Il remove it as default

**Comment by alexbelgium** [comment]
I've updated the ocr language download code also in the latest version. It should be more robust and conform to up-to-date standards

**Comment by alexbelgium** [comment]
I had introduced a bug in 23.0.0-8 and have pushed 23.0.0-9. It will avoid trying to download the eng language as it is default and will avoid the issue. I'll close this, thanks for reporting

**Comment by zimmra** [comment]
This is what I get now. Trying to leave the field blank causes it to default to fra
```
[cont-init.d] 99-ocr.sh: executing... 
/var/run/s6/etc/cont-init.d/99-ocr.sh: line 32: syntax error near unexpected token `fi'
[cont-init.d] 99-ocr.sh: exited 2.
```

**Comment by alexbelgium** [comment]
Thanks I pushed a 23.0.0-10 that solves it :)

**Comment by X1pheR** [comment]
I also had the error but fixed now indeed so can be closed.

**Comment by alexbelgium** [comment]
Perfect, thanks!
