### ISSUE TITLE
🐛 [Scrutiny] Memory leak since 0.8.1, april 8

### ISSUE THREAD

**Issue by chertvl** [alexbelgium/hassio-addons#1501]
### Description

If I'm not mistaken, after the last Scrutiny update on April 8, a memory leak appeared, which has been slowly but surely growing for months.

I'll attach screenshots that show when the memory started leaking, and that the process ```/usr/libexec/udisks2/udisksd``` takes up 4.0% of my 16 GB of memory for 40 days of HAOS uptime.
When HAOS is restarted, 1.5 GB of memory is occupied and this process is not visible at all in the top, and after a month and a half, it's already 2.8 GB and that procces at the top2. Unfortunately, restarting HA Core or restarting all my addons does not help to return the memory, only restarting the entire HAOS helps.

Alex, can you check if the problem exists on your side?

![image](https://github.com/user-attachments/assets/ef3c918c-8faa-43d0-839e-b3f79326c5fe)

![image](https://github.com/user-attachments/assets/b6191d3c-24e9-42f0-801d-918a6987887c)

HW:
Intel NUC10i3, HomeAssistantOS 12.4 

### Reproduction steps

```bash
1. Check used memory in SystemMonitor integration
2. Wait few weeks and check again, or show up history graph
3. You can check top10 process sorted by memory in Advanced SSH & Web Therminal by using command:

 run --privileged --rm -v /dev:/dev --pid host ubuntu:latest nsenter --target 1 --mount --uts --ipc --net --pid -- ps auxww --sort -pmem | head
```

### Addon Logs

```bash
I dont have any.
```

### Architecture

amd64

### OS

HAos

**Comment by andrewjswan** [comment]
+1 the some

**Comment by alexbelgium** [comment]
Mmh very good point thanks. Alas I restart my homeassistant by automation weekly, and sometimes a bit more manually so I don't have long term data to compare. The is no mention of memory leaks in the scrutiny github, but there is some for HAos https://community.home-assistant.io/t/memory-leak-how-to-find-whats-causing-it/611482

I'll try to build a new version just to see if this helps by using updated dependencies

**Comment by chertvl** [comment]
> I'll try to build a new version just to see if this helps by using updated dependencies

Thank you, hope it helps.
ps: its a little hard to monitor processes memory use by all methods, because leakage around 30-35mb/day, it takes huge time to see real difference

**Comment by alexbelgium** [comment]
Might be easy for me to say but implementing a nightly weekly restart might avoid some issues... That's what I'm doing as part of my weekly maintenance routine...

BTW have you tried `ha su repair`? I know that the supervisor has some leftovers (such as dangling images) that are greatly helped by a regular run of this command... I wouldn't see how that would affect memory usage but at least it should recover some space for you :)

**Comment by chertvl** [comment]
> Might be easy for me to say but implementing a nightly weekly restart might avoid some issues... That's what I'm doing as part of my weekly maintenance routine...
> 
> BTW have you tried `ha su repair`? I know that the supervisor has some leftovers (such as dangling images) that are greatly helped by a regular run of this command... I wouldn't see how that would affect memory usage but at least it should recover some space for you :)

Just updated to v0.8.1-4,  tried ```ha su repair```, will look in one week or so, will it growth... 
If nothing helps, I will implement host reboot every week, it will cause some another problems but I have ideas how to automate it. 

Thanks! I'll write in one week about results.

**Comment by chertvl** [comment]
![image](https://github.com/user-attachments/assets/38e5f062-55c9-4a55-a7b2-6a7547d6c2cf)
It seems the latest update didn't help.  ```ha su repair``` command also does not bring results. 
Well, I’ll have to implement the weekly OS reboot automation, apparently this is my last option.
Alex, thank you for your work and time!

Ps: if the reason of this behavior will identified in the future, fill free to reopen issue

**Comment by chertvl** [comment]
@alexbelgium 
I changed my ssd from NVMe to Sata2, and problem is gone ;)
Looks like it was something with SMART data caching/recording to db, according to nvme.

![image](https://github.com/user-attachments/assets/01fd5fad-c35f-477d-8765-0abd06d6b901)

**Comment by alexbelgium** [comment]
Thanks for reporting! This surely will be useful pt others too
