### ISSUE TITLE
🐛 [Firefly-III] Add-on update broken

### ISSUE THREAD

**Issue by GNeras** [alexbelgium/hassio-addons#1505]
### Description

I have version 6.1.18 installed. The update notes show a new version 6.1.19 but the add-on is trying to update to version "6.1.18-2test". Updating breaks the add-on, it does not start and the log remains empty.

### Reproduction steps

```bash
1. Have version 6.1.18 installed
2. Update the add-on
```

### Addon Logs

```bash
Empty
```

### Architecture

aarch64

### OS

HAos

**Comment by JWdeBokx** [comment]
I have the same problem.
On starting a dialog is displayed about missing ssl settings in the configuration

**Comment by alexbelgium** [comment]
Hi, thanks for reporting. Here is an update that should solve that

**Comment by GNeras** [comment]
Thank you. The add-on updated correctly to version 6.1.19 for me.

**Comment by JWdeBokx** [comment]
Hmm mine won't update...
@GNeras from witch version did you do the upgrade?
From the working version, or from the not starting version?

**Comment by GNeras** [comment]
@JWdeBokx I updated from a working version. I restored my backup of version 6.1.18 when the update broke and now I was able to update from 6.1.18 to 6.1.19.

**Comment by JWdeBokx** [comment]
@GNeras tried that, but no good update.
But now good looking, my running version is 6.1.13...
Don't know why it's not updated to 6.1.18...
@alexbelgium is it possible to upgrade first to 6.1.18?

**Comment by alexbelgium** [comment]
> @GNeras tried that, but no good update. But now good looking, my running version is 6.1.13... Don't know why it's not updated to 6.1.18... @alexbelgium is it possible to upgrade first to 6.1.18?

I can confirm that the image pulled from upstream is 6.1.19 and my version correctly updated to 6.1.19 as per the startup log... Perhaps you could ask on the upstream repo of firefly? As upgrade would be managed by his image and not the add-on...

**Comment by JWdeBokx** [comment]
@alexbelgium thank you for your great work!
I restored the backup again, now let it be for the night and this morning the updater showed 6.1.19!
The update worked, and is running again.
I have no idea how the update info works, so sometimes waiting a bit is better...

**Comment by alexbelgium** [comment]
Thanks ! All that stemmed from a failed attempt to implement ssl with nginx, but the image doesn't support php fastcgi so I had stopped in the middle. Thanks for your understanding and the confirmation that it now works!
