### ISSUE TITLE
🐛 [BirdNET-Pi] The Detection in the Overview is permanently refreshing

### ISSUE THREAD

**Issue by UlrichThiess** [alexbelgium/hassio-addons#1506]
### Description

The Detection in the Overview Tab is permanently refreshing.
Tested on macOS with Safari, Firefox and Chrome.
Tested via https directly in my LAN.

### Reproduction steps

```bash
Normal installation
```

### Addon Logs

```bash
no logs
```

### Architecture

amd64

### OS

HAos, Virtual Machine

**Comment by alexbelgium** [comment]
Isn't it the normal behavior? As it must show the latest birds detected?

**Comment by UlrichThiess** [comment]
Sorry, no. On my Raspberry it only refreshed if it has new detections. The HA Addon refreshes nearly every two seconds.

**Comment by alexbelgium** [comment]
I'll look at it thanks

**Comment by alexbelgium** [comment]
didn't find a reason yet - either it is from my nginx layer (so actionable) or HomeAssistant's ingress (so we'll have to just live with it). Actually even without finding the cause I couldn't find yet why it actually does refresh in the php of the page

**Comment by UlrichThiess** [comment]
refreshing has stopped since last version 0.13.88
tested with safari, chrome and firefox on macos
thanks again

**Comment by alexbelgium** [comment]
Ahah good to know but I don't think I changed anything :) well it's the mysteries of HA ;)
