### ISSUE TITLE
🐛 [Addon name] Can't update to 0.13-73

### ISSUE THREAD

**Issue by kongjudas** [alexbelgium/hassio-addons#1507]
### Description
 The last update went fine, but today I got this message on the latest version. It's probably to your interest..?
Thank a lot for this addon, btw. I'm a total nerd and this just ads on to my nerdiness.

Error:
` Can't install ghcr.io/alexbelgium/birdnet-pi-amd64:0.13-74: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=0.13-74&fromImage=ghcr.io%2Falexbelgium%2Fbirdnet-pi-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

### Reproduction steps

```bash
1. Go to '*.*.*.*:8123/hassio/addon/db21ed7f_birdnet-pi/info'
2. Click on 'Update'
3. Scroll down to '....'
4. See error: Can't install ghcr.io/alexbelgium/birdnet-pi-amd64:0.13-74: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=0.13-74&fromImage=ghcr.io%2Falexbelgium%2Fbirdnet-pi-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
```

### Addon Logs

```bash
There's nothing in the addon logs about it
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, HA builder script is broken

https://github.com/home-assistant/builder/issues/212

**Comment by alexbelgium** [comment]
Should be good now with v75
