### ISSUE TITLE
✨ [REQUEST] BirdNET-Pi : add link to flickrimage into mqtt message

### ISSUE THREAD

**Issue by UlrichThiess** [alexbelgium/hassio-addons#1516]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

BirdNET-Pi

### Is your feature request related to a problem? Please describe

No Problem

### Describe the solution you'd like

Please include the link to the flickrimage into the mqtt message, so i could create a card with a picture of the guest in my garden. :-)

**Comment by UlrichThiess** [comment]
Thanks. Installed last version 0.13.77

log:
```
Traceback (most recent call last):
  File "/usr/bin/birdnet_to_mqtt.py", line 20, in <module>
    from .helpers import get_settings
ImportError: attempted relative import with no known parent package
```

**Comment by alexbelgium** [comment]
Thanks! I haven't mqtt configured so did the lazy thing of coding without testing ;-) with your modif does mqtt publishes correctly the flickrimage ?

**Comment by alexbelgium** [comment]
I saw that... but not sure why given that the python script simply reads the log and publishes every instance that finishes with mp3 ; which should in theory be all valid detections.

So if it doesn't work, perhaps I'll rethink the whole mqtt auto-publishing to base it on apprise instead

**Comment by UlrichThiess** [comment]
Something was broken. I uninstalled the AddOn and installed it again. Now ist works again. Every Bird is new. There are many mails. :-)

But MQTT Explorer won't show flickr. I look at this.

**Comment by alexbelgium** [comment]
Is this request completed? As the modification of the mqtt script to ensure all detections will be in the other issue raised?

**Comment by UlrichThiess** [comment]
small bug: please change ```comName``` into ```common_name``` in the master branch
