### ISSUE TITLE
Path change from /config/jellyfin to /config/addons_config/jellyfin breaks metadata in database

### ISSUE THREAD

**Issue by jordanauge** [alexbelgium/hassio-addons#152]
After the latest update, I noticed new content was not updated, and the logs showed path errors while refreshing metadata. The old folders are still accessed despite all paths being correct in jellyfin settings.

This issue is documented here https://github.com/jellyfin/jellyfin/issues/1235

In short, stop the addon and run the following commands in the host (the database in locked otherwise):
```
sudo apt install sqlite3
cd /usr/share/hassio/homeassistant/addons_config/jellyfin/data/data
sqlite3 library.db
```

You can then execute the following SQL query to fix the wrong entries:
```
UPDATE
  "TypedBaseItems"
SET
  "data" = REPLACE("data", '/config/jellyfin/', '/config/addons_config/jellyfin/'),
  "path" = REPLACE("path", '/config/jellyfin/', '/config/addons_config/jellyfin/')
WHERE type='MediaBrowser.Controller.Entities.CollectionFolder';
```

**Comment by alexbelgium** [comment]
Hi, thanks very much for the troubleshooting and solving. This will be problematic for other people, as I don't believe most users will be as technically enclined as you are. Based on your sql knowledge, could I automate this in a script run at addon boot? Thanks!

**Comment by alexbelgium** [comment]
Hi, thanks very much for the troubleshooting and solving. This will be problematic for other people, as I don't believe most users will be as technically enclined as you are. Based on your sql knowledge, could I automate this in a script run at addon boot? Thanks!

Would this script work? It is based on the thread you referenced. 

```sh
#!/bin/bash

#Set variable
db=/config/addons_config/jellyfin/library.db

#Install sqlite3
apt-get update
apt-get install -y sqlite3
apt-get clean

#Modify base
sqlite3 -quote ${db} "UPDATE TypedBaseItems SET data = replace( data, '/config/jellyfin/', 'config/addons_config/jellyfin/' ) WHERE data LIKE '/config/jellyfin/%'; UPDATE TypedBaseItems SET path = replace( path, '/config/jellyfin/', 'config/addons_config/jellyfin/' ) WHERE path LIKE '/config/jellyfin/%';"

**Comment by bruvv** [comment]
Looks good apart from some typos where you forgot a '/' in the updated path. But I'll see if I can spin something up for myself to test this

**Comment by alexbelgium** [comment]
Thanks!

**Comment by jordanauge** [comment]
Seems good indeed. I think we can easily run at during the move as you have already the proper test in the initialization scripts while doing the move. I wonder through how we can automatically fix the already migrated instances.

This is also the opportunity for me to thank you for the great work on these addons

**Comment by jordanauge** [comment]
I would just keep the WHERE i added at the end (which is not in the fix in the thread) that speeds up the update a lot.

**Comment by alexbelgium** [comment]
Thanks! No issue with already migrated database I think : we can run the script at each start and ir will just do nothing if it doesn't find the relevant text... and I'll remove the script in a couple weeks once everyone has updated... As the config location change was some time ago and we can't be sure how many people have already migrated (I have actually 0 idea of how many people use my addons! There is no easy way that I found to put metrics... As local builds are done from a github cache on HA, and therefore files are not directly downloaded... The easiest could be to add a special file downloaded during docker build and count the number of times this file was downloaded but I haven't found a way to do it)

**Comment by alexbelgium** [comment]
I've put the file, but I've got the following error message at addon boot : Table TypedBaseItems doesn't exist. Do you have the same, or is it only because I don't have a "real" library? Or because the WHERE argument prevents the actual TypedBaseItems table to be found?

**Comment by bruvv** [comment]
Maybe @jordanauge can share his database? I think you will need to have some information for it to work. Sorry I didnt reply anymore, got sick and didnt have much time to get into this.

**Comment by alexbelgium** [comment]
Hope you're feeling better! No worry, it's a work that we do for free on our own time, so it's not a matter of a few days ;)

**Comment by jordanauge** [comment]
From your error it seems your table is not populated. Here i have:

```
$ sudo sqlite3 library.db
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> .tables
AncestorIds       ItemValues        TypedBaseItems    mediaattachments
Chapters2         People            UserDatas         mediastreams    
```

and the sqlite3 command succeeds.

I don't know jellyfin well enough to know what bootstraps the database, maybe adding an element in the library.

**Comment by alexbelgium** [comment]
Well if you confirm that the code & structure is correct, I'll close this issue unless we have other ideas for improvements ! Thanks again !

**Comment by jordanauge** [comment]
Got it, if the path to the DB is incorrect, you also get this error instead of an "invalid file or database" message. 

Replace 
db=/config/addons_config/jellyfin/library.db
by
db=/config/addons_config/jellyfin/data/data/library.db

and that might fix it for you also.

**Comment by alexbelgium** [comment]
Prefect, thanks, implemented :)

And thanks @bruvv also for the typo correction

**Comment by dmayle** [comment]
As an additional note for anyone else who comes across this, existing chapter images will also have the wrong path, so the following would be useful:
`UPDATE Chapters2 SET ImagePath = REPLACE(ImagePath, '/config/jellyfin/', '/config/addons_config/jellyfin/') WHERE ImagePath LIKE '%/config/jellyfin/%';`
