### ISSUE TITLE
🐛 [Addon name] <title>

### ISSUE THREAD

**Issue by DigitalDevourer** [alexbelgium/hassio-addons#1522]
### Description

The website linked in the README redirects to multiple spammy and/or insecure websites. 

A Google search shows the current website is [this](https://jellyfin.org/).

### Reproduction steps

```bash
1. Go to https://github.com/alexbelgium/hassio-addons/blob/master/jellyfin/README.md#about
2. Click on "Jellyfin" link.
3. Get erroneously redirected? 
4. See error.
```

### Addon Logs

```bash
There was none.
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks! Indeed they have changed of website url. I've corrected the Readme when your link
