### ISSUE TITLE
🐛 [Mealie] Mealie pulling Nightly, not the latest release version

### ISSUE THREAD

**Issue by andrew-codechimp** [alexbelgium/hassio-addons#1548]
### Description

The latest Mealie update has pulled the Nightly rather than V1.12.0
https://github.com/alexbelgium/hassio-addons/commit/a63794a23b268464a187b83eb543f58ec07f98ea

This addon has been doing nightlies for a while, but the latest nightly is the V2 beta which has major breaking changes, is not fully tested.  The official Mealie integration for HA has not yet been updated to support this so will break, along with existing rest based implementations.
I'm not sure if this can be reverted as there are DB changes but can the build for this be fixed to pick up the latest prod release rather than the nightly to avoid this scenario in future?

### Reproduction steps

```bash
Install latest add-on
Look at the version within the Mealie web UI which says Nightly, not V1.12.0
```

### Addon Logs

```bash
No errors in logs.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks, I'll revert to latest tag but then likely all installations will break down

**Comment by andrew-codechimp** [comment]
Thanks for quickly changing this, yes it's not ideal for those that have updated already but at least it will stop the majority having issues.

**Comment by alexbelgium** [comment]
Thanks for having raised it, I've added a comment in the changelog hopefully it will help

**Comment by alexbelgium** [comment]
Hi, looks like database is stored in a separate container and not mealie's. This means that people likely won't have backups. I fear that now that people's database have moved to v2 we will be stuck with it...

**Comment by andrew-codechimp** [comment]
Mealie has its own backup system for its data, which you have to download and store it somewhere, but unless you have a working Mealie instance you won't be able to get back in to restore it.
The nightly builds could break things at any time so `latest` is the way to go forwards but if we revert to nightly now then approx 1500 users of the Mealie integration will have that breaking until at least the next HA release.

**Comment by alexbelgium** [comment]
Indeed this is quite inconvenient, as the users of the addon will likely have anyway to reset their databases if they don't have performed such a backup. I will describe a manual way to restore the backup but it is something needing to go into the system files and could be complex for this number of users

There was 1030 unique downloads since last update so this should reflect at +/-20% the amount of users impacted

**Comment by tonka3000** [comment]
@alexbelgium Does that mean that I can not fix it if I have no backup from weeks ago? Or is it enough to create a mealie backup now (from the 2.0 version in 1.12.0) and restore it in the old version (1.2 in 1.12.0-2).

**Comment by alexbelgium** [comment]
Hi @andrew-codechimp, it is still a bit the chaos with the whole mealie downgrade situation as I understand that the latest 1.2.0-2 addon was pushed using a nightly 1.2.0 database version that is not the same as the current latest image.

I then propose to migrate back to the nightlies tag, so it would work for all users : people on 1.2.0-* would upgrade, and people that had already updated would have a working version.

What do you think ?

**Comment by andrew-codechimp** [comment]
Hi Alex, the 2024.9 release of Home Assistant added support for 2.0 DB version as well as 1.2 so you can go ahead and update the container to use the nightlies.
Can I suggest that once 2.x of Mealie is fully released you change back to the Latest tag to avoid this happening in future, should a major breaking change enters the nightly releases, that way we will get a chance to make the changes with the integration (hopefully not that often!)

**Comment by alexbelgium** [comment]
Thanks for the feedback. Do you know if a 2.0 backup can be restored to a 1.2 version? To see if it is worth duplicating the add-on with a latest tag for people who want to stay in 1.2

**Comment by andrew-codechimp** [comment]
No it's not possible to restore a 2.0 db to 1.2
The 2.0 nightly seems pretty stable and the new feature doesn't get in the way if you don't need it so I'd say most people wouldn't care about updating to the nightly now the integration works with it.

**Comment by alexbelgium** [comment]
Thanks, then 2.0 it is

**Comment by andrew-codechimp** [comment]
Hi @alexbelgium version 2.0 has now been released and this is what you get when you pull the :latest image, which is the same as the nightly was as far as breaking changes.
Can you now change your docker to pull :latest so that if a future nightly is released with breaking changes we have time to fix the integration. 
I have a specific non-addon instance I run from nightly for testing the integration so I'll see future changes coming before it reaches a latest release.

**Comment by alexbelgium** [comment]
Thanks very much! I've adapted it and it should start pulling latest as soon as tomorrow
