### ISSUE TITLE
[Mealie] Unable to locate custom environment variables

### ISSUE THREAD

**Issue by user34756361233** [alexbelgium/hassio-addons#1558]
### Description

When I install Mealie it creates a folder at /Volumes/addon_configs/db21ed7f_mealie but the logs shows Mealie is looking for the config file in /config/addons_config/mealie/config.yaml and reverts to using default parameters. Strangely, it shows all the info from config.yaml file in the logs (redacted for security), so I assume it must be reading it.

If I move the config file to /config/addons_config/mealie/config.yaml  it creates a new file at /Volumes/addon_configs/db21ed7f_mealie

### Reproduction steps

```bash
1. Install addon
2. Start add-on (logs say no config file)
```

### Addon Logs

```bash
-----------------------------------------------------------
 Add-on: Mealie
 Mealie is a self-hosted recipe manager and meal planner built in Vue
-----------------------------------------------------------
 Add-on version: v1.12.0-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
ALLOW_SIGNUP='true'
DATA_DIR='/config'
PGID='1000'
PUID='1000'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='true'
Timezone set from Etc/UTC to Europe/London
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory
Load environment variables from /config/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /addon_configs/db21ed7f-mealie/config.yaml
---------------------------------------------------------
Wiki here on how to use: [https://github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables](https://github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables)

SMTP_HOST='[REDACTED]'
SMTP_PORT='587'
SMTP_FROM_NAME='Mealie'
SMTP_AUTH_STRATEGY='TLS'
SMTP_FROM_EMAIL='[REDACTED]'
SMTP_USER='[REDACTED]'
SMTP_PASSWORD='[REDACTED]'
BASE_URL='https://192.168.X.XXX:9090'
OPENAI_API_KEY='[REDACTED]'
OPENAI_MODEL='gpt-4'
OPENAI_ENABLE_IMAGE_SERVICES='True'
OPENAI_WORKERS='2'
OPENAI_REQUEST_TIMEOUT='60'
OPENAI_BASE_URL='https://api.openai.com/v1'
/etc/cont-init.d/01-custom_script.sh: executing
Execute /addon_configs/db21ed7f-mealie/mealie.sh if existing
Wiki here: [https://github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation](https://github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation)
/etc/cont-init.d/31-nginx.sh: executing
[16:06:53] INFO: Exporting variables
ALLOW_SIGNUP=true
DATA_DIR=/config
PGID=1000
PUID=1000
certfile=fullchain.pem
keyfile=privkey.pem
ssl=true
[16:06:54] INFO: No config.yaml found in /config/addons_config/mealie/config.yaml, using default parameters
Permissions adapted
[16:06:54] INFO: Starting nginx
[16:06:54] INFO: Starting app
INFO     2024-08-29T16:07:04 - Started server process [7]
INFO     2024-08-29T16:07:04 - Waiting for application startup.
INFO     2024-08-29T16:07:04 - start: database initialization
INFO     2024-08-29T16:07:04 - Database connection established.
INFO     2024-08-29T16:07:04 - Context impl SQLiteImpl.
INFO     2024-08-29T16:07:04 - Will assume non-transactional DDL.
INFO     2024-08-29T16:07:04 - Checking for migration data fixes
INFO     2024-08-29T16:07:05 - end: database initialization
INFO     2024-08-29T16:07:05 - -----SYSTEM STARTUP-----
INFO     2024-08-29T16:07:05 - ------APP SETTINGS------
INFO     2024-08-29T16:07:05 - {
    "TESTING": false,
    "PRODUCTION": true,
    "LOG_CONFIG_OVERRIDE": null,
    "LOG_LEVEL": "info",
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "BASE_URL": "http://localhost:8080",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "HOST_IP": "*",
    "API_HOST": "0.0.0.0",
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "GIT_COMMIT_HASH": "0d06494bbfc62fc8a1771a85fd308190891d6167",
    "ALLOW_SIGNUP": true,
    "DAILY_SCHEDULE_TIME": "23:45",
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "OIDC_AUTH_ENABLED": false,
    "OIDC_CLIENT_ID": null,
    "OIDC_CONFIGURATION_URL": null,
    "OIDC_SIGNUP_ENABLED": true,
    "OIDC_USER_GROUP": null,
    "OIDC_ADMIN_GROUP": null,
    "OIDC_AUTO_REDIRECT": false,
    "OIDC_PROVIDER_NAME": "OAuth",
    "OIDC_REMEMBER_ME": false,
    "OIDC_SIGNING_ALGORITHM": "RS256",
    "OIDC_USER_CLAIM": "email",
    "OIDC_GROUPS_CLAIM": "groups",
    "OIDC_TLS_CACERTFILE": null,
    "OPENAI_BASE_URL": null,
    "OPENAI_API_KEY": null,
    "OPENAI_MODEL": "gpt-4o",
    "OPENAI_ENABLE_IMAGE_SERVICES": true,
    "OPENAI_WORKERS": 2,
    "OPENAI_SEND_DATABASE_DATA": true,
    "OPENAI_REQUEST_TIMEOUT": 60,
    "WORKER_PER_CORE": 1,
    "UVICORN_WORKERS": 1
}
INFO     2024-08-29T16:07:05 - Daily tasks scheduled for 2024-08-29 22:45:00+00:00
INFO     2024-08-29T16:07:05 - Application startup complete.
INFO     2024-08-29T16:07:05 - Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by kk-sonata** [comment]
Also getting this bug. The workaround in #1556 works, but @alexbelgium a suggestion: SMTP_PASSWORD should be masked in the addon log for security

**Comment by user34756361233** [comment]
Bump, no solution yet?

**Comment by Krispkiwi** [comment]
Currently watching this as well

**Comment by mbobbar** [comment]
Also watching this, though the workaround was effective in getting back up and running.

**Comment by user34756361233** [comment]
bump, no resolution yet?

**Comment by user34756361233** [comment]
Just to be sure I copied config.yaml to  /Volumes/addon_configs/db21ed7f_mealie and I updated to version v1.12.0-4. After update I am greeted by the screen in attachment. So I restored to my backup of v1.120-2 after which I can login again. 

![Screenshot 2024-09-22 at 20 34 33](https://github.com/user-attachments/assets/8505002f-13a1-49b7-b310-3ec97fafd08f)

**Comment by ryan7273** [comment]
Uninstalling completely and reinstalling fixed the env variable problem for me, but now it keeps failing to upgrade my database to a new version so your mileage may vary. My next plan is to restore from backups, export all the data, archive the database, start everything from fresh, and try to import.

**Comment by Krispkiwi** [comment]
> Uninstalling completely and reinstalling fixed the env variable problem for me, but now it keeps failing to upgrade my database to a new version so your mileage may vary. My next plan is to restore from backups, export all the data, archive the database, start everything from fresh, and try to import.
> 
> For what it's worth, I just saw v1.12.0-4 and upgraded to it. My env variables are still working, but the database upgrade is still failing. Hopefully it will fix things for others, though.

How has this gone for you? I'm hesistent to reinstall until the matter is resolved

**Comment by user34756361233** [comment]
bump as not resolved

**Comment by boszme** [comment]
So this is seems like more of a general issue (not particularly with the mealie addon) as the injector script is using the actual hostname which contains dash however on the filesystem the configs are stored with underscore instead (at least in my case).

@alexbelgium can you take a look on this please?

https://github.com/alexbelgium/hassio-addons/blob/b734391a37c12ac9e8abd88a762735532682c3b0/.templates/01-config_yaml.sh#L16

**Comment by alexbelgium** [comment]
Hi, injector script works fine for me! Sometimes you need to have several lines and be sure to save for it to execute though not sure why.

**Comment by alexbelgium** [comment]
In case systems handle hostnames differently I forced underscores, thanks

**Comment by alexbelgium** [comment]
> /addon_configs/db21ed7f-mealie/config.yaml

Please access the file from /homeassistant/addons_config/mealie (or mealie_data I forgot).

I've pushed a version based on beta 2.0 that should solve everything. If it is confirmed, I'll push again the new config logic to use the new paths of  /addon_configs/db21ed7f-mealie but I wanted to do it in a sequential manner

**Comment by datdamnzotz** [comment]
I am experiencing this:

Fresh install this morning, the Install creates
```\\<machine\config\addons_config\db21ed7f-mealie\config.yaml```

App is actually reading from:

```\\<machine>\config\addons_config\mealie\config.yaml```

**Comment by alexbelgium** [comment]
> I am experiencing this:
> 
> Fresh install this morning, the Install creates:
> 
> ```
> \\<machine\config\addons_config\db21ed7f-mealie\config.yaml
> and
> \\<machine>\config\addons_config\mealie_data
> ```
> 
> App is actually reading from: `\\<machine>\config\addons_config\mealie\config.yaml`
> 
> So renaming the directory from `\\<machine\config\addons_config\db21ed7f-mealie\` to `\\<machine\config\addons_config\mealie\`
> 
> Works!

Thanks, corrected in next version :)

**Comment by boszme** [comment]
Thanks for the help, after fixing the path problems the env injector started to work for me!

**Comment by user34756361233** [comment]
Worked for me. Update from Mealie v1.12.02 to v2.0-beta5. All information available after upgrade and database complete. Thanks for the work!
