### ISSUE TITLE
🐛 [FIREFLY III] Error : /etc/cont-init.d/99-run.sh exiting 1

### ISSUE THREAD

**Issue by AalianKhan** [alexbelgium/hassio-addons#1559]
### Description

Hello, 

I am trying to install firefly and when trying to start I get the following error
`Error : /etc/cont-init.d/99-run.sh exiting 1`
I have changed the App Key to a random 32 letter and number string

### Reproduction steps

```bash
1. install addon
2. change app key
3. start addon
4. See error
```

### Addon Logs

```bash
-----------------------------------------------------------
 Add-on: Firefly iii
 A free and open source personal finance manager
-----------------------------------------------------------
 Add-on version: 6.1.19
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
APP_KEY='NyZ7GuJNt5NcUZopW1iYAnBzbYA7VOvB'
CONFIG_LOCATION='/config/addons_config/fireflyiii/config.yaml'
DB_CONNECTION='sqlite_internal'
silent='true'
Timezone set from Etc/UTC to America/Toronto
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/addons_config/fireflyiii/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/fireflyiii/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables

... no config file, creating one from template. Please customize the file in /config/addons_config/fireflyiii/config.yaml before restarting.
... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/fireflyiii/fireflyiii.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/99-run.sh: executing
[12:03:06] INFO: Backuping APP_KEY to /config/addons_config/fireflyiii/APP_KEY_BACKUP.txt
[12:03:06] WARNING: Changing this value will require to reset your database
[12:03:06] INFO: Defining database
[12:03:06] INFO: Using built in sqlite
updating database
Error : /etc/cont-init.d/99-run.sh exiting 1
 
Starting the upstream container
```

### Architecture

aarch64

### OS

HAos

**Comment by CamPier** [comment]
If accessing the file with filebrowser it should be mapped to /config/addons_autoscripts/free-games-claimer.sh
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
... no script found, exiting
/etc/cont-init.d/20-folders.sh: executing
Creating config location ...
Copying files if needed...
/etc/cont-init.d/99-run.sh: executing
[16:09:02] WARNING: A default config.env file was copied in /config/addons_config/free_games_claimer. Please customize according to https://github.com/vogler/free-games-claimer/tree/main#configuration--options and restart the add-on
cp: -r not specified; omitting directory '/config/addons_config/free_games_claimer/config.env'
Error : /etc/cont-init.d/99-run.sh exiting 1
 
Starting the upstream container

Same problem

**Comment by PlasmaPod** [comment]
I got mine to work by going into /config/addons_config/fireflyiii/config.yaml
And backspacing the blank line at the bottom

`#============================#
# ALEXBELGIUM'S ENV INJECTOR #
#============================#
#
# All env variables set in this file will be enabled in the app
# This allows enabling more options that normally available in the addon options
# This file must be filled according to the yaml format.
# If the format is invalid, the addon will note an error.
# To validate your yaml, you can use the free online tool http://www.yamllint.com/
# You can use env both for the addon, and for bashio. For bashio, use BASHIO_LOG_LEVEL instead of LOG_LEVEL

# EXAMPLE of the format (you need to remove the # for it to become active)
# TZ: Europe/Paris `
