### ISSUE TITLE
Can’t acces Ha after upgrade

### ISSUE THREAD

**Issue by JaumeJames** [alexbelgium/hassio-addons#1575]
### Description

Can’t acces

### Reproduction steps

```bash
So here is the thing, happened to me with other upgrades( I work on Ios). When I did the upgrade all of a sudden HA doesn’t recognise my username and I really don’t know what to do.
```

### Addon Logs

```bash
{
  "error" : "serverError(statusCode: 400, errorCode: Optional(\"invalid_grant\"), error: nil)"
}
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, this repo supports my addons, which have not link with HAos. You should raise the issue in the homeassistant community https://community.home-assistant.io
