### ISSUE TITLE
[Bitwarden] Difference between yours and home assistant

### ISSUE THREAD

**Issue by X1pheR** [alexbelgium/hassio-addons#158]
Just a small question. What is the difference between your addon version and that of Frenck?
https://github.com/alexbelgium/hassio-addons/tree/master/bitwarden

**Comment by alexbelgium** [comment]
At the beginning, when I put in place mine, the official one was 6m late for updates which prevented to use the android app. It has since now been updated so it is globally the same but I know mine will be updated directly :)

**Comment by X1pheR** [comment]
Haha thanks for explaining. I've seen it before with other addon that updates are quite late to the party. Like with the unifi controller addon.

**Comment by alexbelgium** [comment]
Well Frenck does an incredible job but I think he's very busy and more focused on key HA functions than addons

**Comment by X1pheR** [comment]
Indeed which is good. They do an excellent job. I'm still only scratching the surface functionality wise 😅

**Comment by alexbelgium** [comment]
Me too! But it works exceptionally well for a free software. I'll close this issue. Have fun with the addons :-)
