### ISSUE TITLE
🐛 [Portainer] Not possible to perform Initial Setup

### ISSUE THREAD

**Issue by IPTN** [alexbelgium/hassio-addons#1587]
### Description

Currently it is not possible to perform Initial Setup of Portainer which prevents restoring from backup.
https://github.com/alexbelgium/hassio-addons/blob/25e8a1c324ac6c9ff63f7622f0706a6373e39d28/portainer/config.json#L44
This line is preventing removing the password from the addon configuration options, which is the way to cause a full database reset and allow initial setup.
https://github.com/alexbelgium/hassio-addons/blob/25e8a1c324ac6c9ff63f7622f0706a6373e39d28/portainer/README.md?plain=1#L76
https://github.com/alexbelgium/hassio-addons/blob/25e8a1c324ac6c9ff63f7622f0706a6373e39d28/portainer/rootfs/etc/services.d/portainer/run#L53-L61

This behavior of not allowing matches [HA documentation](https://developers.home-assistant.io/docs/add-ons/configuration/#options--schema) for the options and schema fields, which results in this behavior 
![image](https://github.com/user-attachments/assets/35b66e44-0626-416a-a747-5bbd5894806c)
When simply removing the password field from the addon options it will be repopulated to the default value of 'homeassistant'.
https://github.com/alexbelgium/hassio-addons/blob/25e8a1c324ac6c9ff63f7622f0706a6373e39d28/portainer/config.json#L28

Removing the line [first referenced](https://github.com/alexbelgium/hassio-addons/blob/25e8a1c324ac6c9ff63f7622f0706a6373e39d28/portainer/config.json#L44) from schema in config.json should result in the intended behavior of allowing not setting a password in the addon options.

Willing to submit a PR for this change if requested, but it would obviously be a trivial one.

### Reproduction steps

```bash
1. Remove password from addon options
2. Password option is auto populated to the default value of 'homeassistant'
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Portainer
 Manage your Docker environment with ease
-----------------------------------------------------------
 Add-on version: 2.21.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1
 Home Assistant Core: 2024.9.3
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
certfile='fullchain.pem'
keyfile='privkey.pem'
password='homeassistant'
ssl='false'
/etc/cont-init.d/01-config_yaml.sh: executing
/etc/cont-init.d/01-custom_script.sh: executing
/etc/cont-init.d/30-nginx.sh: executing
/etc/cont-init.d/31-portainer.sh: executing
 
Starting the upstream container
 
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Portainer
 Manage your Docker environment with ease
-----------------------------------------------------------
 Add-on version: 2.21.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1
 Home Assistant Core: 2024.9.3
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun portainer (no readiness notification)
[20:50:55] INFO: Starting Portainer...
[16:50:55] INFO: Waiting for port 9000 to open...
s6-rc: info: service legacy-services successfully started
[20:50:55] INFO: ... password set to homeassistant
[20:50:55] INFO: ... non-addon containers hidden
[20:50:55] INFO: ... portainer launched
2024/09/27 08:50PM INF github.com/portainer/portainer/api/cmd/portainer/main.go:370 > encryption key file not present | filename=portainer
2024/09/27 08:50PM INF github.com/portainer/portainer/api/cmd/portainer/main.go:393 > proceeding without encryption key |
2024/09/27 08:50PM INF github.com/portainer/portainer/api/database/boltdb/db.go:125 > loading PortainerDB | filename=portainer.db
2024/09/27 08:50PM INF github.com/portainer/portainer/api/internal/ssl/ssl.go:80 > no cert files found, generating self signed SSL certificates |
2024/09/27 08:50PM INF github.com/portainer/portainer/api/cmd/portainer/main.go:542 > created admin user with the given password. |
2024/09/27 08:50PM INF github.com/portainer/portainer/api/chisel/service.go:228 > generated a new Chisel private key file | private-key=/data/chisel/private-key.pem
2024/09/27 20:50:55 server: Reverse tunnelling enabled
2024/09/27 20:50:55 server: Fingerprint tzcmzQBRytTsOCwh1eWhV+EEsd7KC4sDyJzrp5ZbRf4=
2024/09/27 20:50:55 server: Listening on http://0.0.0.0:8000
2024/09/27 08:50PM INF github.com/portainer/portainer/api/cmd/portainer/main.go:655 > starting Portainer
2024/09/27 08:50PM INF github.com/portainer/portainer/api/http/server.go:370 > starting HTTPS server | bind_address=:9443
2024/09/27 08:50PM INF github.com/portainer/portainer/api/http/server.go:354 > starting HTTP server | bind_address=0.0.0.0:9000
[16:50:56] INFO: Starting NGinx...
```

**Comment by alexbelgium** [comment]
Hi, doesn't just changing the password lead to a reset of the database? So if you just change homeassistant to homeassistant2? I've read quite quickly through your extensive description though - I'll check it tomorrow

**Comment by alexbelgium** [comment]
Hi, thanks I see your point. I'll check tomorrow (an update will also likely come this night as a new version exists)

**Comment by alexbelgium** [comment]
The issue is that if there is no password it is less convenient for novice users for whom it would be easier to have the password set by default in the HA options. Perhaps I could add a specific boolean that would be automatically reset to false on boot, allowing to circumvent the whole password feature for one single boot...

**Comment by alexbelgium** [comment]
Now you are a very comprehensive person in your search and documentation!

My slight concern in removing the default value is that it makes things less "beginner-proof" as the password will need to be set by them though an action.

Would a middle ground : typing "blank" in the password field be an acceptable workaround? And I'll update the documentation as such. This would allow both the use case of starting without a password (resetting the database), and setting a default value for beginners to have a ready-to-use add-on. 

Second option for me is to remove the default option tag but make a big warning in the log that the password was not set in the options

**Comment by alexbelgium** [comment]
Argh, I forgot about this one, sorry - I had seen your text and instead of answering directly, thought that it warranted a bit more reflection. So here it comes :

Indeed I see your point - I usually try to make things as easy as possible and indeed in this case perhaps it is not warranted.

"One downside to relying on Portainers Initial Setup exclusively is that a beginner user has no way of easily retrieving or reseting the password outside of Portainer." > I agree, either they can uninstall or reinstall, or simply setting the addon in the addon options does this too.

"The other caveat with this approach is that there is a [5 minute window](https://portal.portainer.io/knowledge/your-portainer-instance-has-timed-out-for-security-purposes) to complete the Initial Setup" > now this is a bigger issue. I can put a warning at the bottom of the log.

I'll try to push a version with the new logic, and hopefully will have time to try it before other people update ! Worst case is that all users would loose their databases which would not be the best outcome.

thanks for your very comprehensive descriptions!

**Comment by alexbelgium** [comment]
EDIT : ok, I've rolled back the update. As I feared, changing the default setting removed my password and resetted my database. Therefore, for user continuity I can't remove `    "password": "homeassistant",` from the `options:` block.

**Comment by alexbelgium** [comment]
It seems that HA considers that if a default value was set in the addon options and removed in a further update, it should delete it from the user config (which of course seems like a very bad idea ;-) )

Then I'll have to use the second option : manually type "empty" in password to trigger the startup without password ...

**Comment by alexbelgium** [comment]
Wait perhaps an error on my code, I'll try again with a second version (named -test). I revert the versions as soon as I install them to be sure that no one installs them (I know I should use a devcontainer but mine isn't current working ;-) )

**Comment by alexbelgium** [comment]
And indeed people are starting to get confused : https://github.com/alexbelgium/hassio-addons/discussions/1586

I've tried setting default to "empty" and it resets again my database. So I think I'll keep the default to "homeassistant" and allow initial boot by setting the option to "empty", and write that in the README

**Comment by alexbelgium** [comment]
It should be working now by writing "empty" in the password ; and I tested it on my system. The versions currently pushed are taking this behavior into account
