### ISSUE TITLE
🐛 [immich] ERR_INVALID_URL

### ISSUE THREAD

**Issue by jdumeez** [alexbelgium/hassio-addons#1589]
### Description

Since i installed the latest version of immich today 
1.116.2, the add-on no longer boots up.

Below is the error that gets thrown (note that the external domain is configured within the add-on recently to improve sharing)

### Reproduction steps

```bash
Configure in server settings.
https://immich.app/docs/administration/system-settings#external-domain

Install latest version
Boot the add-on
```

### Addon Logs

```bash
api worker exited with code 1
Starting api worker
[Nest] 77057  - 09/28/2024, 7:16:38 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 77057  - 09/28/2024, 7:16:38 PM   ERROR [Api:An instance of SystemConfigDto has failed the validation:
 - property server.externalDomain has failed the following constraints: isUrl 
] Validation error
TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at SystemConfigCore.buildConfig (/app/immich/server/dist/cores/system-config.core.js:136:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)https://github.com/alexbelgium/hassio-addons/issues/new?assignees=&labels=bug&projects=&template=BUG-REPORT.yml&title=🐛+%5BAddon+name%5D+%3Ctitle%3E
    at async /app/immich/server/dist/cores/system-config.core.js:80:35 {
  code: 'ERR_INVALID_URL',
  input: 'immich.owndomain.xyz'
}
```

### Architecture

amd64

### OS

HAos

**Comment by jdumeez** [comment]
Hey Alex, i used your environmental injector to set IMMICH_CONFIG_FILE and pointed it to a file with following content
{ 
 "server": {
    "externalDomain": "",
    "loginPageMessage": ""
  },
}

This for now allows me to boot up again. Not perfect as i can no longer go back to the GUI now, but i have raised this with the immich team.

**Comment by alexbelgium** [comment]
Thanks for the feedback!
