### ISSUE TITLE
fireflyiii addon https configuration

### ISSUE THREAD

**Issue by michelebossa** [alexbelgium/hassio-addons#159]
* Addon name : fireflyiii
* Addon version : 5.6.10 

**Describe the bug**
 I'm trying to expose the fireflyiii on HTTPS port by using ngix addon without success:

config.yaml
APP_URL: "https://XXXXXX:8123/firefly"
TRUSTED_PROXIES: "**"
 
Ngix configuration
		location /firefly {
			proxy_pass http://XXXXXX:3473/;
			proxy_set_header Host $http_host:8123/firefly;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_buffering off;
        }
		

<img width="386" alt="image" src="https://user-images.githubusercontent.com/38975058/149342729-7025b78e-0d47-4486-9171-a05d0a0040e2.png">

into html page it is incorrect the url
<img width="389" alt="image" src="https://user-images.githubusercontent.com/38975058/149342926-acba54cd-7970-45ad-8d1a-6e2486d1efaf.png">

 Ho can i made this? 

**System**
* Supervisor version: supervisor-2021.12.2
* Host system version: core-2021.12.9

**Comment by alexbelgium** [comment]
Hi, thanks - you should however probably post that to the addon nginx github, I don't use it and not sure how it should be configured... Not all apps support nginx however

**Comment by deku-m** [comment]
Isnt nginx proxy manager (addon) not easy to use for this kind of configuration? I use in combination with inadyn to use subdomains bind to it.

**Comment by alexbelgium** [comment]
honestly I have never used the addon nginx proxy manager...
I see  $http_host:8123/firefly;, however normally isn't it accessed from  $http_host:8123 directly ?
Also you could try http://XXXXXX:3473; for proxypass (without /)

**Comment by michelebossa** [comment]
I'm using NGINX Home Assistant SSL proxy  i have found a configuration of ngix will work at 95% at moment i see when i login it is not working the redirect i need to reload the page. 
If NGIX it is not the best approach how can i use these addon but with https url?

I'm using this configuration:

`        location /firefly {
            proxy_pass http://IP LOCAL:3473/;
			proxy_set_header X-Forwarded-For 	$remote_addr;
			proxy_set_header X-Forwarded-Host 	$host;
			proxy_set_header X-Forwarded-Proto 	$scheme;
			proxy_set_header X-Forwarded-Port 	443;
			proxy_set_header Host 		$host;
			proxy_set_header X-Real-IP 		$remote_addr;
			proxy_set_header Accept-Encoding 	"";
			rewrite 	 ^/firefly/(.*)$ 	/$1 break;
			proxy_redirect   $scheme://$host 	$scheme://$host:8123/firefly;
			sub_filter 	 $scheme://$host 	$scheme://$host:8123/firefly;
			sub_filter 	 $scheme:\/\/$host 	$scheme:\/\/$host:8123/firefly;
			sub_filter_types text/plain application/xml application/json text/html text/css text/javascript application/javascript;
			sub_filter_once  			off;
			sub_filter_last_modified 		on;
			gzip_types      text/plain application/xml application/json text/html text/css text/javascript application/javascript;
			gzip_proxied    no-cache no-store private expired auth;
			add_header Service-Worker-Allowed /;
}
`

**Comment by michelebossa** [comment]
i'm close becouse it is not related at the addon thanks for the help

**Comment by alexbelgium** [comment]
Thanks. If you find a way though don't hesitate to create a PR to add the info in the addon documentation, I'm sure it could be useful for other people! :)

**Comment by alexbelgium** [comment]
Hi, did you manage to make it work in the end?

**Comment by michelebossa** [comment]
Hi,
it is not work at 100% i have still the problem at login but with refreshing of page i can use.

Thanks

**Comment by alexbelgium** [comment]
Thanks for the feedback!
