### ISSUE TITLE
✨ [REQUEST] SCRUTINY Time updates

### ISSUE THREAD

**Issue by hiagocosta** [alexbelgium/hassio-addons#1590]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Scrutiny

### Is your feature request related to a problem? Please describe

the minimum is hourly

### Describe the solution you'd like

is it possible to set more frequently updates, alike avery 5 minutes or set this manually?
will be a great update for this addon, since i'm planning to monitor temperature of my disks to turn on a cooling automation

**Comment by alexbelgium** [comment]
Hi, I've added an option for every 15 min

**Comment by hiagocosta** [comment]
Hi Alex, thank you so much for that!!
