### ISSUE TITLE
✨ [REQUEST] Update Guacamole Client addon to Guacamole 1.5.5

### ISSUE THREAD

**Issue by andrewjswan** [alexbelgium/hassio-addons#1591]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Guacamole Client

### Describe the solution you'd like

Update `Guacamole Client` addon to `Guacamole 1.5.5`, base image already updated:
```
2024-04-09 - Updated to Guacamole 1.5.5
```

**Comment by henrikbla** [comment]
I second this request, would be very much appreciated. Happy to help with testing if needed.

**Comment by alexbelgium** [comment]
Hi, in theory auto updates are on Saturday ; it seems it didn't trigger I'll push it manually

**Comment by henrikbla** [comment]
Thanks, tested and works! I have a very simple setup with only one RDP connection though.

**Comment by alexbelgium** [comment]
Thanks very much! Always my worry ;) there was a nightmare update with Mealie recently and I'm glad here it worked seamlessly!
