### ISSUE TITLE
🐛 [qBittorrent] Running addon produces a HAOS full crash & restart

### ISSUE THREAD

**Issue by diamant-x** [alexbelgium/hassio-addons#1594]
### Description

Hi,

Everytime I run qBittorrent addon, after some (variable, non precise) time my whole HAOS crashes and self-restarts. I have reduced that to the qBittorrent addon, with not sure reason why. It used to run just fine.
I believe my problems started when HAOS upgraded their Python library https://github.com/home-assistant/core/issues/110538#issue-2134045723 which I thought was related to HAOS issue. But lately I've been doing some A/B testing and have re-assessed that the issue is down to qBittorrent (or Sonar, or Radar, which I run at the same time always).
My HA full system error log file looks the same as in the original linked thread above.

I understand is not a common issues or this would be flooded of tickets, but would love to understand why, and if maybe the addon is using some old ha-utils or Python versions that makes it crash with latest HAOS versions?

Versión | core-2024.9.3
-- | --
Tipo de instalación | Home Assistant OS
Desarrollo | false
Supervisor | true
Docker | true
Usuario | root
Entorno virtual | false
Versión de Python | 3.12.4
Familia del sistema operativo | Linux
Versión del sistema operativo | 6.6.31-haos-raspi
Arquitectura de la CPU | aarch64

### Reproduction steps

```bash
1. Normal stable running HAOS
2. Start qBittorrent addon (which uses smb mounted folders)
3. After some time (either 5 minutes or 5 hours) system will crash and reload.
```

### Addon Logs

```bash
[custom-init] No custom files found, skipping...
crond: crond (busybox 1.36.1) started, log level 8
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

Connection to localhost (::1) 8080 port [tcp/http-alt] succeeded!
[ls.io-init] done.
[14:06:35] INFO: Starting NGinx...
nginx: [warn] the "http2_push_preload" directive is obsolete, ignored in /etc/nginx/servers/ingress.conf:17
crond: USER root pid 1629 cmd run-parts /etc/periodic/15min
crond: USER root pid 2886 cmd run-parts /etc/periodic/15min
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, I experienced the same but only once. I tried reduced the amount of accepted connections from the qBittorrent settings and it seems stable since! Or it was a coincidence, but worth testing

**Comment by diamant-x** [comment]
I'm trying to apply you suggestion. I also cleaned up my list.
But I think there's something else. I saw my HAOS RAM usage chart creepingly increasing when the torrent addon is running, but the RAM usage reported by the addon is stable, which means it might be using some "core OS" processes for some of its stuff.

Example, whole HA OS RAM:, last 24h:
![image](https://github.com/user-attachments/assets/63fb368e-a844-4371-9624-89368e1880bc)
QBit addon reported RAM:
![image](https://github.com/user-attachments/assets/e8ee5e43-1159-4dc3-8051-861648f3d01a)

**Comment by alexbelgium** [comment]
Very interesting, nicely seen ! Alas I'm not sure how to use this info to solve the issue... Any ideas?

**Comment by alexbelgium** [comment]
Mmh there seems to be a reported memory leak on the core also, not necessarily linked but at least coincidental https://github.com/home-assistant/core/issues/123831

**Comment by alexbelgium** [comment]
Globally it seems that for each ha memory leak I've seen do far the solution is just to restart the add-on everyday :) https://github.com/coder/code-server/issues/5201

**Comment by alexbelgium** [comment]
OK it's confirmed to be due to qbittorrent itself it seems : https://github.com/qbittorrent/qBittorrent/issues/21502

**Comment by diamant-x** [comment]
> OK it's confirmed to be due to qbittorrent itself it seems : [qbittorrent/qBittorrent#21502](https://github.com/qbittorrent/qBittorrent/issues/21502)

It does seem to be that in regards to. The memory leak indeed. Nice finding thanks!
I might try to roll back to pre v5, although is a pain in the a* to do it because emy backup location contains a lot of files

However I do recall the haos crashes also happened before v5.

**Comment by diamant-x** [comment]
> I'm trying to apply you suggestion. I also cleaned up my list. 

I did this but still occurring. Out of curiosity , in your stable setup how many torrent you have, maybe above +200 starts rising some stability issue in a RPi4 8Gb.

**Comment by alexbelgium** [comment]
I have 0 torrents ;) I delete them once they reach a certain ratio! Indeed HA doesn't seem to manage well multiple connections...

**Comment by diamant-x** [comment]
I'm still looking at this.
Can't find references of it in the main repository. I saw a recommendation of 10 connections max per torrent, but i've applied it and still the same.... https://github.com/linuxserver/docker-qbittorrent/issues?q=crash

I don't understand why it crashed the whole HAOS (I can understand and accept a crash of the container). Is there no way to limit the crash to the container?

**Comment by alexbelgium** [comment]
Have you disabled qbit_manage in the addon options too?

**Comment by diamant-x** [comment]
> Have you tried another ui in case it is the ui and not qbittorrent?

The container has crashed sometimes without never logging into the web ui. Just starting the container, leave it run and suddenly HA crashes. I've used vuetorrent as ui, not sure if there's another UI that might be 'more stable', but this was the one that seemed the most modern and mobile friendly.

> But indeed ha shouldn't be affected by a single container... If it is, then it's a failure of the supervisor code

I guess I can't modify this on my instance. Is this something that can be logged tracked? Maybe the base-addon used is not up to date? 

> Another idea: you could add daily addon restart in case of memory leak?

The memory leak was solved. Was an upstream issue as correctly linked in a previous post. This one is just a random HAOS crash.

i have doubts of whether the PUID and GUID might be something to do? I set them to 0 and 0, because I think to recall they were the only options so that a torrent created from the addon would become visible for other users.

Current config:
```
DNS_server: 192.168.1.1 (my Adguard home adress)
PGID: "0"
PUID: "0"
SavePath: /mnt/video/Downloads
Username: !secret_username
certfile: fullchain.pem
customUI: vuetorrent
keyfile: privkey.pem
qbit_manage: false
ssl: false
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.1.0/16
TZ: Europe/Madrid
cifspassword: !secret_password
cifsusername: !secret_user
networkdisks: //192.168.1.2/video (my smb drive)
```

**Comment by diamant-x** [comment]
I'm checking the supervisor information and RAM usage is not being reported (while CPU is). Could this be an addon issue?

![Image](https://github.com/user-attachments/assets/0592cf27-5df3-4e33-8ee4-c1df987fea33)

**Comment by alexbelgium** [comment]
> I'm checking the supervisor information and RAM usage is not being reported (while CPU is). Could this be an addon issue?
> 
> ![Image](https://github.com/user-attachments/assets/0592cf27-5df3-4e33-8ee4-c1df987fea33)

Mmh once again this is likely supervisor... If you check with portainer it should provide the actual amounts. I have 96Mo for qbittorrent at fresh start, 0.1% cpu, 4.4Mo RX, 110kb TX, 1.2 mb IO.

If you let that run for some time you should have stats showing if there is a trend

Re. the points above : 1. I'm using also vuetorrent ; 2. I'm not using HA base-addon, I'm using the upstream one (but anyway your HA is always up dated to latest), 3. UID/PID shouldn't impact. The only difference between your configs & mine is that I use 8.8.8.8 instead of my adguard home ! I don't know if actually it is adguard home that crashes due to overload of qbittorrent... Might be interesting to disable it to try.

So as a summary I would try empiratically : 
- if qbit_manage is enabled in the options, disable it
- monitor qbittorrent & adguard stats through portainer
- try to use another DNS
- daily reboots if nothing else works...

Good luck this must be a really annoying issue!

**Comment by alexbelgium** [comment]
Hi, for the SYS_ADMIN part it's for continuity with previous way of working ; therefore I cannot remove it
For NET_ADMIN, it is needed I think to map the vpn. I could try to disable it
DAC_READ_SEARCH : don't remember

I've set up a qbittorrent test addon there if you want to test : https://github.com/alexbelgium/hassio-addons-test

I've removed NET_ADMIN and DAC_READ_SEARCH we'll need to test if all functions are still working

**Comment by diamant-x** [comment]
Thanks, I'll give it a look. Can I ask you to change the name/description/slug of the test add-on please? They are impossible to differentiate once installed xD

**Comment by diamant-x** [comment]
Ok nevermind, I just started the add-on with the same config as the other (except the DNS, which I kept default to differentiate between the add-ons) and added one single torrent which made crash the add-on. It crashed during the file recheck.
Not sure if there's any log I can retrieve from a crashed HAOS? Or they get erased?

**Comment by alexbelgium** [comment]
No idea for haos logs. For this addon in test repo just tell me if you want to try anything! Alas I fear it is more on the side of HA os itself...

**Comment by diamant-x** [comment]
> For this addon in test repo just tell me if you want to try anything!

Would it be possible to remove the sysadmin thing? I know mnt might fail so I can explore using the built in nas mount options.

Not sure what you meant with "continuity with previous way of working" or if removing that might break the add-on at all?

Thanks.

**Comment by alexbelgium** [comment]
It means I won't remove it as people wouldn't be able to mount their folders (myself included) and the HA system is not as convenient. However i can remove it from the test version

**Comment by diamant-x** [comment]
> However i can remove it from the test version

Fair enough. At this point I'm mainly trying to figure out where the root cause lies on, the add-on or somewhere else in HAOS.  If you could update the test add-on removing it, and I'll try without mounting the path in the add-on I can see if that makes any chance or I need to keep looking.

Thanks!

**Comment by diamant-x** [comment]
Ok, jsut tried with version "-2" and still crashed. I scrolled the Host logs but the first line is the boot line. (Date time are wrong because Rpi has no cmos battery to store last known datetime clock).

So the issue doesn't seem to be related to that either. Not sure what could cause a HAOS crash...

```
2024-05-27 21:48:35.508 homeassistant kernel: Booting Linux on physical CPU 0x0000000000 [0x410fd083]
2024-05-27 21:48:35.508 homeassistant kernel: Linux version 6.6.62-haos-raspi (builder@c7117cdb84dd) (aarch64-buildroot-linux-gnu-gcc.br_real (Buildroot -g00e8f093) 12.4.0, GNU ld (GNU Binutils) 2.40) #1 SMP PREEMPT Mon Jan 27 11:34:57 UTC 2025
2024-05-27 21:48:35.508 homeassistant kernel: KASLR enabled
2024-05-27 21:48:35.508 homeassistant kernel: random: crng init done
2024-05-27 21:48:35.508 homeassistant kernel: Machine model: Raspberry Pi 4 Model B Rev 1.4
```
