### ISSUE TITLE
[BirdNET-Pi] Time zone reset to Europe default after each update

### ISSUE THREAD

**Issue by DemBones78** [alexbelgium/hassio-addons#1595]
### Description

Time zone reset to Europe after each update
this messes up logs and birdnet reporting

### Reproduction steps

```bash
1. have a different time zone set from default
2. update and walk away
3. discover all your recording times are wrong
4. See error
```

### Addon Logs

```bash
thanks for the good work , i donated via paypal.
```

### Architecture

amd64

### OS

HAos

**Comment by DemBones78** [comment]
![Capture2](https://github.com/user-attachments/assets/f0a59978-119e-45ad-8527-24049f838502)

**Comment by alexbelgium** [comment]
Thanks excellent point. I'll look how to solve this before next release (that adds to the feature of highlighting new species seen in the overview page)

**Comment by alexbelgium** [comment]
Thanks very much for the kind words and donation!

**Comment by alexbelgium** [comment]
There was an issue with v95 I'm pushing v96
