### ISSUE TITLE
[enedisgateway] Build error

### ISSUE THREAD

**Issue by edouardkleinhans** [alexbelgium/hassio-addons#160]
**Which addon?**

* Addon name : enedisgateway
* Addon version : 0.7.7

**Describe the bug**

Install failed on build phase

**To Reproduce**

**Full addon log**
22-01-14 06:01:35 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build db21ed7f/amd64-addon-enedisgateway2mqtt:0.7.7: The command '/bin/sh -c if ! command -v bash >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends bash || apk add --no-cache bash); fi &&     if ! command -v curl >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends curl || apk add --no-cache curl); fi &&     mkdir -p /tmpscripts /etc/cont-init.d &&     for scripts in $MODULES; do curl -L -f -s "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/zzz_templates/$scripts" -o /tmpscripts/"$scripts"; done  &&     if [ -d /etc/cont-init.d ]; then /bin/cp -rf /tmpscripts/* /etc/cont-init.d/ && chmod -R 755 /etc/cont-init.d; fi &&     if [ -d /scripts ]; then /bin/cp -rf /tmpscripts/* /scripts/ && chmod -R 755 /scripts; fi &&     rm -rf /tmpscripts || printf '%s\n' "${MODULES:-}" > /MODULESFILE' returned a non-zero code: 2
22-01-14 06:01:35 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log: 
Step 1/25 : ARG BUILD_UPSTREAM="0.7.7"
Step 2/25 : FROM m4dm4rtig4n/enedisgateway2mqtt:$BUILD_UPSTREAM
 ---> 40332410aaf6
Step 3/25 : COPY rootfs/ /
 ---> Using cache
 ---> af6d63d3bea8
Step 4/25 : ARG MODULES="00-banner.sh 00-global_var.sh"
 ---> Using cache
 ---> 5ebb4a34b02c
Step 5/25 : RUN if ! command -v bash >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends bash || apk add --no-cache bash); fi &&     if ! command -v curl >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends curl || apk add --no-cache curl); fi &&     mkdir -p /tmpscripts /etc/cont-init.d &&     for scripts in $MODULES; do curl -L -f -s "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/zzz_templates/$scripts" -o /tmpscripts/"$scripts"; done  &&     if [ -d /etc/cont-init.d ]; then /bin/cp -rf /tmpscripts/* /etc/cont-init.d/ && chmod -R 755 /etc/cont-init.d; fi &&     if [ -d /scripts ]; then /bin/cp -rf /tmpscripts/* /scripts/ && chmod -R 755 /scripts; fi &&     rm -rf /tmpscripts || printf '%s\n' "${MODULES:-}" > /MODULESFILE
 ---> Running in a3706c000156
/bin/sh: 1: Syntax error: "then" unexpected

Removing intermediate container a3706c000156

**Full addon config**

**System**

* Supervisor version: supervisor-2021.12.2
* Host system version:   Home Assistant OS 7.1

**Comment by alexbelgium** [comment]
Thanks! I did an automated change that makes all addon fail to install ;) I'll push a new version with correction in 2 hours

**Comment by alexbelgium** [comment]
Version 0.7.7-2 will work, thanks for reporting
