### ISSUE TITLE
🐛 [resiliosync] Changed settings are not used by add-on

### ISSUE THREAD

**Issue by carlba** [alexbelgium/hassio-addons#1611]
### Description

The settings for `config_location`, `data_location` and `downloads_location` only seems to persisted the first time the add-on is started. If they are changed and the add-on is restarted the initial values are used. 

### Reproduction steps

```bash
1. Install the add-on and start it without making any config changes.
2. Make some config changes and restart the add-on.

Expected Result:
The changes are used by Resilio

Actual Result:

The initial values from the first Add-on Start are used.
```

### Addon Logs

```bash
The logs are not relevant here as this error is more of the silent type.
```

### Architecture

armv7

### OS

HAos

**Comment by martinlanger90** [comment]
Can confirm this. Tried a lot of times to change data location. Didn't do anything until I found out to remove Resilio and install it again then set data location and then start.
