### ISSUE TITLE
🐛 [jellyseerr] Action failed and build unavailable

### ISSUE THREAD

**Issue by override80** [alexbelgium/hassio-addons#1612]
### Description

Hi @alexbelgium,

Since the drop of arm64 in latest jellyseerr, the github action is failing and do the addon fails to install due to "Manifest unknown".

Guess you should drop the arm64 build from the action for now.

### Reproduction steps

```bash
Try to update/install to latest jellyseerr addon
```

### Addon Logs

```bash
Not required
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by alexbelgium** [comment]
Hi, done! Thanks

**Comment by override80** [comment]
Thank you @alexbelgium
