### ISSUE TITLE
❓ [*Arr] Updrade add-ons

### ISSUE THREAD

**Issue by storm1er** [alexbelgium/hassio-addons#1616]
**Which addon?**

All *arr addons, but may apply to all existing addons in this repo.

**Addon or app?**

Addon

**Describe the solution you'd like**

Either automated or a step by step in README on how to upgrade add ons to there latest available upstream version 

**Describe alternatives you've considered**

Clone this repo and rebuild all images, but it would be time consuming and loose the community aspect of this repo

**Additional context**

Especially about tdarr: there's unmapped node now and it would be very useful, but it's unavailable due to obsolete addon version

https://docs.tdarr.io/docs/nodes/nodes

**Comment by alexbelgium** [comment]
Updates is automatically done every Saturday if the upstream image has a functional nomenclature for releases.

**Comment by storm1er** [comment]
Well then maybe there's an issue

2.00.25 has been released on 9th August 2023

maybe there release nomenclature is wrong? Can you explain more on that? I'm aware of semver, and there version does not really match this (double digit `00`?)

I see the tdarr addon has been updated, thanks =)
