### ISSUE TITLE
fireflyiii addon missed cron schedule 

### ISSUE THREAD

**Issue by michelebossa** [alexbelgium/hassio-addons#162]
Addon name : fireflyiii
Addon version : 5.6.10

**Describe the bug**
Into guide of firefly-iii it indicated to schedule a  cron job every day to handle the "Recurring transactions." there is the possibility to add during the creation of container the cron installation plus the adding of schedule?

<img width="541" alt="image" src="https://user-images.githubusercontent.com/38975058/149496881-698c3aaf-eebb-47ec-8e50-a10f2c67d9a0.png">

Thanks a lot for the help.

  System

Supervisor version: supervisor-2021.12.2
Host system version: core-2021.12.9

**Comment by alexbelgium** [comment]
Thanks I'll look at it

**Comment by alexbelgium** [comment]
Hi, new version with selectable option for hourly, weekly and monthly update

**Comment by alexbelgium** [comment]
I've pulled it back for the moment as there is a weird bug of sqlite database not found even though it is there...

**Comment by alexbelgium** [comment]
I can't understand it... do you also use sqlite, and also have an error 500 on opening the web page?

**Comment by alexbelgium** [comment]
Did v5.6.10 was working for you with sqlite before?

**Comment by michelebossa** [comment]
Hi,
Sorry bur i m using Maria db without any issue anyway i have already installed the 5.6.10-2. I'm setting an automation for tomorrow to test I it is work. I'll give you a feedback.(at what time will be triggered?)
About the issue on sql lite I can't test because i don't use i hope was something easy to fix.

Thanks a lot

**Comment by alexbelgium** [comment]
Thanks! No idea I think 00 the easiest is to set it on hourly and see how it goes :)

**Comment by alexbelgium** [comment]
I had to dl several test with the sqlite issue so I hope you didn't install an intermediate version. To be sure I'll push a v3 now

**Comment by alexbelgium** [comment]
ok all should work now :-)

**Comment by michelebossa** [comment]
This morning my schedule transaction didn't work i have checked inside container and i found nothing strange

The time was every dai at 6:25
<img width="666" alt="image" src="https://user-images.githubusercontent.com/38975058/149654440-cbcc2466-f905-42d2-97e5-d3b349185fda.png">

/etc/cron.daily/cronupdate it is correct 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/38975058/149654464-1a6d77ee-ab10-47b2-b5f5-67c8409f6dc5.png">

i have tried to do manually the command and it is worked .
/usr/local/bin/php /var/www/html/artisan firefly:cron

The bad part was this morning with last version i'm having the error if i update something very very sad
<img width="734" alt="image" src="https://user-images.githubusercontent.com/38975058/149654646-32f502cb-2d1e-4c18-846e-217591dd2f79.png">

Can i made something?
Thanks.

**Comment by alexbelgium** [comment]
thanks I see the issue and will update. It will restore function

**Comment by alexbelgium** [comment]
should be good now. perhaps it's due to the permissions issue, could you please tell me how it goes ? thanks

**Comment by michelebossa** [comment]
I have update and now i have no error about the permission. Tomorrow morning I hope the job will be triggered i'll give you a feedback thanks a lot.

**Comment by michelebossa** [comment]
Hi,
i have recived a mail of scheduled moviment this morning :)
<img width="454" alt="image" src="https://user-images.githubusercontent.com/38975058/149729617-2417b722-62cb-4d83-9447-449a1f1a7747.png">

But  i have another permession issue i hope was the last (yesterday i write and update a lot of transaction without any trouble)
<img width="530" alt="image" src="https://user-images.githubusercontent.com/38975058/149729851-ce6cf9bd-d548-4396-a586-92f8e53cac30.png">
Can you please check?
Thanks.

**Comment by alexbelgium** [comment]
Great news for the cron job :-) So it's working then

For the permissions, I'll add a recurrent update to the cron job then... strange!

**Comment by alexbelgium** [comment]
new version pushed. I think it's because cron runs as root

**Comment by michelebossa** [comment]
It is worked no issue on Permission now . i hope in the future all schedule will be called will see. many many thanks for the help

**Comment by alexbelgium** [comment]
I pushed a new version with a better code : cron runs with www-data instead of manually resetting all permission, could you please test? thanks!!!

**Comment by alexbelgium** [comment]
I pushed again a new version that should work better

**Comment by michelebossa** [comment]
Ok i have installed the 5.6.10-4 i'll came back if some problem occurs.. thanks

**Comment by alexbelgium** [comment]
Thanks!

**Comment by alexbelgium** [comment]
If we want to add a message saying the cron job run we must redirect output to ```> /proc/1/fd/1```

**Comment by alexbelgium** [comment]
uh... I meant : it should now provide lo**g**s

**Comment by alexbelgium** [comment]
I've pushed a new version, should be good : Firefly version-0.8.0-4 ; Data Importer 5.6.14-3

**Comment by alexbelgium** [comment]
Confirmed to work on another thread :)
