### ISSUE TITLE
🐛 [birdnet-pi] build failed

### ISSUE THREAD

**Issue by allanpersson** [alexbelgium/hassio-addons#1620]
### Description

The latest build https://github.com/alexbelgium/hassio-addons/actions/runs/11541358429 failed, can't install addon due to missing manifest 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
https://github.com/alexbelgium/hassio-addons/actions/runs/11541358429
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Thanks ! I'll look at it. It is a quite minor version : it just incorporates the latest upstream changes including the backup feature (not needed in HA)

**Comment by alexbelgium** [comment]
New version pushed! BTW for info I'm not building anymore from Nachtzuster's branch directly but from a fork where I have listed here the additional elements : https://github.com/alexbelgium/BirdNET-Pi/blob/main/README.md

It is however fully compatible

**Comment by alexbelgium** [comment]
I'll try another approach

**Comment by alexbelgium** [comment]
Mmh not working too

**Comment by alexbelgium** [comment]
All good now!
