### ISSUE TITLE
❓ [addon] title

### ISSUE THREAD

**Issue by Sythsaz** [alexbelgium/hassio-addons#1621]
**Which addon?**

Whatsapper

name: Feature request
about: Suggest an idea for this project
title: 'Whatsapper"
labels: ''
assignees: ''

---

**Which addon?**

Whatsapper

**Addon or app?**

Addon

**Describe the solution you'd like**

Some docs on how to use it as it's hard to go down the rabbit hole of figuring it all out based on the image.

**Describe alternatives you've considered**

**Additional context**

Just trying to figure out how to add the notifier and can't find out based on the two repo's that this is based off of on how to set it up and start using it. Can't find anything in either "https://github.com/baldarn/whatsapper" or "https://github.com/pedroslopez/whatsapp-web.js" without diving into the files on how the whole system works. Thanks

**Comment by alexbelgium** [comment]
Hi @baldarn, if you have some time there is a request for additional informations! Perhaps it exists but as I'm not an user I thought you could have an answer more precise than me :) thanks!

**Comment by baldarn** [comment]
@alexbelgium you can assign this to me. i will do my best to do something

@Sythsaz what problem are you having? did you succeed configuring the notifier?

**Comment by baldarn** [comment]
@Sythsaz can you try following the instructions I posted now?
