### ISSUE TITLE
❓ [Nextcloud] Stuck on 28.0.0

### ISSUE THREAD

**Issue by hank-droid** [alexbelgium/hassio-addons#1623]
**Nextcloud**

I am stuck on 28.0.0 version. the update available is 30. if I update to 30, the data cannot be updated because is 2 major version below.

do you have any suggestion on how to get to 29 and then to 30? I have portainer and filebrowser addon.Ii have tried via portainer to redeploy the image with 29, but did not work.

thank you in advance for any support / pointer

**Comment by alexbelgium** [comment]
Hi, did you solve it? You can manually install a specific add-on version directly from the github package list by executing a shell command in the ssh & web terminal addon

**Comment by hank-droid** [comment]
Yes I solved it by reinstalling Nextcloud add-on with the same database credentials (mariadb) and same folder.
But if you can point me to a guide on how to do that, it will definitely be useful for me in the future 😀

**Comment by alexbelgium** [comment]
In theory with addon 3.0 for example you could remove the initial image `docker rmi ghcr.io/alexbelgium/nextcloud-amd64:3.0`, pull an image with `docker pull ghcr.io/alexbelgium/nextcloud-amd64:2.8`, then rename the image to the expected one with `docker tag ghcr.io/alexbelgium/nextcloud-amd64:2.8 ghcr.io/alexbelgium/nextcloud-amd64:3.0` and restart the addon

Then after running it, you remove again the newly created image and run `ha su repair` to make sure HA downloads the latest version

I haven't tested it but it should work, anyway the most important thing is that the addon is now working for you
