### ISSUE TITLE
🐛 [Mealie] Recipes gon

### ISSUE THREAD

**Issue by skank01** [alexbelgium/hassio-addons#1628]
### Description

Hi
I installed mealie some time ago and added some recipes.
Then suddenly the addon stopped working.
I now finally have time and updated the addon and started it again..
I dunno why but it wouldnt start until now..
BUT
It seems i have to start over? Cause he doesnt recognize my account, and all my recipes are gone although i can see folders under recipes.
What do i need to do, to get it all back?

Thx!

### Reproduction steps

```bash
None
```

### Addon Logs

```bash
none
```

**Comment by alexbelgium** [comment]
Hi, in theory the easiest way is : in the Filebrowser addon, delete the folder named /addon_configs/x-mealie, and delete the file /homeassistant/addons_config/mealie/migrated (or its the folder mealie_data) then restart the add-on.

If you had a valid installation, it would migrate your data in the new version.

If you want to delete EVERYTHING and start clean, delete (or rename) /addon_configs/x-mealie and /homeassistant/addons_config/mealie(or mealie_data) and restart

**Comment by skank01** [comment]
Mmm doesnt seem to work after i deleted those folders, he says "it looks like you try to log in for the first time"

**Comment by alexbelgium** [comment]
Do you mean after :
- Redo migration : delete the folder named /addon_configs/x-mealie, and delete the file /homeassistant/addons_config/mealie/migrated (or its the folder mealie_data) then restart the add-on
or
- Clean install : delete all folders (/addon_configs/x-mealie and /homeassistant/addons_config/mealie(or mealie_data) and restart)

For clean install it is normal, however if you had a working mealie instance, redoing the migration should have worked. Or else it was not a valid instance - if you have a full backup from some time ago, you could untar it and extract the folders mealie and mealie_data from it, then put them back in the /homeassistant/addons_config folder to redo the migration

**Comment by skank01** [comment]
Im just gonna start over, nevermind it.
What i also would like to do…
Is it possible to have a button in the addon so i can cast the recipe to one of my google hub speaker?
