### ISSUE TITLE
🐛 [linkwarden] <Needs update to latest version 2.8.x>

### ISSUE THREAD

**Issue by b52src** [alexbelgium/hassio-addons#1634]
### Description

Description
The Home Assistant Addon is not using the latest image.
See here current tags:
https://github.com/linkwarden/linkwarden/releases
Please switch to latest 🙏

Reproduction steps
1. Install the HA addon

Architecture
x86

OS
HAos

### Reproduction steps

```bash
Reproduction steps
1. Install the HA addon
```

### Addon Logs

```bash
NA
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, updates are on Saturday
