### ISSUE TITLE
🐛 [mealie] Addon OIDC redirects no longer work in 2.2.0

### ISSUE THREAD

**Issue by BlackHoleFox** [alexbelgium/hassio-addons#1636]
### Description

Hiyo o/. I tried updating from 2.1.0 to 2.2.0 tonight but something changed in the addon's internal NGINX configuration that broke my OIDC setup, which was relies on a dedicated NGINX addon to route traffic. This resulted in one of two behaviors:
- If I direct traffic to `http://mealie:9000` then I get a broken webpage. Something changed that causes NGINX to return the same HTML file for every request, even for the `.js` files, so nothing loads.
    - There are several `Uncaught SyntaxError: expected expression, got '<'` errors in the console and all network requests just return the same `index.html`.
    -  This was my existing config, which I think changed to talk to the Mealie server directly instead of the addon's internal NGINX (therefore busting it).
- If I direct traffic to `http://mealie:9001`, the addon's new official port, then redirect URIs completely break. This looks to have been caused by the additions made in the `#Improve ip handling` sections that rewrite headers. From what I see, these are breaking my own header configurations. The end result is that the Mealie server sees all requests with a source of `localhost:9000` instead of `mealie.my.domain`, so it [then constructs](https://github.com/mealie-recipes/mealie/blob/172698afce1f72e8200f302dece54555aaa707a8/mealie/routes/auth/auth.py#L114) a broken OIDC callback `redirect_url` that is rejected.

This is my dedicated NGINX addon header config for reference. Their purpose is to make Mealie see requests come from my domain and not any `localhost`. 
```nginx
proxy_redirect off;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Ssl on;
```

In theory a new configuration flag to turn off all of the newly added proxy header and path filtering configuration would fix the problem.

### Reproduction steps

These steps are a little bit complicated, sorry. Happy to test out any beta fixes or work with you to debug this further with my setup as a result.

1. Configure an OIDC provider somewhere.
2. Configure the mealie addon 2.2.0 to use OIDC for signing in.
3. Configure an external NGINX server to be the ingress for both mealie and OIDC. The important one for Mealie should look like this:

```nginx
server {
    listen 443 ssl;
    http2 on;
    server_name mealie.your.domain;

    ssl_certificate ....;
    ssl_certificate_key ....;

    client_max_body_size 0;

    location / {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;

        proxy_pass http://db21ed7f-mealie:9001;
    }
}
```

4. Start the mealie addon
5. Open `mealie.your.domain` and click the OIDC signin button.
6. See that it breaks with an "unknown redirect_url" error in mealie, your browser console, the OIDC provider's logs, etc. Inside the redirect URL, you'll see `localhost:9000` where you expect a real domain:
```
https://auth.your.domain/api/oidc/authorization?response_type=code&client_id=rand&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Flogin&scope=openid+email+profile+groups&state=
```

### Addon Logs

```bash
No error logs appear in the addon logs because the OIDC state redirect is sent from Mealie to the browser client. Mealie generated a bad `redirect_url` but that's not an error to create.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, sorry for short answer I'll check a bit later. Indeed, there is now a default sub_path of /mealie/ that is applied in order to use ingress. On the webui, it automatically redirects but perhaps not with OIDC? Please try appending the /mealie subpath hopefully it could already help

**Comment by BlackHoleFox** [comment]
I tried adding `/mealie/` to the NGINX `proxy_pass` path but it didn't work with either of the ports. The behavior remained the same for port `9000` and resulted in extra loading failures if I switched to `9001` due to `NS_ERROR_CORRUPTED_CONTENT` in my browser.

Without adding any suffix, and using port `9000`, the requests look like they make it to the Mealie container under the correct URI because something is happily serving `/mealie/foobar` back according to the logs:
![image](https://github.com/user-attachments/assets/1ebb27dc-ed2a-4555-ae0c-40e0f32aa6e5)

**Comment by krconv** [comment]
I ran into the same issue when first setting this up. Not familiar with best practices, but got it working with this nginx `.conf` file
```conf
    server {
        server_name recipes.mydomain.com;

        ssl_certificate /ssl/fullchain.pem;
        ssl_certificate_key /ssl/privkey.pem;

        # dhparams file
        ssl_dhparam /data/dhparams.pem;

        listen 443 ssl http2;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

	location / {
            proxy_pass http://db21ed7f-mealie:9000;
	}
	location /mealie/ {
            proxy_pass http://db21ed7f-mealie:9000/;
	}
    }
```

**Comment by BlackHoleFox** [comment]
Oh very nice, thanks for discovering that @krconv. I tried on my NGINX addon and it worked with a small addition (still a simplification from my previous directives):
```nginx
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto $scheme;

location / {    
   proxy_pass http://db21ed7f-mealie:9000;
}

location /mealie/ {
    proxy_pass http://db21ed7f-mealie:9000/;
}
```

Without `X-Forwarded-Proto` it tries setting the redirect URI to an `http://` version of my domain, which the OIDC provider rejects because I specified the expected one to be `https://`. Then without `Host` it tries setting the redirect URI to `http://db21ed7f-mealie:9000`. Unclear why your setup works without them but I might have something elsewhere in my setup causing the behavior difference.

Everything is now working on the latest Mealie addon version, so happy to close this as completed now that I (and others coming later) have a validated configuration update.
