### ISSUE TITLE
❓ [Nextcloud] Consider moving data to addon_config directory

### ISSUE THREAD

**Issue by paviro** [alexbelgium/hassio-addons#1645]
**Which addon?**

name: Feature request
about: Consider moving data to addon_config directory

---

**Which addon?**

Nextcloud addon

**Addon or app?**

Addon

**Describe the solution you'd like**

Hi!
Historically it has been nice to be able to access the data folder via the share folder but when having multiple addons that store there data there (Paperless does too for example) it's impossible to create a clean snapshot only containing all Nextcloud data.

If I for example want to create a daily backup of my Paperless documents but only a weekly one of Nextcloud this is currently impossible which is unfortunate as both contain huge amounts of data.

I think it would be good to consider moving the Nextcloud data into the addon_config directory so a clean snapshot can be created.

Best,
Paul

**Comment by paviro** [comment]
Solved this by not backing up the share folder at all in snapshots and instead backing it up separately which is even cleaner and doesn't create huge snapshots.

**Comment by alexbelgium** [comment]
Hi, thanks actually it is the default data location but people can use whatever they want!

For example for me I'm using an external USB drive as data location. It is way more secure and stable. I am using a script to periodically snapshot my external HDD content on an another drive.

Indeed a you mention if we were using the /config folder it would lead to potentially huge snapshots also
