### ISSUE TITLE
[jellyfin] Add support for OpenMAX OMX hardware acceleration

### ISSUE THREAD

**Issue by wsz34** [alexbelgium/hassio-addons#165]
**Which addon?**
Jellyfin

**Is your feature request related to a problem? Please describe.**
I wanted to test OpenMAX OMX hardware acceleration, but found that /opt/vc/lib volume is not mapped to Docker container, so openmax lib loading is skipped in https://github.com/linuxserver/docker-jellyfin/blob/master/root/etc/cont-init.d/40-gid-video

**Describe the solution you'd like**
Add /opt/vc/lib volume mount

**Additional context**
Is there any other way to mount volume manually after installing this add-on? It seems that Docker does not support it.

**Comment by alexbelgium** [comment]
Hi, I don't think that HA supports this in its config files...

**Comment by alexbelgium** [comment]
Indeed, looks like it is not supported https://community.home-assistant.io/t/ffmpeg-provided-in-hass-io-compiled-with-gpu-hardware-acceleration-mmal-omx-or-not/112427/2

Unless someone says otherwise, I'll have to close this as I don't think there is a technical solution

**Comment by wsz34** [comment]
Jellyfin has its own ffmpeg as I understand (at /usr/lib/jellyfin-ffmpeg/ffmpeg), so not sure if that would be an issue. From my understanding only volume binding is missing

**Comment by alexbelgium** [comment]
I think volume binding is only done through HA's own system in config.json file, which doesn't support custom elements. Just to check, I'll add it both to dockerfile and apparmor it in a version I'll push in a couple minutes. If you can tell me if it works it would be great. Thanks

**Comment by wsz34** [comment]
Thank you, I have tried new version without any luck. Folder /opt/vc/lib is now available in Docker container, but it is empty. As the problem is clear to me now, I have tried to look for the solution, but was not able to find anything.

**Comment by alexbelgium** [comment]
Thanks, I'll revert the changes but don't hesitate to re-open if you think there is a technical solution. Bottom line, I think those are rpi specific drivers and not available in HA os as they are multi devices and not specific to rpi...

**Comment by alexbelgium** [comment]
I tried a force install of the mesa drivers in dockerfile, and pushed a new besoin, would it work?

**Comment by wsz34** [comment]
I am not sure which hardware accelerator I should choose, but doubt that Raspberry Pi supports it. Meanwhile did some tests with pure Docker Jellyfin container, only pretty old versions (e g. 10.4.3) worked anyway, so there is no need to force it to work. Thank you for your help, though

**Comment by alexbelgium** [comment]
Great, thanks for your feedback! Sorry it didn't work but honestly I'm running emby on rpi (3 then 4) and I wouldn't anyway use hardware accelerator for transcoding... I only use direct transfer and it works very well
