### ISSUE TITLE
🐛 [immich] Database backup wrong version

### ISSUE THREAD

**Issue by franortiz** [alexbelgium/hassio-addons#1659]
### Description

immich addon version: 1.122.1-3

Built in database dump feature not working it seems script is looking for wrong DB version 15   but version 16 is builtin

```
root@db21ed7f-immich:/# ls -l  /usr/lib/postgresql
total 4
drwxr-xr-x 4 root root 4096 Nov 23 18:42 16
root@db21ed7f-immich:/# ls -l  /usr/lib/postgresql/16/
bin/ lib/ 
```

### Reproduction steps

```bash
- Enable builtin database dump backup
- Wait for backup time
- Check logs
```

### Addon Logs

```bash
[Nest] 1074  - 12/09/2024, 12:08:46 AM     LOG [Microservices:VersionService] Found v1.122.2, released at 12/8/2024, 8:50:55 PM
[Nest] 1074  - 12/09/2024, 2:00:00 AM     LOG [Microservices:BackupService] Database Backup Starting. Database Version: 15
[Nest] 1074  - 12/09/2024, 2:00:00 AM   ERROR [Microservices:Error: spawn /usr/lib/postgresql/15/bin/pg_dumpall ENOENT] Backup failed with error
[Nest] 1074  - 12/09/2024, 2:00:00 AM   ERROR [Microservices:Error: spawn /usr/lib/postgresql/15/bin/pg_dumpall ENOENT] Database Backup Failure
[Nest] 1074  - 12/09/2024, 2:00:00 AM   ERROR [Microservices:BackupService] Gzip exited with code 0 but pgdump exited with -2
```

**Comment by alexbelgium** [comment]
Hi, I don't understand as I thought postgres wasn't built in and immich relied on an external container?

**Comment by Foshkey** [comment]
It seems that the immich container still has a postgresql client installed (as indicated in the description) and uses this client (specifically `pg_dump`) to run a backup of the database. But this command is really picky with versions, and the immich container has client v16 installed but the postgresql addon runs postgresql 15

**Comment by alexbelgium** [comment]
I've tried to force the client to 15 to test. Was it working before though? It seems to dump a local folder which would be useless with an external database? Isn't it better to rely on backups of the postgres container to align with other methods of backups?

**Comment by Foshkey** [comment]
> Was it working before though?

I personally haven't been using it for long but it's never worked for me.

> It seems to dump a local folder which would be useless with an external database?

I still find it useful considering you can use that file with `pg_restore` on the database. See [documentation](https://www.postgresql.org/docs/current/app-pgdump.html).

> Isn't it better to rely on backups of the postgres container to align with other methods of backups?

While I don't disagree, this is ultimately a feature of Immich that is broken. It's also worth noting that it'll only back up the `immich` database, not all of the postgres container. Considering Immich is the creator of the `immich` database, one could argue that it should also handle the backups.

On a more personal note, this database gets _big_ with a lot of photos in Immich. I'm already at 500MB with ~300GB of photos. I'd like the option to move this backup to live alongside my photos (which has its own backup) and exclude it from my google drive backup so it's not taking up so much space.

And, this is just an opinion, but in general I think the client version should ideally match the database version.

**Comment by alexbelgium** [comment]
I've modified references to postgres 16 in immich init script and forced installed the PostgreSQL 15 client. Does the latest version work?

**Comment by Foshkey** [comment]
Unfortunately it seems the `amd64` build failed? 🤔

```
Can't install ghcr.io/alexbelgium/immich-amd64:1.122.1-3test3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=1.122.1-3test3&fromImage=ghcr.io%2Falexbelgium%2Fimmich-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
```

**Comment by alexbelgium** [comment]
I've pushed a v4 for which build succeeded please tell me how it goes!

**Comment by Foshkey** [comment]
It's working for me! Thanks so much!

**Comment by alexbelgium** [comment]
Perfect! Thanks for the feedback
