### ISSUE TITLE
[Portainer] Stopped containers are not listed and visible

### ISSUE THREAD

**Issue by Salvora** [alexbelgium/hassio-addons#166]
**Which addon?**

* Addon name : Portainer 
* Addon version : 2.11.0-3 

**Describe the bug**
When an addon is running portainer lists the running container which is normal but when you stop an addon, portainer does not list show the stopped container. Tested with Adguard home and aircast. Is this a limitation for the addon?

**To Reproduce**
1. Stop an addon
2. Search the container of the addon on in the portainer container list
3. It is not there

**Full addon log**

**Full addon config**

**System**

* Supervisor version: supervisor-2021.12.2
* Host system version: Home Assistant OS 7.1

**Comment by alexbelgium** [comment]
Hi, actually it's the way HA works : it recreates containers at each stop & restart from a single image. When I look in my own portainer I can see stopped containers (although it is not useful since they will get deleted at next reboot).

**Comment by alexbelgium** [comment]
I'll close it as it seems more a local configuration and not due to the addon as such... Don't hesitate to continue the thread here I'll still read & reply to the messages
