### ISSUE TITLE
Question about connecting

### ISSUE THREAD

**Issue by Golab** [alexbelgium/hassio-addons#167]
Hello I’m wondering can I use this app to connect to it? https://servediter.app/

is the server setup so it can revive connections from code editors? I’m using iPad

**Comment by alexbelgium** [comment]
Hi, could you please precise the addon for which you are asking the question? 

Also I create the addon and can answer any question related to its usage, but for questions on the app itself it is best to check the initial app documentation (I usually provide the link on the Readme), as I create npbut actually don't use most of the addons.

Thanks!

**Comment by alexbelgium** [comment]
ah - codeserver :-)

No idea at all... but do you know that you can access vscode directly from vscode.dev ?

For example, https://vscode.dev/https://github.com/alexbelgium/hassio-addons allows running vscode (most extensions are compatible) in your web app

**Comment by alexbelgium** [comment]
No idea at all... It is said "It's also possible to use this app for free by using a self hosted instance of code-server." so actually you could try and post the result here if it can help other people!

Btw do you know that you can access vscode directly from vscode.dev ? For example, https://vscode.dev/https://github.com/alexbelgium/hassio-addons allows running vscode (most extensions are compatible) in your web app
