### ISSUE TITLE
🐛 [Firefly iii FinTS Importer] Update base image please

### ISSUE THREAD

**Issue by baflo** [alexbelgium/hassio-addons#1677]
### Description

The current version is breaking because of changes in the APIs of a couple of banks. The base image [has already fixed this issue](https://github.com/bnw/firefly-iii-fints-importer/pull/145). Please update 🙏

### Reproduction steps

```bash
n.a.
```

### Addon Logs

```bash
n.a.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Automatic updates are every Saturday. If it didn't work I'll do it manually

**Comment by baflo** [comment]
The latest image of the fints-importer seems to be 3 months old and it contains the fix. 
At least for me, the addon didnt work anymore. Yesterday,  forked your addons and rebuilt the image myself which wirkend then.
But might be that it somehow just did not pull your update correctly before. I'll try again tonight.

**Comment by alexbelgium** [comment]
Thanks! Pushed

**Comment by eifinger** [comment]
@alexbelgium I found this issue because I started the addon for the first time and found out it is out of date, it is missing features which are available if I use the base image directly. Can you force an update again? Thank you!

**Comment by alexbelgium** [comment]
Hi indeed I don’t see a versioning on fints importer which means that the automated updates can’t see them. I’ll do a manual update

**Comment by eifinger** [comment]
Yeah there are no git tags, no github releases and the docker image is only the latest tag which gets updated. Would it be an option to track the hash of the docker image since last update?

Thank you for your work!

**Comment by alexbelgium** [comment]
Hi, I'll try that
