### ISSUE TITLE
Emby NAS Warning log: Add-on have full device access....in the configuration

### ISSUE THREAD

**Issue by duceduc** [alexbelgium/hassio-addons#17]
I am noticing this warning in the Supervisor log. Not sure why it is showing up since I have never installed the add-on.

>Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Emby NAS

![120061184-fb610900-c096-11eb-8332-2e80cf4e05cb](https://user-images.githubusercontent.com/20457723/120118786-4aaa5500-c1cf-11eb-8b39-a1da67f8a4a1.jpg)

![120061191-0156ea00-c097-11eb-8e74-6fdf86758be2](https://user-images.githubusercontent.com/20457723/120118788-4d0caf00-c1cf-11eb-8d41-1af08498cf86.jpg)

**Comment by alexbelgium** [comment]
Thanks! When the supervisor refreshes the addons repos, it checks them for any potential issues. Here the error message is on purpose. In my emby addon, either people can mount smb drives while keeping priviledged mode off, or they can mount local drives if they disable it. So you can safely ignore this message.

Thanks for reporting!

**Comment by duceduc** [comment]
ok. I see. Though it is misleading for anyone who has never installed the add-on seeing this warning and not knowing what to do.
