### ISSUE TITLE
[Jackett] Fails to install

### ISSUE THREAD

**Issue by wsz34** [alexbelgium/hassio-addons#170]
**Which addon?**

* Addon name : Jackett NAS
* Addon version : 0.20.371

**Describe the bug**

Fresh install of Jacket addon fails

**To Reproduce**

**Full addon log**

Can't install ghcr.io/alexbelgium/jackett-armv7:0.20.371: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.20.371&fromImage=ghcr.io%2Falexbelgium%2Fjackett-armv7: Internal Server Error ("Head "https://ghcr.io/v2/alexbelgium/jackett-armv7/manifests/0.20.371": denied")

**System**

* Supervisor version:  2021.12.2
* Host system version:  Raspbian 11, HA 2021.12.10

**Comment by alexbelgium** [comment]
I'm in the process of automating the builds it should arrive in around 30min and hopefully work :)

**Comment by alexbelgium** [comment]
On its working now, just tested it

**Comment by alexbelgium** [comment]
I deeply apologize. I enabled autobuild as recommended by the HA guidelines, and it brought 2 big issues :

    Multi-arch base images are not supported (it needs a pull --platform tag that is not implemented yet, and the system is very complex to fork and customize)
    Upgrade from a locally built addon to an autobuilt addon is not supported : the addon still tries to locally build and then provides a failure message as it doesn't find a local image...

I have decided to revert the changes. This means that everyone that has installed the new versions pushed since 2 days will have to restore a backup, or uninstall the app and reinstall it...

Thanks for your understanding.

**Comment by alexbelgium** [comment]
Closed as the source of the issue changed - local builds is back
