### ISSUE TITLE
[Firefly iii] [rpi4] doesn't launch at all

### ISSUE THREAD

**Issue by Stooovie** [alexbelgium/hassio-addons#171]
**Which addon?**

* Addon name : Firefly III
* Addon version : 5.6.10-4

**Describe the bug**
It doesn't start. I'm getting `[FATAL tini (8)] exec /usr/bin/env failed: Exec format error` and that's it. 

**To Reproduce**

* Supervisor version: 2021.12.2
* Host system version: Home Assistant OS 7.1 on RPi4

**Comment by alexbelgium** [comment]
Hi, thanks for reporting, I just pushed a new version that will fix that

**Comment by alexbelgium** [comment]
Ah no, it still doesn't work. I've got to investigate a bit more

**Comment by alexbelgium** [comment]
I'm sorry it's a bug with the HA builder script that is too complex for me to solve. I've reverted my change (autobuild) to make it work again. This means you need to uninstall completely the app, refresh the repositories, then install the new version available and it will work.

If you had already data, it should ne safe in your database. Or you can also restore a backup before updating

**Comment by Stooovie** [comment]
Addon seems to run but stops anyway complaining about lots of line lenght errors (even if it's copy/pasted/adjusted from the example YAML file in SublimeText and looks correct).

Don't worry about this too much, I wanted to try Firefly but it's not 100% required. Thanks!

`  315:25    error    no new line character at the end of file  (new-line-at-end-of-file)
[08:53:03] FATAL: Config file has an invalid yaml format. Please check the file in /config/addons_config/fireflyiii/config.yaml. Errors list above.
[08:53:03] INFO: Starting the app with the variables in in /config/addons_config/fireflyiii/config.yaml
/etc/cont-init.d/99-run.sh: executing
/.//etc/cont-init.d/99-run.sh: line 5: Ckq: unbound variable
/etc/cont-init.d/99-run.sh: exiting 1`

**Comment by alexbelgium** [comment]
Mmh... Have tried already running firefly iii without the config.yaml filled? It works on my system so it's strange... Indeed here what fails is the yamllint that checks you file and says that according to guidelines you should have a blank line at bottom of your file

**Comment by alexbelgium** [comment]
You can validate your yaml here : http://www.yamllint.com/

**Comment by alexbelgium** [comment]
Actually you don't need to fill the config.yaml to start and use the app

**Comment by Stooovie** [comment]
Yes, as I wrote in the OP, the Ckg: unbound variable error is present even when I remove the config.yaml and let the app regenerate it. Or when I don't do anything at all (and just supply the 32 char app key).

**Comment by alexbelgium** [comment]
Weird, I can't replicate that on my system... I'm also on rpi4 aarch64...

**Comment by alexbelgium** [comment]
Which database do you use? Sqlite?

**Comment by Stooovie** [comment]
I leave the config completely default, so "sqlite_internal". I just supply the app key.

**Comment by alexbelgium** [comment]
Very weird. I can replicate your yamllint error by removing the blank line at bottom of my yaml, but can't replicate the "Ckq: unbound variable" ; and I've got no variables named Ckq. And line 5 of run.sh is a comment starting by #... so weird error

**Comment by Stooovie** [comment]
HA Info says my CPU architecture is armv7l which is 32bit so maybe that's the issue? For some valid reasons I don't really recall I stuck to 32bit.

**Comment by alexbelgium** [comment]
most likely you installed HA os 32bit rpi4 image. At one time it was recommended as there were issues on the 64bit one. Now, the 64bit one is recommended. anyway armv7 images of the addons exist so it shouldn't be an issue...

**Comment by Stooovie** [comment]
Yes, this is my original install from back in 2019, I think it even originated on a RPi3.

I rebooted the host completely but the issue still stands. I guess I won't be using Firefly then :) Thanks for your time.

**Comment by alexbelgium** [comment]
I'm sorry about that. If I encounter the issue and find the cause I'll let you know here

**Comment by alexbelgium** [comment]
Hi, I had to change the way the addons are built. Could you please test again if you are still interested ? thanks !

**Comment by Stooovie** [comment]
Hey, whaddya know, it's working now! Thank you!

**Comment by alexbelgium** [comment]
Great news. I've corrected some codes. In the past days i had messed up several things, and corrected everything today. Thanks!
