### ISSUE TITLE
[Qbittorrent] openvpn connection leak actual ip address

### ISSUE THREAD

**Issue by tyjtyj** [alexbelgium/hassio-addons#172]
**Which addon?**

* Addon name : Qbittorrent
* Addon version : 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-4

**Describe the bug**

To protect public ip to be sent to tracker when using openvpn connection. 
Without it, the qbt will send all ip address to tracker, resulting leaking public ip address even openvpn is enabled

qbittorent.conf file
```
[BitTorrent]
Session\AnonymousModeEnabled=true


[Preferences]
Connection\Interface=tun0
Connection\InterfaceName=tun0
```
**To Reproduce**

Enable openvpn in setting and start the server. 
1. Under original qbt ui(not Vuetorrent UI), setting, advance tab, network interface is set to all interface. Should be tun0 when openvpn enabled. --This setting does NOT retained on restart
2. Under original qbt ui setting, BitTorrent tab, tick AnonymousMode --This setting does retained on restart

**Full addon log**

N/A
**Full addon config**

openvpn_enabled: true

**System**

* Supervisor version: 
* Host system version: 

Additional info.
This may be due to openvpn started AFTER qbt started. Reversing starting openvpn before qbt may retain the setting. I wasn't very sure.

**Comment by alexbelgium** [comment]
Thanks, actually if you click the alternative openvpn connection addon option you'll have the exact behaviour you want. I'll look at make it the default setting

**Comment by alexbelgium** [comment]
Please let me know if it works all right!

**Comment by alexbelgium** [comment]
Settings not being retained is if they are set on purpose by the addon options

**Comment by tyjtyj** [comment]
> Thanks, actually if you click the alternative openvpn connection addon option you'll have the exact behaviour you want. I'll look at make it the default setting


Thanks !!!
This seems to work... but i got some error. 
I dont really concern about it for now. i will test more if it give issue. seems to be cause by route-nopull which can be ignore.

Wed Jan 19 13:45:46 2022 Options error: option 'redirect-gateway' cannot be used in this context ([PUSH-OPTIONS])
Wed Jan 19 13:45:46 2022 Options error: option 'dhcp-option' cannot be used in this context ([PUSH-OPTIONS])
Wed Jan 19 13:45:46 2022 Options error: option 'route' cannot be used in this context ([PUSH-OPTIONS])

**Comment by alexbelgium** [comment]
Perhaps it's this code that was added to allow webui when tunnelling the whole addon : ```/usr/sbin/ip route add 10.0.0.0/8 via 172.30.32.1```

**Comment by tyjtyj** [comment]
Tested seems not leaking now.. other function seems to be work...
if there is anything else need to be fix..ignoring the error. 
we can close this

Again thx...

**Comment by alexbelgium** [comment]
Prefect, thanks!

**Comment by almico** [comment]
Which version of the addon has the fix?
I am currently unable to update.

**Comment by alexbelgium** [comment]
What is the error message? The versions from v3 up should have the fix (last number after the whole complex version name)

**Comment by almico** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/15247405/150638438-d91e8ec2-5ad5-477f-b7c1-7830a4ceea22.png)

I also tried to restart HA, but to no avail 😄

**Comment by tyjtyj** [comment]
Copy ur config in yaml. Uninstall then install again

Or just wait for next release

**Comment by alexbelgium** [comment]
Hi, that's indeed the issue from https://github.com/alexbelgium/hassio-addons/issues/177...

The only way is restore or uninstall reinstall. As all config is external (as described by tyjtyj), unlisted reinstalling should keep your settings (but not the elements being downloaded)

**Comment by almico** [comment]
> Copy ur config in yaml. Uninstall then install again
That did the trick. Thank you 😃

**Comment by alexbelgium** [comment]
Thanks Tyjtyj!
