### ISSUE TITLE
[Photoprism] Update/Install build error

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#173]
**Which addon?**

* Addon name : Photoprism
* Addon version :  20220118

**Describe the bug**

See output the new update with i think the build script produce this
`The command '/bin/sh -c mkdir -p /data/photoprism/originals /data/photoprism/import /data/photoprism/storage/config /data/photoprism/backup /data/photoprism/storage/cache && chmod -R 777 /data/photoprism chown -Rf photoprism:photoprism /data/photoprism && chmod -Rf a+rwx /data/photoprism && mv /entrypoint.sh /entrypoint_photoprism.sh' returned a non-zero code: 1`
**To Reproduce**

Just Install the new update that is provided in repo.
It will fail with above output

**Full addon log**

**Full addon config**

**System**

* Supervisor version: supervisor-2021.12.2 
* Host system version: core-2021.12.10

**Comment by alexbelgium** [comment]
Thanks, corrected in 20220118-2

**Comment by alexbelgium** [comment]
Tested and working, I'll close it to clean things ;-) Let me know here if there is any issues
