### ISSUE TITLE
[Nextcloud] Adapt nextcloud to work with this addon PDF Annotate

### ISSUE THREAD

**Issue by wakielo** [alexbelgium/hassio-addons#176]
Hi Alex!

Could you adapt our nextcloud to work with this addon? I tried install the pdf annotate addon with the app manager from nextcloud and it doesnt work... I found an addon adapted to work in nextcloud but I cant install it...

https://gitlab.com/nextcloud-other/nextcloud-annotate

**Comment by alexbelgium** [comment]
Hi, 

Well this is not an easy thing, as adding the code to the whole addon would mean that everyone would have it by default...

Do you know portainer? The easiest way would be to install the portainer addon, with which you can log as a console inside the nextcloud container and execute the command line script that is described in the page you linked... Let me know if you don't know it perhaps I can help.

I suppose it is this one you tried from nextcloud, https://apps.nextcloud.com/apps/pdfdraw, did you have a specific error message? perhaps it's easier to debug this one

Thanks!

**Comment by alexbelgium** [comment]
Mmh... it has several dependencies that are not available in alpine it seems, on which the addon is based. Not sure it is feasible

**Comment by alexbelgium** [comment]
I pushed the code that will install the app in the nextcloud docker per the instructions in the main addon, but I don't think it will work due to missing dependencies that don't exist on alpine. Could you please confirm if I need to remove it or keep it? thanks

**Comment by wakielo** [comment]
Hi alex!

Sorry for the delay, tried and no success

**Comment by alexbelgium** [comment]
Hi, I tried too but I don't think it is possible on this version of nextcloud built by linuxserver. Too many missing dependencies...

**Comment by nyok92** [comment]
@alexbelgium I think this commit which add this pdfannotate app is still part of the addon (last realease)
I got some errors on Nextcloud logs: 

`Certains répertoires d'applications appartiennent à un utilisateur différent de celui du serveur web. Cela peut être le cas si les applications ont été installées manuellement. Vérifiez les permissions des répertoires d'applications suivants : /app/www/public/apps/pdfannotate`

=> The script installs the app but not under the right owner so Nextcloud complains about this ownership.

Each time i unstinall it, i get rid of this warning but each time i reboot the nextcloud addon, the script installs again the pdf annotate app.

If this is not working for everyone, could you discard this Pdfannotate commit ? 
--> nextcloud/rootfs/etc/cont-init.d/99-add_packages.sh

Thanks
