### ISSUE TITLE
[Spotweb] addon

### ISSUE THREAD

**Issue by woutercoppens** [alexbelgium/hassio-addons#179]
Hi Alex,

Thanks a lot for this repository. It has saved me a lot of time. Great work.

I'm missing one thing in this repository: [Spotweb](https://github.com/spotweb/spotweb)

I have created an addon for Home Assistant: [https://github.com/woutercoppens/hassio-addons/tree/main/spotweb](https://github.com/woutercoppens/hassio-addons/tree/main/spotweb)
If you find it interesting, can you add it to your repo? More people can benefit from it. 

Regards,

W.

**Comment by alexbelgium** [comment]
Hi,

Thanks very much! Your addon is great, I had a look. It will be a pleasure to host it in my repo. I'll add it tomorrow.

However the only way I know is to fully copy paste all your files and add it to my github repo. Is it acceptable for you? Or do you see another way? I just want to be sure that ownership is rightfully attributed to you.

Best regards

**Comment by woutercoppens** [comment]
Hi Alex,

I think the easiest way to transfer it to your repo is indeed to copy the files. I have no idea how you can merge 2 repo's. 
Don't worry about the ownership. It's ok for me that other people can benefit from it, plus I don't have the time to maintain it. 

You'll probably have to update some links in the documentation that are still referring to my repo and add a version. 

W.

**Comment by alexbelgium** [comment]
Hi Wouter,

Thanks I'll add it to the repo then, and check the links 

Best regards,
Alex

**Comment by alexbelgium** [comment]
Thanks! It is now live here : https://github.com/alexbelgium/hassio-addons/tree/master/spotweb

It took the opportunity to align with my Dockerfile logic for easier maintenance, add autobuild to pre-build the main images, and add it to my script for auto-updates based on upstream releases.

Thanks again!
