### ISSUE TITLE
I cant mount my SMB Drive on Radarr

### ISSUE THREAD

**Issue by phgsbr** [alexbelgium/hassio-addons#18]
Hey! Thanks to the addon.

im trying to config radarr and i cant mount my Synology NAS folder. 
![Screenshot_1](https://user-images.githubusercontent.com/20521629/122417408-d65a0a80-cf5f-11eb-9fd3-72df31a079e8.png)
![Screenshot_2](https://user-images.githubusercontent.com/20521629/122417423-d954fb00-cf5f-11eb-85c4-6335ab2a9ef9.png)

i tried with ip number too. Im doing something wrong?

**Comment by alexbelgium** [comment]
Interesting issue. It's due to the \v. I'll modify the code and tell you
when next version is available!

**Comment by alexbelgium** [comment]
You can also try with //BRAINIAC/video if this works, while I modify the code

**Comment by alexbelgium** [comment]
Sorry, its a bit more complicated than I thought. For some reason, the character \v from \video is not accepted (you can see in the log there is an empty space instead) . I really don't see why but don't have much time yet to investigate... I'll do it as soon as possible. Meanwhile, a solution would be to rename your distant folder... 

Thanks for testing this addon!

**Comment by alexbelgium** [comment]
Ahah, I must be tired. The solution is easy. The format for url should be //BRAINIAC/video.

This will work! Thanks!

**Comment by phgsbr** [comment]
@alexbelgium thanks for the quick respose!

Now the log shows the correct adress, but still no mounting the volume. 
![Screenshot_3](https://user-images.githubusercontent.com/20521629/122473632-8186b600-cf98-11eb-970e-0ab261d99951.png)

**Comment by alexbelgium** [comment]
Hi, could you please try with ip instead ? Thanks!

**Comment by phgsbr** [comment]
> 
> 
> Hi, could you please try with ip instead ? Thanks!

Sure!

here is the result
![Screenshot_4](https://user-images.githubusercontent.com/20521629/122574036-9d846900-d025-11eb-8579-a18deb7d23ba.png)

**Comment by alexbelgium** [comment]
argh ;-) ok, next step : could you please try by checking the smbv1 checkbox in the addon options? 

thanks !

**Comment by phgsbr** [comment]
Where can i find this checkbox? 

my config screen just show this options:
![Screenshot_5](https://user-images.githubusercontent.com/20521629/122607357-d0902200-d050-11eb-82e4-14c0a17f8884.png)

**Comment by alexbelgium** [comment]
Ah indeed it's a config in yaml for this addon!

You need to type this, on the same level as UID (for example, so not indented) :
```
smbv1: true
```

**Comment by phgsbr** [comment]
Same result. Even with ip number. =(
![Screenshot_7](https://user-images.githubusercontent.com/20521629/122608566-d25ae500-d052-11eb-9424-d507a9f036ef.png)

**Comment by phgsbr** [comment]
@alexbelgium im wondering if i need to change something in NAS settings.

**Comment by alexbelgium** [comment]
Hi, sorry for not coming back to you! We had exhausted easy solutions ;) and I'm quite busy for the moment

By any chance have you installed my qbittorrent addon? It has a much improved smb code where I added the option to try different smb settings. If this works, I would port the code to this addon. 

Another solution would be to check that there are not smb settings in your host machine that prevents connection... Or else to try to mount it manually in the terminal addon to see what could cause the issue.

**Comment by alexbelgium** [comment]
Are you sure the address is //ip/video? You don't have an intermediate folder? On my system for example it's //ip/computername/foldername

Thanks!

**Comment by phgsbr** [comment]
> 
> 
> Hi, sorry for not coming back to you! We had exhausted easy solutions ;) and I'm quite busy for the moment
> 
> By any chance have you installed my qbittorrent addon? It has a much improved smb code where I added the option to try different smb settings. If this works, I would port the code to this addon.
> 
> Another solution would be to check that there are not smb settings in your host machine that prevents connection... Or else to try to mount it manually in the terminal addon to see what could cause the issue.

No problem, im very grateful for the help!

I installed qbittorrent addon now and seems like the mount works.
![Screenshot_8](https://user-images.githubusercontent.com/20521629/122807972-9e75fe80-d2a2-11eb-89d5-63885517e703.png)
And, in this way, works! I started a download, moving the path to folder configured in "/mnt/video" and bingo. The file folder was created in NAS. Unhappily, this mount cannot be seen on Radarr addon.

**Comment by phgsbr** [comment]
Could you port the code to Sonarr addon too?

**Comment by alexbelgium** [comment]
Perfect! Wow it's not a frequent smb type no wonder it didn't work straight away. I'll update radarr and sonarr right now :)

**Comment by alexbelgium** [comment]
Here it is, versions dev3 are online!

**Comment by phgsbr** [comment]
@alexbelgium  i need to update? Supervisor is not showing updates available.

**Comment by alexbelgium** [comment]
Supervisor refreshes every couple hours. You can force it by going in the addon store, click on the three dots at top right, then reload (second option). You'll see in supervisor log that it refreshes, and then you'll see all updates!

**Comment by phgsbr** [comment]
@alexbelgium Thank you so much! Radarr and Sonarr are working like a charm. Finally i can center all solutions on my RPi4 8Gb and give another job to my Rpi3. Please, continue with this very useful project!

Thank you again!
