### ISSUE TITLE
[addon] title

### ISSUE THREAD

**Issue by aLTeReGo-SWI** [alexbelgium/hassio-addons#186]
**Which addon?** File Browser

---
name: Change Port
about: Suggest an idea for this project
title: 'Change default Port for File Browser Add-on'
labels: ''
assignees: ''

---

**Which addon?**

File Browser

**Addon or app?**

Add-on

**Describe the solution you'd like**

The ability to change the default listening port from 8080, as 8080 is already in use.

**Describe alternatives you've considered**

I assumed since the addon used ingress that no listening ports would be required on the host.

**Additional context**

I already have another application utilizing port 8080 which is not changeable. This add-on should allow the user to change the port from the default of 8080 to some other port as part of its configuration. Even when disabling the host port from 8087 to disabled, the add-on still says port 8080 is in use and will not load.

**Comment by alexbelgium** [comment]
Hi, then there is something wrong... Port 8080 is internal and would only be exposed if your system provides hist network, which is not allowed by default. Normally, you should simply be able to change the port from addon options.

I m myself running another addon with port 8080 set as external, and it causes no issues...

**Comment by alexbelgium** [comment]
Hi, I remember our discussions on qbittorrent! I'll add the apparmor fix let's see if it helps.
