### ISSUE TITLE
[addon] Cloud Commander Port 8000 in-use

### ISSUE THREAD

**Issue by aLTeReGo-SWI** [alexbelgium/hassio-addons#187]
**Which addon?**

---
Cloud Commander
name: Feature request
about: Suggest an idea for this project
title: 'Allow listening port to be configurable'
labels: ''
assignees: ''

---

**Which addon?**

Cloud Commander add-on

**Addon or app?**

Add-on

**Describe the solution you'd like**

Allow the port to be configurable. 8000 is a fairly common port that's already in use and not changeable. The add-on will not load unless this container port is available on the host, despite using ingress. 

**Describe alternatives you've considered**

Tried disabling the webui port with the intention of relying solely on ingress, but that made no difference. Also the add-on says it's required. Changed host port to a known available port "9999" but the add-on will still not load because port 8000 is in use. 

**Additional context**

Starting...
/etc/cont-init.d/00-aaa_dockerfile_backup.sh: executing
/etc/cont-init.d/00-banner.sh: executing
hello
curl: (7) Couldn't connect to server
[14:39:18] ERROR: Something went wrong contacting the API
/etc/cont-init.d/92-local_mounts.sh: executing
curl: (7) Couldn't connect to server
[14:39:18] ERROR: Something went wrong contacting the API
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
curl: (7) Couldn't connect to server
[14:39:18] ERROR: Something went wrong contacting the API
[14:39:18] INFO: Starting...
cloudcmd --port: listen EACCES: permission denied 0.0.0.0:8000

**Comment by alexbelgium** [comment]
Hi, I'm sorry but something is wrong in your system, I two addons exposé their internal ports... What is your system?

**Comment by alexbelgium** [comment]
Setting a fixed ip in the supervisor could help with some curl issues

**Comment by alexbelgium** [comment]
Hi, I remember our discussions on qbittorrent! I'll add the apparmor fix let's see if it helps.

**Comment by aLTeReGo-SWI** [comment]
That fixed it! Thank you

**Comment by alexbelgium** [comment]
Great, thanks!
