### ISSUE TITLE
Organizr Port is Possible?

### ISSUE THREAD

**Issue by phgsbr** [alexbelgium/hassio-addons#19]
Hi!

I would like to use Organizr to index all services. Could you port it to Home Assistant?

Thank you!

**Comment by alexbelgium** [comment]
Hi, it's marked as DEPRECATED by linuxserver. Sure it's a safe thing to invest on?
https://hub.docker.com/r/linuxserver/organizr

**Comment by phgsbr** [comment]
> 
> 
> Hi, it's marked as DEPRECATED by linuxserver. Sure it's a safe thing to invest on?
> https://hub.docker.com/r/linuxserver/organizr

This is the official repo, i think!
https://hub.docker.com/r/organizr/organizr

**Comment by alexbelgium** [comment]
Thanks! It's a bit like Heimdall? An organizer for your services?

**Comment by phgsbr** [comment]
> 
> 
> Thanks! It's a bit like Heimdall? An organizer for your services?

Yeah, but with a lot more features.

**Comment by alexbelgium** [comment]
Great thanks! I'll look at it

**Comment by alexbelgium** [comment]
Hi, it's built. Could you please let me know if it works? Thanks!

**Comment by phgsbr** [comment]
> 
> 
> Hi, it's built. Could you please let me know if it works? Thanks!

You're the best!

Thank you again, is a very useful feature and works perfectly!

**Comment by alexbelgium** [comment]
Great, thanks for the feedback!
