### ISSUE TITLE
[whoogle] unable to install/update

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#193]
**Which addon?**
* Addon name : Whoogle
* Addon version : 

**Describe the bug**
When installing or updating I get an error. Also happened when updating
Could be related to this line:
https://github.com/alexbelgium/hassio-addons/blob/master/whoogle/Dockerfile#L42
Where there is a space missing, but I am unable to test stuff since I am not home atm, sorry!

**To Reproduce**
1. Install the app
2. see the error

**Full addon log**
```bash
The command '/bin/sh -c if ! command -v bash >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends bash || apk add --no-cache bash) >/dev/null; fi && if ! command -v curl >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends curl || apk add --no-cache curl) >/dev/null; fi && mkdir -p /etc/cont-init.d && for scripts in $MODULES; do curl -L -f -s -S "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/.templates/$scripts" -o /etc/cont-init.d/"$scripts" || (echo "script failed to install $scripts" && exit 1); done && chmod -R 755 /etc/cont-init.d || printf '%s\n' "${MODULES}" >/MODULESFILE' returned a non-zero code: 1
```

**Full addon config**
nothing configured, empty

**System**

Version core-2021.12.10
Version supervisor-2021.12.2

**Comment by alexbelgium** [comment]
Hi, it was a user issue : "/bin/sh: can't create /MODULESFILE: Permission denied", I've added in the Dockerfile a USER root setting that should help

It seemed to install correctly on my system (rpi4 aarch64)

**Comment by alexbelgium** [comment]
Tested working :-)

**Comment by bruvv** [comment]
confirmed too! thanks for the quick fix
