### ISSUE TITLE
[spotweb] cronjobs are not running

### ISSUE THREAD

**Issue by woutercoppens** [alexbelgium/hassio-addons#196]
**Which addon?**
Spotweb
* Addon name : Spotweb 
* Addon version : 1.5.1-4

**Describe the bug**
The spots are not retrieved because the script /etc/periodic/hourly/spotweb is not run every hour. It runs never. 

**To Reproduce**

**Full addon log**

**Full addon config**

**System**

**Comment by alexbelgium** [comment]
Mmh we can check by logging in the addon with portainer and see the cron status, and try to run manually the cron service. I'll see if I have time tomorrow to check that

**Comment by alexbelgium** [comment]
Mmh we can check by logging in the addon with portainer and see the cron status, and try to run manually the cron service. I'll see if I have time tomorrow to check that

BTW, shouldn't it be "/etc/cron.hourly" instead of /etc/periodic/hourly ?

**Comment by alexbelgium** [comment]
Looks like spotweb permissions are rw-r-r perhaps we should do a +x in the install script

**Comment by alexbelgium** [comment]
I've pushed a new version to test

**Comment by woutercoppens** [comment]
I have never set +x before and it worked. Let's hope that is the solution.

**Comment by alexbelgium** [comment]
You can test run with "run-parts /etc/periodic/hourly"

**Comment by woutercoppens** [comment]
https://devopsheaven.com/cron/docker/alpine/linux/2017/10/30/run-cron-docker-alpine.html
Scripts inside of cron_tasks_folder have to be without extension and with +x permissions.

**Comment by alexbelgium** [comment]
Closed as it seems to work

**Comment by alexbelgium** [comment]
If we want to add a message saying the cron job run we must redirect output to ```> /proc/1/fd/1```

**Comment by woutercoppens** [comment]
Cool
