### ISSUE TITLE
Scrutiny

### ISSUE THREAD

**Issue by synack666** [alexbelgium/hassio-addons#198]
App dont gather metrics.

Scrutiny
Current version: 0.3.13-6
supervisor-2022.01.0
core-2021.12.10
Home Assistant OS 7.2

System i386 Nuc, Disk mSATA SSD

App log:
time="2022-01-31T19:43:21+01:00" level=info msg="Collecting smartctl results for sda\n" type=metrics
time="2022-01-31T19:43:21+01:00" level=info msg="Executing command: smartctl -x -j /dev/sda" type=metrics
time="2022-01-31T19:43:21+01:00" level=error msg="smartctl returned an error code (2) while processing sda\n" type=metrics
time="2022-01-31T19:43:21+01:00" level=error msg="smartctl could not open device" type=metrics
time="2022-01-31T19:43:21+01:00" level=info msg="Publishing smartctl results for \n" type=metrics

time="2022-01-31T19:43:21+01:00" level=error msg="An error occurred while updating device data from smartctl metrics WHERE conditions required"
time="2022-01-31T19:43:21+01:00" level=error msg="127.0.0.1 - db21ed7f-scrutiny [31/Jan/2022:19:43:21 +0100] \"POST /api/device//smart\" 500 17 \"\" \"Go-http-client/1.1\" (5ms)" clientIP=127.0.0.1 hostname=db21ed7f-scrutiny latency=5 method=POST path=/api/device//smart referer= respLength=17 statusCode=500 userAgent=Go-http-client/1.1
2022/01/31 19:43:21 /app/scrutiny/webapp/backend/pkg/web/handler/upload_device_metrics.go:31 WHERE conditions required
[0.213ms] [rows:0] UPDATE `devices` SET `created_at`="2022-01-31 18:07:34.087",`updated_at`="2022-01-31 19:43:21.131",`device_name`="sda",`device_type`="scsi"
time="2022-01-31T19:43:21+01:00" level=info msg="Main: Completed" type=metrics
[19:43:21] INFO: Local Devices Added

Supervisor log:
22-01-31 18:07:27 ERROR (SyncWorker_1) [supervisor.docker.addon] Add-on Scrutiny try to access to blocked device sda!
22-01-31 18:07:27 ERROR (SyncWorker_1) [supervisor.docker.addon] Add-on Scrutiny try to access to blocked device sda!
22-01-31 18:07:27 ERROR (SyncWorker_1) [supervisor.docker.addon] Add-on Scrutiny try to access to blocked device sda1!

**Comment by alexbelgium** [comment]
Hi, thanks. Are you sure your disk supports SMART?

**Comment by synack666** [comment]
not shure but i will boot from a stick with ubuntu with smartctl installed, tomorrow, come back with result an in case of "yes" the full log, thnx

**Comment by synack666** [comment]
Hi again, i am lost an your idea is right, no smart support from my disk, so i close.
