### ISSUE TITLE
Transmission : 403 Unauthorized IP address

### ISSUE THREAD

**Issue by md-ray** [alexbelgium/hassio-addons#2]
Hi, first of all I would like to say my gratitude for you for making this Transmission addons for HA. I've been looking all time, and stumble upon this.
On the issue, I managed to add your repo, install and do some configuration.
However, when I access the Web UI, I got this error:

403: Forbidden
Unauthorized IP Address.
Either disable the IP address whitelist or add your address to it.
If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.
If you're still using ACLs, use a whitelist instead. See the transmission-daemon manpage for details.

Perhaps we need to make some changes **settings.json**

Any idea how to fix this?

**Comment by alexbelgium** [comment]
Thanks, I'll update the addon in a couple hours to remove the issue. 
In the meantime, you can access the settings.json file by going into /share/transmission/settings.json using the editor app if needed.

**Comment by alexbelgium** [comment]
Version updated - should be good !

**Comment by alexbelgium** [comment]
Version updated - should be good !

And thanks for your kind words 👍 Please let me know if you see other things that could be improved!

**Comment by md-ray** [comment]
Hi, thanks for the quick solution and update. I can confirm that your latest code now works properly.
Just some minor additional feedback. When I try to apply your latest code, I try several ways.
- Rebuilding: not working
- Uninstall then Install the add-ons: also not working
- Remove your repo from add-ons, then adding again: **this is working**

I don't know whether this is my problem only (or due to some caching in HA for example). But anyway, my initial issue already solved. Again, thanks!

**Comment by alexbelgium** [comment]
That's strange ! If it is due to caching issue, you can click on "Reload" at the same menu where you add or remove repo. This should have the same effect, and it allows refreshing to see if new updates are available. It is automatically done periodically by the system. I'll close the issue as you confirm it now works fine. All the best.

**Comment by alexbelgium** [comment]
> Hi, thanks for the quick solution and update. I can confirm that your latest code now works properly.
> Just some minor additional feedback. When I try to apply your latest code, I try several ways.
> 
> * Rebuilding: not working
> * Uninstall then Install the add-ons: also not working
> * Remove your repo from add-ons, then adding again: **this is working**
> 
> I don't know whether this is my problem only (or due to some caching in HA for example). But anyway, my initial issue already solved. Again, thanks!

Hi, I learned some more about hassio and understood why. If a version number hasn't changed, the repo must be manually updated by clicking Reload in the same menu that custom repo can be added. ;) Thanks your experience sharing allowed me to learn that!
