### ISSUE TITLE
Inadyn for use of Dynamic DNS.

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#20]
Hi Alex,

I use your repository with the addons. Very nice you created so many. Thx
So i wonder if you can bring support to a legacy addon which uses Inadyn for dynamic DNS.
It is still working so far. I use it for updating my own IP with a dynamic dns supported domain i bought.

nalipaz created this but isnt maintaining it anymore:
https://github.com/nalipaz/hassio-addons

Inadyn itself:
https://github.com/troglobit/inadyn

I dont know if it is a combination of multiple tools to use it with HASS or only Inadyn.?
That nalipaz created.

**Comment by alexbelgium** [comment]
Hi, would this work ? 
https://hub.docker.com/r/linuxserver/ddclient
It seems like an alternative to inadyn and could be ported easily

**Comment by alexbelgium** [comment]
Actually inadyn seems feasible. I'll fork it and test

**Comment by deku-m** [comment]
> 
> 
> Hi, would this work ?
> https://hub.docker.com/r/linuxserver/ddclient
> It seems like an alternative to inadyn and could be ported easily

I dont know if thats the same could be i can always test it but its the support for the provider in it.
As i use Strato.



> 
> 
> Actually inadyn seems feasible. I'll fork it and test

Nice :) thx

**Comment by deku-m** [comment]
Configuration that are set in legacy addon from nalipaz:

Which are set in Inadyn for example
providers:
  - provider: strato
    username: <username>
    password: <password>
    hostname: <domainname>

**Comment by alexbelgium** [comment]
Hello!
I've made a first version, could you please test it ? As I don't have DNS data I can't see if it works.
Thanks!

**Comment by deku-m** [comment]
Installed the addon and looks like it is working like a charm:
```
-----------------------------------------------------------
 Add-on: Inadyn
 Inadyn is a small and simple Dynamic DNS, DDNS, client with HTTPS support. A large number of dynamic dns providers are supported (https://github.com/troglobit/inadyn#supported-providers). For those that are not, you can use a custom provider as per this project's documentation (https://github.com/nalipaz/hassio-addons/blob/master/README.md)
-----------------------------------------------------------
 Add-on version: 2.8.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.6
 Home Assistant Supervisor: 2021.06.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
inadyn[81]: In-a-dyn version 2.8.1 -- Dynamic DNS update client.
inadyn[81]: Guessing DDNS plugin 'default@strato.com' from 'strato'
inadyn[81]: Update forced for alias subdomain.domain.nl, new IP# <IPaddress>
inadyn[81]: Updating cache for subdomain.domain.nl
```

Adjusted my real domainname.

**Comment by alexbelgium** [comment]
Great! Thanks for the feedback!
