### ISSUE TITLE
Flexget 

### ISSUE THREAD

**Issue by tyjtyj** [alexbelgium/hassio-addons#201]
**Which addon?**
Flexget

**Is your feature request related to a problem? Please describe.**

Change loglevel in addon config

**Describe the solution you'd like**

Can log level setting added to hass addon config page ?

**Describe alternatives you've considered**

**Additional context**

Starting flexget fix loglevel info which is insufficient for debugging

[services.d] executing => flexget -c /config/addons_config/flexget/config.yml --loglevel **info** --logfile flexget.log daemon start --autoreload-config

Available options 
Set the verbosity of the logger. Levels: 
**critical, error, warning, info, verbose, debug, trace**

**Comment by alexbelgium** [comment]
Implemented and tested!

**Comment by tyjtyj** [comment]
works like magic. Thanks again!!
