### ISSUE TITLE
[REQ] NGINX + PHP + MYSQL (or something for a webserver)

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#204]
**Which addon?**
I would like to run a wordpress website on my server is it possible to have nginx + php for this (including a database?)

**Comment by alexbelgium** [comment]
Hi, I'll have to look at it, I think WordPress actually has a docker imagz.

**Comment by alexbelgium** [comment]
What do you think about Grav ?
I've an addon on that, and for example the linuxserserver website is based on it and looks very good : https://www.linuxserver.io/blog/that-long-overdue-update-post

**Comment by ikrowni** [comment]
> Hi, I'll have to look at it, I think WordPress actually has a docker imagz.

I was actually looking for a wordpress addon the other day. +1 for this idea

**Comment by alexbelgium** [comment]
> **Which addon?** I would like to run a wordpress website on my server is it possible to have nginx + php for this (including a database?)

Hi, an addon similar seems to exist here : https://github.com/FaserF/hassio-addons the is an apache2 addon with php. I'll still look at the WordPress addon, but don't have time for the moment

**Comment by bruvv** [comment]
Wow sorry totally lost track on this one. It's not needed for me anymore. I'll close this issue.

**Comment by ikrowni** [comment]
> Wow sorry totally lost track on this one. It's not needed for me anymore. I'll close this issue.

Or we can keep it open since others still have interest in it and he said he would check into it later when he has time.
