### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Axydas** [alexbelgium/hassio-addons#205]
Hello,

first of all i would like to say a BIG THANKS for your great work!! I am using some of your add-ons for some time now. After the last update of the HA i have an issue with the add ons. When i try to open the web UI i get the ERR_SSL_PROTOCOL_ERROR error from Chrome.

I am using the DuckDNS ad on. All add ons that have the ssl option works fine. The rest like Organizr, heimdall etc are not working and i het the error message. If i connect to my HA through http (homeassistant.local:8123) the add ons work fine. 

Any suggestion how to fix this?

**Comment by alexbelgium** [comment]
Hi thanks for the feedback!

Would this help : https://community.home-assistant.io/t/duckdns-how-to-solve-err-ssl-protocol-error/174413/14 ?

I think it is because those addons have self signed certificates

**Comment by alexbelgium** [comment]
BTW my organizr addon don't have ssl option, and I don't have a heimdall addon... Are you sure you are in the right place and this is linked to my addons? Perhaps you could have a better support if you post your issue in the HA https://community.home-assistant.io/ or the supervisor github https://github.com/home-assistant/supervisor/issues

**Comment by Axydas** [comment]
Yes I am sure that I am using your addons. Organize is from your package. Are you using duckdns?

**Comment by alexbelgium** [comment]
I'm not using duck dns, but organizr does not have ssl - it can't be accessed with https and therefore it is normal that you would have an ssl error

What I was meaning is that I only support my addons, if you issue impacts more than my addons (you mentioned heimdall) then it's better to ask for help in the general places I mentioned above
