### ISSUE TITLE
[urielch/chrome-vnc] dont save settings like bookmarks or settins in the browser

### ISSUE THREAD

**Issue by kingunlim** [alexbelgium/hassio-addons#208]
**Which addon?**

* Addon name : urielch/chrome-vnc
* Addon version : 

**Describe the bug**
Hi, i would really like to use this vnc chrome browser, because i want to use it for my old ipads.
i want to connect via vnc and open the ha instance.

I managed to expose a other port than 5900 and i also changed the language via a environment tag.

but i dont know how excactly i can manage it to save settings i make for example bookmarks in the browser.
to let it save those settings.
i see a automated volume gets created and mounted with the container, but i dont know whats the problem :(

**To Reproduce**

**Full addon log**

**Full addon config**

**System**

* Supervisor version: 
* Host system version:

**Comment by alexbelgium** [comment]
Hi, if you have created an addon, the default location for persistent data is /data. So probably you could modify the main user home directory to /data by using something like `usermod -home /data user`, user being the real name used in the addon... Honestly I barely have the time to support my addons so I won't really be able to provide you a lot of help on that. Btw, the ha app, or accessing ha in safari still works great for me even on 32 bits ipad !

**Comment by kingunlim** [comment]
thanks for your answer, but im a little bit lost here :(

What do you mean with "if you have created an addon"?
 - i have createt a new volume and i have created an new container, then i set the env. variable for language and screen dimension, and i set the created volume as volume path in the container.

when i have created the container without a special volume, it creates one it self and i see it mounts the directory /home/chrome
- so you mean i would probably need a data directory there?

"user being the real name used in the addon?
- sry i don't know what you mean exactly with that?

i see in the portainer settings there a some directorys hidden by default, and i leave them like that.

maybe you can explain me the neccessary steps a little bit more?

Best regards

**Comment by alexbelgium** [comment]
Hi, sorry I was unclear. I now understand you use portainer. Forget everything I've writen :) 

You can see in the container for chrome-vnc that it has a volume mounted "/home/chrome". I've never used it this way, but I think the key element is to map this volume to a persistent folder, such as /share. 

Perhaps it is possible that you create a folder in /share/chrome, for example, and that you map " /share/chrome" to

**Comment by kingunlim** [comment]
thx, again for your answer.

alright, so maybe you can explain me the best way to do this?
"Perhaps it is possible that you create a folder in /share/chrome, for example, on your HA system, and that you map "/mnt/data/supervisor/share/chrome", to "/home/chrome"?"

is it true that i must go in the settings of portainer and exclude the HA System Folders and then i can bind it in the container settings or what would be the best way to go?

**Comment by alexbelgium** [comment]
No, just go in portainer in the container, click duplicate/edit, scroll down to the volume section, and you'll probably see that /home/chrome is bound to /home/chrome. You need to bind it to /mnt/data/supervisor/share/chrome

I suggest that you open the container of an existing addon with portainer and study how volumes are mounted! Here is an example. 
![Screenshot_20220209-160550_Home Assistant](https://user-images.githubusercontent.com/44178713/153228818-b1df131d-b280-4e7d-a58c-2c3ce6467623.jpg)

**Comment by kingunlim** [comment]
hmm.... i think i tried this yesterday but i'll try it right know, sadly i can check it right know, because im in the work, but i have configure it like you say: 
![image](https://user-images.githubusercontent.com/42124176/153231831-ad626333-af49-49e8-b1d7-0fd14024e6bd.png)

is the folder: 
/mnt/data/supervisor/share/chrome

also the "share" folder i can access via the samba addon?
i need to create the folder chrome before, of corse?

and may i ask you:
is this the recommended way when i install a new container, to just deploy it and then check the volume options, if the have /data 
/config 
folder and so on, i must mount them somewhere in the persistent filesystem: 
/mnt/data/supervisor/....

**Comment by alexbelgium** [comment]
So the easiest is that you install my filebrowser addon, go in /share and create the folder chrome...

Honestly the recommended way is to avoid using portainer, that's why the ha team has removed the official addon :) and instead create addons. It's not that difficult

**Comment by kingunlim** [comment]
alright, then i will install your Filebrowser addon and take a look ;)

Yeah i understand that, honestly im in the process of rethink everything and maybe i will completly change my system onto another distribution and will also install Hassio as a docker Plugin, but in the moment everything works and you know how things can work out :)

The problem with the native hassio app on old ipad is that i can't connect it in the first place, and i must have a look why, but also when i can connect, so many other lovelance things don't work good on the old ipads :(

maybe sometime in the future you can create something like this container native for hassio, i really don't know how long and how difficult this would be for you?

best regards!

**Comment by kingunlim** [comment]
so i tried the connection and it worked but asume there is no write right set because i just see a black screen when i try to connect :(
![Uploading 5E86DCF2-F47E-44D0-89FC-A7365597DFF7.png…]()

**Comment by alexbelgium** [comment]
Ah... Not easy... An easier idea : that you install my webtop alpine kde addon, install vnc by adding it on the addon options and run it from within the webtop? It's an entire alpine distribution with a kde frontend

**Comment by alexbelgium** [comment]
Or you use docker compose to deploy the chrome vnc image, it allows setting environnement variables and volumes... So you know docker compose ?

**Comment by kingunlim** [comment]
hmm.... i don't know if its the best way to add a hole distribution on top :(

sadly i don't  know how i can use docker compose to deploy the chrome vnc image exactly.

are you sure there is no other way to get it running via portainer?
i see this option in portainer maybe i need to untick the supervisor here:
![image](https://user-images.githubusercontent.com/42124176/153484073-ae2b03a0-dc81-4130-8242-501ae29af2f3.png)

**Comment by alexbelgium** [comment]
Hi, my browser deleted my whole message. I'll type again tomorrow.

However the key element was : here is the docker compose https://github.com/UrielCh/chrome-vnc/blob/master/docker-compose.yml you just need to paste the content into the docker compose part of portainer and it will launch the app. Would setting the entry url suit your purpose by encoding your HA url? 

"i don't know if its the best way to add a hole distribution on top" : actually it's alpine so super light. And all docker images are built on a whole distribution in a sense :) the only thing is that the webtop addon has kde installed.

"i don't know how i can use docker compose to deploy the chrome vnc image exactly." see above, docker compose allow you to quickly launch a dockerhub container while passing environment variables and bound volumes

"are you sure there is no other way to get it running via portainer" actually no idea I'm not a portainer super user... But i was thinking that by comparing the way the container is set with a normal addon, you could see how to make it work... 

"when portainer create the volume by itself, i see that the container is fully running, but after i stop or restart it, it resets itself, shouldn't it hold on till i restart the hole system new?" i think the volume needs to be mapped to something local to be persistent...

" use the native safari and ha app on my old ipad with os.9.5.3 " ah, indeed my old ipad is still on ios 10.3 (last version with support for 32 bits) and it barely works with many lovelace feature not available, so indeed 9.5.3 would be not likely to work
