### ISSUE TITLE
Bazarr SMB mount

### ISSUE THREAD

**Issue by phgsbr** [alexbelgium/hassio-addons#21]
Hey @alexbelgium , could you implement the same smb mount method of radarr/sonarr in bazarr?

Thank you!

**Comment by alexbelgium** [comment]
Hey! Should be good now :) please let me know if everything works as expected!

**Comment by phgsbr** [comment]
Hmm, strange. Still no mounting
![Screenshot_9](https://user-images.githubusercontent.com/20521629/124359855-1cb89600-dbfd-11eb-931f-e54bfc7168e7.png)

**Comment by alexbelgium** [comment]
Hi, v3 is online it should solve that :)

**Comment by phgsbr** [comment]
Its perfect now! Thank you!

**Comment by alexbelgium** [comment]
Thanks! Have a nice day
