### ISSUE TITLE
[Jellyfin] Store data in other folder (/share)

### ISSUE THREAD

**Issue by hulkhaugen** [alexbelgium/hassio-addons#210]
**Which addon?**
Jellyfin and Emby

**Is your feature request related to a problem? Please describe.**
No, but i would like to keep data away from the config folder as it is backed up and takes a lot of space

**Describe the solution you'd like**
Option to specify folder

**Additional context**
I see that your addons store data in `/config/addons_config/(ADDON_NAME)/`, yet it also creates similar folders in `/share/(ADDON_NAME)`, yet those folders are left empty. In Jellyfin, I can specify to store `cache`, `metadata` and `transcodes` individually, but database files, log files and settings files are still stored under config. I like to keep "non-critical" data away from the folders that are backed up by HA.

**Comment by alexbelgium** [comment]
Hi,

What is the size of your files ?

I'm using Emby : 
- /config/addons_config/emby : 304 ko
- /share/emby : 699.4 Mo

So it already seems to be the case...

**Comment by alexbelgium** [comment]
I've done a new version of Jellyfin with a "data_location" tag in addons. Could you please test? thanks.

**Comment by hulkhaugen** [comment]
Is this something on my end?
`400 Client Error for http+docker://localhost/v1.41/build?t=db21ed7f%2Famd64-addon-jellyfin%3A10.7.7-1-ls150-2&q=False&nocache=False&rm=False&forcerm=True&pull=True&buildargs=%7B%22BUILD_FROM%22%3A+%22linuxserver%2Fjellyfin%3Aamd64-latest%22%2C+%22BUILD_VERSION%22%3A+%2210.7.7-1-ls150-2%22%2C+%22BUILD_ARCH%22%3A+%22amd64%22%7D&labels=%7B%22io.hass.version%22%3A+%2210.7.7-1-ls150-2%22%2C+%22io.hass.arch%22%3A+%22amd64%22%2C+%22io.hass.type%22%3A+%22addon%22%2C+%22io.hass.name%22%3A+%22Jellyfin+NAS%22%2C+%22io.hass.description%22%3A+%22A+Free+Software+Media+System+that+puts+you+in+control+of+managing+and+streaming+your+media.%22%2C+%22io.hass.url%22%3A+%22https%3A%2F%2Fgithub.com%2Falexbelgium%2Fhassio-addons%22%7D: Bad Request ("dockerfile parse error line 31: unknown instruction: ECHO")`

**Comment by alexbelgium** [comment]
Yup, pushed a new version I hadn't yet had to test it. ;) new version should work better

**Comment by hulkhaugen** [comment]
It seems to be all good now, thanks for your quick action :) It's a really nice collection of addons you've got here ;)

**Comment by alexbelgium** [comment]
Thanks!
