### ISSUE TITLE
[XTEVE] xteve behind nginx rp

### ISSUE THREAD

**Issue by thetux07** [alexbelgium/hassio-addons#211]
Hello
thank you for your work,
 currently I manage to recover the m3u and the xml by making a proxy_pass if nginx on the other hand the /stream/….  doesn't work on vlc or other app but works fine on Chrome on iPhone.  do you have an idea ?  thank you very much

**Comment by alexbelgium** [comment]
Hi, thanks! Mmh this seems more related to the app itself than the addon... Perhaps you would have a better support on the dev github here https://github.com/collelog/tv-recorder-dockerfile
