### ISSUE TITLE
[fireflyiii] Can't set Base64-encoded APP_KEY

### ISSUE THREAD

**Issue by leppa** [alexbelgium/hassio-addons#217]
**Which addon?**

* Addon name : fireflyiii
* Addon version : 5.6.14-3

**Describe the bug**
I was trying to migrate my manual installation of Firefly III to this addon, however I've hit the following issue. The [official .env.example from Firefly III](https://github.com/firefly-iii/firefly-iii/blob/main/.env.example) recommends generating the `APP_KEY` by running the `php artisan key:generate` command, which I did when I initially installed Firefly III. The issue is that this command seems to produce a Base64-encoded key which looks like this: `APP_KEY=base64:U29tZVJhbmRvbVN0cmluZ09mMzJDaGFyc0V4YWN0bHk=`. When I try to set this key in the addon config, I get "Your APP_KEY has XX instead of 32 characters" error. If I decode the key, it contains non-ASCII characters that seem to break the startup script.

**To Reproduce**
1. Set APP_KEY config parameter to Base64-encoded key (e.g., `base64:U29tZVJhbmRvbVN0cmluZ09mMzJDaGFyc0V4YWN0bHk=` which is Base64-encoded default key `SomeRandomStringOf32CharsExactly`).
2. Try to start the addon

**Full addon log**
With Base64-encoded key:
```
[18:16:09] INFO: Starting the app with the variables in in /config/addons_config/fireflyiii/config.yaml
/etc/cont-init.d/99-run.sh: executing
[18:16:10] FATAL: Your APP_KEY has 51 instead of 32 characters
/etc/cont-init.d/99-run.sh: exiting 1
```
With decoded key (the key contains `)`, amongst other characters):
```
[18:20:12] INFO: Starting the app with the variables in in /config/addons_config/fireflyiii/config.yaml
/etc/cont-init.d/99-run.sh: executing
/./etc/cont-init.d/99-run.sh: line 5: syntax error near unexpected token `)'
/etc/cont-init.d/99-run.sh: exiting 2
```

**Full addon config**
```yaml
DB_CONNECTION: sqlite_internal
APP_KEY: "base64:encoded-key"
CONFIG_LOCATION: /config/addons_config/fireflyiii/config.yaml
silent: true
```

**System**

* Supervisor version: supervisor-2022.01.1
* Host system version: Raspbian 10 (buster)

**Comment by alexbelgium** [comment]
Hi, and thanks for the detailed infos. I've added a check so that keys starting with "base64:" are not counted

**Comment by alexbelgium** [comment]
Should be good in the new addon version, and it should also allow special characters in strings. Thanks for reporting!

**Comment by leppa** [comment]
The addon starts fine after the update, thanks a lot for the lightning fast fix!

Now up to pointing it to the real database and YAMLifying my `.env` file...
