### ISSUE TITLE
[qbittorrent] qbittorrent failling to start with error

### ISSUE THREAD

**Issue by jpz02** [alexbelgium/hassio-addons#221]
qBittorrent

- Addon name : qBittorrent
- Addon version : 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-8

**Describe the bug**

Hi there, I've just installed the addon and haven't really changed the default configuration. From the logs I can see it's getting up to the `91-qbittorrent_configuration.sh` script and curl throws an error and the container stops. I had a look at the script and I can see that the curl is to fetch the frontend code. I've been able to get a shell to an image of the stopped container, and I ran the curl command manually and it's able to fetch the frontend successfully. I've tried to debug this on my own, but I think I'm stuck now!

Thanks in advance for any help.

**To Reproduce**

1. Start the qbittorrent addon

**Full addon log**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-aaa_dockerfile_backup.sh: executing... 
[cont-init.d] 00-aaa_dockerfile_backup.sh: exited 0.
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
 Add-on version: 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-8
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 30-nginx.sh: executing... 
[cont-init.d] 30-nginx.sh: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 90-dns_set.sh: executing... 
[23:59:24] INFO: DNS SERVERS set to 1.1.1.1 
[cont-init.d] 90-dns_set.sh: exited 0.
[cont-init.d] 91-qbittorrent_configuration.sh: executing... 
[23:59:25] INFO: Downloads can be found in /share/qBittorrent
[23:59:25] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[23:59:26] INFO: WEBUI username set to admin
[23:59:26] INFO: Alternate UI enabled : qb-web. If webui don't work, disable this option
curl: (3) URL using bad/illegal format or missing URL
[cont-init.d] 91-qbittorrent_configuration.sh: exited 3.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Full addon config**

```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
customUI: vuetorrent
SavePath: /share/qBittorrent
Username: admin
DNS_server: 8.8.8.8,1.1.1.1
PUID: '0'
PGID: '0'
```

**System**

- Supervisor version: `supervisor-2022.01.1`
- Host system version: `Home Assistant 2022.2.9`

**Comment by jpz02** [comment]
I just tested setting `customUI: ''` in the yaml configuration and it started! So it's definitely an issue fetching the UI.

**Comment by jpz02** [comment]
Okay, the plot thickens... Now that I could grab a shell on the actual running, 'hassio launched' container, I can see that DNS resolution isn't working on the container (and thus qbittorrent doesn't actually work).
```
root@db21ed7f-qbittorrent:/# curl google.com
curl: (6) Could not resolve host: google.com
```

**Comment by jpz02** [comment]
So finally, just in case anyone has the same issue. I was able to disable the custom DNS server with `DNS_server: ''` (the default setting is 8.8.8.8,1.1.1.1)
I was also then able to set the `customUI` option as well and everything else worked.

**Comment by alexbelgium** [comment]
Hello, thanks for the great troubleshooting! I've tried to improve my code lately to have a 100% success on lints, and this surely has caused this issue. I'll investigate and push a new version to restore custom DNS setting. Thanks!

**Comment by alexbelgium** [comment]
You were spot on. I've checked I had the same issue, corrected the dns code, and checked that it works. The new version just pushed will work with custom DNS! Once again, thanks A LOT for your great analysis!

**Comment by alexbelgium** [comment]
BTW new version today, with the latest qbittorrent version. It includes the dns fix

**Comment by deku-m** [comment]
The new version corrupted my qbittorent btw. Its not holding the config file at beginning and changed everything to /config/downloads. When changing it from the GUI it holds but after reboot its config again. Very strange.

As it now messed up my storage as i always save everything at /mnt/NAS/Downloads and not local disk.

**Comment by jpz02** [comment]
@alexbelgium: No worries! Glad I could help :)

@deku-m: it might a good idea to make a new issue for your problem. I was planning on closing this ticket at the original issue is fixed. Plus it'll give you an opportunity to fill in the issue template with additional info.

**Comment by alexbelgium** [comment]
And... That's why I had avoided updating to 4.4.0, but it seems 4.4.1 have s the same bug... I'll check but it's a probable reverse upcoming

**Comment by alexbelgium** [comment]
Download folder bug fixed in new release
