### ISSUE TITLE
[Filebrowser] Wont start when using ssl. Cert not found

### ISSUE THREAD

**Issue by encryptix** [alexbelgium/hassio-addons#224]
**Which addon?**

- Addon name : Filebrowser
- Addon version : 2.20.1-2 

**Describe the bug**
Filebrowser does not load when ssl is enabled. 

I believe the cause is the recent lint changes in the following commit to add " " around the variables in filebrowser/rootfs/etc/cont-init.d/99-run.sh
https://github.com/alexbelgium/hassio-addons/commit/df8cf7397cd0b2b885d14ad178f6c233abb5074d#diff-caf33cd5de52665ea5911a40d759fb89370457024ec67206168560e6b17bc185R79

Changing the 99-run.sh file to display what its running showed the following:

`command="./filebrowser '$CERTFILE' '$KEYFILE' --root='$BASE_FOLDER' --address=0.0.0.0 --database=/config/addons_config/filebrowser/filebrowser.dB '$NOA
UTH'"
echo "COMMAND TO RUN IS '${command}'"
/./filebrowser "$CERTFILE" "$KEYFILE" --root="$BASE_FOLDER" --address=0.0.0.0 --database=/config/addons_config/filebrowser/filebrowser.dB "$NOAUTH" &`

Displays
`bash-5.1# ./etc/cont-init.d/99-run.sh 
[18:24:27] INFO: ssl enabled. If webui don't work, disable ssl or check your certificate paths
The files are .... '-t /ssl/fullchain.pem' and '-k /ssl/privkey.pem'
[18:24:28] INFO: NoAuth option selected
[18:24:28] INFO: Starting...
COMMAND TO RUN IS './filebrowser '-t /ssl/fullchain.pem' '-k /ssl/privkey.pem' --root='/config/filebrowser_data/' --address=0.0.0.0 --database=/config/addons_config/filebrowser/filebrowser.dB '''
2022/02/20 18:24:28 No config file used
2022/02/20 18:24:28 open  /ssl/fullchain.pem: no such file or directory
^C`

since $CERTFILE isnt just a path to a file but is actually "-t <file>", this causes filebrowser not to find the file. Testing moving the quote to be right of the -t successfullly loads.

`bash-5.1# ./filebrowser "-t /ssl/fullchain.pem" "-k /ssl/privkey.pem" --root="/config/filebrowswer_data/" --address=0.0.0.0 --database=/config/addons_config/fileborwser/filebrowser.DB
2022/02/20 18:40:23 No config file used
2022/02/20 18:40:23 open  /ssl/fullchain.pem: no such file or directory`

vs

`bash-5.1# ./filebrowser -t "/ssl/fullchain.pem" -k "/ssl/privkey.pem" --root="/config/filebrowswer_data/" --address=0.0.0.0 --database=/config/addons_config/fileborwser/filebrowser.DB
2022/02/20 18:41:00 No config file used
2022/02/20 18:41:00 Listening on [::]:8080`

**To Reproduce**
1. Start the addon
2. Open the UI
3. Observe it does not load and the logs have an error

**Full addon log**

`
Starting...
/etc/cont-init.d/00-aaa_dockerfile_backup.sh: executing
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Filebrowser
 filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files
-----------------------------------------------------------
 Add-on version: 2.20.1-2
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 11 (bullseye)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[17:31:49] INFO: ssl enabled. If webui don't work, disable ssl or check your certificate paths
[17:31:49] INFO: NoAuth option selected
[17:31:50] INFO: Starting...
2022/02/20 17:31:50 No config file used
2022/02/20 17:31:50 open  /ssl/fullchain.pem: no such file or directory
Terminated
[17:46:50] INFO: Started !
`
**Full addon config**
`
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
NoAuth: true
base_folder: /config/filebrowser_data/
`
**System**

- Supervisor version: Supervisor-2022.01.1
- Host system version: Raspbian GNU/Linux 11 (bullseye)

**Comment by alexbelgium** [comment]
You're fuliy right. I'll revert it. Thanks!

**Comment by alexbelgium** [comment]
New version up

**Comment by encryptix** [comment]
Thank you

**Comment by alexbelgium** [comment]
Great troubleshooting BTW, thanks very much
