### ISSUE TITLE
[Qbittorrent] Add-on causes host server CPU temp rise

### ISSUE THREAD

**Issue by sparkydave1981** [alexbelgium/hassio-addons#225]
**Which addon?**

- Addon name : Qbittorrent
- Addon version : 4.4.1 -ls172

**Describe the bug**

As soon as the add-on is started the host server CPU temperature rises massively, from around 42C to nearly 100C
**To Reproduce**

**Full addon config**
![image](https://user-images.githubusercontent.com/7628509/154869941-02ba10f0-cc22-4233-9da9-6943aac664ea.png)
![image](https://user-images.githubusercontent.com/7628509/154869947-f2e7910e-2746-4170-b4ad-c9a8577c10d6.png)
```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
customUI: vuetorrent
SavePath: /share/qBittorrent
Username: admin
DNS_server: 8.8.8.8,1.1.1.1
PUID: '0'
PGID: '0'
```

**System**

Host machine is an i7 NUC with 16Gb RAM.
## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Australia/Perth

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 1060
Downloaded Repositories | 80

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 22, 2022, 08:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 468.8 GB
disk_used | 60.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.105.2), Grafana (7.4.1), Mosquitto broker (6.0.1), Duck DNS (1.14.0), ESPHome (beta) (2021.9.2), motionEye (0.17.0), Terminal & SSH (9.3.0), Grocy (0.16.0), UniFi Network Application (1.1.4), ESPHome (2022.2.4), Studio Code Server (4.0.0), Assistant Relay (0.7.4), Simple Scheduler (0.35), Portainer (2.0.0), Node-RED (11.0.3), Samba Backup (5.0.0), Samba share (9.5.1), Run On Startup.d (0.10), AdGuard Home (4.4.4), TasmoAdmin (0.16.0), Check Home Assistant configuration (3.10.0), Z-Wave JS (0.1.54), MariaDB (2.4.0), Caddy 2 (1.1.0), Arpspoof (1.0.0), Paradox Alarm Interface (2.7.1), Qbittorrent (release-4.4.1-ls172), Network UPS Tools (0.9.1), Plex NAS (1.25.5.5492-12f6b8c83-ls101), RTSPtoWebRTC (1.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 59
views | 27
mode | storage

</details>

![image](https://user-images.githubusercontent.com/7628509/154870026-eff1e7a5-3b40-499a-972c-9dd5b941eac7.png)

- Supervisor version:  2022.01.1
- Host system version:  HA OS 7.4

Image shows instant CPU temp rise when starting the add-on
![image](https://user-images.githubusercontent.com/7628509/154869817-bf10f84b-03e1-442f-857a-988de1c782b2.png)

**Comment by alexbelgium** [comment]
Hi, the cpu temp jumps from 42 to 92°C instantly? It must be an issue in the temp reporting - It can't possibly change that fast... Actually I remember that you had posted also in the HA forum thread. So the issue is still here? I'll investigate a bit and report here

**Comment by alexbelgium** [comment]
Have you tried to let it run for a longer period of time? Like 15 min? 
Also, do you have an alternative app for T° measurement ?

**Comment by alexbelgium** [comment]
Could this help ?
https://community.home-assistant.io/t/nuc-cpu-temperature-concerns/189287/11?u=alexbelgium

**Comment by alexbelgium** [comment]
You could also install this addon which monitors containers and perhaps will help if anything anomalous occurs when qbittorrent is running : https://community.home-assistant.io/t/docker-container-stats-addon/320442

**Comment by sparkydave1981** [comment]
> Hi, the cpu temp jumps from 42 to 92°C instantly? It must be an issue in the temp reporting - It can't possibly change that fast... Actually I remember that you had posted also in the HA forum thread. So the issue is still here? I'll investigate a bit and report here

Yes, it's very much instantly (or at least as instant as how quickly the temp gets updated, so a few seconds)



> Have you tried to let it run for a longer period of time? Like 15 min?

Yes, the first time I setup the add-on I had it running for quite a while before noticing that the CPU temp was reporting crazy high.

**Comment by alexbelgium** [comment]
I really have no idea on to solve your issue, especially if you had it with other addons also... Perhaps a bios configuration could help you? Or removing your cpu and adding new thermic paste?

**Comment by sparkydave1981** [comment]
I'm not sure either.  MotionEye did create the same situation but only when recording multiple high res video streams.  I've tried two different NUC's and also replaced the thermal paste, that's definitely not the issue.  It seems to be something with the temp reporting.  I'm not sure what to look at in the BIOS as I did go through that to try and resolve the issue with MotionEye but failed to resolve it.  For that I ended up buying a dedicated NVR.

**Comment by alexbelgium** [comment]
> You could also install this addon which monitors containers and perhaps will help if anything anomalous occurs when qbittorrent is running : https://community.home-assistant.io/t/docker-container-stats-addon/320442

Have you tried this? It provides info on containers and could show the cpu usage of qbittorrent. And have you checked if the cpu heater is cold or hot?

**Comment by sparkydave1981** [comment]
> > You could also install this addon which monitors containers and perhaps will help if anything anomalous occurs when qbittorrent is running : https://community.home-assistant.io/t/docker-container-stats-addon/320442
> 
> Have you tried this? It provides info on containers and could show the cpu usage of qbittorrent. And have you checked if the cpu heater is cold or hot?

I'm away at the moment so haven't had a chance to test this out. I should be able to this weekend

**Comment by sparkydave1981** [comment]
I get an error "add-on not found" when trying to install this

**Comment by alexbelgium** [comment]
It installs perfectly well here... I've added Poeschl's repo then installed the addon. If it doesn't work then there seems to be other core issues with your system, independent from my addons...

**Comment by sparkydave1981** [comment]
> It installs perfectly well here... I've added Poeschl's repo then installed the addon. If it doesn't work then there seems to be other core issues with your system, independent from my addons...

I sorted it out, I needed to add the repo without the full link to that particular add-on

**Comment by sparkydave1981** [comment]
Here are some screen shots showing the temp rise with very little impact on CPU usage (temp rise just at the end of the graph when I started the Qbittorrent add-on).

![image](https://user-images.githubusercontent.com/7628509/158296642-70e67a47-0df4-43cb-91fb-34357d7843a1.png)


![image](https://user-images.githubusercontent.com/7628509/158296501-ff7e9858-eceb-4de5-8fdd-9412dfd0622b.png)

**Comment by alexbelgium** [comment]
Ah it's incredible... and without any impact on CPU usage... I really don't see what could cause that. It seems to be a real issue and not not a sensor problem btw as the temperature increase seems not to be perfectly instantaneous, but seems to have an increase slope with spikes. I don't have enough knowledge on what could cause that I'm sorry... Only solution I could think of is to test with the transmission addon which is great also - perhaps this one would work without this impact :-)
