### ISSUE TITLE
Request: Ingress

### ISSUE THREAD

**Issue by schnizki** [alexbelgium/hassio-addons#23]
Hello,
i love this addon but i would like to use it over Ingress. Should be relatively simple to add but i am no expert with docker.
It would be awesome if you could add this to this addon.

This might help: https://developers.home-assistant.io/docs/add-ons/presentation/#basic-ingress-example-with-nginx

**Comment by alexbelgium** [comment]
Hi, which addon are you talking about? Thanks for the infos, I've implemented ingress for several addons but it required some time each time and I'm on holidays for the next couple weeks without computer. Once you specify the addon I'll look for implementing ingress once I'm back!

**Comment by schnizki** [comment]
I am talking about the Cloudcommander addon, would be super nifty to have it as an integarted file manager in homeassistant for the root fs.

Thanks in advance :)

**Comment by schnizki** [comment]
Definitely, CC has more features, is a bit faster and you can access all host files due to direct file system access, FB looks nicer, has multiple user mode and is more user friendly but can only do samba.

**Comment by alexbelgium** [comment]
> Definitely, CC has more features, is a bit faster and you can access all host files due to direct file system access, FB looks nicer, has multiple user mode and is more user friendly but can only do samba.

Hi, I haven't time to look at ingress but I added local disk mount in filebrowser. Just type sda1 for example in the localdisks option.

**Comment by alexbelgium** [comment]
I've had a look but it's not easy to implement ingress. A lot of apps are now developed using fixed paths and it prevents Ingress from working...

**Comment by alexbelgium** [comment]
Hi, a new version is added with ingress. Could you please confirm it's working? thanks

**Comment by schnizki** [comment]
Hey, i tested it and it works great, thank you for your work :)
