### ISSUE TITLE
[tandoor_recipes] Search not work

### ISSUE THREAD

**Issue by davoloko** [alexbelgium/hassio-addons#233]
tandoor_recipes

- Addon name : tandoor_recipes
- Addon version : 1.1.2

I update addon and now work search. Keywords search work fine. I use sqlite

Search some text in recipes

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hi, thanks. Actually someone has reported the same search issue on the official github https://github.com/TandoorRecipes/recipes/issues/1627 and it seems to be resolved when refreshing the cache. Would this solve it for you also? Anyway this more looks like an app issue than an addon so you'll probably have a better support on the Tandoor_recipes github than here...
