### ISSUE TITLE
[firefly flint] configurations not loaded

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#234]
Hi @alexbelgium and thanks for this nice addon. 
Since my current multi banking tool changed from free to only paid model I am searching for a new tool. 
Firefly III seems to be a good alternative for me.
In the docs I found that there is an other importer available (which is easier to use for German bank accounts):
https://github.com/bnw/firefly-iii-fints-importer

I would be very happy if you had time to offer this as an addon as well 😃

_Originally posted by @ElVit in https://github.com/alexbelgium/hassio-addons/issues/126#issuecomment-1060043441_

**Comment by alexbelgium** [comment]
Hi, I'll look at it. Be aware that images only exist for amd64 though

**Comment by alexbelgium** [comment]
Hi, v1.0 is pushed let's test it and see how it goes

**Comment by ElVit** [comment]
Wow that was fast 😃
Thanks for that. And it's working 👍.
But only the manual way. If I create a config file than it's not shown in the drop-down menu. It should be an json file. Here an example: https://github.com/bnw/firefly-iii-fints-importer/blob/master/data/configurations/example.json

**Comment by alexbelgium** [comment]
Great, thanks for the feedback! I wouldn't have thought it would work so easily :-)
So you've created the file in /config/addons_config/fireflyiii_fints_importer/configurations ?

**Comment by alexbelgium** [comment]
I've added a new version to test

**Comment by ElVit** [comment]
Hi sorry for replying so late. 
But the import from a file still doesn't work. The file is not showing up in the dropdow.
I put the config file here: `/config/addons_config/fireflyiii_fints_importer/configurations`

![GetImage](https://user-images.githubusercontent.com/54866762/162958356-49c3b677-0e61-409e-a7fc-4704f45a56c1.png)
n menu.

**Comment by alexbelgium** [comment]
This is so weird, as it works in my own system. I'll think about what could be missing.

**Comment by alexbelgium** [comment]
>The reason may be that the "Updates" option is missing in the config.json

You're totally right! I've pushed a new version hopefully it will work right!

**Comment by alexbelgium** [comment]
Sorry I did it too quickly i'll do that at home a bit later

**Comment by alexbelgium** [comment]
Hi, so I've pushed a new version that should work : "1.2-6" (confirmed to work)

You need to put your configuration file in /config/addons_config/fireflyiii_fints_importer for it to be picked up. If you don't add any config on first boot, it will load the example.json file

Changes : I've simplified the options by
- removing the scheduled updates part as I'm not sure it's supported by this app. If you want it and it is relevant, I'll look what would be needed to re-add it
- removing the configuration location : now fixed to /config/addons_config/fireflyiii_fints_importer

**Comment by ElVit** [comment]
Yes now it's working 😃
The dropdown menu contains my json file. But it also contains all other files and folders. If it's possible it would be better only to show the json files. 
![image](https://user-images.githubusercontent.com/54866762/163120749-ccaf6f01-eba5-491e-bfe5-de496f751f3c.jpeg)

And as you mentioned before it's probably difficult to fully automate the process. The first time it asks me to enter a TAN. This TAN can only be generated from my phone app. But afterwords it’s not needed anymore. But I don’t know how long the authentication lasts.

**Comment by alexbelgium** [comment]
Hi, please remove all other files in the /config/addons_config/fireflyiii_fints_importer
I believe it's residuals from the previous versions, normally only the json files should be there

**Comment by ElVit** [comment]
Ok I see. Now it's showing only my file. Thanks.

**Comment by alexbelgium** [comment]
Great news, glad it worked
