### ISSUE TITLE
Supported filesystems (NTFS, exFAT, FAT32, ext4,...)?

### ISSUE THREAD

**Issue by antonio1475** [alexbelgium/hassio-addons#235]
**Multiple addons tested:** Filebrowser, Sonarr, qbittorrent, Plex

Can you confirm the compatibility? I'm unable to mount NTFS & exFAT partitions, while FAT32 and ext4 partitions mount fine.
I haven't tested ext2 & ext3

---

**Additional context**

>  sdb1 (My_Book): NTFS | sdb2 (CIEN): FAT32 | sdb3 (DOS): exfat

```
/etc/cont-init.d/92-local_mounts.sh: executing
Local Disks mounting...
mount: mounting /dev/sdb1 on /mnt/sdb1 failed: Invalid argument
[10:49:44] FATAL: Unable to mount local drives! Please check the name.
[10:49:44] INFO: Success! sdb2 mounted to /mnt/sdb2
mount: mounting /dev/sdb3 on /mnt/sdb3 failed: Invalid argument
[10:49:44] FATAL: Unable to mount local drives! Please check the name.
```

>  sdb1 (My_Book): NTFS | sdb2 (CIEN): FAT32 | sdb3 (DOS): exfat

```
/etc/cont-init.d/92-local_mounts.sh: executing
Local Disks mounting...
mount: mounting /dev/disk/by-label/My_Book on /mnt/My_Book failed: No such file or directory
[10:51:45] FATAL: Unable to mount local drives! Please check the name.
[10:51:45] INFO: Success! CIEN mounted to /mnt/CIEN
mount: mounting /dev/disk/by-label/DOS on /mnt/DOS failed: Invalid argument
[10:51:45] FATAL: Unable to mount local drives! Please check the name.
```

I then formatted DOS to ext4 and it mounted just fine like CIEN (FAT32). No logs copied but I can if needed.

At one point weeks ago I saw _once_ in a log "exfat: format not supported" but I'm not getting that anywhere now.

Thank you

**Comment by alexbelgium** [comment]
Hi, indeed it really is depending on the drivers available. For example, I've added exfat mounting for alpine based addons, but it is broken for Ubuntu/debian based addons.

The safest is really fat32 (most universal, if you need to share the drive) and ext4 (most stable, if you keep your drive connected to a Linux system) when possible...

**Comment by alexbelgium** [comment]
I haven't tested ext2 and ext3 either but I'm sure it will work as native to Linux

**Comment by antonio1475** [comment]
Thanks a lot for the quick clarification! fat32 worked great for the "testing" but I can't keep it due to the 4GB filesize limitation and the 2TB limit (3TB drive).

I'd have loved exfat as I can easily plug into Windows if needed, but no big deal. So I'm transfering files to make it ext4.
Thank you!

**Comment by alexbelgium** [comment]
Well or else if you help me find a way to install exfat support... My key issue is that also it works great on alpine based addons, apt-get install --no-cache exfat-fuse causes an error... It seems the fuse package can't be configured. Looking ln internet it seems to be an old bug that no one has ever solved...

**Comment by antonio1475** [comment]
I would love to, but I have ~0 knowledge on these topics... 😅 I'm sorry. 
Happy to help you with any testing I can do (as a user/beta-tester).

**Comment by alexbelgium** [comment]
;-) I'll still look around, but honestly I also myself have converted all my data to ext4, and use a (paid app) to connect ext4 drives to windows : https://www.paragon-software.com/fr/home/linuxfs-windows/

**Comment by alexbelgium** [comment]
Hi, have you confirmed that FileBrowser doesn't see it ? You can also map it using the default Homeassistant system (that was not existing at the time I created the Filebrowser addon) here : https://www.home-assistant.io/common-tasks/os/#network-storage

**Comment by tiimsvk** [comment]
great thank you now it is visible in the shared folder
