### ISSUE TITLE
Portainer addon update to 2.6.1. failed

### ISSUE THREAD

**Issue by Pulpyyyy** [alexbelgium/hassio-addons#24]
Hi,

Upgrading from 2.6.0 isn't possible
```
The command '/bin/bash -o pipefail -c apk add --no-cache nginx && if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi && if [ "${BUILD_ARCH}" = "armhf" ]; then ARCH="arm"; fi && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="arm"; fi && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi && curl -L -s "https://github.com/portainer/portainer/releases/download/${BUILD_UPSTREAM}/portainer-${BUILD_UPSTREAM}-linux-${ARCH}.tar.gz" | tar zxvf - -C /opt/' returned a non-zero code: 1
```

## System Health

version | core-2021.7.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 4.19.0-17-amd64
arch | x86_64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 919
Installed Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.7
disk_total | 29.9 GB
disk_used | 9.0 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS to MQTT (0.22.0), Home Assistant Google Drive Backup (0.104.3), AppDaemon 4 (0.6.2), Mosquitto broker (6.0.1), Zigbee2mqtt Edge (edge), Portainer (2.6.0), Node-RED (9.2.0), Terminal & SSH (9.1.3), A better presence (1.2.0), Visual Studio Code (3.5.0), Z-Wave JS (0.1.28), ESPHome (1.19.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 28
views | 15
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by rschuiling** [comment]
Same error here, I'm on Home Assistant OS 6.1 / generic x86 (NUC).

**Comment by alexbelgium** [comment]
Hi, portainer github works in a strange way : they publish a version then the executables with a delay (usually a couple hours but up to 2 days). Please try again tomorrow it should work soon!

**Comment by alexbelgium** [comment]
This is due that addon update is automatic based on a github release. But portainer usually releases the sources first, then the versions for each architecture later. This can be checked here : as soon as https://github.com/portainer/portainer/releases/tag/2.6.1 will show assets for architectures and not only sources, it will work.

**Comment by Pulpyyyy** [comment]
Portainer's tag latest is still pointing to 2.6.0, shoudn't it be the trigger to upgrade the addon ?

**Comment by alexbelgium** [comment]
Well lt works for every other repos but they have configured something differently and the latest tag is not captured correctly... I use this program https://github.com/dvershinin/lastversion to fetch the last version tag and it works for all other github repos that I reference for my other addons

**Comment by alexbelgium** [comment]
Portainer build is now active

**Comment by alexbelgium** [comment]
Note to myself : enhancement would be to extract files from docker image rather than from github releases

**Comment by alexbelgium** [comment]
dvershinin has updated his app with an option that will avoid all recurrences of this issue! He has developed a great app to fetch the last versions on github. Don't hesitate to star his repo as he is the one that really solved this issue.

I'll close this
