### ISSUE TITLE
✨ [REQ] Baikal

### ISSUE THREAD

**Issue by lbouriez** [alexbelgium/hassio-addons#242]
Hello, do you think it would be possible to add Baikal to the list of addons ?
(https://hub.docker.com/r/ckulka/baikal)
A caldav / carddav server

**Comment by l-t-k** [comment]
This one would be really great. Trying to ungoogle myself a self hosted cal/cardav server is needed.

A docker for this app already exists:
https://github.com/ckulka/baikal-docker

**Comment by mikedrawback** [comment]
I second this one. I tried to create an addon using the available docker image but I'm struggling with how to handle the persistent data. I have to re-run the install wizard every time I restart!

**Comment by alexbelgium** [comment]
Hi, and here it is !

**Comment by mikedrawback** [comment]
Wow that was fast! I finally got it working by messing with the dockerfiles and doing symlinks...but I really have no idea what I'm doing so I'm switching to yours! 

Glad to see you used the nginx variant, thats what I was using too. Thank you!!!!

**Comment by alexbelgium** [comment]
Well as you were the third interested I made the addon despite not very sure what it  does  :) happy it works! BTW, if during your tests you saw anything useful to implement here don't hesitate to make a PR! Have a nice day
