### ISSUE TITLE
[REQ] ZoneMinder: A NVR/DVR system

### ISSUE THREAD

**Issue by diamant-x** [alexbelgium/hassio-addons#245]
**Which addon?**

ZoneMinder (https://zoneminder.com)

**Is your feature request related to a problem? Please describe.**

Currently the official AddOns offer MotionEye as private self-hosted NVR system to track cameras. However, it is a bit clunky and hard to integrate with other features. HomeAssistant has n[ative integrations](https://www.home-assistant.io/integrations/zoneminder/) with ZoneMinder making it a potential self-hosted alternative. It [was suggested](https://github.com/hassio-addons/repository/issues/31) in the past to the official team but discarded, but that was on 2017 so a lot of time has passed and new solutions would help to develop alternatives.

\*\*If a new addon, have you checked on Google that such as addon doesn't already exists? -> Yes.

**Describe the solution you'd like**

There are instructions on how to setup a docker image in the official docs: https://zoneminder.readthedocs.io/en/latest/installationguide/packpack.html#all-distros-a-docker-way-to-build-zoneminder
There was also someone that used to build a ready-to-use docker image but no longer is keeping it updated (but could be useful for replicating the steps from the source) https://github.com/dlandon/zoneminder.machine.learning
Unfortunately linuxserver.io has no image of this.
There's also this pointers, but they relate to native installation on RPi, not sure if they are relevant or not.
https://wiki.zoneminder.com/Single_Board_Computers

**Describe alternatives you've considered**

Keep using motioneye, although image capture is not steady all the time.

**Additional context**

N/A.

Thanks!

**Comment by alexbelgium** [comment]
Hi, I really don't have much time for the moment so I'm not really doing requests for totally new addons, but I'll keep it here if I have more time in the future

**Comment by alexbelgium** [comment]
Notes : 

https://hub.docker.com/r/yaoa/zoneminder-base
DZM_CONFIG_DIR=/config/addons_config/zoneminder
sed /config /config/addons_config/zoneminder

**Comment by alexbelgium** [comment]
The current docker image makes its very hard to convert in an addon. It won't be an easy thing

**Comment by diamant-x** [comment]
Thanks for taking the time to check it.
It does look lik ethe one from yaoa is the closest to an 'official' one as per comment in https://forums.zoneminder.com/viewtopic.php?p=125701#p125701 they seem to mention they are running https://demo.zoneminder.com/ from that docker version.

Is fine if nothing comes up, just taking the time to check its feasibility was good enough. Maybe in the future this can be revisited. Thanks!

**Comment by alexbelgium** [comment]
The one from yaoa can't really be converted to an addon, as it's too complex to integrate in the HA system. I've done several tests. However I've found another one that I am testing in my -test repository. Currently it boots, but I still need to achieve remanence of the mysql database

**Comment by alexbelgium** [comment]
There should be a first working version pushed now :) weirdly external database don't work but it contains its own mysql database. Please let me know if it works, thanks

**Comment by diamant-x** [comment]
So far it boots up, as soon as i have more time I'll test it further. Thanks!
![image](https://user-images.githubusercontent.com/7346338/158033218-c27b7c02-f0de-4236-bb48-5a344d5083f9.png)

**Comment by alexbelgium** [comment]
Great, I'll close this here but please re-open if you see issues
