### ISSUE TITLE
[Addon name] Issue description

### ISSUE THREAD

**Issue by tomlut** [alexbelgium/hassio-addons#246]
**Which addon?**

- Addon name : Scrutiny
- Addon version : 0.3.13-7

**Describe the bug**

Seeing these warnings in the supervisor log:

```
22-03-10 22:13:02 WARNING (SyncWorker_5) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Scrutiny
22-03-10 22:13:02 WARNING (SyncWorker_3) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Scrutiny
22-03-10 22:55:36 WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Scrutiny
22-03-10 22:55:36 WARNING (SyncWorker_4) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Scrutiny
```
**To Reproduce**

[16:00:00] INFO: Local Devices Added
2022/03/10 17:00:00 Loading configuration file: /scrutiny/config/collector.yaml
time="2022-03-10T17:00:00+11:00" level=info msg="Verifying required tools" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="Executing command: smartctl --scan -j" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="Executing command: smartctl --info -j -d nvme /dev/nvme0" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="Using WWN Fallback" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="127.0.0.1 - db21ed7f-scrutiny [10/Mar/2022:17:00:00 +1100] \"POST /api/devices/register\" 200 488 \"\" \"Go-http-client/1.1\" (1ms)" clientIP=127.0.0.1 hostname=db21ed7f-scrutiny latency=1 method=POST path=/api/devices/register referer= respLength=488 statusCode=200 userAgent=Go-http-client/1.1
time="2022-03-10T17:00:00+11:00" level=info msg="Collecting smartctl results for nvme0\n" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="Executing command: smartctl -x -j -d nvme /dev/nvme0" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="Publishing smartctl results for 50026b72828c3c40\n" type=metrics
time="2022-03-10T17:00:00+11:00" level=info msg="127.0.0.1 - db21ed7f-scrutiny [10/Mar/2022:17:00:00 +1100] \"POST /api/device/50026b72828c3c40/smart\" 200 16 \"\" \"Go-http-client/1.1\" (13ms)" clientIP=127.0.0.1 hostname=db21ed7f-scrutiny latency=13 method=POST path=/api/device/50026b72828c3c40/smart referer= respLength=16 statusCode=200 userAgent=Go-http-client/1.1
time="2022-03-10T17:00:00+11:00" level=info msg="Main: Completed" type=metrics
[17:00:00] INFO: Local Devices Added
2022/03/10 18:00:00 Loading configuration file: /scrutiny/config/collector.yaml
time="2022-03-10T18:00:00+11:00" level=info msg="Verifying required tools" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="Executing command: smartctl --scan -j" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="Executing command: smartctl --info -j -d nvme /dev/nvme0" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="Using WWN Fallback" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="127.0.0.1 - db21ed7f-scrutiny [10/Mar/2022:18:00:00 +1100] \"POST /api/devices/register\" 200 488 \"\" \"Go-http-client/1.1\" (1ms)" clientIP=127.0.0.1 hostname=db21ed7f-scrutiny latency=1 method=POST path=/api/devices/register referer= respLength=488 statusCode=200 userAgent=Go-http-client/1.1
time="2022-03-10T18:00:00+11:00" level=info msg="Collecting smartctl results for nvme0\n" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="Executing command: smartctl -x -j -d nvme /dev/nvme0" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="Publishing smartctl results for 50026b72828c3c40\n" type=metrics
time="2022-03-10T18:00:00+11:00" level=info msg="127.0.0.1 - db21ed7f-scrutiny [10/Mar/2022:18:00:00 +1100] \"POST /api/device/50026b72828c3c40/smart\" 200 16 \"\" \"Go-http-client/1.1\" (12ms)" clientIP=127.0.0.1 hostname=db21ed7f-scrutiny latency=12 method=POST path=/api/device/50026b72828c3c40/smart referer= respLength=16 statusCode=200 userAgent=Go-http-client/1.1
time="2022-03-10T18:00:00+11:00" level=info msg="Main: Completed" type=metrics
[18:00:00] INFO: Local Devices Added

**Full addon config**

**System**
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
Updates: Hourly
PUID: 0
PGID: 0

- Supervisor version: 2022.03.2
- Host system version: HassOS 7.4

**Comment by alexbelgium** [comment]
You can safely ignore this - it is an overeaction of the supervisor :-)

It is by design : the addon can work perfectly fine without full access, but for some people it won't, reason why I had to enable it
