### ISSUE TITLE
[Request] Sharry or Plik file upload tools

### ISSUE THREAD

**Issue by Stooovie** [alexbelgium/hassio-addons#248]
Hi, I'd love if you could add some simple one-click upload tools such as [Plik](https://github.com/root-gg/plik)  or [Sharry](https://eikek.github.io/sharry/doc/quickstart#quickstart-with-docker). Thanks!

**Comment by alexbelgium** [comment]
Hi, actually it already exists here : https://github.com/mdegat01/addon-sharry

I'll then close this request as it already exists

Best regards

**Comment by Stooovie** [comment]
Ah, Sharry is not for ARM... Thanks anyway!

**Comment by alexbelgium** [comment]
Hi, please try installing this : https://github.com/alexbelgium/addon-sharry I've forked his repo and added armv7. If you confirm it works I'll propose this as a PR so he has armv7 on his repo. Thanks!

**Comment by Stooovie** [comment]
I'll have to move my install to ARM 64bit first (I still have my first HA setup from 2019 when 32bit was recommended). But thank you so much for your work, I'll install it ASAP.

**Comment by alexbelgium** [comment]
No, I have modified it to use armv7 if you want using the link above

But honestly moving to arm64 bits is a smart move that I don't regret myself :-)

So should I delete the armv7-modified repo ? If you're not using it I'll delete it it took me 2 min to do :-)

**Comment by Stooovie** [comment]
I can't install it at all, it says "manifest unknown"...

**Comment by alexbelgium** [comment]
Oops - corrected hopefully. If you force refresh the repo and try to reinstall perhaps it will work :-) I don't have an armv7 device to test

**Comment by Stooovie** [comment]
Now it's this 

`The command '/bin/ash -o pipefail -c set -eux; apk update; apk add --no-cache mariadb-client=10.6.4-r2 netcat-openbsd=1.130-r3 openjdk11-jre=11.0.14_p9-r0 ; java -version; echo "Add user for Sharry" mkdir -p /data/sharry; addgroup -S abc; adduser -u 12345 -h /data/sharry -D -S abc -G abc;' returned a non-zero code: 1 `

**Comment by alexbelgium** [comment]
Ok I think I've seen the issue. Could you please force refresh and reinstall? Thanks

**Comment by Stooovie** [comment]
Unfortunately, this: 

`The command '/bin/ash -o pipefail -c set -eux; apk update; apk add --no-cache mariadb-client=10.6.4-r2 netcat-openbsd=1.130-r3 ; java -version; echo "Add user for Sharry" mkdir -p /data/sharry; addgroup -S abc; adduser -u 12345 -h /data/sharry -D -S abc -G abc;' returned a non-zero code: 127`

**Comment by alexbelgium** [comment]
ah ah at least it's not the same error code ;-) perhaps indeed it doesn't work with armv7 then, which would explain why the initial maintainer did do add it :-)

**Comment by Stooovie** [comment]
No this is it, more logs are from different things (localtuya device that is currently physically off). Thanks.

**Comment by alexbelgium** [comment]
127 is a command not found, I've done a last test :)
