### ISSUE TITLE
Please enable ingress

### ISSUE THREAD

**Issue by LoganJFisher** [alexbelgium/hassio-addons#249]
**Which addon?**

Jellyfin NAS

**Describe the solution you'd like**

I would like for [ingress](
https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/) to be enabled such that the web UI would become accessible from the Home Assistant sidebar.

Thank you.

**Comment by alexbelgium** [comment]
Hi, sorry not all apps accept ingress, it depends on their structure. I verified that it doesn't work for emby so I'm confident it won't work for jellyfin as its the same base

**Comment by alexbelgium** [comment]
I'll still do a check and close if it didn't work

**Comment by alexbelgium** [comment]
Good news, ingress in added in the new pushed version : 10.7.7-1-ls155-ingress

**Comment by LoganJFisher** [comment]
That's great! Thank you.

**Comment by alexbelgium** [comment]
mmh it worked on my test environment and not in production. I'll do some more tests

**Comment by alexbelgium** [comment]
ok, should work now in 10.7.7-1-ls155-ingress2
