### ISSUE TITLE
[Request] Update Paperless NG to Paperless NGX

### ISSUE THREAD

**Issue by Nils3311** [alexbelgium/hassio-addons#250]
**Which addon?**

Paperless NG

**Is your feature request related to a problem? Please describe.**

Paperless NG has been deprecated. Under the new name Paperless NGX (https://github.com/paperless-ngx/paperless-ngx) the development will be continued. 
Until now there is no add-on for HassIO.

**Describe the solution you'd like**

It would be great to have a new/updated add-on for the new Paperless NGX.

**Comment by alexbelgium** [comment]
Hi, thanks. Currently linuxserver has not updated its image (https://github.com/linuxserver/docker-paperless-ngx), when they will have done that I'll switch to paperless-ngx

**Comment by alexbelgium** [comment]
Hi, paperless NGX is up! Just update the addon and it will install the new version. Please let me know if there is any breaking change as I don't use the addon myself. Enjoy!

**Comment by Nils3311** [comment]
Thanks! When  I tried to install, I got an error:
Head "https://ghcr.io/v2/linuxserver/paperless-ngx/manifests/arm32v7-latest": unauthorized

**Comment by alexbelgium** [comment]
Argh - it's so fresh they haven't updated their ghcr permissions yet. I'll use the docker one, please wait 5 min, refresh and it should be good
