### ISSUE TITLE
[Request] add JDownloader 2 

### ISSUE THREAD

**Issue by KuchenKavalier** [alexbelgium/hassio-addons#268]
Can we please have a docker container for JDownloader 2? 

As seen here: jlesage/jdownloader-2
https://hub.docker.com/r/jlesage/jdownloader-2

**Comment by alexbelgium** [comment]
Hi, an addon already exists have you tested it? https://github.com/d-two/hassio-addons

Best regards

**Comment by KuchenKavalier** [comment]
Hi,

Thank you for letting me know - I wasn't aware of it!
Yes - seems to work so far. 

Thank you for your lovely work here! 

Best

**Comment by alexbelgium** [comment]
Thanks for the feedback, usually I try to avoid addons duplication as there is already enough fragmentation :)

Envoy the addons!
