### ISSUE TITLE
[Issue] Qbittorrent port 

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#27]
Hi,

Is it possible to have a port configuration change to qbittorrent.
I tried and editted your config file and on login to qbittorrent on the old webui, it is possible to change all the config option.
But when restart or rebuild this is back to default 6881.

From some private torrents and ISP port 6881 is blocked (range 6881-6999 normally).
So it might be best to use a different port for that.

**Comment by alexbelgium** [comment]
Hi, I've removed the automatic reset of port 6881 starting from the next version that I've just pushed ls143-v2. Please tell me if it works!

**Comment by deku-m** [comment]
I changed it in the webgui and looks like it is working. 
But isnt it conflicting with the docker ports 6881 a bit? 
As 6881 is getting blacklisted quite often.

**Comment by alexbelgium** [comment]
Hi, what do you mean conflicting with docker port 6881? Unless I'm mistaken with how docker works, if you keep 6881 in qbittorrent, docker will map this port with whatever you mention in the addon option? And if you change it, it will work it will just show in bittorrent that the port is not available from Internet (which would also be the case with 6881 unless you open a channel in your router)
