### ISSUE TITLE
[webtop] Can't start addon.

### ISSUE THREAD

**Issue by DDanii** [alexbelgium/hassio-addons#274]
**Which addon?**

- Addon name : Webtop Alpine KDE
- Addon version : 4.16-r0-ls49

**Describe the bug**

When I start the addon i get that error: 

Failed to start add-on
Can't start addon_db21ed7f_webtop-kde: 500 Server Error for http+docker://localhost/v1.41/containers/1bf555214decb2f01408fac99b7580b8d31aeaa0bdf9593a8da6e33564fd1fcd/start: Internal Server Error ("error while creating mount source path '/sys/firmware/devicetree/base': mkdir /sys/firmware/devicetree: operation not permitted")

**To Reproduce**

1. Go to 'Addon page'
2. Click on 'Start'

**Full addon log**

no log

**Full addon config**

DNS_server: 8.8.8.8
PGID: 1000
PUID: 1000
additional_apps: engrampa,libreoffice
rpi_video_drivers: false

**System**

- Supervisor version: supervisor-2022.03.5
- Host system version: Home Assistant OS 7.5

**Comment by alexbelgium** [comment]
Hi, that's strange I am have exactly the same setup and it works fine. I've pushed a new version with a modified apparmor. Please let me know if it doesn't. Could you please check if you have an apparmor error in your host or supervisor log when trying to launch the addon?

Otherwise, I'll simply remove the devicetree mapping feature. Thanks!

**Comment by DDanii** [comment]
Hello, now I get an error if I try to install it:

Failed to install add-on
Can't load profile db21ed7f_webtop-kde: Can't load profile '/mnt/data/supervisor/apparmor/db21ed7f_webtop-kde': exit status 1

It is on an Intel singel board machine.

**Comment by alexbelgium** [comment]
OK the new code that I put had an issue. I've replicated this issue and corrected it. Could you please refresh your repo and reinstall? If the device tree error is still there I'll simply remove the feature. Thanks!

**Comment by DDanii** [comment]
Yeah it is still there. I found these logs in supervisor:

22-03-30 19:11:27 ERROR (SyncWorker_4) [supervisor.docker.addon] Add-on Webtop Alpine KDE try to access to blocked device sda!
22-03-30 19:11:27 ERROR (SyncWorker_4) [supervisor.docker.addon] Add-on Webtop Alpine KDE try to access to blocked device sda1!
22-03-30 19:11:28 ERROR (SyncWorker_4) [supervisor.docker] Can't start addon_db21ed7f_webtop-kde: 500 Server Error for http+docker://localhost/v1.41/containers/92836d53887296b4b790f2dda63bf094641ad0db28cd62a8336b3a9e0cf951a2/start: Internal Server Error ("error while creating mount source path '/sys/firmware/devicetree/base': mkdir /sys/firmware/devicetree: operation not permitted")

**Comment by alexbelgium** [comment]
Well, New version pushed without devicetree. Can you please test? thanks

**Comment by DDanii** [comment]
It starts now many thanks.
