### ISSUE TITLE
[Request] Apache Guacamole (Clientless remote desktop)

### ISSUE THREAD

**Issue by KairuByte** [alexbelgium/hassio-addons#276]
Not sure if you're currently taking on new addons, but I'm wondering if you'd be willing to give Apache Guacamole a shot?

It previously had an addon, but that addon was archived/abandoned a while ago, and I can't seem to find any working/updated forks.

Official docker image is here: https://hub.docker.com/r/guacamole/guacamole though that version seems to require three docker images total. None of the single docker image versions seem to be maintained.

Let me know if I can provide any more info!

**Comment by alexbelgium** [comment]
Hi, actually I've already a guacamole based addon : webtop by linuxserver. Due to how HA works, you can't share your screen but at best use guacamole to access the container os, which is what this addon does. Is that what you wanted?

**Comment by KairuByte** [comment]
I was actually hoping for a way to use the addon to connect to internal devices like other servers or machines through the guacamole server. I could be incorrect, but I don't think webtop can handle secondary machines?

**Comment by KairuByte** [comment]
There *is* an existing addon that partially works if you wanted to take a look, it's outdated and seems to have a few bugs, but even on modern HA it does boot up and connect to external machines. The main issue is that it's been abandoned, assumably because ingress had issues that could not be worked through.

Located here: https://github.com/bleakvin/hass-guacamole

**Comment by alexbelgium** [comment]
if webtop doesn't work, I see an existing nice docker image here that perhaps could be transformed in addon : https://docs.linuxserver.io/images/docker-guacd - but I usually try as much as posisble to avoid duplication ;-)

**Comment by KairuByte** [comment]
I might be missing something, but I can't seem to find a way to get the current webtop addon to connect to anything other than the xorg desktop.

As for that docker image, I'm not sure it would be enough? I think the traditional setup is to run guacd in addition to the web client. I've seen a couple images that purport to combine them both, along with a sql server, but I'm not familiar enough with docker to properly speak on how.

**Comment by alexbelgium** [comment]
indeed, I've tried to create a guacd addon (which was easy) but it can't connect without the web client... I'll investigate when I will have more time

**Comment by alexbelgium** [comment]
Not working yet for the moment, I need to solve an s6 issue of changing the log location as /dev/log is read only

**Comment by KairuByte** [comment]
I appreciate the work! I'll keep an eye here for if/when I should give testing a shot. Thank you!

**Comment by KairuByte** [comment]
It may, I'm actually not sure. The thing that drew me towards Guacamole is that everything is handled over HTTPS so client PC's wont throw a fit, and packet shaping wont eat the connections. I can't seem to find any info on how remmina works, and if it would work in a similar way.

**Comment by alexbelgium** [comment]
OK, then let's wait for the guacamole dev to respond... He has kindly created a dev environment to see if he can help with making his container work in our environment

**Comment by alexbelgium** [comment]
New version pushed in my dev repo. At least it installs and boots, still need to do some more tests

**Comment by alexbelgium** [comment]
Hi, the addon is up and running, and should be working!

**Comment by alexbelgium** [comment]
Hi, I'll close the request but feel free to let me know if you encounter any issue

**Comment by KairuByte** [comment]
I finally got a chance to give the new version a shot, but I can't seem to get the UI to open up. I'm trying to connect at `http://[homeassistantip]:[configuredport]/` and `http://[homeassistantip]:[configuredport]/guacamole/` but both result in refused connections. Any thoughts?

**Comment by alexbelgium** [comment]
Thanks, it's a stupid bug I had implemented ingress then removed it due to incompatibilities and forgot to reset the relevant elements. I'll remove them and push a new version

**Comment by alexbelgium** [comment]
New version pushed and tested working

**Comment by alexbelgium** [comment]
Great thanks! I'll close it for the moment if it works
