### ISSUE TITLE
[Request] BeEF

### ISSUE THREAD

**Issue by rjgout** [alexbelgium/hassio-addons#277]
Hi, can you add Beef: https://hub.docker.com/r/phocean/beef

**Comment by alexbelgium** [comment]
Hi, I am sorry, I prefer not to implement addons that might be seen as potential security risks. You can still run it manually using the portainer addon, though (there are lots of guides on internet how to deploy an image using portainer). It will work as if it was an addon, only downside is the lack of updates. Best regards
