### ISSUE TITLE
Request: xTeVe (m3u proxy) for jellyfish/emby/plex

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#28]
Hi,

I found out when using plex/emby/jellyfish and you use IPTV (m3u file) for those apps its a bit limited.

They point to use https://github.com/xteve-project/xTeVe (xTeve) as a virtual M3u adapter.
Its a M3U Proxy for Plex DVR and Emby Live TV.

Can you perhaps make a addon for this?
Sorry for the many request.

**Comment by alexbelgium** [comment]
Hi, there seems to be a good docker image, I'll look at it in the coming days!

**Comment by alexbelgium** [comment]
Hi! The addon is up and seems to work :-) just install and go to http://url:port/web

/config and /share from the host are exposed to allow integration with other addons (the other addons need to share their m3u files on one of those folders).

Let me know if it works!

**Comment by deku-m** [comment]
It works perfectly :)

**Comment by alexbelgium** [comment]
Perfect, thanks!

**Comment by alexbelgium** [comment]
> It works perfectly :)

Don't hesitate to star my repo if the addons are useful!
