### ISSUE TITLE
Merging containers into the 'community' addons project?

### ISSUE THREAD

**Issue by JeffersonBledsoe** [alexbelgium/hassio-addons#282]
Just stumbled across this repo whilst looking for a Joplin add-on and there's a number of amazing add-ons in here! I was wondering if you'd consider adding some of them to the [Home Assistant Community Add-ons project](https://github.com/hassio-addons)? This should make them easier to be discovered by others and allow others to contribute back to your addons.

**Comment by alexbelgium** [comment]
Hi, thanks for the feedback! I'm not part of the HA organisation, and am not looking for it. Merging with the community repo would be more complex for me, and probably unwelcomed by the current owners. I remember that they mention some time ago that they were not looking to add new addons to it. Actually I think Frenckx is the main maintainer of this repo, and doing an amazing job at that. So in summary, although indeed I see the added benefit for the users of your idea, I will keep this repo standalone as a personal hobby. Best regards
