### ISSUE TITLE
[Webtop KDE] - Timezone not working

### ISSUE THREAD

**Issue by Mdleal** [alexbelgium/hassio-addons#297]
I can't get timezone to do anything. I'm using America/Chicago. I've tried others.

DNS_server: 192.168.1.3
PGID: 1000
PUID: 1000
additional_apps: engrampa
rpi_video_drivers: false
KEYBOARD: en-us-qwerty
TZ: America/Chicago

**Comment by alexbelgium** [comment]
Hi, thanks for reporting. To be sure to understand, the custom keyboard works but not the TZ value? As both use in theory the same processus

Thanks!

**Comment by alexbelgium** [comment]
Update: I've found the issue, please update to 4.16-r0-ls52-2 and let me know if it works! Thanks

**Comment by Mdleal** [comment]
Same after update. Timezone does not change from UTC. Nothing stands out in the logs.

**Comment by Mdleal** [comment]
I did that as a test. It appears to do nothing as well. On screen keyboard does not change and neither does settings in the OS.

**Comment by alexbelgium** [comment]
Mmh good news at least the behavior is the same for both. Thanks I'll investigate tomorrow

**Comment by alexbelgium** [comment]
Hi, so I've done some tests.
- KEYBOARD : it is actually applied, but applies only to the virtual keyboard on the left of the screen, accessed when clicking on the little black ball
- TZ : should be corrected in 4.16-r0-ls52-3

Best regards

**Comment by Mdleal** [comment]
Awesome. That did it. 

Thank you
