### ISSUE TITLE
Overseerr

### ISSUE THREAD

**Issue by ikrowni** [alexbelgium/hassio-addons#298]
**Which addon?**

Overseerr
https://docs.overseerr.dev/getting-started/installation

**Is your feature request related to a problem? Please describe.**

no

\*\*If a new addon, have you checked on Google that such as addon doesn't already exists?

yes

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by alexbelgium** [comment]
Hi, if you're still interested I've created the addon ;-)

**Comment by ikrowni** [comment]
> Hi, if you're still interested I've created the addon ;-)

Damn dude that was quick. I appreciate it. I ended up closing this shortly after posting because I found the requestrr service and it's pretty cool. If I find need for it still I'll be back here to get it.

RDTclient would be another cool one to have it's a downloader that works with real debrid. 

Thanks again dude your support is top notch.
