### ISSUE TITLE
Nextcloud: returned a non-zero code: 2

### ISSUE THREAD

**Issue by poudenes** [alexbelgium/hassio-addons#3]
Hello,

I was trying to install Nextcloud AddOn but get this error message:

The command '/bin/sh -c apk update' returned a non-zero code: 2

RPI4 2GB
Home Assistant 2021.1.4
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.79-v8+
CPU Architecture | aarch64
Timezone | Europe/Amsterdam

**Comment by alexbelgium** [comment]
Hi, Could you please provide more info such as your system and architecture (arm,...)? Thanks

**Comment by poudenes** [comment]
> Hi, Could you please provide more info such as your system and architecture (arm,...)? Thanks

Already did now. I was forgotten to add it

**Comment by alexbelgium** [comment]
Thanks, could you please refresh the repo manually (it's located on the same menu where you add manually repos), then try to reinstall? I've declared the shell to bash and slightly modified the code to see if it works. Thanks :)

**Comment by poudenes** [comment]
I get this error now:

`The command '/bin/bash -o pipefail -c apk add tesseract-ocr' returned a non-zero code: 1`

**Comment by alexbelgium** [comment]
OK, I've removed the OCR addition... Now my code should be near exactly the same as community one. Could you please reload the repo and try again to install?

If it works, I'll add OCR through a config option and not by default.

Thanks!

**Comment by poudenes** [comment]
I installed now the nextcloud and r start it. No errors now.

My internet is stable and running good. All official addons where installed all correct in past.

**Comment by alexbelgium** [comment]
Glad it worked! I'll then add in a couple days the code for OCR in a script that will execute only if a specific option is set.

Actually, installation of official addons could still work as they are usually downloaded as precompiled images in dockerhub, compared to addons such as this one that are based on an image but then modified on your machine... Well anyway as long as it works. I'll then close the issue.

**Comment by poudenes** [comment]
Nextcloud is running now. Installation itself of nextcloud went OK also.. All apps installed correct. 

I have a nextcloud running. But maybe this is better. The current one is running on his own rpi4.

If this new one is not to heavy running in a docker then its easier to install when needed.

Sometimes my current is crashing. Hope not the one in docker will crash my HA system.. Hehe

**Comment by alexbelgium** [comment]
Glad to read that. Currently I'm running nextcloud on a rpi3b+ rather reliably, so I would expect that it should also run fine on your rpi4! If it's crashing you might check your power supply or sdcard. It used to crash also and by updating those (I use the official rpi 4 power supply, and a SanDisk max endurance sd card) it worked much more smoothly.

BTW, do you use a vpn? Or have a dns blocker such as adguard home?

**Comment by poudenes** [comment]
For my HA I don't use VPN. I did a test to upload photos. Cpu increase to 82% usage. And cpu temp from 44 to 55 degrees celcius. 

I will do some test if the upload doesn't change the performance of HA itself or get some lag.

**Comment by poudenes** [comment]
one little off-topic. Can I mount a USB HDD drive as local external storage in a Nextcloud Docker?

**Comment by alexbelgium** [comment]
The easiest way to do it is :
- either mount the usb hdd in your debian system at a mount point available to the addon (such as /share), it should be accessible to nextcloud
- install the [SambaNas ](https://github.com/dianlight/hassio-addons) addon to share your local USB HDD through smb on your network, then install the "external storage" application on nextcloud, and add the smb share to your system

I haven't added the possibility to mount a local drive as using SMB is more convenient and avoids mounting the same drive at different places on the same system.

**Comment by poudenes** [comment]
Added SambaNas, was little confusing to add the shared into Nextcloud. But it work.
Now I do a test with a big folder that now is syncing to Nextcloud with a 1.5TB External HDD (Has is own power supply)

85GB with a calculated time of 4 hours to be done... 
Now also see if HA is working smooth. CPU usage start with 88% and now its between 46-60%

**Comment by poudenes** [comment]
Is there a way to create backups of the database? If Nextcloud must be installed again because of a reason?
I can imagine that this add-on can go into snapshot. (I know databases of MariaDB always give error when restore, because its running while backup)

If I backup the add-on of Nextcloud, and restore it back will this work? My data is stored external, so after a restore and database is working, everything must work normal?

**Comment by alexbelgium** [comment]
Hi, I recommend the great plugin here. https://github.com/sabeechen/hassio-google-drive-backup
It automatizes snapshots, and uploads them to a google drive. It has the option to stop the addons before making the snapshot, avoiding the issue that you noted of backuping running databases. 

Also as you mention MariaDB - I suppose that you use it also with Nextcloud? With such a big database, the default sqlite would be a limiting factor. The nextcloud sqlite database is in its own container and backuped/restored at the same time as the addon, however if you use another database such as MariaDB it might be even easier.

Btw, data is independent of the database if you store it on an external hdd that communicates with smb. So if you delete the addon, there is no impact on the addon. You'll just need to re-index after re-installing the addon.

**Comment by poudenes** [comment]
Thanks for all the information. I use the Google Drive Backup. Great app indeed.
After my test with a backup of 82GB to Nextcloud > SMB > External HDD I see a performance change of HA.
Little slower then normal, and with big scenes I use I see it skips some lights. So I went back to NextcloudPi on its own Pi.

Maybe when I get a RPi4 with 4GB instead of 2GB now, it will goes better. I love the way how easy Nextcloud can be installed. Ok NextcloudPi is also very easy with his installer. 

Im still hope your Bitwarden will work later on... Lets hope we find the solution.

**Comment by poudenes** [comment]
Ok, tried install your Nextcloud again and now I get this error popup in the Add-on screen of HA:

`The command '/bin/bash -o pipefail -c +e apk add --no-cache curl jq && curl -J -L -o /tmp/bashio.tar.gz "https://github.com/hassio-addons/bashio/archive/v0.7.1.tar.gz" && mkdir /tmp/bashio && tar zxvf /tmp/bashio.tar.gz --strip 1 -C /tmp/bashio && mv /tmp/bashio/lib /usr/lib/bashio && ln -s /usr/lib/bashio/bashio /usr/bin/bashio && rm -fr /tmp/bashio.tar.gz' returned a non-zero code: 1`

**Comment by alexbelgium** [comment]
Could you add the full supervisor error log ? I added a fake package to check how it would fail on my system, and actually the last lines of the failure provide the exact issue. This is an error code 1, but the last lines of the log provide the error (package a does not exist) 

Example :
``
21-01-20 20:33:58 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build db21ed7f/armv7-addon-nextcloud_ocr:20.0.5-ls113: The command '/bin/bash -o pipefail -c set +e     && apk add --no-cache     curl jq a     && curl -J -L -o /tmp/bashio.tar.gz     "https://github.com/hassio-addons/bashio/archive/v0.10.1.tar.gz"     && mkdir /tmp/bashio     && tar zxvf     /tmp/bashio.tar.gz     --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -fr /tmp/bashio.tar.gz' returned a non-zero code: 1
21-01-20 20:33:58 ERROR (SyncWorker_2) [supervisor.docker.addon] Build log: 
Step 1/16 : ARG BUILD_FROM
Step 2/16 : ARG BUILD_VERSION
Step 3/16 : FROM ${BUILD_FROM}-${BUILD_VERSION}
 ---> 14d1bfb6d300
Step 4/16 : ENV NEXTCLOUD_PATH="/data/config/www/nextcloud"
 ---> Using cache
 ---> 49625462d2ff
Step 5/16 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Running in 320f153b18b0
Removing intermediate container 320f153b18b0
 ---> 6252dfb3b092
Step 6/16 : RUN set +e     && apk add --no-cache     curl jq a     && curl -J -L -o /tmp/bashio.tar.gz     "https://github.com/hassio-addons/bashio/archive/v0.10.1.tar.gz"     && mkdir /tmp/bashio     && tar zxvf     /tmp/bashio.tar.gz     --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -fr /tmp/bashio.tar.gz
 ---> Running in a91b5c68623e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
ERROR: unable to select packages:

  a (no such package):
    required by: world[a]
Removing intermediate container a91b5c68623e
``

**Comment by poudenes** [comment]
Here you are:

```
21-01-20 21:04:38 INFO (SyncWorker_6) [supervisor.docker.addon] Starting build for db21ed7f/armv7-addon-nextcloud_ocr:20.0.5-ls113
21-01-20 21:04:41 ERROR (SyncWorker_6) [supervisor.docker.addon] Can't build db21ed7f/armv7-addon-nextcloud_ocr:20.0.5-ls113: The command '/bin/bash -o pipefail -c +e apk add --no-cache     curl     jq     && curl -J -L -o /tmp/bashio.tar.gz     "https://github.com/hassio-addons/bashio/archive/v0.7.1.tar.gz"     && mkdir /tmp/bashio     && tar zxvf     /tmp/bashio.tar.gz     --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -fr /tmp/bashio.tar.gz' returned a non-zero code: 1
21-01-20 21:04:41 ERROR (SyncWorker_6) [supervisor.docker.addon] Build log: 
Step 1/16 : ARG BUILD_FROM
Step 2/16 : ARG BUILD_VERSION
Step 3/16 : FROM ${BUILD_FROM}-${BUILD_VERSION}
 ---> 14d1bfb6d300
Step 4/16 : ENV NEXTCLOUD_PATH="/data/config/www/nextcloud"
 ---> Using cache
 ---> e4f3b449ca83
Step 5/16 : SHELL ["/bin/bash", "-o", "pipefail", "-c", "+e"]
 ---> Using cache
 ---> 28405cc29340
Step 6/16 : RUN apk add --no-cache     curl     jq     && curl -J -L -o /tmp/bashio.tar.gz     "https://github.com/hassio-addons/bashio/archive/v0.7.1.tar.gz"     && mkdir /tmp/bashio     && tar zxvf     /tmp/bashio.tar.gz     --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -fr /tmp/bashio.tar.gz
 ---> [Warning] The requested image's platform (linux/arm) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 9cb7d648d55a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  jq (no such package):
    required by: world[jq]
Removing intermediate container 9cb7d648d55a
```

**Comment by poudenes** [comment]
Reload the repo and now the install work...

**Comment by alexbelgium** [comment]
Thanks for the full log, indeed the docker cannot connect to alpine repositories to download the packages. Weird.

I added actually a bit of code that cancels the error so it builds regardless of the error... Just hope it also starts fine or else I'll need to add the same code to the script that manages the OCR options (install tesseract ocr + language files)

**Comment by poudenes** [comment]
Install is working now. Im now finish the setup!

**Comment by alexbelgium** [comment]
Great!!! Happy it works, and it means I can continue updating it without fearing to break it ;)

Thanks for your troubleshooting. Have fun with nextcloud!
