### ISSUE TITLE
[addons_updater] API and config

### ISSUE THREAD

**Issue by jdeath** [alexbelgium/hassio-addons#303]
addons_updater

Trying to use your updater to keep my addons in sync. I found 3 issues before I got it to work:

1. schema requires an extra "repository" tag set in the root of the config. Just needs to be added to documentation
2. non-API commits are disabled by github now, but commit line uses password instead of gitapi.
3. remove git config --system user.email "${GITMAIL}" as github says email will be included in commit.

I fixed in a local version and seems to work.

also had to add updater.json, which is not in documentation. perhaps this is not necessary if authentication worked.

**Comment by alexbelgium** [comment]
Hi, actually you downloaded it at a really bad time :) I'm in the process since yesterday of competely changing the logic and base the infos on an updater.json instead of the addon options.

That explains the fact that 1) it doesn't work, 2) documentation is not up to date

I was doing it live on production as I didn't thought anyone was using it. I apologise. I'll put back the normal version (back to 2.4), which works great

**Comment by alexbelgium** [comment]
EDIT : ah I see it is working for you... So I'll keep v3 then but update documentation and config.json

Mmh I'm surprised by your points 2 and 3, I still do it that way and don't have issues (and commits don't reference my email)...

I'll iron out the remaining issues and let you know when v3 is fully ready :)

**Comment by alexbelgium** [comment]
Updater.json contains all infos needed for the update (upstream repo, upstream version...) that were previously in the addon options. This allows I think a more robust updater, and to lead the way to converting this addon in a github action!

**Comment by alexbelgium** [comment]
Hi, the addon is now fully working with the new updater.json logic in v3.8
I've also rewritten the Readme. Could you please check if everything is clear ? Thanks very much!
And thanks for using this addons, I wasn't aware a fellow dev was interested in this ;-)

**Comment by jdeath** [comment]
I thought i would try it on a whim. I guess I should have checked if being update! Just tried 3.8.1 and works except for the push to github.
documentation looks good (maybe code quote the config.json so cany copy paste). Also, there is a mention of 2 ports, which must be from another addon
But peering into the code, i think will need to: (at least for my account)
remove the gitmail or do not set if use the API. Perhaps your setup has your email public, the git complains if it is set for me and instructs me to change my account settings if want to commit
If use gitapi, the update command should be
git remote set-url origin "https://${GITUSER}:${GITHUB_API_TOKEN}@github.com/${REPOSITORY}" &>/dev/null

**Comment by alexbelgium** [comment]
Thanks, I'll investigate and update

**Comment by alexbelgium** [comment]
Hi, I'll investigate your points, anything making the addon more robust is good to know ;)

And gitlab is supported by the app used to check the upstream version (https://github.com/dvershinin/lastversion) so it will be easy to implement too :)

**Comment by alexbelgium** [comment]
Hi, in 3.8.2 there are the following changes :
- Github email optional
- Additional supported sources: dockerhub,github,gitlab,bitbucket,pip,hg,sf,website-feed,local,helm_chart,wiki,system,wp

I'll check again the git api thing

**Comment by jdeath** [comment]
Thanks for changes.

I think 186 should be:
        if bashio::config.has_value 'gitapi'; then
not
 if bashio::config.has_value 'GITHUB_API_TOKEN'; then

Also, do you run this manually every couple days? I'l try the gitlab capability later ! Thanks so much.

**Comment by alexbelgium** [comment]
Yup, you're right, I've pushed yet another version ;)

I've set an automation in my HA instance so it runs on Monday, Wednesday, and Fridays. There is also an automated github action that builds upon update, which allows checking that there is no upstream change that prevents building

**Comment by alexbelgium** [comment]
I've pushed a new version solving the beta tag : it should have been "github_beta" and not "beta"

**Comment by jdeath** [comment]
github works perfect now! Awesome. Great idea with the automation, that is super slick!

I am having trouble with gitlab, but that is for another day. I think it is because both the code and docker image is hosted on gitlab. The source is set to gitlab in the updator.json
 I get:
[18:56:13] INFO: ... updating jdeath/homeassistant-addons
[18:56:14] INFO: ... earthwalker : checking slug exists in repo
[18:56:14] INFO: ... earthwalker : get current version
[18:56:14] INFO: ... earthwalker : fulltag is on
[18:56:14] INFO: ... earthwalker : asset_only is off
[18:56:14] INFO: ... earthwalker : beta is on
No such project found on GitHub: glatteis/earthwalker

**Comment by alexbelgium** [comment]
Thanks, indeed it uses now the - - at tag to specify the source... I'll check if we have to fill a bug report in lastversion, if you have not it already. 

Great too know that it is working with full url! Indeed I also have an addon without upstream releases (or just latest), which prevents it from working...

**Comment by alexbelgium** [comment]
Hi, the gitlab bug is fixed by the lastversion dev so everything is working in the new version. Have fun!

**Comment by alexbelgium** [comment]
Hi, I implemented a "paused" tag if you need to pause update for some time
