### ISSUE TITLE
[Request] Calibre Server

### ISSUE THREAD

**Issue by phgsbr** [alexbelgium/hassio-addons#304]
Hey @alexbelgium !

Could you port Calibre Web to Home Assistant add-ons?

Thank you!

**Comment by alexbelgium** [comment]
Hi, you are mentioning two things : calibre server and calibre Web access are different apps. I suppose this is what you want? https://github.com/linuxserver/docker-calibre

**Comment by phgsbr** [comment]
> Hi, you are mentioning two things : calibre server and calibre Web access are different apps. I suppose this is what you want? https://github.com/linuxserver/docker-calibre

Sorry, I made a mistake. This is the correct!

**Comment by alexbelgium** [comment]
I'm testing an addon, but it's a bit more complex that I thought. Have you also tried ubooquity? It's user interface is much better.

**Comment by alexbelgium** [comment]
Calibre by linuxserver is broken for the moment, we'll have to wait for an update https://github.com/linuxserver/docker-calibre/issues/81

**Comment by alexbelgium** [comment]
OK the addon is up! Please let me know if everything works!

**Comment by phgsbr** [comment]
Thank you! You're the best!

**Comment by alexbelgium** [comment]
Everything works fine?

**Comment by phgsbr** [comment]
Sorry about late response: the guacamole screen, to set the library, works perfectly. But the port to web UI don't load anything. I tried to change the settings, but was not successful.

**Comment by alexbelgium** [comment]
The port to which webui doesn't work? As I think  the only UI is through guacamole, and the other port is for access through a third party client?

**Comment by alexbelgium** [comment]
I've also created the linuxserver calibre web container for a reader

**Comment by phgsbr** [comment]
> 

The 8080 port is used to configure the database like a windows, using a Guacamole ui. The 8081 is used to access the Calibre Web UI. I can configure the database but i cant access the Calibre UI, the browser cant reach the page.

**Comment by alexbelgium** [comment]
According to the documentation above : "Port 8081 is reserved for Calibre's built-in webserver, which can be enabled within the desktop app settings, and the internal port must be set to 8081 although it will then be available at the host mapped port for external access."

I think you need to enable it manually from the desktop app for it to work
