### ISSUE TITLE
Request: Ombi Port

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#31]
Hey, I really love these. Is there a chance that you could add Ombi https://ombi.io ? It's a real nice webui that communicates with Sonarr and Radarr. Thanks

**Comment by alexbelgium** [comment]
That's perfect as it already uses my other addon structure. The build is up, please refresh your addons market and let me know if it works!

**Comment by hacshacdgacs** [comment]
Thank you, it works perfectly

**Comment by tbaumann** [comment]
> What are the right settings to connect to Sonarr and Radarr? Ombi always says it can't connect. Perhaps I have to do something unexpected in a homeassistant environment?

PEBCAK - The ingress url don't work. But the direct ports do work
