### ISSUE TITLE
Request: Unpackerr

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#312]
Hey there, another request if you wouldn't mind. It's called Unpackerr. It's useful for things like Sonarr and Radarr as it links to them and automatically extracts any compressed files they may download. I've put the docker link below. Thanks for all these btw. 

https://hub.docker.com/r/golift/unpackerr

**Comment by alexbelgium** [comment]
Thanks, I'll look at that when I have some time. It really depends on the quality of the upstream container. For example, a container made by linuxserver is very fast to convert in an addon. Containers made by other people can be very long, or impossible to convert depending on the case (for example I haven't find a way to convert containers using s6v3 as overlay)

**Comment by alexbelgium** [comment]
Hi, the addon is up and running. Please read carefully the Readme (everything is configured through a config file that you need to create manually) and let me know if it works. Accessible shared folders are /media, /config and /share

**Comment by hacshacdgacs** [comment]
Hey sorry just got around to trying to install this now however it's failing on my end it seems. 
![image](https://user-images.githubusercontent.com/85550264/167252392-92a2e7b4-7fb0-4179-8b1b-810d5d07d7f7.png)

**Comment by alexbelgium** [comment]
That's very strange, given that for me it works :) I've pushed a new name for the version to force an image creation. Could you test again? Thanks

**Comment by hacshacdgacs** [comment]
It's working now, thank you

**Comment by alexbelgium** [comment]
Thanks
