### ISSUE TITLE
🐛 [Zoneminder] Storage

### ISSUE THREAD

**Issue by snellie1972** [alexbelgium/hassio-addons#314]
Hi ,
A question about Zoneminder

how can I change the storage path from /var/cache/zoneminder/events from within Docker to the outside docker /media

thanks in advance 

greetings Jan

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version allowing to set the directory from addons options, please let me know if it works

**Comment by alexbelgium** [comment]
Hi, thanks for the feedback. Could you please describe the steps that you take to arrive at this error message? It will allow me to replicate and find the solution.

Thanks, best regards,
Alexandre

**Comment by snellie1972** [comment]
Ok I have update the addon and then I went to the configuration tab 
On the field  images_location I have filled in the proper dir for my system / media/camera
Then restarted the addon and opened the webpage.
I have deleted all events and waited for a new one but when I tried to open the event it still is pointed to the var/cache/zoneminder/events

I have also deinstalled the addon and installed it again but it makes no different.
I have opened the container with portainer and looked at the volumes for Zoneminder and I can see that the volumes pointed to var/cache/zoneminder/events

I hope you have enough information Thanks in advance 

Greets Jan

**Comment by alexbelgium** [comment]
I thought variables would do the trick, but indeed they don't. Have you noticed however you can set the storage location in Options / Storage from within the webui ?

I'll still investigate how to change by default the path

**Comment by snellie1972** [comment]
Yes I can changeover storage path within the webui but unfortunately it does’nt change the storage path 

thanks
