### ISSUE TITLE
[qBittorrent] Set global transfer speed limits (as well as alt limits)

### ISSUE THREAD

**Issue by pullaf** [alexbelgium/hassio-addons#315]
**Which addon?**
qBitTorrent

**Is your feature request related to a problem? Please describe.**
Either I'm blind or I can't find a way to set the down/upload speeds in the WebUI, be it normal or alternate limits

\*\*If a new addon, have you checked on Google that such as addon doesn't already exists?
Not applicable

**Describe the solution you'd like**
Just 4 new fields, for the 4 speed limits

**Describe alternatives you've considered**
Setting the speed on each torrent is an alternative, but not really viable as it's not global

**Additional context**

**Comment by alexbelgium** [comment]
Hi, good idea... not sure how that would work though.

There is an integration but without toggles : https://www.home-assistant.io/integrations/qbittorrent/.

The best way is to use an automation to stop the addon, change manually the qbittorrent.conf relevant file, then restart the addon.

Here is where the idea comes from : https://unix.stackexchange.com/questions/59237/is-there-a-workaround-for-a-lack-of-scheduler-in-qbittorrent

**Comment by alexbelgium** [comment]
Hi, mimicking a click won't be possible I think. However, the config file is exposed in /config/qBittorrent/qBittorrent.conf which is accessible by HA. it will allow this type of automation, but only if the addon is stopped before modifying the file

**Comment by pullaf** [comment]
It's not really a matter of simulating a click, it's just as easy as doing this call: POST /api/v2/transfer/toggleSpeedLimitsMode 

Not sure where those api are exposed with your addon though, if you could help me out with that I think it should be trivial to create a curl script to execute through HA

**Comment by alexbelgium** [comment]
Thanks! I was going to say that. If you have opened the port, you can use that as you said. If you have only ingress, you need to use the ingress call api for that. I'll modify the script to write in the addon log the ingress url

**Comment by pullaf** [comment]
Well, that was even easier than I expected, I didn't even need to get home

`shell_command:
  toggle_torrent_speed: curl -X POST https://<HA IP>:8081/api/v2/transfer/toggleSpeedLimitsMode -k`

Simply call it with shell_command.toggle_torrent_speed and that's it, it takes less than a second to have it updated in the UI as well

**Comment by alexbelgium** [comment]
Great, thanks! I'll add that to the Readme

**Comment by pullaf** [comment]
Thanks
Also, a little extra:

`-sensor:
  - platform: get_torrent_speed
    command: curl https://<HA IP>:8081/api/v2/transfer/speedLimitsMode -k`

This will expose a sensor that returns 0 if the speed isn't limited and 1 if the alt speed are enabled, since the toggle API doesn't let you choose which speed you want it might help to check beforehand whether it's already active or not

**Comment by alexbelgium** [comment]
That's great, thanks very much ! and thanks for the PR
