### ISSUE TITLE
[Emby & Ubooquity] No longer able to mount network drives. 

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#319]
Essentially in the last couple of days, my Emby hasn't been able to mount any of the folders in mnt (Edit: I've also noticed that ubooquity has the same issues of being unable to mount). All my libraries are still configured to be reading from their files and send back 'no playback streams available' and when I go to set up a new library my mnt folder is empty. All my other addons from here (Radarr, Sonarr, Qbittorrent) however are able to access these folders with no issues. Attached is an image showing Radarr accessing with no issues and what I see from Emby. Also attached is my Emby config.

![image](https://user-images.githubusercontent.com/85550264/167317088-9d44d73d-0803-4a79-a6ec-743cee8d42aa.png)
![image](https://user-images.githubusercontent.com/85550264/167317106-3590d9c5-0175-4325-8030-622e1fbac7e9.png)
![image](https://user-images.githubusercontent.com/85550264/167317152-737334d0-e851-440d-a062-b3dd61b6be83.png)

Thank you for any help

**Comment by alexbelgium** [comment]
Hi, I've just tested and reinstalled emby and it mounts fine.

Can you please provide a log from the addon ? 

Thanks!

**Comment by hacshacdgacs** [comment]
I'll attach a copy of the logs now, as far as permissions are concerned I haven't changed anything so I'd assume it's not that. 

Info CoverArt: CoverArt plugin started with SkiaCoverArtImageProcessor image processor
Info App: Entry point completed: CoverArt.ServerEntryPoint. Duration: 0.0392775 seconds
Info App: Starting entry point playback_reporting.EventMonitorEntryPoint
Info PlaybackReporting - EventMonitorEntryPoint: EventMonitorEntryPoint Running
Info PlaybackReporting - EventMonitorEntryPoint: Sqlite version: 3.35.5
Info PlaybackReporting - EventMonitorEntryPoint: Sqlite compiler options: COMPILER=gcc-8.3.0,ENABLE_COLUMN_METADATA,ENABLE_DBSTAT_VTAB,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS3_TOKENIZER,ENABLE_FTS4,ENABLE_FTS5,ENABLE_GEOPOLY,ENABLE_JSON1,ENABLE_MATH_FUNCTIONS,ENABLE_PREUPDATE_HOOK,ENABLE_RTREE,ENABLE_SESSION,ENABLE_UNLOCK_NOTIFY,ENABLE_UPDATE_DELETE_LIMIT,LIKE_DOESNT_MATCH_BLOBS,MAX_SCHEMA_RETRY=25,MAX_VARIABLE_NUMBER=250000,OMIT_LOOKASIDE,SECURE_DELETE,THREADSAFE=1
Info PlaybackReporting - EventMonitorEntryPoint: Default journal_mode for /emby/data/playback_reporting.db is delete
Info PlaybackReporting - EventMonitorEntryPoint: Initialize PlaybackActivity Repository
Info PlaybackReporting - EventMonitorEntryPoint: PlaybackActivity table schema OK
Info PlaybackReporting - EventMonitorEntryPoint: Expected : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int|pauseduration:int
Info PlaybackReporting - EventMonitorEntryPoint: Received : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int|pauseduration:int
Info App: Entry point completed: playback_reporting.EventMonitorEntryPoint. Duration: 0.007603 seconds
Info App: Starting entry point Emby.Security.PluginSecurityManager
Info App: Entry point completed: Emby.Security.PluginSecurityManager. Duration: 5.16E-05 seconds
Info App: Starting entry point IntroSkip.IntroSkipPluginEntryPoint
Info PlaybackReporting - EventMonitorEntryPoint: PlaybackMonitoringTask : Started
Info App: Entry point completed: IntroSkip.IntroSkipPluginEntryPoint. Duration: 0.0102851 seconds
Info App: Starting entry point IntroSkip.VideoBlackDetect.VideoBlackDetectionManager
Info App: Entry point completed: IntroSkip.VideoBlackDetect.VideoBlackDetectionManager. Duration: 5.14E-05 seconds
Info App: Starting entry point IntroSkip.Statistics.StatsManager
Info App: Entry point completed: IntroSkip.Statistics.StatsManager. Duration: 0.0003971 seconds
Info App: Starting entry point IntroSkip.RemoteControl.AutoSkip
Info App: Entry point completed: IntroSkip.RemoteControl.AutoSkip. Duration: 0.0002519 seconds
Info App: Starting entry point IntroSkip.Detection.SequenceDetection
Info App: Entry point completed: IntroSkip.Detection.SequenceDetection. Duration: 4.46E-05 seconds
Info App: Starting entry point IntroSkip.Detection.SequenceDetectionManager
Info App: Entry point completed: IntroSkip.Detection.SequenceDetectionManager. Duration: 4.27E-05 seconds
Info App: Starting entry point IntroSkip.Chapters.ChapterErrorTextFileCreator
Info App: Entry point completed: IntroSkip.Chapters.ChapterErrorTextFileCreator. Duration: 0.0003043 seconds
Info App: Starting entry point IntroSkip.Chapters.ChapterInsertion
Info App: Entry point completed: IntroSkip.Chapters.ChapterInsertion. Duration: 4.47E-05 seconds
Info App: Starting entry point IntroSkip.AudioFingerprinting.AudioFingerprintManager
Info App: Entry point completed: IntroSkip.AudioFingerprinting.AudioFingerprintManager. Duration: 0.0003265 seconds
Info App: Starting entry point MediaBrowser.Plugins.Trailers.EntryPoint
Info App: Entry point completed: MediaBrowser.Plugins.Trailers.EntryPoint. Duration: 0.0008905 seconds
Info App: Starting entry point Emby.PortMapper.ExternalPortForwarding
Info App: Entry point completed: Emby.PortMapper.ExternalPortForwarding. Duration: 0.0016093 seconds
Info App: Starting entry point Emby.Security.PluginSecurityManager
Info App: Entry point completed: Emby.Security.PluginSecurityManager. Duration: 3.57E-05 seconds
Info App: Starting entry point Emby.Server.CinemaMode.IntrosEntryPoint
Info App: Entry point completed: Emby.Server.CinemaMode.IntrosEntryPoint. Duration: 9.29E-05 seconds
Info App: Starting entry point Tvdb.EntryPoint
Info App: Entry point completed: Tvdb.EntryPoint. Duration: 3.77E-05 seconds
Info App: Starting entry point Emby.Api.ApiEntryPoint
Info App: Entry point completed: Emby.Api.ApiEntryPoint. Duration: 3.24E-05 seconds
Info App: Starting entry point Emby.Server.Implementations.Udp.UdpServerEntryPoint
Info App: Entry point completed: Emby.Server.Implementations.Udp.UdpServerEntryPoint. Duration: 0.0011213 seconds
Info App: Starting entry point Emby.Server.Implementations.Library.DeviceAccessEntryPoint
Info App: Entry point completed: Emby.Server.Implementations.Library.DeviceAccessEntryPoint. Duration: 0.0003887 seconds
Info App: Starting entry point Emby.Server.Implementations.IO.LibraryMonitorStartup
Info App: Init BeginReceive on 0.0.0.0
Info App: Init BeginReceive on 0.0.0.0
Info App: Init BeginReceive on 192.168.68.109
Info App: Init BeginReceive on 127.0.0.1
Info LibraryMonitor: Skipping realtime monitor for /mnt/Library/Anime because the path does not exist
Info LibraryMonitor: Skipping realtime monitor for /mnt/Library/AudioBooks because the path does not exist
Info LibraryMonitor: Skipping realtime monitor for /mnt/Library/Cartoons because the path does not exist
Info LibraryMonitor: Skipping realtime monitor for /mnt/Library/Documentaries because the path does not exist
Info LibraryMonitor: Skipping realtime monitor for /mnt/Library/Movies because the path does not exist
Info LibraryMonitor: Skipping realtime monitor for /mnt/Library/TV because the path does not exist
Info App: Entry point completed: Emby.Server.Implementations.IO.LibraryMonitorStartup. Duration: 0.2481034 seconds
Info App: Starting entry point Emby.Server.Implementations.EntryPoints.AutomaticRestartEntryPoint
Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.AutomaticRestartEntryPoint. Duration: 0.0002348 seconds
Info App: Starting entry point Emby.Server.Implementations.EntryPoints.KeepServerAwake
Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.KeepServerAwake. Duration: 0.0001391 seconds
Info App: Starting entry point Emby.Server.Implementations.EntryPoints.LibraryChangedNotifier
Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.LibraryChangedNotifier. Duration: 0.0015116 seconds
Info App: Starting entry point Emby.Server.Implementations.EntryPoints.ServerEventNotifier
Info LibraryMonitor: Watching directory /emby/data/playlists
Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.ServerEventNotifier. Duration: 0.0021495 seconds
Info App: Starting entry point Emby.Server.Implementations.EntryPoints.StartupWizard
Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.StartupWizard. Duration: 0.0002624 seconds
Info App: Starting entry point Emby.Server.Implementations.EntryPoints.SystemEvents
Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.SystemEvents. Duration: 0.0003352 seconds
Info App: Starting entry point Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier
Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier. Duration: 9.5E-05 seconds
Info App: Starting entry point Emby.Server.Implementations.Channels.ChannelsEntryPoint
Info App: Entry point completed: Emby.Server.Implementations.Channels.ChannelsEntryPoint. Duration: 0.0032841 seconds
Info App: Starting entry point Emby.LiveTV.EntryPoint
Info LiveTV: Loading live tv data from /emby/data/livetv/timers
Info App: Entry point completed: Emby.LiveTV.EntryPoint. Duration: 0.0179701 seconds
Info App: Starting entry point Emby.LiveTV.UpgradeChannelOptionsEntryPoint
Info App: Entry point completed: Emby.LiveTV.UpgradeChannelOptionsEntryPoint. Duration: 0.0011648 seconds
Info App: Starting entry point Emby.LiveTV.RecordingNotifier
Info App: Entry point completed: Emby.LiveTV.RecordingNotifier. Duration: 0.0001822 seconds
Info App: Starting entry point Emby.ActivityLog.ActivityLogEntryPoint
Info App: Entry point completed: Emby.ActivityLog.ActivityLogEntryPoint. Duration: 0.0027724 seconds
Info App: Starting entry point Emby.Server.MediaEncoding.Api.EncodingManagerEntryPoint
Info App: Entry point completed: Emby.Server.MediaEncoding.Api.EncodingManagerEntryPoint. Duration: 0.0008677 seconds
Info App: Starting entry point Emby.Notifications.Notifications
Info App: Entry point completed: Emby.Notifications.Notifications. Duration: 0.0002256 seconds
Info App: Starting entry point Emby.Server.Sync.SyncManagerEntryPoint
Info App: SyncRepository Initialize taking write lock
Info App: SyncRepository Initialize write lock taken
Info App: Entry point completed: Emby.Server.Sync.SyncManagerEntryPoint. Duration: 0.0036134 seconds
Info App: Starting entry point Emby.Server.Sync.SyncNotificationEntryPoint
Info App: Entry point completed: Emby.Server.Sync.SyncNotificationEntryPoint. Duration: 0.0017527 seconds
Info App: Starting entry point EmbyServer.Windows.LoopUtilEntryPoint
Info App: Entry point completed: EmbyServer.Windows.LoopUtilEntryPoint. Duration: 8.25E-05 seconds
Info App: All entry points have started

**Comment by alexbelgium** [comment]
Hi, could you please provide the upper part of the log. Perhaps setting the option "silent" to true would help you capture the upper part (starting with the banner).

Thanks!

**Comment by hacshacdgacs** [comment]
Done, here you go.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-aaa_dockerfile_backup.sh: executing... 
Executing modules script : 00-banner.sh 92-local_mounts.sh 92-smb_mounts.sh
00-banner.sh
92-local_mounts.sh
92-smb_mounts.sh
Executing dependency script with custom elements : nginx
[cont-init.d] 00-aaa_dockerfile_backup.sh: exited 0.
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-folders.sh: executing... 
Creating /emby
Creating link for /emby/cache
Creating link for /emby/config
Creating link for /emby/data
Creating link for /emby/logs
Creating link for /emby/metadata
Creating link for /emby/plugins
Creating link for /emby/root
[cont-init.d] 20-folders.sh: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 32-nginx.sh: executing... 
Adapting for ingress
Allowing case sensitive url
[cont-init.d] 32-nginx.sh: exited 0.
[cont-init.d] 40-gid-video: executing... 
[cont-init.d] 40-gid-video: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 91-silent.sh: executing... 
[17:22:11] INFO: Silent mode activated, all logs from emby server are hidden. Disable this option if you need to troubleshoot the addon.
[cont-init.d] 91-silent.sh: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:22:12] INFO: Starting NGinx...

**Comment by alexbelgium** [comment]
Weird, the smb mount script doesn't run. I'll investigate

**Comment by hacshacdgacs** [comment]
Thank you, I appreciate it

**Comment by alexbelgium** [comment]
Just for testing purposes : do you have a working emby backup to restore to check if the script appears again? If it doesn't appear, the culprit would be external to the addon, if it does it would be internal.

I think that if you rebuild the Radarr addon that is currently working you should arrive at the same issue as downloading scripts is common to all addons

**Comment by hacshacdgacs** [comment]
Not currently no. Do you suggest I rebuild the radarr add-on to see if it's
an external issue?

**Comment by alexbelgium** [comment]
Perhaps, if you like taking risks :-)

I don't see what changed on my addons side... Scripts are still with LF eol, no major changes recently... The only thing I did is remove the "apparmor=true" value from config but that was a proposal from HA scripts validator as it is already a default value

**Comment by hacshacdgacs** [comment]
I'll try the radarr rebuild and see if that does anything. Do you have any
other advice? I think this issue started when I upgraded home assistant so
I'll try find a backup of that also.

**Comment by alexbelgium** [comment]
Well I'm not sure... In my script the first step is that it downloads the different elements (such as the mount script), then reads through them.

I can see several things going wrong : either internet not available (but we can skip this as emby by definition connects to internet), a change of s6 supervision settings that causes the downloaded script not being seen, an issue with the script itself (but then it should have impacted also the other addons)... And I can't replicate that so for the moment I'm just trying to think about debugging options :-)

**Comment by hacshacdgacs** [comment]
![image](https://user-images.githubusercontent.com/85550264/167367354-d1b55b6d-833d-4922-a730-f4c6b5781040.png)
![image](https://user-images.githubusercontent.com/85550264/167367426-57c75aee-1e03-4a20-8b14-e29e5d8de289.png)

You were right in terms of Radarr then losing it's mount access

**Comment by alexbelgium** [comment]
Mmh... I've pushed a new version of emby with an explicit apparmor=True tag. 
Could you please test if it solves it (low probability) ? Thanks

**Comment by alexbelgium** [comment]
I should have a solution : could you please try emby in version 4.7.0.38-1

**Comment by hacshacdgacs** [comment]
It works now, thank you.

**Comment by alexbelgium** [comment]
Thanks for the feedback, I'll align other addons tomorrow

**Comment by alexbelgium** [comment]
I have pushed the code to all my addons. Just rebuild the ones failing and they will work again. Thanks for reporting this, I'm sure it would have impacted many people!

**Comment by alexbelgium** [comment]
I'll close the issue if it now works, or let me know if otherwise
