### ISSUE TITLE
✨ [Request] Epic Games Store Weekly Free Games (Existing docker image)

### ISSUE THREAD

**Issue by KairuByte** [alexbelgium/hassio-addons#325]
URL to project: https://github.com/claabs/epicgames-freegames-node

Technically speaking, I think this is pretty much already good to go as an addon, I think it could even be added as an image with Portainer directly (if I could just figure out how to properly use it lol)

**Comment by ikrowni** [comment]
This would be cool to have in home assistant for sure. +1 from me.

**Comment by alexbelgium** [comment]
Hi, I don't have time for the moment to move this to an addon, but indeed running it in portainer should be easy and fast. There are many guides on Internet to do that : globally you select the container sourced, map ports, and voilà. The tricky part is to get data out of the container, for that you'll have to look into one of my other addons where /share (for example) is mapped and use it to map the container data folder

**Comment by tyjtyj** [comment]
+1 for me,, who can say no to free stuff.

**Comment by alexbelgium** [comment]
Hi, I'm really busy for the moment so no new addons but thanks for the interest I'll consider it when I'll have more time!

**Comment by alexbelgium** [comment]
Hi, first version pushed. Please read the Readme on how to configure (with json files as per official app documentation). The config files are copied in the container on addon start, an addon restart is needed if they are modified

**Comment by tyjtyj** [comment]
It works for me.... you will need TOTP to pass thru the login page.
There are plenty of visual captcha u need to by pass via notification. 
It is not entirely "auto". You need to make sure you are available to solve the captcha. 

Kudos to @alexbelgium to get this working. I will test it further.

**Comment by ikrowni** [comment]
`Hi, I'm really busy for the moment so no new addons but thanks for the interest I'll consider it when I'll have more time!`

[3 Hours Later...](https://i.ytimg.com/vi/omoNXtnVt1g/maxresdefault.jpg)

`Hi, first version pushed. Please read the Readme on how to configure (with json files as per official app documentation). The config files are copied in the container on addon start, an addon restart is needed if they are modified`

You absolutely rock @alexbelgium

**Comment by KairuByte** [comment]
@ikrowni Not going to lie, I thought exactly the same thing when I saw that second comment.

**Comment by tyjtyj** [comment]
anyone managed to get cookies login working ? i got error missing parameter at 60

https://github.com/claabs/epicgames-freegames-node/issues/260
