### ISSUE TITLE
[Photoprism] No https

### ISSUE THREAD

**Issue by ivico94** [alexbelgium/hassio-addons#327]
I use home assistant with duckdns + let's encrypt addon .

I set port forwarding according to the port included in the configuration panel of the Photoprism addon (version 220302-impish).

I do not have https and firefox tells me that the website (photosprims gui) is unsecure.

How can I have secure connection? 

Thank you

**Comment by alexbelgium** [comment]
Hi, https with ssl definition is now implemented in the latest version

**Comment by alexbelgium** [comment]
Please let me know if everything went fine

**Comment by ivico94** [comment]
Great job @alexbelgium 

Https is working now as expected once ssl toogle is activated in the config panel!

Thank you so much!

**Comment by alexbelgium** [comment]
Thanks for the feedback!
