### ISSUE TITLE
[portainer] portainer requires 12 character passwords

### ISSUE THREAD

**Issue by si458** [alexbelgium/hassio-addons#329]
**Which addon?**

- Addon name : Portainer
- Addon version : 2.13.0

**Describe the bug**
portainer 2.13.0 required passwords to be 14 characters with special charactors - https://github.com/portainer/portainer/releases/tag/2.13.0
now 2.13.1 requires 12 character passwords instead - https://github.com/portainer/portainer/releases/tag/2.13.1

**To Reproduce**

**Full addon log**

**Full addon config**

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hi, thanks for posting this! However, as you mention, this is linked to portainer itself and not the addon... If you would want to change that you would need to post on the portainer github

**Comment by alexbelgium** [comment]
Strange... It should keep your password when restarting! I changed it yesterday and when I restarted the container this morning it had kept my new password

**Comment by alexbelgium** [comment]
Normally, the password from options is only applied for an initial install, or if it is itself changed

**Comment by si458** [comment]
> Strange... It should keep your password when restarting! I changed it yesterday and when I restarted the container this morning it had kept my new password

my mistake, it does indeed keep the password if i change it in portainer and then restart the addon AND if i change it in the addon it changes to that password

BUT you still have the issue when you first login when adding the add-on with a password less than 12 characters in 2.13.1, portainer asks you to change it, maybe update the default password to say `homeassistant` for 2.13.1 ?

**Comment by alexbelgium** [comment]
thanks good idea!

**Comment by si458** [comment]
> thanks good idea!
> 
> As the requirement is "Special characters Lower case characters Upper case characters Numeric characters"
> 
> I'll have to change it to "Homeassistant123!"

thats the old requirement for 2.13.0, the new 2.13.1 is only 12 characters, no case matching
https://github.com/portainer/portainer/commit/16f8b737f1b623af76af07b162717f562ea022ff

**Comment by alexbelgium** [comment]
Guess I haven't updated yet my own local HA ;-) thanks!

**Comment by si458** [comment]
> Ok to close the issue, with the new default password at "homeassistant" as you propose ? Hopefully a tag to remove secure password will be implemented as per issue linked above but unlikely given the history of the portainer developers.

thats perfectly fine! it at least helps with new users using version `2.13.1` and we could look at the toggle for secure password later if/when the developers do anything about it

**Comment by alexbelgium** [comment]
Thanks!

**Comment by alexbelgium** [comment]
Argh, changing the default seems to reset the whole database upon update :-)

**Comment by si458** [comment]
> Argh, changing the default seems to reset the whole database upon update :-)

yeh i spotted that but nothing you can do about it sadly

**Comment by gigatexel** [comment]
What would the new password be after updating to the latest version? Somhow I've been locked out.
Not working:

username admin, 
- my previous password
- Homeassistant123!
- homeassistant (as described in the changelogs)

**Comment by alexbelgium** [comment]
Hi, the new password is `homeassistant`or whatever is in the addon option field password. I, the unlikely case it doesn't work, you can change the password from the addon options. Watch out a password change resets the database. If you really need to keep your old database, you need to export it, update, then import it back 

Best regards

**Comment by gigatexel** [comment]
I'm back in :-)

Thanks!
