### ISSUE TITLE
Request: Transmission/QBittorrent with Wireguard support

### ISSUE THREAD

**Issue by Antexa** [alexbelgium/hassio-addons#33]
Idea of going through a VPN when downloading at home without using openvpn 

Repo : https://github.com/vidurb/docker-transmission-wireguard
Repo : https://hub.docker.com/r/dyonr/qbittorrentvpn/
Repo : https://github.com/binhex/arch-qbittorrentvpn

**Comment by alexbelgium** [comment]
Hi! Thanks for reaching out. Why use wireguard instead of openvpn?

**Comment by alexbelgium** [comment]
Hi, as I understand, it's only an improvement on speed and cpu usage. As I don't have much time to allocate to the addons for the moment I'll put this on hold - but anyone having an idea on how to implement is free to propose a PR

**Comment by Antexa** [comment]
This could be awesome, in a meantime I will setup an openvpn instance.

**Comment by alexbelgium** [comment]
Sorry I've got too much work with already maintaining current addons, I won't be able to accept new requests for the moment

**Comment by alexbelgium** [comment]
I'll close this issue as I don't intend to work on it at short term... One day perhaps I'll switch the base image to one that's supports it natively but I fear to break it for other users curently using it... Thanks for your understanding!
