### ISSUE TITLE
[Whoogle] Feature Request - Add ingress support

### ISSUE THREAD

**Issue by pasyn** [alexbelgium/hassio-addons#330]
Would it be possible to enable ingress for the Whoogle addon? Whoogle would be a lot more useful If I could use it via the Nabu Casa cloud instead of only on my local network or through a VPN.

**Comment by alexbelgium** [comment]
Hi, I'll look at it but not that many apps support subfolder case sensitive urls that ingress requires.

**Comment by alexbelgium** [comment]
I have spent HOURS on that in the last couple days and then found there was a variable that could be set to enable the feature I was wanting ! Ingress is available in the new version !

**Comment by pasyn** [comment]
After the update, Ingress works perfectly! Thank you very much for all of your hard work!

**Comment by alexbelgium** [comment]
Thanks for the feedback!
