### ISSUE TITLE
[Resilio Sync] default share folder is not created

### ISSUE THREAD

**Issue by ElVit** [alexbelgium/hassio-addons#333]
**Which addon?**

- Addon name : Resilio Sync
- Addon version : 2.7.3.1381

**Describe the bug**

If I install the addon the first time the folders `share/resiliosync_config/custom-cont-init.d` and `share/resiliosync_config/custom-services.d` are created. I think they are not needed here right?

Also the addon requires the folder `/share/resiliosync/folders` and `/share/resiliosync/mounted_folders`. But they are not created by default. So I get an permission error if I want to share a file or folder.
Only if I create the folder `/share/resiliosync/folders` manually the sharing of files and folders will be possible.

Then the **storage_path** is set to `/config`, but it should be somthing like `/share/resiliosync_config`.

And the last thing is maybe a feature request, but is it possible to 
- add Ingress support for this addon and 
- move the config file also to `/config/addons_config/resiliosync` like your other addons (instead of `/share/resiliosync_config`)?

Thanks :)

**To Reproduce**

**Full addon log**

**Full addon config**

```
PGID: 0
PUID: 0
```

**System**

- Home Assistant Core 2022.5.4
- Home Assistant Supervisor 2022.05.2
- Home Assistant OS 8.0

**Comment by alexbelgium** [comment]
Hi, thanks for your input.

I'll structure the work packages :
- [ ] Add code for folders creation
- [ ] Add config location setting
- [ ] Update documentation
- [ ] Check symlinks for config
- [ ] Evaluate ingress potential addition

**Comment by alexbelgium** [comment]
Could you please test (after a backup) if the new version which allows setting the sync and config folders in working? Thanks!

**Comment by ElVit** [comment]
Thanks for the quick update.

The **config_location** is working as expected. Only the **data_location** needs some modifications:
Either you have to create the folders `/share/resiliosync/folders` and `/share/resiliosync/mounted_folders`
Or change in the file `sync.conf` the value `dir_whitelist` to `[ "/share/resiliosync" ]`.

Also the value `files_default_path` should probably be changed to `"/share/resiliosync/downloads"`.

And the folders `custom-cont-init.d` and `custom-services.d` are still copied to the **config_location**.

**Comment by alexbelgium** [comment]
Hi, thanks.

For custom-cont-init.d & custom-services.d those are folders inherent to the linuxserver.io architecture that I use as based image. I won't be able to delete those. They are used to run custom scripts & services in this addon as per their documentation [here](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers)

For other elements I'll check that a bit later

**Comment by alexbelgium** [comment]
Work : 
- [] creation of the `/share/resiliosync/folders` and `/share/resiliosync/mounted_folders`
- [] change `files_default_path` to `"/share/resiliosync/downloads"`
- [] `custom-cont-init.d` and `custom-services.d` : kept as part of the linuxserver.io infrastructure and allow specific functionality such as custom scripts running
- [] version publishing
- [] testing

**Comment by alexbelgium** [comment]
Hi, it seems to work, could you please test the new version? Thanks

**Comment by ElVit** [comment]
Yes its working now. Thanks

**Comment by ElVit** [comment]
Now the folders `downloads`, `folders `and `mounted_folders` are also copied to the **config_location**.
But this is probably the same reason as you mentioned before for the other 2 folders.

**Comment by alexbelgium** [comment]
hi, indeed this is voluntary as they are default folders in the app (the downloads folder being used for `files_default_path`), and the folders and mounted_folders being in the whitelist defaults

**Comment by alexbelgium** [comment]
And ingress can't be added, as resiliosync uses hardcoded urls (like /gui/) in a compiled app which prevents on the fly modification that I know of - and they have not coded a base_url (or prefix) variable that could be use to circumvent that

**Comment by alexbelgium** [comment]
Hi, ingress is implemented in the latest version

**Comment by ElVit** [comment]
I just tried to disable the password in the `sync.config` by setting the value `allow_empty_password` to `true`.
After created the user (with no password) it also worked in the Home Assistant iOS App.

**Comment by alexbelgium** [comment]
Great, thanks for the feedback!
