### ISSUE TITLE
[cailbre] Calibre add-on can access all of the `/config` directory

### ISSUE THREAD

**Issue by JeffersonBledsoe** [alexbelgium/hassio-addons#334]
calibre

**Which addon?**

calibre

**Describe the solution you'd like**

Currently the calibre add-on uses `/config/addons_config/calibre` as it's directory for both the library and all of the app config. This ends up giving the add-on full access to the home-assistant config directory. I'm fairly new to add-on development, but would it not be possible to use the `share` mount to read/ write the database rather than exposing all my Home Assistant data to the add-on?

**Comment by alexbelgium** [comment]
Hi, just set the UID and PGID in your addon to a specific user. The addon will load with those credentials and it won't be able to access the other config files. Currently all my addons use the config folder for their storage so it would be too complex to move all of them... I could add an option to define the location of the data directory, but as the config folder is still mounted it will only hide the issue and not replace it. And removing the access to config is not an option as it would mean all other users will lose access to their data... In short I think using uid/gid, although inconvenient as your files will need to have the same permissions, is the best way to prevent calibre from accessing to your HA config files
