### ISSUE TITLE
[Apache Guacamole] Extensions

### ISSUE THREAD

**Issue by paulgbrichardson** [alexbelgium/hassio-addons#336]
According to the source Docker project - https://github.com/abesnier/docker-guacamole  - Extensions can be enabled using the -e EXTENSIONS variable. Multiple extensions can be enabled using a comma separated list without spaces.  How does this translate to the Home Assistant UI?  I've tried various combos in the Extension option but can't seem to get it working.

Reading the source project TOTP can be enabled using the flag   -e "EXTENSIONS=auth-totp" but I can't seem to get the add-on to pick this up.  

Any advice?

**Comment by alexbelgium** [comment]
Hi, you can use the "EXTENSIONS" option from the addon to use those. Now I see that the documentation is missing but hopefully it should work

**Comment by paulgbrichardson** [comment]
But what do I enter in the entry - so far I've tried -

auth-totp
"auth-totp"
EXTENSIONS=auth-totp
EXTENSIONS="auth-totp"
"EXTENSIONS=auth-totp"
....

Yet I don't see the same as a standalone install where it configures the
use of TOTP, and I don't see anything in the logs saying the extension is
picked up.

**Comment by alexbelgium** [comment]
I'll check and adapt documentation ;-)

**Comment by alexbelgium** [comment]
I understand... I though all extensions were there by default and we only had to enable them. Now I understand that we need to download them as well. I'll have to adapt my code to do that https://guacamole.apache.org/releases/1.4.0/

**Comment by alexbelgium** [comment]
It should work in -v7 could you please test? For example you could put ```auth-totp```
Normally it will work but make sure to customize the app according to the extension documentation

The config files are now in /config/addons_config/guacamole

**Comment by paulgbrichardson** [comment]
Excellent, that worked and allowed me to enable TOTP as expected.  I don't
use the other extensions so can't talk around their compatibility.
I don't actually have time for a few days to test the add-on more robustly
but thank you so much for your help and such an awesome set of add-ons!

**Comment by alexbelgium** [comment]
Great, thanks for the feedback!
