### ISSUE TITLE
[ photoprism ] Upload cron job not working since updating to 220517-jammy

### ISSUE THREAD

**Issue by richard-scott** [alexbelgium/hassio-addons#340]
**Which addon?**

- Addon name : PhotoPrism
- Addon version : 220517-jammy

**Describe the bug**

New photos uploaded and imported do not show in search when ordered by show most recently added.
It worked in 220302-impish .

**To Reproduce**

1. upload new photos
2. import new photos
3. look in search and order by recently added and see your new photos are not there.

**Full addon log**

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Photoprism
 A server-based application for browsing, organizing and sharing your personal photo collection
-----------------------------------------------------------
 Add-on version: 220517-2
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2022.5.5
 Home Assistant Supervisor: 2022.05.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/32-nginx_ssl.sh: executing
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/photoprism/config.yaml
Config file is a valid yaml
[08:27:08] INFO: Starting the app with the variables in in /config/addons_config/photoprism/config.yaml
PHOTOPRISM_SITE_URL=https://photos.blah/
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
Mounting smb share(s)...
[08:27:09] FATAL: The structure of your "networkdisks" option : "//server/share" doesn't seem correct, please use a structure like //123.12.12.12/sharedfolder,//123.12.12.12/sharedfolder2. If you don't use it, you can simply remove the text, this will avoid this error message in the future.
/etc/cont-init.d/99-run.sh: executing
[08:27:09] INFO: Defining database
[08:27:09] INFO: Using MariaDB addon. Requirements : running MariaDB addon. Discovering values...
PHOTOPRISM_DATABASE_DRIVER=mysql
PHOTOPRISM_DATABASE_SERVER=core-mariadb:3306
PHOTOPRISM_DATABASE_NAME=photoprism
PHOTOPRISM_DATABASE_USER=service
PHOTOPRISM_DATABASE_PASSWORD=
[08:27:14] WARNING: Webtrees is using the Maria DB addon
[08:27:14] WARNING: Please ensure this is included in your backups
[08:27:14] WARNING: Uninstalling the MariaDB addon will remove any data
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARACTER SET = utf8mb4' at line 1
[08:27:15] INFO: Please wait 1 or 2 minutes to allow the server to load
[08:27:15] INFO: Default username : admin, default password: "please_change_password"
[08:27:15] INFO: App launched...
started 220517-bookworm as root (amd64-prod)
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /share/photoprism/storage
config path...: default
cache path....: default
backup path...: /share/photoprism/backup
import path...: /share/photoprism/import
originals path: /share/photoprism/originals
running as uid 0
photoprism start
time="2022-05-23T08:27:24+01:00" level=info msg="PhotoPrism® needs your support!"
time="2022-05-23T08:27:24+01:00" level=info msg="Visit https://docs.photoprism.app/funding/ to learn more."
time="2022-05-23T08:27:26+01:00" level=info msg="webdav: /originals/ enabled, waiting for requests"
time="2022-05-23T08:27:26+01:00" level=info msg="webdav: /import/ enabled, waiting for requests"
time="2022-05-23T08:27:26+01:00" level=info msg="http: starting web server at 0.0.0.0:2341"
```

PS. I have changed my password, so this line isn't true:

```Default username : admin, default password: "please_change_password"```

**Full addon config**

BACKUP_PATH: /share/photoprism/backup
CONFIG_LOCATION: /config/addons_config/photoprism/config.yaml
DB_TYPE: mariadb_addon
IMPORT_PATH: /share/photoprism/import
ORIGINALS_PATH: /share/photoprism/originals
STORAGE_PATH: /share/photoprism/storage
UPLOAD_NSFW: true
certfile: fullchain.pem
cifspassword: password
cifsusername: username
keyfile: privkey.pem
networkdisks: //server/share
ssl: false

**System**

- Supervisor version: Home Assistant Supervisor 2022.05.2
- Host system version: Home Assistant Core 2022.5.5

**Comment by alexbelgium** [comment]
Hi, thanks. To be clear, they only don't appear in this view or they aren't uploaded at all ?
I'll have to look if this is an issue with the addon, or the underlying app

**Comment by alexbelgium** [comment]
Hi, I can't replicate. I've installed the latest version and have the exact same log as you (mentioning the default username / password is still correct as it says it is the default and not current). I've uploaded a picture, approved it in the "review" tab, then it appeared on my recent files... Are you sure your files are not stuck in review?

**Comment by richard-scott** [comment]
I use the Photosync app to upload into the import folder, and then I run the following on a cron using docker exec:

```
photoprism mv /share/photoprism/import
```

Hmmm, I've never had to use the review tab before... is that enforced now?
I've got 6K of photos in there, is there any way to approve them all?

**Comment by alexbelgium** [comment]
Hi, do you need the cron? According to documentation, auto import is a built in function : https://docs.photoprism.app/user-guide/library/import/

**Comment by alexbelgium** [comment]
Hi, so if I understand correctly your issue, it is that your cron command stopped working ?

Several options : 
- with webdav - If you go in the webui, in library, import, you can set the move function and upload all files at once if needed. All files added in the future in the upload folders should be automatically uploaded baesd on photoprism documentation. This only works with webdav https://github.com/photoprism/photoprism/issues/1288
- with cron : you could use another command sur as this one `docker exec -it photoprism photoprism import` https://github.com/photoprism/photoprism/issues/281#issuecomment-1067956594
- For info, cron job request ongoing : https://github.com/truecharts/apps/issues/2467

**Comment by alexbelgium** [comment]
Edit : I've put files in the import folder and have tested both the import from UI option, and the command `photoprism import` successfully. I've therefore removed the "bug" tag as everything seems to work as intended

**Comment by richard-scott** [comment]
I have no idea what the cause of the issue was now, but it's gone after a restart of Home Assistant.

**Comment by alexbelgium** [comment]
Ah ah, well in the end what is important is that it works ;-)
