### ISSUE TITLE
[Request] Change Transmission NAS image to haugene/transmission-openvpn

### ISSUE THREAD

**Issue by ping-localhost** [alexbelgium/hassio-addons#341]
**Which addon?**

Transmission NAS

**Describe the solution you'd like**

I know this is a bit of a weird ask, but I was wondering if it's possible to switch the image from linuxserver to [haugene/transmission-openvpn](https://hub.docker.com/r/haugene/transmission-openvpn). It's added benefit is that it allows you to select a VPN provider, provide the addon with a username/password and it does the rest. There is no need to deal with `.ovpn `-files and it will always pick the best server for you.

**Describe alternatives you've considered**

I'm currently using an addon [from petersendev/hassio-addons](https://github.com/petersendev/hassio-addons/tree/master/transmission-openvpn#readme), but it's not as maintained as Transmission NAS and there is no Ingress support.

**Additional context**

I tried to combine the two repo's myself, but I don't understand enough of Hassio addons to do this myself (as of right now). If this is too much of an ask or you don't want to trust `haugene` with usernames/passwords from people that will use your addon, I totally understand. Feel free to close the issue if so.

**Comment by alexbelgium** [comment]
Hi, thanks! I'll then take inspiration from petersendev. Just the haugene image seems much less frequently updated than the linuxserver one

**Comment by alexbelgium** [comment]
Well I've looked at it and honestly I would have to take his whole code to make it work and I'm not really comfortable with that. I'll look to create my own logic & code but it will take a longer

**Comment by alexbelgium** [comment]
Another issue that I see is that Haugene's image can't start without vpn - that would prevent people not using VPN to use the addon

**Comment by ping-localhost** [comment]
> Another issue that I see is that Haugene's image can't start without vpn - that would prevent people not using VPN to use the addon

Hmmmm, maybe we should offer this as a separate addon then? As that is exactly the feature I want (next to picking a random server from a VPN provider). I do not want to use Transmission without the VPN being on. 🤔

**Comment by alexbelgium** [comment]
Indeed I'll look at it

**Comment by alexbelgium** [comment]
I've put a first version here: https://github.com/alexbelgium/hassio-addons-test
Could you please test if it works? It doesn't support my openvpn config

**Comment by ping-localhost** [comment]
It works perfectly for me:

![image](https://user-images.githubusercontent.com/37925797/171256130-c47acbc6-42cf-46af-8e0b-759d66d43ad5.png)
![image](https://user-images.githubusercontent.com/37925797/171256271-33b99ec1-9e9f-4595-b929-311e4b657026.png)

The `customUI` option didn't change anything and it seems to be as root, instead of a separate user, but that is fine for now.

**Comment by alexbelgium** [comment]
Wow it worked??? That's great ;) indeed I'll have to cleanup some things still but glad to now that the base architecture works!

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version that hopefully should have working addon options. Could you please test if it works? If yes then I'll move it to the main repo

Thanks,
Best regards

**Comment by ping-localhost** [comment]
I see that you made `OPENVPN_CONFIG` optional (which seems like a good idea), but `OPENVPN_PROVIDER` is now also optional. Is that on purpose? 

Other than that, it looks to be working just fine. I've switched my current setup to run on this test image. Thank you so much for your effort! The only thing I would like now is Ingress. 😜

**Comment by alexbelgium** [comment]
it was not, I'll update that ;-) thanks for the very fast feedback

for ingress I'll look at it a bit later

**Comment by ping-localhost** [comment]
All good! I've sent some coffees your way for the hard work. Thanks again!

**Comment by alexbelgium** [comment]
Thanks very much! I'm moving right now the transmission_openvpn addon from the test to main repo

**Comment by alexbelgium** [comment]
Hi, ingress is pushed could you please test it? thanks. custom ui won't change the ingress ui, a single ui can be defined at addon creation

**Comment by ping-localhost** [comment]
I'm getting some errors:

```
/etc/cont-init.d/32-nginx_ingress.sh: executing
grep: /opt/photoprism: No such file or directory
sed: no input files
/etc/cont-init.d/32-nginx_ingress.sh: exiting 123
..... 
Normal startup stuff
..... 
STARTING TRANSMISSION
Transmission startup script complete.
Wed Jun  1 22:07:20 2022 /sbin/ip route add xxx.xxx.xxx.xxx/32 via 172.30.32.1
Wed Jun  1 22:07:20 2022 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Wed Jun  1 22:07:20 2022 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
Wed Jun  1 22:07:20 2022 Initialization Sequence Completed
[22:07:20] INFO: Ingress ready
nginx: [emerg] duplicate location "/" in /etc/nginx/servers/ingress.conf:13
/etc/cont-init.d/99-run.sh: exiting 1 
```

**Comment by alexbelgium** [comment]
sorry, I pushed a 4.0-ingress2 to solve that

**Comment by ping-localhost** [comment]
Addon now starts as expected, but I'm getting a mixed content message. I can access the Frigate UI via Ingress as well, so it should be possible to resolve this, right? As I have HTTP completely disabled (and use a proper SSL cert). 😅 

```
Mixed Content: The page at 'https://my.home.assistant.com/db21ed7f_transmission_openvpn/dashboard' was loaded over HTTPS, but requested an insecure frame 'http://my.home.assistant.com:8099/web/'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by alexbelgium** [comment]
Mmh... Good question I'll look at that. I'm pretty sure it's because nginx used for ingress maps it's port to http://127.0.0.1:9091

Where did you input your ssl certificate for transmission? Directly in transmissions' config file ?

**Comment by alexbelgium** [comment]
I'll push a v4 to test a solution

**Comment by alexbelgium** [comment]
Thanks, I see your config. It seems I can add a new directive to pass proto scheme in nginx, I've added it to see if it makes a difference

**Comment by ping-localhost** [comment]
I have found one more issue. Every time I restart the addon, all the configuration (and pending downloads) are gone. I think this is why `petersendev` stored the config files somewhere else: [customstart.sh](https://github.com/petersendev/hassio-addons/blob/master/transmission-openvpn/root/customstart.sh).

**Comment by alexbelgium** [comment]
Thanks I'll look at it. Strange for config as I thought I had indeed made it to be stored in  /config/addons_config/transmission, i'll double check

**Comment by alexbelgium** [comment]
Just reacting to an edit you did above : 
"Maybe it's because nginx sends me to http://my.home.assistant.com:8099/web/? I am not sure. 🤔"
-> the key issue is that transmission expects to be in /web, however ingress opens a / url. Therefore, transmission tries to add the /web at the end of the url but in a hard way which means that instead of http://host:port/ingress_url/web it just puts http://host:port/web which doesn't work...

That's the reason of the redirect directive in my nginx config but it doesn't seem to fully work. I haven't put HA behind ssl so I can't directly replicate your issue but will try to find a way and already test your proposed nginx code

**Comment by alexbelgium** [comment]
"    location / {
        proxy_pass http://127.0.0.1:9091/;"

> location / {
>         proxy_pass http://127.0.0.1:9091/;

This gives an error 404 not found as it looks for the /transmission part
Removing the /web gives an error 409 as it expects the /web

Still looking

**Comment by alexbelgium** [comment]
What method are you using to access HA with https? To replicate your case thanks

**Comment by ping-localhost** [comment]
I am using DuckDNS: https://github.com/home-assistant/addons/tree/master/duckdns

**Comment by alexbelgium** [comment]
Well, I managed to install ssl so thanks for that! It will be an improvement on my own installation

Where did you see the error message ? in the addon log ? I don't have a paid vpn so I can't use the openvpn transmission addon, but I implemented the same code for the normal transmission addon and can connect it with ingress through the https://domain:port without any error message

**Comment by ping-localhost** [comment]
I just uninstalled the addon and installed it fresh, now it just works, so I guess nevermind. Sorry for wasting your time. 😅 

----

So the last issue would be configuration (and pending downloads) being lost after a restart right? If required I can give you temporary access to my VPN provider.  Oh and it might be nice to have the [available providers as a dropdown](https://haugene.github.io/docker-transmission-openvpn/supported-providers/), but that is not at all important.

**Comment by alexbelgium** [comment]
I've pushed a new version that enables the users script creation. That's strange as it should execute on openvpn enabling, but I would appreciate if you could test that :) if this doesn't work I'll get a trial

**Comment by ping-localhost** [comment]
That seems to work as expected! For some reason Transmission doesn't resume the download after a restart, but that's fine. I can live with that 😁
