### ISSUE TITLE
[Nextcloud] "Nextcloud is not installed"

### ISSUE THREAD

**Issue by Neotastisch** [alexbelgium/hassio-addons#344]
**Which addon?**

- Addon name : Nextcloud
- Addon version : newest

**Describe the bug**

Everything starts fine, but I can't connect via the Webinterface button and I get an error

**To Reproduce**

Default 

**System**

Add-on version: 24.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.1  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2022.6.0
 Home Assistant Supervisor: 2022.05.3

**Comment by alexbelgium** [comment]
Hi, the nextcloud is not installed messages are normal - you'll get those error messages until you've installed it from the webui

Have you already done the initial setup?

**Comment by alexbelgium** [comment]
I can't replicate : I've installed a fresh instance, run it (with the "not installed" errors), then access the webui with https and everything works

**Comment by Neotastisch** [comment]
> Hi, the nextcloud is not installed messages are normal - you'll get those error messages until you've installed it from the webui
> 
> Have you already done the initial setup? 

Initial setup? I can't even access the webui, it just doesn't load in my browser 

Wait I'll get a few more errors (after 5 mins or so)


```
Exception: Not installed in /data/config/www/nextcloud/lib/base.php:282
Stack trace:
#0 /data/config/www/nextcloud/lib/base.php(663): OC::checkInstalled()
#1 /data/config/www/nextcloud/lib/base.php(1104): OC::init()
#2 /data/config/www/nextcloud/cron.php(43): require_once('/data/config/ww...')
#3 {main}
{"reqId":"WRrRUkFXJmZWivjGL0QZ","level":3,"time":"2022-06-03T11:55:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Not installed","userAgent":"--","version":"","exception":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/data/config/www/nextcloud/lib/base.php","line":663,"function":"checkInstalled","class":"OC","type":"::"},{"file":"/data/config/www/nextcloud/lib/base.php","line":1104,"function":"init","class":"OC","type":"::"},{"file":"/data/config/www/nextcloud/cron.php","line":43,"args":["/data/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/data/config/www/nextcloud/lib/base.php","Line":282,"CustomMessage":"--"}}
```

**Comment by alexbelgium** [comment]
I can't replicate, and all the errors you are mentioning are perfectly normal and only due to the initial setup not being completed. 

Please follow the bug report template, otherwise it is complex to troubleshoot, in particular with the full addon log (from banner to loading) and addon config (in yaml format)

Btw, it is better to access webui with HA local IP and https to make sure there is no port forward issue on your router. Thanks

**Full addon log**


**Full addon config**

**Comment by Neotastisch** [comment]
I don't use portforwarding, I use a tunnel
Config:
```
Full_Text_Search: false
OCR: false
OCRLANG: de
PGID: 1000
PUID: 1000
certfile: fullchain.pem
data_directory: /share/nextcloud
elasticsearch_server: <ip:port>
keyfile: privkey.pem
trusted_domains: NeoHome.tk, your-domain2
use_own_certs: false

```
Full log:
```
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser.sh: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser.sh: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen.sh: executing... 
[14:36:03] INFO: No ssl certificates set. Auto generating ones...
Generating a RSA private key
..............+++++
........+++++
writing new private key to '/ssl/nextcloud/keys/cert.key'
-----
... adding ssl certs in files
[14:36:03] INFO: ... done
[cont-init.d] 30-keygen.sh: exited 0.
[cont-init.d] 40-config.sh: executing... 
[cont-init.d] 40-config.sh: exited 1.
[cont-init.d] 50-install.sh: executing... 
[cont-init.d] 50-install.sh: exited 0.
[cont-init.d] 60-memcache.sh: executing... 
[14:36:05] INFO: Setting data diretory: /share/nextcloud
[cont-init.d] 60-memcache.sh: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 92-local_mounts.sh: executing... 
[cont-init.d] 92-local_mounts.sh: exited 0.
[cont-init.d] 92-smb_mounts.sh: executing... 
[cont-init.d] 92-smb_mounts.sh: exited 0.
[cont-init.d] 99-add_packages.sh: executing... 
[cont-init.d] 99-add_packages.sh: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] 99-elasticsearch.sh: executing... 
Nextcloud is not installed - only a limited number of commands are available
Full_Text_Search option not set
[cont-init.d] 99-elasticsearch.sh: exited 0.
[cont-init.d] 99-mariadb_discovery.sh: executing... 
[cont-init.d] 99-mariadb_discovery.sh: exited 0.
[cont-init.d] 99-ocr.sh: executing... 
Nextcloud is not installed - only a limited number of commands are available
[cont-init.d] 99-ocr.sh: exited 0.
[cont-init.d] 99-trusted_domains.sh: executing... 
Nextcloud is not installed - only a limited number of commands are available
[14:36:21] INFO: Currently set trusted domains :
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
[14:36:23] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[14:36:23] INFO: Trusted domains set in the configuration. Refreshing domains.
[14:36:23] INFO: ... removing previously added trusted domain (except for first one created)
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
[cont-init.d] 99-trusted_domains.sh: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
{"reqId":"gmWUYuPmRB36BxW8nzEJ","level":3,"time":"2022-06-03T12:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Not installed","userAgent":"--","version":"","exception":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/data/config/www/nextcloud/lib/base.php","line":663,"function":"checkInstalled","class":"OC","type":"::"},{"file":"/data/config/www/nextcloud/lib/base.php","line":1104,"function":"init","class":"OC","type":"::"},{"file":"/data/config/www/nextcloud/cron.php","line":43,"args":["/data/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/data/config/www/nextcloud/lib/base.php","Line":282,"CustomMessage":"--"}}
Exception: Not installed in /data/config/www/nextcloud/lib/base.php:282
Stack trace:
#0 /data/config/www/nextcloud/lib/base.php(663): OC::checkInstalled()
#1 /data/config/www/nextcloud/lib/base.php(1104): OC::init()
#2 /data/config/www/nextcloud/cron.php(43): require_once('/data/config/ww...')
#3 {main}
```
Screenshot when I open the webpage
![Screenshot_2022-06-03-14-38-00-209_com.android.chrome.jpg](https://user-images.githubusercontent.com/54811660/171855426-6ba2e627-fe60-4edf-adc0-f09bf04abd93.jpg)

Ha-config:
Nothing changed(addon relevant)

I tryed a few other ha add-ons, same Problem (can't open the webpage)

**Comment by alexbelgium** [comment]
Hi,

> I tryed a few other ha add-ons, same Problem (can't open the webpage)

I'm sorry, then I can't help you it means the issue is with the tunnel config and not this addon... As I don't know this system I'm not sure how to help you. If this occurs with several addons, I would suggest that you post on the [community forum](https://community.home-assistant.io/) where there might be people with the same config as you

If you are using the cloudflare addon, here is the direct link : https://community.home-assistant.io/t/new-add-on-cloudflared

From the log at least everything seems good - do you have an mean to access HA from a local ip instead of your tunneled domain? That way you might do the initial set-up, then manage later the tunneling issue

Please let me know if there is another way I could help you

**Comment by Neotastisch** [comment]
> Hi,
> 
> > I tryed a few other ha add-ons, same Problem (can't open the webpage)
> 
> I'm sorry, then I can't help you it means the issue is with the tunnel config and not this addon... As I don't know this system I'm not sure how to help you. If this occurs with several addons, I would suggest that you post on the [community forum](https://community.home-assistant.io/) where there might be people with the same config as you
> 
> If you are using the cloudflare addon, here is the direct link : https://community.home-assistant.io/t/new-add-on-cloudflared
> 
> From the log at least everything seems good - do you have an mean to access HA from a local ip instead of your tunneled domain? That way you might do the initial set-up, then manage later the tunneling issue
> 
> Please let me know if there is another way I could help you

As I said, the tunnel is not the Problem, same Problem with the local ip, I use the cloudflared addon... And I'm using your portainer addon without any issues

**Comment by alexbelgium** [comment]
Portainer from webui or ingress? if it's with ingress then it's not a webui as such but it is opened from within HA itself which would explain it working

As long as you say you encounter the issue on several addons, this means it's due to your installation and not my addon, sorry - that's why I was mentioning you should use the community forum

**Comment by Neotastisch** [comment]
Yay I got it to work, no idea how but I did

**Comment by Neotastisch** [comment]
Sqlite, whats PUID and GUID?

**Comment by alexbelgium** [comment]
Mmh it should be full automatic...

**Comment by Neotastisch** [comment]
> Mmh it should be full automatic...

I deleted it and reinstalled it, same problem

**Comment by alexbelgium** [comment]
Thanks indeed I see the issue on your server. What is strange is that there is not this error on mine - it installs normally. I'll check some more

**Comment by Neotastisch** [comment]
> Thanks indeed I see the issue on your server. What is strange is that there is not this error on mine - it installs normally. I'll check some more
> 
> Could you please try running with PUID 0 GUID 0 ? Looking on internet it mostly seems to be an issue with permissions

Could you please explain to me what I have to check? I have no idea what PUID and GUID means, in the config it says 1000

**Comment by Neotastisch** [comment]
> Thanks indeed I see the issue on your server. What is strange is that there is not this error on mine - it installs normally. I'll check some more
> 
> Could you please try running with PUID 0 GUID 0 ? Looking on internet it mostly seems to be an issue with permissions

I'll try that, one second

**Comment by alexbelgium** [comment]
Thanks, I've pushed a new version to try to solve permission issues

**Comment by Neotastisch** [comment]
> Thanks, I've pushed a new version to try to solve permission issues 

Thanks, I'll try it later

**Comment by Neotastisch** [comment]
Same problem

**Comment by Neotastisch** [comment]
I tried using an local db from an addon, but there was an error:

```
Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Operation timed out
```

**Comment by Neotastisch** [comment]
I think I got it to work with the MariaDB addon, but now I get an internal Server Error (see yourself on nc.neohome.tk)

**Comment by Neotastisch** [comment]
Got it to work, but it's pretty slow, please try to improve that

**Comment by alexbelgium** [comment]
Hi, happy to read that it worked in the end. What did you do? That way I can add your knowledge to the addon documentation.  Thanks

For the speed, it's mostly impacted bumy the underlying app and software. For example I had a bug speed increase moving from rpi3 to rpi4. I suppose tunneling doesn't help also for speed. If you want to try another addon to see if the addon impacts speed, haberda has also developed one here : https://github.com/haberda/hassio_addons

Happy to know everything worked out in the end, have fun with the addons

**Comment by Neotastisch** [comment]
> Hi, happy to read that it worked in the end. What did you do? That way I can add your knowledge to the addon documentation.  Thanks
> 
> For the speed, it's mostly impacted bumy the underlying app and software. For example I had a bug speed increase moving from rpi3 to rpi4. I suppose tunneling doesn't help also for speed. If you want to try another addon to see if the addon impacts speed, haberda has also developed one here : https://github.com/haberda/hassio_addons
> 
> Happy to know everything worked out in the end, have fun with the addons 

Yeah, thanks, I used the MariaDB addon as a database, it took me ages to know where to put the data provided by the console, but it worked... Anyway to "prioritize" the addon

**Comment by alexbelgium** [comment]
Glad it worked! The info for the mariadb addon are in the log but I'll see to clarify in the documentation how to use it.

For addon prioritisation,

**Comment by alexbelgium** [comment]
Edit : I clicked by error on re-open, and edited my message above to clarify that resources prioritisation is a limitation of homeassistant and can't be modified at an addon level

**Comment by Neotastisch** [comment]
> Edit : I clicked by error on re-open, and edited my message above to clarify that resources prioritisation is a limitation of homeassistant and can't be modified at an addon level 

But in the addon it uses 0% of the CPU and only 3% of the ram... Anyway, thanks for the help(and the great addon) 😄

**Comment by KairuByte** [comment]
Was a cause ever found for this? I'm having similar errors. 

```

[25-Aug-2022 01:38:01] ERROR: [pool www] please specify user and group other than root
[25-Aug-2022 01:38:01] ERROR: FPM initialization failed
```

**Comment by alexbelgium** [comment]
Hi, have you tried setting the puid pgid to 1000:1000?

**Comment by KairuByte** [comment]
Ah, I had not. I was using the default of 0:0. Thank you!
