### ISSUE TITLE
FileBrowser: No Login when using ingress

### ISSUE THREAD

**Issue by ElVit** [alexbelgium/hassio-addons#35]
Hi @alexbelgium,

thanks for his great addon and the recently added ingress support.
I like this addon more and more. Good job!

In my opinion it would also be nice if the user has not to login if he is opening the FileBrwoser by ingress.

This is possible in e.g. the [Adguard Addon](https://github.com/hassio-addons/addon-adguard-home).
If opening Adguard by the IP+Port then a user+password is requierd (to test it I had to disable ssl and set a port).

It would also be possible to start FileBrowser [without authentication](https://filebrowser.org/configuration/authentication-method). But I don't know if this is a good idea...

**Comment by alexbelgium** [comment]
Hi! You can use the noauth option to remove need for login. Otherwise the app doesn't support white list addresses contrary to others... So you can't have one bahavior for ingress, and one for external connection.

BTW have you tried cloudcommander? It actually has more functions than filebrowser...

**Comment by alexbelgium** [comment]
BTW if you remove the port, the app is only connectable through ingress. So you need first to authentificate with HA before connecting to the app... Therefore removing the need for password completely

**Comment by ElVit** [comment]
> BTW have you tried cloudcommander? It actually has more functions than filebrowser...

Yes I tried it, but I like more the UI from FileBrowser.
Also imho the EditMode of the FileBrowser looks better. 
The font size in CloudCommanders EditMode is too big and it doesn't use the full screen. 
Especially on a phone I like FileBrowser more. On a PC I use the [VS Code Addon](https://github.com/hassio-addons/addon-vscode).

If I think about it maybe an option to use FileBrowser without authentication would be enough for me.
I start it only from HomeAssistant so I don't need the multi-users feature.

Would it be possible to add this [no authentication](https://filebrowser.org/configuration/authentication-method#no-authentication) option in your addon?

**Comment by alexbelgium** [comment]
well the no authentication is already there! you just need to go in the addon options and check "No-Auth" :-)
