### ISSUE TITLE
[transmission] Watch directory inaccesible and can not configure it

### ISSUE THREAD

**Issue by grunjol** [alexbelgium/hassio-addons#351]
**Which addon?**

- Addon name : transmission
- Addon version : 3.00-r5-ls125

**Describe the bug**

Log is flooded with error accessing watch directory (maybe not accesible by user service) and we can not configured to use it. 

**To Reproduce**

**Full addon log**
```
watchdir Failed to open directory "/watch" (2): No such file or directory 
(/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/watchdir.c:358)
```
**Full addon config**

**System**

- Supervisor version: 2022.05.3
- Host system version: core-2022.6.2
--

**Comment by alexbelgium** [comment]
I've pushed a new version that also allows to configure the watch-dir folder

**Comment by grunjol** [comment]
I can confirm the issue is fixed and watch_dir is working correctly
thanks @alexbelgium !

**Comment by alexbelgium** [comment]
Great, thanks!
