### ISSUE TITLE
[PhotoPrism] admin password

### ISSUE THREAD

**Issue by baldarn** [alexbelgium/hassio-addons#354]
**Which addon?**

PhotoPrism

**Addon or app?**

dunno

**Describe the solution you'd like**

I can't login with the admin user and I can't find it anywhere.
I also tried the command 
`photoprism passwd`
changing it and it didn't worked

I would show the default admin password in the description

**Comment by alexbelgium** [comment]
Hi, the default name and password are in the log when booting the addon

https://github.com/alexbelgium/hassio-addons/blob/a8fa76f738c9f55283b080d640f459a3dcd8ec68/photoprism/rootfs/etc/cont-init.d/99-run.sh#L92
