### ISSUE TITLE
[addon] TRANSMISSION NAS

### ISSUE THREAD

**Issue by Rubiolaso** [alexbelgium/hassio-addons#355]
Mounted localdisk cannot be used as Download path?
"Infos: Read-only file system /mnt/XXXX"

**Comment by alexbelgium** [comment]
Hi, that seems like a permissions issue. Is your PUID and GUID set either to 0, or to the same user to whom the files belong?

**Comment by Rubiolaso** [comment]
PUID and PGID are both 0, and i dont know who is the files owner since the addon is who mount the disk

**Comment by alexbelgium** [comment]
Have you tried setting the download_dir to /mnt/SSD/downloads (for example) in your addon config ?
This would be the normal way to set the directory, or else it will be replaced by the one in the addon config

**Comment by Rubiolaso** [comment]
Will try create a subfolder in my SSD
