### ISSUE TITLE
✨ [Request] Mealie v1

### ISSUE THREAD

**Issue by Tommatheussen** [alexbelgium/hassio-addons#356]
**Which addon?**

Mealie

**Addon or app?**

Addon

**Describe the solution you'd like**

Mealie has 'released' their V1, it's still in beta but so was the the v0.5 releases.
The 'problem' with the upgrade is they now switched to 2 different docker containers, backend and frontend.
I could switch to Tandoor, but it doesn't have a clear API. I'd eventually like to get the API support working into Home Assistant ;)
I'm not sure if it's worth the trouble to try and merge both Dockerfiles, but an initial effort was made here: https://github.com/hendrix04/mealie-combined

**Comment by alexbelgium** [comment]
Hi, hendrix04 has created a great combined image! Currently it only works on amd64 so I've already switched this architecture in my addon. Aarch64 should come at one point but a base image used is only based on amd64 and also would need to be multi-arch for this to happen. 

Here is the repo if you want to star it, and the issue thread where aarch64 is discussed : https://github.com/hendrix04/mealie-combined/issues/2#issuecomment-1163043687

**Comment by thibaultmol** [comment]
Any update on this?

**Comment by alexbelgium** [comment]
Until the upstream joint image is created I won't be able to build the addons, I think it is more difficult than expected for the upstream dev

**Comment by alexbelgium** [comment]
Hi, I've pushed a first test version of the frontend and API addons in my repo. You need to first backup all your data from within the current instance of Mealie, install the new addons, run the API one, configure the API url in the front end one, and run the fronted one. Then you can import back your data. Let me know how this goes!
