### ISSUE TITLE
Bashio broken Mealie addon

### ISSUE THREAD

**Issue by AhoyhoyGit** [alexbelgium/hassio-addons#36]
Hey,
Think your latest bashio update might have broken some addons:

21-08-09 21:27:46 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for db21ed7f/amd64-addon-mealie:0.5.2
21-08-09 21:27:49 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build db21ed7f/amd64-addon-mealie:0.5.2: The command '/bin/sh -c apk add --no-cache jq curl bash         && mkdir -p /tmp/bashio     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"     | tar -xzf - --strip 1 -C /tmp/bashio     && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -rf /tmp/bashio         && grep -rl "/app/data" /app | xargs sed -i 's|/app/data|/data|g'     && sed -i '1d' /app/mealie/run.sh     && cat /app/mealie/run.sh >> /nginx.txt     && cat /nginx.txt > /app/mealie/run.sh     && chmod +x /app/mealie/run.sh' returned a non-zero code: 127
21-08-09 21:27:49 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/21 : ARG BUILD_FROM
Step 2/21 : ARG BUILD_VERSION
Step 3/21 : FROM ${BUILD_FROM}
 ---> 6c1e1a77775e
Step 4/21 : COPY rootfs /
 ---> Using cache
 ---> 386192aae4a1
Step 5/21 : ARG BASHIO_VERSION=0.13.1
 ---> Using cache
 ---> f93195c13238
Step 6/21 : RUN     apk add --no-cache jq curl bash         && mkdir -p /tmp/bashio     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"     | tar -xzf - --strip 1 -C /tmp/bashio     && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -rf /tmp/bashio         && grep -rl "/app/data" /app | xargs sed -i 's|/app/data|/data|g'     && sed -i '1d' /app/mealie/run.sh     && cat /app/mealie/run.sh >> /nginx.txt     && cat /nginx.txt > /app/mealie/run.sh     && chmod +x /app/mealie/run.sh
 ---> Running in 3f7915a39da1
/bin/sh: 1: apk: not found

Removing intermediate container 3f7915a39da1

**Comment by alexbelgium** [comment]
Hi ! I've because the image for arm7 is based on Alpine and Amd64 on ubuntu... The new code should be universal for both. Could you please try it ?

Thanks!

**Comment by BrownFam** [comment]
@alexbelgium Mealie and Plex NAS installs fail with the same error codes. I am running Hasio on a Pi 4.

**Comment by alexbelgium** [comment]
Hi, have you tried the latest version of Mealie? It still doesn't work?

If it doesn't, is there no additional message below apk not found?

**Comment by alexbelgium** [comment]
Ah, for plex it was a stupid typo. Thanks, its solved

**Comment by alexbelgium** [comment]
If you don't see the new versions you'll have to manually refresh the repositories

**Comment by AhoyhoyGit** [comment]
Confirming I am now able to install Mealie in HassIO successfully. However haven't yet tried to configure and start the module

**Comment by AhoyhoyGit** [comment]
Installed and working without issue, thanks
