### ISSUE TITLE
[emby] Unable to start with error "fatal: can only run as pid 1"

### ISSUE THREAD

**Issue by kii24** [alexbelgium/hassio-addons#361]
**Which addon?**

- Addon name : Emby
- Addon version : 4.8.0.0

**Describe the bug**
Installed the Emby NAS add-on on Home Assistant OS, core version 2022.6.5. Left the configuration as below but add-on unable to start

**To Reproduce**
1. Go to Emby NAS add-on Info screen.
2. Click on 'Start', shows add-on as running.
3. Click on Log, shows error "s6-overlay-suexec: fatal: can only run as pid 1".
4. Click on 'Open Web UI' shows blank screen with error "502: Bad Gateway".
5. Navigate back to Emby NAS add-on Info page, the add-on status is not running.

**Full addon log**
(Only one line from the log)
s6-overlay-suexec: fatal: can only run as pid 1

**Full addon config**
PGID: 1000
PUID: 1000
silent: false
networkdisks: //192.168.0.101/movies,192.168.0.100/dramas
cifsdomain: WORKGROUP
cifspassword: xxxxxxxxxxxx
cifsusername: Aaron

**System**
- Supervisor version: supervisor-2022.05.3
- Core version: core-2022.6.5
- Host system version: Home Assistant OS 8.1

**Comment by alexbelgium** [comment]
Thanks, that's probably due to the new restrictions in HA... I'll look how I can update, thanks!

**Comment by alexbelgium** [comment]
With the latest HA update most of my addons died… I don’t know when I will be able to solve this as it will be very complex. Don’t update HA if you need to use my addons…

**Comment by alexbelgium** [comment]
Oh, that was easier than expected. Solved in "4.8.0.0-2"

**Comment by kii24** [comment]
Thanks for the quick work on this. 6 months with HA and I realize that latest HA often breaks addons. Will take note of that and avoid the latest HA updates

**Comment by alexbelgium** [comment]
Well updates are good for security, but I recommend to get regular backups! I use an addon named Google drive backup that automatizes the backup process: it's one of the most useful addons I've found. It allows to always have a backup at hand!

Thanks very much for the coffees, much appreciated!

**Comment by fcps3** [comment]
Same problem on Tdarr @alexbelgium
