### ISSUE TITLE
Teamspeak: Addon data do not survive addon restart

### ISSUE THREAD

**Issue by ogajduse** [alexbelgium/hassio-addons#365]
**Which addon?**

- Addon name : Teamspeak
- Addon version : 3.13.6

**Describe the bug**

Addon does not preserve database and server configuration. Data gets deleted with every container restart.

**To Reproduce**

1. Start the addon
2. Connect to the server using TS client
3. Use the generated privilege key to get admin privileges
4. Create room
5. Restart the addon
6. Log back in to the server

**Expected results**
After I log back in to the server, I should see the room that I created. ->Database and other necessary files are noy stored on the ephemeral storage.

**Actual results**
I do not see the room there and server asks me to enter the initial privilege key again. 

**Full addon log**

**Full addon config**

_default configuration_

**System**

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**Note**
I can give a hand with fixing it. I just need some hints to get started.

**Comment by alexbelgium** [comment]
Hi , thanks for reporting and proposing your help. The key element is that we find out where the database is store, then we either find a variable to change this location, or we create a symlink from the remanent folder to the expected location

Your help is welcome, otherwise I'll look to update it a bit later in the week. I'll create a branch so we can make our changes in a common location

**Comment by alexbelgium** [comment]
On which architecture are you (amd64, aarch64...) ? I see that I use different images depending on the architectures

**Comment by ogajduse** [comment]
In my diff tool, I do not see a difference between the two logs except timestamps and secrets.

**Comment by ogajduse** [comment]
Even backups are not working properly. I tried to restore the addon state from the backup, but the backup does not contain the TeamSpeak DB.

**Comment by ogajduse** [comment]
My architecture: aarch64 - RPi 4

Btw, I found official TS Dockerfile: https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images/blob/master/alpine/Dockerfile. 

I will try to investigate more tomorrow.

**Comment by alexbelgium** [comment]
Hi, the thing is that we need to symlink the sqlite database to a location that is remanent, such as /data. I thought this was done in the code but I don't have a working instance to test. Probably the symlink code needs to be adapted. It seems that the database stays within the temporary container but is not symlinked to its permanent location

**Comment by alexbelgium** [comment]
I've pushed a new version with a new logic that should work

**Comment by ogajduse** [comment]
Thanks @alexbelgium! The last patch seems to do the trick.
Addon version `3.13.6-3` preserves the DB.

**Comment by alexbelgium** [comment]
Thanks very much for the coffee!
