### ISSUE TITLE
[Nextcloud] Crashes out of nowhere

### ISSUE THREAD

**Issue by Neotastisch** [alexbelgium/hassio-addons#366]
Hey, me again, my Nextcloud Crashes out of nowhere and randomly

Can't give you the log since it crashes randomly without me doing anything

**Comment by alexbelgium** [comment]
Hi, I'm sorry but that's not really a workable bug report ;-)
Can be due to tons of things : nextcloud itself, failing SD card, some installed addons...
Have you tried a clean installation after backupping your current one ?

**Comment by Neotastisch** [comment]
Hey, not sure what information I give you except for that.
Yeah I've tried that
