### ISSUE TITLE
Cloud Commander Consuming 12.6GB of Virtual Ram?

### ISSUE THREAD

**Issue by aLTeReGo-SWI** [alexbelgium/hassio-addons#373]
Tested on CloudCommander 16.2.0 and 16.1.1. I'm seeing Cloud Commander consuming 12.6GB of VIrtual RAM. Is this normal? I don't ever recall seeing this behavior in the past. Running on Debian 11.

![image](https://user-images.githubusercontent.com/26488241/175797019-907e7dd7-552e-4d2c-a627-3a0a50de50d9.png)

![image](https://user-images.githubusercontent.com/26488241/175797020-a158359d-945b-4b3a-a840-ccce28b84716.png)

**Comment by alexbelgium** [comment]
Hi, that indeed seems a lot but I don't know what I could do from the addon side thấy could influence ram usage. Perhaps you should try posting on the app gtihub to see if they can help you?
