### ISSUE TITLE
[addons_updater] Issue description

### ISSUE THREAD

**Issue by jdeath** [alexbelgium/hassio-addons#375]
addons_updater

- Addon name : addons_updater
- Addon version : 3.8.11

If it wouldn't break any of your addons, could you add a `sed -e '/.*nightly.*/d' |` in addons_updater/rootfs/etc/cont-init.d/99-run.sh around lines 92 and 100?

A dockerhub addon I update, pushes a "versionNumber-nightly" but do not want the nightly version.

**Full addon log**

**Full addon config**

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hi, sure! Actually I'll probably add it only on line 92, as for line 100 a nightly tag could be an acceptable beta software. Right?

**Comment by jdeath** [comment]
Ok. Sounds perfect. Sure, next time I'll do a PR..

**Comment by alexbelgium** [comment]
Great, thanks!
