### ISSUE TITLE
[qBittorrent] Port forwarding help

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#376]
Qbittorrent.

Hi, this is more of a question. When I change my internal port to match the external port I can connect to trackers but am not open for incoming connections (the client refuses). When I keep the internal port as 6881 however it is open for connection but trackers have this port blacklisted so it doesn't work. I guess the question is do we know why this is happening and is there any way to change it?

Sorry for the poor wording, I hope this makes sense.

Thanks.

**Comment by hacshacdgacs** [comment]
![image](https://user-images.githubusercontent.com/85550264/176547317-5f4f92e3-2cc5-4989-99b8-7ee689f3bec5.png)
![image](https://user-images.githubusercontent.com/85550264/176547704-8ce25c5c-9742-4180-9f55-45ae80de6ff7.png)

This is the current setup now. 59595 in both the internal settings and in the config file. This allows me to connect to trackers but not be open to connections (port forwarding has been set up for 59595). 

When I had 59595 in the config page but had the internal qbit settings listening to 6881 I was able to be open to the connections but unable to connect to trackers as that port is blocked even though I was still portforwarding 59595 and the config file was set to that.

I hope that's explained more of my situation anyhow.

**Comment by alexbelgium** [comment]
Hi, thanks. What would be the solution? Changing the default qbittorrent port from 6881 to another port ? such as 59595 ?

**Comment by hacshacdgacs** [comment]
That should work, yes.

**Comment by alexbelgium** [comment]
I'll push a new version ASAP and we'll see how that goes ;-)

**Comment by hacshacdgacs** [comment]
That worked for me perfectly, thank you.

**Comment by alexbelgium** [comment]
Great news, thanks

**Comment by hiagocosta** [comment]
this ports can be changed?
