### ISSUE TITLE
[Jackett] No access to webUI

### ISSUE THREAD

**Issue by pkejval** [alexbelgium/hassio-addons#379]
Hello, I cannot access Jackett webUI at http://ha-ip:9117 nor http://ha-ip:8889 not hostname alternative. Browser returns "ERR_CONNECTION_REFUSED".

```
07-04 18:45:07 Info Jackett startup finished in 12.458 s 
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:8889
Application started. Press Ctrl+C to shut down.
```

in addon settings I have PGID 0, PUID 0, network port 9117

**Comment by alexbelgium** [comment]
Hi, strange it should not listen on this port. Is it a fresh install?

**Comment by pkejval** [comment]
Yes, it's fresh install. Never used it before but it's installed 2 weeks ago and few times updated. But I cannot access webUI from begining.

**Comment by alexbelgium** [comment]
Thanks, I'll check. It listens indeed on the wrong port

**Comment by alexbelgium** [comment]
I've done a clean install and it is the correct port. What most likely happened is that you changed the port in the webui without realizing. The best thing is to full uninstall (including deleting the folder in /config/addons_config/Jackett) and reinstall. To change he port, you should only do it from the addons options. Thanks!

**Comment by pkejval** [comment]
Thanks it's working now. I uninstalled addon,  deleted /config/addons_config/Jackett and installed again now I can access webUI at 9117. Thank you very much and sorry for false bug report.

I changed to 8889 because I cannot access webUI at 9117 when I first used addon. But when I changed it back to 9117 it stayed at 8889 inside container....

**Comment by alexbelgium** [comment]
Thanks for the feedback! Enjoy
