### ISSUE TITLE
[Qbittorrent] Fails to start

### ISSUE THREAD

**Issue by akrigator** [alexbelgium/hassio-addons#380]
**Which addon?**

- Addon name : Qbittorrent
- Addon version : 4.4.3.1-r1-ls205

**Describe the bug**

The login page only accessible

**To Reproduce**

1. Update the addon from 4.4.3.1-r1-ls204-5 to 4.4.3.1-r1-ls205

**Full addon log**
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
 Add-on version: 4.4.3.1-r1-ls205
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.7
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-folders.sh
cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/30-nginx.sh
cont-init: info: /etc/cont-init.d/30-nginx.sh exited 1
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/90-dns_set.sh
[10:37:06] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 0
cont-init: info: running /etc/cont-init.d/91-qbittorrent_configuration.sh
[10:37:06] INFO: Downloads can be found in /mnt/downloads
[10:37:07] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[10:37:07] INFO: WEBUI username set to admin
[10:37:08] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
curl: (3) URL using bad/illegal format or missing URL
cont-init: info: /etc/cont-init.d/91-qbittorrent_configuration.sh exited 3
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
Mounting smb share(s)...
[10:37:10] INFO: ... //192.168.88.2/downloads successfully mounted to /mnt/downloads with options ,vers=1.0,noserverino
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-openvpn.sh
[10:37:10] INFO: Direct connection without VPN enabled
cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service 00-legacy: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service 00-legacy successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
**Full addon config**

```
DNS_server: 8.8.8.8,1.1.1.1
PGID: '0'
PUID: '0'
SavePath: /mnt/downloads
Username: admin
certfile: fullchain.pem
customUI: vuetorrent
keyfile: privkey.pem
ssl: false
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
networkdisks: //192.168.88.2/downloads
cifsusername: xxxx
cifspassword: xxxx
cifsdomain: WORKGROUP
```
Network: default ports are used

**System**

- Supervisor version: 2022.05.3
- Host system version: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)

**Comment by EthicalObligation** [comment]
Thanks for leaving this! <3

> **Which addon?**
> 
> * Addon name : Qbittorrent
> * Addon version : 4.4.3.1-r1-ls205
> 
> **Describe the bug**
> 
> The login page only accessible
> 
> **To Reproduce**
> 
> 1. Update the addon from 4.4.3.1-r1-ls204-5 to 4.4.3.1-r1-ls205
> 
> **Full addon log**
> 
> ```
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service 00-legacy: starting
> s6-rc: info: service 00-legacy successfully started
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
> cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
> cont-init: info: running /etc/cont-init.d/00-banner.sh
> -----------------------------------------------------------
>  Add-on: Qbittorrent
>  qBittorrent is a bittorrent client
> -----------------------------------------------------------
>  Add-on version: 4.4.3.1-r1-ls205
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2022.6.7
>  Home Assistant Supervisor: 2022.05.3
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums
>  https://github.com/alexbelgium/hassio-addons
> -----------------------------------------------------------
> cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
> cont-init: info: running /etc/cont-init.d/00-folders.sh
> cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
> cont-init: info: running /etc/cont-init.d/01-envfile
> cont-init: info: /etc/cont-init.d/01-envfile exited 0
> cont-init: info: running /etc/cont-init.d/01-migrations
> [migrations] started
> [migrations] no migrations found
> cont-init: info: /etc/cont-init.d/01-migrations exited 0
> cont-init: info: running /etc/cont-init.d/02-tamper-check
> cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
> cont-init: info: running /etc/cont-init.d/10-adduser
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> Brought to you by linuxserver.io
> -------------------------------------
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    0
> User gid:    0
> -------------------------------------
> cont-init: info: /etc/cont-init.d/10-adduser exited 0
> cont-init: info: running /etc/cont-init.d/30-config
> cont-init: info: /etc/cont-init.d/30-config exited 0
> cont-init: info: running /etc/cont-init.d/30-nginx.sh
> cont-init: info: /etc/cont-init.d/30-nginx.sh exited 1
> cont-init: info: running /etc/cont-init.d/90-custom-folders
> cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
> cont-init: info: running /etc/cont-init.d/90-dns_set.sh
> [10:37:06] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
> cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 0
> cont-init: info: running /etc/cont-init.d/91-qbittorrent_configuration.sh
> [10:37:06] INFO: Downloads can be found in /mnt/downloads
> [10:37:07] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
> [10:37:07] INFO: WEBUI username set to admin
> [10:37:08] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
> curl: (3) URL using bad/illegal format or missing URL
> cont-init: info: /etc/cont-init.d/91-qbittorrent_configuration.sh exited 3
> cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
> cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
> cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
> Mounting smb share(s)...
> [10:37:10] INFO: ... //192.168.88.2/downloads successfully mounted to /mnt/downloads with options ,vers=1.0,noserverino
> cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
> cont-init: info: running /etc/cont-init.d/93-openvpn.sh
> [10:37:10] INFO: Direct connection without VPN enabled
> cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 0
> cont-init: info: running /etc/cont-init.d/99-custom-files
> [custom-init] no custom files found exiting...
> cont-init: info: /etc/cont-init.d/99-custom-files exited 0
> cont-init: warning: some scripts exited nonzero
> s6-rc: warning: unable to start service legacy-cont-init: command exited 1
> /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
> /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service 00-legacy: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service 00-legacy successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> ```
> 
> **Full addon config**
> 
> ```
> DNS_server: 8.8.8.8,1.1.1.1
> PGID: '0'
> PUID: '0'
> SavePath: /mnt/downloads
> Username: admin
> certfile: fullchain.pem
> customUI: vuetorrent
> keyfile: privkey.pem
> ssl: false
> whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
> networkdisks: //192.168.88.2/downloads
> cifsusername: xxxx
> cifspassword: xxxx
> cifsdomain: WORKGROUP
> ```
> 
> Network: default ports are used
> 
> **System**
> 
> * Supervisor version: 2022.05.3
> * Host system version: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)

Thanks for leaving this!

**Comment by EthicalObligation** [comment]
The login page is not even accessible for me

**Comment by alexbelgium** [comment]
Hi, thanks I'll look at it

**Comment by EthicalObligation** [comment]
> Hi, thanks I'll look at it

Might have to do with a dead link as: curl: (3) URL using bad/illegal format or missing URL
Also: running /etc/cont-init.d/30-nginx.sh fails

**Comment by akrigator** [comment]
> The login page is not even accessible for me

No matter, just cashed page)

**Comment by EthicalObligation** [comment]
Latest commit has this FATAL: /etc/cont-init.d/30-nginx.sh exited 141

**Comment by alexbelgium** [comment]
Thanks, weird issue I don't understand what this means... as curl works when run manually

**Comment by EthicalObligation** [comment]
Will look into it with a fresh installation of hass on my test bed and see if it persists. soon™

**Comment by alexbelgium** [comment]
The root cause is that the latest tag of the theme I use for ingress didn't have a zip file. This causes the curl to fail. I've tried getting the url from the releases url instead of latest and keep only the first result but then the error 141 came

**Comment by alexbelgium** [comment]
Should work now in "4.4.3.1-r1-ls205-2". I haven't realized what changed vs my latest code but now it starts without the error on my system

**Comment by akrigator** [comment]
> 

Strange stuff, but it started just now on db21ed7f/aarch64-addon-qbittorrent:4.4.3.1-r1-ls205, or the *ls205-2 build overrides *ls205?

**Comment by alexbelgium** [comment]
it's the same actually - what happens is that the zip that was missing missing from the third party repository has been added.
Now I'm trying to avoid recurrence through the code in *ls205-2 (not working).

My key problem is : 
```
LATEST_RELEASE=$(curl -f -s --retry 5 -L https://api.github.com/repos/wdaan/vuetorrent/releases |
    grep "browser_download_url.*zip" |
    cut -d : -f 2,3 |
    tr -d \" |
xargs)
```
gives a whole list of download links. I need to select only the first one, but can't find an easy way to do it

**Comment by EthicalObligation** [comment]
Thank you, it is working perfectly now!

**Comment by akrigator** [comment]
Thank you! Great job!
