### ISSUE TITLE
[Tandoor Recipes] CSRF verification error when logging in

### ISSUE THREAD

**Issue by SirJohnDoe** [alexbelgium/hassio-addons#385]
Just saw that the add-on supports ingress, so I went to try it. And it works up to a point: I can't manage to login due to this error:

![image](https://user-images.githubusercontent.com/11654657/177861425-b845dcb0-e977-4d07-bb38-b770bac2563a.png)

It seems to be this issue: https://github.com/TandoorRecipes/recipes/issues/518

**Comment by alexbelgium** [comment]
Hi, I started to implement ingress but it is broken in part as the way the app works does not make it easy to implement. Either I remove it completely, or I'll continue working on it in the future, but for the moment you can only access directly with ip:port

Sorry about that

**Comment by ConfidentKeyboard** [comment]
Has ingress addition bee completed as of now? Or still in progress?
