### ISSUE TITLE
[Whoogle] Not a real issue, but why ?

### ISSUE THREAD

**Issue by jojolll** [alexbelgium/hassio-addons#387]
Hello, 
I have been using the Whoogle addon recently. The interface is accessible via internet, using either

- search.mydomain.com 
- google.mydomain.com
- whoogle.mydomain.com

The Nginx reverse proxy is in charge of redirecting the requests on the port 5000 of the addon: 
![image](https://user-images.githubusercontent.com/26553241/178111669-c4407807-882b-430a-b743-9eefcf9d4f29.png)

A behavior escapes me. When I do a search from `search.domain.com`, the result usually sends me to `search.domain.com/search`
![image](https://user-images.githubusercontent.com/26553241/178111707-1e906c87-a3c0-44a8-8151-9ad88f143931.png)

If the search comes from my browser, the request appears in the URL bar
![image](https://user-images.githubusercontent.com/26553241/178111728-a4fa9deb-65ff-40d5-a897-8a629a9cf8f9.png)

Up to now, everything is clear. However, at certain moments (I really don't understand "when" this happens exactly), the URL changes and gives me an incomprehensible link of this type:
![image](https://user-images.githubusercontent.com/26553241/178111790-bf6bf10d-b81b-41c0-aabd-4126b888438b.png)

The search remains functional! The URL is same, with `/search` at the end when I ask for something.
![image](https://user-images.githubusercontent.com/26553241/178111845-e22f60d1-d2e1-44ed-ab48-ca7e8c3286b3.png)

But why is it talking about Ingress? It's not supposed to go through this function at all, since I use port 5000? 
And why does it only happen one search out of 20? 

On my smartphone, outside my local network it happens very often

I don't really understand, do you have any idea of "why" ?

**Comment by alexbelgium** [comment]
Hi, this behavior is to allow it working with ingress : I had to set a base url. Why it kicks in from an ip/port, I don't know... However as you say it shouldn't prevent any function.
