### ISSUE TITLE
[qBittorrent] Fails to launch after a fresh HA install. 

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#392]
**qBittorrent**

- Addon name : qBittorrent
- Addon version : 4.4.3.1-r1-ls206

**Describe the bug**

Addon fails to start on a fresh install of Home Assistant. Is acting similar to when it had a script that it was failing to activate when HA changed how things work a month or so back.

<!-- Steps to reproduce the behavior:
Launch the addon

**Full addon log**

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
 Add-on version: 4.4.3.1-r1-ls206
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.6.7
 Home Assistant Supervisor: 2022.07.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-folders.sh
cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/30-nginx.sh
curl: (3) URL using bad/illegal format or missing URL
cont-init: info: /etc/cont-init.d/30-nginx.sh exited 3
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/90-dns_set.sh
[23:11:35] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 0
cont-init: info: running /etc/cont-init.d/91-qbittorrent_configuration.sh
[23:11:35] INFO: Downloads can be found in /share/qBittorrent
[23:11:35] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[23:11:35] INFO: WEBUI username set to admin
[23:11:35] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
curl: (3) URL using bad/illegal format or missing URL
cont-init: info: /etc/cont-init.d/91-qbittorrent_configuration.sh exited 3
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-openvpn.sh
[23:11:36] INFO: Direct connection without VPN enabled
cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service 00-legacy: stopping
s6-rc: info: service 00-legacy successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stoppe

**Full addon config**

DNS_server: 8.8.8.8,1.1.1.1
PGID: '0'
PUID: '0'
SavePath: /share/qBittorrent
Username: admin
certfile: fullchain.pem
customUI: vuetorrent
keyfile: privkey.pem
ssl: false
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
cifsusername: 
cifspassword: 
silent: false

**System**

- Supervisor version: supervisor-2022.07.0
- Host system version: Home Assistant OS 8.2

**Comment by hacshacdgacs** [comment]
Unsure if you can actually see the rest of the information I gave in the post above, for me it's only showing the first two steps.

**Comment by alexbelgium** [comment]
Hi, indeed I can't see the full log. I've tested when a rebuild and it seems to work here. Does it work from backup?

**Comment by hacshacdgacs** [comment]
Hi so, after a day at work and another restart of the system everything is now running perfectly fine. 
I appreciate the help anyway. Thanks

**Comment by hacshacdgacs** [comment]
I tried a backup last night and that didn't work either. I'll upload the
full log in a txt file when I get home from work tonight. It seems like
it's throwing a similar error to when the script was failing to run when HA
changed things a little while back.

**Comment by alexbelgium** [comment]
Strange, I just rebuilt mine and it works great

**Comment by hacshacdgacs** [comment]
Unsure if this was an old thread that got necro'd but in case it wasn't. My
qbit has been working fine for a while now.
