### ISSUE TITLE
[UPDATE] Gazpar2mqtt

### ISSUE THREAD

**Issue by novisys** [alexbelgium/hassio-addons#394]
**Which addon?**
Gazpar2mqtt

name: Update to Last est version 0.8.2
about:
title: ''
labels: ''
assignees: ''

---

**Which addon?**

**Addon or app?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexbelgium** [comment]
Hi, the automatic update cycle takes at most 2 days after release

**Comment by novisys** [comment]
Ok Al we need now is to wait...
Thanks
