### ISSUE TITLE
Reporoster list down

### ISSUE THREAD

**Issue by tyjtyj** [alexbelgium/hassio-addons#396]
I dont know what is link for but it redirected to page with http causing HTTPS insecure error

https://reporoster.com/stars/alexbelgium/hassio-addons
redirected to
http://bytecrank.com/nastyox/reporoster/php/stargazersSVG.php?user=alexbelgium&repo=hassio-addons

https://github.com/alexbelgium/hassio-addons/blame/master/flexget/README.md#L17

**Comment by tyjtyj** [comment]
Inspect html shows it loading the img src file

<img src="https://reporoster.com/stars/alexbelgium/hassio-addons" alt="Stargazers repo roster for @alexbelgium/hassio-addons">

**Comment by alexbelgium** [comment]
Hi, thanks for noticing this. That's the code to show the number of stars that is hosted on a separate site to run the code... Is that an issue for a readme file?

**Comment by tyjtyj** [comment]
Not sure why u still need this but this site is already down
http://bytecrank.com/nastyox/reporoster/php/stargazersSVG.php?user=alexbelgium&repo=hassio-addons

If you using https, any link using http will result insecure page warning.

**Comment by alexbelgium** [comment]
Thanks, I'll check how to solve this

**Comment by alexbelgium** [comment]
I'm using this site to generate it : https://www.reporoster.com/ probably it has some difficulties for the moment as indeed even though the code generates the links it doesn't show images

**Comment by alexbelgium** [comment]
Hi, this was reported on their repo here : https://github.com/nastyox/Repo-Roster/issues/5

**Comment by alexbelgium** [comment]
I've changed the way to reference people having starred and will remove the invalid code. Thanks!

**Comment by ch4d1** [comment]
Hi, I also noticed this. It is intentional that the old code is still in there? Because of that there is still mixed-content, which leads to unsafe pages.

https://github.com/alexbelgium/hassio-addons/blame/master/plex/README.md#L17

**Comment by alexbelgium** [comment]
Well I had left both once it worked again, but I'll remove it then
