### ISSUE TITLE
Filebrowser: bigger file upload

### ISSUE THREAD

**Issue by macieksonik** [alexbelgium/hassio-addons#40]
I need to upload bigger (than 16MB) file using Filebrowser. How it is possible?

**Comment by alexbelgium** [comment]
Hi, I'm off for the moment without pc, but not sure how to do that. Have you checked the documentation? https://filebrowser.org/

Otherwise, you could try couldbrowser to see if it works!

**Comment by alexbelgium** [comment]
Hi, this is a limitation from HA : https://github.com/home-assistant/supervisor/issues/2950

If you need to upload more than 16mo you need to connect with ip:port

**Comment by alexbelgium** [comment]
The new version will allow an upload >16mb I've just tested it :)
