### ISSUE TITLE
[Nextcloud] Not load after last update

### ISSUE THREAD

**Issue by davoloko** [alexbelgium/hassio-addons#401]
**Nextcloud**

- Addon name : nextcloud
- Addon version :  24.0.3

Error when start

After update show the next error:

cont-init: info: /etc/cont-init.d/30-keygen.sh exited 0
cont-init: info: running /etc/cont-init.d/40-config.sh
Creating folders
Updating permissions
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: warning: unable to start service legacy-cont-init: command exited 111

Full_Text_Search: true
OCR: true
OCRLANG: esp
PGID: 1000
PUID: 1000
certfile: fullchain.pem
data_directory: /share/nextcloud
elasticsearch_server: <ip:port>
keyfile: privkey.pem
trusted_domains: >-
 *************************
use_own_certs: false

**System**

- Supervisor version: supervisor-2022.07.0
- Host system version: 5.10.0-15-amd64

**Comment by davoloko** [comment]
Hi @alexbelgium ! I think I have found where the problem is. I have created a fork and got the addon up and it is working fine.

It is the timeout
# Set S6 wait time
ENV S6_CMD_WAIT_FOR_SERVICES=1 \
    S6_CMD_WAIT_FOR_SERVICES_MAXTIME=300000 \
    S6_SERVICES_GRACETIME=300000

Setting 0 in the variables S6_CMD_WAIT_FOR_SERVICES_MAXTIME and the S6_SERVICES_GRACETIME starts correctly. 

It would be possible to modify it to continue using your image.

Thank you very much!

**Comment by alexbelgium** [comment]
Thanks, I've modified that also for all addons

**Comment by alexbelgium** [comment]
Do you confirm its now working with your fix? Thanks!

**Comment by davoloko** [comment]
Hi @alexbelgium! 

Apparently it works now. It seems that with the tests I have generated another problem and now I have the following error:

              Nextcloud is not installed - only a limited number of commands are available
              [08:31:37] INFO: Currently set trusted domains :
              Nextcloud is not installed - only a limited number of commands are available
                                                                                 
                There are no commands defined in the "config:system" namespace. 

I'm going to try to reinstall it to let it solved. Anyway, the timeout error no longer appears :D

Thank you very much!

**Comment by alexbelgium** [comment]
Great, this error just means that the initial config setup was not run yet. Congrats for finding the solution

**Comment by alexbelgium** [comment]
Closed as working
