### ISSUE TITLE
Mealie Smtp settings 

### ISSUE THREAD

**Issue by remb0** [alexbelgium/hassio-addons#404]
Maybe its already possible, but i doet know how. Is it possible to add more parameters in the settings?

**Comment by alexbelgium** [comment]
Hi, I suggest you check the app documentation : https://hay-kot.github.io/mealie/

My addon allows using it on HA but I do not develop the app. Thanks!

**Comment by remb0** [comment]
By default users can give parameters, but in the settings of the addon not.  Maybe I can't explain it right.

**Comment by alexbelgium** [comment]
I'm sorry indeed I don't understand... I think you mean to pasd ENV variables at container launch but I am not sure. Could you please point me the location in the documentation where what you want to achieve is described? It will probably help clarify communication. Thanks very much

**Comment by remb0** [comment]
In the docker compose we can use email parameters.
https://github.com/hay-kot/mealie/blob/mealie-next/docker-compose.yml

But I can't past them in de addon configuration. Only port pgid en puid.

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version allowing custom env variables.

You need to create the folder and file: /config/addons_config/mealie/config.yaml, and add your env variable in yaml format inside based on those values : https://nightly.mealie.io/documentation/getting-started/installation/backend-config/

For example, the content of your config.yaml could be :
```yaml
SMTP_HOST:  www.myhost.com
SMTP_PORT: 587
SMTP_FROM_NAME : Mealie
SMTP_AUTH_STRATEGY: TLS
SMTP_FROM_EMAIL: None
SMTP_USER: None
SMTP_PASSWORD: Password
```

If you are not sure of yaml format, you can search on Google "yaml online validator" and you'll find free resources to test your yaml for validity

**Comment by remb0** [comment]
thank you so much!
it works!   and mealie gave an error when not using '   '  around my variables.    so it's solved now.   many thanks!

**Comment by alexbelgium** [comment]
With pleasure, I'll close this if this is solved
