### ISSUE TITLE
🐛 [Spotweb] wont start

### ISSUE THREAD

**Issue by arcidodo** [alexbelgium/hassio-addons#405]
**Which addon?**

- Addon name : Spotweb
- Addon version : newest

just installed the addon an pressed start. 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
fix-attrs: info: applying /etc/fix-attrs.d/nginx
Segmentation fault (core dumped)
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
fix-attrs: warning: some fix files failed to apply
s6-rc: warning: unable to start service fix-attrs: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

none

none

- Supervisor version: latest
- Host system version: debian 11 latest

**Comment by alexbelgium** [comment]
Hi, corrected in newest version (-12)

**Comment by arcidodo** [comment]
yes it works now thx!, but the ingress page wont load correctly due certificate issues. using ha over HTTPS it wont load the JS/CSS files using ha over http it works correctly. (enabled the ssl in the config of the addon)

**Comment by alexbelgium** [comment]
A new version was pushed that should solve the issue

**Comment by arcidodo** [comment]
it works! (after removing the cache)  thanks!
