### ISSUE TITLE
[Request] nzbget HA ingress 

### ISSUE THREAD

**Issue by fbloemhof** [alexbelgium/hassio-addons#407]
**Which addon?**
NZBget

**Addon or app?**

**Describe the solution you'd like**
Is it possible to configure HA ingress for the Nzbget addon? 

**Describe alternatives you've considered**

**Additional context**
Would be great to access the addon trough HA and Nabu Vasa.

**Comment by alexbelgium** [comment]
Hi, I'll look at it when I have time. Ingress addition is depending on how the app is coded, either easy or impossible depending on the app

**Comment by alexbelgium** [comment]
Hi, I've pushed a first version, does it work ? Thanks

**Comment by fbloemhof** [comment]
First result looks good. Thanks!

Had to remove my port configuration to get it working.

**Comment by alexbelgium** [comment]
Strange that the port had to be removed, what was the message?

**Comment by fbloemhof** [comment]
I had an other port configured. When accessing it gave me a 503
I'm not sure of this error was from Nzbget or something else, accessing nzbget outside HA ingress was working.
