### ISSUE TITLE
✨ [REQUEST] calibre-web

### ISSUE THREAD

**Issue by julupanter** [alexbelgium/hassio-addons#409]
**Which addon?**

calibre-web

**Is your feature request related to a problem? Please describe.**

I want to convert books from this library to mobi format, to send them to kindle, but the addon need the calibre-convert binaries

**Describe the solution you'd like**

It would be gratefull to have this feature in the addon, as this web app is a very good way to manage the library

**Describe alternatives you've considered**

I also have the calibre addon, but I can't select the binaries from there, maybe it is not possible as they are different docker containers. If it is possible, will be a good idea to wirte how to in the readme.

In the docker container description says something about another image, that comes with this feature enabled:
https://github.com/janeczku/calibre-web:

> Github - (Optional Calibre layer) - https://github.com/linuxserver/docker-calibre-web/tree/calibre
>
>This image has the option to pull in an extra docker manifest layer to include the Calibre ebook-convert binary. Just include the >environmental variable DOCKER_MODS=linuxserver/calibre-web:calibre in your docker run/docker compose file. (x64 only)

**Thank you very much in advance.**

**Comment by alexbelgium** [comment]
Hi, thanks for having done the preliminary search work. Indeed I've found the active linuxserver mod and have added it to the latest version of the addon. There is no readme on how to use it but I hope this will be enough for you ?

**Comment by julupanter** [comment]
> Hi, thanks for having done the preliminary search work. Indeed I've found the active linuxserver mod and have added it to the latest version of the addon. There is no readme on how to use it but I hope this will be enough for you ?

Its working perfect. Only needed config it is to set the converter external binary to "/usr/bin/ebook-convert".

Thnal you very much for your quick response nada solution.

What a discovery your repo!!

**Comment by alexbelgium** [comment]
Thanks for the feedback! Glad it works!
