### ISSUE TITLE
Start sequence addons?

### ISSUE THREAD

**Issue by Calimerorulez** [alexbelgium/hassio-addons#410]
Hi,
Is there a way to configure the sequence how addons start?

The Bazarr, Sonarr and Radarr addons are dependent on the Samba share addon, because the last one exposes the smb share that Bazarr, Sonarr and Radarr use.

I'm getting errors now in that containers is that they can't find the smb share, because the Samba share isn't available when they start. After I restart Bazarr, Sonarr and Radarr, they works as expected.

**Comment by alexbelgium** [comment]
Hi, there are two ways to do this. Either you create an automation that starts the addons sequentially, or I change their startup priority. Currently, they start at the same time as HA (as a service) but they could start after HA (as an application). They would work only if the samba addon has a "startup: service" in its config.json

**Comment by alexbelgium** [comment]
I've already applied the second option now, but they first one is your way in if it doesn't work!

**Comment by alexbelgium** [comment]
All addons need to rebuild to have the new permissions. Given that the addons you mention are locally build, you can trigger a "rebuild" from the addon window (where you start it). At next start it will run after HA.

**Comment by Calimerorulez** [comment]
Thank you for your detailed and quick reply. Should I manually change anything to the Samba addon to make this work? I'm using the one from the official HA repo.

**Comment by alexbelgium** [comment]
Hi, I checked and it has the startup services in its config. Therefore it should now start before the addons, once you will have rebuild them

**Comment by Calimerorulez** [comment]
Hi @alexbelgium 

I've rebuilt the addons, rebooted my server, and all seems to be working fine now.
Thank you for your help :)

**Comment by Calimerorulez** [comment]
@alexbelgium I just bought you a coffee, but I forgot to type something in the tip note, but I hope you enjoy it :)

**Comment by alexbelgium** [comment]
Thanks very much! Highly appreciated :-) I'll go right away drink one in your name !
