### ISSUE TITLE
🐛 [Requestrr] Config isn't saved after reboot

### ISSUE THREAD

**Issue by Calimerorulez** [alexbelgium/hassio-addons#412]
Hi,

Sorry I'm not finished bugging you just yet ;)

It's now the third time I've configured Requestrr, but everytime I reboot the container, or the server, Requestrr looses its config.

There is nothing displayed in the Requestrr log, only that the app detects that its config is changed:

```
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
```
but that is nothing spectaculair. 

What can I check to see if something is wrong? Thanks again.

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version is it better?

**Comment by Calimerorulez** [comment]
I'm getting an error when upgrading:

`The command '/bin/sh -c sed -i "s|/config \|/data \|g" /etc/cont-init.d/30-config && if [ -f /etc/cont-init.d/02-tamper-check ]; then rm /etc/cont-init.d/02-tamper-check; fi && sed -i 's/bash/bashio/g' /etc/cont-init.d/10-adduser && sed -i 's/{PUID:-911}/(bashio::config "PUID")/g' /etc/cont-init.d/10-adduser && sed -i 's/{PGID:-911}/(bashio::config "PGID")/g' /etc/cont-init.d/10-adduser' returned a non-zero code: 1`

**Comment by Calimerorulez** [comment]
And some extra:

```
22-08-01 21:50:11 ERROR (SyncWorker_7) [supervisor.docker.addon] Can't build db21ed7f/amd64-addon-requestrr:2.1.2-2: The command '/bin/sh -c sed -i "s|/config \|/data \|g" /etc/cont-init.d/30-config         && if [ -f /etc/cont-init.d/02-tamper-check ]; then rm /etc/cont-init.d/02-tamper-check; fi     && sed -i 's/bash/bashio/g' /etc/cont-init.d/10-adduser     && sed -i 's/{PUID:-911}/(bashio::config "PUID")/g' /etc/cont-init.d/10-adduser     && sed -i 's/{PGID:-911}/(bashio::config "PGID")/g' /etc/cont-init.d/10-adduser' returned a non-zero code: 1
22-08-01 21:50:11 ERROR (SyncWorker_7) [supervisor.docker.addon] Build log: 
Step 1/25 : ARG BUILD_FROM
Step 2/25 : ARG BUILD_VERSION
Step 3/25 : FROM ${BUILD_FROM}
 ---> 706ad0e64562
Step 4/25 : ENV S6_CMD_WAIT_FOR_SERVICES=1     S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0     S6_SERVICES_GRACETIME=0
 ---> Using cache
 ---> f30fae370c79
Step 5/25 : RUN     sed -i "s|/config \|/data \|g" /etc/cont-init.d/30-config         && if [ -f /etc/cont-init.d/02-tamper-check ]; then rm /etc/cont-init.d/02-tamper-check; fi     && sed -i 's/bash/bashio/g' /etc/cont-init.d/10-adduser     && sed -i 's/{PUID:-911}/(bashio::config "PUID")/g' /etc/cont-init.d/10-adduser     && sed -i 's/{PGID:-911}/(bashio::config "PGID")/g' /etc/cont-init.d/10-adduser
 ---> Running in ce200fcb2833
sed: -e expression #1, char 21: unterminated `s' command
```

**Comment by alexbelgium** [comment]
Thanks, I see the error I'll push a new version.

**Comment by Calimerorulez** [comment]
Hi,

Rebuilt the addon, config was gone, configured the addon, restarted the addon, and the config is retained :)

Thank you again :)
