### ISSUE TITLE
🐛 [Portainer] Can't Install

### ISSUE THREAD

**Issue by wes1993** [alexbelgium/hassio-addons#414]
**Which addon?**

- Addon name : Portainer
- Addon version : 2.14.2

**Describe the bug**

Error processing tar file(exit status 1): write /opt/portainer/kubectl: no space left on device

**To Reproduce**

Try to install

**Full addon log**

NO

**Full addon config**

NO

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hello, this is inconvenient and I can't replicate. Have you actual space remaining on your device?

**Comment by wes1993** [comment]
Thanks for your fast reply and sorry for my delay, i'm installing again everythig
ill keep you updated thanks a lot
Stefano

**Comment by wes1993** [comment]
After i have reistalled everything seems work thanks a lot and sorry for the disturb :-(
Stefano

**Comment by alexbelgium** [comment]
The important is that it works! Enjoy the addon

**Comment by wes1993** [comment]
@alexbelgium 
Can i ask if you can create an addon based on this image here?
https://hub.docker.com/r/honeygain/honeygain
So i can install this from homeassistant and keep installation supported.
Thanks a lot
Stefano

**Comment by alexbelgium** [comment]
Hi, please create a separate request topic for that so I keep track of it. However I don't have much time for the moment so I won't be able to work on it

**Comment by alexbelgium** [comment]
For tinyproxy can't the existing nginx based addons fit your need? I would avoid creating an addon if there is already a solution existing

**Comment by wes1993** [comment]
@alexbelgium thanks again for your help and fast reply :)

unfortunately nginx seems more complex and I can’t find a way to add an header when request one link, with tiny proxy is more simple instead.

thanks a lot again
Stefano
