### ISSUE TITLE
[Scrutiny] Help needed to migrate to the official Scrutiny Image?

### ISSUE THREAD

**Issue by AnalogJ** [alexbelgium/hassio-addons#416]
Hey, 
I noticed that both [scrutiny](https://github.com/alexbelgium/hassio-addons/tree/master/scrutiny) and [scrutiny_fa](https://github.com/alexbelgium/hassio-addons/tree/master/scrutiny_fa) use the deprecated LSIO scrutiny images. 

Is there anything I can do to help you migrate to the official image? `ghcr.io/analogj/scrutiny:master-omnibus`
It does have an additional dependency on InfluxDB, but it also has a ton of bug fixes & features that may be relevant to your users. 

see the releases page for a changelist since v0.4.0 (when InfluxDB was introduced) - https://github.com/AnalogJ/scrutiny/releases

**Comment by alexbelgium** [comment]
Hi, thanks very much for reaching out, I'm glad that my work caught your attention.

I had indeed followed (from far) the latest development and was concerned about several elements that made me keep the current deprecated image as it was the easiest for me in terms of workload. Of course, as you are the dev I'm sure that the benefits outweigh the disadvantages ;-)

Why I had currently not implemented : 
- There will a break in user experience, as they will have to install an additional addon (influxdb) to continue using it. Good thing is that there is an official addon for influxdb which could hopefully limit the burden. Is there a way to continue using sqlite (like an ENV variable) for people who don't want to install influxdb (for example to limit the number of installed addons on a low-memory setting such as an rpi3) ?
- Is there a way to upgrade without losing data, meaning transferring in an automatic manner the previous database to the new system and avoid data loss ?

Thanks very much

**Comment by alexbelgium** [comment]
Btw, congratulations on your excellent app

**Comment by AnalogJ** [comment]
appreciate your kind words about Scrutiny -- and helping to bring it to the Home Assistant community 😃

> There will a break in user experience, as they will have to install an additional addon (influxdb) to continue using it. Good thing is that there is an official addon for influxdb which could hopefully limit the burden.

Completely understand, an additional dependency on InfluxDB could definitely make things more complicated for your users, especially if they have to manually install and configure another addon first. 
I have a couple of questions here: 

1. 	Do hassio addons have a concept of dependencies (can you specify the influxdb addon as a dependency, and have it automatically installed when your plugin is installed)?
2. 	Are hassio addons always installed via docker images? I noticed that you have [custom Dockerfiles](https://github.com/alexbelgium/hassio-addons/blob/master/scrutiny_fa/Dockerfile) in your scrutiny folders. Since you're already using `s6-overlay` to run multiple processes in the container, you could technically add influxdb into the container (similar to how I do in the [omnibus Dockerfile](https://github.com/AnalogJ/scrutiny/blob/master/docker/Dockerfile#L32-L33)) - then you wouldn't need to depend on the influxdb addon and the upgrade could be completely transparent to your users. 

> Is there a way to upgrade without losing data, meaning transferring in an automatic manner the previous database to the new system and avoid data loss ?

oh, this was actually one of the reasons it took me so long to release the v0.4.x branch. I'm happy to say that **yes**, Scrutiny has a built in data-migration system, that will automatically pull historical data from sqlite and move it to influxdb on first run. [Here's the general algorithm that I use](https://github.com/AnalogJ/scrutiny/blob/master/webapp/backend/pkg/database/scrutiny_repository_migrations.go#L71-L81). In general the upgrade should be completely transparent to your users (they should be completely unaware that the underlying database has changed -- as all their data will persist as normal). 

Hopefully that answers all your questions :)

**Comment by alexbelgium** [comment]
Thanks very much!

1. Hassio addons have a concept of depencies only for very specific elements preconfigured (such as mqtt or mariadb), which is not the case for influxdb
2. The link between HA and the addon is through a config.json/yaml file that tells it either to download a container image from github, or locally build it. It does this based on a Dockerfile that pulls either files from the github folder, or pulled from other sources (such as a pre-existing docker image). Your proposal to add influxdb through the dockerfile is a great idea, I'll check your omnibus file for that.

Great to know about the transfer tool ! It was one of my main concern actually :-)

I'll be soon be off on holidays and will have less time to check all these elements but updating the addons to the latest version will be on my radar for the very near future.

Thanks very much again

**Comment by alexbelgium** [comment]
I am encountering an issue for which perhaps you would have the knowledge to help me.
The nginx server for Ingress listens on the url http://HOST:PORT/api/hassio/INGRESSURL/

As scrutiny doesn't see the /web in the url, it tries to go to /web which redirects to http://HOST:PORT/web -> 404 error

In the past on the lsio versions, I was using a rewriting by sed of the files to avoid that which worked pretty well despite being a messy code : 
```bash
grep -rl '/web/' /app/scrutiny-web/ | xargs sed -i 's|/web/|./|g'
grep -rl '/api/' /app | xargs sed -i 's|/api/|api/|g'
grep -rl 'api/' /app | xargs sed -i 's|api/|./api/|g'
```

The traffic was redirected through nginx to http://backend/web/ which took care of the /web part.

This does not work anymore and lead to scrutiny to go to //web urls, and therefore broke its logical link where /web leads it to /web/dashboard as I understand.

Do you understand what I want to describe and see a way out of this ?
Thanks

**Comment by alexbelgium** [comment]
Ok, all is good I've made it work for ingress, next step is data persistence

**Comment by alexbelgium** [comment]
Hi, update is done

**Comment by AnalogJ** [comment]
awesome! thats great news

**Comment by alexbelgium** [comment]
Great, I'll close this then ; thanks again for your great app!
