### ISSUE TITLE
Emby NAS  WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access,

### ISSUE THREAD

**Issue by shirou93** [alexbelgium/hassio-addons#42]
hi,
on logs supervisor:

`21-08-25 16:17:33 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Emby NAS`

**Comment by alexbelgium** [comment]
Good news I found how to make it work :) the error won't appear anymore. Thanks for having highlighted it
