### ISSUE TITLE
Problem when installing Readarr on Homeassistant

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#421]
### Discussed in https://github.com/alexbelgium/hassio-addons/discussions/420

<div type='discussions-op-text'>

<sup>Originally posted by **Trodfoot** August  9, 2022</sup>
I thought since I am new at reporting errors I would first ask about it, rather than just put it in the issue area. Sorry if I am wrong.

So I am trying to install readarr as an addon to homeassistant and I go into configuration and change the location that put there /config/readarr  to /config/addons_config/readarr as that is where other addons are... When I go to the log to watch the container start up the config line that is passed to the program is being overwritten.  Here is part of the output:   [Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr/readarr]    I didn't add the radarr I checked 3 times. 
The next line is:  [Info] MigrationController: *** Migrating data source=/config/addons_config/radarr/readarr/readarr. So it got worse.  I have the full log if its wanted,  I didn't know how to link it as a download.  At least the programmer had a sense of humour because the next line read: [Fatal] ConsoleApp: EPIC FAIL!, I just thought no kidding.</div>

**Comment by alexbelgium** [comment]
Hi, Ahah, love programmer's humour :)

Actually it was a residual code issue in my addon, a line that was relevant at some point in the past but not anymore. I've pushed a new version that hopefully solves this. Thanks!

**Comment by alexbelgium** [comment]
Adding this here for traceability

**Comment by airtonix** [comment]
....420
