### ISSUE TITLE
[omada] automatic updates for Omada addon

### ISSUE THREAD

**Issue by ankushg** [alexbelgium/hassio-addons#422]
**Which addon?**

Omada Controller

**Describe the solution you'd like**

Your Omada controller addon doesn't currently get automatically updated when the upstream docker image is updated.

It would be nice to get an `updater.json` file set up for your addon

**Describe alternatives you've considered**

- manually creating an issue here when there's an update, or
- manually updating from within the addon and hoping things don't break

**Additional context**

The upstream docker image for omada gets updated automatically when there's a new release, and it would be great if the HA addon also got those updates automatically :)

**Comment by alexbelgium** [comment]
Hi, the updater.json is created, let's see how that goes

**Comment by ankushg** [comment]
Nice!

I think there's still something a bit funky with the container image versioning... It has versioned tags, but the tags don't get updated for patch releases of the Omada Controller

e.g., let's say
- TPLink releases a new version of the Omada Controller at `5.4.6`
- the github repo for the docker container is updated to download 5.4.6 when the container is created
- a new Docker image is pushed to the **already existing** `5.4` tag 

Is there any way for the updater to detect that the existing tag has a new hash and should be rebuilt?

**Comment by alexbelgium** [comment]
Alas I need a place in github or dockerhub showing this versioning as a release... There is no way for me to infer the real version... I'll look at the hash idea

**Comment by alexbelgium** [comment]
Should be good now! I've based it on the last update date instead of the hash to have something smaller in theory
