### ISSUE TITLE
[Question] Configuration file

### ISSUE THREAD

**Issue by tkupka** [alexbelgium/hassio-addons#423]
Hello,
here https://github.com/alexbelgium/hassio-addons/tree/master/nextcloud#configuration the configuration is described. What is the file format ? Is it standard configuration.php ? Can you provide simple example?

The *.sh scripts located in `/config/addons_config/nextcloud` are executed fine. I haven;t found a way how to configure from *sh script.

**Comment by tkupka** [comment]
config tab was missing in HA after installing, now it's there

**Comment by alexbelgium** [comment]
Indeed the addons can't create file there when installing so they only appear at first boot
