### ISSUE TITLE
Tandoor recipes

### ISSUE THREAD

**Issue by Tntdruid** [alexbelgium/hassio-addons#427]
The addon wont start amymore:

env: can't execute '/entrypoint.sh': No such file or directory in the logs.

Current version: 1.3.3
Home Assistant 2022.8.4

**Comment by alexbelgium** [comment]
Hi, I'm sorry but I can't accept a request that doesn't follow the proper template for bug reports. I've tested the addon and it works, meaning that without further informations I can't support you
