### ISSUE TITLE
Joal - doesn't work

### ISSUE THREAD

**Issue by Cissoubaka** [alexbelgium/hassio-addons#43]
Could you limit to 2.1.24 as it's the only one working in docker ?

**Comment by alexbelgium** [comment]
Done, thanks for reporting! Should I stop automatic updates then? Or do you know if the next versions are expected to work?

**Comment by alexbelgium** [comment]
I see the issue, the upstream owner changed the tags nomenclature. I'll try aligning my code

**Comment by alexbelgium** [comment]
Just tested it should work now even with the latest version :)

**Comment by alexbelgium** [comment]
I'll close the issue but let me know if you still have an issue and I'll reopen it
