### ISSUE TITLE
✨ [REQUEST] Unpackerr add localdisk

### ISSUE THREAD

**Issue by crowley666x** [alexbelgium/hassio-addons#430]
**Which addon?**

Unpackerr

**Is your feature request related to a problem? Please describe.**

Config has no option for localdisks

**Comment by alexbelgium** [comment]
Hi, It won't be easily done due to the structure of the app itself

**Comment by alexbelgium** [comment]
Actually it won't be possible at all, I'm sorry... That's because it's built in go without bash included. I'll therefore have to close this request
