### ISSUE TITLE
🐛 [Transmission Openvpn] testaze file leftover after CIFS check

### ISSUE THREAD

**Issue by almico** [alexbelgium/hassio-addons#431]
**Which addon?**

- Addon name : Transmission Openvpn
- Addon version : 4.0-v8

**Describe the bug**

Using CIFS, the add-on performs some pre-flight check on the shared folder, but forgets to delete the file used for checks

I think the issue is in the following piece of code:
![image](https://user-images.githubusercontent.com/15247405/185583752-46737d47-cb38-4938-9b1c-0ca025a49a74.png)

where that "cp" should be changed to "mv".

**Comment by alexbelgium** [comment]
Nicely seen, thanks

**Comment by alexbelgium** [comment]
Should be good now, this will be implemented on next addon update. As this impacts all addons, I won't push individual updates
