### ISSUE TITLE
🐛 [Paperless] Leftover add-on Images

### ISSUE THREAD

**Issue by KairuByte** [alexbelgium/hassio-addons#434]
**Which addon?**

- Addon name : Paperless
- Addon version : All?

**Describe the bug**

When paperless updates, the previous images seem to stick around. With the addon image being 1.3 GB, this takes up quite a bit of space rather quickly.

**To Reproduce**

Just update Paperless, then check portainer.

**Comment by alexbelgium** [comment]
Hi, that's due to a bug in supervisor that's I've reported since January... Once this bug is solved I'll be able to migrate my addons to image based and avoid this... https://github.com/home-assistant/supervisor/issues/3414

**Comment by alexbelgium** [comment]
To be clearer, the way to avoid this docker bug is to avoid building locally the addons. However, the supervisor in HA bugs when an addon is updated from a locally build to a remote build image. This would lead to a loss of all data in /data, and the need for each individual user to remove and readd the addon and remake all its configuration. I prefer to wait for the debs to solve their big but they don't seem interested. If you know any python you are welcome to have a look at the bug report that I've linked!

**Comment by KairuByte** [comment]
My first thought it to have two different versions, one that is remote built, and another that is locally built. But I understand that becomes a problem farther down the road.

My main issue with the way things currently are, is that it requires users to pay enough attention to notice the loss of storage space, portainer installed, and enough knowledge of docker to understand how to handle it themselves.

I suppose there isn't a good solution for the current situation.

**Comment by alexbelgium** [comment]
The only sensible way would be for the devs to solve the supervisor bug, we need to find a way to reach them and that they understand the impact
