### ISSUE TITLE
🐛 [Nextcloud] Unable to mount SMB share with spaces in name

### ISSUE THREAD

**Issue by nkm8** [alexbelgium/hassio-addons#436]
**Nextcloud**

- Addon name : Nextcloud
- Addon version : 24.0.4

**Describe the bug**

When using an SMB share with a space in the share name, the add-on attempts to create a local mount with an invalid directory name. The YAML config doesn't accept a share name with spaces in it, so I tried replacing the spaces with `\040` based on the solution [here](https://serverfault.com/questions/1000200/unable-to-mount-cifs-share-in-fstab-with-spaces-in-share-name)

**To Reproduce**

Attempt to start the add-on with a config similar to mine

**Full addon log**

```
Mounting smb share(s)...
Using PUID 0 and PGID 0
[02:56:39] FATAL: Error, unable to mount //192.168.1.37/WD USB drive to /mnt/040drive with username *****, *****. Please check your remote share path, username, password, domain, try putting 0 in UID and GID
[02:56:39] FATAL: Here is some debugging info :
	Sharename       Type      Comment
	---------       ----      -------
	internal        Disk      
	WD USB drive    Disk      
	IPC$            IPC       IPC Service (localhost server (Samba, Ubuntu))
SMB1 disabled -- no workgroup available
[02:56:41] FATAL: Error read : mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
mount: mounting //192.168.1.37/WD USB drive on /mnt/040drive failed: No such file or directory
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
```

**Full addon config**

```
networkdisks: //192.168.1.37/WD\040USB\040drive
cifsusername: *****
cifspassword: ******
```

**System**

- Home Assistant 2022.8.6
- Supervisor 2022.08.3
- Operating System 8.4
- Frontend 20220802.0 - latest

**Comment by alexbelgium** [comment]
Hi, thanks, I've pushed a new code that hopefully will solve this

**Comment by nkm8** [comment]
@alexbelgium Thank you so much for the quick turn-around, I can confirm that the issue is fixed:

```
Mounting smb share(s)...
Using PUID 0 and PGID 0
[10:09:36] INFO: ... //192.168.1.37/WD USB drive successfully mounted to /mnt/WD USB drive with options 
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
```

Keep up the great work!
