### ISSUE TITLE
[omada] Not finding AP

### ISSUE THREAD

**Issue by riddertommie** [alexbelgium/hassio-addons#437]
[omada](https://github.com/alexbelgium/hassio-addons/tree/master/omada)

Question
about: Omada not finding AP
---

Hi All, 

I tried to use this app several times now, but I just can't seem to add devices.

They are simply not shown in omada

_No devices found.
The device will automatically appear in the list when it is detected on your network.
UDP 29810, TCP 29811, TCP 29812, TCP 29813, and TCP 29814 are required for device management, make sure that these ports are open in your firewall._

I have a working environment directly in docker (separate pc). There I unregistered the AP and start the hassio version. but there they are not visible. If i switch back to Docker they are found again and I can import them.

Am I missing something?  can/must i do something something extra?

Thanks!

**Comment by riddertommie** [comment]
Anybody?  tips?

**Comment by alexbelgium** [comment]
I'm not using this addon, but I think @ankushg does ; perhaps he can help us know if everything works ?
In terms of technics however ports are exposed so I don't see a specific reason why it wouldn't work

**Comment by Deckoz2302** [comment]
Issue is because the omada controller is running on the docker network. Omada controller needs the flag 'host_network' = 'true' in docker compose, so that omada runs on the host network - this way devices are discoverable.

**Comment by alexbelgium** [comment]
Hi, thanks I'll add that

**Comment by alexbelgium** [comment]
Thanks very much!

**Comment by Deckoz2302** [comment]
![Screenshot_20220829-134010](https://user-images.githubusercontent.com/8958480/187264158-a6da5b4b-c92d-40b8-8451-17ba418d2939.png)

Here's the merged PR up and running and discovering a device I abandoned from my physical hardware controller to show it working and discovering devices.  This issue can be closed 🤙

**Comment by ankushg** [comment]
Nice -- I think I may have been able to avoid this issue because I use DHCP Option 138 to have my router point all the APs to the static IP of my controller

**Comment by Deckoz2302** [comment]
> Nice -- I think I may have been able to avoid this issue because I use DHCP Option 138 to have my router point all the APs to the static IP of my controller

That definitely works, say if you had a omada hardware controller and migrated to a software controller. As the ER605 would have had to be adopted and configured for 138 to be in effect (unless you are using 3rd party router with 138). Likely wouldn't work for those who are setting up an omada environment from scratch with factory default hardware.  Nice to mention that though 👌

**Comment by riddertommie** [comment]
I can confirm its working now. Removed one of the AP in my working environment and after some time it shows 'pending' in the the Home assistent version.

Thanks!
