### ISSUE TITLE
🐛 [Emby & Sonarr] Won't mount localdisks. Invalid user

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#440]
Emby

- Addon name : Emby NAS
- Addon version : 4.8.0.7
- Addon name : Sonarr NAS
- Addon version : 3.0.9.1549
**Describe the bug**

After latest HA update it's failing to mount localdisks. Gives the following error
"Local Disks mounting...
Using PUID 0 and PGID 0
chown: invalid user: ‘PUID:PGID’"
No config changed on my end to cause this error.
Rolling back to older versions of the addon also doesn't fix the issue.

**Comment by alexbelgium** [comment]
Hi, thanks its a typo now solved. Please refresh your addons repository then update to the new versions I've pushed, or rebuild other affected addons

**Comment by hacshacdgacs** [comment]
Can confirm it works now, thanks for the quick fix.
