### ISSUE TITLE
✨ [REQUEST] XTEVE

### ISSUE THREAD

**Issue by thetux07** [alexbelgium/hassio-addons#442]
hello,
tahnk you for your job
i used home assistant with nginx proxy and i have https 
visibly, i'm not alone 
https://github.com/xteve-project/xTeVe/issues/327
it's possible to make this tweak with the fork of xteve included https option?
https://github.com/SenexCrenshaw/xTeVe
thank you

**Comment by alexbelgium** [comment]
Hi, I've updated the addon with this image

**Comment by thetux07** [comment]
thank you very much :)
