### ISSUE TITLE
✨ [REQUEST] Sabnzb

### ISSUE THREAD

**Issue by skank01** [alexbelgium/hassio-addons#444]
Hi, since i dont use nzbget, is there a chance you'll add sabnzb to your addons, i'm using a lot from you, this is the only left as i would have to add another repository from someone else :)
Just asking :)

**Comment by ping-localhost** [comment]
NZBGet is deprecated since December 31, 2022, so having SABNzb would be great!

**Comment by pbvdven** [comment]
There is an "active" fork for nzbget https://github.com/nzbget-ng/nzbget

**Comment by ping-localhost** [comment]
> There is an "active" fork for nzbget https://github.com/nzbget-ng/nzbget

Good to know, too bad I already fully switched 😂

**Comment by red-centre** [comment]
> I've pushed a first version. Let me know how it goes. It doesn't seem to support ingress though

hey - thanks very much for doing this - I get an error installing (I think it might have something to do with the "test" status - maybe I have to change a system setting to allow installing "test" addons?)


Can't install ghcr.io/alexbelgium/sabnzbd-amd64:test: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=test&fromImage=ghcr.io%2Falexbelgium%2Fsabnzbd-amd64&platform=linux%2Famd64: Internal Server Error ("Head "https://ghcr.io/v2/alexbelgium/sabnzbd-amd64/manifests/test": denied")

**Comment by alexbelgium** [comment]
Thanks, I've pushed a version test2 that this time has a package and will avoid this issue
