### ISSUE TITLE
🐛 [XTEVE] database don't update

### ISSUE THREAD

**Issue by thetux07** [alexbelgium/hassio-addons#445]
the home of Xteve as change with the new version of SenexCrenshaw
config folder : /home/xteve/conf
bin folder: /home/xteve/bin
Do you have any other changes to make on your side?
thank you

**Comment by alexbelgium** [comment]
Hi, 

Normally the location should not impact as in Dockerfile the command is  ‘CMD ["-config", "/data", "-port", "34400"]‘, so it's strange it doesn't update

**Comment by thetux07** [comment]
thank you, i'm sorry but it don't work :(
the addon don't start and in log i have: 
/bin/sh: /data/bin/xteve: not found

**Comment by alexbelgium** [comment]
I've pushed a new version that should avoid that, does it allow data persistence? Thanks

**Comment by thetux07** [comment]
ok now it work perfectly 
however, you have to remap the channels but it works with an https host and a redirection to a domain name, thank you very much!
