### ISSUE TITLE
🐛 [Emby] Library not loading

### ISSUE THREAD

**Issue by skank01** [alexbelgium/hassio-addons#450]
**Which addon?**

- Addon name : Emby NAS
- Addon version : Latest

**Describe the bug**

Movie collection is not loading/ not showing covers

**System**

Raspberry pi 4
HA OS latest version

Anyone experienced same behaviour on pi?

**Comment by alexbelgium** [comment]
Hi, for me everything is working, have you checked the permissions of your emby system and its data folder?

**Comment by skank01** [comment]
MMM maybe i should look into the permissions stuff indeed.
Normally when i acces my movies on unraid, i need to fill in user and pw.
However when i pointed to it in emby on HA (pi), i didnt need to fill that in.
Any idea how i can check? I opened a topic on emby forum as well

**Comment by skank01** [comment]
I think i was too early in reporting.
Working fine now.

Before closing this, can i jusk ask if its possible to make bazarr/ organizr / radarr and stuff also ingress? Or is that impossible?
Reason why i ask this is, that i'm using cloudflare to acces my instance outdoor.
The nebget and emby addon is reachable cause its ingress..
The bazarr, organizr and stuff isnt  cause its not loading..

**Comment by alexbelgium** [comment]
Great news! For the other addons I think there are requests open for ingress addition but I don't have time for the moment to implement new requests

**Comment by skank01** [comment]
Ok no problem, thx for the help !
