### ISSUE TITLE
[Piwigo] Docker service error during update from 12.2.0 to 12.3.0

### ISSUE THREAD

**Issue by jordanauge** [alexbelgium/hassio-addons#451]
**Which addon?**

- Addon name : piwigo
- Addon version : 12.3.0

**Describe the bug**

When upgrading the piwigo addon, an error is raised by the docker service which is unable to retrieve the docker image. (see error log).
Updating other addons worked.

**To Reproduce**

1. Go to Add ons / Piwigo
2. Click on 'INSTALL' to install the update
3. See error in GUI (transient popup), found also in supervisor log (ha supervisor log)

**Full addon log**

```
INFO (SyncWorker_5) [supervisor.docker.interface] Updating image ghcr.io/alexbelgium/piwigo-armv7:12.2.0 to db21ed7f/armv7-addon-piwigo:12.3.0
INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image db21ed7f/armv7-addon-piwigo with tag 12.3.0.
ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install db21ed7f/armv7-addon-piwigo:12.3.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=12.3.0&fromImage=db21ed7f%2Farmv7-addon-piwigo&platform=linux%2Farm%2Fv7: Not Found ("pull access denied for db21ed7f/armv7-addon-piwigo, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
```

**Full addon config**

N/A

**System**

- Supervisor version: 2022.08.5 
- Host system version:  2022.8.7

**Comment by alexbelgium** [comment]
I haven't had a response in 8m, but you could try creating a new issue on the supervisor to say that an addon without an IMG tag (therefore auto build) tries to download a remote image...

**Comment by alexbelgium** [comment]
It is building and the image should be up soon, but if other people had installed it with autobuild they won't be able to update

**Comment by jordanauge** [comment]
Thanks for spotting the origin of the bug and as usual the prompt support. I had spent a bit of time on trying to understand it with no success (I was not aware of autobuilds).

**Comment by alexbelgium** [comment]
Thanks! And for the message on supervisor thread

**Comment by jordanauge** [comment]
At least with your change the update works. Let's hope we can have the proper fix implemented in HA...

**Comment by alexbelgium** [comment]
I'll close this as the initial issue is solved, have a nice day
