### ISSUE TITLE
Lost Password

### ISSUE THREAD

**Issue by WorldOfMaze** [alexbelgium/hassio-addons#455]
I was using Portainer a while ago and after changing my configuration, I removed it as I did not need it any longer.  Now I do not remember my credentials.  After removing and reinstalling the add-on, I still do not have the option to reset the new password.  Looking at the log, I do see this line:

```time="2022-08-31T17:05:40Z" level=info msg="Created admin user with the given password."```

Can someone help me get back into Portainer?

Thanks.

**Comment by WorldOfMaze** [comment]
Worked!  Thank you for the quick response.

**Comment by alexbelgium** [comment]
Glad it worked!

**Comment by wes1993** [comment]
Hello,
how can i reset the password of Portainer addon? i can't find the option in settings..

Best Regards
Stefano

**Comment by alexbelgium** [comment]
Hi, if you change it from the addons options it will reset the portainer database and use your new password. If it doesn't show in the addon option either you have an issue with your system or you need to clear on the "more options" tab that was included in latest versions of HA

**Comment by wes1993** [comment]
Thanks for your fast reply @alexbelgium,
So rry bu i can't find this "more options" tab, this is my options tab of portainer:

![image](https://user-images.githubusercontent.com/52070589/214283807-983e8f12-a627-43e7-976b-991a107918ad.png)

**Comment by wes1993** [comment]
Damn... sorry very very stupid question... I thought that was the password for the SSL certificates...

**Comment by alexbelgium** [comment]
No worry! There are no stupid questions ;-) have a nice day
