### ISSUE TITLE
[Jellyfin] L'interface ingress est elle utile/utilisable ?

### ISSUE THREAD

**Issue by jojolll** [alexbelgium/hassio-addons#459]
**Which addon?**

Jellyfin

**Additional context**

Salut,

J'ai installé l'addon Jellyfin ce matin. J'ai réussi à le configurer via mon navigateur (hors ingress, homeassistant.lan:8096)
Une interface ingress est incluse à l'addon, mais voici ce que ça me donne : 
![image](https://user-images.githubusercontent.com/26553241/187977479-f4721710-b603-468a-9c7f-fdfbad6a9a43.png)

J'ai à peu près tout essayé (adresses publiques, privées, ports...), rien n'y fait, elle n'accède jamais au serveur Jellyfin et donc ne peut pas être utilisée.
Est-ce que quelque chose m'échappe dans la configuration de l'UI ingress, ou cette option n'est pas réellement utilisable ? 

Merci d'avance et désolé du dérangement,

Jonathan

**Comment by alexbelgium** [comment]
Bonjour, je viens d'essayer et ça marche nickel. Le premier point est de s'assurer de ne pas faire tourner emby et jellyfin en même temps, car ils utilisent tout deux le port 8096.

Ensuite il suffit de mettre l'ip local:8096 dans l'onglet serveur. Ou le domaine, si un mapping de port existe.

**Comment by jojolll** [comment]
J'ai installé uniquement Jellyfin, et taper `http://192.168.1.12:8096` ou `http://homeassistant:8096` dans mon navigateur fonctionne tout à fait. C'est étrange s'il n'y a que chez moi ! Je continue de chercher mais je pense avoir fait le tour de toutes mes options.

**Comment by alexbelgium** [comment]
Curieux... En fait ingress concerne juste l'interface utilisateur donc si c'est accessible via http://192.168.1.12:8096 par un navigateur ça devrait l'être depuis Ingress aussi ! Y a-t-il un message dans le log de l'addon ? Par contre c'est normal que homeassistant.lan ne fonctionne pas depuis Ingress

**Comment by jojolll** [comment]
Malgré d'autres essais, je n'ai trouvé aucune solution pour faire fonctionner l'interface Ingress. Elle ne parviens pas à communiquer avec le serveur Jellyfin. 
Vu que ça semble venir de mon installation et que ce n'est pas du tout un point bloquant, je préfère fermer l'issue.

**Comment by alexbelgium** [comment]
Comme tu veux, c'est vraiment étrange. Pour tes lignes d'erreur, j'ai trouvé ça :
https://www.reddit.com/r/jellyfin/comments/osdswv/jellyfin_connection_error_after_network_change/
"I deleted the stack in portainer, then the image, then deleted the network xml files in the config folder. Redeployed the stack, and voila."

Donc ça pourrait être un problème réseau. Il est toujours utile de mettre un DNS fixe dans HA, et désactiver l'ipv6 peut parfois résoudre certains soucis aussi

**Comment by jojolll** [comment]
Je te remercie pour la piste. Une réinstallation clean de l'addon en suivant ces consignes ne change rien aux symptômes malheureusement. Toujours aucune connexion possible depuis ingress. 

Je n'ai déjà pas d'IP fixe, et mon DNS est fixe : c'est le module AdGuard home. Ceci dit, vu que je tape l'adresse IP directement, il ne devrais pas y avoir de problème de DNS, mais plutot de routage j'imagine. Dans tous les cas je vais désinstaller le module, mon serveur domotique manque de performances pour utiliser Jellyfin (Rpi 4) 😢. Je me contenterais de Kodi client side.

**Comment by alexbelgium** [comment]
C'est vraiment curieux, j'utilise emby sans soucis avec un rpi4 (et avant sur un rpi3b) ! Le tout est de désactiver le transcoding, et ça fonctionne tout seul. J'ai ensuite le plugin kodi pour réccupérer la bibliothèque emby sur kodi. 0 lag!

**Comment by jojolll** [comment]
>  Le tout est de désactiver le transcoding, 
Sauf que sur Jellyfin on ne peut pas réellement le désactiver :) Du coup, en fonction de la vidéo et du lecteur, une fois sur 10 il y aura un transcodage (saturation RAM et CPU du pi 4 grosso modo, pas fou).

J'utilise Kodi sans aucun intermédiaire, il lit directement les NFO générés par Sonarr/Radarr. Quelle est la valeur ajoutée d'un serveur type EMBY dans ton cas vu que tu utilise aussi KODI ? Je n'arrive pas à bien comprendre 😉

**Comment by alexbelgium** [comment]
Car j'utilise mon HA comme un NAS. Je télécharge depuis HA sur un disque dur en usb, le contenu est importé dans Emby puis distribué soit localement à kodi, soit à distance sur d'autres de ces via l'app emby qui se connecte au serveur via mon domaine internet. Pour kodi j'utilise un NUC Intel, mais que je n'allume que quand j'en ai besoin
