### ISSUE TITLE
[Epic Games Free] Base image has been updated

### ISSUE THREAD

**Issue by KairuByte** [alexbelgium/hassio-addons#460]
The base image for `Epic Games Free` has been updated, and the add-on is now using an outdated docker image.

One thing to note, this image can get frequent updates, sometimes multiple in a week, so it may be beneficial to incorporate automation if it is at all possible.

**Comment by alexbelgium** [comment]
Hi, that's strange as the app itself wasn't updated : https://github.com/claabs/epicgames-freegames-node

**Comment by KairuByte** [comment]
Ah, yeah I forgot about that...

Sometimes the image gets updated without pushing a release. For example, the latest image is 22 days old, but the last release was in may.

I'm not certain on the best way to automate such a situation, but I believe the images are updated in these two places: 
- https://hub.docker.com/r/charlocharlie/epicgames-freegames
- https://github.com/claabs/epicgames-freegames-node/pkgs/container/epicgames-freegames-node
- 
Not sure if either works for automation.

**Comment by alexbelgium** [comment]
Hi I've updated the system to update based on date and not version

**Comment by KairuByte** [comment]
Tyvm!

**Comment by KairuByte** [comment]
@alexbelgium this seems to be broken still? As can be seen [here](https://github.com/claabs/epicgames-freegames-node/pkgs/container/epicgames-freegames-node) the last update was 4 days ago.

**Comment by alexbelgium** [comment]
Hi, indeed, I've modified the script and it will now be automatic

**Comment by KairuByte** [comment]
Ah, thank you. I saw the update but forgot to confirm here. Seems to be working well!
