### ISSUE TITLE
MANY BUGS FOR THE MOMENT

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#467]
Linuxserver images, on which several of my addons are based, are changing their internal structure. It causes issues with many addons. I'll adapt them soon but am too busy this week. Thanks for your understanding, due to that I've paused the automatic updates to limit the impact on users

**Comment by diamant-x** [comment]
Hi,
I noticed que qbittorrent no longer respects existing configurations and instead overwrites as if if was a new install (although it hopefully preserves the torrent list).

- Is this issue related with upstream linuxserver issues?
Else, could you please take a look or should I open a different ticket?
Thanks.

**Comment by alexbelgium** [comment]
Hi, an issue was already opened here : https://github.com/alexbelgium/hassio-addons/issues/470 at the same time of your comment
