### ISSUE TITLE
QBitTorrent not showing network disk storage

### ISSUE THREAD

**Issue by tonysprenk** [alexbelgium/hassio-addons#47]
In the side panel of the vue UI it used to show the remaining storage of the network disk but after a reinstall it shows only the remaining disk spaces of the internal SD card even though I have specified the IP address of my network disk.

**Comment by alexbelgium** [comment]
I'm not sure why, It is a detail that I had never seen before... Did you reference the network drive as download path? I suppose it only shows the space of the target disk... Or don't you have a backup that could be restored of this addon?

**Comment by alexbelgium** [comment]
I've just tested and it shows my network disk usage. Please double check your referenced download directory.

**Comment by tonysprenk** [comment]
Is this config correct? 

```

ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
customUI: vuetorrent
SavePath: //192.168.4.67/HDD
Username: admin
DNS_server: 8.8.8.8,1.1.1.1
PUID: '0'
PGID: '0'
TZ: ''
openvpn_password: ''
networkdisks: //192.168.4.67/HDD
cifsusername: homeassistant
cifspassword: password

```
I also have an unrelated question; how can I change the default password for the webUI?

**Comment by tonysprenk** [comment]
I fixxed it. Download location should be /mnt/HDD.

**Comment by alexbelgium** [comment]
Exact! Does it work now? Enjoy!
