### ISSUE TITLE
NextCloud: I have successfully mount a network share, and it's showing in NextCloud, how do I use it as storage?

### ISSUE THREAD

**Issue by bobloadmire** [alexbelgium/hassio-addons#472]
Pretty much in the title. The network share is mounted successfully, but nextcloud is still using the SD card as storage. I set the data directory as the same location as the network mount, //192.168.0.100/Nextcloud, but it's still using the sd card. I also tried /mnt/Nextcloud, but that folder does not exist, contrary to the logs verbage.

**Comment by bobloadmire** [comment]
this seems to be the relevant logs, no errors.

`User uid:    1000
User gid:    1000
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser.sh exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen.sh
[09:34:20] INFO: No ssl certificates set. Auto generating ones...
Generating a RSA private key
............+++++
...................................+++++
writing new private key to '/ssl/nextcloud/keys/cert.key'
-----
... adding ssl certs in files
[09:34:21] INFO: ... done
cont-init: info: /etc/cont-init.d/30-keygen.sh exited 0
cont-init: info: running /etc/cont-init.d/40-config.sh
Creating folders
Updating permissions
cont-init: info: /etc/cont-init.d/40-config.sh exited 0
cont-init: info: running /etc/cont-init.d/50-install.sh
cont-init: info: /etc/cont-init.d/50-install.sh exited 0
cont-init: info: running /etc/cont-init.d/60-memcache.sh
[09:34:23] INFO: Setting data diretory: /mnt/Nextcloud
cont-init: info: /etc/cont-init.d/60-memcache.sh exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
Mounting smb share(s)...
Using PUID 1000 and PGID 1000
[09:34:25] INFO: ... //192.168.0.116/i/Nextcloud successfully mounted to /mnt/Nextcloud with options 
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-add_packages.sh
[09:34:25] INFO: Installing additional apps :
... inotify-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/1) Installing inotify-tools (3.20.11.0-r0)
Executing busybox-1.33.1-r8.trigger
OK: 289 MiB in 230 packages
cont-init: info: /etc/cont-init.d/99-add_packages.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
cont-init: info: running /etc/cont-init.d/99-custom_scripts.sh
cont-init: info: /etc/cont-init.d/99-custom_scripts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-elasticsearch.sh
Full_Text_Search option not set
cont-init: info: /etc/cont-init.d/99-elasticsearch.sh exited 0
cont-init: info: running /etc/cont-init.d/99-mariadb_discovery.sh`

**Comment by bobloadmire** [comment]
fixed, closed

**Comment by Eeeeeediot** [comment]
@bobloadmire Hey, I have the same issue - can you help by telling me how you resolved this?

**Comment by zagi988** [comment]
Yes, how did you fix it?
I'm trying to use /mnt/NAS folder for storage but keep nextcloud in /share/nextcloud but can't seem to figure out how.
