### ISSUE TITLE
🐛 [gitea] Enabling ssl in the addon config does not enable ssl

### ISSUE THREAD

**Issue by financelurker** [alexbelgium/hassio-addons#474]
**Which addon?**

- Addon name : gitea
- Addon version : 1.17.2

**Describe the bug**

If I enable ssl in the addon config the http port just listenes for http traffic.

**To Reproduce**

1. Go to 'addon config'
2. Click on 'ssl'
3. restart the service
4. open the web-ui with https://...
5. See error --> no TLS enabled

**Full addon config**

```yaml
certfile: fullchain.pem
keyfile: privkey.pem
ssl: true
```

**Findings**
To enable ssl in gitea there should be some extension to the `/data/gitea/conf/app.ini` file:
```ini
...
[server]
PROTOCOL  = https
CERT_FILE = /ssl/fullchain.pem
KEY_FILE  = /ssl/privkey.pem
...
```

Tho, the service is run as the "gitea" user, and the "/ssl" mount is only imported, so the "root" user can read the key... This leads to gitea not starting the service (I've tried it by accessing the container and manually adding that config).

See:
```bash
bash-5.1# pwd
/ssl
bash-5.1# ls -lha
total 20K    
drwxr-xr-x    3 root     root        4.0K Aug 13 07:10 .
drwxr-xr-x    1 root     root        4.0K Sep 12 07:09 ..
-rw-r--r--    1 root     root        3.6K Aug 13 07:10 fullchain.pem
-rw-------    1 root     root        1.7K Aug 13 07:10 privkey.pem
```

and

```
bash-5.1# ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/s6-svscan /etc/s6
   15 root      0:00 s6-supervise gitea
   16 root      0:00 s6-supervise openssh
   17 git       0:06 /usr/local/bin/gitea web
   18 root      0:00 sshd: /usr/sbin/sshd -D -e [listener] 0 of 10-100 startups
   64 root      0:00 bash
   80 root      0:00 ps aux
```

**Comment by alexbelgium** [comment]
Hi, thanks for reporting. Hi @baldarn, any idea ? Thanks!
I'll look at it also a bit later

**Comment by financelurker** [comment]
You're welcome.

And I don't know if this should be a dedicated new issue, but when "ssl" is enabled and you click on "OPEN WEB UI" it's opening the http-url.

Would be nice to configure the base-url in the addon as well (lets say: my dns config is a bit more complex 😁).

**Comment by alexbelgium** [comment]
At least the opening of webui with https is taken care of :-)

**Comment by alexbelgium** [comment]
Hi @baldarn, do you want to take it or I do ? I think the best would be to add a custom script when the addon starts to create the lines in `/data/gitea/conf/app.ini` as proposed by [financelurker](https://github.com/financelurker); with replacing the real ssl paths with $(bashio::config 'certfile')

**Comment by financelurker** [comment]
The other critical part would also be to manage to get access to the certfile and keyfile for the "git" user.

**Comment by alexbelgium** [comment]
Indeed, however the good thing is that the script itself has root access. Either it could copy the ssl files to a location inside the container and provide this path to the data config (more secure), or it modifies the ssl certificates to add gitea access (more robust as permissions kept if the certificates change while the addon is running)

**Comment by financelurker** [comment]
How are other addons handling this topic? I would prefer a solution where Let's Encrypt addon can renew the certs on the fly without service-disruption 🤘🏻

**Comment by baldarn** [comment]
Hi! Sorry for the problem.

I usually use a retroproxy on top (like nginx) to take care of SSL.

I'll take a look to native SSL for the add-on

**Comment by financelurker** [comment]
Perfect - with version 1.17.2.3 it seems to work. Changed the config (added ROOT_URL and DOMAIN) and the certificates from the let's encrypt addon are being used for TLS 👌🏻 I'll close that issue.
