### ISSUE TITLE
🐛 Overseerr configfile location unwritable

### ISSUE THREAD

**Issue by rjgout** [alexbelgium/hassio-addons#478]
Overseerr

- Addon name : Overseerr
- Addon version : 1.29.1-bugfix

When openeing the webui. You need to login with your Plex account to configure. But it was already setup correct. The log gives me this error.

[error][Plex Scan]: Scan interrupted {"errorMessage":"Permission denied even after attempted authentication :( Wrong username and/or password maybe?"}
2022-09-13T07:10:12.244Z [error]: Error checking user access: Plex is not configured! 

And the config file is not present at the location specified in the addon config.

Instant after startup.

**Full addon log**

 Add-on version: 1.29.1-bugfix
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.5  (amd64 / qemux86-64)
 Home Assistant Core: 2022.8.7
 Home Assistant Supervisor: 2022.08.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-config_location.sh
[09:09:17] INFO: Config stored in /config/addons_config/overseerr
cont-init: info: /etc/cont-init.d/00-config_location.sh exited 0
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Overseerr Github Sponsors: https://github.com/sponsors/sct
Overseerr Patreon: https://patreon.com/overseerr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun overseerr (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
yarn run v1.22.17
$ NODE_ENV=production node dist/index.js
2022-09-13T07:09:22.496Z [info]: Commit Tag: v1.29.1 
2022-09-13T07:09:22.550Z [info]: Starting Overseerr version 1.29.1 
2022-09-13T07:09:24.622Z [info][Notifications]: Registered notification agents 
2022-09-13T07:09:24.663Z [info][Jobs]: Scheduled jobs loaded 
2022-09-13T07:09:25.057Z [info][Server]: Server ready on port 5055 

CONFIG_LOCATION: /config/addons_config/overseerr
PGID: 0
PUID: 0
TZ: Europe/Amsterdam

Home Assistant 2022.8.7
Supervisor 2022.08.6
Operating System 8.5
Frontend-versie: 20220802.0 - latest

**Comment by rjgout** [comment]
Yes, there is no data. Just to make sure it should work with a clean install, I removed Overseerr. And reinstalled. Same problem. As if the config was still present. Then, I rebuild Overseerr, same result. Then Remove Overseer, also al the folders and in portainer the image. Still same result. What Can I do more to clean up a application. Seems something is stuck.

**Comment by rjgout** [comment]
I changed the location of the config file to: /config/overseerr
It creates the folder with nothing in it. It also creates the folder /config/addons_config/overseerr with the folders:
/config/addons_config/overseerr/addons_config
/config/addons_config/overseerr/custom-cont-init.d
/config/addons_config/overseerr/custom-services.d

But no files in those folders.

**Comment by encor50** [comment]
Hello i solved it with rolling back to the version 1.29.1 without the bug fix removed and clean install of Overseerr now it works or if you have a full backup remove Overseerr and its files then then do a partial restore to only Overseerr to version 1.29.1 :)

**Comment by alexbelgium** [comment]
Thanks! I really have limited time until the weekend to check but will roll it back then in the repo itself :)

**Comment by alexbelgium** [comment]
It's probably due to my new lsio code that impacted all addons and was intended to anticipate upstream migration to s6-rc that they are starting

**Comment by alexbelgium** [comment]
OK nearly there, now it seems to work as long as uid/gid 0 is used

**Comment by alexbelgium** [comment]
If you want I remove the puid/GUID setting and everything would work again. Is it an Orton that you use?

**Comment by alexbelgium** [comment]
I've removed puid/pgid, should work now

**Comment by rjgout** [comment]
Yes! Thanks. It works again.
