### ISSUE TITLE
✨ [REQUEST] update "Epic Games Free" addon from the last commit from claabs/epicgames-freegames-node

### ISSUE THREAD

**Issue by viny182** [alexbelgium/hassio-addons#482]
**Which addon?**

Epic Games Free

**Is your feature request related to a problem? Please describe.**

Yes, it seems that the current old version is not working.

\*\*If a new addon, have you checked on Google that such as addon doesn't already exists?

**Describe the solution you'd like**

Update addon with the last version from claabs/epicgames-freegames-node

**Describe alternatives you've considered**

Create my own docker image and run it outside HomeAssistant

**Additional context**

Not sure if the image is actually updated

**Comment by alexbelgium** [comment]
Hi, I've updated manually to version 938a9653ffd08b8284ea32cf01ac8727d25c5d4c

The updater script is confused by the strange versions numbering
