### ISSUE TITLE
🐛 [Bazarr] Missing default login information

### ISSUE THREAD

**Issue by elmerenges** [alexbelgium/hassio-addons#483]
**Which addon?**

- Addon name : Bazarr
- Addon version : 1.1.1-bugfix

**Describe the bug**

I just installed the addon and the default user/password is missing from the startup log.

**To Reproduce**

1. install the addon
2. start the addon

**Full addon log**

[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Bazarr NAS
 Companion application to Sonarr and Radarr to download subtitles
-----------------------------------------------------------
 Add-on version: 1.1.1-bugfix
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2022.9.4
 Home Assistant Supervisor: 2022.08.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun bazarr (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
2022-09-18 10:27:25,365 - root                             (7fd744d7cb38) :  INFO (signalr_client:48) - BAZARR trying to connect to Sonarr SignalR feed...
2022-09-18 10:27:25,365 - root                             (7fd753750b48) :  INFO (server:41) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2022-09-18 10:27:25,431 - root                             (7fd744d7cb38) :  INFO (signalr_client:64) - BAZARR SignalR client for Sonarr is connected and waiting for events.
**Full addon config**

PGID: 0
PUID: 0

**System**

- Supervisor version: supervisor-2022.08.6
- Host system version: Debian GNU/Linux 11 (bullseye), core-2022.9.4,

**Comment by alexbelgium** [comment]
Hi, I just reinstalled it and actually it goes right to the we page without asking for a password. Or did you set one yourself from within the app?

**Comment by elmerenges** [comment]
Hello! No, the login window opened for me. I reinstalled again, but it is the same. If I try random user/pass I get an error 400 message. It's strange sonarr, radarr and prowlarr from you worked out of the box.

**Comment by elmerenges** [comment]
I dig deeper, and find that I installed bazarr a long ago and completely forgot about it, and there was the old config file. Sorry for wasting your time, I closing this issue.

**Comment by alexbelgium** [comment]
Glad it worked! The readme was incorrect I've changed it. One day I might improve the readme documentation but it just takes too much time :) have a nice day, enjoy the addons
