### ISSUE TITLE
✨ [REQUEST] tandoor_recipes enable ingress

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#484]
Thanks for the update. I've tried it, and I don't have the error any more, but still have problems...
I can log in, but then, I'm stucked in this "Space" page. Wherever I click, I stay on this page. I can't even log out. (The only thing working on this page, seems to be the group creation).

![image](https://user-images.githubusercontent.com/43144578/191037483-ea084cb6-2993-4c04-ac33-4a2d5279b3ab.png)

Any idea why this is happening ? Do you think it can still be a problem with nabu casa ? Do you need logs ?

In the configuration, I didn't set anything in SECRET_KEY. Can it be the problem ? What should I set in this SECRET_KEY ?

Thanks,
Jérôme

_Originally posted by @jeromegoo in https://github.com/alexbelgium/hassio-addons/discussions/480#discussioncomment-3681409_

**Comment by alexbelgium** [comment]
Hi, this is a bug with ingress that I can replicate whatever the mean of connection... That's strange as nothing else has changed since the last time I tested it to be working. I'll investigate what could be the cause, but for the moment ingress doesn't work... On this addon ingress is quite complex to put in place so the slightest thing can derail it.. '

**Comment by alexbelgium** [comment]
I see the issue. It must be opened at least once on the device using a browser to write the "space" information in a cookie (I think). I'll continue checking how to make it work directly in ingress

**Comment by alexbelgium** [comment]
Hi, should be good now

**Comment by jeromegoo** [comment]
Hi Alex,
Thanks for update. Indeed, not stucked any more in spaces page. But the add-on seems still unstable. I get some 404 errors, when accessing some pages (ex after adding a recipe, and click on the recipe created).

Strange behavior also, I sometimes get my home assistant UI reloaded inside the existing UI, so I can have this strange result:
![image](https://user-images.githubusercontent.com/43144578/192218476-8654b26b-7263-4774-88f4-1dad883f96d6.png)
I can reproduce it when I click on my space name in the "tool bar" in the top right.

Regards

**Comment by alexbelgium** [comment]
Indeed, thanks for the feedback. I'll have to look a bit more in the week...

**Comment by alexbelgium** [comment]
Hi, not perfect but it could work

**Comment by RolfKoenders** [comment]
Quickly updated and currently getting: `503: Service Unavailable` is any new configuration needed? Im using the external nabu.casa url at the moment.

**Comment by jeromegoo** [comment]
> 

Same result for me. 

Is it still required to start it at least once on a local device ?

**Comment by alexbelgium** [comment]
Strange... I don't have a nabucasa url. Do you see any 503 error in the logs?

**Comment by alexbelgium** [comment]
or could you please post your log ? thanks

**Comment by jeromegoo** [comment]
Here is my log:

Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Tandoor recipes
 recipe manager
-----------------------------------------------------------
 Add-on version: 1.4.5-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[15:09:32] INFO: Execute /config/tandoor-recipes.sh if existing
[15:09:32] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/32-ingress.sh: executing
/etc/cont-init.d/99-run.sh: executing
ALLOWED_HOSTS=https://*********************.ui.nabu.casa
SECRET_KEY=YOUR_SECRET_KEY
[15:09:33] INFO: Defining database
[15:09:34] INFO: Using a local sqlite database
Creating symlinks
[15:09:34] INFO: Launching nginx
done
[15:09:34] INFO: Launching app
Checking configuration...
Waiting for database to be ready...
Database is ready
Migrating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
Generating static files
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse
1 static file copied to '/opt/recipes/staticfiles', 644 unmodified, 1388 post-processed.
Done
[2022-12-20 15:10:31 +0100] [177] [INFO] Starting gunicorn 20.1.0
[2022-12-20 15:10:31 +0100] [177] [INFO] Listening at: http://0.0.0.0:8080 (177)
[2022-12-20 15:10:31 +0100] [177] [INFO] Using worker: gthread
[2022-12-20 15:10:31 +0100] [183] [INFO] Booting worker with pid: 183
[2022-12-20 15:10:31 +0100] [184] [INFO] Booting worker with pid: 184
[2022-12-20 15:10:31 +0100] [185] [INFO] Booting worker with pid: 185

**Comment by alexbelgium** [comment]
Thanks, I'll delete my version from the test repo and re-add from this one to check if everything went well when I transferred from one repo to the other

**Comment by alexbelgium** [comment]
it works on my system with ip:port ; and domain:port. Only thing I haven't tested yet is a domain with a "normal" port (like 80 or 443) which doesn't appear in the url... I remember once an issue linked to that on an addon

**Comment by alexbelgium** [comment]
Argh for me it even works with a nabu casa url... I'll try to understand if I have something remaining somewhere that could impact

**Comment by RolfKoenders** [comment]
@alexbelgium  I re-saved my config, basically modified the port and put it back to where it was to be able to re-save it and now it works for me!

**Comment by alexbelgium** [comment]
ah, great!!! Sometimes HA is a bit quirky

**Comment by alexbelgium** [comment]
Mmh I can replicate an error 400 with nabu casa url... Argh. Let me know if I should revert to the non-Ingress version, or if I leave it   like this

**Comment by RolfKoenders** [comment]
I was literally about to post that, sorry im doing multiple things at the same time. Initial page load works but doing any other action fails atm. Strange

**Comment by jeromegoo** [comment]
> @alexbelgium I re-saved my config, basically modified the port and put it back to what it was to be able to re-save it and now it works for me!

Do you really have it fully working ? I now have the connexion page, but nothing else works. Can't log in or display another page without errors (404: Not found, or Bad Request (400) ...)

**Comment by RolfKoenders** [comment]
> > @alexbelgium I re-saved my config, basically modified the port and put it back to what it was to be able to re-save it and now it works for me!
> 
> Do you really have it fully working ? I now have the connexion page, but nothing else works. Can't log in or display another page without errors (404: Not found, or Bad Request (400) ...)

I responded to quick i guess, same result here. I didn't immediately try to do any other action then load the initial page.

**Comment by RolfKoenders** [comment]
Using it locally works fine though. The only thing i notice with the current version is that when you click the logo/header it gives me a 404.

**Comment by alexbelgium** [comment]
Thanks, the 404 on logo I've noticed but not the settings saving... Well ingress is really super complex on this app...

Should I remove it?

**Comment by RolfKoenders** [comment]
Hmm, maybe till we can figure out how to solve it? at least its more usable for people that use it.

**Comment by alexbelgium** [comment]
Done, thanks. I'll continue tests on my other repo https://github.com/alexbelgium/hassio-addons-test

**Comment by alexbelgium** [comment]
It works with a port so it is probably a matter of host header...

**Comment by alexbelgium** [comment]
BTW if you want to do tests, I've got a script that execute a custom  script at startup if it is in /config/tandoor-recipes-test.sh (for the test version). It can be used to inject a new ingress.conf file in /etc/nginx/servers. Alternative that I use is portainer

**Comment by RolfKoenders** [comment]
😬

**Comment by kuduacz** [comment]
anyone can tell me how can i reach this page with cloudflare?
i set my domain adress and local adress in configuration, save, restart addon and cant reach mydomain.xx:9928.
`ALLOWED_HOSTS: 192.168.x.x,mydomain.com`

**Comment by jimmyz5150** [comment]
Hey guys,
I have this installed in HA but I need to be able to point Tandoor to look at my QNAP.
All of my recipes are in PDF on QNAP and it's a decent size library.
My problem is that I can't seem to figure out how to import my recipes into Tandoor. I also have them sync via Google drive, but want to use local. Is it a ingress issue HA=>QNAP?
Not sure in HA how to point db to qnap for my recipes. 

I do have Tandoor mostly set up in a container in QNAP. I've tried for a year or so on/off and found a youtube vid ( youtube.com/watch?v=7-nb3muJxI0 ) that mostly works but seems I get a... "ERROR failed to initialize plugins" in log but able to access an http Tandoor via QNAP port in a browser, but can't point to recipes of mine. 
I have tried the External Recipes several different ways but get errors and not really sure how to set up correctly. Manage watched Folders as well but unsure of setting up.
Synology NAS info doesn't seems to help... Docker mostly does. Not the most proficient at it. 

QNAP docker setup
`
version: "3"
services:
  db_recipes:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  recipes:
    image: vabene1111/recipes
    container_name: recipes
    ports:
      - 51:8080
    volumes:
      - /JZvol1/xx/TandoorRecipes/staticfiles:/opt/recipes/staticfiles
      - /JZvol1/xx/TandoorRecipes/mediafiles:/opt/recipes/mediafiles
    environment:
      - SECRET_KEY=xx
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    depends_on:
      - db_recipes
`
Also does _!secrets_ in HA work bc seems to except for port #... BUT it exposes the secrets values instead of showing hidden _!secret_.

HA tandoor below...
`
/etc/cont-init.d/01-custom_script.sh: executing
[18:53:51] INFO: Execute /config/addons_autoscripts/tandoor-recipes.sh if existing
[18:53:51] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/32-ingress.sh: executing
[18:53:51] INFO: Ingress disabled
/etc/cont-init.d/99-run.sh: executing
ALLOWED_HOSTS=xxx
SECRET_KEY=xxxx
[18:53:52] INFO: Defining database
[18:53:52] INFO: Using an external database, please populate all required fields in the addons config
POSTGRES_HOST=192.168.xxx
POSTGRES_PORT=xx
POSTGRES_DB=/JZvol1/xxx
POSTGRES_USER=xxx
POSTGRES_PASSWORD=xxx
Creating symlinks
[18:53:53] INFO: Launching app
Checking configuration...
Waiting for database to be ready...
Database not reachable. Maximum attempts exceeded.
Please check logs above - misconfiguration is very likely.
Make sure the DB container is up and POSTGRES_HOST is set properly.
Shutting down container.
/etc/cont-init.d/99-run.sh: exiting 1`


It would be awesome to get setup in HA, I have wanted this type of self managed PDF db for quite a while. I'd would be glad to help out.
Regards and Cheers
JZ

**Comment by alexbelgium** [comment]
Hi, ingress will not be implemented but it is recommended to use iframe instead. Please check this thread for infos! https://github.com/TandoorRecipes/recipes/issues/354

**Comment by lovelylain** [comment]
https://community.home-assistant.io/t/ingress-access-for-tandoor-recipes/717859

**Comment by RolfKoenders** [comment]
> https://community.home-assistant.io/t/ingress-access-for-tandoor-recipes/717859

This is great! Thanks for the how-to!
