### ISSUE TITLE
🐛 [Epic Games Free] Timeout Exceed on puppeteer

### ISSUE THREAD

**Issue by jaamulberry** [alexbelgium/hassio-addons#485]
**Which addon?**

- Addon name : Epic Games Free
- Addon version : 938a9653ffd08b8284ea32cf01ac8727d25c5d4c

**Describe the bug**

Timeout continually happens. Changing Config makes no difference to issue. Always timeout.

**To Reproduce**

1. Start add-on to generate config file
2. Updated config values
3. Start addon. 
4. Wait for log to timeout
5. No notifications sent either.

**Full addon log**

Add-on: Epic Games Free
Automatically login and redeem promotional free games from the Epic Games Store
-
Add-on version: 938a9653ffd08b8284ea32cf01ac8727d25c5d4c
You are running the latest version of this add-on.
System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
Home Assistant Core: 2022.9.5
Home Assistant Supervisor: 2022.09.1
-
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/99-run.sh: executing
[10:04:55] INFO: The following json files were found in /config/addons_config/epicgamesfree and will be used in the app. Changing those files will require to restart the addon.
... processing config.json
 
[10:04:55] INFO: Starting the app
 
> epicgames-freegames-node@4.1.0 entrypoint-config
> node dist/src/entrypoint-config.js
npm notice 
npm notice New minor version of npm available! 8.15.0 -> 8.19.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice 
Setting timezone: America/New_York
Run on startup: true
[2022-09-20 10:05:01.906 -0400] INFO: Started epicgames-freegames-node
    COMMIT_SHA: "938a9653ffd08b8284ea32cf01ac8727d25c5d4c"
    BRANCH: "master"
    DISTRO: "alpine"
[2022-09-20 10:05:02.276 -0400] INFO: Checking free games for jaamulberry@gmail.com 
    user: "jaamulberry@gmail.com"
[2022-09-20 10:05:37.682 -0400] ERROR: Encountered an error during browser automation. Saved a screenshot for debugging purposes.
    user: "jaamulberry@gmail.com"
    errorFile: "error-2022-09-20T14:05:33.461Z.png"
[2022-09-20 10:05:37.695 -0400] ERROR: Navigation timeout of 30000 ms exceeded
    user: "jaamulberry@gmail.com"
    err: {
      "type": "TimeoutError",
      "message": "Navigation timeout of 30000 ms exceeded",
      "stack":
          TimeoutError: Navigation timeout of 30000 ms exceeded
              at /usr/app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:211:18
      "name": "TimeoutError"
    }
[2022-09-20 10:05:37.750 -0400] WARN: Current version
    COMMIT_SHA: "938a9653ffd08b8284ea32cf01ac8727d25c5d4c"
    BRANCH: "master"
    DISTRO: "alpine"
Run once: false
Setting cron schedule as 5 16 * * *

**Full addon config**
{
   "runOnStartup":true,
   "cronSchedule":"5 16 * * *",
   "logLevel":"info",
   "webPortalConfig":{
      "baseUrl":"http://localhost:3000"
   },
   "accounts":[
      {
         "email":"fake@gmail.com",
         "password":"NotReal",
         "totp": "IMadeItUp"
      }
   ],
   "notifiers":[
      {
         "type":"telegram",
         "token":"5679931307:AAGufZ81gg0NQQGVTI3TVSMldvNuljjq9CQ",
         "chatId":"-549362502"
      },
      {
         "type":"discord",
         "webhookUrl":"https://discord.com/api/webhooks/1021608366616871013/Fake",
         "mentionedUsers":[         ]
      }
   ]
}

**System**

- Supervisor version:  2022.09.1 
- Host system version: 2022.9.5

**Comment by nkm8** [comment]
Related: https://github.com/claabs/epicgames-freegames-node/issues/233

Adding `"browserNavigationTimeout": 120000,` to my `config.json` file resolved this issue for me. I am using an 8GB pi4.

**Comment by jaamulberry** [comment]
@nkm8 Exactly what I needed. Thanks!
