### ISSUE TITLE
How to configure https on for the HA ZoneMinder docker image

### ISSUE THREAD

**Issue by GregoryMachin** [alexbelgium/hassio-addons#486]
**ZoneMinder**

name: How to configure HTTPS 
about: 
title: ''
labels: ''
assignees: ''

Hi.
I'm looking for some clear direction on how to configure hassio ZoneMinder addon to use https and no http. I cant see where to configure this in HA or in ZoneMinder.  

And can it be configured to work on port 8123 along with HA ?

Thank you.

**Comment by alexbelgium** [comment]
Hello, this is currently not supported by the addon. The easiest (and recommended way) is to install the nginx reverse proxy addon from the official (or community) HA addon store, and create a link between your HA installation and the app
