### ISSUE TITLE
Can log in without credentials

### ISSUE THREAD

**Issue by tonysprenk** [alexbelgium/hassio-addons#49]
I just noticed that when you don’t put any credentials in the login fields and select login it just logs you in. This is problematic when you have port 8080 forwarded so you can access the website from outside the local network as that way anyone with your public ip can log in to the webui. Is this an issue with this addon or with QBitTorrent itself?

**Comment by alexbelgium** [comment]
Hi, actually it is feature : you can select the whitelisted ip in the addon options. Remove your local ip and it should ask you for a password!

**Comment by tonysprenk** [comment]
Yes you’re right. Unrelated question: I can’t seem to get the torrent search feature to work, do I need to activate it somewhere?

**Comment by alexbelgium** [comment]
Mmh I had managed to make it work. I think we need to add search engines according to this : https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Comment by tonysprenk** [comment]
Yes I tried but I can’t find the option in the vue webui. I tried changing the ui in the addon config but whatever I set it to it keeps opening in the vue UI.

**Comment by alexbelgium** [comment]
Actually, changing the ui only works when accessing from a direct url. With ingress, only VueTorrent is possible

**Comment by alexbelgium** [comment]
It works on my system in VueTorrent... At the bottom of the screen I click on plugin manager, I enable the search engines, then search for something and it works.

**Comment by alexbelgium** [comment]
You need to click on three little dots at top right in VueTorrent, then click o' the magnifying glass
