### ISSUE TITLE
🐛 [omada] SSL certificate not loading

### ISSUE THREAD

**Issue by r15ch13** [alexbelgium/hassio-addons#490]
**Which addon?**

- Addon name : omada
- Addon version : 5.5 (current)

**Describe the bug**

- [`entrypoint.sh`](https://github.com/mbentley/docker-omada-controller/blob/d64321df26e96444465b609e3be3654393d00fb5/entrypoint-5.x.sh#L172) requires that the certificate is located in `/cert` instead of `/ssl`. The mount point for the volumes should be changed to `/cert`
- `SSL_CERT_NAME` should be set to `fullchain.pem`
- `SSL_KEY_NAME` should be set to `privkey.pem`

I modified the container to mount the `ssl`-directory to `/cert` and changed the environment variables for testing.

**Comment by alexbelgium** [comment]
Hi, I've adapted it, you just must be sure that the ssl certificates are accessible to your user 508:508,for example with permissions 700

**Comment by r15ch13** [comment]
Hm, instead of changing the permission for the private key, wouldn't it be better to copy to `/cert` on startup? The webserver has to be restarted anyway if the cert gets renewed.

Also there are two volumes in the base image that have to get mapped, because restarting the containers creates unused directories in `/mnt/data/docker/volumes`

`/opt/tplink/EAPController/data` and `/opt/tplink/EAPController/logs` (See: [Dockerfile.v5.x#L25](https://github.com/mbentley/docker-omada-controller/blob/d64321df26e96444465b609e3be3654393d00fb5/Dockerfile.v5.x#L25))

**Comment by alexbelgium** [comment]
Hi, volumes can't be mapped with HA, which is why I'm using symlinks to extract folders from those two mapped areas. Normally `/mnt/data/docker/volumes` stays within the container and therefore it's folders are removed at restart. Only folders such as /config, /data, /share are remanent.

OK for the /cert, actually it is an easier way to do it, I'll adapt the code

**Comment by r15ch13** [comment]
`/cert` works fine now, thanks :smile:

To bad that there is no way to remove volumes from images.


Here is how the running container looks like in Portainer:
![image](https://user-images.githubusercontent.com/432127/192869962-bca5a720-63a7-4506-8f4a-b983bce4e3fe.png)

That's the list of unused volumes after a restart of the addon (after the restart `450b...` and `a24e...` are now unused):
![image](https://user-images.githubusercontent.com/432127/192870278-6fad38db-3847-40b9-a8cc-e825219bb315.png)


Each volume contains just the logs and the symlinks, but it will eventually require cleanup.

Maybe building the base image without the volume would be a solution, but I don't know if it works with your CI configuration. :smile:
