### ISSUE TITLE
✨ [REQUEST] Sonarr Ingress

### ISSUE THREAD

**Issue by MiguelAngelLV** [alexbelgium/hassio-addons#495]
**Which addon?** Sonarr

**Is your feature request related to a problem? Please describe.** Access from outside

\*\*If a new addon, have you checked on Google that such as addon doesn't already exists?

**Describe the solution you'd like**

Sonarr allow configure URL base, so, could be work with Ingress

**Comment by nstrelow** [comment]
What is required to enable ingress?
I have experience with docker from some time but never enabled ingress.

Is there anything that might be blocking or more tricky to enable it on sonarr?

**Comment by MiguelAngelLV** [comment]
For enable ingress, only add this in config file

```
  "ingress": true,
  "ingress_port": port of sonarr,
  "ingress_entry":"relative url of sonarr",

```

Por sonarr, you need add relative url to works fine.

**Comment by nstrelow** [comment]
I don't see "ingress_entry" in the config file, but I see ingress related scripts in overlay for other addons

[rootfs/etc/cont-init.d/32-nginx_ingress.sh](https://github.com/alexbelgium/hassio-addons/blob/6a5d8b0f21bbf9bc5f0cb309b09afd7f49539a52/photoprism/rootfs/etc/cont-init.d/32-nginx_ingress.sh)

**Comment by alexbelgium** [comment]
Indeed ; actually I need to implement an nginx proxy (as in the photoprism example) and create nginx redirects. Often, apps don't support relative urls that are required for ingress. Therefore it is not necessarily as easy as that

**Comment by alexbelgium** [comment]
Should be good now, I've pushed a version with it !

**Comment by nstrelow** [comment]
WOW, thanks a lot @alexbelgium, really appreciate it, saw me a lot of hours trying to figure it out ^^.

Just fyi, I am running sonarr v4 beta currently (forking your repo). Is there any way to allow beta versions of addons? So people can choose? (kinda off topic for this bug, sorry)

**Comment by alexbelgium** [comment]
There was some issues but I've pushed a new version that will solve it!

**Comment by alexbelgium** [comment]
There is no option to allow stable or beta. But I could switch the whole repo to beta. Did you do something special to make the beta work or just changed the build.json?

**Comment by kulmegil** [comment]
FYI: This works great for me so far.

**Comment by alexbelgium** [comment]
Thanks then I'll leave it to v3 until v4 is stable

**Comment by nstrelow** [comment]
I might have found a problem with Ingress and probably the nginx setup.

Somehow Sonarr cannot communicate with my Prowlarr/Indexer, I get 503 Service Unavailable errors when using Ingress, but not when accessing directly.

Might be because it's accessing something in the local network and/or Prowlarr doens't have Ingress?
I can provide logs and debug a bit when I have time.

**Comment by alexbelgium** [comment]
If you could include the logs it would be great indeed. I don't use those addons so can't troubleshoot further than just it starting. There is a high risk that it communicates its baseurl and that Prowlarr tries to connect to homeassistant_ip:port/sonarr ; and the only solution here would be for me to modify the base url to the full ingress one (so homeassistant_ip:port/api/hassio/XXXXX/sonarr). I had avoided that as it is not very user friendly but might be the only way to go
