### ISSUE TITLE
Texhnitium DNS

### ISSUE THREAD

**Issue by ChristoffBo** [alexbelgium/hassio-addons#496]
Hi,

Could you create an addon for Technitium DNS I do see they have an official docker image. I tried to create one but can't get it working? I'm a bit of a noob and don't want. To. Run it in. Portaner

**Comment by alexbelgium** [comment]
Hi, Thanks for your interest in my addons. Usually I avoid creating a new addon when something similar already exists, and it seems to me adguard home already fulfils the need for a DNS based adguard. This is why it is preferable to use the Request templates : it sets labels and prevents it being closed as stale, and ensure that such questions are pre-checked. Hope you enjoy the repo! Have a nice day

**Comment by ChristoffBo** [comment]
Hi, thanks for the reply. Awesome Repo.
