### ISSUE TITLE
nextcloud compatibility

### ISSUE THREAD

**Issue by pazz** [alexbelgium/hassio-addons#50]
Is it (easily) possible to change your image so that it picks up the "let's encrypt" certs generated by the HA addon by the same name? (This requires only to change the nginx config to point to /ssl/*pem).

Secondly, could you add a config option to use a DB other than the basic sqlite?
This would require chaning the nextcloud config.php appropriately.

I have been able to do both the above, but of course this is not persistent and once you push a new image I'd have to locally make changes again.
Many thanks for the good work!

**Comment by alexbelgium** [comment]
Hello ! I'll look at the ssl part, it should be easy.

For config, normally when you initialize the addon it asks you what database you want. Either you can connect to an external database that is provided by an addon such as mariadb, or indeed you can choose to use sqlite. Normally,both should work fine. Could you please test ? For example, you could backup your nextcloud addon, uninstall it, reinstall and you should at first boot be able to select the option to connect to an external database

**Comment by alexbelgium** [comment]
Hi, I pushed a new version. You need to activate the option "use_own_certs". Could you please test if it works? Thanks

**Comment by pazz** [comment]
I'm having some issues with the nextcloud container seemingly running (according to the portainer app) but also having crashed with exit code 255.
I'm sure this is due to my malconfiguration though. I will have to look up how to remove the "running" container.

In the meantime let me ask you a noob question: what happens to my config if you push a new image? Specifically the database config that isn't exposed to the hassio addon config.

- Firstly, how do I manually trigger repulling of an updated image?
- Then, is there a way to update without having to set up nextcloud again in its web interface? 

I suspect that this is possible but would require me to set it up, then connect to an existing external DB, which then pulls in the old config? Wouldn't it be be easier to generate the db config from the addon config?

While I'm misusing this issue for unrelated things: I noticed that the ocr part did not work even if configured in the addon config. The ocr plugin in nextcloud complains that the nc version is incompatible. But that's obviously unrelated and not important for me atm.

Cheers,
P

Quoting Alexandre (2021-09-21 20:36:25)

**Comment by pazz** [comment]
Just a heads up:
A reboot has fixed my docker issue and apparantly it pulled a new version of your image:
The ssl options now appear and it seems like this is being picked up (although magically my old config is still intact, so that may be due to my changes on the image).

**Comment by alexbelgium** [comment]
Hi, actually the config is mapped to /share/nextcloud, which is a persistent Volume (external from the image). Config is therefore always kept from restarts to restarts, and updates to updates. Glad it works! Do you confirm that it is indeed the right ssl certificates that are use?

**Comment by alexbelgium** [comment]
When you install the addon, HA compiles an images based on the addon in my repo. Then, each time you start it, it creates a new container. To allow remanence, some folders are mapped to external volumes to,allow them to be kept outside,of the containers. This is the case by default for /data, and I've configured it for this addon for /ssl and /share/nextcloud. Hope this helps

**Comment by alexbelgium** [comment]
For the ocr I would need more info (including logs) to investigate... I don't myself use it. It could depend on the addon used also

**Comment by pazz** [comment]
Thank you, that indeed explains what I'm seeing!

So what do I do if I want to do a "factory reset" of your addon? Is it safe to remove all nextcloud directories then hit "rebuild"?
P


Quoting Alexandre (2021-09-22 17:35:39)

**Comment by alexbelgium** [comment]
Hi, rebuild is the same as updating the addon : it simply compiles the image based on the github repo. To "factory reset" you can simply delete the /share/nextcloud folders, uninstall the addon (removes /data), and reinstall it.

**Comment by pazz** [comment]
Will this also cause the external database to be re-populated?
Otherwise I'd have to remove the nextcloud related tables there somehow correct?

Quoting Alexandre (2021-09-22 17:42:51)

**Comment by alexbelgium** [comment]
If you used sqlite it should have been stored as a standalone file in the /share /nextcloud folder. If you have used an external dB, either you need to drop the tables, or change the database name to avoid it completely. Normally, this should work...

**Comment by pazz** [comment]
gotit. Many thanks for your explanations.

#close

Quoting Alexandre (2021-09-22 18:14:33)

**Comment by alexbelgium** [comment]
My pleasure! Don't hesitate if you need any other infos, or if anything in the addon is not working as expected
