### ISSUE TITLE
how to get started with jellyfin

### ISSUE THREAD

**Issue by itsboo07** [alexbelgium/hassio-addons#503]
Hi how do i  get started with jellyfin addon and what all does it support? i cant find much of detailed explanation or documentation for this addon.

**Comment by alexbelgium** [comment]
Hi, it's actually an addon providing this image : https://github.com/linuxserver/docker-jellyfin

So if you run it, you can have a jellyfin server on your HA

**Comment by itsboo07** [comment]
thanks mate...
