### ISSUE TITLE
[Calibre] 502 Bad Gateway

### ISSUE THREAD

**Issue by LoganJFisher** [alexbelgium/hassio-addons#506]
I've installed the Calibre addon, and when I start it and click "OPEN WEB UI", I'm greeted with the error message "502 Bad Gateway".

Below is a copy of my log:
```
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-data_location.sh
[13:21:23] INFO: Setting data location to /config/addons_config/calibre
usermod: no changes
Creating /config/addons_config/calibre
[13:21:23] INFO: Setting ownership to 0:0
cont-init: info: /etc/cont-init.d/00-data_location.sh exited 0
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/13-keygen
Generating 2048 bit rsa key...
ssl_gen_key_xrdp1 ok
saving to rsakeys.ini
Generating a RSA private key
..+++++
........................+++++
writing new private key to '/etc/xrdp/key.pem'
-----
cont-init: info: /etc/cont-init.d/13-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/30-config
chsh: Shell not changed.
Changing shell for abc.
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/32-nginx.sh
cont-init: info: /etc/cont-init.d/32-nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/50-armless
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *        This Calibre image no longers supports        *
    *    32 bit ARM due to a lack of upstream packages     *
    *   The last armhf tag will be arch-version-79d7ec5e   *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
cont-init: info: /etc/cont-init.d/50-armless exited 0
cont-init: info: running /etc/cont-init.d/50-gid-video
**** permissions for /dev/dri/card1 are good ****
**** permissions for /dev/dri/renderD128 are good ****
**** permissions for /dev/dri/card0 are good ****
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/55-autostart-config
cont-init: info: /etc/cont-init.d/55-autostart-config exited 0
cont-init: info: running /etc/cont-init.d/80-configuration.sh
cont-init: info: /etc/cont-init.d/80-configuration.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun autostart (no readiness notification)
services-up: info: copying legacy longrun guacd (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun web (no readiness notification)
services-up: info: copying legacy longrun xrdp (no readiness notification)
services-up: info: copying legacy longrun xrdp-sesman (no readiness notification)
```

I'm not sure what to do. I do see the notice regarding 32 bit ARM, but HA doesn't give an incompatibility notice, so I'm not entirely certain if this is necessarily a dead-end.

**Comment by alexbelgium** [comment]
Hi, are you on armv7? Indeed it's discontinued... From linuxserver [github] (https://github.com/linuxserver/docker-calibre/releases) "Deprecate Arch armhf image due to dropping of upstream support"

**Comment by LoganJFisher** [comment]
I'm using an RPi 4B, which I believe has a Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz

**Comment by alexbelgium** [comment]
Hi, indeed armv8 cpu but it depends if you installed the 32 or 64 bit os... I don't myself get the warning so I suppose you have 32 bits? However there indeed is a change upstream that prevents the addon from working for the moment, I'll have to fix this

**Comment by LoganJFisher** [comment]
Hmm... I ran three commands in my terminal:

```
cat /etc/os-release
```
This returned that I'm running Alpine Linux v3.16

```
cat /proc/cpuinfo
```
This returned that the model name of my CPU is "ARMv7 Processor rev 3 (v71)". Not sure why that is though because the specs online definitely show the RPi 4B as being ARMv8, and I'm certain that's the model I have (4GB model to be exact).

```
getconf LONG_BIT
```
This returned "32".

**Comment by LoganJFisher** [comment]
> However there indeed is a change upstream that prevents the addon from working for the moment, I'll have to fix this

Do you mean that you'll look into fixing this so I can run this addon on 32-bit systems? I want to make sure I'm understanding correctly.

**Comment by alexbelgium** [comment]
Sorry, 32 bit is discontinued upstream so I'll remove it... But I highly recommend you to switch to a 64 bit system, you'll have much broader addon compatibility. Much apps are now dropping  armv7 support. To do that, you need to do a full backup, wipe your HA os, and fully restore... I did it some time ago and it actually worked quite well. Of course, all addons had to be reinstalled to remove the 32 bit versions and install the 64 but version...

What I meant is that there was an upstream change 6 days ago in the linuxserver container that broke my code compatibility, its a code being developed in all linuxserver images one by one. I'll have to fix that for the 64bit addon to also work

**Comment by LoganJFisher** [comment]
Ah, I see. I guess that'll be a project for me to do when I have a fair bit of spare time to do this and sort out the inevitable resulting issues. Serves me right for choosing a 32-bit OS when I should have chosen a 64-bit one from the start.

**Comment by alexbelgium** [comment]
Actually some time ago it was recommended to use 32 bits for rpi 4... But now a switch to 64 bits could be preferable at longer term for you when you'll have time to do so...

**Comment by alexbelgium** [comment]
Hi if OK with you I'll keep it open to remind myself the is also a bug with the armv8 version

**Comment by alexbelgium** [comment]
It's now fixed for armv8 :) just to test I'll push an armv7 to check

**Comment by LoganJFisher** [comment]
Just to be clear, still no good for 32-Bit though, right?

**Comment by alexbelgium** [comment]
Not sure, as I've solved it on 64 bits I'll still push a 32 but version. It's building, please let me know if it launches!

**Comment by LoganJFisher** [comment]
Still a 502: Bad Gateway

So I guess it's still 64-bit only.

Thanks for fixing the ARMv8 compatibility. At least now it's something resolvable on my end by upgrading to a 64-bit OS when I have time.

**Comment by alexbelgium** [comment]
Could you please post your full on g out of curiosity? But indeed seeing all apps that are removing 32 bit support I recommend it to,you

**Comment by LoganJFisher** [comment]
```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
 Add-on: Calibre
 e-book manager
-----------------------------------------------------------
 Add-on version: 6.1.1
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.10.1
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-data_location.sh
[15:46:59] INFO: Setting data location to /config/addons_config/calibre
sed: couldn't edit /etc/s6-overlay/s6-rc.d/99-ci-service-check/dependencies.d: not a regular file
sed: can't read /etc/services.d/web/run: No such file or directory
sed: can't read /etc/services.d/web/run: No such file or directory
usermod: no changes
Creating /config/addons_config/calibre
[15:46:59] INFO: Setting ownership to 0:0
cont-init: info: /etc/cont-init.d/00-data_location.sh exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/32-nginx.sh
cont-init: info: /etc/cont-init.d/32-nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/80-configuration.sh
cont-init: info: /etc/cont-init.d/80-configuration.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
Generating 2048 bit rsa key...
ssl_gen_key_xrdp1 ok
saving to rsakeys.ini
....+......+...+..+...+.+.....+......+....+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+...+.+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+......+......+.....+.+............+..+.+.....+...+......+......+...+....+..+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.........+.+...+........+...+....+.....+.+......+...+......+..+.......+........+...+.......+..+.+............+...+.....+......+...+.............+.....+.......+......+...........+.....................+.......+............+........+...+...+.+...+...+.....+....+...+......+.....+........................+.+.....+.......+..+.+..+.........+...+.+......+.....+...+......+.......+.....+...+............+.............+......+.........+..+.......+...........+....+..+.+..+.+.....+......+....+.....+.........+...+.........+.............+...+.....+.........+.........+....+......+......+...+..+.+........+.......+..+...+....+...+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
**** permissions for /dev/dri/card1 are good ****
**** permissions for /dev/dri/renderD128 are good ****
**** permissions for /dev/dri/card0 are good ****
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *        This Calibre image no longers supports        *
    *    32 bit ARM due to a lack of upstream packages     *
    *   The last armhf tag will be arch-version-79d7ec5e   *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
[custom-init] No custom files found, skipping...
[ls.io-init] done.
services-up: info: copying legacy longrun nginx (no readiness notification)
```

**Comment by alexbelgium** [comment]
Indeed, it's really the discontinuation. I've tagged the version mentioned for armv7, perhaps it will work in the new version I've pushed

**Comment by alexbelgium** [comment]
I've tagged the latest arm version that should work referenced in the log

**Comment by FancyNerd92** [comment]
Same problem on 502 Bad Gateway....
I did all the steps but nothing....

`Unpacking libxshmfence1:amd64 (1.3-1) ...
Selecting previously unselected package libegl-mesa0:amd64.
Preparing to unpack .../20-libegl-mesa0_21.2.6-0ubuntu0.1~20.04.2_amd64.deb ...
Unpacking libegl-mesa0:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Selecting previously unselected package libllvm12:amd64.
Preparing to unpack .../21-libllvm12_1%3a12.0.0-3ubuntu1~20.04.5_amd64.deb ...
Unpacking libllvm12:amd64 (1:12.0.0-3ubuntu1~20.04.5) ...
Selecting previously unselected package libsensors-config.
Preparing to unpack .../22-libsensors-config_1%3a3.6.0-2ubuntu1.1_all.deb ...
Unpacking libsensors-config (1:3.6.0-2ubuntu1.1) ...
Selecting previously unselected package libsensors5:amd64.
Preparing to unpack .../23-libsensors5_1%3a3.6.0-2ubuntu1.1_amd64.deb ...
Unpacking libsensors5:amd64 (1:3.6.0-2ubuntu1.1) ...
Selecting previously unselected package libvulkan1:amd64.
Preparing to unpack .../24-libvulkan1_1.2.131.2-1_amd64.deb ...
Unpacking libvulkan1:amd64 (1.2.131.2-1) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../25-libgl1-mesa-dri_21.2.6-0ubuntu0.1~20.04.2_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Selecting previously unselected package libglvnd0:amd64.
Preparing to unpack .../26-libglvnd0_1.3.2-1~ubuntu0.20.04.2_amd64.deb ...
Unpacking libglvnd0:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../27-libxcb-glx0_1.14-2_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.14-2) ...
Selecting previously unselected package libxfixes3:amd64.
Preparing to unpack .../28-libxfixes3_1%3a5.0.3-2_amd64.deb ...
Unpacking libxfixes3:amd64 (1:5.0.3-2) ...
Selecting previously unselected package libxxf86vm1:amd64.
Preparing to unpack .../29-libxxf86vm1_1%3a1.1.4-1build1_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1build1) ...
Selecting previously unselected package libglx-mesa0:amd64.
Preparing to unpack .../30-libglx-mesa0_21.2.6-0ubuntu0.1~20.04.2_amd64.deb ...
Unpacking libglx-mesa0:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Selecting previously unselected package libglx0:amd64.
Preparing to unpack .../31-libglx0_1.3.2-1~ubuntu0.20.04.2_amd64.deb ...
Unpacking libglx0:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Selecting previously unselected package libgl1:amd64.
Preparing to unpack .../32-libgl1_1.3.2-1~ubuntu0.20.04.2_amd64.deb ...
Unpacking libgl1:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../33-libgl1-mesa-glx_21.2.6-0ubuntu0.1~20.04.2_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Selecting previously unselected package libxdamage1:amd64.
Preparing to unpack .../34-libxdamage1_1%3a1.1.5-2_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.5-2) ...
Selecting previously unselected package libxkbcommon0:amd64.
Preparing to unpack .../35-libxkbcommon0_0.10.0-1_amd64.deb ...
Unpacking libxkbcommon0:amd64 (0.10.0-1) ...
Selecting previously unselected package libegl1:amd64.
Preparing to unpack .../36-libegl1_1.3.2-1~ubuntu0.20.04.2_amd64.deb ...
Unpacking libegl1:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Selecting previously unselected package libopengl0:amd64.
Preparing to unpack .../37-libopengl0_1.3.2-1~ubuntu0.20.04.2_amd64.deb ...
Unpacking libopengl0:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Setting up libxcb-dri3-0:amd64 (1.14-2) ...
Setting up libwayland-server0:amd64 (1.18.0-1ubuntu0.1) ...
Setting up libx11-xcb1:amd64 (2:1.6.9-2ubuntu1.2) ...
Setting up libpciaccess0:amd64 (0.16-0ubuntu1) ...
Setting up libxdamage1:amd64 (1:1.1.5-2) ...
Setting up libxcb-xfixes0:amd64 (1.14-2) ...
Setting up libglvnd0:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Setting up libxcb-glx0:amd64 (1.14-2) ...
Setting up libedit2:amd64 (3.1-20191231-1) ...
Setting up libsensors-config (1:3.6.0-2ubuntu1.1) ...
Setting up xkb-data (2.29-2) ...
Setting up libopengl0:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1build1) ...
Setting up libxcb-present0:amd64 (1.14-2) ...
Setting up libxfixes3:amd64 (1:5.0.3-2) ...
Setting up libxcb-sync1:amd64 (1.14-2) ...
Setting up libllvm12:amd64 (1:12.0.0-3ubuntu1~20.04.5) ...
Setting up libsensors5:amd64 (1:3.6.0-2ubuntu1.1) ...
Setting up libglapi-mesa:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libvulkan1:amd64 (1.2.131.2-1) ...
Setting up libxcb-dri2-0:amd64 (1.14-2) ...
Setting up libxshmfence1:amd64 (1.3-1) ...
Setting up libdrm-common (2.4.107-8ubuntu1~20.04.2) ...
Setting up libxkbcommon0:amd64 (0.10.0-1) ...
Setting up libwayland-client0:amd64 (1.18.0-1ubuntu0.1) ...
Setting up libdrm2:amd64 (2.4.107-8ubuntu1~20.04.2) ...
Setting up libdrm-amdgpu1:amd64 (2.4.107-8ubuntu1~20.04.2) ...
Setting up libdrm-nouveau2:amd64 (2.4.107-8ubuntu1~20.04.2) ...
Setting up libgbm1:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libdrm-radeon1:amd64 (2.4.107-8ubuntu1~20.04.2) ...
Setting up libdrm-intel1:amd64 (2.4.107-8ubuntu1~20.04.2) ...
Setting up libgl1-mesa-dri:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libegl-mesa0:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libegl1:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Setting up libglx-mesa0:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libglx0:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Setting up libgl1:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
Setting up libgl1-mesa-glx:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mod-universal-calibre-setup: starting
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`

**Comment by alexbelgium** [comment]
Hi, your log ends right through the calibre being dowloaded. Perhaps you need to wait for this step to conclude

**Comment by FancyNerd92** [comment]
Yes you're right! But i have and 200mbps line and lan connection on my device and it take 10 min. 😅 I didn't thought... Thanks.

**Comment by blackshoals** [comment]
Getting the 502 Bad Gateway message on both the local IP and external port forward addresses under  the addon version v6.15.0-ls211. Previously working OK. Raspberry Pi 4B running Home Assistant 2023.4.1. The Calibre addon log is repeating:

mkdir: cannot create directory ‘/sys/fs/cgroup/init’: Read-only file system
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
mkdir: cannot create directory ‘/sys/fs/cgroup/init’: Read-only file system
