### ISSUE TITLE
[zoneminder] How do I use MariaDB addon instead of internal DB?

### ISSUE THREAD

**Issue by ddokupil** [alexbelgium/hassio-addons#508]
Hi,
I'm experiencing an issue with internal MySQL server ever since I installed an 8TB drive to store my recording. After some time MySQL database just stops working and zoneminder crashes with 

` * Warning: Mysql startup timer expired!
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

This is not an issue with this addon since I had exactly the same problem with my previous docker setup as well.
I wanted to give a chance to MariaDB addon but I can't find a place to set it up. I only found [this](https://github.com/alexbelgium/hassio-addons/blob/a22dde1979c3e555b5616f4367a4210216316de0/zoneminder/rootfs/etc/cont-init.d/99-run.sh#L21) case statement.
Where do I configure `DB_CONNECTION` to use `mariadb_addon)` instead of `*)`?

**Comment by alexbelgium** [comment]
Hi, indeed I had disabled this option... Not sure why though :) I'll push a new version today that restores this option, please let me know how that goes!

**Comment by alexbelgium** [comment]
An alternative is to frequently reboot the addon with an automation to avoid this

**Comment by ddokupil** [comment]
Hi, I just noticed a new version with DB_CONNECTION variable enabled. Thanks for that. Sadly it didn't go flawless. Looks like addon properly detects Maria but later on, zoneminder tries to use its own settings:

'/etc/cont-init.d/99-run.sh: executing
[08:40:37] INFO: Defining database
[08:40:37] INFO: Using MariaDB addon. Requirements : running MariaDB addon. Detecting values...
ZM_DB_HOST=core-mariadb
ZM_DB_PORT=3306
ZM_DB_NAME=firefly
ZM_DB_USER=service
ZM_DB_PASS=Sahth7ho7Viwei5Eeb7Airiquei5cepouyee0eisai0ohnooRoc5ua9lohr4eoWu
[08:40:37] WARNING: Firefly-iii is using the Maria DB addon
[08:40:37] WARNING: Please ensure this is included in your backups
[08:40:37] WARNING: Uninstalling the MariaDB addon will remove any data
[08:40:37] INFO: Creating database for Firefly-iii if required
mysql: [Warning] Using a password on the command line interface can be insecure.
[08:40:37] INFO: Please wait while the app is loading !
 * Remote database credentials detected. Continuing...
 * Looking for remote database server   ...found.
 * Looking for existing remote database   ...found.
 * Starting Apache http web server service   ...done.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.'

Anyway, thanks for that. I will try to play around with that this evening. Will try to remove the addon completely and install it once again from scratch, or add some code to edit zm settings directly.

**Comment by alexbelgium** [comment]
Mmh I think that's why I had removed the variable...

**Comment by alexbelgium** [comment]
Mmh its probably the `case` code that doesn't pass the variables to zoneminder we would have to check the code structure

**Comment by ddokupil** [comment]
Hard to tell. Looks like configuration files are set propertly. I wonder why is zmupdate.pl called twice here? 
https://github.com/ZoneMinder/zmdockerfiles/blob/2a76b686f963e11f14731a187478ba5f6bb1e598/utils/entrypoint.sh#L347

I would fork all the repos and build everything myself with first call disabled, or with database variables passed, but first I guess I will try to extend event leght and set automation to reboot every once in a while. If that doesn't help I will get back to that MariaDB option. I guess you should disable it as it was before not to confuse people. Thanks for your help nayway.
