### ISSUE TITLE
🐛 [Qbittorrent] Retain old image

### ISSUE THREAD

**Issue by tyjtyj** [alexbelgium/hassio-addons#509]
**Which addon?**

- Addon name : qbittorrent
- Addon version : does not matter

**Describe the bug**
I wasn't sure it just me or everyone. Only this addons is not deleting the old image over time.. 

docker image ls | grep qbi
db21ed7f/amd64-addon-qbittorrent                  4.4.5-r0-ls219                                        8f6a23fd78fe   5 days ago      286MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.5-r0-ls219                                  da66b6142804   6 days ago      208MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.5-r0-ls218                                  7d4bfebd34bf   13 days ago     208MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.5-r0-ls217                                  318e8904eff1   2 weeks ago     208MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.5-r0-ls215                                  53c0e1eb27e2   3 weeks ago     208MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.5-r0-ls214                                  59732be550b8   4 weeks ago     209MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.5-r0-ls213                                  5b3a16024ea7   5 weeks ago     210MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.3.1-r1-ls211                                b048afe5c6c1   5 weeks ago     219MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.3.1-r1-ls210                                ca9891fe34ae   8 weeks ago     219MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.3.1-r1-ls209                                3920172c68fe   2 months ago    219MB
lscr.io/linuxserver/qbittorrent                   amd64-4.4.3.1-r1-ls208                                e5842e4a9690   2 months ago    219MB

docker prune does not remove it.. 
I need to manually remove each. 

@alexbelgium, please close it if this is due to home assistant supervisor design.. I remember this was discussed before, i wasn't sure if this has changed. 

**To Reproduce**

**Full addon log**

**Full addon config**

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hi, still due to [this bug](https://github.com/home-assistant/supervisor/issues/3414) that prevents me from moving from local build to remote build

**Comment by alexbelgium** [comment]
If I remember `docker prune -a` worked, not sure why

Or `ha su repair` perhaps

**Comment by tyjtyj** [comment]
`docker prune -a ` will delete all the container not running.. this includes Let's Encrypt which always stopped. 

I will check what ha su repair.. .

Closing this.

**Comment by tyjtyj** [comment]
I will start with ha su repair next time. 

![image](https://user-images.githubusercontent.com/5368474/194779898-f65ce57d-c939-4d45-b49f-ed100b4cd6bc.png)

**Comment by alexbelgium** [comment]
Actually I think they both are the same given this screenshot

![Screenshot_20221009_234212](https://user-images.githubusercontent.com/44178713/194780871-0845d3fa-c130-4e9c-bc64-6cf693169a7b.jpg)
