### ISSUE TITLE
nextcloud OCR

### ISSUE THREAD

**Issue by pazz** [alexbelgium/hassio-addons#51]
I have the ocr option enabled and the log lists the following error:

```
ERROR: unable to select packages:
  leptonica-1.81.1-r0:
    masked in: @community
    satisfies: tesseract-ocr-4.1.1-r5[so:liblept.so.5]
  tesseract-ocr-4.1.1-r5:
    masked in: @community
    satisfies: world[tesseract-ocr]
[cont-init.d] 51-ocr: exited 2.
```

**Comment by alexbelgium** [comment]
Thanks, I'll look at it

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version, ocr should be fixed /

**Comment by pazz** [comment]
All good now, thanks!

```
11:02:30] INFO: Installing OCR
fetch https://dl-3.alpinelinux.org/alpine/latest-stable/main/aarch64/APKINDEX.tar.gz
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/aarch64/APKINDEX.tar.gz
fetch https://dl-3.alpinelinux.org/alpine/latest-stable/community/aarch64/APKINDEX.tar.gz
(1/3) Installing giflib (5.2.1-r0)
(2/3) Installing leptonica@community (1.81.1-r0)
(3/3) Installing tesseract-ocr@community (4.1.1-r5)
Executing busybox-1.33.1-r3.trigger
OK: 307 MiB in 219 packages
[11:02:36] INFO: Installing OCR language
fetch https://dl-3.alpinelinux.org/alpine/latest-stable/main/aarch64/APKINDEX.tar.gz
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/aarch64/APKINDEX.tar.gz
fetch https://dl-3.alpinelinux.org/alpine/latest-stable/community/aarch64/APKINDEX.tar.gz
(1/1) Installing tesseract-ocr-data-deu@community (4.1.1-r5)
```

On a related note: the nc app "recognize" does not work because of missing libs. It asks for "System with glibc (usually the norm; Alpine linux is not such a system)". So as your image is alpine based there is no easy way to turn that on right?

**Comment by alexbelgium** [comment]
Please try 22.1.1-4, I've added gclib compatibility

**Comment by pazz** [comment]
I can actually install this app and it integrates well with occ, but then fails to classify images (apologies for hijacking this issue, i can open another one if you prefer):

```
root@db21ed7f-nextcloud-ocr:/# occ recognize:classify
Classifying photos of user pix
Failed to classify images
Classifier process error
```

The web interface nc -> settings -> logging contains this

```
Classifier process output: sh: exec: line 1: : Permission denied
```

I don't really know where to find mor everbose logs, the occ command does not accept `-v` args.

**Comment by alexbelgium** [comment]
Mmh I 'll have to think about it... Which file would lack permissions. That's on 22.1.1-4?

**Comment by pazz** [comment]
Yes, the latest from this repo.

Here is another log entry, which unfortunately is truncated at the interesting point :/

```
Error: fwrite(): write of 8192 bytes failed with errno=32 Broken pipe at /data/config/www/nextcloud/3rdparty/symfony/process/Pipes/AbstractPipes.php#128
<<closure>>

OC\Log\ErrorHandler::onError()

/data/config/www/nextcloud/3rdparty/symfony/process/Pipes/AbstractPipes.php - line 128:

fwrite()

/data/config/www/nextcloud/3rdparty/symfony/process/Pipes/UnixPipes.php - line 105:

Symfony\Component\Process\Pipes\AbstractPipes->write()

/data/config/www/nextcloud/3rdparty/symfony/process/Process.php - line 1446:

Symfony\Component\Process\Pipes\UnixPipes->readAndWrite()

/data/config/www/nextcloud/3rdparty/symfony/process/Process.php - line 1369:

Symfony\Component\Process\Process->readPipes()

/data/config/www/nextcloud/3rdparty/symfony/process/Process.php - line 1417:

Symfony\Component\Process\Process->updateStatus("*** sensiti ... *")

/data/config/www/nextcloud/3rdparty/symfony/process/Process.php - line 665:

Symfony\Component\Process\Process->readPipesForOutput()

/data/config/www/nextcloud/apps/recognize/lib/Service/ClassifyImagenetService.php - line 82:

Symfony\Component\Process\Process->getIterator()

/data/config/www/nextcloud/apps/recognize/lib/Command/Classify.php - line 99:

OCA\Recognize\Service\ClassifyImagenetService->classify()

/data/config/www/nextcloud/3rdparty/symfony/console/Command/Command.php - line 255:

OCA\Recognize\Command\Classify->execute()

/data/config/www/nextcloud/3rdparty/symfony/console/Application.php - line 1009:

Symfony\Component\Console\Command\Command->run()

/data/config/www/nextcloud/3rdparty/symfony/console/Application.php - line 273:

Symfony\Component\Console\Application->doRunCommand()

/data/config/www/nextcloud/3rdparty/symfony/console/Application.php - line 149:

Symfony\Component\Console\Application->doRun()

/data/config/www/nextcloud/lib/private/Console/Application.php - line 209:

Symfony\Component\Console\Application->run()

/data/config/www/nextcloud/console.php - line 99:

OC\Console\Application->run()

/data/config/www/nextcloud/occ - line 11:

require_once("/data/confi ... p")
```

**Comment by pazz** [comment]
no wait, this is `Add-on version: 22.1.1-3` according to the logs, generated after clicking on "rebuild" in the supervisor web ui

**Comment by alexbelgium** [comment]
If you refresh now the repo, you should be able to install the latest version

**Comment by pazz** [comment]
I'm confused by the logs. I did "rebuild" via the supervisor interface. The logs say

```
 Add-on version: 22.1.1-3
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.1
```

notice line 2 :)

**Comment by alexbelgium** [comment]
It's because the supervisor needs to be refreshed for it to see the new version

**Comment by alexbelgium** [comment]
https://community.home-assistant.io/t/supervisor-add-ons-manual-update/231673/12?u=alexbelgium

**Comment by pazz** [comment]
args, yes, thank you.

I now see some seemingly unrelated error: the (updated) image runs but NC is not responding.
the logs say 

```
Creating possible missing Directories
mkdir: cannot create directory ‘/data/config/www/nextcloud/occ’: File exists
chmod Files and Directories
```

From inside the image root shell i can see that there is actually a php script at this path.
Also, I canno simply call the `occ` command from the (image) shell anymore.

**Comment by pazz** [comment]
Sorry, things have just changed again: The problem I reported above goes away after waiting some 10 minutes, no image restart. Very strange.

**Comment by alexbelgium** [comment]
Creating possible missing Directories
mkdir: cannot create directory ‘/data/config/www/nextcloud/occ’: File exists
chmod Files and Directories

That's normal, you just need to wait a bit for the addon to load

**Comment by pazz** [comment]
OK, all is back up again, and it seems my problem with the recognize script failing due to permission issues persists, exactly as described above.

**Comment by pazz** [comment]
Actually, this doesn't seem to work well. When prefixing the command with `su abc` (abc is the webserver user) I get no output whatsoever. But as you say, root should not have permissions issues.
How do *you* run such test commands on the image as user btw?

**Comment by alexbelgium** [comment]
Honestly I don't use much nc... And when I do I use the webui :)

**Comment by alexbelgium** [comment]
Actually perhaps the owner of the app could better help you as he'll better know his architecture... https://github.com/marcelklehr/recognize

**Comment by pazz** [comment]
Fair. I'll ask around there.
Many thanks for your help!
P


Quoting Alexandre (2021-09-23 18:10:07)

**Comment by alexbelgium** [comment]
With pleasure, if it is due to the addon architecture please let me know and I'll adapt it! 

For example, if we need to provide additional permissions to a global folder... However as I'm not able to run this app on my nc instance (as I only have 1gb ram on a rpi3b+ with armv7) I can't repeat the issue on my system, so it's difficult to help.

Btw, don't hesitate to star my repo if it is useful to you, thanks! :)

**Comment by alexbelgium** [comment]
I'll close the issue as both initially reported elements (ocr and glibc compatibility) were added to the addon. If you receive the info that the issue with the Recognize app is linked to the addon I'll gladly add a new patch afterwards.
