### ISSUE TITLE
🐛 [tandoor_recipes] No mariadb_addon as DB_TYPE

### ISSUE THREAD

**Issue by IonutNeagu** [alexbelgium/hassio-addons#510]
**Which addon?**

- Addon name : tandoor_recipes
- Addon version : 1.4.4

**Describe the bug**

In the readme it appears that "mariadb_addon " can be selected as DB_TYPE, but in the config it cannot be selected.

**To Reproduce**

**Full addon log**

**Full addon config**

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hi, thanks, tandoor recipes doesn't support mariadb and I had to remove it. I'll adapt the readme, thanks for noticing
