### ISSUE TITLE
[Nextcloud] Can you mount an NTFS external HDD through localdisks:?

### ISSUE THREAD

**Issue by Eeeeeediot** [alexbelgium/hassio-addons#511]
**Nextcloud**

name: NTFS support
title: 'Can you mount an NTFS external HDD through localdisks:?'
labels: 'Question'

Can you mount an NTFS external HDD through localdisks: to a Powered USB hub attached to a RPi4? I have a media drive that is full of Pictures/Tv Shows/Movies that I would like to make accessible on my local network. It does work through the networkdisks: option but its currently plugged into a windows machine that sleep after 10 minutes and therefore becomes inaccessible.

I originally intended to use the SAMBANAS addon but that doesn't play nice with Windows formatted HDD apparently.

Great Addon btw, cheers!

**Comment by alexbelgium** [comment]
Hi, indeed it uses the same mount system so it won't work to mount NTFS drives. This topic was also discussed here : https://github.com/alexbelgium/hassio-addons/issues/235

**Comment by alexbelgium** [comment]
Support could have been added

**Comment by Eeeeeediot** [comment]
> Support could have been added

Sorry, do you mean you have added it?

**Comment by alexbelgium** [comment]
Yes indeed, but not sure it works. It is in the latest pushed version

**Comment by Eeeeeediot** [comment]
> Yes indeed, but not sure it works. It is in the latest pushed version ; I don't have a NTFS drive to test

Ok thanks. I will try it and let you know
