### ISSUE TITLE
🐛 [Nextcloud] Stange version of update pop up 

### ISSUE THREAD

**Issue by michelebossa** [alexbelgium/hassio-addons#518]
**Which addon?**
 

- Addon name : Nextcloud
- Addon version : 24.0.7

**Describe the bug**

This moring i recive a pop up to update from 24.0.7 to 24.0.6 i think there is some trouble on verison of addon.
<img width="528" alt="image" src="https://user-images.githubusercontent.com/38975058/196898894-43da67e9-2976-4871-bae8-6f9fde6298f3.png">

Someone chan check?

**To Reproduce**

**Full addon log**

**Full addon config**

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hi, thanks I had forced it manually to avoid it showing as it's broken due to an upstream change. I've put back the correct version thanks for noticing it!

**Comment by michelebossa** [comment]
can i proceed with update now ?

**Comment by alexbelgium** [comment]
I'll test it also in parallel, not sure it still works https://github.com/alexbelgium/hassio-addons/issues/519

**Comment by michelebossa** [comment]
Ok i'm waiting i suppose for next version or when you close the #519 many thanks

**Comment by alexbelgium** [comment]
Hi, the new version should work fine. thanks

**Comment by michelebossa** [comment]
it is not working now i have an error into log about this:

s6-rc: info: service 99-ci-service-check successfully started
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /data/config/nginx/site-confs/default.conf:9****

**Comment by alexbelgium** [comment]
Should be solved now

**Comment by michelebossa** [comment]
Fixed thanks
