### ISSUE TITLE
Download speed very slow

### ISSUE THREAD

**Issue by tonysprenk** [alexbelgium/hassio-addons#52]
All of a sudden my download speeds are veery slow. When I check if port 50277 is open it is not. Could it be that my iso is blocking that port suddenly? If so what would be the best way to setup openVPN?

**Comment by alexbelgium** [comment]
Hi, I suppose port 50277 is your external port?
Internal ports for qbittorrent are:
    "8080/tcp": 8081,
    "6881/tcp": 6881,
    "6881/udp": 6881

If you map 50277 in the addon options, it means your isp will see port 50277 being used but it is simply mapped to 6881. That's why ports in qbittorrent itself shouldnt be changed : if so, the link between internal and external ports would stop' There are no automatic port mapping.

Are you sure it is not simply your vpn provider that has slowed due to some issue of theirs?

**Comment by tonysprenk** [comment]
I read somewhere that qbittorrent uses 50277 for peer connections. I am not using a vpn at this moment.

**Comment by alexbelgium** [comment]
Hi, the port is customized with the addon. You can check it by looking at /config/qBittorrent/qbittorrent.conf and see the line
```
Connection\PortRangeMin=6881
```

**Comment by alexbelgium** [comment]
Sorry if it seems a bit a simplistic solution, but have you checked that the alternative upload speed option is not enabled? This would severely reduce speeds

**Comment by tonysprenk** [comment]
Yup that was it, I feel stupid now…

**Comment by alexbelgium** [comment]
As long as it works! That's the most important!

**Comment by tonysprenk** [comment]
I was wrong, speeds are still really slow. A little bit faster but never above 100kbs. When I toggle the alt  speed switch on and off the speed spikes up momentarily but then drops back down. Any idea?

**Comment by tonysprenk** [comment]
Reopen

**Comment by alexbelgium** [comment]
Hi, please try that https://www.reddit.com/r/qBittorrent/comments/fvpeib/comment/fmk3yh6/
Custom DNS referred to in the article can be changed from the addon options 

Have you a backup version from when it last worked that you can go to? That would make sure if it's something that has changed on the addon or your system.

**Comment by tonysprenk** [comment]
That sorted it. Thanks for everything!

**Comment by alexbelgium** [comment]
Thanks for the feedback!
