### ISSUE TITLE
[Nextcloud] how to pass extra param(s) to config.php ?

### ISSUE THREAD

**Issue by kulmegil** [alexbelgium/hassio-addons#520]
**Nextcloud**

name: config
title: How can I pass extra param to config.php ?
labels: question

---

Is it possible to add a pram (not part of addon configuration) to Nextcloud's `config.php`?
`/data/config/www/nextcloud/config/config.php`

I want to add `'allow_local_remote_servers' => true` so Nextcloud can read data from other containers - e.g. import my external calendars. I can always got into container's shell to edit the file.. but is there a better way?

**Comment by alexbelgium** [comment]
Dear [kulmegil](https://github.com/kulmegil), thanks for your request ; please use the template if possible next time it sets labels & ensure formatting. I'll look at it when I have some time but it would seem rather easy to implement

**Comment by alexbelgium** [comment]
Hi, should be good now

**Comment by kulmegil** [comment]
I have tested with 25.0.0-7 and indeed the param was passed to config.php
