### ISSUE TITLE
🐛 [portainer] Addon fails to start

### ISSUE THREAD

**Issue by cuihaijun** [alexbelgium/hassio-addons#522]
-----------------------------------------------------------
 Add-on: Portainer
 Manage your Docker environment with ease
-----------------------------------------------------------
 Add-on version: 2.15.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.2  (amd64 / qemux86-64)
 Home Assistant Core: 2022.10.4
 Home Assistant Supervisor: 2022.10.0
-----------------------------------------------------------
 s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
Executing modules script : 00-banner.sh
/etc/cont-init.d/00-aaa_dockerfile_backup.sh: line 15: apt-get: command not found
00-banner.sh
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 4 ms: Connection refused
script failed to install 00-banner.sh
Executing dependency script with custom elements : nginx
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 0 ms: Connection refused
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-aaa_portainer_install.sh
cont-init: info: /etc/cont-init.d/00-aaa_portainer_install.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh

[http,server] [message: starting HTTP server on port 0.0.0.0:9000]"
[06:55:12] INFO: Starting NGinx...
./run: line 12: exec: nginx: not found
[06:55:12] INFO: Waiting for port 9000 to open...
[06:55:12] INFO: Starting NGinx...
./run: line 12: exec: nginx: not found
[06:55:13] INFO: Waiting for port 9000 to open...

**Comment by cuihaijun** [comment]
Please forgive me for not speaking English. Post the wrong log，raw.githubusercontent.com

**Comment by alexbelgium** [comment]
Hi, are you on HA os? It seems your system doesn't allow external connection : `curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 4 ms: Connection refused`

**Comment by alexbelgium** [comment]
I've tested and on my system it installs and starts fine

**Comment by alexbelgium** [comment]
To be clearer, it's probably due to how your system is configured

**Comment by cuihaijun** [comment]
> Hi, are you on HA os? It seems your system doesn't allow external connection : `curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 4 ms: Connection refused`

Executing modules script : 00-banner.sh
/etc/cont-init.d/00-aaa_dockerfile_backup.sh: line 15: apt-get: command not found

**Comment by cuihaijun** [comment]
> 更清楚的是，这可能是由于您的系统是如何配置的。

The version I upgraded to now works, but this time it's reinstalled and it doesn't work

**Comment by cuihaijun** [comment]
> I've tested and on my system it installs and starts fine
The version I upgraded to now works, but this time it's reinstalled and it doesn't work

**Comment by cuihaijun** [comment]
> I've tested and on my system it installs and starts fine

The version I upgraded to now works, but this time it's reinstalled and it doesn't work

**Comment by alexbelgium** [comment]
> > Hi, are you on HA os? It seems your system doesn't allow external connection : `curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 4 ms: Connection refused`
> 
> Executing modules script : 00-banner.sh /etc/cont-init.d/00-aaa_dockerfile_backup.sh: line 15: apt-get: command not found

Hi, that's normal : it first tests with apt-get then with apk (it's an universal script)
