### ISSUE TITLE
[Cloudcommander (and others)] FATAL: Unable to mount local drives

### ISSUE THREAD

**Issue by KuchenKavalier** [alexbelgium/hassio-addons#523]
Hi there 

I can't mount any USB-drive to Cloudcommander and all other addons. I have tried different ext. HDD/SSDs with different FS. EXT4 and the EXT3 as well. 

**Here the log for Cloudcommander:**

/etc/cont-init.d/92-local_mounts.sh: executing
Local Disks mounting...
mount: /mnt/sdb1: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error.
[15:54:08] FATAL: Unable to mount local drives! Please check the name.
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[15:54:08] INFO: Starting...

**HAOS Host reports:** 

[ 1038.089390] EXT**4**-fs (sdb1): Unrecognized mount option "uid=0" or missing value

(but this SSD is formatted in EXT**3** as the Hardware Attribute says)

**Hardware Attribute:**

Attribute:
DEVLINKS: >-
  /dev/disk/by-id/ata-Samsung_Portable_SSD_T5_S511NR0N401845H-part1
  /dev/disk/by-id/wwn-0x5002538e00000000-part1 /dev/disk/by-partuuid/b605c35c-01
  /dev/disk/by-path/pci-0000:01:1b.0-usb-0:4.1:1.0-scsi-0:0:0:0-part1
  /dev/disk/by-uuid/3c7a23c1-61cc-4f8b-8908-e8a8b88e404e
DEVNAME: /dev/sdb1
DEVPATH: >-
  /devices/pci0000:00/0000:00:1e.0/0000:01:1b.0/usb2/2-4/2-4.1/2-4.1:1.0/host3/target3:0:0/3:0:0:0/block/sdb/sdb1
DEVTYPE: partition
DISKSEQ: '14'
ID_ATA: '1'
ID_ATA_DOWNLOAD_MICROCODE: '1'
ID_ATA_FEATURE_SET_PM: '1'
ID_ATA_FEATURE_SET_PM_ENABLED: '1'
ID_ATA_FEATURE_SET_SMART: '1'
ID_ATA_FEATURE_SET_SMART_ENABLED: '1'
ID_ATA_ROTATION_RATE_RPM: '0'
ID_ATA_SATA: '1'
ID_ATA_SATA_SIGNAL_RATE_GEN1: '1'
ID_ATA_SATA_SIGNAL_RATE_GEN2: '1'
ID_ATA_WRITE_CACHE: '1'
ID_ATA_WRITE_CACHE_ENABLED: '1'
ID_BUS: ata
ID_FS_TYPE: ext3
ID_FS_USAGE: filesystem
ID_FS_UUID: 3c7a23c1-61cc-4f8b-8908-e8a8b88e404e
ID_FS_UUID_ENC: 3c7a23c1-61cc-4f8b-8908-e8a8b88e404e
ID_FS_VERSION: '1.0'
ID_MODEL: Samsung_Portable_SSD_T5
ID_MODEL_ENC: >-
  Samsung\x20Portable\x20SSD\x20T5\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_PART_ENTRY_DISK: '8:16'
ID_PART_ENTRY_NUMBER: '1'
ID_PART_ENTRY_OFFSET: '2048'
ID_PART_ENTRY_SCHEME: dos
ID_PART_ENTRY_SIZE: '1953521664'
ID_PART_ENTRY_TYPE: '0x83'
ID_PART_ENTRY_UUID: b605c35c-01
ID_PART_TABLE_TYPE: dos
ID_PART_TABLE_UUID: b605c35c
ID_PATH: pci-0000:01:1b.0-usb-0:4.1:1.0-scsi-0:0:0:0
ID_PATH_TAG: pci-0000_01_1b_0-usb-0_4_1_1_0-scsi-0_0_0_0
ID_REVISION: MVT42P1Q
ID_SERIAL: Samsung_Portable_SSD_T5_S511NR0N401845H
ID_SERIAL_SHORT: S511NR0N401845H
ID_TYPE: disk
ID_WWN: '0x5002538e00000000'
ID_WWN_WITH_EXTENSION: '0x5002538e00000000'
MAJOR: '8'
MINOR: '17'
PARTN: '1'
SUBSYSTEM: block
TAGS: ':systemd:'
USEC_INITIALIZED: '805155494'

Any idea how to fix this issue? Looking forward to any help!

**Comment by alexbelgium** [comment]
Hi, please refresh your repos and try to rebuild, let's see how that goes

**Comment by KuchenKavalier** [comment]
Thank you Alex - this did the trick. Now the ext. hdd is mounted as it should. :-) 

But unfortunately PLEX can't be reinstalled. 

**I get the follow error:** 

Add-on konnte nicht installiert werden
The command '/bin/sh -c file="$(grep -sril 'Server claimed successfully, navigate to http://serverip:32400/web to complete plex setup' /etc/cont-init.d /etc/services.d /etc/s6-overlay/s6-rc.d)" && sed -i 's/with-contenv bash/with-contenv bashio/g' "$file" && sed -i '2iexport PLEX_CLAIM=$(bashio::config "claim")' "$file" && sed -i '3i[ $PLEX_CLAIM = "Get_from_https://www.plex.tv/claim" ] && bashio::log.warning "Please change the PLEX_CLAIM code from the options" && exit 1 || true' "$file"' returned a non-zero code: 2

**The log says:** 
22-10-22 00:43:30 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build db21ed7f/amd64-addon-plex_nas:1.29.1.6313-f4cdfea9c-ls135: The command '/bin/sh -c file="$(grep -sril 'Server claimed successfully, navigate to http://serverip:32400/web to complete plex setup' /etc/cont-init.d /etc/services.d /etc/s6-overlay/s6-rc.d)"     && sed -i 's/with-contenv bash/with-contenv bashio/g' "$file"     && sed -i '2iexport PLEX_CLAIM=$(bashio::config "claim")' "$file"     && sed -i '3i[ $PLEX_CLAIM = "Get_from_https://www.plex.tv/claim" ] && bashio::log.warning "Please change the PLEX_CLAIM code from the options" && exit 1 || true' "$file"' returned a non-zero code: 2
22-10-22 00:43:30 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/27 : ARG BUILD_FROM
Step 2/27 : ARG BUILD_VERSION
Step 3/27 : FROM ${BUILD_FROM}
 ---> 4203d569b996
Step 4/27 : ENV S6_CMD_WAIT_FOR_SERVICES=1     S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0     S6_SERVICES_GRACETIME=0
 ---> Using cache
 ---> dea2b098185e
Step 5/27 : RUN     file="$(grep -sril 'Server claimed successfully, navigate to http://serverip:32400/web to complete plex setup' /etc/cont-init.d /etc/services.d /etc/s6-overlay/s6-rc.d)"     && sed -i 's/with-contenv bash/with-contenv bashio/g' "$file"     && sed -i '2iexport PLEX_CLAIM=$(bashio::config "claim")' "$file"     && sed -i '3i[ $PLEX_CLAIM = "Get_from_https://www.plex.tv/claim" ] && bashio::log.warning "Please change the PLEX_CLAIM code from the options" && exit 1 || true' "$file"
 ---> Running in 34826b4f26bc
Removing intermediate container 34826b4f26bc

Any idea on this one?

**Comment by alexbelgium** [comment]
Thanks, this will be followed here : https://github.com/alexbelgium/hassio-addons/issues/525

I'll close this one then
