### ISSUE TITLE
QBitTorrent web ui issue 

### ISSUE THREAD

**Issue by SiriosDev** [alexbelgium/hassio-addons#527]
**Which addon?**

QBitTorrent

- Addon name : QBitTorrent
- Addon version : 4.4.5-r2-ls224

**Describe the bug**

1. Selected web UI does not affect the ingress page of QBitTorrent
2. The theme (personal custom UI) of the page exposed on 8081, reset on every reboot/launch of the addon

**Full addon config**

```
DNS_server: *redacted*
PGID: "0"
PUID: "0"
SavePath: *redacted*
Username: *redacted*
certfile: fullchain.pem
customUI: default
keyfile: privkey.pem
ssl: false
whitelist: *redacted*
```

**System**

- Supervisor version: 2022.10.0
- Host system version: Home Assistant OS 9.2

**Comment by alexbelgium** [comment]
Hi, indeed the ingress UI is hardcoded to avoid issues with browser cache. For the second element I can check how to make it remanent

**Comment by SiriosDev** [comment]
about the ingress page, I agree with your choice, just, in the configuration, it is a bit ambiguous what the themes will be applied to, btw, for the second one I can suggest (in the configuration) a "custom" option (besides vue, qb-mat, etc.) and a text field (optional) to enter a path?

**Comment by alexbelgium** [comment]
Hi, selecting custom in the list of ui should allow you to keep remanent the ui that you modified manually .

**Comment by SiriosDev** [comment]
Funziona! Avevo pensato ad un campo stringa nella configurazione ma l'importante è che non cambi dopo il riavvio. Per adesso ritengo di poter chiudere l'issue, grazie!
