### ISSUE TITLE
🐛 [Paperless-ngx] Linuxserver Image Deprecated

### ISSUE THREAD

**Issue by F4bsi** [alexbelgium/hassio-addons#528]
**Which addon?**

- Addon name : Paperless-ngx
- Addon version : v1.8.0-ls30

**Describe the bug**

Not sure if bug is the right category 😄 

Sadly the Image proved by linuxserver is deprecated (see [here](https://docs.linuxserver.io/images/docker-paperless-ngx#deprecation-notice)) and they recommend using the official one, which is currently at version 1.9.2.

Is there any way to switch it to the official one?

Thank you for this huge repository!

**Comment by alexbelgium** [comment]
Hi, thanks I've switched it to a request and will look at it

**Comment by alexbelgium** [comment]
This is not an easy switch... The container structure is quite different. I'll look at it but not sure when

**Comment by alexbelgium** [comment]
Hi, I've changed the version and it seems to work. Please let me know if there are issues. Commit : https://github.com/alexbelgium/hassio-addons/commit/c6f80bdd16bd9d27f47f0903a59d358d354233f0

**Comment by F4bsi** [comment]
Hey, Thanks! You are fast 😄 

I just tested this with a new install and for some reason it did not create the default user. I think with the official image you have to run a command (`docker-compose run --rm webserver createsuperuser`) or include some variables (`PAPERLESS_ADMIN_USER `& `PAPERLESS_ADMIN_PASSWORD`) to create the user. 

I used the docker command to start a bash and was able to create it with the following command inside the container: `python manage.py createsuperuser ` but as this is interactive, I guess the variables would be the way to go. 

Also I noticed the version is 1.9.2, but the addon says its 1.8.2, or is this just a coincidence, that you follow a simmilar versioning? 

I was able to test a couple of documents and everything seems normal, now I just need to find a good way to move everything from my old installation, running on a way too loud and energy-hungry windows pc 😆

**Comment by alexbelgium** [comment]
Thanks, I've reused the code from linuxserver to create the default user

If you could move everything it would be very interesting to have a slight guide so we could add it to the documentation :-)

**Comment by F4bsi** [comment]
Hey, just noticed on thing in the logs. Not sure if relevant:

```
[15:14:14] INFO: Starting redis
[15:14:14] INFO: Avoid overcommit memory
sysctl: permission denied on key "vm.overcommit_memory"
/etc/cont-init.d/99-run.sh: exiting 255
```

Also still have an issue moving my old installation, I thought the easiest way would be to use the network mount feature and change the path to the files via the config.yaml like this:

```
PAPERLESS_DATA_DIR=/mnt/homeassistant
PAPERLESS_MEDIA_ROOT=/mnt/homeassistant/media
PAPERLESS_CONSUMPTION_DIR=/mnt/homeassistant/consume
```

But it still seems to use the data inside the homeassistant config folder (so currently on the SD card). Am I doing something wrong, or is this not how it is supposed to work?

I copied over the database file to the config folder and it is able to load everything (except the PDFs and images, because I didn't copy everything), but I would like to keep all the PDF files and so on on my Nas.

**Comment by alexbelgium** [comment]
Indeed I've forced it to use the config folder with `ENV \
    PAPERLESS_DATA_DIR=/config/addons_config/paperless_ng \
    PAPERLESS_MEDIA_ROOT=/config/addons_config/paperless_ng/media \
    PAPERLESS_CONSUMPTION_DIR=/config/addons_config/paperless_ng/consume
` which has precedence over the config file

I would have to see how to make that dynamic

**Comment by malcolmrigg** [comment]
Hi, I was hoping to try out this addon for the first time, but looks like you're in the middle of some fairly large changes, so the error I'm getting may just be related to these?

Every time I try starting the addon it fails and I just get this in the log:
/usr/bin/env: ‘bashio’: No such file or directory

I'm running version 1.9.2-8 on a Raspberry Pi 4B/raspbian/supervised install.

**Comment by alexbelgium** [comment]
Hi, should work now

**Comment by malcolmrigg** [comment]
Amazing, thank you!
