### ISSUE TITLE
Acces volume to edit config.js

### ISSUE THREAD

**Issue by GoempieK** [alexbelgium/hassio-addons#529]
Running Home assistant OS, after importing a container a volume is created.
After this I should edit the config.js file that is located in the path below.
But can't seems to acces the config.js tried with file editor but i can't seem to find the file.

Sorry for the noob question

![image](https://user-images.githubusercontent.com/2872530/198555155-9ffc05a3-da81-4aad-a4d8-01a847529d24.png)

**Comment by alexbelgium** [comment]
Hi, for which addon? Either you can modify it with portainer, ssh with root access, or we need to customize the add-on to expose it

**Comment by GoempieK** [comment]
The container stops running is the config.js file isn't ok.
Its not an addon its https://github.com/SpoBo/dobiss2mqtt

**Comment by alexbelgium** [comment]
Hi, sorry I don't provide support for apps I don't have in my repo. However, the easiest could be to install the container in portainer, and map the env variable CONFIG_PATH to an accessible path such as the shared files. I suggest you post in the HA community forum for better support. Hope it will work out for you!

**Comment by GoempieK** [comment]
Alex thanks for pointing me in the right direction.
Was more looking at it as a combination of HA OS and portainer problem.

But got it working with the smb addon and the correct variables/volume binds
For people having the same problem just add the smb addon so you can access the share folder and bind the volume to the container.

![image](https://user-images.githubusercontent.com/2872530/198868263-b8a8a64e-f74d-46f9-adfd-d78947183d8c.png)

**Comment by alexbelgium** [comment]
Thanks for the info!
