### ISSUE TITLE
nextcloud broken config.php after recent change

### ISSUE THREAD

**Issue by pazz** [alexbelgium/hassio-addons#53]
6a1d8c5f23287b79cff176a53649a875cfe65c2c seems is problematic (sorry for the repost as issue, I'm not sure if you get notified for comments on commits).
Even with only setting one trusted domain in the config, the generated config.php is broken as it wraps the domain string in garbage.
This is how it looks with a named domain after a local ip for me:

```
  'trusted_domains' =>
  array (
    0 => '192.168.1.234:8098',
    2 => '{notmyreal.duckdns.org//,/',
    3 => '}',
  ),
```

**Comment by alexbelgium** [comment]
Hi, thanks it was a typo mistake. It should work in the -6 version

**Comment by pazz** [comment]
hmm not sure this has worked:
The web interface claims there is an internal server error and the nginx logfile sais this:

```
2021/09/28 15:35:45 [error] 76440#76440: *53 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'dbtype' (T_STRING), expecting ')' in /data/config/www/nextcloud/config/config.php on line 13" while reading upstream, client: 81.187.229.141, server: _, request: "GET /apps/photos/service-worker.js HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "notreal.duckdns.org:8443", referrer: "https://notreal.duckdns.org:8443/apps/photos/service-worker.js"
```

the generated config looks like this now:

```
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/share/nextcloud',
  'instanceid' => 'ocm9hv714a',
  'passwordsalt' => 'hXdsgaJk8//jykC4624e5vgLE3YW',
  'secret' => '29z9XMXIZ4TGJ0nGwheLCGkYGfX7xqzvBvELk1yTziPGYw',
  'trusted_domains' =>
  array (
    0 => '192.168.1.234:8098',
    1 => 'notreal.duckdns.org,
  ),
  'dbtype' => 'mysql',   # <- this is line 13
```

**Comment by alexbelgium** [comment]
mmh... it works on my system but I fear that the typo created a corrupted database... do you have a backup ?
That would be the easiest way to test it...

**Comment by alexbelgium** [comment]
btw your config has an error : 
"1 => 'notreal.duckdns.org," -> there should be a ' before the ,

**Comment by pazz** [comment]
Oh boy, you are right! Mea culpa!
What happened was that I've edited that file manually to "fix" the initial syntax error and since everything under /data is preserved that kept introducing the issue.
All's good now :)
P


Quoting Alexandre (2021-09-28 16:03:45)

**Comment by alexbelgium** [comment]
Great news!

**Comment by alexbelgium** [comment]
Hi, I've done a new change to the config. It only refreshes the files ownership at restart if the PUID changes in the options. It should be much much faster, but please let me know if you see any issue! Thanks

**Comment by pazz** [comment]
The newest version 22.1.1-6 seems to work well for me.

**Comment by alexbelgium** [comment]
Thanks!
