### ISSUE TITLE
[qbittorrent] VPN "configured properly" but not also "Options error: Unrecognized option or missing or extra parameter(s)"

### ISSUE THREAD

**Issue by Stooovie** [alexbelgium/hassio-addons#539]
**Which addon?**

- Addon name : Qbittorrent
- Addon version : 4.4.5-r2-ls226 

**Describe the bug**

Qbittorrent doesn't start with OpenVPN (Mullvad) enabled. Log tells me OVPN is properly configured, yet then is starts complaining about /etc/openvpn/config.ovpn which I don't have access to:

`cont-init: info: running /etc/cont-init.d/93-openvpn.sh
[20:11:49] INFO: Configuring openvpn
[20:11:50] INFO: openvpn correctly set, qbittorrent will run tunnelled through openvpn
Using interface binding in the qBittorrent app
... deleting previous interface settings
... binding tun0 interface in qBittorrent configuration
... adding route-nopull to your config.ovpn
cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 0
[custom-init] No custom files found, skipping...
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/config.ovpn:19: service (2.5.7)
Use --help for more information.
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/config.ovpn:19: service (2.5.7)
Use --help for more information.`

**Full addon log**

```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
 Add-on version: 4.4.5-r2-ls226
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.11.1
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-folders.sh
cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/30-nginx.sh
cont-init: info: /etc/cont-init.d/30-nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/90-dns_set.sh
[20:17:23] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 0
cont-init: info: running /etc/cont-init.d/91-qbittorrent_configuration.sh
[20:17:24] INFO: Downloads can be found in /mnt/Public/Downloads
[20:17:24] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[20:17:25] INFO: WEBUI username set to stooovie
[20:17:25] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
[20:17:27] INFO: Default username/password : admin/adminadmin
[20:17:27] INFO: Configuration can be found in /config/addons_config/qBittorrent
cont-init: info: /etc/cont-init.d/91-qbittorrent_configuration.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
Mounting smb share(s)...
Using PUID 0 and PGID 0
[20:17:29] INFO: ... //192.168.0.216/Public successfully mounted to /mnt/Public with options 
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-openvpn.sh
[20:17:30] INFO: Configuring openvpn
[20:17:30] INFO: openvpn correctly set, qbittorrent will run tunnelled through openvpn
Using interface binding in the qBittorrent app
... deleting previous interface settings
... binding tun0 interface in qBittorrent configuration
... adding route-nopull to your config.ovpn
cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 0
[custom-init] No custom files found, skipping...
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/config.ovpn:19: service (2.5.7)
Use --help for more information.
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/config.ovpn:19: service (2.5.7)
Use --help for more information.
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/config.ovpn:19: service (2.5.7)
Use --help for more information.
```

**Full addon config**

DNS_server: 8.8.8.8,1.1.1.1
PGID: "0"
PUID: "0"
SavePath: /mnt/Public/Downloads
Username: xxxxxx
certfile: fullchain.pem
customUI: vuetorrent
keyfile: privkey.pem
ssl: false
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
cifsusername: xxxx
cifspassword: xxxx
networkdisks: //192.168.0.216/Public
openvpn_enabled: true
openvpn_config: mullvad_cz_prg.ovpn
openvpn_username: "XXXXXXXX"
openvpn_password: m

**System**

Home Assistant 2022.11.1 on Rpi4
Supervisor 2022.10.2

**Comment by alexbelgium** [comment]
Hi, your ovpn for must be in /config/openvpn. It id the copied to the file in which the error is detected. https://github.com/alexbelgium/hassio-addons/blob/409dce74dfd695c33242c423e015aee81268d978/qbittorrent/rootfs/etc/cont-init.d/93-openvpn.sh#L24

It seems your ovpn file has an error inside

**Comment by Stooovie** [comment]
it is there... weird thing is, no matter what I remove or adjust at the error line, next time the same line number appears in the error

**Comment by Stooovie** [comment]
This is the ovpn file:

`client
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
remote-cert-tls server
ping 10
ping-restart 60
sndbuf 524288
rcvbuf 524288
cipher AES-256-CBC
tls-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA
proto udp
auth-user-pass mullvad_userpass.txt
ca mullvad_ca.crt
service mullvadopenvpn
remote-random
remote 217.138.199.82 1196 # cz-prg-005
remote 185.156.174.146 1196 # cz-prg-001
remote 146.70.129.162 1196 # cz-prg-ovpn-101
remote 146.70.129.194 1196 # cz-prg-ovpn-102
remote 217.138.199.74 1196 # cz-prg-004
remote 185.216.35.242 1196 # cz-prg-003
remote 185.156.174.170 1196 # cz-prg-002
pull-filter ignore "route-ipv6"
pull-filter ignore "ifconfig-ipv6"`

**Comment by alexbelgium** [comment]
I've checked it worked. I don't know openvpn and can't help you, but from a Google search the error you see in the log indicates the line starting with service (service mullvadopenvpn) is invalid

**Comment by Stooovie** [comment]
Still the same error after removing "service mullvadopenvpn" - I have triple-checked if I'm editing and saving the right file, I am... I guess no MullvadVPN for me. Thanks!

**Comment by alexbelgium** [comment]
That's strange... I've installed your ovpn file and replicate the `service` error. I then stopped the addon, removed this line, restarted the addon, and the error message regarding `service` has disappeared. Of course it does't connect has I don't have the certs your ovpn file lists, but it changes the message.

**Comment by Stooovie** [comment]
It is really weird as I'm now getting the same thing. Any idea where to put the .crt file? If I put it alongside the ovpn file, it's not found. Jesus this VPN stuff is complicated :)

**Comment by Stooovie** [comment]
For posterity: if you pick **Android/ChromeOS** as a Platform on Mullvad website, the cert is embedded in the ovpn file. Also I had to add
```
pull-filter ignore "route-ipv6"
pull-filter ignore "ifconfig-ipv6"
```
into it. Then it still complains at launch, but launches anyway, and the VPN seems to be working. Thanks for your time!

**Comment by alexbelgium** [comment]
Great news! Enjoy
