### ISSUE TITLE
Xteve loses all configuration after server reboot.

### ISSUE THREAD

**Issue by tonysprenk** [alexbelgium/hassio-addons#54]
Is this normal behaviour? Every time my homeassistant server reboots xteve reverts back to factory settings and I have to configure everything again…

**Comment by alexbelgium** [comment]
well that's surely not an expected behavior and I'm sorry for the work it has caused you.
It means that the database is not located in a persistent folder such as /data.
I'll check how to solve that

**Comment by alexbelgium** [comment]
I forgot a "/" in the dockerfile... hopefully it will work now with the new version I've pushed, I'll test it

**Comment by alexbelgium** [comment]
It should work, could you please confirm? Thanks

**Comment by tonysprenk** [comment]
Yes working fine now! Thanks for all your hard work and thanks for maintaining so actively!

**Comment by alexbelgium** [comment]
That's great, thanks for the feedback!
