### ISSUE TITLE
✨ [REQUEST] Webtrees

### ISSUE THREAD

**Issue by dtrochow** [alexbelgium/hassio-addons#540]
**Which addon?**

- Addon name: Webtrees
- Addon version: v2.1.7

**Is your feature request related to a problem? Please describe.**

I would like to connect to the Webtrees from outside of my local network and the simplest way to accomplish that is to use the [Cloudflare](https://www.cloudflare.com/) Tunnels. Because of how the Webtrees works I am not able to connect to it, because it refuses the connections.

**Describe the solution you'd like**

As I saw on the Webtrees webpage, the additional line in a `data/config.ini.php` file needs to be added to allow connections from Cloudflare servers -> [Using webtrees behind a proxy server](https://webtrees.net/admin/proxy/).

`trusted_headers="cf-connecting-ip"`

Is it possible to add this to the Configurations of webtrees add-on? It would be perfect if we could just fill the `cf-connecting-ip` in webtrees configuration tab.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by dtrochow** [comment]
Hi @alexbelgium, thanks for taking an action so quickly! ;)
I have another question, is it possible to manually specify the `BASE URL`?

I think there might be a problem with the URL, because when I configuring the BASE_URL in configuration it must be filled without the port. When I changing the base address to one from Cloudflare, e.g. `some.address.tk` (which is configured to get me to my local instance of Webtrees - `ip-address:port`), the base address is being modified to `some.address.tk:port`, so it is not able to reach my local server, because port is already given in Cloudflare configuration.

**Comment by dtrochow** [comment]
The addon is not starting properly now, because it occurred that for some reasons the `data/config.ini.php` file does not exists within the webtrees docker container.
```
sed: couldn't edit /share/webtrees: not a regular file
/etc/cont-init.d/99-run.sh: exiting 4
```

**Comment by alexbelgium** [comment]
Hi, thanks ! Indeed I forgot the path for the ini file, should be solved with https://github.com/alexbelgium/hassio-addons/commit/88616f9935ad26030ff49669291ae13a11b71271

**Comment by dtrochow** [comment]
I think it could solve the problem

**Comment by dtrochow** [comment]
It works! ;) Thanks a lot for a quick response!

**Comment by alexbelgium** [comment]
Great news! Enjoy
