### ISSUE TITLE
🐛 [Transmission] Can't configure alternative frontend

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [alexbelgium/hassio-addons#541]
**Which addon?**

- Addon name : Transmission
- Addon version : 3.00-r6-ls140

**Describe the bug**

When trying to change configuration of an add-on to use another web interface, change is not reflected in freshly restarted container.

**To Reproduce**

1. Go to HA Add-ons → Transmisssion → Configuration
2. Change CustomUI to another value. Click Save and restart add-on
3. Go to web page. UI is not changed!

**Full addon log**

```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Transmission
 Bittorrent client based on linuxserver image
-----------------------------------------------------------
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
 Add-on version: 3.00-r6-ls140
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.1
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/19-config.sh
Updating folders
sed: /etc/services.d/transmission/run: No such file or directory
cont-init: info: /etc/cont-init.d/19-config.sh exited 1
cont-init: info: running /etc/cont-init.d/19-json_repair.sh
Checking settings.json format
```
Quick look at code https://github.com/alexbelgium/hassio-addons/blob/master/transmission/rootfs/etc/cont-init.d/19-config.sh#L39 shows that changing UI is doing a `sed` on file `/etc/services.d/transmission/run`. Unfortunately, such file is not present inside the container.

**Full addon config**

![image](https://user-images.githubusercontent.com/24268470/200646214-5f1f60ff-5813-4052-9395-834d40683e20.png)

**System**

- Supervisor version: 2022.10.2
- Host system version: 9.3  (amd64 / qemux86-64)

**Comment by alexbelgium** [comment]
Hi, thanks, this is solved in the newly pushed version. Beware that you need to clear browser cache for the webui to refresh
