### ISSUE TITLE
🐛 [Transmission] Error: Invalid prefix for given prefix length.

### ISSUE THREAD

**Issue by novisys** [alexbelgium/hassio-addons#545]
**Which addon?**
Transmission 4.2-test5

- Addon name : transmission_openvpn
- Addon version : 4.2-test5 

**Describe the bug**
Transmission not accessible and ingress give me 502 bad gateway

**Full addon log**
+ export CONFIG=/etc/openvpn/custom/custom.ovpn
+ CONFIG=/etc/openvpn/custom/custom.ovpn
+ python3 /etc/openvpn/persistEnvironment.py /etc/transmission/environment-variables.sh
+ TRANSMISSION_CONTROL_OPTS='--script-security 2 --route-up /etc/openvpn/tunnelUp.sh --route-pre-down /etc/openvpn/tunnelDown.sh'
+ [[ false == \t\r\u\e ]]
+ [[ -n 192.168.178.0/16 ]]
++ awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}'
++ /sbin/ip route list match 0.0.0.0
+ eval GW=172.30.32.1 INT=eth0
++ GW=172.30.32.1
++ INT=eth0
+ [[ false == \t\r\u\e ]]
+ [[ false == \t\r\u\e ]]
+ [[ -n 192.168.178.0/16 ]]
+ [[ -n 172.30.32.1 ]]
+ [[ -n eth0 ]]
+ for localNet in ${LOCAL_NETWORK//,/ }
+ echo 'adding route to local network 192.168.178.0/16 via 172.30.32.1 dev eth0'
+ /sbin/ip route replace 192.168.178.0/16 via 172.30.32.1 dev eth0
adding route to local network 192.168.178.0/16 via 172.30.32.1 dev eth0
Error: Invalid prefix for given prefix length.

**Full addon config**

**System**

- Supervisor version: latest
- Host system version:  latest

**Comment by novisys** [comment]
solved 👍  by changing :     
"LOCAL_NETWORK": "192.168.178.0/16", to     "LOCAL_NETWORK": "192.168.178.0/24",

**Comment by alexbelgium** [comment]
Thanks!
