### ISSUE TITLE
🐛 [Jacket] Not starting

### ISSUE THREAD

**Issue by shostko** [alexbelgium/hassio-addons#547]
**Which addon?**

- Addon name : Jackett NAS
- Addon version : 0.20.2236

**Describe the bug**

Addon is not started after installation.

The only page I found relevant is https://community.home-assistant.io/t/exec-fatal-unable-to-exec-bashio-no-such-file-or-directory/214752

**To Reproduce**

1. Install addone
2. Start addone
3. Open Log tab
4. See error log

**Full addon log**

`exec: fatal: unable to exec bashio: No such file or directory`

**Full addon config**

```
PGID: 0
PUID: 0
```

**System**

Home Assistant 2022.10.5
Supervisor 2022.10.2
Frontend 20221010.0
Raspbian on Rasberry Pi 4B

**Comment by alexbelgium** [comment]
Hi, that's because if you don't use HAos it sometime occurs. Normally I have a script to prevent that, I'll check it

**Comment by alexbelgium** [comment]
Could you please post your log when starting? Bashio should be installed at that moment in your configuration based on script 00-aaa_dockerfile_backup.sh

**Comment by shostko** [comment]
@alexbelgium this is the only line in Log tab of the addon:
![image](https://user-images.githubusercontent.com/1906638/201601214-9be0e97b-69a9-49e0-b950-2cdff980ea8e.png)
and the only one in the Logs screen in Settings>System
![image](https://user-images.githubusercontent.com/1906638/201601496-5bc3ba06-f0eb-4321-b334-14334ee48bdf.png)
and the only one log in Supervisor section:
```
22-11-14 10:34:32 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on db21ed7f/armv7-addon-jackett_nas with version 0.20.2236
```

**Comment by alexbelgium** [comment]
Thanks, really strange it starts fine for me. Actually once this supervisor PR is deployed (I suppose in version 2022-11) I will provide pre-build images that will avoid this : https://github.com/home-assistant/supervisor/issues/3414#event-7732125083

**Comment by shostko** [comment]
thanks @alexbelgium. hope that will work

btw have you checked line ending symbols in the scripts?

**Comment by alexbelgium** [comment]
What I don't understand is that the entrypoint should be though the s6 supervisor. On my system, I see the init scripts executing long before it comes to my own script containing bashio... How would you suggest that I look for line ending symbols? Thanks

**Comment by shostko** [comment]
I was thinking if your sh scripts have incorrect line endings, but just checked - they are already in Unix format

**Comment by alexbelgium** [comment]
Hi, could you please refresh the repo and try installing again

**Comment by shostko** [comment]
@alexbelgium unfirtunatelly issue still remains. with same log

**Comment by alexbelgium** [comment]
OK, solved and tested!

**Comment by alexbelgium** [comment]
Or too much enthusiasm. On which supervisor version are you?

**Comment by shostko** [comment]
hey @alexbelgium thanks
I have now `Supervisor 2022.11.2` and looks like addon now works fine!

**Comment by alexbelgium** [comment]
Double great news, thanks! The supervisor version means I can start deploying pre built versions. Have a nice day
