### ISSUE TITLE
[Meailie] How to update to the latest version?

### ISSUE THREAD

**Issue by remb0** [alexbelgium/hassio-addons#548]
**Maelie**

name: Question
in the addon I got the following message in the settings:   Your current version (v1.0.0beta-3) does not match the latest release. Considering updating to the latest version (v1.0.0beta-5).
Is it possible to update the addon to this latest version?

**Comment by alexbelgium** [comment]
Hi, sorry I can't : I'm using this dockerhub image which wasn't updated yet : https://hub.docker.com/r/hendrix04/mealie-combined

**Comment by remb0** [comment]
Aha I understand.  thank you very much for your work and answer.

**Comment by alexbelgium** [comment]
An alternative is that I build two addons for api and front end

**Comment by remb0** [comment]
That would be awesome!  I tested tandoor but mealy is easier and better. but that changes in the last betas are enormous.
I will test it for sure when it is published.

> An alternative is that I build two addons for api and front end

**Comment by remb0** [comment]
I see you did, can you let me know when its ready for testing?

**Comment by alexbelgium** [comment]
Should be ready! I'll test it tomorrow

**Comment by alexbelgium** [comment]
Could you please try a backup and restore from the current Addon? They are separate so there is no link between the previous and new one. You can even keep both in parallel for the time being if you prefer

**Comment by alexbelgium** [comment]
It looks like it's working. You need to wait a couple minutes for the app to launch.

**Comment by alexbelgium** [comment]
Upgrade how to : https://github.com/alexbelgium/hassio-addons/blob/master/mealie/README.md

**Comment by remb0** [comment]
I tested it besides each other and it works perfect.    the config files must be in the api folder and it works perfect.

but import from the old addon doesn't work because of a schema difference.
and importing pictures also not work I think because of:
in settings: 
Docker Volume:  Volumes are misconfigured.

**Comment by alexbelgium** [comment]
What do you mean schema difference? This should be perfectly compatible in theory as based on official images?

**Comment by remb0** [comment]
from the obsolete addon i made a backup.
uploaded it to the new frontend.
and tried to restore but got a message:  database backup schema version does not match current database

I don't think its a problem from the addon but from mealie itselsf.
the docket volume message is an addon problem i think

**Comment by alexbelgium** [comment]
Indeed... https://github.com/hay-kot/mealie/issues/1844 now this is quite complex for users to manage...

**Comment by remb0** [comment]
No problem for me. 
When the docker volume is fixed in the addon I will import the recieps manually (because when I do right now, it can't write the images to the folder.  and a recipe without picture is not handy ;)
