### ISSUE TITLE
🐛 [Qbittorrent] init-qbittorrent-config fails to start on homassistantOS

### ISSUE THREAD

**Issue by RandomUsernameThatIsNotYetTaken** [alexbelgium/hassio-addons#552]
**Which addon?**

- Addon name : Qbittorrent
- Addon version : 4.4.5-r3-ls229

First time installing the qbittorrent addon, throws an error with required files not being found.
I initially assumed this has to do with HomeassistantOS not having included the necessary files, 
however, it seems we're already inside the container at this point:

`/etc/s6-overlay/s6-rc.d/init-qbittorrent-config/run: line 19: /usr/bin/lsiown: cannot execute: required file not found
`

**To Reproduce**

1. Download addon from repository
2.  Try to start addon
3.  Addon shows as started, but webui is unavailable
4.  Check status, addon has stopped
5.  Check logs for error.

**Full addon log**

`[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
 Add-on version: 4.4.5-r3-ls229
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-folders.sh
cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/30-nginx.sh
cont-init: info: /etc/cont-init.d/30-nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/90-dns_set.sh
[14:58:00] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 0
cont-init: info: running /etc/cont-init.d/91-qbittorrent_configuration.sh
sed: no previous regexp
[14:58:00] INFO: Downloads can be found in /share/qBittorrent
[14:58:01] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[14:58:01] INFO: WEBUI username set to admin
[14:58:01] INFO: Default username/password : admin/adminadmin
[14:58:01] INFO: Configuration can be found in /config/addons_config/qBittorrent
cont-init: info: /etc/cont-init.d/91-qbittorrent_configuration.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-openvpn.sh
[14:58:01] INFO: Direct connection without VPN enabled
cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 0
/etc/s6-overlay/s6-rc.d/init-qbittorrent-config/run: line 19: /usr/bin/lsiown: cannot execute: required file not found
s6-rc: warning: unable to start service init-qbittorrent-config: command exited 127
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.`

**Full addon config**

`[AutoRun]
enabled=false
program=

[LegalNotice]
Accepted=true

[Preferences]
WebUI\Username=admin
WebUI\AuthSubnetWhitelist=localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\Address=*
WebUI\HostHeaderValidation=false
WebUI\ClickjackingProtection=false
WebUI\CSRFProtection=false
WebUI\Address=*
WebUI\Address=*
WebUI\Address=*
WebUI\Address=*
WebUI\Address=*
WebUI\Address=*
Connection\UPnP=false
Connection\PortRangeMin=59595
Downloads\SavePath=/share/qBittorrent
Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\0)
Downloads\TempPath=/share/qBittorrentincomplete/
WebUI\Address=*
WebUI\ServerDomains=*
WebUI\LocalHostAuth=false
`
**System**

Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

- Supervisor version: 2022.10.2
- Host system version: Operating System 9.3

**Comment by RandomUsernameThatIsNotYetTaken** [comment]
I think i included all relevant info.

Trying to get a headstart by going through the container image myself.
Let me know if you need anything else in the meantime.

**Comment by alexbelgium** [comment]
Hi, looks like linuxserver updated their code without updating their dependencies. Not sure how to solve that for the moment

**Comment by RandomUsernameThatIsNotYetTaken** [comment]
Damn you're fast :)

Yep, seems like the issue comes frome here? https://github.com/linuxserver/docker-qbittorrent/pull/200
https://github.com/linuxserver/docker-qbittorrent/commit/65621a9ba3e87a20cdb426ce25654715a91ff42b

Wait for an upstream fix or reference an older base -image?

**Comment by alexbelgium** [comment]
Hi, new version pushed to solve this

**Comment by RandomUsernameThatIsNotYetTaken** [comment]
Can confirm, works now!

Merci

**Comment by alexbelgium** [comment]
Thanks!
