### ISSUE TITLE
[Nextcloud] Preview Generator

### ISSUE THREAD

**Issue by arievanoosten** [alexbelgium/hassio-addons#553]
I'm trying to see the app preview generator working but I can't.  The documentation says to add something to /var/www/nextcloud/occ .  I just can't find that file with file editor.  I hope you can help me further

**Comment by alexbelgium** [comment]
You can use portainer to access a console inside a container. Or else I've pushed a new version that checks if a custom script exists, then executes it if the file exists. That might be your solution :-)

**Comment by arievanoosten** [comment]
thanks for the tip.  this is how i got on.

**Comment by alexbelgium** [comment]
Great to know! I'll close that then if it works for you. Enjoy
