### ISSUE TITLE
🐛 [plex] issue with networkdisks

### ISSUE THREAD

**Issue by bilak** [alexbelgium/hassio-addons#554]
**plex**

- Addon name : plex
- Add-on version: 1.29.2.6364-6d72b0cf6-ls143
- System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
- Home Assistant Core: 2022.11.2
- Home Assistant Supervisor: 2022.10.2

I'm trying to setup the plex server however I don't want to provide `networkdisks` while I have enough space in HA itself. When I try to remove the value of `networkdisks` from configuration tab and then I hit `save` button the default value is returned back. So currently there is no easy way how to run plugin without configuring `networkdisks` properly. I even tried to put there empty space, but it failed again. 

```
The structure of your "networkdisks" option : "//server/share" doesn't seem correct, please use a structure like //123.12.12.12/sharedfolder,//123.12.12.12/sharedfolder2. If you don't use it, you can simply remove the text, this will avoid this error message in the future.
```

**Comment by alexbelgium** [comment]
Hi, thanks I've removed the default values. If you click on reset options it should be removed
