### ISSUE TITLE
🐛 [Arpspoof] Failed to install

### ISSUE THREAD

**Issue by hrubosz** [alexbelgium/hassio-addons#555]
**Which addon?**
Arpspoof

- Addon name : Arpspoof
- Addon version : 1.0.0

**Describe the bug**
I can't install addon in home assisatant.

**To Reproduce**

1. Go to Add-On Store in HA
2. Click on 'Arpspoof'
3. Click on 'Install'
4. See error -> Failed to install add-on ->manifest unknown

**Full addon log**

**Full addon config**

**System**

- Supervisor version: 2022.10.2
- Host system version:  HassOS 9.3

**Comment by alexbelgium** [comment]
Hi, please refresh your repo and reinstall it will work now

**Comment by hrubosz** [comment]
Now it works! Many thanks!!!
