### ISSUE TITLE
[calibre/calibre-web] Add network shares with nobrl option

### ISSUE THREAD

**Issue by Fabenissimo** [alexbelgium/hassio-addons#556]
### Which addon?

Addon name : calibre/calibre-web
Addon version : v6.8.0-ls192 (14-11-2022)

### Describe the bug
When using a network share for the location of the calibre databse, calibre runs into an error and the database get's corrupted.
(Database is locked errors when trying to change to the library)
See https://coderwall.com/p/zrxobw/calibre-libraries-on-nas

--> Possible soultion in the article: Add the smb shares in the 92-smb_mounts.sh file with option `nobrl`

### To Reproduce
Install addon
Add network share that gets mounted on startup
try to create the database/library on the network share
calibre throws databse is locked error message

### Full addon log
- should be of no relevance

### Full addon config
PGID: 0
PUID: 0
TZ: Europe/Berlin
networkdisks: //my_nas_ip/calibre
cifsusername: ****
cifspassword:****
PASSWORD: ****

### System

Supervisor version: Supervisor 2022.10.2
Host system version: HassOS 9.3

**Comment by alexbelgium** [comment]
Hi, nobrl is added please let me know how that goes
