### ISSUE TITLE
[qbittorrent] Unable to log in to local web UI, but can on HA Cloud

### ISSUE THREAD

**Issue by salvadornico** [alexbelgium/hassio-addons#558]
I restarted Home Assistant earlier today, and when it had finished I noticed that the qBittorrent add-on did not automatically start. I use the default username & password, and now when I try to log in to the web UI from `homeassistant.local` I always get back 401 errors. I only know this because I checked the devtools network tab, the usual 'Login failed' notification doesn't even appear. What's strange is that when I access it from the mobile app or via Home Assistant Cloud, I'm able to log in normally using the same credentials.

Does anyone have an idea what could be going on?

**Comment by perebusquets** [comment]
Not sure if this could be related with the above error or not:

For me, when I try to load and get a blank screen, this error appears in the logs: 
`2022/11/16 19:02:23 [error] 611#611: *1 open() "/vuetorrent/public/js/975.d77c0760.js" failed (2: No such file or directory),...`

A similar 404 error appears in the web dev tools for this file, it looks like it can't find the JS bundle when loading,... Maybe an incorrect Nginx config or pointing to the wrong file path by mistake?

**Comment by salvadornico** [comment]
Did some additional investigating:
- This only happens when accessing `homeassistant.local`, regardless of the browser or device
- These are the errors in the JS console after a login attempt (Firefox & Chrome respectively) 
![image](https://user-images.githubusercontent.com/25360297/202332170-f9f79968-1422-446d-81da-156eb8cde7be.png)
![image](https://user-images.githubusercontent.com/25360297/202332352-68475b5a-1cf1-4e53-95ee-c60173efe175.png)
- I show the qBittorrent status on my dashboard, and even though I can log in via HA Cloud and start & finish a download there, the sensor always shows 'unavailable' as its status.
```
Logger: homeassistant.components.qbittorrent.sensor
Source: components/qbittorrent/sensor.py:126
Integration: qbittorrent (documentation, issues)
First occurred: 09:25:51 (30 occurrences)
Last logged: 09:30:22

Invalid authentication
```

**Comment by alexbelgium** [comment]
Thanks for the investigation! I've reverted my latest change and it works again... Not sure what occurred there... Thanks!

**Comment by salvadornico** [comment]
Working again now, even found my old session. Thanks!

**Comment by alexbelgium** [comment]
Thanks!
