### ISSUE TITLE
Can't mount sdd1 and sde1 since Emby 4.7.0.10

### ISSUE THREAD

**Issue by Alexisc21** [alexbelgium/hassio-addons#56]
Hi,
Since the update to version 4.7.0.10 of emby I can no longer mount my sdd1 or sde1 disks.
I observe the same behavior on all your addons that I recently updated.

`[15:08:23] INFO: Mounting local hdd...
[15:08:24] INFO: Local Disks mounting.. sda1, sdb1, sdd1, sde1
[15:08:24] INFO: Mount sda1
[15:08:24] INFO: Success!
[15:08:24] INFO: Mount sdb1
[15:08:24] INFO: Success!
[15:08:24] INFO: Mount sdd1
mount: permission denied (are you root?)
[15:08:24] INFO: Mount sde1
mount: permission denied (are you root?)`

I noticed that you changed things in config.json going from this : 
`],
  "devices": [
    "/dev/ttyUSB0",
    "/dev/*",
    "/dev/sda1"`

to that :
`],
  "devices": [
    "/dev/sda1",
    "/dev/sda2",
    "/dev/sdb1",
    "/dev/sdb2"`

Could it be linked?

Thanks in advance.

**Comment by alexbelgium** [comment]
Thanks! Great troubleshooting. I'll udpate and push a new version in 1 min let me know if it works!

**Comment by alexbelgium** [comment]
Done, If you confirm I'll realign all my addons with it. Thanks!

**Comment by Alexisc21** [comment]
I can't reach my HA for now.

I will let you know if it works as soon as possible.

**Comment by Alexisc21** [comment]
I just updated to your new version. Everything is working now 😃. 

I think you can realign your other addons.

Thank you

**Comment by alexbelgium** [comment]
Perfect, thanks!
