### ISSUE TITLE
🐛 [Ubooquity] Failed to install

### ISSUE THREAD

**Issue by etlon** [alexbelgium/hassio-addons#561]
**Which addon?**

- Addon name : Ubooquity
- Addon version : 2.1.2-10-bugfix

Describe the bug

When trying to install the addon it fails.
**To Reproduce**

Supervisor version: Supervisor 2022.10.2<br>
Host system version: HassOS 9.3
Raspberry Pi 4

**Comment by alexbelgium** [comment]
Thanks for the feedback, I've aligned to upstream changes. It would work know
