### ISSUE TITLE
🐛 [qbittorrent] unable to start service legacy-cont-init

### ISSUE THREAD

**Issue by Stooovie** [alexbelgium/hassio-addons#562]
Lately the qbittorrent add on stopped working on my system. From its log:

`cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container. `

**### Addon version:**
4.4.5-r3-ls229-4

**### Home Assistant version**
2022.11.3 HAOS running on Rpi4

### **### Entire log**

`[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
 Add-on version: 4.4.5-r3-ls229-4
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-folders.sh
cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[08:45:54] INFO: Execute /config/qbittorrent.sh if existing
[08:45:54] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/30-nginx.sh
cont-init: info: /etc/cont-init.d/30-nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/90-dns_set.sh
[08:45:58] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 0
cont-init: info: running /etc/cont-init.d/91-qbittorrent_configuration.sh
[08:45:58] INFO: Downloads can be found in /mnt/Public/Downloads
[08:45:59] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[08:45:59] INFO: WEBUI username set to stooovie
[08:46:00] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
[08:46:02] INFO: Default username/password : admin/adminadmin
[08:46:02] INFO: Configuration can be found in /config/addons_config/qBittorrent
cont-init: info: /etc/cont-init.d/91-qbittorrent_configuration.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
Mounting smb share(s)...
Using PUID 0 and PGID 0
[08:46:04] INFO: ... //192.168.0.216/Public successfully mounted to /mnt/Public with options 
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-openvpn.sh
[08:46:04] INFO: Configuring openvpn
[08:46:05] INFO: openvpn correctly set, qbittorrent will run tunnelled through openvpn
Using interface binding in the qBittorrent app
/etc/cont-init.d/93-openvpn.sh: line 72: cd: /config/addons_config/qbittorrent/: No such file or directory
cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 1
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container. `

**Comment by alexbelgium** [comment]
Hi, thanks for reporting, solved in new version

**Comment by Stooovie** [comment]
Started to get the same thing today with qb 4.5.5 and HA 2023.10.5: 
`s6-rc: warning: unable to start service legacy-cont-init: command exited 1
`
I have made absolutely no changes to anything.

**Comment by Stooovie** [comment]
Here's more: 

`option
[14:21:24] INFO: Default username/password : admin/adminadmin
[14:21:24] INFO: Configuration can be found in /config/addons_config/qBittorrent
[14:21:24] INFO: Configuring openvpn
[14:21:24] INFO: openvpn correctly set, qbittorrent will run tunnelled through openvpn
Using interface binding in the qBittorrent app
... deleting previous interface settings
... binding tun0 interface in qBittorrent configuration
/etc/cont-init.d/93-openvpn.sh: line 89: 11
44: syntax error in expression (error token is "44")
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container. `


It shouldn't be an issue with ovpn (Mullvad), I checked and I have 15 days left.

**Comment by alexbelgium** [comment]
I can replicate, I'll check

**Comment by alexbelgium** [comment]
Ok fixed in this version

**Comment by Stooovie** [comment]
Fantastic, working, thanks!
