### ISSUE TITLE
🐛 [Overseerr] can't set user/group ID

### ISSUE THREAD

**Issue by Test-subj** [alexbelgium/hassio-addons#563]
**Which addon?**

- Addon name : Overseer
- Addon version :1.30.1

**Describe the bug**

**To Reproduce**

1. Go to the configuration screen
2. Click on Edit in yaml
3. Add PGID: xxxx and PUID:xxxx
4. Start addon
5. Look at log
I've tried adding it through the addon config page, the file that the config page edits (/usr/share/hassio/addons/data/xxxxxxxx
_
overseerr) and the downloaded config in /usr/share/hassio/addons/git/xxxxxxxx/overseerr. 
None of them pass the proper uid/gid

**Full addon log**

"[custom-init] No custom services found, skipping...
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/00-aaa_dockerfile_backup.sh exited 0
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Overseerr
 Request management and media discovery tool built to work with your existing Plex ecosystem
-----------------------------------------------------------
 Add-on version: 1.30.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.11.dev0802
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-config_location.sh
[13:50:54] INFO: Config stored in /config/
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Overseerr Github Sponsors: https://github.com/sponsors/sct
Overseerr Patreon: https://patreon.com/overseerr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
cont-init: info: /etc/cont-init.d/00-config_location.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[13:50:59] INFO: Execute if existing custom script /config/overseerr.sh
[13:50:59] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh"

**Full addon config**
CONFIG_LOCATION: /config/
TZ: XXXX
GID: XXXX
UID: XXXX

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Please try this new version

**Comment by Test-subj** [comment]
Fixed.
Thank you for making this migration less painless.

**Comment by alexbelgium** [comment]
Thanks
