### ISSUE TITLE
✨ [REQUEST] immich (Google photo alternative) 

### ISSUE THREAD

**Issue by idarius** [alexbelgium/hassio-addons#573]
Hi, if someone has the time and motivation to port Immich  into a home assistant addon, it would be really kind. 

https://github.com/immich-app/immich

Its a Google photo alternative, and a really active project. 

I Could install it with docker compose or portainer, but it would tag my ha install unsupported. 

Thx a lot !

**Comment by mikedrawback** [comment]
I vote for this as well!

**Comment by kuduacz** [comment]
vote for it too

**Comment by alexbelgium** [comment]
Hi, there seems to be 4 different containers required to run it... https://raw.githubusercontent.com/immich-app/immich/main/docker/docker-compose.yml If you can find an omni container which incorporates everything I'll create the Addon!

**Comment by alexbelgium** [comment]
There is already a request for that here : https://github.com/immich-app/immich/issues/84

**Comment by mikedrawback** [comment]
It doesn't look like they plan to support it anytime soon. I also have to use a separate container for the machine learning since my CPU doesn't support AVX. [https://github.com/bertmelis/immich-machine-learning-no-avx](https://github.com/bertmelis/immich-machine-learning-no-avx)

**Comment by alexbelgium** [comment]
Actually I, as building it for the moment with : https://github.com/martabal/docker-immich

**Comment by alexbelgium** [comment]
Current action list :
[ ] Photos not remanent (to change)
[ ] Need feedback on usage of external database

**Comment by idarius** [comment]
thanks you ! i will try this weekend :)

**Comment by alexbelgium** [comment]
@mikedrawback : either me or someone else can also implement an option to add the specific libraries you were linking to

**Comment by alexbelgium** [comment]
Latest version of the container doesn't work, I'll pin a version

**Comment by MartB** [comment]
Nice work so far 💪 

Im looking forward to switch from Photoprism, but I need the API to work for bulk image uploading. Fingers crossed that the new container with v1.41 wont be a pain to support!

**Comment by alexbelgium** [comment]
Well v1.41 is not working, I reverted to v1.40 ;-) Other than that it seems fine but indeed it would need deeper usage to check

**Comment by cybuletz** [comment]
great addon but consumes RAM just like Chrome
