### ISSUE TITLE
🐛 [Nextcloud] New files not visible after restore full backup hassio

### ISSUE THREAD

**Issue by arievanoosten** [alexbelgium/hassio-addons#576]
After restoring a full hassio backup, the files that have been uploaded to nc in the meantime are no longer visible. I can see them in the folder via an ssh command. Is there a solution to make them visible again in nc?

**Comment by alexbelgium** [comment]
Hi, no idea, you should check nextcloud documentation of contact them... As I see it you restored the files but not the database in which they were already imported. I guess there is a scan function in nextcloud but I don't know and use the app

**Comment by arievanoosten** [comment]
thanks for putting me on the right track. via the following command in the addon portainer console it worked:
sudo -u abc php /data/config/www/nextcloud/occ files:scan --all

**Comment by alexbelgium** [comment]
Great to know it's solved. Have a nice day
