### ISSUE TITLE
Images are not deleted

### ISSUE THREAD

**Issue by almico** [alexbelgium/hassio-addons#58]
I am testing your Jackett hassio-addon and, after some upgrades, I noticed that there are multiple unused images left in the system:
![image](https://user-images.githubusercontent.com/15247405/136650374-c9fc005e-6b20-4cfd-a600-4dbed3988df2.png)

Is this normal?
Is it something that could be addressed to automatically delete old images?
Can I manually remove unused images?

P.S.: the same happens for your Sonarr too.

**Comment by alexbelgium** [comment]
The issue has been escalated to HA github. I'll close it here
