### ISSUE TITLE
✨ [REQUEST] browserless-chrome

### ISSUE THREAD

**Issue by shirou93** [alexbelgium/hassio-addons#580]
browserless-chrome

Can you add "https://hub.docker.com/r/browserless/chrome" as addon?
This addon not require special volumes etc. This app will helpfull to use selenium in localhost.
In documentation to run it enough one commend 'docker run -p 3000:3000 browserless/chrome'

Thank you for your work.

**Comment by alexbelgium** [comment]
Hi, you could use webtop_kde also for the same purpose

**Comment by shirou93** [comment]
Hi, webtop can expose webdriver for scripts? On browserless-chrome i put only http://127.0.0.1:3000/webdriver to selenium python script and no require additional config.

**Comment by alexbelgium** [comment]
And here it is : https://github.com/alexbelgium/hassio-addons/tree/master/browserless_chrome

**Comment by shirou93** [comment]
> And here it is : https://github.com/alexbelgium/hassio-addons/tree/master/browserless_chrome

Thanks a lot. When will be visible on repository. Current update check not add this app to list.

**Comment by alexbelgium** [comment]
Just refresh your repo or wait for it to refresh automatically. Currently I didn't activate any custom env variables but this can be done if needed
