### ISSUE TITLE
🐛Enedisgateway2mqtt token_bad_formatted

### ISSUE THREAD

**Issue by data-source** [alexbelgium/hassio-addons#582]
**Description du bug**
DEBUG : {'error_code': True, 'detail': {'message': {'error': 'token_bad_formatted', 'description': 'Ton token est mal formaté.', 'alert_user': True}}}

Impossible de faire passer le token. 4 nouveaux tokens générés, ' ou " pareil, nouveau fichier de conf tout neuf, conversions, validations yaml en ligne, rien n'y fait. 

J'ai un autre message d'erreur sur le debug log: 
/usr/local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

NB: La conf fonctionnait et j'ai bien un résultat via d'autres méthodes. 
J'ai aussi consulté https://github.com/alexbelgium/hassio-addons/issues/84 mais ca ne change rien

cycle: 86400
debug: true
enedis_gateway:
  "148775123456705":
    token: "1E0fBJPJNDFIDYFGISYFDGS-LyOZSbPNPxB6OH4g="
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.18971
    #consumption_price_hc: 0
    #consumption_price_hp: 0.157
    #offpeak_hours: null
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
home_assistant:
  card_myenedis: true

**Type d'installation**
HassIO 

**Version : 0.7.7-3*

**Comment by alexbelgium** [comment]
En effet, il semble que l'application n'existe plus et a été migrée vers une nouvelle : https://github.com/m4dm4rtig4n/myelectricaldata

Je vais faire de même ici

**Comment by alexbelgium** [comment]
Est-ce que tout fonctionne après la migration?

**Comment by m4dm4rtig4n** [comment]
@data-source , Attention, la nouvelle version à switch de passerelle pour les consentements :
=> https://myelectricaldata.fr
