### ISSUE TITLE
✨ [REQUEST] filebrowser - block direct access

### ISSUE THREAD

**Issue by pabloalcantara** [alexbelgium/hassio-addons#583]
!!! I have a real life job in parallel to this addon, and don't think I'll be able to add new addons for the moment. You can still however express your interest in case someone would do it

**Which addon?**

filebrowser

**Is your feature request related to a problem? Please describe.**

request: It´s possible to block, or at least an option, to block direct access fo filebrowser outside Hassio?
In your browser, if you use the IP of hassio and the TCP port for the filebrowser, anyone can access it without password.
I have even tryed to put an password, but filebrowser response was: "Forbidden You don't have permission to access this resource."

- An option to Block direct TCP access to filebrowser port, and only permits from inside of hassio
- 

**Additional context**

**Comment by pabloalcantara** [comment]
Thanks.
My bad.

**Comment by pabloalcantara** [comment]
Out empty resolve this

**Comment by alexbelgium** [comment]
Happy it worked ! And writing it will allow people to solve it also. Actually you're right i'll disable external access by default as a safety measure
