### ISSUE TITLE
🐛 [Emby NAS] showing wrong version and asking for upgrade.

### ISSUE THREAD

**Issue by rqmartins73** [alexbelgium/hassio-addons#586]
**Which addon?**

Emby NAS

- Addon name : Emby NAS
- Addon version : 4.8.0

**Describe the bug**

Good morning,

I have an issue with the Emby NAS.
I have Emby NAS version 4.8.0.19 installed on Home Assistant OS, but when I open the App on any device (windows, android, etc) it shows that it is at version 4.8.0.12 beta and telling to shut down and install the most recent version.

I have rebooted Home Assistant more than once already, I even deleted the add-on from Home Assistant and installed again, but it didn't change nothing.

I did some search but didn't find any info about this issue. It's this a known bug?

Thanks in advance.
Regards.

**System**

- Supervisor version: 2022.11.2
- Host system version: 9.3

![Emby dashboard](https://user-images.githubusercontent.com/83714215/205046407-9f499baf-1fa1-4d6b-b7e1-2e7ed2b50db1.png)
![Emby NAS](https://user-images.githubusercontent.com/83714215/205046410-84757401-94fe-4b9b-8d15-5f7ef5c44c0b.png)

**Comment by alexbelgium** [comment]
Thanks very much, you are right indeed. I've updated the version
