### ISSUE TITLE
🐛 [Photoprism] Ingress not working

### ISSUE THREAD

**Issue by Taxxian** [alexbelgium/hassio-addons#589]
**Which addon?**

- Addon name : **Photoprism**
- Addon version : Current version: 20220121-3

When I click on Photoprism on the Sidebar the called URL is:

.../db21ed7f_photoprism/dashboard

which seems correct. But the Browser returns only

404: Not Found

This happens localy via ip address and via Nabu Casa link.

I can access the addon via IP adress and port, but I want to access it via Nabu Casa.

**To Reproduce**

1. Install Photoprism
2. Configure and click Show on Sidebar
3. Click on Sidbar Icon

**Full addon log**

Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Photoprism
 A server-based application for browsing, organizing and sharing your personal photo collection
-----------------------------------------------------------
 Add-on version: 20220121-3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.11.5
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[14:49:14] INFO: Execute /config/photoprism.sh if existing
[14:49:14] INFO: ... no script found
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/32-nginx_ssl.sh: executing
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/photoprism/config.yaml
Config file is a valid yaml
[14:49:16] INFO: Starting the app with the variables in /config/addons_config/photoprism/config.yaml
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
Mounting smb share(s)...
touch: cannot touch '/mnt/-=Bilder=-/testaze': Permission denied
[14:49:17] FATAL: Disk is mounted, however unable to write in the shared disk. Please check UID/GID for permissions, and if the share is rw
touch: cannot touch '/mnt/-=Bilder=-/testaze': Permission denied
[14:49:17] WARNING: noserverino option used
/etc/cont-init.d/99-run.sh: executing
[14:49:17] INFO: Defining database
[14:49:17] INFO: Using MariaDB addon. Requirements : running MariaDB addon. Discovering values...
PHOTOPRISM_DATABASE_DRIVER=mysql
PHOTOPRISM_DATABASE_SERVER=core-mariadb:3306
PHOTOPRISM_DATABASE_NAME=photoprism
PHOTOPRISM_DATABASE_USER=service
PHOTOPRISM_DATABASE_PASSWORD=******************************************************************
[14:49:18] WARNING: Webtrees is using the Maria DB addon
[14:49:18] WARNING: Please ensure this is included in your backups
[14:49:18] WARNING: Uninstalling the MariaDB addon will remove any data
touch: cannot touch '/mnt/-=Bilder=-/aze': Permission denied
[14:49:18] FATAL: /mnt/-=Bilder=- path is not writable
[14:49:18] INFO: Please wait 1 or 2 minutes to allow the server to load
[14:49:18] INFO: Default username : admin, default password: "please_change_password"
[14:49:18] INFO: Starting, please wait for next green text...
started 221118-jammy as root (amd64-prod)
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /share/photoprism/storage
config path...: default
cache path....: default
backup path...: /share/photoprism/backup
import path...: /share/photoprism/import
originals path: /mnt/-=Bilder=-
running as uid 0
photoprism start
time="2022-12-02T14:49:24+01:00" level=info msg="PhotoPrism® needs your support!"
time="2022-12-02T14:49:24+01:00" level=info msg="Visit https://photoprism.app/membership to learn more."
time="2022-12-02T14:49:24+01:00" level=info msg="migrate: executing pre migrations"
time="2022-12-02T14:49:24+01:00" level=info msg="migrate: executing main migrations"
time="2022-12-02T14:49:25+01:00" level=info msg="config: read-only mode enabled"
time="2022-12-02T14:49:25+01:00" level=info msg="webdav: server disabled"
time="2022-12-02T14:49:25+01:00" level=info msg="server: tls disabled"
time="2022-12-02T14:49:25+01:00" level=info msg="server: listening on 0.0.0.0:2341 [2.225621ms]"
[14:49:25] INFO: App launched

**Full addon config**

BACKUP_PATH: /share/photoprism/backup
CONFIG_LOCATION: /config/addons_config/photoprism/config.yaml
DB_TYPE: mariadb_addon
IMPORT_PATH: /share/photoprism/import
ORIGINALS_PATH: /mnt/-=Bilder=-
STORAGE_PATH: /share/photoprism/storage
UPLOAD_NSFW: "true"
certfile: fullchain.pem
keyfile: privkey.pem
ssl: false
cifspassword: *******************************
cifsusername: HA
networkdisks: //192.168.2.11/Sternendaten/-=Bilder=-

**System**

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest
Generic x64 now, but using my old RaspPi4 I had the same result.

**Comment by alexbelgium** [comment]
Hi, thanks. It's the same issue as https://github.com/alexbelgium/hassio-addons/issues/588

I'll check

**Comment by alexbelgium** [comment]
Alas photoprism has updated its app in a way that seems incompatible with ingress. No promises of fix.

**Comment by Taxxian** [comment]
In docker compose you can use 

PHOTOPRISM_HTTP_COMPRESSION | --http-compression |   | Web server compression METHOD (none or gzip)

Explained here: https://docs.photoprism.app/getting-started/config-options/

Hope that will help^^

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version that works on my system. The only impact is that the direct access url is modified, but I've implemented an automatic redirect to make this smoother.

**Comment by Taxxian** [comment]
Works great :-)

**Comment by alexbelgium** [comment]
Thanks for the feedback!

**Comment by alexbelgium** [comment]
I'll close then as Ingress works fine. Enjoy
