### ISSUE TITLE
Any plan to add Lidarr too?

### ISSUE THREAD

**Issue by almico** [alexbelgium/hassio-addons#59]
I was wondering why Lidarr was missing from your repository and if you could consider adding it 😃

**Comment by almico** [comment]
Sure! Tell me what to do 😃

**Comment by alexbelgium** [comment]
It seems to start :) just refresh your repositories, and it should appear!

**Comment by almico** [comment]
I cleared this field:
![image](https://user-images.githubusercontent.com/15247405/136660314-c4db90c7-9c8d-4885-982b-929f9cd15ff4.png)
But, pressing SAVE, it was reset to the content you see now.
I think that generates a FAILURE on addon startup.

**Comment by alexbelgium** [comment]
Thanks for reporting! For networjdisks, that failure does not prevent execution but it's not clean. I've updated the code to remove the failure even if the default setting is kept

Indeed I'll also solve the downloads folder. 

Appart from those, is the addon working as expected?

**Comment by almico** [comment]
I'm looking around right now 😃

**Comment by almico** [comment]
I think this issue deserves to be closed 🤣

**Comment by diamant-x** [comment]
Lovely work here, thanks!
I came across this 'extension' of lidarr, which build source lidar + adds some complements to auto-download from tidal and deezer and videos from youtube.
https://github.com/RandomNinjaAtk/docker-lidarr-extended
not sure how much of an "easy" thing would it be to adapt. Hopefully by setting
-e enableAudioScript=false
-e enableVideoScript=false
by default it would avoid regression impact for existing addon users.

Open for thoughts! Thanks!

**Comment by trashcatt** [comment]
> Lovely work here, thanks! I came across this 'extension' of lidarr, which build source lidar + adds some complements to auto-download from tidal and deezer and videos from youtube. https://github.com/RandomNinjaAtk/docker-lidarr-extended not sure how much of an "easy" thing would it be to adapt. Hopefully by setting -e enableAudioScript=false -e enableVideoScript=false by default it would avoid regression impact for existing addon users.
> 
> Open for thoughts! Thanks!

I'd love to see this added too.
