### ISSUE TITLE
✨ [REQUEST] LocalDisks for Unpackerr

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#590]
Unpackerr

**Is your feature request related to a problem? Please describe.**

Is there any way to have it that Unpackerr monitors a folder on a localdisk instead of being limited to the 'share' drive?
(I have 3 other drives I'm using for Emby and qBittorrent so would like to have Unpacker look at one of those as they're much larger in size)

**Comment by alexbelgium** [comment]
Thanks, and now?

**Comment by hacshacdgacs** [comment]
Now it works perfectly, thank you.

**Comment by alexbelgium** [comment]
Great, thanks for the feedback enjoy
