### ISSUE TITLE
🐛 [Photoprism] test WebDAV

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#596]
See https://github.com/alexbelgium/hassio-addons/commit/ec5ea6c127e4886dd87d05df0ccc8e0a8556418f?notification_referrer_id=NT_kwDOAqIdGbM1MDAwODMyNDY3OjQ0MTc4NzEz

**Comment by kuduacz** [comment]
On latest version of all reach error method not allowed.
How to fix IT?
