### ISSUE TITLE
✨ [REQUEST] Jellyfin mount web folder to addons_config/jellyfin

### ISSUE THREAD

**Issue by Martrijn** [alexbelgium/hassio-addons#602]
**Which addon?**
Jellyfin

**Is your feature request related to a problem? Please describe.**
I think so. I wanted to add a custom link to the sidebar of jellyfin. They added a configuration option for that in Jellyfin 10.8 but to add it you need to edit the config.json file in the webroot. I could not find that file in the addons_config/jellyfin folder. See here: https://jellyfin.org/docs/general/clients/web-config/

**Describe the solution you'd like**
mount the /usr/share/jellyfin/web/ folder to addons_config/jellyfin i guess?

**Describe alternatives you've considered**
none

**Additional context**

**Comment by alexbelgium** [comment]
Hi, not sure about the benefit but I've pushed it :-)

**Comment by deejbee** [comment]
The server doesn't start after upgrading to this version:
```[15:08:43] [ERR] [1] Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /config/addons_config/jellyfin/web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings.
[15:08:43] [INF] [2] Main: Received a SIGTERM signal, shutting down

**Comment by Martrijn** [comment]
Thank you for pushing this update :) ! It works but it makes a web directory in the web directory causing the error above.

**Comment by alexbelgium** [comment]
Thanks, my mistake. I've corrected the cp command as you proposed and pushed a new version
