### ISSUE TITLE
✨ [REQUEST] guacamole - ingress functionality

### ISSUE THREAD

**Issue by 0bimaster** [alexbelgium/hassio-addons#603]
!!! I have a real life job in parallel to this addon, and don't think I'll be able to add new addons for the moment. You can still however express your interest in case someone would do it

**Which addon?**

guacamole

**Is your feature request related to a problem? Please describe.**

Currently the addon is only usable either locally or remotely by using port forwarding. It would be nice if the addon would support Home Assistant's integrated ingress functionality to use it seamlessly from remote.

\*\*If a new addon, have you checked on Google that such as addon doesn't already exists?

**Describe the solution you'd like**

Usage of Home Assistant's ingress functionality for this addon
**Describe alternatives you've considered**

Forwarding the port on my router to allow external access

**Additional context**

Home Assistant Ingress: https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/

**Comment by RaptorPR443** [comment]
Hello,
if you do not want to port forward, install Tailscale Addon in HA. Set the VPN Server and enable Subnet access in it. you can then remotely log in with the vpn tunnel from whatever devices you want and access your whole LAN without exposing ports to the internet or forwarding them.

**Comment by alexbelgium** [comment]
Just pushed!

**Comment by 0bimaster** [comment]
Hi Alex!

I just tested it out and it works like a charm! Thanks so much, i appreciate your effort! :)
