### ISSUE TITLE
✨ [REQUEST] MyElectricalData

### ISSUE THREAD

**Issue by m4dm4rtig4n** [alexbelgium/hassio-addons#605]
Hello @alexbelgium , 

Depuis la version 0.8.X de MyElectricalData, le conteneur Docker posséde un interface sur le port 5000.

Est-ce que tu as sais faire en sorte d'exposer le portail via l'addon stp ?

**Comment by alexbelgium** [comment]
Hello, voici une nouvelle version avec la modif
