### ISSUE TITLE
🐛 [Mealie] Incomplete?

### ISSUE THREAD

**Issue by chicknlil** [alexbelgium/hassio-addons#606]
Mealie

- Addon name : Mealie
- Addon version : 1.0.0.1-2

**Describe the bug**

Looking at the demo for Mealie on [their site](https://demo.mealie.io/), there appears to be several features missing from this version of Mealie, for example, the Meal Planner and Shopping Lists.

**System**

- Supervisor version:  Supervisor 2022.12.0
- Host system version:  Home Assistant 2022.12.6

Thanks for making this accessible; it's just at the moment I see no way to integrate the meals (or eventual meal plans) into my HA instance!

**Comment by alexbelgium** [comment]
Hi, on which architecture are you? Currently only amd64 supports the latest and nicest version...

Regarding home assistant they have a page on integration here : https://hay-kot.github.io/mealie/documentation/community-guide/home-assistant/

**Comment by chicknlil** [comment]
I have an ODROID-N2+. That makes a difference even though this was installed as an add-on, not as a docker container? The addon version says it's 1.0.0.1-2. So what are you trying to tell me my *actual* addon version is?

**Comment by chicknlil** [comment]
It appears it's 0.5.6. According to that post you linked, there should be SOME sort of meal plan functionality as of 0.4.1, but I'm not seeing it.

**Comment by alexbelgium** [comment]
I'll discontinue the current Addon and instead push the official version with separate addons for api and frontend

**Comment by chicknlil** [comment]
Stupid questions from me, then.  Does that mean the official version would work for me? And if so, am I understanding correctly that I would need to export my current recipes since 1.0 isn't backwards compatible?

I did eventually find meal plan, but it wasn't anywhere where you'd normally think to look. I don't even remember at this point how I stumbled on it, but I wasn't actively looking for it!

**Comment by alexbelgium** [comment]
Hi, indeed once the new version will be there you'll have to do a full backup in the current one and restore in the new one. Not sure if it would help you but at least it would be the latest and up to date versions

**Comment by chicknlil** [comment]
> Hi, indeed once the new version will be there you'll have to do a full backup in the current one and restore in the new one. Not sure if it would help you but at least it would be the latest and up to date versions

Good to know. I will keep my fingers crossed that it works for me. Thank you very much for your time and assistance!

**Comment by alexbelgium** [comment]
Thanks!
