### ISSUE TITLE
Mealie API

### ISSUE THREAD

**Issue by michelangelonz** [alexbelgium/hassio-addons#608]
Does the API Interface work for the Mealie Add-on?

Using http://xxx.xxx.xx.xx:9925/api/meal-plans/today/image?group_name=Home responds with {"detail":"Not Found"}

**Comment by alexbelgium** [comment]
Hi, which architecture are you on? This impacts the version of mealie running. Thanks

**Comment by michelangelonz** [comment]
I'm running a hassos virtual box image.

Thanks for your great work on this add on.

**Comment by michelangelonz** [comment]
64 bit

**Comment by alexbelgium** [comment]
Thanks! Mmh... It should work but I don't have an amd64 install to test and it's the only architecture which is on the latest version... I'll think about it

**Comment by michelangelonz** [comment]
When I use /docs I get a HTTP error 502? Perhaps related? This should bring up the API documentation...

**Comment by alexbelgium** [comment]
That's strange... I guess 502 would point to an issue with the caddy proxy but I only do minimal modif (port and ssl). Key issue is that I don't have a working amd64 system : whenever I start a virtual box with HA my computer reboots... And now with holidays coming I won't have much time to fix my amd64 setup

**Comment by alexbelgium** [comment]
Actually the only true solution I see is to move back to mealie's official images but then there will be two addons : one with the api, one with the front end

**Comment by michelangelonz** [comment]
That sounds fine to me. Its great to have the add-on with HA. Cheers for looking into this.

**Comment by michelangelonz** [comment]
Hi there I did a few experiments with the latest Mealie builds in Docker on another machine. I got similar issues with the API call above except for the /doc  which works. I wounder if the latest version uses a different call to get the meal of the day picture? Cheers.

**Comment by alexbelgium** [comment]
Just read that : "API Integration Will Break

Several of the endpoints in the API have changed. This means that you will need to update your code to use the new endpoints."

https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

**Comment by michelangelonz** [comment]
You are right. There is thread on The Mealie Git about HA integration. I found a integration that has been put together that works with your addin so all good. Not sure why /docs does not work though.

**Comment by michelangelonz** [comment]
https://github.com/hay-kot/mealie/issues/1626

**Comment by michelangelonz** [comment]
I though Id leave this here for  future reference.

To integrate Mealie addon information; 

Create a restful sensor
sensor:
  - platform: rest
    resource: 'http://###.###.#.#:9090/api/groups/mealplans/today'
    method: GET
    name: Mealie todays meal 
    headers:
      Authorization: Bearer <put  auth here> 
    value_template: "{{ value_json.value }}"
    json_attributes_path: $..recipe
    json_attributes:
      - name
      - id
      - totalTime
      - prepTime
      - performTime
      - description
      - slug

Create template sensors from attributes
     - name: TodaysDinner
       unique_id: sensor.TodaysDinner
       state: "{{ state_attr('sensor.mealie_todays_meal', 'name') }}"
     - name: TodaysDinnerDescription
       unique_id: sensor.DinnerDescription
       state: "{{ state_attr('sensor.mealie_todays_meal', 'description') }}"
     - name: TodaysDinnerSlug
       unique_id: sensor.DinnerSlug
       state: "{{ state_attr('sensor.mealie_todays_meal', 'slug') }}"
     - name: TodaysDinnerID
       unique_id: sensor.DinnerID
       state: "{{ state_attr('sensor.mealie_todays_meal', 'id') }}"

Add a generic camera for image
http://###.###.#.#:9090/api/media/recipes/{{ state_attr('sensor.mealie_todays_meal', 'id') }}/images/min-original.webp
