### ISSUE TITLE
[Request] freqtrade - opensource crypto trading bot.

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#62]
HI,

Is this something that can be included in the repo as well?
Free, open source crypto trading bot.
www.freqtrade.io

Repo:
https://github.com/freqtrade/freqtrade

**Comment by alexbelgium** [comment]
I must say that I have checked both your requests and alas none has a ready to use self contained pre existing docker image. I'll try to create one but the probability of success is lower. For the moment I've created an addon draft using the freqtrade provided docker image but it is not working, and the ui is not including by the by default

**Comment by deku-m** [comment]
https://hub.docker.com/r/freqtradeorg/freqtrade/  
this is the pre excisting docker image right?

They state in frequi its available in the dockers.
https://www.freqtrade.io/en/stable/rest-api/

**Comment by alexbelgium** [comment]
I've looked a bit more but it doesn't seem easy. I don't understand why but when I run their docker image it sames freqtrade is not installed...

**Comment by alexbelgium** [comment]
I was starting to have a look again... Are you still interested by this ? An alternative could be to run it directly through portainer

**Comment by alexbelgium** [comment]
Sorry its too complex I'll close this. If anyone manages to make it work for example in portainer as a direct image I would gladly reopen it.
