### ISSUE TITLE
[Meallie] docker volume isn't correct.

### ISSUE THREAD

**Issue by remb0** [alexbelgium/hassio-addons#621]
In the latest mealie addon there is a small bug.   In setting i see:
Docker Volume:
Volumes are misconfigured.

The old alexbelgium addon was working good because the volumes/storage of the front and api were in one container.   It looks like the newest separated containers can't share volumes.   that's the reason that I can import receips but no pictures.     I THINK.

- Addon name : Meailie
- Addon version : latest  v1.0.0-beta-

In the deprecated addon: The Volumes are configured correctly.

**Comment by alexbelgium** [comment]
Hi, mmh you think that recipes are linked to the API Addon, and images to the frontend? I'll have a look when I have some time, thanks

**Comment by remb0** [comment]
Thank you very much

Mealie requires that the frontend container and the backend share the same docker volume or storage. This ensures that the frontend container can properly access the images and assets stored on disk.

**Comment by alexbelgium** [comment]
Thanks then I see the issue. Indeed the storage is in /data which is internal to the Addon. I'll test to externalize it

**Comment by alexbelgium** [comment]
I've pushed new versions where both data location are set to /config/addons_config/mealie_data

**Comment by remb0** [comment]
Damn you are fast.  Thanks it's fixed now 😄

Op za 31 dec. 2022 13:10 schreef Alexandre ***@***.***>:

**Comment by alexbelgium** [comment]
Thanks for the accurate issue analysis. Enjoy the addon
