### ISSUE TITLE
Filebrowser HA app download not authorized 🐛

### ISSUE THREAD

**Issue by zagi988** [alexbelgium/hassio-addons#622]
**Which addon?**

Filebrowser 2.23.0

**Describe the bug**

When Filebrowser is opened thru ingress in HA android app and you try to download something, you get "401: unauthorized"

**To Reproduce**

1. Start Filebrowser
2. Open HA android app, go to WEB UI of Filebrowser
3. Select any file and try to download it
4. 401: unauthorized

**Config**
NoAuth: true
certfile: fullchain.pem
keyfile: privkey.pem
ssl: false
networkdisks: //192.168.1.6/nas
cifsusername: zagi
cifspassword: xxx
base_folder: /mnt/nas

**System**

- Supervisor version: Supervisor 2022.12.1
- Host system version: Home Assistant 2022.12.8, Debian 11

**Comment by alexbelgium** [comment]
Hi, indeed... And I'm not sure how this could be solved.

**Comment by zagi988** [comment]
Yeah, I'm trying to figure out why doesn't the API work when going from the app.

**Comment by alexbelgium** [comment]
Strange : `192.168.178.23:8123/api/hassio_ingress/LASbhFO2gmUYsQVHEYt-LvtkyMTnxwcwVALzeXePS-0/api/raw/filebrowser?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJsb2NhbGUiOiJlbiIsInZpZXdNb2RlIjoibW9zYWljIiwic2luZ2xlQ2xpY2siOmZhbHNlLCJwZXJtIjp7ImFkbWluIjp0cnVlLCJleGVjdXRlIjp0cnVlLCJjcmVhdGUiOnRydWUsInJlbmFtZSI6dHJ1ZSwibW9kaWZ5Ijp0cnVlLCJkZWxldGUiOnRydWUsInNoYXJlIjp0cnVlLCJkb3dubG9hZCI6dHJ1ZX0sImNvbW1hbmRzIjpbXSwibG9ja1Bhc3N3b3JkIjpmYWxzZSwiaGlkZURvdGZpbGVzIjpmYWxzZSwiZGF0ZUZvcm1hdCI6ZmFsc2V9LCJpc3MiOiJGaWxlIEJyb3dzZXIiLCJleHAiOjE2NzI1MTAyNTYsImlhdCI6MTY3MjUwMzA1Nn0.X68ahKKWKu9bUcPH87SVGWtfPFEPwaaEgoOgmPKIm5c` which is the normal download url gives a 401, while `192.168.178.23:8123/api/hassio_ingress/LASbhFO2gmUYsQVHEYt-LvtkyMTnxwcwVALzeXePS-0/api/raw/filebrowser?auth=A` does not. Something in the auth code creates the 401...

**Comment by zagi988** [comment]
Hah, it works just fine if you are just logged in over the browser.
So you open your HA instance thru the browser, log in, be remembered and then it works both from the app and from the browser.

**Comment by alexbelgium** [comment]
Ah, nicely seen! Then it's due to ingress auth. Not sure what we can do, but this is not user friendly... Congrats on having found the solution!

**Comment by zagi988** [comment]
Yeah, not user friendly indeed. But since Filebrowser is not intended to be part of HA, I'd say this works just fine.

**Comment by alexbelgium** [comment]
Thanks!
