### ISSUE TITLE
🐛 [fireflyiii] Error 500, Firefly III broke

### ISSUE THREAD

**Issue by OrangEnerIgel** [alexbelgium/hassio-addons#623]
**Which addon?**

- Addon name : Firefly III
- Addon version : 5.7.17

**Describe the bug**

- Since the installation of Firefly III in HomeAssistant more and more sites become unavailable with the Error-Code 500 in the header and the info Firefly broke. At first only some edit-pages for Bank-Accounts didnt work, but now i have even no access to the Piggy-Bank-Site. The Error was also present in Version 5.7.16

![Screenshot 2022-12-31 19 29 59](https://user-images.githubusercontent.com/120215391/210152826-7db9985c-febc-426f-b7d6-dc40b1253e79.png)

**To Reproduce**

1. Go to the Firefly III Website.
2. Browse the site.
3. Some sites (edit-pages and Piggy-Bank for me) gives an Error-Code 500.

**Full addon log**

- Docker Log: [https://pastebin.com/5YeFzsbD](https://pastebin.com/5YeFzsbD)
- Firefly Debug Page: [https://pastebin.com/xWD8Ca7B](https://pastebin.com/xWD8Ca7B)

**Full addon config**

[https://pastebin.com/WCF3R7KK](https://pastebin.com/WCF3R7KK)

**System**

- Supervisor version: Supervisor 2022.12.1
- Host system version: Home Assistant 2022.12.8
- Operating System: 9.4
- Frontend: 20221213.1 - latest

**Comment by MaoZ1993** [comment]
same here, 5.7.17

**Comment by alexbelgium** [comment]
Hi, I think it's this issue in the upstream app : https://github.com/firefly-iii/firefly-iii/issues/6787

**Comment by OrangEnerIgel** [comment]
Hi, i think i found a workaround. 
I changed the database to mariadb and its working for me now.
Unfortunately i didnt know how to move my data to the new db, so i had to start from scratch.

**Comment by alexbelgium** [comment]
Hi, strange! It would mean it's specific to sqlite... Well anyway in the long run Mariab is much more stable for large database. Beware of backups though : you need to backup the Mariadb addon, and it's preferable to stop the Addon before 
 performing the backup

**Comment by OrangEnerIgel** [comment]
Thanks for the info! I had to restore HomeAssistant from a backup today because i played a little with my network and couldnt reach it! Luckily Firefly and everything else still works fine.

**Comment by alexbelgium** [comment]
I use this mighty app for automation : https://github.com/sabeechen/hassio-google-drive-backup which allows stopping addons before backups

**Comment by OrangEnerIgel** [comment]
Then I used the right app for my backups ;) I use this add-on since my first installation.

**Comment by Blogshot** [comment]
This has been fixed in version 5.7.18 from around three days ago, is it possible to update the addon to the latest upstream?

**Comment by alexbelgium** [comment]
Hi, automated updates are on Saturday morning, it should be good tomorrow
