### ISSUE TITLE
🐛 [Jackett Nas] Unable to mount local drives! Please check the name.

### ISSUE THREAD

**Issue by furang** [alexbelgium/hassio-addons#624]
**Which addon?**

- Addon name : Jackett Nas
- Addon version : 0.20.2459

**Describe the bug**

Local disk is not mounted in jacket nas, although it's mounted in Radarr Nas, Sonarr Nas, Transmission with the same config

**To Reproduce**

1. Go to 'Jackett Nas' config page in Home Assistant addons
2. Append 
```yaml
localdisks: sdb1
```
to config
3. Click 'Save'
4. Start the addon
5. See the error in logs
mount: /mnt/sdb1: permission denied.
mount: /mnt/sdb1: permission denied.
[12:46:28] FATAL: Unable to mount local drives! Please check the name.
 
**Full addon log**

Log: https://pastebin.com/DHu0vtq4

**Full addon config**

```yaml
PGID: 0
PUID: 0
localdisks: sdb1
```

**System**

- Supervisor version: 2022.12.1
- Host system version: Home Assistant OS 9.4  (aarch64 / odroid-n2)

**Comment by alexbelgium** [comment]
Hi, thanks I've added the permissions
