### ISSUE TITLE
[addon] Mealie

### ISSUE THREAD

**Issue by jdeath** [alexbelgium/hassio-addons#625]
mealie

name: Documentation Update
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

While you cannot update from >1.0 to the new version, you can move your database.
1. Start new API and front end addon.
2. Stop new API and front end addon
3. Start the old mealie addon, log in to the docker container, and cp -r /data/* /config/addons_config/mealie_data/
4.  Start new API and front end addon, and everything should be working
---

**Which addon?**

**Addon or app?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexbelgium** [comment]
Good idea! Actually I'll automate that through an addon update

**Comment by alexbelgium** [comment]
Thanks very much!

**Comment by jdeath** [comment]
Thanks for the shout-out. Looks like there is now an omni container, so will not need two addons soon.

**Comment by alexbelgium** [comment]
No, really??? Argh... 2 weeks after me switching from omni container (not official) to the official images. Then everyone will have again to change their databases! Well, we'll see

**Comment by alexbelgium** [comment]
Thanks for the info though, I've updated the main Addon to the omni image to rest

**Comment by jdeath** [comment]
Appreciate you working on the single image. It doesn't work. I think it is due to the port mapping. The addon maps only the 9000, but the web interface is on 8080? Good thing i have a backup, seems to have kept two-addon version from working again.

**Comment by alexbelgium** [comment]
And now the omni should work on the original addon
