### ISSUE TITLE
Import Backup from old Portainer Install

### ISSUE THREAD

**Issue by EpicLPer** [alexbelgium/hassio-addons#63]
Hi,

I want to import the old Settings from the (now fully broken) Community Portainer, however the import of settings is only possible during the initial setup screen of Portainer. This screen however doesn't appear since it seems to be pre-configured.

Is there any other way to import those?

Thanks!

**Comment by EpicLPer** [comment]
The page simply stays blank for me when I provide no password. But the latest version still seems to be -2, not -3.

**Comment by alexbelgium** [comment]
Please update to the new version I've pushed, v3. I've removed the manual_override option. Just removed the password from the options (make it blank) and the addon will allow to restore the backup!

**Comment by alexbelgium** [comment]
OK, this time it works :)

**Comment by EpicLPer** [comment]
Hm, now there seems to be an issue when trying to log in.

My old username on the exported instance was "stefan", but it doesn't let me log in with either that or "admin" and the now defined password anymore.

**Comment by alexbelgium** [comment]
So the backup was correctly restored? And then you still couldn't log in? I'm not familiar with the portainer backup  process but I suppose it keeps the same user base.

Actually it's even possible to manually restore by sshing into the addon and replacing the /data/portainer.db file with the one you would extract from the old addon

**Comment by alexbelgium** [comment]
BTW, due to portainer structure, each password change in the addon options resets the whole database . So once you restore your backup you shouldn't change the "password" addon option

**Comment by EpicLPer** [comment]
Thanks! Yeah my issue it seems was me setting a new password afterwards. I didn't know it needs to just stay empty.

Tho, as an improvement notice, you may want to update it so that you have a config checkmark where it says "Force Password Change" so people don't accidentally wipe their entire Portainer config.

**Comment by alexbelgium** [comment]
Thanks for the suggestion! Actually any password change in the addon config results in a database wipeout... I've put a description in the log and Readme of the addon, but indeed the only way to avoid that would be to prevent changing the admin password from addon options but that would not be very user friendly...
