### ISSUE TITLE
🐛 [Webtrees] Configuration "BASE_URL" cannot be modified

### ISSUE THREAD

**Issue by thorschtn** [alexbelgium/hassio-addons#633]
Webtrees

- Addon name : Webtrees
- Addon version : 2.1.15-4

**Describe the bug**

Configuration "BASE_URL" cannot be modified. Whatever I enter and save, BASE_URL switches back to http://192.168.178.23. However a modification of the Port works, BASE_URL doesn't. Entering another BASE_URL in /config/addons_config/webtrees/config.yaml doesn't work either.

**Full addon log**

`
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Webtrees
 web's leading on-line collaborative genealogy application
-----------------------------------------------------------
 Add-on version: 2.1.15-4
 You are running the latest version of this add-on.
 System: Ubuntu 22.04.1 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2023.01.dev0602
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[15:38:56] INFO: Execute /config/addons_autoscripts/webtrees.sh if existing
[15:38:56] INFO: ... no script found
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/webtrees/config.yaml
Config file is a valid yaml
[15:38:57] INFO: Starting the app with the variables in /config/addons_config/webtrees/config.yaml
BASE_URL=http://192.168.178.186
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[15:38:57] INFO: Defining database
[15:38:57] INFO: Using a local sqlite database /data/webtrees/webtrees please wait then login. Default credentials : admin : mybadpassword
[15:38:57] INFO: Launching app, please wait
... update data with image
... update permissions
... make links with data in /share
... linking data
... linking modules_v4
... align base url with latest addon value
Aligning base_url addon config
[15:38:57] INFO: Aligning trusted_headers addon config with cf-connecting-ip
[15:38:57] INFO: Data is stored in /share/webtrees
[15:38:57] INFO: Webui can be accessed at : http://192.168.178.23:9997
python3 /docker-entrypoint.py
[NV_INIT] PRETTY_URLS found in environment variables
[NV_INIT] HTTPS found in environment variables
[NV_INIT] HTTPS_REDIRECT found in environment variables
[NV_INIT] SSL_CERT_FILE NOT found in environment variables, using default: /certs/webtrees.crt
[NV_INIT] SSL_CERT_KEY_FILE NOT found in environment variables, using default: /certs/webtrees.key
[NV_INIT] BASE_URL found in environment variables
[NV_INIT] LANG found in environment variables
[NV_INIT] DB_TYPE found in environment variables
[NV_INIT] DB_HOST found in environment variables
[NV_INIT] DB_PORT found in environment variables
[NV_INIT] DB_USER found in environment variables
[NV_INIT] DB_PASS found in environment variables
[NV_INIT] DB_NAME found in environment variables
[NV_INIT] DB_PREFIX found in environment variables
[NV_INIT] WT_USER found in environment variables
[NV_INIT] WT_NAME found in environment variables
[NV_INIT] WT_PASS found in environment variables
[NV_INIT] WT_EMAIL found in environment variables
[NV_INIT] DB_KEY NOT found in environment variables, using default: None
[NV_INIT] DB_CERT NOT found in environment variables, using default: None
[NV_INIT] DB_CA NOT found in environment variables, using default: None
[NV_INIT] DB_VERIFY NOT found in environment variables, using default: None
[NV_INIT] PHP_MEMORY_LIMIT NOT found in environment variables, using default: 1024M
[NV_INIT] PHP_MAX_EXECUTION_TIME NOT found in environment variables, using default: 90
[NV_INIT] PHP_POST_MAX_SIZE NOT found in environment variables, using default: 50M
[NV_INIT] PHP_UPLOAD_MAX_FILE_SIZE NOT found in environment variables, using default: 50M
[NV_INIT] Setting up folder permissions for uploads
[NV_INIT] Updating php.ini
[NV_INIT] Creating php.ini
[NV_INIT] Setting value for memory_limit in php.ini
[NV_INIT] Setting value for max_execution_time in php.ini
[NV_INIT] Setting value for post_max_size in php.ini
[NV_INIT] Setting value for upload_max_filesize in php.ini
[NV_INIT] Updating config file
[NV_INIT] Setting value for rewrite_urls in config
[NV_INIT] Setting value for base_url in config
[NV_INIT] Setting value for dbtype in config
[NV_INIT] Setting value for dbhost in config
[NV_INIT] Setting value for dbport in config
[NV_INIT] Setting value for dbuser in config
[NV_INIT] Setting value for dbpass in config
[NV_INIT] Setting value for dbname in config
[NV_INIT] Setting value for tblpfx in config
[NV_INIT] Configuring HTTPS
[NV_INIT] Removing HTTPS
[NV_INIT] Disabling site webtrees-redir
Site webtrees-redir already disabled
[NV_INIT] Disabling site webtrees-ssl
Site webtrees-ssl already disabled
[NV_INIT] Enabling site webtrees
Enabling site webtrees.
To activate the new configuration, you need to run:
  service apache2 reload
[NV_INIT] Setting up folder permissions for uploads
[NV_INIT] Starting Apache
[Fri Jan 06 15:38:58.084288 2023] [mpm_prefork:notice] [pid 277] AH00163: Apache/2.4.54 (Debian) PHP/8.1.13 OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Jan 06 15:38:58.084323 2023] [core:notice] [pid 277] AH00094: Command line: 'apache2 -D FOREGROUND'
`

**Full addon config**

`
#============================#
# ALEXBELGIUM'S ENV INJECTOR #
#============================#
#
# All env variables set in this file will be enabled in the app
# This allows enabling more options that normally available in the addon options
# This file must be filled according to the yaml format.
# If the format is invalid, the addon will note an error.
# To validate your yaml, you can use the free online tool http://www.yamllint.com/

# EXAMPLE of the format (you need to remove the # for it to become active)
# TZ: Europe/Paris
BASE_URL: "http://192.168.178.186" # The url with which you access webtrees
`
**System**

Home Assistant 2023.1.1
Supervisor 2023.01.dev0602
Frontend 20230104.0 - latest

**Comment by alexbelgium** [comment]
Hi, you could try resetting the addon options. There is no specific reason it should be kept to the default setting...

**Comment by thorschtn** [comment]
Thanks for your reply. A day and a reboot later everything works fine.
