### ISSUE TITLE
🐛 [Spotweb] cannot start spotweb due php8 error

### ISSUE THREAD

**Issue by remb0** [alexbelgium/hassio-addons#636]
**Spotweb**

- Addon name : Spotweb
- Addon version :Current version: 1.5.4-3

**Describe the bug**

Spotweb cannot start anymore. Uninstall install already tried.

**To Reproduce**

Uppdated the spotweb addon to: Current version: 1.5.4-3

**Full addon log**

cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[07:12:53] INFO: Execute /config/addons_autoscripts/spotweb.sh if existing
[07:12:53] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/90-spotweb
[07:12:53] WARNING: Spotweb is using the Maria DB addon
[07:12:53] WARNING: Please ensure this is included in your backups
[07:12:53] WARNING: Uninstalling the MariaDB addon will remove any data
core-mariadb (172.30.33.1:3306) open
[07:12:53] INFO: Existing database, checking health with upgrade-db....
s6-applyuidgid: fatal: unable to exec php8: No such file or directory
cont-init: info: /etc/cont-init.d/90-spotweb exited 127
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Full addon config**

**System**

- Home Assistant 2023.1.1
Supervisor 2022.12.1
Frontend-versie: 20230104.0 - latest

**Comment by alexbelgium** [comment]
Hi, 1.5.4-6 should be good
