### ISSUE TITLE
Transmission add-on fails to install

### ISSUE THREAD

**Issue by danielvschoor** [alexbelgium/hassio-addons#64]
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 2:05:45 PM (2 occurrences)
Last logged: 2:10:57 PM

Failed to to call /addons/db21ed7f_transmission_ls/install - The command '/bin/sh -c apk add --no-cache curl jq samba smbclient && curl -J -L -o /tmp/bashio.tar.gz "https://github.com/hassio-addons/bashio/archive/v0.13.1.tar.gz" && mkdir /tmp/bashio && tar zxvf /tmp/bashio.tar.gz --strip 1 -C /tmp/bashio && mv /tmp/bashio/lib /usr/lib/bashio && ln -s /usr/lib/bashio/bashio /usr/bin/bashio && rm -fr /tmp/bashio.tar.gz' returned a non-zero code: 1 
```

Looks like it fails adding `smbclient`. Running it manually from the terminal results in this:
```bash
$ apk add smbclient
ERROR: unable to select packages:
    smbclient (no such package)
        required by: world[smbclient] 
```

**Comment by alexbelgium** [comment]
Hi, as I know you're one of transmission users I'm taking advantage of that ;-)
I've made a few changes yesterday to the addon, with :
- Removal of unprotected mode required
- Addition of local disks mount
- Addition of repair capabilities for the json
- Optional custom UI, with flood custom UI set by default
- Optional custom DNS setting (to avoid flooding a local DNS filter such as adguard)
- Optional whitelist
- Optional identification with USER & PASS
- 
Could you please let me know if everything went smoothly, or if you encounter any issues? 
Thanks very much!

**Comment by danielvschoor** [comment]
> Hi, as I know you're one of transmission users I'm taking advantage of that ;-) I've made a few changes yesterday to the addon, with :
> 
> * Removal of unprotected mode required
> * Addition of local disks mount
> * Addition of repair capabilities for the json
> * Optional custom UI, with flood custom UI set by default
> * Optional custom DNS setting (to avoid flooding a local DNS filter such as adguard)
> * Optional whitelist
> * Optional identification with USER & PASS
> 
> Could you please let me know if everything went smoothly, or if you encounter any issues? Thanks very much!

Hi. 

Sorry, I switched to qBittorrent about a week ago due to some high CPU usage issues with transmission.

**Comment by alexbelgium** [comment]
Thanks for the feedback!
