### ISSUE TITLE
✨ [REQUEST] MyElectricalData + power_max usage

### ISSUE THREAD

**Issue by r0m1CH** [alexbelgium/hassio-addons#643]
Hello Alex, 

Great job for your addons.

I would love to get some new entities with the power usage based on mqtt topics:  myelectricaldata/XXXXXXXXXXXX/power_max/

I can think about a new entity for the last 7 days power usage like you did with sensor.myelectricaldata_consumption_last5day_XXXXXXXXXXXX

It will allow us to graph all the values.

Let me know if I'm not clear.

**Comment by alexbelgium** [comment]
Thanks very much ; actually the app developper is @ma4dm4rtig4n for the [app in itself](https://github.com/m4dm4rtig4n/myelectricaldata), I'm only doing the addon

**Comment by r0m1CH** [comment]
Oh okay. Thanks from the feedback. I will see with @m4dm4rtig4n
