### ISSUE TITLE
qBittorrent - Disabling Bypass authentication for whitelisted IP not surviving restart 

### ISSUE THREAD

**Issue by edonelezovic** [alexbelgium/hassio-addons#645]
I have the Clouflared HA add-on installed and have remote access enabled to qBittorent.

Because the access is being routerd locally I need to disable 'Bypass authentication for clients in whitelisted IP subnets'.
This works until the next restart of the qBittorrent add-on. I tried disabling the option, removing the IP subnets, inputing some random subnet, nothing helps.
Removing the option in YAML configuration also doesn't help, the add-on reverts to the defaults.

Is there any option for the add-on to remember the choice od disabling bypass authentificaiton of clients in whitelisted IP subnets between restarts?

**Comment by alexbelgium** [comment]
Hi, have you tried typing "null" in the subnet yaml option? I'll investigate a bit later

**Comment by alexbelgium** [comment]
Type anything less than 5 characters, such as null, and it will disable the whitelist

**Comment by edonelezovic** [comment]
When I written 'null' it seems like it works now. The value stays disabled after restart.
Thanks!

**Comment by celynw** [comment]
A few updates later, I was going to open a new issue since this didn't seem to hold anymore. But I changed the value from `null` to `n` and it's working again. It could have just been the fact I made a modification. Just posting here in case it helps somebody else
