### ISSUE TITLE
✨ [REQUEST] MyElectricalData - Access to portail from HA

### ISSUE THREAD

**Issue by Skuair** [alexbelgium/hassio-addons#649]
**Which addon?**

MyElectricalData

**Feature request**
C'est la 1ère fois que j'installe cet addon et je pensais pouvoir accéder au portail dashboard de MyElectricalData (port 5000 du container) directement depuis HA (via Ingress si j'ai bien compris).
Là il faut obligatoirement faire un port forwarding pour y accéder directement sur l'ip HA:5000 par exemple.
Est-il possible de donner accès au portail directement via HA sans avoir à ouvrir le port 5000 sur le host HA ?

**Comment by alexbelgium** [comment]
Bonjour, je vais regarder mais ingress n'est pas compatible avec toutes les app donc rien de garanti

**Comment by alexbelgium** [comment]
Bonjour, j'ai fais un addon avec cette option dans mon repo de test. Le soucis est que je n'ai pas de compte Enedis donc je ne peux pas le tester... Vu la complexité de l'implémentation d'ingress, je ne pourrais pas mettre cette option sans avoir de compte.
Est-ce que vous pourriez tester l'addon MyElectricalData dans ce repo : https://github.com/alexbelgium/hassio-addons-test

Si ingress ne fonctionne pas directement je crains de ne pas pouvoir l'implémenter. Merci d'avance

**Comment by Skuair** [comment]
J'ai récupéré l'add-on de test, malheureusement, quand je cliques sur "Ouvrir l'interface utilisateur web", j'ai écrit 502: Bad Gateway dans la page.
![image](https://user-images.githubusercontent.com/49756503/213810419-8345186f-c68f-43ac-8c11-d77babdd75fb.png)

**Comment by alexbelgium** [comment]
Merci, y-a-t-il un message dans le log de l'addon ? En theorie il pourrait dire si il y a un soucis

**Comment by Skuair** [comment]
Effectivement, j'ai complètement oublié de regarder les logs, c'est la base
Le logs de l'add-on semble ok :
```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: MyElectricalData
 Use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.8.13-beta1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (armv7 / raspberrypi3)
 Home Assistant Core: 2023.1.6
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/enedisgateway2mqtt/config.yaml'
TZ='Europe/Paris'
mqtt_autodiscover='true'
verbose='true'
/etc/cont-init.d/01-custom_script.sh: executing
[08:12:24] INFO: Execute /config/addons_autoscripts/enedisgateway2mqtt.sh if existing
[08:12:24] INFO: ... no script found
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/91-mqtt_autodiscover.sh: executing
[08:12:25] INFO: mqtt_autodiscover is defined in options, attempting autodiscovery...
[08:12:26] INFO: ... MQTT service found, fetching server detail (you can enter those manually in your config file) ...
/etc/cont-init.d/91-mqtt_autodiscover.sh: exiting 2
/etc/cont-init.d/99-run.sh: executing
creating symlink
[08:12:28] INFO: Using database file found in /config/enedisgateway2mqtt
[08:12:28] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
Config file is a valid yaml
 
[08:12:28] INFO: Starting the app
```
Ensuite, le log de MyElectricalData qui se poursuit.

Par contre, ce qui est intéressant, c'est dans le log du supervisor quand j'ouvre l'interface, le problème est là :
```
23-01-21 08:14:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.5:8099 ssl:default [Connect call failed ('172.30.33.5', 8099)]
```

**Comment by alexbelgium** [comment]
Est-ce que vous pouvez me dire si ça fonctionne ? Merci d'avance

**Comment by Skuair** [comment]
Je viens de mettre à jour, j'ai bien accès maintenant à la page du portail.
Cependant, des requêtes ajax retournent 404, je pense que c'est parce qu'elles ne partent pas du chemin ingress/xxxxxxxx mais direct de ip:port/. Le 404 retourné doit être celui de l'api de HA direct.

Quelques exemples :
![image](https://user-images.githubusercontent.com/49756503/214931458-c296b411-3072-426e-bd2a-4ed085fcc023.png)
![image](https://user-images.githubusercontent.com/49756503/214931475-635ec906-886d-4120-be71-245beeb56803.png)
![image](https://user-images.githubusercontent.com/49756503/214931492-2b19076e-b7a1-4337-8ae1-3ed418102538.png)

On voit que l'url d'appel est sur HA et non sur ingress :
![image](https://user-images.githubusercontent.com/49756503/214932165-97ee607d-8ef9-467e-8542-3c3b1ea96fa5.png)

Contrairement à la requête de get_status par exemple :
![image](https://user-images.githubusercontent.com/49756503/214932332-d269ea24-2652-4b94-96de-52c880920c14.png)

A mon avis, ce problème sort du cadre de cette issue, et est plutôt pour @m4dm4rtig4n.
Si c'est le cas, tu peux fermer l'issue et j'en ouvrirai une autre sur MyElectricalData.
Merci à toi.

**Comment by alexbelgium** [comment]
Merci pour le test, j'ai poussé une version pour faire le lien avec le datatable. Un grand merci pour les détails de troubleshooting c'est exactement ce qu'il fallait

**Comment by Skuair** [comment]
C'est ok avec la nouvelle version, merci.

**Comment by alexbelgium** [comment]
Super, merci
