### ISSUE TITLE
[Issue] Emby - Unable to mount local drives!

### ISSUE THREAD

**Issue by dan81andrei** [alexbelgium/hassio-addons#650]
Unable to mount local drives!

Local Disks mounting...
Using PUID 0 and PGID 0
ntfs-3g-mount: failed to open /dev/fuse: Operation not permitted
ntfs-3g-mount: failed to open /dev/fuse: Operation not permitted
[23:44:37] FATAL: Unable to mount local drives! Please check the name.

**Comment by alexbelgium** [comment]
Hi, thanks indeed there weren't accesses. I've added it but ntfs is not fully supported so no guarantee it will work

**Comment by dan81andrei** [comment]
It works, the external hdd was successfully mounted to /mnt/sda1
I was able to add the movies to the library, everything is perfect now, thank you very much!
