### ISSUE TITLE
[EPIC GAMES FREE] addon crashes during startup

### ISSUE THREAD

**Issue by Bagnuk** [alexbelgium/hassio-addons#655]
**Which addon?**

- Addon name : EPIC GAMES FREE
- Addon version : 67778639ee9bc09c8a543f7e7904116f850dcabc-2023-01-12 (2023-01-12)

**Describe the bug**

Addon stops by itself after launch

**Full addon log**

`Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Epic Games Free
 Automatically login and redeem promotional free games from Epic Games Store
-----------------------------------------------------------
 Add-on version: 67778639ee9bc09c8a543f7e7904116f850dcabc-2023-01-12
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.1.6
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[19:57:21] INFO: Execute /config/addons_autoscripts/epicgamesfree.sh if existing
[19:57:21] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/99-run.sh: executing
 
[19:57:22] INFO: Starting the app
 
> epicgames-freegames-node@4.1.0 entrypoint-config
> node dist/src/entrypoint-config.js
Error: Invalid config
    at Object.<anonymous> (/usr/app/src/common/config/setup.ts:110:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/app/src/common/config/index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
[2023-01-21 19:57:25.064 +0200] ERROR: Validation error(s)
    errors: [
      {
        "value": [
          {
            "email": "example@gmail.com",
            "password": "abc1234",
            "totp": "EMNCF83ULU3K3PXPJBSWY3DPEHPK3PXPJWY3DPEHPK3YI69R39NE"
          }
        ],
        "property": "accounts",
        "children": [
          {
            "value": {
              "email": "example@gmail.com",
              "password": "abc1234",
              "totp": "EMNCF83ULU3K3PXPJBSWY3DPEHPK3PXPJWY3DPEHPK3YI69R39NE"
            },
            "property": "0",
            "children": [
              {
                "value": "EMNCF83ULU3K3PXPJBSWY3DPEHPK3PXPJWY3DPEHPK3YI69R39NE",
                "property": "totp",
                "children": [],
                "constraints": {
                  "matches": "totp must match /^[A-Z2-7]+=*$/ regular expression"
                }
              }
            ]
          }
        ]
      }
    ]
npm notice 
npm notice New major version of npm available! 8.19.3 -> 9.3.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.3.1>
npm notice Run `npm install -g npm@9.3.1` to update!
npm notice `

**System**

- Supervisor version: supervisor-2022.12.1
- Host system version: core-2023.1.6
- npm version in raspberry: 9.3.1

**Comment by viny182** [comment]
Hello, the error is pretty clear....

You have to create a config.json file in the path /config/addons_config/epicgamesfree with your own cofiguration (email id/account info) before starting the addon.

An example of the file can be found in the "Setup" section from this link -> https://github.com/claabs/epicgames-freegames-node

If you already have your config.json file, validate its content in here: https://jsonlint.com/
