### ISSUE TITLE
✨ [REQUEST] Guacamole – custom fonts directory (solution in issue)

### ISSUE THREAD

**Issue by fischer-felix** [alexbelgium/hassio-addons#656]
**Which addon?**

Guacamole Client

**Is your feature request related to a problem? Please describe.**

I use powerlevel10k as a zsh theme on most of my systems, so the defautl fonts on guacamole don't display correctly.

**Describe the solution you'd like**

To fix this, you have to use a compatible font, such as MesloLGS NF (listed on [romkatv/powerlevel10k](https://github.com/romkatv/powerlevel10k#fonts)). 

This should be possible to achieve by adding `<dir>/config/fonts</dir>` to `/etc/fonts/fonts.config`, so that the user can just add a fonts directory in their config folder and add whatever fonts they like. 
Then fontconfig will pick those up and they will be available to guacamole.

The only change necessary would be adding another sed command to the Dockerfile:
`sed -i '\|<dir>/usr/share/fonts</dir>|a\ \ \ \ \ \ \ \ <dir>/config/fonts</dir>' /etc/fonts/fonts.conf`
This adds the directory after `/usr/share/fonts` which should always be there.
I tried making the sed command a bit nicer, but this was the only way it worked with the correct indentation.

**Additional context**

Currently the terminal looks like this:

![Screenshot_2023 01 21_23:30:39](https://user-images.githubusercontent.com/65448408/213889503-18c29903-0b5e-4d7a-93b5-91ffe8077937.png)

It should look like this:
![Screenshot_2023 01 21_23:43:24](https://user-images.githubusercontent.com/65448408/213889907-210eaf26-3ba3-4c89-8142-9ea7e1b3a356.png)

**Comment by alexbelgium** [comment]
Thanks should be good now! Thanks again for coming with the solution :)
