### ISSUE TITLE
[ guacamole] Init too many symlinks

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#659]
Hello, I removed completly and installed again latest version same issue:

![image](https://user-images.githubusercontent.com/42787097/213937845-d5da63f3-88c7-4300-902d-70840b61ea54.png)

_Originally posted by @E-NINA in https://github.com/alexbelgium/hassio-addons/issues/652#issuecomment-1399594143_

**Comment by E-NINA** [comment]
I try just update and them complete remove and install agian and same error

![image](https://user-images.githubusercontent.com/42787097/213994811-3b4cb30a-4da2-472d-a9b3-c8b3e832dfa2.png)

**Comment by alexbelgium** [comment]
Are you on HA os or your own system? Here is what I found on google : "I had to change my host fstab to mount shm fs at /run/shm to follow docker ubuntu pattern." https://github.com/docker/for-linux/issues/588#issuecomment-471198821

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version to test removal of the file that seems to be problematic

**Comment by alexbelgium** [comment]
Great news! And it works on my system too so no downside apparently
