### ISSUE TITLE
[MyElectricalData] Accès au cache.db + renomage du enedisgateway2mqtt en myelectricaldata

### ISSUE THREAD

**Issue by m4dm4rtig4n** [alexbelgium/hassio-addons#663]
Hello Alex,

Dit je viens d'installer une version d'HaOS sur une VM pour voir le fonctionnement de l'addon et je m'appercois qu'il y a encore des endroit où il est marqué enedisgateway2mqtt.

Exemple : 
![image](https://user-images.githubusercontent.com/7872518/214294567-103dfe91-5fff-42f5-954c-46fdb38f40ef.png)

Et j'ai un soucis d'initialisation de la bdd chez certain utilisateurs depuis l'addon, une idée de où ca peut venir ?
D'ailleurs je ne trouve pas le fichier cache.db dans le dossier enedisgateway2mqtt, normal ?

**Comment by alexbelgium** [comment]
Bonjour,

Merci, je viens de créer une branche pour enlever les instances (principalement en effet le dossier + Readme). Le seul endroit que je ne puisse changer est le slug, sinon ça enlèverais la possibilité d'upgrade pour les users. Par contre c'est un nom interne qui ne devrait pas être apparent.

J'ai installé l'addon et le cache.db se crèe bien sur mon système donc je ne peux pas répliquer cet élément
![image](https://user-images.githubusercontent.com/44178713/214331236-36bd3d64-a5c6-4a65-b009-dabca5e58a59.png)

**Comment by alexbelgium** [comment]
Aurais-tu un log correspond au démarrage où le cache.db ne se crèe pas? Merci d'avance

**Comment by m4dm4rtig4n** [comment]
En fait il le crée bien le cache.db, c'est juste qu'il n'apparait pas dans Visual Studio Code :)
Le soucis est ailleurs, je suis en train d'essayer de debug...

En gros l'application crée bien le cache.db, crée la structure, mais l'ajout des data juste après l'init ne remonte pas d'erreur mais ne fait rien :/

Bref je continue de debug et de découvrir haos :D

**Comment by alexbelgium** [comment]
Une issue avec le suivi de symlink? Car un symlink est créé entre /config/myelectricaldata/config.yaml et /data/config.yaml et /config/myelectricaldata/cache.db et /data/cache.db

**Comment by m4dm4rtig4n** [comment]
@alexbelgium j'ai trouver le soucis avec le cache mal init, c'était un soucis liée à la lib SQLAlchemy qui ne réagit pas tt à faire pareil sur l'addon via HA (je ne sais pas trop pk).
J'ai config la lib en autocommit + autoflush, sauf que l'autoflush ne semblais pas fonctionner via HaOS.
=> J'ai forcer le flush

**Comment by alexbelgium** [comment]
Merci pour le feedback, donc le soucis est résolu en upstream et nécessite simplement que j'update l'addon a la dernière version de l'app ?

**Comment by alexbelgium** [comment]
Y-a-t-il une manière pour moi de démarrer l'app et accéder au webui sans avoir de compte ? Car pour l'instant mes debugs sont en aveugle ce qui n'aide pas toujours

**Comment by m4dm4rtig4n** [comment]
Actuellement il n'y a pas d'authentification sur l'UI, par contre l'application ne boot pas si aucun point de livraison + token saisie dans le fichier de configuration mais je pense que je vais faire sauter cette limitation car il est possible de configurer les point de livraison via l'interface maintenant

**Comment by hautfr** [comment]
[db21ed7f_enedisgateway2mqtt_2023-01-30T11-43-46.764Z.log](https://github.com/alexbelgium/hassio-addons/files/10535431/db21ed7f_enedisgateway2mqtt_2023-01-30T11-43-46.764Z.log)

J'ai le même problème, pas de .db visible via StudioCodeServer et pb lié, cf. mon log attaché.
