### ISSUE TITLE
✨ [REQUEST] myelectricaldata / enedisgateway2mqtt : add a "Open Web UI" button/function

### ISSUE THREAD

**Issue by chrsc59** [alexbelgium/hassio-addons#665]
!!! I have a real life job in parallel to this addon, and don't think I'll be able to add new addons for the moment. You can still however express your interest in case someone would do it

**Which addon?**

myelectricaldata / enedisgateway2mqtt

**Is your feature request related to a problem? Please describe.**

No Open Web UI button

**Describe the solution you'd like**

Add the Open Web UI button/function

**Describe alternatives you've considered**

**Additional context**

**Comment by alexbelgium** [comment]
Indeed, strange it was gone. Readded ; it should appear at next repo refresh
