### ISSUE TITLE
🐛 [Photoprism] strange update version

### ISSUE THREAD

**Issue by baldarn** [alexbelgium/hassio-addons#668]
sorry to bother you, is this version suppose to be like this?
I really care of photoprism and I wouldn't like to destroy everything updating :)

![Screenshot from 2023-01-25 14-15-43](https://user-images.githubusercontent.com/2814802/214572934-a5a3d7db-467f-459f-b998-3b2f8341e390.png)

**Comment by alexbelgium** [comment]
However honestly I really recommend you to always have regular backups in case anything goes wrong

**Comment by baldarn** [comment]
thanks! I will update that.
ofc I have backups, but the least I use those the happier I am ;)

**Comment by alexbelgium** [comment]
Ahah, fully agree with you! Btw have you tried immich? I don't understand the buzz about people saying they move from photoprism to it, currently it seems photoprism is more robust with its face algorithm, places, and ability to use an existing photo structure. Photoprism is super fast too :)
