### ISSUE TITLE
Unable to mount NTFS local drives! Please check the name

### ISSUE THREAD

**Issue by pjopaul** [alexbelgium/hassio-addons#670]
**Which addon?**

-----------------------------------------------------------
```
 Add-on version: 2.23.0-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.1.7
 Home Assistant Supervisor: 2022.12.1
```

-----------------------------------------------------------

**Which addon?**

FileBrowser

I am getting the "Unable to mount local drives! Please check the name." error message in the logs.

logs =>
-----------------------------------------------------------
```
/etc/cont-init.d/01-custom_script.sh: executing
[21:32:28] INFO: Execute /config/addons_autoscripts/filebrowser.sh if existing
[21:32:28] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/92-local_mounts.sh: executing
Local Disks mounting...
mount: mounting /dev/sdb1 on /mnt/sdb1 failed: Invalid argument
mount: mounting /dev/sdb1 on /mnt/sdb1 failed: Invalid argument
[21:32:30] FATAL: Unable to mount local drives! Please check the name.
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
```

--------------------------------------
As per HA logs it is mounted to /dev/sdb1
=>
```
23-01-25 13:49:21 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/002/005 - None
23-01-25 13:49:23 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/sg1 - None
23-01-25 13:49:23 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bsg/1:0:0:0 - None
23-01-25 13:49:23 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/sdb - /dev/disk/by-id/usb-_USB_DISK_3.0_900037233A245902-0:0
23-01-25 13:49:23 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/sdb1 - /dev/disk/by-id/usb-_USB_DISK_3.0_900037233A245902-0:0-part1

```
-----------------------------------------------------
Filebrowser configuration updated as follow

`localdisks: sdb1`

--------
Let me know if I missed anything

**Comment by alexbelgium** [comment]
Hi, your config seems good... What is your filesystem? Only ext* is supported, and sometimes ntfs

**Comment by pjopaul** [comment]
Usb formatted as ntfs

**Comment by alexbelgium** [comment]
Uh, sorry closing it was mz pressing the wrong button. Ntfs is sometimes supported but not fully as the library is sometimes buggy... I'll check tomorrow. I've myself switched all my disks to ext4 as it is natively supported by linux

**Comment by pjopaul** [comment]
Sure, let me also try ext*.

**Comment by alexbelgium** [comment]
That's the issue, i have only enabled the ntfs libraries on alpine based distributions as (at the time i created the script) apt-based distribution install failed. I havent checked but perhaps filebrowser is not based on alpine

https://github.com/alexbelgium/hassio-addons/blob/5cd461702e0cf480489ed16ab3e76c4b01ff9783/.templates/automatic_packages.sh#L66

**Comment by pjopaul** [comment]
The main reason I formatted USB with NTFS is to share media files between my windows system and home assistant.
Trying to figure it out how to format for ext4

**Comment by pjopaul** [comment]
ok, thx @alexbelgium really appreciate it

**Comment by alexbelgium** [comment]
Script to reinstall ntfs driver is:
```
#!/bin/bash

apk update
apk add  ntfs-3g
```

**Comment by pjopaul** [comment]
Created the .sh file
![image](https://user-images.githubusercontent.com/18707812/214705071-f90870b1-c1df-4e1c-8379-5ae60b92a98f.png)

Filebrowser Logs =>
-------------------------------
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Filebrowser
 filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files
-----------------------------------------------------------
 Add-on version: 2.23.0-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.1.7
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
```
/etc/cont-init.d/01-custom_script.sh: executing
[22:21:18] INFO: Execute /config/addons_autoscripts/filebrowser.sh if existing
[22:21:18] INFO: ... script found, executing
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
v3.16.3-145-g4534ab608c [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
v3.16.3-145-g4534ab608c [https://dl-cdn.alpinelinux.org/alpine/v3.16/community]
OK: 17043 distinct packages available
OK: 92 MiB in 92 packages
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/92-local_mounts.sh: executing
Local Disks mounting...
mount: mounting /dev/sdb1 on /mnt/sdb1 failed: Invalid argument
mount: mounting /dev/sdb1 on /mnt/sdb1 failed: Invalid argument
**[22:21:22] FATAL: Unable to mount local drives! Please check the name.**
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[22:21:24] INFO: NoAuth option selected
[22:21:24] INFO: Starting...
2023/01/25 22:21:24 No config file used
2023/01/25 22:21:24 Listening on [::]:8080
[22:21:24] INFO: Started !
```
---------------------------------------------------
USB still with ntfs format

**Comment by pjopaul** [comment]
After formatting the USB  to ext4 format it worked and mounted.
I think NTFS drive have the issue

**Comment by alexbelgium** [comment]
Yep ntfs support seems sketchy in Linux. Actually the most portable format between Linux and Windows is fat32, but it comes with limitations

**Comment by pjopaul** [comment]
Thanks @alexbelgium for the support and great product
