### ISSUE TITLE
[all] supervisor logs flooded with error messages from recent translation changes

### ISSUE THREAD

**Issue by MaxWinterstein** [alexbelgium/hassio-addons#671]
When checking for updates the supervisor throws errors like 

```log
23-01-26 22:43:44 ERROR (SyncWorker_2) [supervisor.utils.yaml] Can't read YAML file /data/addons/git/db21ed7f/booksonic_air/translations/en.yaml - mapping values are not allowed in this context
  in "/data/addons/git/db21ed7f/booksonic_air/translations/en.yaml", line 267, column 123
23-01-26 22:43:44 WARNING (SyncWorker_2) [supervisor.store.data] Can't read translations from /data/addons/git/db21ed7f/booksonic_air/translations/en.yaml - Can't read YAML file /data/addons/git/db21ed7f/booksonic_air/translations/en.yaml - mapping values are not allowed in this context
  in "/data/addons/git/db21ed7f/booksonic_air/translations/en.yaml", line 267, column 123
```

<img width="1811" alt="image" src="https://user-images.githubusercontent.com/5927148/214957677-946fff31-8166-4038-bb91-ca52708265c5.png">

**Comment by alexbelgium** [comment]
Ahah, indeed! I used the translation file to have unique file that would explain all addon options but this is indeed unexpected :) i'll investigate tomorrow if i need to revert or adapt the file

**Comment by MaxWinterstein** [comment]
I guess the colon `:` creates the issue

https://github.com/alexbelgium/hassio-addons/blob/3121a0e8248f4914c3d3ecc3a359aedf2e24ef97/arpspoof/translations/en.yaml#L267

**Comment by alexbelgium** [comment]
All good now, thanks. I wanted to transfer options description from readme to the subtext under the option itself
