### ISSUE TITLE
🐛 [Epic Games Free] Version discrepancy seems to have reappeared

### ISSUE THREAD

**Issue by KairuByte** [alexbelgium/hassio-addons#672]
**Which addon?**

- Addon name : Epic Games Free
- Addon version : Latest/Current/etc.

**Describe the bug**

Add-on version has fallen behind released version of the original docker image again.

**Note**
Snipped the other questions because they do not apply.

**Comment by alexbelgium** [comment]
Hi, the automatic update is every saturday.

67778639ee9bc09c8a543f7e7904116f850dcabc was released 16 days ago (so is the current version), a730bceb8ad5c476fd6c2a90e5685e2ed6783957 was released 1 day ago (and will be updated tomorrow).

So it seems to me everything is as should be ?

**Comment by KairuByte** [comment]
Ah! I didn't realize there was a schedule. Apologies, and you are correct.

**Comment by alexbelgium** [comment]
Thanks! As the updater runs on my rpi I've limited the run of time it runs. It also reduces the probability of picking up releases with issues that would have been pulled or for which a new version would be instantly pushed
