### ISSUE TITLE
🐛 [Epic Games Free] Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by OutOfThisPlanet** [alexbelgium/hassio-addons#675]
**Which addon?**

- Addon name : Epic Games Free]
- Addon version : Current version: 5fc6de6ce0306d51e1867b10e76e9dbd1343faa0-2023-01-28

**Describe the bug**

`ERROR: Navigation timeout of 30000 ms exceeded
    user: "my+email@gmail.com"
    err: {
      "type": "TimeoutError",
      "message": "Navigation timeout of 30000 ms exceeded",
      "stack":
          TimeoutError: Navigation timeout of 30000 ms exceeded
              at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (/usr/app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:220:12)
      "name": "TimeoutError"
    }`

**To Reproduce**

This has always happened in every version. 
My email has a "+" in it. 
I wonder if that is the reason.

**Full addon log**

![image](https://user-images.githubusercontent.com/42836083/215314247-1fe31e53-946f-4463-bac1-9b1e4fcd55ab.png)

`
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Epic Games Free
 Automatically login and redeem promotional free games from Epic Games Store
-----------------------------------------------------------
 Add-on version: 5fc6de6ce0306d51e1867b10e76e9dbd1343faa0-2023-01-28
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.1.7
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[08:10:39] INFO: Execute /config/addons_autoscripts/epicgamesfree.sh if existing
[08:10:39] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/99-run.sh: executing
 
[08:10:40] INFO: Starting the app
> epicgames-freegames-node@4.1.0 entrypoint-config
> node dist/src/entrypoint-config.js

Setting timezone: Europe/London
Run on startup: true
[2023-01-29 08:10:52.913 +0000] INFO: Started epicgames-freegames-node
    COMMIT_SHA: "5fc6de6ce0306d51e1867b10e76e9dbd1343faa0"
    BRANCH: "master"
    DISTRO: "alpine"
[2023-01-29 08:10:53.495 +0000] INFO: Checking free games for my+email@gmail.com 
    user: "my+email@gmail.com"
[2023-01-29 08:11:39.216 +0000] ERROR: Encountered an error during browser automation. Saved a screenshot for debugging purposes.
    user: "my+email@gmail.com"
    errorFile: "error-2023-01-29T08:11:30.677Z.png"
[2023-01-29 08:11:39.231 +0000] ERROR: Navigation timeout of 30000 ms exceeded
    user: "my+email@gmail.com"
    err: {
      "type": "TimeoutError",
      "message": "Navigation timeout of 30000 ms exceeded",
      "stack":
          TimeoutError: Navigation timeout of 30000 ms exceeded
              at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (/usr/app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:220:12)
      "name": "TimeoutError"
    }
[2023-01-29 08:11:39.284 +0000] WARN: Current version
    COMMIT_SHA: "A SHA HASH"
    BRANCH: "master"
    DISTRO: "alpine"
Run once: false
Setting cron schedule as 5 16 * * *
`

- Supervisor version: 2023.1.1
- CORE: 2023.1.7
- OS: 9.5

**Comment by alexbelgium** [comment]
Hi, if this has happened with every version you would be safer in posting on the epicgamesfree [github forum](https://github.com/claabs/epicgames-freegames-node), not sure I'll be able to help from the addon side

**Comment by OutOfThisPlanet** [comment]
That was a quick response! :)

Sure, thanks for the tip :)

**Comment by OutOfThisPlanet** [comment]
Credit where credit is due, in case anybody else searches for this issue. My solution is in this post: 

[https://github.com/claabs/epicgames-freegames-node/issues/317#issuecomment-1407661163](https://github.com/claabs/epicgames-freegames-node/issues/317#issuecomment-1407661163)

I added the following to my config.json for epicgamesfree:

`"browserNavigationTimeout": 300000,`

**Comment by brashenfr** [comment]
> Credit where credit is due, in case anybody else searches for this issue. My solution is in this post:
> 
> [claabs/epicgames-freegames-node#317 (comment)](https://github.com/claabs/epicgames-freegames-node/issues/317#issuecomment-1407661163)
> 
> I added the following to my config.json for epicgamesfree:
> 
> `"browserNavigationTimeout": 300000,`

Thank you so much it works for me ! 👍 @alexbelgium @OutOfThisPlanet

**Comment by mardito** [comment]
It's worked for me too !!
