### ISSUE TITLE
🐛 [Addon name] Issue description

### ISSUE THREAD

**Issue by Puppetmaster91** [alexbelgium/hassio-addons#682]
**Which addon?**

Sonarr & Radarr
on the newest version

**Describe the bug**

Addon trying to mount network drives using SMB version 1 despite the SMBv1 is disabled in add-on configuration.

**To Reproduce**
1. go to addon setting
2. add a SMB share that doesn't allow SMBv1 connections
3. start addon
4. check log

**Full addon log**

`cont-init: info: running /etc/cont-init.d/00-banner.sh
[migrations] started
[migrations] no migrations found
-----------------------------------------------------------
 Add-on: Radarr NAS
 A fork of Sonarr to work with movies like Couchpotato
-----------------------------------------------------------
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
 Add-on version: 4.3.2.6857-3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.2.0
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[13:25:22] INFO: Execute /config/addons_autoscripts/radarr-nas.sh if existing
[13:25:22] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
Mounting smb share(s)...
Using PUID 0 and PGID 0
mount error(95): Not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
mount: mounting //10.0.0.3/Media on /mnt/Media failed: Not supported
[13:25:24] FATAL: Error, unable to mount //10.0.0.3/Media to /mnt/Media with username ****, ********. Please check your remote share path, username, password, domain, try putting 0 in UID and GID
[13:25:24] FATAL: Here is some debugging info :
	Sharename       Type      Comment
	---------       ----      -------
	Back Up         Disk      
	homes           Disk      user home
	Media           Disk      
	NetBackup       Disk      System default shared folder
	surveillance    Disk      System default shared folder
	uploads         Disk      uploads
	web             Disk      System default shared folder
	web_packages    Disk      
	IPC$            IPC       IPC Service ()
	home            Disk      Home directory of ****
SMB1 disabled -- no workgroup available
[13:25:25] FATAL: Error read : mount error(95): Not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
mount: mounting //10.0.0.3/Media on /mnt/Media failed: Not supported
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.3.2.6857 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Info] MigrationController: *** Migrating data source=/config/addons_config/radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/addons_config/radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[ls.io-init] done.`

![image](https://user-images.githubusercontent.com/63652895/216330699-7f31c5e4-57bd-48ed-ae88-c409e5586733.png)

**Full addon config**

`PGID: 0
PUID: 0
networkdisks: //10.0.0.3/Media
cifsusername: ****
cifspassword: ********
TZ: DK`

**System**
- Supervisor version: supervisor-2023.01.1
- Host system version: Home Assistant OS 9.5

**Additional comments**
If i enable SMBv1 on my NAS it mounts the folder

**Comment by alexbelgium** [comment]
Hi, actually it tests all its known SMB options. It starts testing with SMB v3.2 and moves from older to older versions until reaching SMB v1. However, is that an issue to use SMB v1 for you? Or do you know the SMB version you are using?
