### ISSUE TITLE
✨ [REQUEST] Omada_v3 AddOn upgrade from v5.7 to v5.8

### ISSUE THREAD

**Issue by DanielTheCoder** [alexbelgium/hassio-addons#683]
!!! I have a real life job in parallel to this addon, and don't think I'll be able to add new addons for the moment. You can still however express your interest in case someone would do it

**Which addon?**

=> Omada_v3

**Describe the solution you'd like**

=> Omada_v3 AddOn upgrade from v5.7 to v5.8

**Describe alternatives you've considered**

=> creating a PR but not sure what is needed to do

Thank you for your work!

**Comment by alexbelgium** [comment]
Hi, thanks! It should be automatically updated this Saturday given it's now released. My automated release cycle is now every Saturday

**Comment by DanielTheCoder** [comment]
Great and thank you for your time, maintaining all these integrations.

**Comment by alexbelgium** [comment]
Done
