### ISSUE TITLE
🐛 [Addon name] Issue description

### ISSUE THREAD

**Issue by AtticusG3** [alexbelgium/hassio-addons#687]
**Which addon?**

- Addon name : [Sonarr NAS]
- Addon version : 3.0.9.1549-5

**Describe the bug**

Sonarr NAS fails to Start

**To Reproduce**

**Full addon log**

> cont-init: info: running /etc/cont-init.d/00-banner.sh
> -----------------------------------------------------------
>  Add-on: Sonarr
>  Can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them
> -----------------------------------------------------------
>  Add-on version: 3.0.9.1549-5
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 9.5  (amd64 / qemux86-64)
>  Home Assistant Core: 2023.2.1
>  Home Assistant Supervisor: 2023.01.1
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums
>  https://github.com/alexbelgium/hassio-addons
> -----------------------------------------------------------
> cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
> cont-init: info: running /etc/cont-init.d/01-custom_script.sh
> [23:10:13] INFO: Execute /config/addons_autoscripts/sonarr-nas.sh if existing
> [23:10:13] INFO: ... no script found
> cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
> cont-init: info: running /etc/cont-init.d/01-envfile
> cont-init: info: /etc/cont-init.d/01-envfile exited 0
> cont-init: info: running /etc/cont-init.d/01-migrations
> [migrations] started
> [migrations] no migrations found
> cont-init: info: /etc/cont-init.d/01-migrations exited 0
> cont-init: info: running /etc/cont-init.d/10-adduser
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> Brought to you by linuxserver.io
> -------------------------------------
> To support the app dev(s) visit:
> Sonarr: https://sonarr.tv/donate
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    0
> User gid:    0
> -------------------------------------
> cont-init: info: /etc/cont-init.d/10-adduser exited 0
> cont-init: info: running /etc/cont-init.d/20-folders.sh
> cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
> cont-init: info: running /etc/cont-init.d/30-config
> cont-init: info: /etc/cont-init.d/30-config exited 0
> cont-init: info: running /etc/cont-init.d/32-nginx_ingress.sh
> cont-init: info: /etc/cont-init.d/32-nginx_ingress.sh exited 0
> cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
> cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
> cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
> Mounting smb share(s)...
> Using PUID 0 and PGID 0
> [23:10:17] INFO: ... //192.168.1.11/Movies successfully mounted to /mnt/Movies with options 
> [23:10:17] INFO: ... //192.168.1.11/TV successfully mounted to /mnt/TV with options 
> [23:10:17] INFO: ... //192.168.1.11/Anime successfully mounted to /mnt/Anime with options 
> cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
> cont-init: info: running /etc/cont-init.d/99-custom-files
> [custom-init] No custom files found, skipping...
> cont-init: info: /etc/cont-init.d/99-custom-files exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service init-mods: starting
> s6-rc: info: service init-mods successfully started
> s6-rc: info: service init-mods-package-install: starting
> s6-rc: info: service init-mods-package-install successfully started
> s6-rc: info: service init-mods-end: starting
> s6-rc: info: service init-mods-end successfully started
> s6-rc: info: service init-services: starting
> s6-rc: info: service init-services successfully started
> s6-rc: info: service legacy-services: starting
> services-up: info: copying legacy longrun nginx (no readiness notification)
> services-up: info: copying legacy longrun sonarr (no readiness notification)
> s6-rc: info: service legacy-services successfully started
> s6-rc: info: service 99-ci-service-check: starting
> [ls.io-init] done.
> s6-rc: info: service 99-ci-service-check successfully started
> [Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.9.1549 
> [Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/sonarr] 
> [Fatal] ConsoleApp: EPIC FAIL! 
> [v3.0.9.1549] NzbDrone.Common.Exceptions.SonarrStartupException: Sonarr failed to start: /config/addons_config/sonarr/config.xml is empty. Please delete the config file and Sonarr will recreate it.
>   at NzbDrone.Host.Bootstrap.Start (NzbDrone.Common.EnvironmentInfo.StartupContext startupContext, NzbDrone.Host.IUserAlert userAlert, System.Action`1[T] startCallback) [0x0009f] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Host\Bootstrap.cs:55 
>   at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00030] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Console\ConsoleApp.cs:42 
> Press enter to exit...
> Non-recoverable failure, waiting for user intervention...

**Full addon config**

`PGID: 0
PUID: 0
TZ: Australia/Brisbane
cifspassword: smbusrpassword
cifsusername: smbusr
networkdisks: //192.168.1.11/Movies,//192.168.1.11/TV,//192.168.1.11/Anime
`

**System**

Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by alexbelgium** [comment]
Hi, this looks like a config.xml corruption. Could you please paste the content of /config/addons_config/sonarr/config.xml ?

thanks

**Comment by AtticusG3** [comment]
This issue is occurring on a clean install, there should be no
configuration file present at all.

Unfortunately it's not possible for me to post the file your shipping it
with as I deleted the file as it suggests and sonar rebuilt the
configuration file itself.

**Comment by alexbelgium** [comment]
The strangest thing is i don't actually ship one, it is built on the fly by the app... Is it still occurring with the latest version i pushed? It solved another issue but perhaps it had an impact
