### ISSUE TITLE
🐛 [Radarr/Sonarr] Waiting for config.xml to be created

### ISSUE THREAD

**Issue by IonutNeagu** [alexbelgium/hassio-addons#688]
**Which addon?**

- Addon name : Sonarr
- Addon version : 3.0.9.1549-5 

- Addon name : Radarr
- Addon version : 4.3.2.6857-7 

**Describe the bug**

Although the file exists, in the log it appears tens/hundreds of times that it does not exist

**To Reproduce**

```
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
Waiting for /config/addons_config/sonarr/config.xml to be created
```

```
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
Waiting for /config/addons_config/radarr/config.xml to be created
```

**Full addon config**

```
PGID: 0
PUID: 0
networkdisks: ""
cifsusername: ""
cifspassword: ""
TZ: Europe/Bucharest
```

**System**

- Supervisor version: 
- Host system version:

**Comment by alexbelgium** [comment]
Hi, sorry it's an issue with the code to add ingress. Hope having ingress will be useful to you and its worth it ;)

**Comment by alexbelgium** [comment]
The latest versions I've pushed work on my system

**Comment by IonutNeagu** [comment]
> Hi, sorry it's an issue with the code to add ingress. Hope having ingress will be useful to you and its worth it ;)

Not really, because I use Nginx Proxy and I don't need URL Base to be set

**Comment by IonutNeagu** [comment]
@alexbelgium, how can I make it stop rewriting the Base URL ?

**Comment by alexbelgium** [comment]
I thought that even if there was a base url, the domain was directly accessible. I'll add a switch to the config otherwise to avoid that

**Comment by alexbelgium** [comment]
Pushed for radarr in v18, I'll align the other  addons

**Comment by deku-m** [comment]
hi alexbelgium,

Im reusing this ticket as there is a new issues with the new published sonarr with communicating with bittorrent.

**Comment by alexbelgium** [comment]
Hi, please create a new issue it's easier for me to track. Normally sonarr should start fine now, I've corrected the latest code that I added. However, my last addition was a switch to disable ingress, so it shouldn't impact qbittorrent. Or else, perhaps it is due to the fact a base url had to be set for ingress ?
