### ISSUE TITLE
✨ [REQUEST] Addon  changedetection.io 

### ISSUE THREAD

**Issue by shirou93** [alexbelgium/hassio-addons#689]
Please add this docker image as addon to your repo

https://hub.docker.com/r/dgtlmoon/changedetection.io

"Website change detection and notification, know when JSON or websites have a change, get notified of changes in websites via Discord, Telegram, Slack, Email and 70+ more"

Official website https://changedetection.io/

Thanks

**Comment by thomastunc** [comment]
Hey, I am a fan of this tool as well and would love to see it as an addon. I've understand that images from linuxserver.io are easier to implement, so I'd think it's better to use this link:

https://docs.linuxserver.io/images/docker-changedetection.io

**Comment by shirou93** [comment]
> Hey, I am a fan of this tool as well and would love to see it as an addon. I've understand that images from linuxserver.io are easier to implement, so I'd think it's better to use this link:
> 
> https://docs.linuxserver.io/images/docker-changedetection.io

On hassos is to big interfering in os. Portainer can qickly destroy system when user is beginner.

**Comment by alexbelgium** [comment]
Should be good, let me know

**Comment by shirou93** [comment]
Working Good. Thanks 🥳

**Comment by plangin** [comment]
@shirou93 

Did you manage to use the Visual Filter Selector?

Looks like a Playwright Chrome fetcher is needed.

**Comment by diamant-x** [comment]
I would like to ask as well regarding the visual filter selector.

Based on linuxserver: 

> Please note that this image does not contain the [Playwright content fetcher](https://github.com/dgtlmoon/changedetection.io/wiki/Playwright-content-fetcher#docker-compose-based) due to a lack of support for muslc-based systems. If you require this feature please use https://github.com/linuxserver/docker-changedetection.io/issues/3#issuecomment-1250251715 or the [official container](https://github.com/dgtlmoon/changedetection.io#docker)

So either we need to get a Selenium addon as well developed, or maybe rebase the addon to the official docker?
