### ISSUE TITLE
[Joal] Failed to connect to joal

### ISSUE THREAD

**Issue by inrepublica** [alexbelgium/hassio-addons#69]
Bonjour,

Je n'arrive pas à faire fonctionner correctement Joal dans HA. J'ai bien installé l'addon mais ensuite je sèche un peu sur la configuration.

Dans les options de l'addon dans le superviseur j'ai ceci:
```
ui_path = joal
secret_token = XXXX
run_duration = 12h
```
Je n'ai pas touché à la configuration réseau.

Ensuite dans la webUI de joal "Connection settings" j'ai ceci:
```
Server adress: homeassistant.local
Server port = 8123
Path prefix = joal
Secret token = XXXX
```

Malheureusement j'ai systématiquement le message "Failed to connect"

Merci de votre aide.

**Comment by alexbelgium** [comment]
Bonjour, 
Il est clair que ce n'est pas l'addon le plus facile à configurer car la logique d'enregistrement qu'il utilise est difficilement compatible avec le système "Ingress" qu'utilise HA pour permettre l'affichage au sein de l'app.

Il est possible d'y accéder de deux manières, qui demandent chacune une manière différente de se connecter. Je vais l'écrire en anglais ainsi je fais un copier coller dans mon README après pour les autres ;-)

Je vais pousser une nouvelle version de l'app dans quelques minutes pour donner l'addresse Ingress dans le log de l'addon. Ca devrait déjà faciliter. J'espère que ça va aider, sinon n'hésitez pas à me dire!

Bonne journée

1. Via ingress (accessible from within the app)
- Address : 
   - until I make it automatic, you need to get the Ingress URL from the addon log. It will look something like : 
   - example from my config : `192.168.178.69:8123/api/hassio_ingress/POVP6iOh67KUz_LQQJg4lOC-DJi7FNXutaz_7kNiFWM/`
- Port : your HA port (usually 8123)
- Prefix : defined in "ui_path" addon options _(default : joal)_
- Secret token : defined in "secret_token" addon options _(default : lrMY24Byhx)_

2. From the local network, by accessing directly accessing the url ("joal" must be replaced by whatever your "ui_path" is set to in the addon options): `http://homeassistant.local:8081/joal/ui`
- Address : homeassistant.local _(or your direct url, or your external url if you have opened the port on your router)_
- Port : defined in addon options _(default : 8081)_
- Prefix : defined in "ui_path" addon options _(default : joal)_
- Secret token : defined in "secret_token" addon options _(default : lrMY24Byhx)_

**Comment by alexbelgium** [comment]
J'ai mis en ligne une version qui contient dans le log toutes les infos exactes pour se connecter

**Comment by inrepublica** [comment]
Merci pour votre aide et la nouvelle version. Alors bizarrement en accès direct c'est ok mais directement dans l'app cela ne fonctionne pas... Ou puis-je trouver un log pour la webUI JOAL?

**Comment by alexbelgium** [comment]
Avec plaisir. Il faut aller l'onglet de HA Supervisor, puis HA, puis la juste choisir Log.
Il y aura la description de comment configurer la version directe via l'app (le port et adresse à encoder sont différents)

**Comment by inrepublica** [comment]
Effectivement dans le log j'ai bien trouvé ce qu'il faut pour un accès direct (OK) et pour l'accès via HA. Mais avec ces paramètres cela ne fonctionne pas j'ai toujours failed to connect...

**Comment by alexbelgium** [comment]
Pourriez-vous poster le contenu exact que vous mettez dans la config ? Aucune de ces informations ne peut être utilisée de manière frauduleuse à ma connaissance.

Merci d'avance

**Comment by alexbelgium** [comment]
Je pense avoir réussi à répliquer votre soucis. Vous avez changé le "path" ou "mot de passe"? Car dans ce cas ci en effet j'arrive à me connecter en direct mais plus via ingress

**Comment by alexbelgium** [comment]
J'ai trouvé : si vous êtes connecté à HA via homeassistant.local:8123 ; il faut remplacer l'ip par homeassistant.local en début d'addresse.

Si vous êtes connecté à HA via IP, il faut utiliser l'IP. Je vais pousser une nouvelle version -v5 qui décrit les 2 possibilités et vous donne le choix du copier coller dans le log.

**Comment by inrepublica** [comment]
Effectivement c'est bien ça! Encore merci à vous pour votre aide ;-)

**Comment by alexbelgium** [comment]
Avec plaisir, bon amusement avec HA !

**Comment by jojolll** [comment]
Bonjour,

Je me permets de commenter ici car je rencontre un problème très similaire : impossible de faire fonctionner la WebUI de l'addon Joal malgré tous vos conseils et mes heures d'essais.

Je ne comprends pas le fonctionnement de l'Addon. Il s'agit bien "d'un kit" comprenant l'application Joal ainsi que sa WebUI, et pas uniquement la WebUI ? 
Si j'ai compris, nous devons ensuite configurer cet UI pour qu'elle soit en mesure de contacter le serveur Joal "inclus" dans le docker ? (je crois que c'est la ou je me trompe)

Je ne comprends également pas la subtilité d'utilisation de l'adresse IP ou du domaine local dans la WebUI. Pourquoi est-ce que cela doit changer d'une installation à l'autre ? homeassistant.local doit bien renvoyer la bonne adresse locale, systématiquement ? 
Personnellement j'utilise un reverse proxy. HomeAssistant fonctionne bien sur le port 8123, mais j'utilise https://mondomaine.com/ sur le port 443 pour y accéder, ce qui doit encore compliquer les choses. 
La webUI est bien accessible en ingress ou sur le sous domaine https://joal.mondomaine.com/ (reverse proxy), mais je suis incapable de comprendre comment la faire fonctionner :( 

Pourriez vous me donner votre avis sur mon installation ? Est-elle compatible avec cet addon, ou il me manque des éléments ? 

Merci d'avance ! 👍

**Comment by alexbelgium** [comment]
Bonjour, l'addon comprends bien la totalité : addon + webui

Ce qu'il faut remplir dans les champs est écrit dans le log de l'addon.

On peut y accéder de deux manières : 
- soit via un port externe, et dans ce cas là on n'a rien à configurer (il suffit d'aller sur l'ip de homeassistant avec le port décrit dans les options de l'addon, 8091 par défaut. D'après votre example, je suppose que vous utilisez 8081). Au lieu de l'ip, vous pouvez tenter de mettre `homeassistant.local`

- soit via ingress, à travers l'interface de home assistant. Dans ce cas là, le "server port" est le port exposé par HA lui-même (8123 par défault), l'addresse est soit l'ip, soit le domaine selon la manière dont vous vous connectée, et le "secret token" reste dans tous les cas le même (celui défini dans les options de l'addon)

**Comment by alexbelgium** [comment]
est-ce que ça a pu vous aider?

**Comment by jojolll** [comment]
Voici mes logs, j'ai a peu près tout essayé malheureusement : 
![image](https://user-images.githubusercontent.com/26553241/172588143-798f5f23-c3c9-4c23-803b-86c59234dbbd.png)

Il ne me parle a aucun  moment du port 443 même si c'est celui que j'utilise (logique, il n'en a pas conscience). Mais je ne comprends pas pourquoi il devrait sortir du réseau local pour fonctionner de toute manière ?

**Comment by jojolll** [comment]
Le server port est peut être erroné ? Il devrait être différent du port WEBUI, mais on en parle nulle part il me semble.

**Comment by alexbelgium** [comment]
En fait il faut utiliser le dernier set d'instructions, en remplaçant juste 8123 par 443

**Comment by alexbelgium** [comment]
Donc : 
Server address = mondomaine.com:443/api/...
Prefix = joal
secret token = kls...
Port = 433

**Comment by alexbelgium** [comment]
Il doit sortir du réseau local car en fait il utilise l'api HA pour se connecter au serveur

**Comment by jojolll** [comment]
Pas mieux :( un truc doit merder avec les proxy ou le HTTPS je pense.

**Comment by alexbelgium** [comment]
en théorie c'est du websocket donc justement ça contourne le https. En fait il faut quasi une config par système qui se connecte, mais une fois que c'est fait c'est bon :-)

J'ai moi même refait ma config à l'instant et je suis en https avec un port différent entre HA et le port exposé donc je suis assez confiant sur le fait que ça doit marcher...

Server address = CEQUEJUTILISEPOURMECONNECTER/api/hassio_ingress/_mjEFcSMyLBtIbHb2zQjFzs39xWGIq8jw1YcfLBQ8z0
Prefix = joal
secret token = klsfdjbs123
Port = PORTPOURMECONNECTER

CEQUEJUTILISEPOURMECONNECTER : c'est l'url:port avec laquelle tu accède à HA pour ingres
PORTPOURMECONNECTER : c'est le port avec lequel tu accès à HA pour ingress

Voici ma config exacte : 
- commun : 
    Prefix = joal
    Secret token = lrMY24Byhx123
- Si je me connecte en local avec ip :
      Port = 433
      Server address = 192.168.178.23:433/api/hassio_ingress/qG_eJSO51uoHqkxiZzgzi9s5ZeNn5CVxBJH7ymrhW6c/
- Si je me connecte en local avec domaine :
      Port = 433
      Server address = homeassistant.local:433/api/hassio_ingress/qG_eJSO51uoHqkxiZzgzi9s5ZeNn5CVxBJH7ymrhW6c/
- Si je me connecte à distance :
       Port = 8123
       Server address = MONDOMAIN:8123/api/hassio_ingress/qG_eJSO51uoHqkxiZzgzi9s5ZeNn5CVxBJH7ymrhW6c/

**Comment by alexbelgium** [comment]
Curieux... en fait la théorie est simple : quand on accès à HA via un site (genre MONSUPERSITE.fr:123), on s'authentifie. Ensuite, pour accéder à une app, il gère un proxy nginx interne qui fait que accéder à MONSUPERSITE.fr:123/api/hassio_ingress/XXX revient à accéder à l'addon directement

Mettre cette addresse dans le "server address" permet à Joal de communiquer avec son websocket (Joal va aller le chercher à ws://MONSUPERSITE.fr:123/api/hassio_ingress/XXX). Le tout est d'avoir la même addresse dans la barre, et dans Joal, car l'authentification est faite sur base de l'adresse! donc à chaque fois qu'on accès avec une addresse différente (par exemple, local ou distante), la config de joal sera vide et il faudra la re-remplir en référençant l'addresse d'accès

Par contre, une fois que c'est rempli c'est gardé en cache donc généralement il ne faut remplir qu'une fois :-)

**Comment by jojolll** [comment]
C'est la faute à mon reverse proxy Nginx permettant l'utilisation du port 443 et du HTTPS. Voici la config pas intuitive qui fonctionne dans le cas de figure que je rencontre 👍 
![image](https://user-images.githubusercontent.com/26553241/172619838-8b65c1ba-11dc-4a91-b95d-2b01c2e916d1.png)

**Comment by jojolll** [comment]
Je vais essayer sur mon NDD avec proxy cloudflare, mais maintenant ça doit fonctionner j'imagine :)

**Comment by alexbelgium** [comment]
Super !
