### ISSUE TITLE
Calibre_web does not expose Port 8083

### ISSUE THREAD

**Issue by blackshoals** [alexbelgium/hassio-addons#692]
On Home Assistant 2023.2.2 on an Rpi 4 Calibre_web starts and is accessible under the Web UI of the add-on, but is not accessible through the default 'MY-IP:8083' address. Manually entering '8083' as the port results in a 'Port is already in use' conflict message. Choosing a different port number works. Thanks for your work.

**Comment by alexbelgium** [comment]
Hi, that's the normal behavior. Port is disabled by default as ingress is enabled. By putting a port, you map it to the 8080 within the addon

**Comment by blackshoals** [comment]
Hi, that doesn't seem to be what I'm experiencing. Calibre_web uses port 8083 by default. When I use the default settings in the addon [https://imgur.com/a/BCr9oAJ](url) nothing comes up on "My-IP:8083" and there is no response if I telnet  to port 8083. If I try to use the "force-port" option or enter 8083 under 'Network' []https://imgur.com/a/YAjgHoY(url) it won't restart with a Port 8083 in use by the host error message []https://imgur.com/a/YAjgHoY(url). A port scan shows nothing using 8083. If I choose a random port it works, but unfortunately my ISP has closed off new port forwarding so I'm limited to my existing 8083.

**Comment by alexbelgium** [comment]
Hi, that's normal : in your first screenshot the port is disabled. You need to click on the placeholder and encode a port. I've readded the port by default to avoid misunderstandings

**Comment by blackshoals** [comment]
8083 seems to work for me now after your commit. Thanks
