### ISSUE TITLE
🐛 [Unpackerr] Unable to move files back to original folder when unpacked

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#696]
**Which addon?**

- Addon name : Unpackerr
- Addon version : release-9bf8c46

**Describe the bug**

No matter what settings I configure in the unpackerr.conf file they get overwritten by the addons settings. This is fine except for when I tried to set the files to be moved back in to their original folder instead of an 'unpackerred' folder

**To Reproduce**

If you set move files back to original folder to true in unpackerr.conf it will be overwritten at startup. The logs showcase this as well.

**Comment by alexbelgium** [comment]
Hi, that's strange. I have installed unpackerr, started it, went into /config/unpackerr.conf and modified on line 142 `move_back = true`. I then restarted and the value `move_back = true` was still activated

**Comment by hacshacdgacs** [comment]
![image](https://user-images.githubusercontent.com/85550264/217380659-c1d4e655-63dc-4064-abcf-73f25b45c35a.png)
Above is the log for my unpackerr after I've made the changes.
Below is my config.
![image](https://user-images.githubusercontent.com/85550264/217380951-c42de5f7-186e-4401-8ce2-1a9a00a4cae6.png)
As far as I know it should be working but it seems to be ignoring the move_back line according to my log?

**Comment by alexbelgium** [comment]
well the move_back in your file has # in front which means it is disabled ; have you tried removing it ?

You need to have `move_back = true` instead of `# move_back = true`

**Comment by hacshacdgacs** [comment]
Yea... that was it. Thanks for the help, can't believe I kept overlooking that.

**Comment by alexbelgium** [comment]
Glad it worked!
