### ISSUE TITLE
Nextcoud OCR 20.0.7 | Fail to Inicialize 

### ISSUE THREAD

**Issue by jonathanicq** [alexbelgium/hassio-addons#7]
Hi @alexbelgium 

I've tried to initialize the addon but got the following error

Composer autoloader not found, unable to continue. Check the folder "3rdparty". Running "git submodule update --init" will initialize the git submodule that handles the subfolder "3rdparty".

The log seems fine
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
Creating possible missing Directories
chmod Files and Directories
chown Directories
chmod/chown .htaccess
using pem keys found in /ssl
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing... 
[cont-init.d] 50-install: exited 0.
[cont-init.d] 51-ocr: executing... 
[cont-init.d] 51-ocr: exited 0.
[cont-init.d] 60-memcache: executing... 
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 61-trusted_domains: executing... 
[19:15:18] INFO: Currently set trusted domains :
/var/run/s6/etc/cont-init.d/61-trusted_domains: line 13: /data/config/www/nextcloud/occ: Is a directory
[cont-init.d] 61-trusted_domains: exited 126.
[cont-init.d] 70-aliases: executing... 
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

Any Idea ?

**Comment by alexbelgium** [comment]
Indeed - I had installed several versions of the addon so I probably have data stored that allows it to work on my computer but not for a new install.

I've made a 20.0.7-rev2, could you please test? Thanks!

**Comment by jonathanicq** [comment]
I've just installed the 20.0.7-rev2 and it still get this

/var/run/s6/etc/cont-init.d/61-trusted_domains: line 24: /data/config/www/nextcloud/occ: Is a directory

This directory does not exit, should I make myself ?

**Comment by alexbelgium** [comment]
Can you access the WEBUI ? Normally files are installed at first connection, so there sounds be no need to create files yourself. If it doesn't work I'll look into it tomorrow

**Comment by jonathanicq** [comment]
@alexbelgium 
No, I can't access the webui 
but now, there is no error, just don't load anything.

**Comment by alexbelgium** [comment]
Thanks! Rev3 put on line, I've un installed the addon and installed this version to start from scratch and it works. So hopefully it will for uoj too ;)

**Comment by alexbelgium** [comment]
BTW, v21 will come soon with a great speed improvement

**Comment by jonathanicq** [comment]
@alexbelgium 
Worked 
Once again, thanks a lot !

**Comment by jonathanicq** [comment]
@alexbelgium 
Stupid question, is there any solution that could list all my files over a web portal without format or take the ownership of the drive?

I want to use the smb shared drive but find photos and other files type by a web portal.

**Comment by alexbelgium** [comment]
Doesn't nextcloud does exactly that? Because if you install an app named external something you can mount an smb drive. Then you can see all files without filters, or you can see, for example, only photos if you go into the pictures app

**Comment by jonathanicq** [comment]
@alexbelgium 
You ROCK !

Thank you

**Comment by alexbelgium** [comment]
Thanks! Have fun with HA!
