### ISSUE TITLE
[Request] Hidden service Nginx

### ISSUE THREAD

**Issue by wakielo** [alexbelgium/hassio-addons#70]
Hi

Im enjoying too much with your addons for my home assistant! I guess if you could help me importing this docker in home assisatant?? I have no idea how to integrate it

ozeliurs/tor-hiddenservice-nginx

**Comment by alexbelgium** [comment]
Hi, thanks for the feedback!

Mmh I've read their page and I think it is a really complex think to do... You need direct access to docker to create a custom image, which is not feasible with HA. Also they haven't updated it in 5 years so things are perhaps not working anymore - I see there is a fork slightly updated here : https://github.com/ozeliurs-MaximeBilly/docker-tor-hiddenservice-nginx. So as I understand, you would need to have another system on which you would run the docker commands they provide, then deploy it in HA using the Portainer addon...

Sorry I won't be able to help you much more with this.

**Comment by wakielo** [comment]
Such a pitty... The point was to use the hassio server to run and manage 24/7 additional Dockers..

Thanks for answer!

**Comment by alexbelgium** [comment]
Well that's possible using the portainer addon, which can download and deploy containers. It will then run as if you had an addon, as long as you don't stop the portainer addon! It's made even easier with docker compose, which is included in portainer. The only thing is that you still need to create a custom image as I understand to run this app.
