### ISSUE TITLE
🐛 [Transmission] It doesn't start 

### ISSUE THREAD

**Issue by IonutNeagu** [alexbelgium/hassio-addons#702]
**Which addon?**

- Addon name : Transmission
- Addon version : 4.0.0-r0-ls152

**Describe the bug**

**To Reproduce**

**Full addon log**

```
s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/s6-rc.d/init-migrations/run: No such file or directory
s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/s6-rc.d/init-envfile/run: No such file or directory
s6-rc: warning: unable to start service init-migrations: command exited 127
s6-rc: warning: unable to start service init-envfile: command exited 127
cont-init: info: running /etc/cont-init.d/00-banner.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/00-banner.sh: not found
cont-init: info: /etc/cont-init.d/00-banner.sh exited 127
cont-init: info: running /etc/cont-init.d/01-config.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/01-config.sh: not found
cont-init: info: /etc/cont-init.d/01-config.sh exited 127
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/01-custom_script.sh: not found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 127
cont-init: info: running /etc/cont-init.d/19-json_repair.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/19-json_repair.sh: not found
cont-init: info: /etc/cont-init.d/19-json_repair.sh exited 127
cont-init: info: running /etc/cont-init.d/32-nginx_ingress.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/32-nginx_ingress.sh: not found
cont-init: info: /etc/cont-init.d/32-nginx_ingress.sh exited 127
cont-init: info: running /etc/cont-init.d/90-dns_set.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/90-dns_set.sh: not found
cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 127
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/92-local_mounts.sh: not found
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 127
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/92-smb_mounts.sh: not found
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 127

```

**Full addon config**

**System**

- Supervisor version: 
- Host system version:

**Comment by rdsars** [comment]
I'm having the same issue

**Comment by jeroenwouters** [comment]
I'm having this problem with Qbittorrent too.

**Comment by SiriosDev** [comment]
> I'm having this problem with Qbittorrent too.

I confirm

#704

**Comment by DarkoMir** [comment]
Confirm

**Comment by alexbelgium** [comment]
Mmh linuxserver has updated something in their base image that makes them incompatible with my code it seems, i'll have to update all addons

**Comment by DarkoMir** [comment]
> Mmh linuxserver has updated something in their base image that makes them incompatible with my code it seems, i'll have to update all addons

Thank you for your hard work

**Comment by SiriosDev** [comment]
> Mmh linuxserver has updated something in their base image that makes them incompatible with my code it seems, i'll have to update all addons

I agree

**Comment by alexbelgium** [comment]
Qbittorrent (and others) should be solved. For transmission there is another issue that they have removed custom UI and I need to add it manually

**Comment by alexbelgium** [comment]
WebUI don't seem supported by default anymore by transmission linuxserver. I've removed then, and the addon now boots too in latest version

**Comment by alexbelgium** [comment]
Let me know if customui is really that important for transmission or if default webui is enough ;-)

**Comment by nstrelow** [comment]
Thanks for fixing it. I feel some of the custom skins looks nicer and is easier to use in some scenarios.

I used transmission-flood the whole time.

**Comment by DarkoMir** [comment]
Alternative web ui are really useful. Integrated one in 4.0 is good, but
not as good as other

Il giorno dom 12 feb 2023 alle ore 14:00 Nils Strelow <
***@***.***> ha scritto:

**Comment by alexbelgium** [comment]
I've re-added custom webui with my own code in latest version v4, but you'll have to check if they supports transmission v4 or not ;-) I myself don't use transmission

**Comment by alexbelgium** [comment]
v6 actually

**Comment by alexbelgium** [comment]
Webui are implemented, tested working

**Comment by nstrelow** [comment]
Wow awesome, thanks so much :D
