### ISSUE TITLE
PAPERLESS_OCR_LANGUAGE deu

### ISSUE THREAD

**Issue by jjmwiwi** [alexbelgium/hassio-addons#703]
Dear all,
There seems a problem with with OCR language German. If i set in the confiy.yaml the "PAPERLESS_OCR_LANGUAGE: GER" (GER according to  https://www.loc.gov/standards/iso639-2/php/code_list.php) the following error comes:

Logs: 

"Package tesseract-ocr-ger not found! :("

"?: The selected ocr language ger is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE"

How do I fix this? How can I install the needed language pack GER or DEU

Thanks

**Comment by alexbelgium** [comment]
Mmh from what I remember German is deu, but u u seem to have tried also. I'll check

**Comment by alexbelgium** [comment]
Actually I don't manage this script it's from the paperless ngx upstream app : https://github.com/paperless-ngx/paperless-ngx/blob/bdf9b2453fcd8ef14045463bc90779f977ce5ed8/docker/docker-entrypoint.sh#L157

You'll have to post on their github to get support I'm afraid...

**Comment by alexbelgium** [comment]
Hi, according to this https://github.com/paperless-ngx/paperless-ngx/blob/00c3d8c5237030e0934e7885b6b32f26ee7fcb89/Dockerfile#L101 German is preinstalled. So you don't need to reinstall it and should just be able to enable it in the webui

**Comment by jjmwiwi** [comment]
Hi Alex,

Thanks a lot for your help. 

In meanwhile I found a solution:

I put the following command in the config.yaml

PAPERLESS_OCR_LANGUAGES: deu ces

This command installs the language German

**Comment by alexbelgium** [comment]
Thanks!
