### ISSUE TITLE
[SPOTWEB] Api endpoint for installation on Home Assistant Supervisor server

### ISSUE THREAD

**Issue by moostmartijn** [alexbelgium/hassio-addons#705]
**Which addon?**

name: Question
about: The API endpoint of Spotweb as an add-on on a Home Assistant Supervisor server 

---

**Which addon?**
Spotweb

**Addon or app?**
Add-on

**Describe the question you have**

I would like to use the Spotweb API for Sonarr/Radarr on another server, but when I test the link (https://mydomain.duckdns.org/spotweb/api?t=c) it does not seem to work. I also tried with the local IP address and with /db21ed7f_spotweb/ (ingress link) which also don't work. 

Am I missing something or will the API endpoint just don't work when using Spotweb as an add-on on a Home Assistant Supervisor server? 

Thanks in advance!

**Comment by moostmartijn** [comment]
Bump. Is there a way to use the API with Home Assistant supervisor?

**Comment by alexbelgium** [comment]
Hi, i don't use spotweb so I'm not sure. I'll install it to test. Have you tried also from a local ip to check if it's due to the duckdns domain or the app?

**Comment by moostmartijn** [comment]
Thanks for your reply.

I also tried the through local ip, but I can't find the correct link, because the ingress link is also in the url (http://ip-address:8123/db21ed7f_spotweb/spotweb/api?t=c) 
I think I tried all combinations of which I think could work, but none of them do. And the same problem occurs with the duckdns domain. I'm just not sure if it is possible to use the API in combination with Home Assistant / ingress.

I also have Spotweb on my Synology NAS (but with some time-out problems, so I wanted to try this solution), which returns a correct xml at http://ip-address/spotweb/api?t=c

**Comment by alexbelgium** [comment]
Hi, it works for me. Here are the steps I did : 
- installed the addon
- enabled the outside port in the addon options, and set it to 1234 (disabled by default as ingress is enabled)
- as I access my homeassistant system with "homeassistant.local:8123", I've typed "homeassistant.local:1234/api?t=c" and I had the api infos

Are you sure you enabled the external port?

**Comment by moostmartijn** [comment]
I did overlook the option to use another port than the ingress one. I have enabled it and it does indeed work. Thanks a lot for your help!

**Comment by alexbelgium** [comment]
Great, glad it works! I'll enable it by default for other people
