### ISSUE TITLE
🐛 [Jellyfin NAS] Addon fails to start

### ISSUE THREAD

**Issue by wlad128** [alexbelgium/hassio-addons#706]
**Which addon?**

- Addon name : Jellyfin NAS
- Addon version : 10.8.9-1-ls198 and also 10.8.9-1-ls199 

**Describe the bug**
When trying to start the freshly downloaded Jellyfin Addon, it fails to start. No extra configs were made. 
Also tried to start with PGID + PUID on "1000" without any success.

**To Reproduce**

1. Go to Addons
2. Click on Jellyfin and Start
3. Check Logs

**Full addon log**
/package/admin/s6-overlay/libexec/preinit: info: read-only root
/package/admin/s6-overlay/libexec/preinit: info: writable /run. Checking for executability.
/package/admin/s6-overlay/libexec/preinit: warning: unable to find /run in /proc/mounts, check that your container manager pre-mounts /proc, and that /run is a tmpfs. The container is likely to crash soon, if /run is (incorrectly) mounted noexec.
Segmentation fault (core dumped)

**Full addon config**
PGID: 0
PUID: 0
data_location: /config/addons_config/jellyfin

**System**

- Supervisor version: 2023.2.3
- Host system version: HA OS 9.5 in a VM

**Comment by alexbelgium** [comment]
Strange, i have the same start if log except for segmentation fault
```
/package/admin/s6-overlay/libexec/preinit: info: read-only root
/package/admin/s6-overlay/libexec/preinit: info: writable /run. Checking for executability.
/package/admin/s6-overlay/libexec/preinit: warning: unable to find /run in /proc/mounts, check that your container manager pre-mounts /proc, and that /run is a tmpfs. The container is likely to crash soon, if /run is (incorrectly) mounted noexec.
[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
```

**Comment by wlad128** [comment]
That means everything is okay except the "Segmentation fault (core dumped)"-Error?
Do you know any ways to check some deeper logs?

**Comment by alexbelgium** [comment]
I'll do some deeper investigation a bit later ; on which arch are you ? amd64 I suppose ?

**Comment by wlad128** [comment]
Yes exactly.
Thanks a lot!

**Comment by wlad128** [comment]
Update:
I uninstalled and installed the Addon around 6 times, now it works!!!
Very strange but im fine with that for the moment.
