### ISSUE TITLE
Converting docker image to addon

### ISSUE THREAD

**Issue by IThundxr** [alexbelgium/hassio-addons#707]
Hi I was wondering what the general process is for making a docker image a HA addon as I’d like to make a few and contribute if you want to chat about this over discord that would be slightly easier for me: IThundxr#2619

**Comment by alexbelgium** [comment]
Hi, you could look here for an example : https://github.com/alexbelgium/hassio-addons/discussions/398#discussioncomment-3221150 Hope it will work for you ;-)

**Comment by IThundxr** [comment]
Thanks, I'll try it and see if I succeed :)

**Comment by IThundxr** [comment]
ok so im kinda stuck https://github.com/diced/zipline how would i go about making this into a addon? cant figure out how to get it to start https://github.com/IThundxr/ZiplineHA heres where ive got to at this time

2023-02-13 06:13:15,145 PM error [config] Config is invalid, see below:
2023-02-13 06:13:15,149 PM error [config] CombinedPropertyError (1)
  Received one or more errors
  input.core
  | MissingPropertyError > core
  |   A required property is missing

thats the error i get when i start it

**Comment by IThundxr** [comment]
So error cause config isnt filled out now ill have to figure out how to add the things for people to fill configs

**Comment by IThundxr** [comment]
So how would i have like the addon have a config tab and those configs be used inside the .env.local file

**Comment by IThundxr** [comment]
https://github.com/IThundxr/ZiplineHA So for some reason i cant like export them properly

**Comment by IThundxr** [comment]
Seems my scripts dont work either

**Comment by IThundxr** [comment]
appears it doesnt wanna run dockerfile when im using the image

**Comment by IThundxr** [comment]
I think it's something like it isn't my image or something? Just wondering in your code you use your own images for stuff what's modified in those?

**Comment by alexbelgium** [comment]
Hi, you need to delete this line https://github.com/IThundxr/ZiplineHA/blob/e14b386a81be524dbb0c3c8b79732f2bcd9afddb/config.json#L46 for your addon to self build on your HA

**Comment by alexbelgium** [comment]
Exact ! I've got a github action workflow that builds and publishes my own images, but that's not needed to develop addons

**Comment by IThundxr** [comment]
ok works to a extent but now the dockerfile from the actual zipline image makes the workdir /zipline and me trying to change it to / doesnt work so it ends up not being able to find the start script any way to force change workdir?

**Comment by IThundxr** [comment]
ok got it working but now it launches node before my startup scripts

**Comment by IThundxr** [comment]
/entrypoint.sh:4
export DEBUG=true
^^^^^^
SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Node.js v19.3.0

Getting that

**Comment by alexbelgium** [comment]
Indeed the CMD is executed with node and not bash. Perhaps you could try to force the shell? I think you had it on your dockerfile at one point. Or execute the entrypoint from nodejs ? I don't know that language to know if this is possible

**Comment by alexbelgium** [comment]
But globally in this situation I would google it and try solutions found online like : https://www.google.com/search?q=bash+entrypoint+from+a+nodejs+image&oq=bash+entrypoint+from+a+nodejs+image&aqs=edge..69i57j69i64.5550j0j4&sourceid=chrome&ie=UTF-8

The first result provides a potential solution by changing ENTRYPOINT and CMD

**Comment by IThundxr** [comment]
entrypoint.sh: line 4: bashio::config: command not found
entrypoint.sh: line 5: bashio::config: command not found
entrypoint.sh: line 6: bashio::config: command not found
entrypoint.sh: line 7: bashio::config: command not found
entrypoint.sh: line 8: bashio::config: command not found
entrypoint.sh: line 9: bashio::config: command not found
entrypoint.sh: line 10: bashio::config: command not found
entrypoint.sh: line 11: bashio::config: command not found
entrypoint.sh: line 13: bashio::config: command not found
entrypoint.sh: line 14: bashio::config: command not found
node:internal/modules/cjs/loader:1042

  throw err;
  ^
Error: Cannot find module '/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v19.3.0
entrypoint.sh: line 4: bashio::config: command not found
entrypoint.sh: line 5: bashio::config: command not found
entrypoint.sh: line 6: bashio::config: command not found
entrypoint.sh: line 7: bashio::config: command not found
entrypoint.sh: line 8: bashio::config: command not found
entrypoint.sh: line 9: bashio::config: command not found
entrypoint.sh: line 10: bashio::config: command not found
entrypoint.sh: line 11: bashio::config: command not found
entrypoint.sh: line 13: bashio::config: command not found
entrypoint.sh: line 14: bashio::config: command not found
node:internal/modules/cjs/loader:1042

  throw err;
  ^
Error: Cannot find module '/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v19.3.0

Worked to a extent now bashio can't be found and seems it's still running in node I'll have to check out how I can override this
Might just need to add a different script to diced/zipline to startup and stuff

**Comment by alexbelgium** [comment]
bashio can't be found become my shell scripts in the Dockerfile likely didn't get executed... we perhaps need to define the shell to use to execute those intermediate scripts

That's a good news though it already means you managed to launch the script with bash

**Comment by IThundxr** [comment]
Maybe it will work if I change the entry point before it runs those scripts should run in bash then and properly execute right?

**Comment by alexbelgium** [comment]
entrypoint only applies for launching the container, I think you need to specify bash using the SHELL command perhaps ?

**Comment by IThundxr** [comment]
Hmm not home atm but I'll try it out and see if it works

**Comment by IThundxr** [comment]
Ok ive tried failed and switched to home assistant dockized thanks for your help but seems addons isnt my thing

**Comment by alexbelgium** [comment]
I can look next week if you want

**Comment by IThundxr** [comment]
Nah it's fine I've switched to home assistant docker version as it's just easier to run stuff
