### ISSUE TITLE
🐛 [epicgamesfree] Login returned error: Incorrect response

### ISSUE THREAD

**Issue by nstrelow** [alexbelgium/hassio-addons#708]
**Which addon?**

Epic free games node

- Addon name :
- Addon version : 03-02-2023

I am not 100% how all updates work, but it seems this is set to a version from 3rd Feb.

I've been running into this issue: https://github.com/claabs/epicgames-freegames-node/issues/288

And the maintainer updated the image in hopes of fixing it.

**Comment by nstrelow** [comment]
Thanks, just tested it. still not working. Might be the hassio setup that makes it detect that this is automated.

So maybe mark the addon as potentially non working with error: " Login returned error: Incorrect response. Please refresh the page."

**Comment by Scales82** [comment]
Mine works now with latest update. Had to login with captcha but it has the fresh cookie now and all is well.

**Comment by alexbelgium** [comment]
> So maybe mark the addon as potentially non working with error: " Login returned error: Incorrect response. Please refresh the page."

This is done automatically : once an issue is started that contains the addon name in its title, it appears on the readme and anyone installing it would see it
