### ISSUE TITLE
[epicfreegames] Outside local network

### ISSUE THREAD

**Issue by IThundxr** [alexbelgium/hassio-addons#709]
So im wondering as on both this and the repo of epicfreegames it doesnt say if you should allow people outside your local network to access it so basically id like to have it under a domain like epic.example.com so i can do the captchas when im not home but is this safe?

**Comment by filikun** [comment]
I wonder if you could achieve this with the cloudflare tunnel?

In the newest relase of the docker container it states that you could use:

```Localtunnel setup
If you don't have the ability to port forward/reverse proxy on your network, you can still access captcha remotely by setting:

{
  "webPortalConfig": {
    "localtunnel": true,
  },
} 
```

Not sure if it's on the HA addon already (got a release today). I havent got HA notifications to work with the cloudflare tunnel though.

**Comment by IThundxr** [comment]
> I wonder if you could achieve this with the cloudflare tunnel?
> 
> 
> 
> In the [newest relase](https://hub.docker.com/r/charlocharlie/epicgames-freegames) of the docker container it states that you could use:
> 
> 
> 
> ```Localtunnel setup
> 
> If you don't have the ability to port forward/reverse proxy on your network, you can still access captcha remotely by setting:
> 
> 
> 
> {
> 
>   "webPortalConfig": {
> 
>     "localtunnel": true,
> 
>   },
> 
> } 
> 
> ```
> 
> 
> 
> Not sure if it's on the HA addon already (got a release today). I havent got HA notifications to work with the cloudflare tunnel though.

I think cloudflared might work I'll try that out and see

**Comment by filikun** [comment]
@IThundxr sweet, do let me know how it goes
