### ISSUE TITLE
🐛 [Seafile] localdisk mount, does not work

### ISSUE THREAD

**Issue by cokeman0** [alexbelgium/hassio-addons#710]
Logs shows localdisk label from config, but there in no access to it. worked i last version

**Comment by alexbelgium** [comment]
Hi, nothing changed in my code for that. Could to please post a log and options, i can do little otherwise. Thanks

**Comment by cokeman0** [comment]
Hi

9.0.14-pro (old version):
[9.0.14-pro.log](https://github.com/alexbelgium/hassio-addons/files/10767510/9.0.14-pro.log)
config:
PGID: 1000
PUID: 1000
SEAFILE_ADMIN_EMAIL: XXX
SEAFILE_ADMIN_PASSWORD: XXX
TZ: Europe/Copenhagen
URL: xxx.tplinkdns.com
data_location: /mnt/DataDisk/seafile
database: sqlite
localdisks: DataDisk

**Comment by cokeman0** [comment]
9.0.10 (latest version)
[9.0.10.txt](https://github.com/alexbelgium/hassio-addons/files/10767521/9.0.10.txt)
config:
CONFIG_LOCATION: /config/addons_config/seafile/config.yaml
FILE_SERVER_ROOT: http://homeassistant.local:8082
PGID: 1000
PORT: "8082"
PUID: 1000
SEAFILE_ADMIN_EMAIL: xxx
SEAFILE_ADMIN_PASSWORD: xxx
SERVER_IP: homeassistant.local
TZ: Europe/Copenhagen
URL: xxx.tplinkdns.com
data_location: /mnt/DataDisk/seafile
database: sqlite
localdisks: DataDisk

**Comment by alexbelgium** [comment]
Thanks indeed the local mount script doesn't execute, I'll investigate

**Comment by alexbelgium** [comment]
Really sorry about that i had a typo! It's corrected in the newly pushed version

**Comment by cokeman0** [comment]
Oki.

Just need to upload 4.5TB now, as seafile is stupid when losing local data
access and running on the MarinaDB.

It reset the filespaces, I'm trying to use SqlLite on the same drive as the
data, so if it loses access to local data, the DB is not deleted .... So
far it looks like the best way to go, and with more than 2.5TB uploaded
right now, the speed is still fantastic... :-)

**Comment by alexbelgium** [comment]
Sorry about that... An app like phpmyadmin allows go manipulate mariadb data but not sure if it would help correct the issue. Sqlite on the samd disk is a good idea though! I wss reflecting how to avoid the issue you faced and can't see another solution

**Comment by cokeman0** [comment]
Great, thanks, "-2" confirmed working again.

Perhaps a small write about sqllite on local drive, so others will not
suffer the reupload that I did :-)

**Comment by alexbelgium** [comment]
Thanks, done ;-)
