### ISSUE TITLE
🐛 [Gazpar2mqtt] Error with GRDF password

### ISSUE THREAD

**Issue by alexballow** [alexbelgium/hassio-addons#729]
Hello, I have the same problem with the GRDF_PASSWORD variable :

When starting the add-on, the log shows :

```
/etc/cont-init.d/99-run.sh: executing
/./etc/cont-init.d/99-run.sh: line 4: xxxx: unbound variable
/etc/cont-init.d/99-run.sh: exiting 1
```

xxxx being a part of my password
just before this part there is a "$" character and after this part is a "!" character.
The problem is not only the '$' character

I could still change my password but the site requires special characters

Thank you for your help
This bug looks like issue #507

**Comment by alexballow** [comment]
Hello, 
Thank you very much for the quickness ! :-)
I have updated and the problem is still here but different : 

Here is an example password : a$b1c2!!d3ef, an "\" is added before the dollar.

```
GRDF_PASSWORD=a\$b1c2!!d3ef
MQTT_HOST=xxx.xxx.xxx.xxx
MQTT_PORT=xxxx
/etc/cont-init.d/99-run.sh: executing
/./etc/cont-init.d/99-run.sh: line 4: b1c2: unbound variable
/etc/cont-init.d/99-run.sh: exiting 1
```

**Comment by alexbelgium** [comment]
Thanks, I've tried another approach

**Comment by alexbelgium** [comment]
Could you please let me know the result? Thanks!

**Comment by alexballow** [comment]
Hello,

So, i've installed the your release, and now, i 've a 'LOGIN_INVALID_ATTEMPTS' error when connecting to the grdf site. I checked my password (I even changed it again).

I can send you my log (anonymized) if you want.

**Comment by alexbelgium** [comment]
Hi, then this is an issue for the app that I can't solve serverwise. The developer is @yukulehe, and this is a similar issue : https://github.com/yukulehe/gazpar2mqtt/issues/78

Given it's due to the app and not the addon, I'll close this issue, thanks
