### ISSUE TITLE
Business card scanning application

### ISSUE THREAD

**Issue by althafis** [alexbelgium/hassio-addons#73]
Is this available in the Arabic language & saving images of the business cards?

**Comment by alexbelgium** [comment]
Hi, this seems more a job for an app than an HA addon, or would you have a dockerhub image example of a project that could be used?

Thanks

**Comment by alexbelgium** [comment]
I see that a reddit thread arrived to the same conclusion : https://www.reddit.com/r/selfhosted/comments/3pgd45/any_selfhosted_visiting_card_scanners/

I'll close the topic, unless you think it's really useful and provide me with a currently existing project github or dockerhub link from which I could start looking if the addon is feasible.

Thanks!

**Comment by althafis** [comment]
Thanks Alex.I am either looking for any option which will make it..

Using non-nextcloud or non-self-hosted also fine

**Comment by alexbelgium** [comment]
Ah, I think I misunderstood your request...

You wanted to know if you can use Nextcloud to store business card images and use OCR in arabic language to extract information ? I think this would work using full text search, but it would not create contacts out of business cards like an app such as camcard (paid) would do...

Apart from nextcloud, If you want a dedicated app to scan business card and create contacts out of it, I'm not sure if there exists free apps with good OCR... I see paid app exists like https://magneticonemobile.com/. For free apps I read that haystack is good (https://play.google.com/store/apps/details?id=com.theHaystackApp.haystack&hl=en_US&gl=US) but not all people are happy with it... One good site to look for different apps scanning Business cards is here : https://alternativeto.net/software/camcard/...

**Comment by althafis** [comment]
Once Again,Thanks in tons for providing all valuable information.

As a result of some study ,I found there are paid apps available but not comprehensive.

Like zoho app is good but it does not have Arabic language support.
World Card has it but quality of Arabic language is not good, even it doesn't scan both sides of the card.

**Comment by alexbelgium** [comment]
Have you looked at https://www.abbyy.com/products/mobile/business-card-reader/ar/ ? It's one of the biggest names in OCR hopefully it is good...

**Comment by althafis** [comment]
Tried ,somehow it doesn't meeting all criteria!

It would have been really good if could had a solution with the below criteria have tried since couple of weeks luck yet.


1 ) Arabic language Support
2) Two sided content capture
3) Two sided image  capture and store it along with the text.

Alex, You have been a great help.

I think if a solution has above features then it would make a better impact.
3)

**Comment by alexbelgium** [comment]
Indeed, the solution you describe would be nice... Sadly I'm not an app developer so I won't be able to help you more. I'll close this issue except if you want to talk more about it - but perhaps people on reddit.com could also help you better than me to find an app that fits your needs! Good luck and have a nice day
