### ISSUE TITLE
Editing trusted_domains has no effect after nextcloud has already been setup

### ISSUE THREAD

**Issue by bobloadmire** [alexbelgium/hassio-addons#730]
Editing trusted_domains has no effect after nextcloud has already been setup, there is a config file in nextcloud you can edit to update this, but I have no idea how to access the file from homeassistant, or where its located, editing the add-on config has no effect unless it's modified before installation.

**Comment by alexbelgium** [comment]
Hi, that's strange the code removes all trusted domains and readd them. I'll try next week on my own installation

**Comment by bobloadmire** [comment]
Yeah, I'm not sure, I moved my home assistant instance to a new IP on a different machine, but adding that IP still says that it's not a trusted domain, but I can still access from the old IP that was originally there

**Comment by alexbelgium** [comment]
Could you please check your logs when starting? The relevant part starts with:
```
INFO: Trusted domains set in the configuration. Refreshing domains.
[06:27:50] INFO: ... removing previously added trusted domain (except for first one created)
```

Thanks
