### ISSUE TITLE
🐛 [Portainer 2.17.1] Failed to install add-on

### ISSUE THREAD

**Issue by vangelis86** [alexbelgium/hassio-addons#732]
Can't install ghcr.io/alexbelgium/portainer-amd64:2.17.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2.17.1&fromImage=ghcr.io%2Falexbelgium%2Fportainer-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by alexbelgium** [comment]
Thanks, I've relaunched build and it succeeded
