### ISSUE TITLE
✨ [REQUEST] gluetun

### ISSUE THREAD

**Issue by kolossboss** [alexbelgium/hassio-addons#734]
**Which addon?**

[gluetun](https://github.com/qdm12/gluetun)

A docker image to connect to your vpn provider.

**Is your feature request related to a problem? Please describe.**

I would feel better if I can route my addons to a VPN

**Describe the solution you'd like**

A addon with gluetune image. When active and running, you can route other docker images through gluetun, using Portainer to configure.

Thanks a lot

**Comment by alexbelgium** [comment]
Hi, you could use the official addon Tailscale. I'm usually trying to avoid duplicating existing functions, plus this is an official addon which means you'd have a much better support. Also, I really don't have much time to add addons for the moment... Thanks!

**Comment by kolossboss** [comment]
Hi,
Thanks for reply.
Are your sure Tailscale has the same functionality?
With gluetun, you can connect to a paid VPN provider like ExpressVPN or NordVPN.
Tailscale is only to connect your private devices.
Or do I misunderstand something?

I understand if you dont have the time for this. Its just a request. Thanks for all the time you put into this 😁

**Comment by alexbelgium** [comment]
Well I don't use the vpn so I'm not sure if it has the same function... I just remembered having read about tailscale ;-) actually I'm wrong it seems it was wireguard that allowed it (https://www.nstec.com/how-to-set-up-home-assistant-with-a-vpn/)

**Comment by kolossboss** [comment]
Gluetun is more to encrypt internet traffic for "sensitive" data like torrent, jackett or usenet apps (like nzbget).
Hassio Addons like wireguard or tailscale are more to connect to your local network from an extern connection.

**Comment by alexbelgium** [comment]
Ok, thanks for the info. Transmission and qbittorrent have vpn capabilities (especially transmission) but indeed then there is no other existing solution

**Comment by kolossboss** [comment]
Yes, but sadly both are torrent client, I'm more familiar with usenet. 😃 
There is also a usenet newsreader client with openvpn support ([SABnzbd](https://hub.docker.com/r/mumiehub/sabnzbdvpn)).
But the main problem (time) still exists 😁 
(And with gluetun can encrypt every docker container if needed)

**Comment by lotohov** [comment]
let me vote for this addon cos it add vpn to any docker container .. but sadly still this cant be configured from ha.

**Comment by kolossboss** [comment]
You can configure the network this very easy with Portainer. I'm not sure if Home Assistant detect this as "unsupported".
But sure, I also think HA is not the right Environments for this. 
I the meantime I setup a second docker Environments and routed my container through gluetun. Its working perfect.

I think I can close this. Thanks a lot.

**Comment by alexbelgium** [comment]
Thanks for the feedback, and anyway i don't think I would have time in near future to work on it. Indeed HA os is meant for a ready to use system, for more advanced usage it is better to have it as a supervised installation...
