### ISSUE TITLE
🐛 [qbittorrent] 4.5.1 Vulnerability found

### ISSUE THREAD

**Issue by nathang21** [alexbelgium/hassio-addons#744]
Qbittorrent

- Addon name : qbittorrent
- Addon version : 4.5.1-r1-ls246-2

**Describe the bug**

Qbittorrent has a vulnerability, which is fixed in version 4.5.2 already. Technically this does not impact HA users who run on linux, however some torrent trackers are blocking all qbittorrent clients running this outdated version as a precaution. 

I'm not sure how often the updater-bot runs, but it's been a few days so I figured id file an issue to track this. 

**Vulnerability details**

A vulnerability was recently found in qBittorrent WebUI v4.5.1 on Windows. It allows the attacker to see arbitrary files content on your computer.

v4.5.0 seems to also be affected, however it's not clearly confirmed yet.
Older versions (v4.4.5 and below) are not vulnerable.
If WebUI is used only locally and it's port is not open to the internet, you're not vulnerable.
Considering the fix, only the Windows version is vulnerable, due to backslashes in paths.

If you are using WebUI in qBittorrent client of versions 4.5.1 or 4.5.0 on Windows,
and it is accessible from the internet, turn the WebUI off ASAP and wait till 4.5.2 update
before turning it on again, or downgrade back to v4.4.5 and wait till 4.5.2 as well.

Quick Q&A

I'm just using qBittorrent v4.5.1 normally and don't know what WebUI is, am I vulnerable?
No. WebUI is off by default, so if you don't know what it is or didn't turn it on because you don't need it, you're safe. It only affects those who use WebUI.

I'm using WebUI with qBittorrent v4.5.1 on Linux or Mac, am I vulnerable?
No considering the fix, only the Windows version is vulnerable, due to backslashes in paths.

I'm using WebUI with qBittorrent v4.5.1, but the port isn't open to the internet, only connectable from LAN, or VPN network, am I vulnerable?
No. You are safe. It only works if the WebUI port is connectable for the potential attacker.

I'm using WebUI with qBittorrent v4.5.1, and the port is/was available from the internet, can the attacker mine crypto, install malware, make me part of a botnet, or do other harmful things on my machine? Do I need to do a virus scan or something?
No. The vulnerability only allows the attacker to read the content of files on your computer, to see their content. It can access the files the user you're running qBittorrent from has access to.

Will the issue be fixed in v4.5.2?
Yes, it should be. Check the changelog when it's out to make sure.

All credit where due this post is copied from another place that beat us to making a good one about it

SECURITY: This version contains a security bugfix in the web server. The bug allowed for any file on the user's filesystem to be served without any authentication. This affects users that have enabled the WebUI/WebAPI. It seems to affect only v4.5.0 and v4.5.1 on Windows.

**Comment by alexbelgium** [comment]
Hi, thanks for the post and detailed explanations. Actually the updater runs every Saturday, so tomorrow everything should be updated. Thanks for reporting

**Comment by alexbelgium** [comment]
Update done
