### ISSUE TITLE
🐛 [Portainer] Unreliable since v2.17.1-4 - supervisor entities regularly unavailable

### ISSUE THREAD

**Issue by bcutter** [alexbelgium/hassio-addons#745]
**Which addon?**

- Addon name : Portainer
- Addon version : 2.17.1-4

**Describe the bug**

Since running v2.17.1-4 (before I was using I think v2.17.1-2 - lost overview with this intransparent micro release updates), these supervisor provided entities are regularly `unavailable`:
- `sensor.portainer_cpu_percent`
- `sensor.portainer_memory_percent`

This only happens for the Portainer addon, others are just fine.

**To Reproduce**

1. Update to Portainer v2.17.1-4
2. Do nothing for some time
3. Watch listed entities switching to `unavailable` regulary, turning back to normal operation after few minutes

```
2023-03-04 06:37:00.300 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/db21ed7f_portainer/stats request
2023-03-04 06:37:00.302 WARNING (MainThread) [homeassistant.components.hassio] Could not fetch stats for db21ed7f_portainer:
-sensor.portainer_cpu_percent
-sensor.portainer_memory_percent
-sensor.portainer_cpu_percent
-sensor.portainer_memory_percent
```

**Full addon log**

Nothing in there corresponds to any time code the issue happens.

**Full addon config**

Default config, only password is set of course.

**System**

- Supervisor version: 2023.01.1
- Host system version: 9.4

**Comment by alexbelgium** [comment]
Given the number of feedback on portainer despite the very little changes to my code, I wonder if the issue is not more due to HA changes. The only difference between v2.17.1-2 and v2.17.1-4 is how the app service is called (s6 cont-init.d vs s6-rc.d).

**Comment by bcutter** [comment]
Interesting, I'll follow that one.

But please note: nothing else has changed on my setup. Same HA OS, Supervisor and HA Core version for more than 50 days.

Unfortunately I can't downgrade Portainer to test and prove this, as the backup seems to be not available anymore.

**Comment by alexbelgium** [comment]
Would you like me to rollback to v2.17.1 ? v2.17.1 didn't build due to an issue with dockerfile so I had to push v2.17.1-1. Versions v2.17.1-2 to 4 were linked to switch to s6rcd to avoid an error where portainer seemed to erroneously report run status

Given there is no change in main codes, rollback won't have any impact on systems

**Comment by bcutter** [comment]
It's just a never ending story, happening many times a day.
![grafik](https://user-images.githubusercontent.com/13799156/222965432-f7061dab-2c2a-4cd5-8348-e1b0fb1a65bc.png)

Of course I could just put those sensors to the ignore list, but silencing actual issues never seems to be a good idea to me.

I found a backup from before updating Portainer and am gonna try to restore it and see if it changes.

![grafik](https://user-images.githubusercontent.com/13799156/222965381-dec62967-06b5-4e13-be41-3ebc87a7c822.png)

**Comment by alexbelgium** [comment]
Thanks, please let me know

**Comment by bcutter** [comment]
As expected: not one single incident with 2.17.1-2 since two days. Nothing else changed.

**Comment by alexbelgium** [comment]
Then, let's keep it that way as it is working

**Comment by bcutter** [comment]
So you want me to never update Portainer again? Why did you close this issue?

I'm on 2.17.1-**2**:

![image](https://user-images.githubusercontent.com/13799156/223679685-2c2143a8-f542-4ff5-ae16-2f1296488a18.jpeg)

I can double check and update to latest 2.17.1-4 again and see if the unavailable entities return.

At the moment definitely not closed.

**Comment by alexbelgium** [comment]
> Then, let's keep it that way as it is working
I meant that I would keep the 2.17.1-2 code and revert the s6-rc.d update ; indeed I had not yet performed the revert which is now completed.

Please note that I find your tone very aggressive, knowing that I am doing this work freely on my own time and that all updates are mostly me taking time off my other activities to provide you with addons to perform your work. You might have communicated the same elements (that indeed an update was still provided despite the intent to rollback) in a more non confrontational manner. This is actually one of the reason why Frenck (one of the main dev) had removed Portainer from the HA repository.

Best regards

**Comment by bcutter** [comment]
Based on your post I thought you overlooked what I wrote and were thinking the 2.27.1-**4** is working fine now for me.

And I also didn't get (due to detailed information) what is meant with "let's keep it that way". So all in all probably lost in translation/communication 😀 

What exactly did you interpret as "aggressive tone"? Definitely not intended by me, maybe I can learn and check wordings based on your input.

I totally value your work 👍 

Fraenck removed Portainer from the official repo because people did bad stuff with it, sometimes rendering their HA instances inoperable. But of course every addon/piece of software creates maintenance efforts, totally get you.

On-topic:
Funnily since updating to v2.17.1-4 AND the auto-update of the Supervisor from 2023.1.1 to 2023.3.1 the issue did not appear until now, even it's only few hours. Maybe something in the supervisor changed which also affects the entity state reporting? Seems like it was an important update according to https://alerts.home-assistant.io/alerts/security-disclosure/.
Update: probably I installed the updated -4 already at least according to the release notes and the fact there's no -5 version available to install. In short: looking good for now 👍

**Comment by alexbelgium** [comment]
Thanks ; then we are aligned ;-)

Re. versioning, HA only checks if the version name is different and not if it is incrementally increased. Therefore, it's only a matter of time that your supervisor updates the repositories and "sees" the version 2.27.1-2 that it will then propose to you as an "upgrade". The "-4" version should have been more reliable, given that it implemented the new "s6-rc.d" services system, plus periodic healthchecks. The "-2" version (on which future versions will be based) on the other hand did not contain the healthchecks, plus relied on the legacy folders (/etc/cont-init.d for oneshot scripts and /etc/services.d for services). The s6-rc.d system still calls on those folders through its legacy system to avoid code breakage (slightly more detailed description here)[https://github.com/just-containers/s6-overlay#init-stages]. 

Well, as long as there is no visible downsides I'll keep it that way then. It is often very hard to discriminate issues stemming from addons from the ones originating from the HA os updates

**Comment by bcutter** [comment]
Today I updated to latest 2.17.1-6
![grafik](https://user-images.githubusercontent.com/13799156/224512239-8cdc973f-e34a-4f12-b136-f125de85339d.png)

While before there were no issues the last days, now with 2.17.1-6 the Portainer supervisor entities again regularly render unavailable 😞 

![grafik](https://user-images.githubusercontent.com/13799156/224512261-566b18fc-ac4c-41b5-9939-4d4ded513513.png)

Even I lost overview of all the recent up- and downgrades and micro versions, I understand that the 2.17.1-6 should basically be fine on this.
As these newly incidents make no sense to me, I tend to
- have a much deeper look at https://github.com/home-assistant/core/issues/75187 and similar ones and
- probably just gonna silence (ignore) `sensor.portainer_cpu_percent` and `sensor.portainer_memory_percent` entities for now (or forever).

**Comment by alexbelgium** [comment]
This is the exact same code as 2.17.1-2, with the addition of healthcheck. I'll adapt the healthcheck to see if this prevents the unhealthy state. Given that you reported once this issue with -4 but then it seemed to work again when you went back with this version, this is perhaps linked to your system

**Comment by bcutter** [comment]
After being quite for some time, today I updated from 2.17.1-9 to 2.18.1 at around 3 pm. Since then... again regularly `unavailable` (while having an ignore time of 2 minutes in place already):

![grafik](https://user-images.githubusercontent.com/13799156/233677266-8a1f7337-71f0-4213-b4cd-2c75446141f3.png)

![grafik](https://user-images.githubusercontent.com/13799156/233677531-049cd3d1-4422-4912-9432-a04662347bbc.png)

**Comment by alexbelgium** [comment]
Indeed this might be linked to system specificities as I can't replicate. And seeing the sporadic effect, perhaps it is linked to specific periods such as just after upgrading

**Comment by bcutter** [comment]
That's a good theory. 3 days ago I updated the File Editor addon. Since that and today intensively I get alerts on that one... no idea what Supervisor messes up here. Currently I tend to say: probably not Portainer specific.

![image](https://user-images.githubusercontent.com/13799156/234924286-19c27b81-52b0-4a0e-9881-d1817986833a.jpeg)
