### ISSUE TITLE
✨ [REQUEST] free-games-claimer

### ISSUE THREAD

**Issue by amosyuen** [alexbelgium/hassio-addons#747]
!!! I have a real life job in parallel to this addon, and don't think I'll be able to add new addons for the moment. You can still however express your interest in case someone would do it

**Which addon?**
https://github.com/vogler/free-games-claimer. Supports epic games, prime gaming and GOG

**Is your feature request related to a problem? Please describe.**
Claim free games from multiple services. 

\*\*If a new addon, have you checked on Google that such as addon doesn't already exists?**
Yes

**Describe the solution you'd like**

Configure single add-on to claim all free games.

**Describe alternatives you've considered**

Not aware of other alternatives

**Comment by diamant-x** [comment]
there's an epic games one already.

https://github.com/alexbelgium/hassio-addons/tree/master/epicgamesfree

**Comment by amosyuen** [comment]
That one always prompts for a security code, so isn't that helpful. [free-games-claimer](https://github.com/vogler/free-games-claimer) doesn't prompt and supports more accounts.

**Comment by KairuByte** [comment]
Oh my goodness, thank you For bringing this project to my attention. It seems they are looking to as even more services to The grabber as well!

**Comment by hacshacdgacs** [comment]
As someone who's had issues with the epicgamesfree addon in the past (was unable to get it to actually claim games because of the captcha) I would also like this if possible.

**Comment by alexbelgium** [comment]
I'll look at it

**Comment by alexbelgium** [comment]
Would this addon remove the epicgamesfree one? For sake of simplification

**Comment by hacshacdgacs** [comment]
I believe so but I don't personally use the epicfreegames addon so it may
be worth putting a poll/question for them if that's an option?

**Comment by KairuByte** [comment]
I think it makes sense to keep both. They use different methods, and epic games free tends to be much more reliable from what I'm seeing.

**Comment by alexbelgium** [comment]
Is the latest working?

**Comment by KairuByte** [comment]
The latest egf is still working, and the latest *container* for fgc is working. I tried to set up the fgc app last night but ran into issues with it accepting creds from the config file, so need to sit down today and figure out what's going on.

**Comment by alexbelgium** [comment]
On theory values from the config file (in yaml format) are exported as env variables

**Comment by KairuByte** [comment]
I'm not sure why, but I am getting constant stalls on start. It gets to the point that I *am* seeing output from the container, but it just stops sometimes moments after it starts up. Is that likely an issue with the container itself, or is that potentially a misconfiguration on the addon "wrapper" side?

**Comment by alexbelgium** [comment]
Well config.yaml is my internet system to,export env variables. Not sure about config.env

**Comment by MaxWinterstein** [comment]
Just found a minute and was going to check if 'epic-games-free' is fixable, and was confused where the readme part was gone. Found that you renamed the whole folder, therefore it looked 'abandoned' to me.

Tried the new 'free-games-claimer' - currently shown as 'epic-games-free' and had just one weird thing. It was not showing the novnc server, nor something useful in the logs. After adding a real port to the VNC port mapping everything started fine. After removing it still works fine. Not sure how settings are handled internally, and if a setting that once was overwritten is now empyt/null - or at least other than it was before.

To make every business consultant happy, here is the positive feedback: Would be nice to select which game plattforms i would like to check, as e.g. I have no usage of amazon prime gaming.

Keep up the good work :v:

**Comment by KairuByte** [comment]
Yeah, I'm having trouble getting novnc running here as well, and my entries in the config file don't seem to be working at all. I tried adding a vnc port in the network config section of the addon to no avail. I may need to remove and re-add or something.

As for picking and choosing which service works, technically the following command can be appended to the end of the docker run command to achieve that, leaving out what you don't want: `bash -c node epic-games; node prime-gaming; node gog` it may be possible to incorporate that into the plugin but I'm not sure.

**Comment by alexbelgium** [comment]
Latest version includes custom commands through addon options as you propose, and usage of the config.env instead of my config.yaml. The config.env uses the nomenclature `KEY=VALUE` instead of the previous yaml that was `KEY: VALUE`

**Comment by alexbelgium** [comment]
> Just found a minute and was going to check if 'epic-games-free' is fixable, and was confused where the readme part was gone. Found that you renamed the whole folder, therefore it looked 'abandoned' to me.

Hi - sorry this was unintended, I had pushed the folder in the free-games-claimer one on explorer :-) corrected now

**Comment by alexbelgium** [comment]
Not working yet

**Comment by alexbelgium** [comment]
Hi, latest version is tested to start. Could you please check the applicability of the config.env ? I've modified the format to `export KEY=VALUE`

**Comment by KairuByte** [comment]
Okay, I got it to run. Wrapping strings in single quotes, `export` keyword in front (though I'm surprised that can't be simulated) does work. Integers can remain unquoted no issue.

One "major* problem at the moment, is the command entry. The first command works, anything after that fails to ever run. For example, if you set `node prime-gaming ; node gog ; node epic-games` the prime-gaming module does indeed run, but the gog and epic-games modules never get run.

**Comment by alexbelgium** [comment]
Would `"node prime-gaming" "node gog" "node epic-games"` work? I'll check this evening

**Comment by KairuByte** [comment]
I tried looking into that, but it's proving difficult since I'm actually terrible with docker. My initial thought was wrapping them all in a double quote together, so it's seen as a single command. But I don't have proper knowledge of what that script being referenced actually does (I assume it's part of the original image?...) so I can't speak with any authority.

**Comment by alexbelgium** [comment]
Thanks, I've pushed a new version. Now, the CMD_ARGUMENTS should be in the form : `node prime-gaming; node gog; node epic-games` and the config.env should be in the form `KEY='VALUE'`. I've also corrected the default files but as you have already installed the addon it won't probably use the new defaults.

**Comment by KairuByte** [comment]
Sorry to be the bearer of bad news: ```

/./etc/cont-init.d/99-run.sh: line 46: AZE: unbound variable
/etc/cont-init.d/99-run.sh: exiting 1
```

**Comment by alexbelgium** [comment]
That's my test variable, I went too fast and need to push another version

**Comment by alexbelgium** [comment]
still not working

**Comment by amosyuen** [comment]
I got it running, but then it needs me to login in UI. So when I try to access the no VNC port the chrome tab shows the loading icon for a while then eventually says site can't be reached.

**Comment by MaxWinterstein** [comment]
btw, works fine for me, thanks :)

**Comment by alexbelgium** [comment]
For me it works too... Perhaps a matter of ram availability too as I think it requires quite an amount?

**Comment by amosyuen** [comment]
Hmm, I have 2.2 GB of free memory so I feel it's unlikely a memory problem. I also tried accessing from a different browser with same problems.

**Comment by KairuByte** [comment]
I'm still seeing the issue of the first module running, but no others. I'm wondering if I'm missing something since two different individuals have said things are working for them.

I also find the idea of RAM being an issue, dubious. I regularly have >4GB of ram available, but noVNC has never worked.

**Comment by alexbelgium** [comment]
When I say it works for me, I mean I can access Firefox through the novnc webui, and even go on internet through it. I havent tested other functionalities. I'll look again for multi modules launch

**Comment by Stooovie** [comment]
For whatever reason none of these claimer addons work for me. This one launches successfully (no errors in log) but tying to access the webUI spins indefinitely and the addon takes 50% CPU. I don't have any weird network config, it's all typical 192.168. IPs.

**Comment by KairuByte** [comment]
Yeah, I can't get the web Ui working either. You can use the config.env to get yourself logged in though. The variables are all listed on the main repo.

**Comment by Stooovie** [comment]
I can't. I never got the text prompt. I can, however, run the very same config env file with docker outside of HA (I am used to run docker stuff in HA as I didn't have other options before, now I do), and it does work there for me. No problem, thanks!

**Comment by alexbelgium** [comment]
So weird. Here is my log:
```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Free Games Claimer (in development)
 automatically claims free games on the Epic Games Store, Amazon Prime Gaming and GOG
-----------------------------------------------------------
 Add-on version: 1.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.5.2
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[10:08:57] INFO: Execute /config/addons_autoscripts/free-games-claimer.sh if existing
[10:08:57] INFO: ... script found, executing
dos2unix: converting file /config/addons_autoscripts/free-games-claimer.sh to Unix format...
/etc/cont-init.d/20-folders.sh: executing
Creating config location ...
Copying files if needed...
/etc/cont-init.d/99-run.sh: executing
[10:08:58] WARNING: The config.env file found in /config/addons_config/free_games_claimer will be used. Please customize according to https://github.com/vogler/free-games-claimer/tree/main#configuration--options and restart the add-on
 
 
[10:08:58] INFO: Starting the app with arguments node epic-games ; node prime-gaming ; node gog
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080
2023-05-30 10:08:58.288 started checking epic-games
Not signed in anymore. Please login in the browser or here in the terminal.
Open http://localhost:6080 to login inside the docker container.
Login timeout is 180 seconds!
Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).
```

And going to `http://homeassistant.local:6080/` shows 
![image](https://github.com/alexbelgium/hassio-addons/assets/44178713/abb76445-9fdd-4087-aaec-5beaaff80e5c)

I'll do some other tests.

**Comment by alexbelgium** [comment]
Btw even with default settings (running straight the container from upstream), it's using 47.1% of my 8go ram rpi4

**Comment by alexbelgium** [comment]
Last version pushed (1.4-test8) fully works on my system.
1. I uninstalled everything and clean reinstalled.
2. Started addon, waiting for log to complete (until "started checking epic-games")
3. Logged on webui on epic
4. Logged in epic (the addon then moved on automatically to prime-gaming)
5. Logged on webui on prime
...

10% ram on a 16gb system

Full log : 
````bash
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Free Games Claimer (NOT WORKING)
 automatically claims free games on the Epic Games Store, Amazon Prime Gaming and GOG
-----------------------------------------------------------
 Add-on version: 1.4-test8
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.5.2
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[15:00:55] INFO: Execute /config/addons_autoscripts/free-games-claimer.sh if existing
[15:00:55] INFO: ... script found, executing
dos2unix: converting file /config/addons_autoscripts/free-games-claimer.sh to Unix format...
/etc/cont-init.d/20-folders.sh: executing
Creating config location ...
Copying files if needed...
/etc/cont-init.d/99-run.sh: executing
[15:00:55] WARNING: The config.env file found in /config/addons_config/free_games_claimer will be used. Please customize according to https://github.com/vogler/free-games-claimer/tree/main#configuration--options and restart the add-on
 
 
[15:00:55] INFO: Starting the app with arguments node epic-games ; node prime-gaming ; node gog
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080
2023-05-30 15:00:56.100 started checking epic-games
Not signed in anymore. Please login in the browser or here in the terminal.
Open http://localhost:6080 to login inside the docker container.
Login timeout is 180 seconds!
Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).
? Enter email ‣  ✖ Enter email ·  timeout
Waiting for you to login in the browser.
page.waitForURL: Timeout 180000ms exceeded.
=========================== logs ===========================
waiting for navigation to "https://store.epicgames.com/en-US/free-games" until "load"
============================================================
    at file:///data/epic-games.js:102:16 {
  name: 'TimeoutError'
}
2023-05-30 15:07:02.376 started checking prime-gaming
Not signed in anymore.
Login timeout is 180 seconds!
Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).
? Enter email ‣  ✖ Enter email ·  timeout
Waiting for you to login in the browser.
```

**Comment by alexbelgium** [comment]
I've created a request on the upstream repo here : https://github.com/vogler/free-games-claimer/issues/149

**Comment by viny182** [comment]
Hello, not working on a HAOS 10.2 am64 / generic x86-64 installation. which makes it weirder.

Direct VNC is not reacheable on port 5900, so noVNC is also not reachable as well on :6080 trough browser... The tab opens, and keeps spinning for a while and eventually a timeout error is displayed.

I've also added a comment in here https://github.com/vogler/free-games-claimer/issues/149

**Comment by viny182** [comment]
update: after insisting a lot to connect trough VNC direct client on port:5900 I was able to connect after pressing connect button several times on my VNC Client! However, it was already on one of the later stages, during the GOG login, so I have missed the login for Epic and Prime...

**Comment by alexbelgium** [comment]
Hi sorry I disabled the function to customize the nodes to be as close as possible to the base container to avoid sources of issues

**Comment by KairuByte** [comment]
Just as a side note for the env variables, it is not possible to use the built in way of using them? The config file appears to be loaded as described here: https://github.com/vogler/free-games-claimer/issues/143#issuecomment-1551822765

**Comment by alexbelgium** [comment]
What is strange is that the config.env file is already pushed in the workdir here : 
https://github.com/alexbelgium/hassio-addons/blob/2d56211be25865a38a489d476eb1c4d8128092d5/free_games_claimer/rootfs/etc/cont-init.d/99-run.sh#LL20C1-L21C37

Just realized perhaps I should do /data/data/config.env to respect the code you were showing. I'll push a new version to do that

I spent a lot of time trying to solve the VNC not starting thing - but it seems to be getting nowhere.

**Comment by alexbelgium** [comment]
I also need to re-enable the option to choose which elements to run, I'll push a test10 version

**Comment by alexbelgium** [comment]
config.env doesn't seem to be working, either in /data/config.env or /data/data/config.env (given that /data is the initial WORKDIR)

**Comment by KairuByte** [comment]
That's very odd... I think the only time I've ever seen the env variables work was when they needed `export` in front of them. But looking at the code every way you've set them up looks like they should work.

Maybe if you dropped the later set +a/-a? I wonder if that might be causing the code to ignore the set variables somehow? _Very_ much a shot in the dark though.

**Comment by alexbelgium** [comment]
When they needed export, I didn't use the embedded config.env system but instead read the file line per file and exported them in the bash shell 

I can redo it. Set -a was to avoid error messages for undeclared variables

**Comment by alexbelgium** [comment]
Current dev status (test11) : 
- [ ] config.env working in test11 (variables passed)
- [ ] sequencial execution of CMD_ARGUMENTS (use format `node gog; node prime-gaming`
- [ ] succesful execution of free games claimer scripts (to confirm)
- [ ] VNC & noVNC reliable usage

**Comment by KairuByte** [comment]
I did try adding `export` previous to the most recent with no luck.

If you wanted to do a real quick test (I will asap) you can try setting the size to 1024 by 768 and seeing if the size message properly reflects that just after the image is spun up.

**Comment by KairuByte** [comment]
After testing `test11` and `test12` I can confirm that the environment variables do appear to be properly loading!

That said, `test12` seems to still have issues with setting the command arguments. Using `node epic-games ; node prime-gaming; node gog` I am seeing ```

Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Free Games Claimer (NOT WORKING)
 automatically claims free games on the Epic Games Store, Amazon Prime Gaming and GOG
-----------------------------------------------------------
 Add-on version: 1.4-test12
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[16:18:25] INFO: Execute /config/addons_autoscripts/free-games-claimer.sh if existing
[16:18:25] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
Creating config location ...
Copying files if needed...
/etc/cont-init.d/99-run.sh: executing
[16:18:26] WARNING: The config.env file found in /config/addons_config/free_games_claimer will be used. Please customize according to https://github.com/vogler/free-games-claimer/tree/main#configuration--options and restart the add-on
 
[16:18:27] INFO: Starting the app with arguments node epic-games; node prime-gaming; node gog 
 
Xvfb display server created screen with resolution 1024x768
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080
node:internal/modules/cjs/loader:1093
  throw err;
  ^
Error: Cannot find module '/data/epic-games;'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v19.9.0
[16:18:27] INFO: All actions concluded, addon will stop```

**Comment by alexbelgium** [comment]
Thanks :) I'll add automatic stop. And check sequential execution. I thought I had the error message only because I didn't have a real account to test

**Comment by alexbelgium** [comment]
Latest version should work (except for VPN), it will also show in blue exported values from config.env

**Comment by KairuByte** [comment]
Just... in case, before I run it. Are you censoring anything with the word password in the env variable? You are able to pass usernames and passwords, and keeping a log of those doesn't sound like a good idea.

**Comment by alexbelgium** [comment]
Well, logs are temporary, they only appear but are not stored anywhere that I am aware of. Anyway it would still be stored locally - which is already the case from the passwords being written as plain text in the config.env. So really the key element is to keep your HA system secure. But I can remove this feature if you prefer

**Comment by KairuByte** [comment]
Apologies for the late follow up. I’ve been able to test and can confirm things run. However. Sequential running does not appear to work? `node epic-games; node prime-gaming; node gog` results in only `node epic-games` being run, and the log appears to confirm this with this line `[23:29:23] INFO: Starting the app with arguments "node epic-games"`

**Comment by alexbelgium** [comment]
Hi, indeed sequential running is executed but doesn't connect... Well I'll have to look again

**Comment by KairuByte** [comment]
Bad bot

**Comment by alexbelgium** [comment]
Well it reminded me of this sorry I was quite caught up in work. I'll have a look again soon

**Comment by KairuByte** [comment]
Haha no worries, it's not like you're paid to do this, and I'm fairly certain you don't even have a use for this particular add-on.

**Comment by alexbelgium** [comment]
Hi, I think I got it in version test22. Please let me know!

**Comment by amosyuen** [comment]
NoVNC still isn't working for me. But looks like it's able to claim epic games for me.

**Comment by KairuByte** [comment]
Things kinda work now.

Honestly, I think I’m going to revert to using my PC and waking it to handle this… It seems horribly slow on a Pi, and sometimes takes so long things break. I think this may just be an inherent limitation of the Pi and/or image.

**Comment by hacshacdgacs** [comment]
VNC doesn't work for me either but can confirm that Epic and GOG will claim games without me needing to restart the addon. I'm running this on an old machine and not having any issues with the speed @KairuByte so that may just be a Pi issue.

**Comment by alexbelgium** [comment]
I think VNC doesn't work due to rpi being too slow... It didn't work on my rpi4 either...

Regarding the script in itself however it seems to run fine on my rpi4 !

**Comment by alexbelgium** [comment]
Closed with disclaimer that novnc does not work but that the add-on can still work using the config file

**Comment by amosyuen** [comment]
Hi, would you consider an option to mount a config directory instead of just the config file? Reason is that there are options like `RECORD=1` that will record a video to help debug problems in `config/record` directory, but since directory isn't mounted there isn't an easy way to access the recorded file.

Another side effect would be that the browser state is also saved in there. That could be useful for uninstall / reinstall.

**Comment by Teberon** [comment]
I am missing something here... I configured the env correctly adding discord, eg, ap, and gog but there's no way to open anything. How do I use this: "Please use config.env to execute the script"?

**Comment by alexbelgium** [comment]
Hi, I don't use the addon so can't help you with the config.env content. However, I can see from your log that the config.env file is correctly loaded by the addon `Getting variables from /config/addons_config/free_games_claimer/config.env`

So you would have more chance trying on their repo https://github.com/vogler/free-games-claimer. From the log it seems you haven't filled a #password tag in the config.env but they would know better than me what that means.
