### ISSUE TITLE
🐛 Calibre Docker version out of date

### ISSUE THREAD

**Issue by blackshoals** [alexbelgium/hassio-addons#748]
Calibre

- Addon name : Calibre
- Addon version : v6.13.0-ls204

The addon initiates with an older version of Calibre (6.7.1) rather than the current one (6.13.0). It functions fine and the addon updater looks like it is pointing to the correct Docker version of 6.13.0 but trying the in-app updater, restarting the addon and rebooting the system does not trigger an update.

**Comment by alexbelgium** [comment]
Thanks, it's updated
