### ISSUE TITLE
[Wger] - 500 Internal Server Error on adding exercise

### ISSUE THREAD

**Issue by paulgbrichardson** [alexbelgium/hassio-addons#753]
I get the following error from the logs when trying to add an exercise to a workout.   

```
[10/Mar/2023 11:15:58] "GET /en/workout/set/day/1/set/add HTTP/1.0" 500 2767
Exception ignored in: <generator object cursor_iter at 0x7fad56291690>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1649, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
[10/Mar/2023 11:19:11] "GET /en/workout/set/day/1/set/add HTTP/1.0" 500 2767
```

Might be the same issue but also none of the icons appear to be working.   This is a clean install done today with no changes made.

**Comment by alexbelgium** [comment]
Thanks, I can replicate, I'll look at it when I have time

**Comment by alexbelgium** [comment]
Hi, this is a known wger issue : https://github.com/wger-project/wger/issues/1269 ; therefore we need to wait for the upstream image to update

**Comment by alexbelgium** [comment]
Could you please try to fully uninstall, and reinstall the latest version "-5" ? Thanks

**Comment by alexbelgium** [comment]
I'll close it as it now works on my system, feel free to reopen
