### ISSUE TITLE
🐛 [sonarr radarr ] missing root folder

### ISSUE THREAD

**Issue by pbvdven** [alexbelgium/hassio-addons#759]
**Which addon?**

- Addon name : sonarr radarr
- Addon version : since the ingress implementation

**Describe the bug**
The first time the addon starts after host reboot or addon reboot or addon update the container sees en empty root folder. I have all my drives mounted in the /share folder of home assistant so i don't use any addon config for drives/storage. The drive mounted in /share/sd1 is a samba share from my storage server. I never had this issue before you started ingress implements so maybe you can think of something that could cause this issue and  also i don't have the issue with other addons. I've i stop the addon and then start it again it will work sometimes i need to do it twice.

Also since you implemented that you can disable ingress i did that but no change in behavior. 

There is nothing related about this issue in the log i will paste one in later its not easy on mobile. But when it works or not log output is the same

**Comment by alexbelgium** [comment]
You closed it?
