### ISSUE TITLE
Volumes

### ISSUE THREAD

**Issue by wakielo** [alexbelgium/hassio-addons#76]
Hi Alex,

Could we make it persistent the folder of the files from nextcloud to make it accessible trough samba addon?

**Comment by alexbelgium** [comment]
Hi wakielo,
Normally the files from Nextcloud are exposed in the /share/nextcloud folder, so it should be directly accessible from the samba addon !

**Comment by alexbelgium** [comment]
I haven't access to my system for the moment but my remembering is that in the nextcloud options, you can select the folders in which the files are accessible. You can even use an SMB mount as a storage location (I used to do that)

**Comment by alexbelgium** [comment]
Thanks, did it work? I just realised that on new installs the default folder is indeed inside the addon in /data although in the past it used to be in /share/nextcloud (that's the danger of having automatic upstream updates). I was wondering if I should put it back to /share/nextcloud but I just worry to mess up the addon for people already using it

**Comment by wakielo** [comment]
No Alex, I couldnt make it work I think its related what you explained... IMO would be better adapt to share/nextcloud... So the people could manage better the uploaded data...

**Comment by alexbelgium** [comment]
It's corrected! The easiest for you is to fully uninstall the addon, then install the new version (22.2.0-8) and it will propose to use /share/nextcloud by default :-)
Does this work for you ?

**Comment by wakielo** [comment]
It works like a charm now!

**Comment by alexbelgium** [comment]
Thanks for the feedback!
