### ISSUE TITLE
🐛 [Qbittorrent] Login via Ingress fails

### ISSUE THREAD

**Issue by antonio1475** [alexbelgium/hassio-addons#760]
**Which addon?**

- Addon name : Qbittorrent
- Addon version : 4.5.2 

**Describe the bug**

Login from HA / Ingress fails with the last update.
Using default user/password, restarted a few times.
![image](https://user-images.githubusercontent.com/63130724/226172964-138eb7de-b06d-491e-a5e8-5c23b7e0f3f9.png)

But via ip:port works
![image](https://user-images.githubusercontent.com/63130724/226173003-5a80c7b8-bb3c-46d1-b05f-3374c726a497.png)
![image](https://user-images.githubusercontent.com/63130724/226173006-baae37f2-86ea-4786-b415-e4ff0fa78e4f.png)

**To Reproduce**

1. Go to HA
2. Click on Settings > Addons (or sidebar)
3. Open Qbittorrent UI
4. Inpuit credentials
5. See error

**Full addon log**

```
[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Qbittorrent
 qBittorrent is a bittorrent client
-----------------------------------------------------------
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
 Add-on version: 4.5.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.3.5
 Home Assistant Supervisor: 2023.03.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-folders.sh
cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[12:41:44] INFO: Execute /config/addons_autoscripts/qbittorrent.sh if existing
[12:41:44] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/30-nginx.sh
cont-init: info: /etc/cont-init.d/30-nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/90-dns_set.sh
[12:41:45] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
cont-init: info: /etc/cont-init.d/90-dns_set.sh exited 0
cont-init: info: running /etc/cont-init.d/91-qbittorrent_configuration.sh
[12:41:46] INFO: Downloads can be found in /mnt/EXT4/Downloads
[12:41:47] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[12:41:47] INFO: WEBUI username set to admin
[12:41:47] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
[12:41:49] INFO: Default username/password : admin/adminadmin
[12:41:49] INFO: Configuration can be found in /config/addons_config/qBittorrent
cont-init: info: /etc/cont-init.d/91-qbittorrent_configuration.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
Local Disks mounting...
[12:41:52] INFO: Mounting EXT4 of type ext4
[12:41:52] INFO: Success! EXT4 mounted to /mnt/EXT4
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-openvpn.sh
[12:41:52] INFO: Direct connection without VPN enabled
cont-init: info: /etc/cont-init.d/93-openvpn.sh exited 0
[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
services-up: info: copying legacy longrun nginx (no readiness notification)
[ls.io-init] done.
[12:41:54] INFO: Starting NGinx...
```

**Full addon config**

DNS_server: 8.8.8.8,1.1.1.1
PGID: "0"
PUID: "0"
SavePath: /mnt/EXT4/Downloads
Username: admin
certfile: fullchain.pem
customUI: vuetorrent
keyfile: privkey.pem
ssl: false
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
localdisks: EXT4
openvpn_enabled: false
**System**

 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.3.5
 Home Assistant Supervisor: 2023.03.1

**Comment by antonio1475** [comment]
A side effect of this is that Sonarr/Radarr can't connect to qBittorrent.

But, I just added my HA IP to the qbit config whitelist and goes straight in. I hadn't set it up properly with the IP subnets (I don't understand how that works).
I had whitelisted 192.168.0.0/16 but my HA IP is 192.168.3.77

Sonarr/Radarr can now connect to qBit too.

This didn't happen before the last add-on update though, so not sure if the bug still stands. 
Thanks :)

**Comment by alexbelgium** [comment]
Hi, actually some addons configs were not properly sent to the qbittorrent.conf in the previous version... So if the addons options are correctly reflected in the qbittorrent config then it would seem that things are working as expected

**Comment by alexbelgium** [comment]
Shouldn't 192.168.0.0/16 cover 192.168.3.77?

**Comment by antonio1475** [comment]
Interesting.

I just removed 192.168.3.77 and left the previous config from the OP. It works.

Maybe something got hung up with the update and I just needed to re-save the config?

Anyway everything seems fine now, so feel free to close this if you think all is okay!
At the very least opening this made me re-save the config and it's solved... :)

**Comment by alexbelgium** [comment]
Great to know if works again! Just to try, I've updated the exec code with upstream to see if this improves something. In theory, qbittorrent could launch in a more stable manner
