### ISSUE TITLE
🐛 [NextCloud] Missing APACHE_IP_BINDING for running behind a reverse proxy. 

### ISSUE THREAD

**Issue by Deckoz2302** [alexbelgium/hassio-addons#768]
NextCloud

**The title of the addon this issue is for.** 

- Addon name : NextCloud
- Addon version : 25.0.4-11

**Bug Description:**
Endless Redirects. No option for evnronment variables to set apache binding config. 

Below is the default in NextCloud AIO but it should be able to be bound to 0.0.0.0 via environment vars
```   
environment: # Is needed when using any of the options below
       - APACHE_PORT=11000 # Is needed when running behind a reverse proxy.
       - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy
 ```

**A clear and concise description of what the bug is:**

In the add-on logs when running behind a reverse proxy
```
127.0.0.1 - - [23/Mar/2023:11:29:03 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:08 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:13 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:19 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:24 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:29 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:34 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:39 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:44 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:50 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:29:55 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:00 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:05 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:10 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:15 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:21 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:26 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:31 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:36 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:41 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:46 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:52 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:30:57 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:02 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:07 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:12 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:17 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:22 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:28 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:33 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:38 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:43 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:48 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:53 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:31:59 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:32:04 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
127.0.0.1 - - [23/Mar/2023:11:32:09 -0400] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1"
```

**Steps to reproduce the behavior:**
1. Start the Add-On behind a reverse proxy(NginX Proxy Manager)
2. Wait

**The addon config in yaml:**

config.yaml not relevant - need additional options for environment to set NextCloud AIO to not have endless redirects when behind a reverse proxy. 
APACHE_IP_BINDING=0.0.0.0

See documentation for NextCloud AIO reverse proxy https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md 

**HAOS Versions:**

Home Assistant 2023.3.4
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.0 - latest

**Comment by alexbelgium** [comment]
Hi, what do you mean "config.yaml is not relevant"? In theory, any variable you add inside will be pushed as en environement variable.

**Comment by Deckoz2302** [comment]
> Hi, what do you mean "config.yaml is not relevant"? In theory, any variable you add inside will be pushed as en environement variable.
> 
> Edit : actually it doesn't, I'll push this option

Hey sorry, I wasn't trying to undermine and say config.yaml is not relevant. I am just familiar with a few other add-ons you have in your repo that have the env_vars as part of the schema so it is configurable within the home assistant UI or in yaml

**Comment by alexbelgium** [comment]
Thanks, actually what you see is a a log due to a perioid 5 seconds healthcheck... I'll see how to suppress that

**Comment by alexbelgium** [comment]
Thanks for reporting! It gave me the idea how to solve it and I'll push a new version a bit later. Please let me know how it will go!

**Comment by alexbelgium** [comment]
Should be good, I'll try it also on my system

**Comment by Deckoz2302** [comment]
> Should be good, I'll try it also on my system

Just looked at your commits. Looks good to me. Sorry forgot ha ingress and such use NginX.

**Comment by alexbelgium** [comment]
Sorry for all the weird versioning, I thought it was linked to the -latest version of the container. When I saw it was not I've realigned versioning until the next major version that will be published this saturday
