### ISSUE TITLE
Meali (Omni) SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by DominikWrobel** [alexbelgium/hassio-addons#769]
Meali (Omni)  v1.0.0-beta-1

I've just upgradet to Meali (Omni)  v1.0.0-beta-1 from Mealie 1.0.0.1-2 and I get the SSL_ERROR_RX_RECORD_TOO_LONG when I try to see the page. I reach my Home Assistant (2023.3.5) via duckdns add on. I've also tried to reach it via local IP adress and have the same problem.

Every other add on works just great. I've also tried to go back to Mealie 1.0.0.1-2 version but then I get the same SSL error. Could you help me with this?

**Comment by Deckoz2302** [comment]
mealie has content security in place. 

In mealie config, ensure you have set the BASE_URL which should be in the format of https://your.domain.com:port or if you have a custom subdomain for mealie, set the https://your.mealie.domain 

if you want to have ingress enabled within an iframe in home assistant. atleast for nginx proxy manager you will need to set a custom location with 

```
add_header Content-Security-Policy "frame-ancestors homeassistant.yourdomain.com;";
```

or whatever your HA domain is.

**Comment by DominikWrobel** [comment]
Ok, so I had my BASE_URL without port number, just added this and still get the same error. 

As for the nginx part - I have never used it and will have to get my head around it to get it working. But not today, it's late here in Poland ;)

Thank you for the help.
