### ISSUE TITLE
Enedis2mqtt | How to add entities to HA ?

### ISSUE THREAD

**Issue by silversmarty** [alexbelgium/hassio-addons#77]
Hello,

first of all : thanks for your fantastic job! I've nbeen able to create my Enedis account, share informations and install the HA add-on easily. According to logs, data is imported as expected.

However, I can see Enedisgateway2mqtt in the list of devices, but nothing about my electric meter in the Entities section : what should I do to see my data ? Is there any specific YAML lines to add to configuration.yaml ?

Thanks a lot, again !
Paul

**Comment by alexbelgium** [comment]
Hi, thanks for the feedback!

The best is for you to contact the owner of the HA integration here : https://github.com/m4dm4rtig4n/enedisgateway2mqtt/blob/master/README.md

He's the developer of the app and can help you with the integration in HA...

Have a nice day!

**Comment by alexbelgium** [comment]
Did you receive the support you wanted? I'll close the issue here as related to the app itself and not the addon
