### ISSUE TITLE
🐛 [Firefly III Data Importer] Auto import fails due to missing 'IMPORT_DIR_ALLOWLIST'

### ISSUE THREAD

**Issue by SirJohnDoe** [alexbelgium/hassio-addons#770]
**Which addon?**

- Addon name : Firefly iii Data Importer
- Addon version : 1.2.2

**Describe the bug**

Looks like ENV variable 'IMPORT_DIR_ALLOWLIST' is not defined in the latest version of the addon, because I get the following error when using auto importer:

```
[14:17:01] INFO: Running update according to defined schedule. Files located in /config/addons_config/fireflyiii_data_importer will be imported
No valid paths in IMPORT_DIR_ALLOWLIST, cannot continue.
Path "/config/addons_config/fireflyiii_data_importer/import_files" is not in the list of allowed paths (IMPORT_DIR_ALLOWLIST).
```

**To Reproduce**

Try auto importing a import_config JSON which is located in the default 'Import_files' directory.

**Full addon log**

-----------------------------------------------------------
 Add-on: Firefly iii Data Importer
 Data importer for Firefly III (separate addon)
-----------------------------------------------------------
 Add-on version: version-1.2.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.3.6
 Home Assistant Supervisor: 2023.03.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/addons_config/fireflyiii_data_importer/config.yaml'
FIREFLY_III_ACCESS_TOKEN=x
FIREFLY_III_URL=x
NORDIGEN_ID=x
NORDIGEN_KEY=x
Updates='hourly'
Timezone set from Etc/UTC to Europe/Amsterdam
/etc/cont-init.d/01-custom_script.sh: executing
[14:23:47] INFO: Execute /config/addons_autoscripts/fireflyiii-data-importer.sh if existing
[14:23:47] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/fireflyiii_data_importer/config.yaml
Config file is a valid yaml
/etc/cont-init.d/98-fix.sh: executing
Fix for Nordigen
/etc/cont-init.d/99-run.sh: executing
[14:23:50] INFO: hourly updates
Starting periodic command scheduler: cron.
[14:23:50] INFO: Automatic updates were requested. The files in /config/addons_config/fireflyiii_data_importer/import_files will be imported hourly.
[14:23:50] INFO: Please wait while the app is loading !
Now in entrypoint.sh for Firefly III Data Importer
Script:        1.6 (2022-02-17)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  205
Build date:    18-03-2023 14:56:24 CET
Now parsing _FILE variables.
done!
Firefly III data importer v1.2.2
PHP: cli 8.2.3 Linux
Will now run Apache web server:
[Sat Mar 25 14:24:02.627629 2023] [mpm_prefork:notice] [pid 305] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
[Sat Mar 25 14:24:02.635347 2023] [core:notice] [pid 305] AH00094: Command line: 'apache2 -D FOREGROUND'

**Full addon config**

CONFIG_LOCATION: /config/addons_config/fireflyiii_data_importer/config.yaml
FIREFLY_III_URL: x
FIREFLY_III_ACCESS_TOKEN: x
NORDIGEN_ID: x
NORDIGEN_KEY: x
Updates: hourly

**System**

- Supervisor version: 2023.03.2
- Host system version: 9.5

**Comment by SirJohnDoe** [comment]
Putting 'IMPORT_DIR_ALLOWLIST: /config/addons_config/fireflyiii_data_importer/import_files' in the config.yaml fixes it. Would be better if this ENV is set by default.

**Comment by alexbelgium** [comment]
Thanks for the report and solution, I'll add that in the next version

**Comment by alexbelgium** [comment]
Hi, should be good, could you please test? Thanks

**Comment by SirJohnDoe** [comment]
> Hi, should be good, could you please test? Thanks

Thanks! Seems to work fine now.

**Comment by alexbelgium** [comment]
Thanks

**Comment by SirJohnDoe** [comment]
Just noticed this in the HA supervisor logging:

`23-03-28 11:18:29 WARNING (MainThread) [supervisor.addons.options] Option 'IMPORT_DIR_WHITELIST' does not exist in the schema for Firefly iii Data Importer (db21ed7f_fireflyiii_data_importer)`

`23-03-28 11:18:29 WARNING (SyncWorker_5) [supervisor.addons.options] Option 'IMPORT_DIR_WHITELIST' does not exist in the schema for Firefly iii Data Importer (db21ed7f_fireflyiii_data_importer)`

I get this every 5 minutes or so. It seems the variable needs to be defined somewhere for it to stop?
