### ISSUE TITLE
✨ [REQUEST] tandoor: enable ingress

### ISSUE THREAD

**Issue by ftrueck** [alexbelgium/hassio-addons#772]
**Which addon?**

Tandoor recipes

**Is your feature request related to a problem? Please describe.**

The addon does not support ingress, which makes it require additional steps to make the addon accessible if you have a remote setup, e.g. nabucasa access and/or HA App.

**Describe the solution you'd like**

enable ingress in config.yaml plus required config for custom port

**Describe alternatives you've considered**

using nginx proxy manager but this is not a neat solution in my eyes as integration into HA ui fits much better in my opinion

**Additional context**

not applicable

**Comment by alexbelgium** [comment]
Hi, there is already a thread on this topic, please use it for further comments : https://github.com/alexbelgium/hassio-addons/issues/484

Current status is that the app doesn't seem compatible
