### ISSUE TITLE
✨ [REQUEST] Guacamole Client  - Enable RDP/SSH File Transfer Over Guacamole

### ISSUE THREAD

**Issue by E-NINA** [alexbelgium/hassio-addons#773]
**Guacamole Client**

Enable RDP/SSH File Transfer Over Guacamole

By default file transfer under RDP or SSH is disabled.
Will be something interesting to be possible add by defualt or possible to enable trough configuration page.
I don t know how to made this on docker but seems isnºt so much complicated, below a link with explanations

https://kifarunix.com/how-to-enable-rdp-ssh-file-transfer-over-guacamole/?utm_content=cmp-true

**Comment by alexbelgium** [comment]
Hi, that's strange, the upstream image should support it by default : https://github.com/abesnier/docker-guacamole

I wonder if this is an HA limitation

**Comment by E-NINA** [comment]
No definitely its my limitation.
I dig trough all parameters on guacamole server and found my mistake on configuration

![image](https://user-images.githubusercontent.com/42787097/228206445-79150fbf-6725-4241-9404-3195701c689e.png)

Sorry for this

**Comment by alexbelgium** [comment]
Happy it works for you! That's the most important ;-) have a nice day
