### ISSUE TITLE
[PaperlessNGX] Documentation for Accessing the Docker Shell

### ISSUE THREAD

**Issue by feamsr00** [alexbelgium/hassio-addons#776]
**Which addon?**

Paperless NGX

name: Feature request
about: Document the method to get to the shell for this (each?) addon
title: ''
labels: ''
assignees: ''

---

**Describe the solution you'd like**

It would be great if there was a single clear place that had documentation that said how to get to a terminal for the addon container.

Also, why don't you have the wiki enabled for this repo? You could shove all interesting tidbits like this in there.

**Describe alternatives you've considered**

Looked around for a while, can't make heads or tails on how to get in to the *containers* ssh shell.

**Additional context**
I've migrated to the PaperlessNGX here from Moshee's (Thanks so much for keeping this up to date!!) However I need to run `document_thumbnails` (https://github.com/paperless-ngx/paperless-ngx/blob/96e8cfb7659930037cd32f02f3c6cf30d88c929f/src/documents/management/commands/document_thumbnails.py) in paperless' environment in order to do this.

**Comment by alexbelgium** [comment]
Hi, the easiest way would be by installing the portainer addon which allows direct access into the container's shell

**Comment by alexbelgium** [comment]
I'll close as this should provide all details to access the docker shell, please feel free to reopen

**Comment by alexbelgium** [comment]
Timeout is probably linked to a nginx server on your system. The addon itself allows longer timeouts. Here is the likely solution : https://github.com/portainer/portainer/issues/2953#issuecomment-1235795256
