### ISSUE TITLE
Mealie Omni SSL issue

### ISSUE THREAD

**Issue by SeeThisIsMe** [alexbelgium/hassio-addons#782]
Hi,

I’ve had an ongoing issue with the Mealie Omni add-on that I cannot work out the cause of. It may be something specific to my system or something that I’ve done wrong, but I doubt it. 

The previous dual frontend/backend add-on’s all worked fine. If I upgrade to the Omni version by removing the old dual add-on’s, and then installing the Omni add-on, it then mostly looks good (recipes/accounts/data is all there) but it's not possible to use a SSL/HTTPS connection. 

- If I disable the SSL option in Omni, everything is fine via an HTTP connection. 
- If I enable SSL, I can get the login page via HTTPS, but when entering credentials I get a generic error of “something went wrong”. However, also with SSL enabled I can go to the same address via HTTP, and log in correctly and use everything in the application. 

I don’t see anything in the logs indicating the problem, and all the add-on options are configured the same as for the previous dual add-on setup. Cert and key files are present, base URL is set, port mappings are the same for frontend and api. I’m using a duckdns address with lets encrypt. 

I must have tried 10+ times to upgrade to Omni and always end up having to restore a backup to revert to the previously working SSL version with the dual add-on’s.

Has anyone else seen this, or any suggestions on what the cause might be?

Thanks!

**Comment by alexbelgium** [comment]
Hi, thanks indeed Caddyfile that was handling the ssl part was removed from this image. I'll have to see to enable a new system

**Comment by alexbelgium** [comment]
Version v1.0.0-beta-3 should be good

**Comment by SeeThisIsMe** [comment]
Looks good now - thanks!
