### ISSUE TITLE
🐛 [Calibre] 502 Bad Gateway error

### ISSUE THREAD

**Issue by blackshoals** [alexbelgium/hassio-addons#783]
Getting the 502 Bad Gateway message on both the local IP and external port forward addresses under the addon version v6.15.0-ls211. Previously working OK. Raspberry Pi 4B running Home Assistant 2023.4.1. The Calibre addon log is repeating:

mkdir: cannot create directory ‘/sys/fs/cgroup/init’: Read-only file system
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:2
mkdir: cannot create directory ‘/sys/fs/cgroup/init’: Read-only file system

**Comment by alexbelgium** [comment]
Hi, looks like this version has issues https://github.com/linuxserver/docker-calibre/issues i'll investigate if yours is related

**Comment by alexbelgium** [comment]
Thanks for reporting, I've reverted the version as I don't have an easy pc access. I'll upgrade again later in the future

**Comment by blackshoals** [comment]
Thanks Alex. It looks like the calibre docker version was the issue. I should have checked their issue list.

**Comment by alexbelgium** [comment]
No worry, we'll let pass a couple weeks for them to sort things out before re enabling updates. Usually linuxserver (the organisation in charge of the upstream images) works with incremental leaps : everything is stable for a long time, then there is a big change to accommodate and it goes back to stable again. Glad anyway this is working again for you!
