### ISSUE TITLE
Repository not showing

### ISSUE THREAD

**Issue by tiagomaricate** [alexbelgium/hassio-addons#785]
After adding the repository, no add-on is showing.
Any clue whats going on?

**Comment by alexbelgium** [comment]
Have you tried to restart home assistant? You could also enable advanced mode https://smarthomehobby.com/configure-home-assistant/#activate-advanced-mode

**Comment by chef-blip** [comment]
Possibly experiencing the same issue. after adding repository to Hassio it doesn't show up on the add-on store. 
Tried following actions, wich did'nt change the situation;
-Removing and re-adding the the repository
-check for updates from the add-on store.
-restart homeassistant.

Supervisor logs

`2023-04-16 20:50:08.876 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xB618:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2023-04-16 20:50:42.139 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/reload request
2023-04-16 20:50:42.144 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/reload - 
2023-04-16 20:55:30.565 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2023-04-16 20:56:02.137 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/reload request
2023-04-16 20:56:02.141 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/reload - `

**Comment by alexbelgium** [comment]
Dear all, sorry this is occurring but I don't see what I can change on my end. This seems like a supervisor bug, and it should be reported in their github repository

**Comment by alexbelgium** [comment]
Or better ask on the forum, this seems relevant [:](https://community.home-assistant.io/t/additional-repo-not-showing-up/314496/7)

**Comment by chef-blip** [comment]
> Or better ask on the forum, this seems relevant : [link](https://community.home-assistant.io/t/additional-repo-not-showing-up/314496/7)

I checked some time later, and the repo appeared in the add-on store. perhaps it has something to do with the browser cache indeed. for me the problem is solved. 

Thank you, happily using Qbittorrent ATM ;)
