### ISSUE TITLE
Téléchargement impossible

### ISSUE THREAD

**Issue by mellowtronik** [alexbelgium/hassio-addons#79]
Bonjour,
Je n'arrive pas à télécharger le fichier ZIP, ça me dit que le téléchargement et désactivé. (Les téléchargements de fichiers nécessitent un accès push à ce référentiel)

Pouvez-vous m'aider, s'il vous plait?
Merci

**Comment by alexbelgium** [comment]
Bonjour, que cherchez vous a faire ? Si c'est pour installer le repo dans HA il suffit de suivre cette procédure :
"A user can add a repository by going to the Supervisor panel in Home Assistant, clicking on the store icon in the top right, copy/paste the URL of your repository into the repository textarea and click on Save."

Il y a moyen d'accéder directement à cette page avec ce bouton :    [![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Falexbelgium%2Fhassio-addons)

Dites moi si ça répond à votre besoin

Bonne journée !

**Comment by mellowtronik** [comment]
Bonjour, merci j'ai pu le télécharger directement via votre lien. Là, il est installé sous Supervisor, j'ai mis mon pdl et token, etc.. Mais ensuite je ne sais pas comment il faut faire pour l'ajouter dans lovelace. J'ai bien Mqqt aussi.. Par contre, je ne suis sous docker.

**Comment by alexbelgium** [comment]
Nickel. En fait cet addon est vraiment pour l'addon du serveur, pour tout ce qui est intégration il vaut mieux demander sur le premier github ! C'est eux qui gèrent l'app.

A priori ça devrait se populer dans l'onglet énergie, mais ils pourront mieux t'aider que moi.

Bonne continuation !
