### ISSUE TITLE
[nextcloud] Directory creation problem

### ISSUE THREAD

**Issue by ug30242** [alexbelgium/hassio-addons#790]
**Which addon?**

<nextcloud>

I get an error message "Cannot create or write into the data directory" while installing nextcloud. We do not want to use the default directory because it is included in automatic backups.

**Comment by ug30242** [comment]
Hi!

Sure. 
I've tried it with the created file directory, and I've tried it without it, but the result is the same.
FYI, I'm not using HAOS, I'm using HA Supervised in Docker on Raspberry Pi 4.
I understand that if you proceed to the default directory (/shared/nextcloud) during HA backup, the files stored in Nextcloud are also backed up, taking up a lot of space.
Can I change the file storage space of the Next Cloud to an external hard drive?

**Comment by alexbelgium** [comment]
Hi sure, for example @bobloadmire does it too. You just mount the drive through the addon options, and see in the logs where it is mounted (/mnt/xxx) then reference this folder as data folder.

Before that, you need to create the folder and chown it to the same puid/guid you are using, normally 1000:1000

**Comment by bobloadmire** [comment]
Data directory detected : /share/nextcloud


you're setting data directory to the wrong location. Reinstall nextcloud and specify /mnt/nextcloud at the setup GUI. the YAML config doesn't really work, you have to do it at setup, make sure the network share is mounted before setup.

**Comment by alexbelgium** [comment]
Thanks, indeed. And make sure that you refer all smb infos in the addon options first to make sure that the data directory will well be available whd' you install nextcloud

**Comment by ArekKubacki** [comment]
> Before that, you need to create the folder and chown it to the same puid/guid you are using, normally 1000:1000

I have in logs /mnt/sdb1

But when I want to create an admin it says "Cannot create or write into the data directory". What folder exactly and where should I create it?
