### ISSUE TITLE
enedisgateway2mqtt : version 8.14 impossible to install HassIO

### ISSUE THREAD

**Issue by LGO44** [alexbelgium/hassio-addons#794]
**enedisgateway2mqtt**

- Addon name : enedisgateway2mqtt
- Addon version : 8.14

**This release cannot be installed , not present on the repository only 8.13**

**Full addon log**

**Full addon config**

**System**
Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5

**Comment by alexbelgium** [comment]
Hi, updates are fine on Saturday (except in case of special needs for which I do manual updates).

It should be up tomorrow!

**Comment by LGO44** [comment]
> Hi, updates are done on Saturday (except in case of special needs for which I do manual updates).
> 
> It should be up tomorrow!

Thanks, it work fine with the 8.16 release
