### ISSUE TITLE
🐛 [Photoprism] Cannot add user in Photoprism Preview-6

### ISSUE THREAD

**Issue by MiSebCo** [alexbelgium/hassio-addons#798]
**Which addon?**

- Addon name : Photoprism
- Addon version : Preview-6

**Describe the bug**

I am trying to add a user but the user either cannot log in or is lost after restart of the addon.

**To Reproduce**

I tried two configurations

A) using mariadb_addon and BACKUP_PATH, IMPORT_PATH, ORIGINALS_PATH, STORAGE_PATH with the default values
B) using sqlite with
BACKUP_PATH /photoprism/storage/backups
IMPORT_PATH /photoprism/import
ORIGINALS_PATH /photoprism/originals
STORAGE_PATH /photoprism/storage

Configuration A) should be the default configuration.

Configuration B) was just for testing purposes. In Configuration A) with command _photoprism config_ the path as given by the addon do not show up (e.g. /share/photoprism/storage)

How to reproduce:

In Configuration A)
_photoprism users ls_ before adding the user shows an empty table with error message _users: no such table: auth_users_

After adding the user _photoprism users ls_ shows the added user but the user cannot log in.

After restarting the addon _photoprism users ls_ shows an empty table and the error message _users: no such table: auth_users_

In Configuration B)
_photoprism users ls_ before adding the users shows only the admin user and no error.

After adding the user _photoprism users ls_ shows the added user and the user can log in.

After restarting the addon the new user is not available anymore and is not listed when executing _photoprism users ls_. Only the admin user is listed. The UID of the admin user changed, however.

**Full addon log**

Starting...
/etc/cont-init.d/00-banner.sh: executing

 Add-on: Photoprism
 A server-based application for browsing, organizing and sharing your personal photo collection

 Add-on version: Preview-6
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.4.1
 Home Assistant Supervisor: 2023.04.0

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums

 Provided by: https://github.com/alexbelgium/hassio-addons 

/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-custom_script.sh: executing
[23:41:38] INFO: Execute /config/addons_autoscripts/photoprism.sh if existing
[23:41:38] INFO: ... no script found
/etc/cont-init.d/30-graphic_drivers.sh: executing
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/32-nginx_ssl.sh: executing
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/photoprism/config.yaml
Config file is a valid yaml
[23:41:40] INFO: Starting the app with the variables in /config/addons_config/photoprism/config.yaml
/etc/cont-init.d/90-disable_ingress.sh: executing
/etc/cont-init.d/99-run.sh: executing
[23:41:40] INFO: Defining database
[23:41:41] INFO: Using a local sqlite database
[23:41:41] WARNING: Ingress is enabled. To connect, you must add /api/hassio_ingress/6hjFmsd-Bn0j9qBUwdqSA3AKXcgfEZ58WKoYevLViFk/ to the end of your access point. Example : http://my-url:8123/api/hassio_ingress/6hjFmsd-Bn0j9qBUwdqSA3AKXcgfEZ58WKoYevLViFk/
[23:41:42] INFO: Please wait 1 or 2 minutes to allow the server to load
[23:41:42] INFO: Default username : admin, default password: "please_change_password"
[23:41:42] INFO: Starting, please wait for next green text...
started 230414 as root (arm64-prod)
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /photoprism/storage
config path...: default
cache path....: default
backup path...: /photoprism/storage/backups
import path...: /photoprism/import
originals path: /photoprism/originals
running as uid 0
photoprism start
time="2023-04-15T23:41:57+02:00" level=info msg="Become a member today, support our mission and enjoy our member benefits! 💎"
time="2023-04-15T23:41:57+02:00" level=info msg="Visit https://www.photoprism.app/membership to learn more."
time="2023-04-15T23:41:57+02:00" level=info msg="migrate: running database migrations"
time="2023-04-15T23:41:57+02:00" level=info msg="migrate: 20221015-100000 successful [26.826089ms]"
time="2023-04-15T23:41:57+02:00" level=info msg="migrate: 20221015-100100 successful [30.174697ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20211121-094727 successful [25.47618ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20211124-120008 successful [29.784591ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-040000 successful [26.067635ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-050000 successful [49.85552ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-061000 successful [28.436032ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-071000 successful [29.830942ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-081000 successful [43.401874ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-083000 successful [29.236894ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-091000 successful [40.2353ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220329-093000 successful [28.144388ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20220421-200000 successful [40.705054ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20230309-000001 successful [28.812621ms]"
time="2023-04-15T23:42:01+02:00" level=info msg="migrate: 20230313-000001 successful [28.085629ms]"
time="2023-04-15T23:42:04+02:00" level=info msg="webdav: shared /api/hassio_ingress/6hjFmsd-Bn0j9qBUwdqSA3AKXcgfEZ58WKoYevLViFk/originals/"
time="2023-04-15T23:42:04+02:00" level=info msg="webdav: shared /api/hassio_ingress/6hjFmsd-Bn0j9qBUwdqSA3AKXcgfEZ58WKoYevLViFk/import/"
time="2023-04-15T23:42:04+02:00" level=info msg="server: disabled tls"
time="2023-04-15T23:42:04+02:00" level=info msg="server: listening on 0.0.0.0:2341 [6.793438ms]"
[23:42:04] INFO: App launched

**Full addon config**

BACKUP_PATH: /photoprism/storage/backups
CONFIG_LOCATION: /config/addons_config/photoprism/config.yaml
DB_TYPE: sqlite
IMPORT_PATH: /photoprism/import
ORIGINALS_PATH: /photoprism/originals
STORAGE_PATH: /photoprism/storage
UPLOAD_NSFW: "true"
certfile: fullchain.pem
keyfile: privkey.pem
ssl: false

**System**

Add-on version: Preview-6
System: Home Assistant OS 9.5 (aarch64 / raspberrypi4-64)
Home Assistant Core: 2023.4.1
Home Assistant Supervisor: 2023.04.0

**Comment by alexbelgium** [comment]
Thanks for the very detailed bug report. Probably variables don't get passed anymore due to an upstream change in the photoprism scripts structure. I'll investigate this evening or tomorrow

**Comment by MiSebCo** [comment]
Thank you very much! Really great work you are doing here. Let me know when you need any other information.

**Comment by alexbelgium** [comment]
Hi, I've created a fresh instance and everything works : I can access my previous instance using mariadb using the config.yaml, and I can create a new sqlite instance and change the password using the web interface.

I reviewed your configuration, and watch out that because of how docker work, only folders in `/config`, `/share`, `/data` or mounted folders (in `/mnt`) are remanent. Your folder `/photoprism` therefore isn't remanent and is removed at each reboot

**Comment by alexbelgium** [comment]
I tried to create a user with command line `photoprism users add -r admin -p mysecret -n "Bob" bob` and it seemed to work, but this is a feature specific for paid users (the specific code to activate paid feature must be added to the config.yaml based on the informations received after the donation)

**Comment by MiSebCo** [comment]
Thank you for looking into this!

My understanding is that you can have multiple users also in the community version with just "Admin" as account role for all users: https://www.photoprism.app/editions#compare

Multiple users (all admin) are working when running it as stated here: https://docs.photoprism.app/getting-started/docker-compose/#__tabbed_1_5 Everything works as expected - adding a new user, working with multiple users. 

I mapped all directories to CIFS - still no change. I also tried an external mariadb. Also clean install of the photoprism addon.

I get the error message _error msg="users: no such table: auth_users"_ when executing _photoprism users ls_ after starting with a clean install (now also with sqlite as option). This does not happen when running it in the docker environment.

Addon with clean install:
![image](https://user-images.githubusercontent.com/103767523/233831041-8e6e48a7-1ec0-4440-8e5d-32f88329f428.png)

Docker with clean install:
![image](https://user-images.githubusercontent.com/103767523/233831366-81c7cdd9-014e-4d0f-b97f-24331d86d4a6.png)

Maybe the addon has some issues with accessing the data base. I will not be able to further investigate this week. Any ideas are welcome. 

Thanks again!

**Comment by alexbelgium** [comment]
This is curious. If I restart my working instance and go in portainer, `photoprism users ls` returns the same error despite being able to log with my modified password. If I then type `photoprism users add admin`, several migrations run and then it tells me that admin user already exists and `photoprism users ls` show it again.

It doesn't work if I add a new one. If after performing those steps, `photoprism users add test` creates the user test. But if I restart the addon and go though the steps described above, the user test has disappeared. The strangest thing is that the database is remanent, as my database and custom password are kept after reboot. It's as if users password were stored in the correct mariadb database, but users themselves were stored somewhere else that is not remanent...

**Comment by MiSebCo** [comment]
Yes - I see a similar behaviour here. The first admin user seems to be a special user ("Super Admin") - although this documentation is from the Pro Version.

https://www.photoprism.app/pro/kb/roles

![image](https://user-images.githubusercontent.com/103767523/233841014-c1d7de43-902a-4375-ab4c-3aa21e95413e.png)

**Comment by alexbelgium** [comment]
I've seen the upstream images had modified the entrypoint vs was it was when I initially set the addon. I don't see how this would be related to this issue, but I'll still push a new version with this modification to see if it changes something

**Comment by alexbelgium** [comment]
Ok I've got it. The custom environment variables launched by the scripts are only available in the initial shell. Meaning that when you access cmd with portainer, you are in a new shell and therefore have lost all configuration. Therefore it opens a new sqlite database instead of accessing the one in which photoprism is opened

**Comment by MiSebCo** [comment]
Great! This might also explain why running _photoprism config_ also does not show the configured options.

**Comment by alexbelgium** [comment]
Seems good in latest version :-) at least `photoprism users ls` works

**Comment by MiSebCo** [comment]
Very good! Thank you! I will test it this weekend.

**Comment by MiSebCo** [comment]
I still do not have it working with Preview-8.

I unsinstalled photoprism addon, deleted all folders in _share_ and _config_. Unstalled MariaDB addon. 

Tried it 

- with a clean install of the photoprism addon (no changes to config)
- with a new clean install of photoprism addon, clean install of MariaDB and folders mapped to CIFS

I still get the error message _users: no such table: auth_users_

![image](https://user-images.githubusercontent.com/103767523/235349980-240be579-c9b0-4491-90c2-5481bb2fd754.png)

**Comment by alexbelgium** [comment]
How do you connect? When I connect with portainer selecting the bash shell it works (it won't work with sh though)

**Comment by MiSebCo** [comment]
I use the _docker exec_ command. I will send a screenshot on the weekend. Thanks!!

**Comment by alexbelgium** [comment]
That's why, my change was to add the env variables to bashrc that is not called in your configuration. You must therefore import manually in your shell the content of the ~/.bashrc file which should provide you with an the environnement variables. Or else, you can connect with portainer and the bash console will automatically contain all variables

**Comment by MiSebCo** [comment]
Ok. Thank you for the fast feedback! I will test it on the weekend.

**Comment by alexbelgium** [comment]
Actually perhaps just  `docker exec bash` or `source ~/.bashrc` might work

**Comment by MiSebCo** [comment]
Good point. Thank you for the hint. I will give it a try.

**Comment by MiSebCo** [comment]
I reinstalled mariaDB and the photoprism addon (Preview-8). 

I used `docker exec -it <mycontainer> bash` to execute photoprism commands - still getting the error _users: no such table: auth_users_

I think bashrc works however the environment variables seem to have an issue.

Here is the result of `photoprism users ls`

![image](https://user-images.githubusercontent.com/103767523/236644702-f33e98ed-ef6a-4a7a-9a00-d2632a3bd7cb.png)

**Comment by alexbelgium** [comment]
Hi, indeed it is not possible to modify the true environment variables from a script such as mine. Therefore, the only way is to source the environment variables manually when you connect by sourcing the ~/.bashrc file. I've tested connecting with the portainer add-on to the container bash and it worked as it sources automatically the bashrc file in its temporary environnement variables. Another option is for you to execute `/./entrypoint.sh && photoprism users ls` which perhaps will allow to reexport the variables prior to running the command

**Comment by MiSebCo** [comment]
I installed portainer addon, reinstalled mariaDB, reinstalled photoprism. This time no changes to the configuation.

I connected via portainer. 

Still get the error.

![image](https://user-images.githubusercontent.com/103767523/236646887-43e5edc5-c8b4-4276-99c0-adde9939d40c.png)

Note that also in portainer the environment variables seem to have an issue.

![image](https://user-images.githubusercontent.com/103767523/236646983-c5cf8d62-8494-415b-b8d4-f00c54847122.png)

**Comment by alexbelgium** [comment]
Argh it's crazy, just tried again. Logging in portainer with bash shell works in finding my users. Logging with the sh shell initially doesn't find my users as bashrc is not loaded, but if I execute `exec bash` then it loads a bash subshell with the right environnement and I can see my users. I wonder if we shouldn't modify the structure of the bashrc file as it might be the think causing the different behavior in our systems

**Comment by alexbelgium** [comment]
A key difference in our bashrc files is that I have " around each variable, which you don't have. Therefore it won't work in exporting your variables but probably an evil mess mixing everything together. I'll probably have to adapt the bashrc code to put variables on new lines. Actually I'm not sure why it is not already in new lines from the start

**Comment by MiSebCo** [comment]
This sounds like a possible explanation. Thanks for looking into it!

**Comment by alexbelgium** [comment]
Does the last version somehow works? If you first do `exec bash` to load the bashrc then `photoprism users ls`. I've tried on my system and it works but it isn't very telling as it was working also before. But now the bashrc us with one line per variable (for the most important)

**Comment by MiSebCo** [comment]
Sure. I will test it this morning. Thanks.

**Comment by MiSebCo** [comment]
I uninstalled the photoprism addon an installed it again - _preview-8test_

Opening container console with portainer gives:

![image](https://user-images.githubusercontent.com/103767523/236665194-a29fe801-101c-4499-9947-ab8cf77225cf.png)

This is the content of _~/.bashrc_

![image](https://user-images.githubusercontent.com/103767523/236665290-bed8b817-accb-42e2-ae24-88063a348e49.png)

The result of `photoprism users ls` now shows the following error

![image](https://user-images.githubusercontent.com/103767523/236665384-4d1ce12d-a501-479f-ac71-738cf6654721.png)

**Comment by alexbelgium** [comment]
I've pushed a new version that will clean the bashrc file then use export for variables

**Comment by MiSebCo** [comment]
Uninstalled photoprism and installed photoprism _preview-9_

Now it works. Great job!

Tested it using portainer and via `docker exec -it <mycontainer> bash`

Both ways seem to work.

Also tested with MariaDB - also seems to work.

As expected `docker exec <mycontainer> photoprism users ls` does not work. This might be a risk for users not aware of this issue. 

Thank you for providing the fix so fast!

**Comment by alexbelgium** [comment]
Thanks very much for your perseverance, and for the PR!
