### ISSUE TITLE
🐛 [QBittorrent] Downloads info are empty on small scale window

### ISSUE THREAD

**Issue by aviadlevy** [alexbelgium/hassio-addons#801]
**Which addon?**

- Addon name : Qbittorent
- Addon version : 4.5.2-2

**Describe the bug**

When my window size width is lower than 960 pixels my downloads are empty

Window size width 960:

<img width="960" alt="Screenshot 2023-04-18 at 10 46 55" src="https://user-images.githubusercontent.com/11833447/232711587-a9b95fb5-488d-4957-a184-f323098c23fb.png">

Window size width 959:

<img width="965" alt="Screenshot 2023-04-18 at 10 46 29" src="https://user-images.githubusercontent.com/11833447/232711680-d185e637-9e63-4784-b4c1-1c27c621d69e.png">

**To Reproduce**

1. Set window size to 959 or lower

- Supervisor version: 2023.04.0
- Host system version: 2023.4.5 (recently updated but it happens on previous versions as well)

**Comment by alexbelgium** [comment]
Hi, this seems an issue linked to the UI (Vuetorrent) and not the addon ; you should post the issue on their github : https://github.com/WDaan/VueTorrent

**Comment by aviadlevy** [comment]
Thanks for the quick response!
I'll open issue there. Thanks!

**Comment by alexbelgium** [comment]
Or we can try to modify on the fly with sed, I'll check that

**Comment by aviadlevy** [comment]
Found this solution: https://github.com/WDaan/VueTorrent/issues/723 

I will try it soon and I'll update

**Comment by alexbelgium** [comment]
Great, thanks! Actually I had the issue for a time then it disappeared so I didn't really think about it ;-) This will be useful for future people too
