### ISSUE TITLE
🐛 [Immich] 502 Bad Gateway

### ISSUE THREAD

**Issue by peeter22** [alexbelgium/hassio-addons#802]
**Which addon?**

- Addon name : Immich
- Addon version : 1.53.0

**Describe the bug**

I have the version 1.50.1 installed after updating the addon  to any higher version I get 502 bad gateway error

**log:**
Request #1681805245824: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"
Request #1681805245824: Sleeping for 4s and then retrying request...
Request #1681805245824: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"
Request #1681805245824: Sleeping for 4s and then retrying request...
Request #1681805245824: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"
Request #1681805245824: Sleeping for 4s and then retrying request...
Request #1681805245824: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"
Request #1681805245824: Sleeping for 4s and then retrying request...
Request #1681805245824: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"

**Full addon config**

**System**

- Supervisor version: 2023.04.0
- Host system version: 2023.4.5  (but it happened on the previous versions as well)

**Comment by alexbelgium** [comment]
Hi, this is an issue logged in the immich repository : https://github.com/immich-app/immich/issues/2028

**Comment by alexbelgium** [comment]
Please let me know how this new version goes

**Comment by peeter22** [comment]
Hello thanks for the quick reply as alway. Unfortunattely even after updating to 1.53.0-2 everything is the same

**Comment by alexbelgium** [comment]
Have you tried saving the options and restarting? On my system it solved the issue

**Comment by alexbelgium** [comment]
Actually I set it to true, restarted, then set it to false, and restarted again

**Comment by peeter22** [comment]
I only installed the 1.53.0-2 did not preform any additional steps, I am just updading it again and will try to rastrat the addon and/or restart HA entirely. 
To be honest I am not really familiar where to enable/disable typesense. I set up the addon using the GUI and when trying to find a config file in the HA file structure I was not able to do so.

**Comment by alexbelgium** [comment]
I've added the typesens option in the addon options (so in the gui)

**Comment by peeter22** [comment]
So with the typesense enabled I still get the 502 bad gateway error when trying to access the web interface.
And with it turned off I get this error message

```

[Nest] 664  - 04/18/2023, 2:03:40 PM   ERROR [ExceptionsHandler] ENOENT, No such file or directory '/photos'
Error: ENOENT, No such file or directory '/photos'
    at check (/app/immich/server/node_modules/diskusage/index.js:23:21)
    at /app/immich/server/node_modules/diskusage/index.js:10:5
    at new Promise (<anonymous>)
    at Object.exports.check (/app/immich/server/node_modules/diskusage/index.js:9:10)
    at FilesystemProvider.checkDiskUsage (/app/immich/server/dist/apps/immich/libs/infra/src/repositories/filesystem.provider.js:65:36)
    at ServerInfoService.getInfo (/app/immich/server/dist/apps/immich/libs/domain/src/server-info/server-info.service.js:28:55)
    at ServerInfoController.getServerInfo (/app/immich/server/dist/apps/immich/apps/immich/src/controllers/server-info.controller.js:24:29)
    at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (/app/immich/server/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
    at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:46:60
```

**Comment by alexbelgium** [comment]
What is your data_location config value? You haven't filled it in the bug report, thanks

**Comment by peeter22** [comment]
it is 
`/mnt/d/photos`
mounted from windows shared network drive

**Comment by alexbelgium** [comment]
Hi, thanks. Solved in latest version
