### ISSUE TITLE
🐛 [Whoogle] image not being displayed because of an ingress error

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#803]
**Which addon?**

- Addon name: Whoogle
- Addon version: 0.8.2

**Describe the bug**

When viewing images in Whoogle it is unable to find them:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/3063928/232786287-87f1d211-b3d0-448b-b263-d8cdd6c1e533.png">

For some reason `apihassioingresseuVedKwLzUXcyI3YRPOZI54TGKzitZnWhyGCwSPtyIc` is added to the url.

The url for the image is:
```
https://whoogleurlhere.com/apihassioingresseuVedKwLzUXcyI3YRPOZI54TGKzitZnWhyGCwSPtyIc/element?url=gAAAAABkPpVW5eGu8BCr3TqBynhznotjQsvHrs6xG40u3_fCj3B2feHAw-Uf3zaV6ruY0veQXvzYV-7X8eJK8HRPb3Q76UnncS6r69SqFk5zXm1dqFZxZMWrNuiGQbwmeDMVLBiNbCrWTgxRCMw4P177rXh-4WqvuEO5gqNnj-RQqaH1T5Lw3aInMFY6XxRInn6K9ML8DRSLQyhwHPN3jb-XGfCkc_vTl_5pYtYpbwqsDl--HwSntQM=&type=image/png
```

But it should be:
```
https://whoogleurlhere.com/element?url=gAAAAABkPpVW5eGu8BCr3TqBynhznotjQsvHrs6xG40u3_fCj3B2feHAw-Uf3zaV6ruY0veQXvzYV-7X8eJK8HRPb3Q76UnncS6r69SqFk5zXm1dqFZxZMWrNuiGQbwmeDMVLBiNbCrWTgxRCMw4P177rXh-4WqvuEO5gqNnj-RQqaH1T5Lw3aInMFY6XxRInn6K9ML8DRSLQyhwHPN3jb-XGfCkc_vTl_5pYtYpbwqsDl--HwSntQM=&type=image/png
```

**To Reproduce**

1. Install the addon
2. Use an external url (not the ingress one)
3. Search for a photo
4. error as above

**Full addon log**

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Whoogle Search
 Self-hosted, ad-free, privacy-respecting metasearch engine
-----------------------------------------------------------
 Add-on version: 0.8.2-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.5
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
HTTPS_ONLY='0'
TZ='Europe/Amsterdam'
WHOOGLE_AUTOCOMPLETE='1'
WHOOGLE_CONFIG_DISABLE='0'
WHOOGLE_CONFIG_GET_ONLY='1'
WHOOGLE_CONFIG_LANGUAGE='lang_en'
WHOOGLE_CONFIG_NEW_TAB='1'
WHOOGLE_CONFIG_URL='https://*****/'
WHOOGLE_CONFIG_VIEW_IMAGE='1'
WHOOGLE_MINIMAL='0'
/etc/cont-init.d/01-custom_script.sh: executing
[15:01:10] INFO: Execute /config/addons_autoscripts/whoogle-search.sh if existing
[15:01:10] INFO: ... no script found
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/99-run.sh: executing
Starting NGinx...
 * WARNING: tor is already starting
```

**Full addon config**

```
TZ: Europe/Amsterdam
WHOOGLE_CONFIG_LANGUAGE: lang_en
WHOOGLE_CONFIG_URL: https://*****/'
WHOOGLE_CONFIG_GET_ONLY: "1"
WHOOGLE_CONFIG_VIEW_IMAGE: "1"
WHOOGLE_CONFIG_NEW_TAB: "1"
WHOOGLE_CONFIG_DISABLE: "0"
HTTPS_ONLY: "0"
WHOOGLE_MINIMAL: "0"
WHOOGLE_AUTOCOMPLETE: "1"
```

**System**

HAS OS, all up to date.

**Comment by alexbelgium** [comment]
Hi, this is a normal way to allow ingress. But however, there are missing / indeed, it should be /api/hassioingress/euVedKwLzUXcyI3YRPOZI54TGKzitZnWhyGCwSPtyIc

Strange, thanks I'll look. Hì @bruvv, I remember that you helped set up the addon, do you encounter issues? Thanks!

**Comment by bruvv** [comment]
Haha yes I encountered issue. Hence why I opened the issue. I've no time ATM to take a look myself.

**Comment by alexbelgium** [comment]
Ha ha, sorry I was doing several things in parallel and didn't notice it was you the OP :-p so much for me ;) well I'll investigate!

**Comment by alexbelgium** [comment]
Looks complicated, I don't know enough python to revert the upstream change. `sed -i "s/word = re.sub.*/word = re.sub(r'[^A-Za-z0-9 ]+', '', word)/g" /whoogle/app/utils/results.py` doesn't seem to work. It seems python has a cache and changing the results.py does nothing

**Comment by bruvv** [comment]
I see, I will have a look at it. For the time being can we just switch off ingress ? I am not using ingress anyway.

**Comment by bruvv** [comment]
Not stall

**Comment by alexbelgium** [comment]
Hi, tested working on my system in the latest version.

**Comment by bruvv** [comment]
I just tested it with an update of the addon and it did not fix it, did a clean install and still same error. Firefox, chrome and safari. All the same issue.

**Comment by alexbelgium** [comment]
I see. The solution only works though nginx, therefore only through ingress for the moment. I'll have to route the external traffic through ingress too. While this is implemented you can access the app with ingress

**Comment by bruvv** [comment]
Works! THanks
