### ISSUE TITLE
🐛 [nextcloud] Access denied for user 'service'@'172.30.33.9' (using password: YES)

### ISSUE THREAD

**Issue by snipah** [alexbelgium/hassio-addons#804]
When setting up the nextcloud the db-user cannot be created, The nextcloud-config-page throws the following error;

`Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'service'@'172.30.33.9' (using password: YES)`

Maria-DB is running an creating the requested database. The Maria-DB-addon simply refuses to create the db, as it has a "different" name. The Maria-DB-log says:
` 2023-04-19 17:06:28 29 [Warning] Access denied for user 'service'@'172.30.33.9' (using password: YES)
`
Solution would be to create a user named 'service'@'172.30.33.9' but this is not accepted by the addon-config.

**Comment by alexbelgium** [comment]
Strange, "service" is the name used by mariadb inter-addons communication. I don't see where the @ip comes from. Have you tried to encode the informations exactly as described in the log ? Thanks

**Comment by snipah** [comment]
Yes, pretty sure I did everything correctly.

The MariaDB-config:

`databases:
  - nextcloud
logins:
  - password: Eangohyuchae6aif7saich2nies8xaivaejaNgaev6gi3yohy8ha2aexaetei6oh
    username: service
rights:
  - database: nextcloud
    username: service`

**Comment by alexbelgium** [comment]
Thanks for the feedback, glad it works
