### ISSUE TITLE
🐛 [Bazarr NAS] mount: mounting /dev/sda1 on /mnt/sda1 failed: Invalid argument

### ISSUE THREAD

**Issue by fcps3** [alexbelgium/hassio-addons#806]
Bazarr NAS

- Addon name : Bazarr
- Addon version : 1.2.0

**Describe the bug**

All other addons works, this has this error when trying to mount localdisk:
mount: mounting /dev/sda1 on /mnt/sda1 failed: Invalid argument
[12:53:35] FATAL: Unable to mount local drives! Please check the name.

I tried all possible reboots, all works except this

- Supervisor version: 2023.04.0
- Host system version: 10.0

**Comment by alexbelgium** [comment]
Hi, please post your full log, thanks!

**Comment by fcps3** [comment]
Oh, sorry, here it is, thank you
`GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
 System: Home Assistant OS 10.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.4.5
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[14:23:46] INFO: Execute /config/addons_autoscripts/bazarr-nas.sh if existing
[14:23:46] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
Local Disks mounting...
[14:23:50] INFO: Mounting sda1 of type ext4
Using PUID 0 and PGID 0
mount: mounting /dev/sda1 on /mnt/sda1 failed: Invalid argument
[14:23:51] FATAL: Unable to mount local drives! Please check the name.
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
[custom-init] No custom files found, skipping...
[ls.io-init] done.
2023-04-21 14:24:22,144 - root                             (7f9f5829d8) :  INFO (signalr_client:53) - BAZARR trying to connect to Sonarr SignalR feed...
2023-04-21 14:24:22,147 - root                             (7f9f47f9d8) :  INFO (signalr_client:190) - BAZARR trying to connect to Radarr SignalR feed...
2023-04-21 14:24:22,147 - root                             (7fae673058) :  INFO (server:67) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2023-04-21 14:24:22,332 - root                             (7f9f37c9d8) :  INFO (signalr_client:218) - BAZARR SignalR client for Radarr is connected and waiting for events.
2023-04-21 14:24:22,348 - root                             (7f9f5829d8) :  INFO (signalr_client:73) - BAZARR SignalR client for Sonarr is connected and waiting for events.`

**Comment by fcps3** [comment]
And here as reference my Radarr, same configuration
`GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.4.5
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[12:29:06] INFO: Execute /config/addons_autoscripts/radarr-nas.sh if existing
[12:29:06] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/32-nginx_ingress.sh
cont-init: info: /etc/cont-init.d/32-nginx_ingress.sh exited 0
cont-init: info: running /etc/cont-init.d/90-disable_ingress.sh
[12:29:07] WARNING: Ingress is disabled. You'll need to connect using ip:port
cont-init: info: /etc/cont-init.d/90-disable_ingress.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
Local Disks mounting...
[12:29:11] INFO: Mounting sda1 of type ext4
[12:29:11] INFO: Success! sda1 mounted to /mnt/sda1
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.3.2.6857 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Info] MigrationController: *** Migrating data source=/config/addons_config/radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/addons_config/radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
services-up: info: copying legacy longrun nginx (no readiness notification)
[ls.io-init] done.
[12:29:25] INFO: Ingress is disabled, removing base url
[12:29:25] INFO: Starting NGinx...`

**Comment by alexbelgium** [comment]
Thanks very much, that's exactly what I would have tried too. Radarr's version was pushed on 17 Mar, Bazarr on 04-Mar. Perhaps I had changed the underlying mount code since, I'll try to simply push a new bazarr version to check
