### ISSUE TITLE
[photoprism] automatic index on automation

### ISSUE THREAD

**Issue by baldarn** [alexbelgium/hassio-addons#809]
Hi,
I have photoprism indexing a syncthing folder with the picture of all the family, but I'm noob and I have to manually start the indexing.

is there a way to make this automatic based on an automation? also a cronjob could be enough for now ;)

thanks for your time!

**Comment by alexbelgium** [comment]
Hi, you could set a cronjob using the custom scripts : https://github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation

**Comment by alexbelgium** [comment]
Actually, `PHOTOPRISM_AUTO_INDEX` default setting is 5 min

**Comment by baldarn** [comment]
yes, but that's triggered only for WEBDAV updates if i'm not mistaking :(

**Comment by baldarn** [comment]
sad thing, I did as you suggested but this error appears:
```
/./etc/cont-init.d/01-custom_script.sh: line 18: dos2unix: command not found
```
