### ISSUE TITLE
Update variable

### ISSUE THREAD

**Issue by foXaCe** [alexbelgium/hassio-addons#81]
hello
it possible to update the variable table please

https://github.com/m4dm4rtig4n/enedisgateway2mqtt#environment-variable

thank again for your work

**Comment by alexbelgium** [comment]
Hi, pas de soucis je fais ça ce week-end. Je vais rajouter un champ vide pour encoder manuellement de nouvelles variables pour anticiper des changements futurs et ne pas devoir attendre l'update de l'addon à chaque fois.

En plus des variables env directement mappées, il y aura un champs "custom_var" dans lequel on pourra mettre un texte sous la forme : "var1:texte, var2:texte2" et ces variables seront automatiquement mappées également sous la forme var1=texte1, var2=text2.
Si une variable existe tant dans les options normales de l'addon, et dans le champs custom_var, c'est ce premier qui aura préséance

**Comment by foXaCe** [comment]
alors la bravo
super merci

**Comment by alexbelgium** [comment]
Bonjour, la nouvelle version est en ligne. Voici le descriptif que j'ai mis à jour dans le readme.
Toute proposition d'amélioration est la bienvenue!

There are 3 ways to configure this addon :

Using the addon options
Using the custom_var field, where variables not already defined in the addon options can be described using the format : var1="text1",var2="text2"
Manually editing the file /config/enedisgateway2mqtt/enedisgateway2mqtt.conf and adding options with the format var1="text1"
All variables defined the in the addon options and custom_var fields are automatically copied in the /config/enedisgateway2mqtt/enedisgateway2mqtt.conf file.

The complete list of options can be seen here : https://github.com/m4dm4rtig4n/enedisgateway2mqtt#environment-variable

**Comment by alexbelgium** [comment]
Par ailleurs, j'ai mis dans les "addon options" la liste totale des variables actuellement dispo

**Comment by alexbelgium** [comment]
Je ferme cette issue comme le point de base était la mise à jour des variables qui est faite, mais n'hésite pas si il y a de nouvelles choses

**Comment by foXaCe** [comment]
Traceback (most recent call last):
  File "/app/main.py", line 15, in <module>
    f = import_module("function")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/function.py", line 6, in <module>
    import main
  File "/app/main.py", line 52, in <module>
    port = int(os.environ['MQTT_PORT'])
ValueError: invalid literal for int() with base 10: "'1883'"
[16:02:48] FATAL: The app has crashed. Are you sure you entered the
correct config options?

**Comment by alexbelgium** [comment]
Mmh... Est-ce qu'une des variables n'est pas correctement exportée?

**Comment by alexbelgium** [comment]
ah je vois... il interprête doublement : le 1883 est à la fois entre '' et ""

**Comment by alexbelgium** [comment]
tu as mis la variable via les options addons ou manuellement dans le fichier config ?

**Comment by alexbelgium** [comment]
J'ai mis une nouvelle version v3, ça refonctionne?

**Comment by foXaCe** [comment]
Par l'éditeur d'ui

**Comment by alexbelgium** [comment]
ok merci, j'ai poussé une v3 pour voir si ça aide. Je voulais anticiper un problème mais ça en a causé un autre ;-)

**Comment by foXaCe** [comment]
Pareil même bug

Le sam. 13 nov. 2021 à 16:12, Stéphane Chabrol ***@***.***> a
écrit :

**Comment by foXaCe** [comment]
Ok pas de problème

**Comment by foXaCe** [comment]
Je test après et je te dit. Merci pour le job

Le sam. 13 nov. 2021 à 16:20, Stéphane Chabrol ***@***.***> a
écrit :

**Comment by alexbelgium** [comment]
Et là sur la v4 ?

**Comment by alexbelgium** [comment]
Ce qui est certain c'est que le "'1883'" de ton log devrait repasser à "".
Est-ce qu'il sera interprêté comme un integer, ça c'est la question intéressante :-)

**Comment by foXaCe** [comment]
qos = int(os.environ['QOS'])
ValueError: invalid literal for int() with base 10: '"0



Le problème a avancé d'une variable

**Comment by alexbelgium** [comment]
Nickel, v5 postée ;-) merci pour le test, je ne peux pas tester car je n'ai pas d'environnement enedys

**Comment by foXaCe** [comment]
Super ça marche
Merci encore une fois et bravo

**Comment by alexbelgium** [comment]
ah, top :-) content que ça marche. A priori cette fois c'est la bonne, car toute nouvelle variable env pourra être encodée soit via custom_var dans les options, soit écrite manuellement dans le fichier /config/enedisgateway2mqtt/enedisgateway2mqtt.conf (qui est également automatiquement populée avec les variables définies dans les options de l'addon)

Merci pour les tests

Bonne journée

**Comment by foXaCe** [comment]
Merci à toi
