### ISSUE TITLE
🐛 [Joplin Server] Health Check / Watchdog fail if APP_BASE_URL not localhost

### ISSUE THREAD

**Issue by mxbchr** [alexbelgium/hassio-addons#811]
**Which addon?**

- Addon name : Joplin Server
- Addon version : 2.10.11

**Describe the bug**

Docker Health Check / Home Assistant Watchdog fails if APP_BASE_URL is not set to localhost / 127.0.0.1. If Watchdog is activated the add-on constantly restarts, because Container Health Check fails.
As far as is can tell the problem is the Environment Variable HEALTH_URL (see image). It sets the path for the health check, default is "/health". This works fine as long as APP_BASE_URL is localhost. But if APP_BASE_URL is configured for external access, connections from all other origins including localhost are blocked by default, resulting in a container health check fail, docker marking the container as unhealthy and therefore Home Assistant Supervisor/Watchdog continuously restarting the add-on.
I tried setting HEALTH_URL to "https://example.duckdns.org/health", but since it seems the variable only is for a path at localhost and not a complete url, that doesn't work and prevents the add-on from starting at all.
Possible solution could be to make the variable accessible in supervisor interface and change the variable to accept a complete url instead of only a path with localhost as server fixed (or change the default host if APP_BASE_URL is changed). But this might to lead to further confusion down the road if access is configured to be behind a reverse proxy, since by default connection for health check is established via port 22300, which is usually closed and only port 80/443 are open.
Best Solution I can think of would be to persistently whitelist access from origin localhost/127.0.0.1, even if APP_BASE_URL is configured to a different location.
I have no clue how to do that though.

I'm pretty sure the problem lies in this line of code: https://github.com/alexbelgium/hassio-addons/blob/d58ed747e5c22fc0e0f67202f271a70ce21e5f17/joplin/Dockerfile#L124

**To Reproduce**

1. Install Addon with HomeAssistant
2. Configure APP_BASE_URL for external access (i.e. https://example.duckdns.org)
3. Activate Watchdog
4. Check log

**Full addon log**

2023-04-25 14:59:41: [error] App: 404: GET /health: ::ffff:127.0.0.1: Invalid origin: http://127.0.0.1:22300
2023-04-25 14:59:41: App: GET /health (404) (2ms)
2023-04-25 14:59:46: [error] App: 404: GET /health: ::ffff:127.0.0.1: Invalid origin: http://127.0.0.1:22300
2023-04-25 14:59:46: App: GET /health (404) (1ms)
2023-04-25 14:59:51: [error] App: 404: GET /health: ::ffff:127.0.0.1: Invalid origin: http://127.0.0.1:22300
2023-04-25 14:59:51: App: GET /health (404) (1ms)
2023-04-25 14:59:56: [error] App: 404: GET /health: ::ffff:127.0.0.1: Invalid origin: http://127.0.0.1:22300
2023-04-25 14:59:56: App: GET /health (404) (1ms)

**Full addon config**

APP_BASE_URL: https://example.duckdns.org
data_location: /config/addons_config/joplin
DB_CLIENT: pg
POSTGRES_DATABASE: joplin
POSTGRES_PORT: 5432
POSTGRES_HOST: 77b2833f-timescaledb
POSTGRES_USER: postgres
POSTGRES_PASSWORD: ***
MAILER_HOST: smtp.gmail.com
MAILER_ENABLED: 1
MAILER_AUTH_USER: ***@gmail.com
MAILER_SECURITY: starttls
MAILER_PORT: 587
MAILER_NOREPLY_EMAIL: ***@gmail.com
MAILER_NOREPLY_NAME: Joplin
MAILER_AUTH_PASSWORD: ***

**System**

- Supervisor version: 2023.04.1 
- Host system version: 10.0 

<img width="957" alt="Screenshot 2023-04-25 at 14 53 13" src="https://user-images.githubusercontent.com/75482460/234337629-32088111-6231-454b-959e-2f30a724efda.png">

**Comment by alexbelgium** [comment]
Hi, thanks you are totally right, and I see that it seems to be an issue others have experimented : https://github.com/laurent22/joplin/issues/7606#issuecomment-1452995483

It seems it is not possible to add additional whitelisted addresses. I'll probably remove the healthcheck if I don't find a way

**Comment by mxbchr** [comment]
Thanks for looking into that.

Just for you to know. Yesterday I poked around with the "ALLOWED_HOSTS" in the 99-run.sh a bit, adding 127.0.0.1 but to no avail. Still the same error as before.

https://github.com/alexbelgium/hassio-addons/blob/3e8a1c8394f1dda36ffbb12794dbd2824167c0cf/joplin/rootfs/etc/cont-init.d/99-run.sh#L63

**Comment by alexbelgium** [comment]
I wonder if we can check if the joplin app is running rather than doing an ip check

**Comment by mxbchr** [comment]
I have no clue tbh. But as far as I understand it is that Supervisor Watchdog just monitors Dockers Standard Container health check. It seems to be possible to customize the docker heath check procedure (https://scoutapm.com/blog/how-to-use-docker-healthcheck -> How to Write a Custom Health Check). But I cant think of a way to customize it that works for everybody, ie. using APP_BASE_URL/health, without running into further issues with external access and ports etc.

**Comment by alexbelgium** [comment]
Thanks, indeed I've written a custom healthcheck command for each of my addon. I've adapted it with a new logic, let's see if this works

**Comment by alexbelgium** [comment]
Should be good now in the latest version

**Comment by mxbchr** [comment]
Nice. Gonna try and report as soon as I'm home.

**Comment by mxbchr** [comment]
Works fine now with 2.10.11-3.
Watchdog activated, addon running stable, no errors in log.
Thanks a lot!
