### ISSUE TITLE
✨ [REQUEST] Portainer Agent

### ISSUE THREAD

**Issue by rodalpho** [alexbelgium/hassio-addons#812]
I already run portainer elsewhere on my network and would like to install the portainer *agent* only, a small resident program that essentially allows my main portainer instance to remotely control the host running the agent. 

https://hub.docker.com/r/portainer/agent

**Comment by alexbelgium** [comment]
Hi, thanks for the proposal. There is an already existing request here : https://github.com/alexbelgium/hassio-addons/issues/565

I'll therefore close to avoid duplication
