### ISSUE TITLE
[paperless-ngx] Stale file handle IOError with Fritzbox SMB mounts

### ISSUE THREAD

**Issue by ralfzen** [alexbelgium/hassio-addons#813]
Hello,

unfortunately the following test did not work correctly in my case:
https://github.com/alexbelgium/hassio-addons/blob/584f5b5b15127f03a09ee72c0655a21b609b4e72/.templates/00-smb_mounts.sh#L119

It always validates with freshly created files and the `noserverino` will not be set as a mount option. But when accessing a file which was created from another network device an IOError will be thrown.

Fortunately I could fix it by myself with a small hack: Just add `,noserverino` as a suffix in the smb password field. This solution works, but is not elegant. I would recommend an own mountoption field in the advanced options, because I have no idea how to test reliably for server or client index nodes usage.

I found the solution here:
https://askubuntu.com/questions/1265164/stale-file-handler-when-mounting-cifs-smb-network-drive-from-fritz-router
especially: https://debianforum.de/forum/viewtopic.php?t=176154

**Comment by alexbelgium** [comment]
Thanks! Actually your method is really smart. And perhaps even easier to implement than an additional option in all addons
