### ISSUE TITLE
Missing price

### ISSUE THREAD

**Issue by cob94440** [alexbelgium/hassio-addons#82]
Bonjour. Malgré la dernière version et tous les champs remplis, je n'ai pas de remontée du tarif. Je suis en HP hc. En base j'ai mis 0. 
Qu'ai je manqué ?

**Comment by alexbelgium** [comment]
Bonjour,

@foXaCe, une idée?

**Comment by cob94440** [comment]
J'avais déjà le souci sous la version 0.6
Je viens d'installer l'addon. Auparavant j'avais le plugins mais il buguait.

**Comment by alexbelgium** [comment]
En fait l'addon et le plugin sont exactement le même - l'addon facilite juste l'installation... C'est pour cela que j'en appelle aux devs de l'application car je ne connais pas le fonctionnement interne du plugin

Bonjour @m4dm4rtig4n, @foXaCe, des idées ?

**Comment by foXaCe** [comment]
@cob94440 je t'invite a venir sur le discord . ton problème viens surement d'autre chose.
pour ma part l'addon de @alexbelgium fonctionne très bien

**Comment by cob94440** [comment]
Quelle est l'adresse du discord stp

**Comment by foXaCe** [comment]
https://discord.gg/DfVJZme

**Comment by alexbelgium** [comment]
Le problème est résolu via le discord ? Je peux fermer l'issue ?

**Comment by cob94440** [comment]
J'ai pas de retour encore mais s'il y a que moi tu peux fermer. J'ai posté
sur le discord.
