### ISSUE TITLE
🐛 calibre web convert epub to pdf failed because of missing libnss3 in container.

### ISSUE THREAD

**Issue by pbvdven** [alexbelgium/hassio-addons#824]
**Which addon?**

- Addon name : calibre web
- Addon version : Current version: 0.6.20-ls207

**Describe the bug**

i can not convert epub to pdf it is an known issue seems to be easy fix please if you have the time see below links for it to work it needs libnss3 installed.

https://github.com/janeczku/calibre-web/issues/2487
https://bugs.launchpad.net/calibre/+bug/1955911

**To Reproduce**

- Supervisor version: latest main
- Host system version: debian ha supervised

**Comment by pbvdven** [comment]
thanks for your quick response i just installed the update but i still have the same error when converting epub>pdf

Calibre failed with error: ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)

**Comment by pbvdven** [comment]
calibre-web log:
[calibre-web (1).log](https://github.com/alexbelgium/hassio-addons/files/11407770/calibre-web.1.log)
Home assistant calibre-web addon log:
[db21ed7f_calibre-web_2023-05-05T15-23-47.184Z.log](https://github.com/alexbelgium/hassio-addons/files/11407771/db21ed7f_calibre-web_2023-05-05T15-23-47.184Z.log)

**Comment by alexbelgium** [comment]
I'm sorry I have added libnss3 to the container so not sure how I can help... I don't really know calibre-web

**Comment by pbvdven** [comment]
> Actually it is already in the container : https://github.com/linuxserver/docker-calibre-web/blob/984876c8c9cc42c88d82e77d0f88382c76ddbd47/Dockerfile#L23
> 
> 
> 
> You could post in the linuxserver github https://github.com/linuxserver/docker-calibre-web as they are the ones providing the base image

Okay ill do that thank you for your quick reply

**Comment by alexbelgium** [comment]
Wait, looks like issues already described such as : https://github.com/linuxserver/docker-calibre-web/issues/219#issuecomment-1435559765

I'll push a new version with those modifications

**Comment by pbvdven** [comment]
They fixed one warning but for me the wrong one i still get this one and that engine is needed to convert to pdf.

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________
	Traceback (most recent call last):
	  File "calibre/linux.py", line 837, in setup_completion
	  File "calibre/linux.py", line 587, in write_completion
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/tweak_book/main.py", line 12, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/ebooks/oeb/polish/check/css.py", line 11, in <module>
	ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)

**Comment by alexbelgium** [comment]
I'm sorry I can't help you if the linuxserver github's tells you what we need to change I'll implement that

**Comment by pbvdven** [comment]
sorry but this version lscr.io/linuxserver/calibre-web:latest works fine

**Comment by alexbelgium** [comment]
oh, I see the issue... you're 100% right it wasn't on latest release. I'll solve that now
