### ISSUE TITLE
🐛 [Mealie] Cant add to current day in meal planner

### ISSUE THREAD

**Issue by Scags104** [alexbelgium/hassio-addons#831]
**Which addon?**

- Addon name : Mealie
- Addon version : v1.0.0-beta-4

**Describe the bug**
When adding to the meal planner all dates in the week allow me to add to it except today

**To Reproduce**
Try to add to today

**Full addon log**

**Full addon config**

**System**

- Supervisor version: 2023.04.1
- Host system version: 2023.5.2

**Comment by alexbelgium** [comment]
Hi, you'd have more chances opening the issue on the upstream repo as I only provide the addon.

**Comment by Scags104** [comment]
It's not stale GitHub! 
@alexbelgium looks like it was fixed upstream, any idea when that change will be pushed here? 

Thanks
