### ISSUE TITLE
❓ [gazpar2mqtt] Do you think gazpar2mqtt can be used as a starting point for similar add-on for smartmeter2mqtt ?

### ISSUE THREAD

**Issue by alexboss** [alexbelgium/hassio-addons#832]
**Which addon?**

gazpar2mqtt / smartmeter2mqtt

name: Question
about: Possibility to port smartmeter2mqtt similarly to gazpar2mqtt 
title: ''
labels: ''
assignees: ''

---

**Which addon?**

gazpar2mqtt / smartmeter2mqtt

**Addon or app?**

Addon

**Describe the solution you'd like**

I'd need to have smartmeter2mqtt for Hassio. 

The add-on gazpar2mqtt looks very similar in its purpose / outcome.

I wonder if it would be possible to do something similar with smartmeter2mqtt .

I've read https://github.com/alexbelgium/hassio-addons/issues/326 , I don't expect you to create such add-on, especially since few people may be interested.

However, I'd like you simple feedback / opinion to say if copying your code of gazpar2mqtt and adapting it with the docker image of smartmeter2mqtt with the corresponding parameters would work.

Thanks a lot for your help.

**Describe alternatives you've considered**

I've tried to create an add-on to get smartmeter2mqtt as a node and have it working with Node Red but never managed to make it work.

**Additional context**

SmartMeter2MQTT:
* https://svrooij.io/smartmeter2mqtt/
* https://hub.docker.com/r/svrooij/smartmeter

**Comment by alexbelgium** [comment]
Hi, this was last updated 2 years ago - is it still relevant ? I am sorry but have very little time to create new addons for the moment

**Comment by alexboss** [comment]
Don't worry, I didn't expect you to do the add-on, just to get feedback about technical possibility of grabbing your code of gazpar2mqtt and adapting it with the docker image of smartmeter2mqtt. I'll give it a try and see how it goes. Thanks.

**Comment by alexbelgium** [comment]
No problem - actually it all depends on each docker image is built. I have looked quite quickly and the same strategy could work to use my custom entrypoint logic; only thing is that the 99-run.sh script must launch the current docker entrypoint that is `node ./dist/index.js`

I've made a wiki to describe how I'm creating the addons here : https://github.com/alexbelgium/hassio-addons/wiki/Building-an-addon

Good luck! I can help you once you've started if you want

**Comment by alexboss** [comment]
Perfect, thanks, I'll let you know how it goes.
