### ISSUE TITLE
🐛 [Filebrowser] Can't install ghcr.io/alexbelgium/filebrowser-amd64:2.23.0-6: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.23.0-6&fromImage=ghcr.io%2Falexbelgium%2Ffilebrowser-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

### ISSUE THREAD

**Issue by rqmartins73** [alexbelgium/hassio-addons#834]
- Addon name : Filebrowser
- Addon version : 2.23.0-5 when upgrading to 2.23.0-6

**Describe the bug**
I get this message when trying to update to 2.23.0-6

Can't install ghcr.io/alexbelgium/filebrowser-amd64:2.23.0-6: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.23.0-6&fromImage=ghcr.io%2Falexbelgium%2Ffilebrowser-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

Running:
HAOS 10.1
Core 2023.5.2 (also gave the same error in 2023.4.6)
Supervisor 2023.04.1

Regards.

**Comment by rqmartins73** [comment]
BTW I get this same error when trying to update Emby from 4.8.0.34 to 4.8.0.34-2

**Comment by alexbelgium** [comment]
Hi, indeed there is an issue with many add-ons with fake updates. I'll cancel those updates notifications soon

**Comment by alexbelgium** [comment]
Should be good now. On next repo refresh all those notifications should disappear

**Comment by rqmartins73** [comment]
> Should be good now. On next repo refresh all those notifications should disappear

Yes, can confirm that. Thanks. Have a nice weekend.
