### ISSUE TITLE
🐛 [Transmission OpenVPN] Update impossible !

### ISSUE THREAD

**Issue by novisys** [alexbelgium/hassio-addons#836]
When i try to update this addon i get this error message:
Can't install ghcr.io/alexbelgium/transmission_openvpn-aarch64:v5.0.2-2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=v5.0.2-2&fromImage=ghcr.io%2Falexbelgium%2Ftransmission_openvpn-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

**Comment by alexbelgium** [comment]
Thanks, I've canceled the erroneous update
