### ISSUE TITLE
[Request] portainer agent

### ISSUE THREAD

**Issue by heikok88** [alexbelgium/hassio-addons#840]
Hello, first of all: thank's for your work!

You already have (re)added the portainer addon, but in my use case I just need the portainer agent. I have installed portainer on another host and just want to add home assistant with the agent.

Best regards
Heiko

**Comment by alexbelgium** [comment]
Hi, thanks for your interest! Your request was actually already mapped here https://github.com/alexbelgium/hassio-addons/issues/565 so I'll close your request to centralize the discussion.

I was hoping to merge both agent and portainer in a single image to simplify maintenance but haven't yet had the time

Best regards

**Comment by heikok88** [comment]
Hey Alex, sry, i forgot to use the search function xD
Maybe I can help: I am a software engineer and could give it a try - but I would use dedicated images.

**Comment by alexbelgium** [comment]
Thanks for the proposal! I've also written a guide how to make add-ons based on custom docker images in the repo wiki. After having a look on dockerhub it seems a nice agent container already exist. I'll look to build it, it should be rather fast. Especially as I understand from the way it works no data needs to be remanent and survive restart? It's just a monitoring local agent ? Thanks

**Comment by alexbelgium** [comment]
Hi, I've pushed a first version, please let me know how it goes
