### ISSUE TITLE
✨ [REQUEST] Nextcloud - nginx- client_max_body_size 

### ISSUE THREAD

**Issue by blendrik** [alexbelgium/hassio-addons#846]
First of all: I really appreciate that you are spending your free time providing the Nextcloud add-on. Thank you!

**Which addon?**

Nexcloud

**Is your feature request related to a problem? Please describe.**
Upload a >2 GB file via Nextcloud Windows client results in nginx error: 413 request entity too large

**Describe the solution you'd like**

Could you please consider raising  client_max_body_size in the default.conf?

nginx default.conf
```
server {
.
.
.
   # set max upload size and increase upload timeout:
    client_max_body_size 8192M;
    client_body_timeout 300s;
    fastcgi_buffers 64 4K;

``` 

**Describe alternatives you've considered**
Changing the default.conf in the config folder myself is only lasting until restarting the docker container. The file gets overwritten at each restart.

**Comment by alexbelgium** [comment]
Hi, sure I've aligned all upload relevant values. I'll push the version this afternoon once stats have run

**Comment by blendrik** [comment]
Hi, that was quick. Thanks a lot!
