### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pbvdven** [alexbelgium/hassio-addons#85]
Could you add an addon for audiobooks please. im a big fan of your addons there very helpful but im missing some kind off tool for audiobooks. maybe docker-booksonic-air.

sorry if this is not the way to ask but i didn't know another way.

**Comment by alexbelgium** [comment]
Hi, I've pushed a version, could you please test if everything works and if it functions as you would expected ? thanks

**Comment by alexbelgium** [comment]
It's a bit long to start but should work

**Comment by pbvdven** [comment]
Wow thats fast thanks. I’ll test it little bit I’m on my way home right now.

**Comment by pbvdven** [comment]
yes it works nice. first run takes a while but after then it runs smooth. thanks your the best
![image](https://user-images.githubusercontent.com/39600990/141850063-fe3ccaf5-b454-40cb-abfa-770a58f83aaf.png)

**Comment by alexbelgium** [comment]
Thanks! did you already restart it? To test for persistence. Thanks!

**Comment by pbvdven** [comment]
Yes no issues. It works great maybe i shoud mention i don’t use the smb option. I have all my drives mounted in the hassio/share folder. im running home assistant supervised on debian. I ran it first in docker but then home assistant gets unsupported i know thats no real issue but i like this better. Thank you 🙏

**Comment by alexbelgium** [comment]
Thanks for the precisions. I'll close this as it works! Enjoy!
