### ISSUE TITLE
Mealie - database not retained between restarts

### ISSUE THREAD

**Issue by ezpl** [alexbelgium/hassio-addons#856]
I am experiencing that changes to the database is not committed, it seems to reside in memory only. I belive this started occurring after upgrading to 1.0.1 (03-01-2023) and doing the required backup/restore from within Mealie.

If I add something in Mealie, then restarts the addon, it just disappears and reverts to the old DB version. What could be the cause of this? Would the best resolution be to uninstall Mealie and restore from the in-app backup?

```
-----------------------------------------------------------
 Add-on: Mealie (Omni):
 Mealie is a self hosted recipe manager and meal planner built in Vue
-----------------------------------------------------------
 Add-on version: v1.0.0-beta-5
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[15:40:44] INFO: Execute /config/addons_autoscripts/mealie.sh if existing
[15:40:44] INFO: ... no script found
/etc/cont-init.d/31-nginx.sh: executing
[15:40:44] INFO: Exporting variables
ALLOW_SIGNUP=true
PGID=0
PUID=0
certfile=fullchain.pem
keyfile=privkey.pem
ssl=false
[15:40:44] INFO: No config.yaml found in /config/addons_config/mealie/config.yaml, using default parameters
Permissions adapted
[15:40:44] WARNING: Data migration for amd64
[15:40:44] WARNING: Data migrated to /config/addons_config/mealie_data ; you can now use the new addons. For aarch64, you need to do a manual backup and restore
[15:40:45] INFO: Starting app
[15:40:45] INFO: Starting app
```

**Comment by alexbelgium** [comment]
Indeed it seems that the argument I used to change data dir doesn't exist. I've set an env variable that should do the same

**Comment by ezpl** [comment]
Awesome that you had time to look at this! I will have a look inside the data dirs and if I'm lucky, I will find my data there. Anyway, the most important is that I can get it working again. 

I'll let you know how it goes 😊

**Comment by alexbelgium** [comment]
Hope it will work... A key element is to have frequent backups I usually backup my whole HA system once per week to Google drive using an add-on. By having backups of add-ons and /config it significantly decreases any chance of data lost, and allows to downgrade when needed!

**Comment by alexbelgium** [comment]
Tests done :
- [ ] Installed current version, add recipe, restart, check recipe stays
- [ ] Try to mimick upgrade process
- [ ] ...

**Comment by ezpl** [comment]
The data is retained after restarts now with the latest version 👍

I have tried to look through some backups, but none of them contain any updates after april or so. Seems like my suspicion was right - nothing has been committed to the database? Does that make sense?

**Comment by ezpl** [comment]
No worries. It is only a few recepies and som config.
What you suggest was my first thought as well. I have already tried a couple of the weekly backups witout any luck.
Thanks for the quick response with this matter!
