### ISSUE TITLE
❓ [Paperless] HTTPS / SSL won't work

### ISSUE THREAD

**Issue by SeeThisIsMe** [alexbelgium/hassio-addons#857]
Hi, 

I've recently installed the Paperless addon and am trying to get it working with HTTPS. I think its all configured correctly; cert/key files are in place and the addon URL option should be correct including port numbers. But every time I try to view the HTTPS page I get this:

![image](https://github.com/alexbelgium/hassio-addons/assets/53046241/154b79f7-5e2d-4eb9-b09b-6c786966e9d1)

HTTP works fine. Perhaps there's an issue with the SSL handling for the addon? It seems somewhat similar to an issue I had a couple of months ago with Mealie, and that was caused by the addon package https://github.com/alexbelgium/hassio-addons/issues/782

Thanks!

**Comment by alexbelgium** [comment]
Addon deprecated, I recommend to use this one : https://github.com/BenoitAnastay/home-assistant-addons-repository
