### ISSUE TITLE
Problème HC/HP

### ISSUE THREAD

**Issue by YNK-22** [alexbelgium/hassio-addons#86]
Hello Alex,

Tout d'abord merci pour cet Addon, très bien fait et bien pensé !

Mais j'ai encore quelques soucis, notamment au niveau des heures creuses/heures pleines lorsque j'indique mes heures creuses voici ce que j'obtiens dans les logs, à noter que j'ai indiqué mes HC de cette façon `OFFPEAK_HOURS: 00h00-06h24;22h24-23h59`

`"Linky", "manufacturer": "Enedis"}}
Traceback (most recent call last):
  File "/app/main.py", line 640, in <module>
    run()
  File "/app/main.py", line 565, in run
    my_enedis_data = myenedis.myEnedis(cur, con, client, last_activation_date, offpeak_hours)
  File "/app/myenedis.py", line 414, in myEnedis
    dateBegin = today.replace(hour=int(plage[0].split("H")[0]), minute=int(plage[0].split("H")[1]), second=0)
ValueError: invalid literal for int() with base 10: '00h00'
[10:36:24] FATAL: The app has crashed. Are you sure you entered the correct config options?
exit 0`

Et deuxième question : J'ai souvent le message d'erreur comme quoi j'ai atteint la limite des 50 appels de l'API mais a t'on moyen de mettre une limite ?

Merci beaucoup !

**Comment by alexbelgium** [comment]
Bonjour, merci! 

En fait l'addon est l'intégration dans HA d'une app développée ici : https://github.com/m4dm4rtig4n/enedisgateway2mqtt
Donc je m'occupe des soucis addon, mais pour les soucis app que tu rencontres il vaut mieux poster là bas... Je t'ai ouvert une issue ici : https://github.com/m4dm4rtig4n/enedisgateway2mqtt/issues/52

Je viens de pousser une nouvelle version de l'addon par contre qui change toute la logique par contre :-)
Il faut maintenant mettre les infos dans un fichier config.yaml depuis la version 0.7.1 de l'addon.  Le fichier est créé automatiquement au premier boot de l'addon

Bonne journée!

**Comment by YNK-22** [comment]
Super merci ! J'attends de voir ce que ça donne dans l'issue avant de faire la maj dans ce cas.

Merci, bonne journée à toi !
