### ISSUE TITLE
❓ [almost all] Better isolate addons configs - do not use /config/addons_config

### ISSUE THREAD

**Issue by iBobik** [alexbelgium/hassio-addons#863]
**Which addon?**
Almost all

**Addon or app?**

Addon

**Describe the solution you'd like**

I would like to better secure all apps I use in the Hassio, so by default use named volumes. Currently config is saved to the shared /config/addons_config, so one compromised addon can potentially write to configs of all other.

**Describe alternatives you've considered**

Users who are concerned about it can configure it, but who will do it...

**Additional context**

If addon can be compromised or compromise others then this could raise wrong expectations about security:

<img width="353" alt="Snímek obrazovky 2023-06-09 v 17 45 06" src="https://github.com/alexbelgium/hassio-addons/assets/614232/35fcfedf-9b4f-47d1-aafd-9db0acf8d589">

**Comment by alexbelgium** [comment]
Dear iBobik, I do understand your point but HAos doesn't support named volumes. So we need to use an already mapped folder, such as /config or /share which intrisically causes the security issue that you are raising. It would be possible to move everything to /share with an overlap period in which all addons can access both /config and /share, however this would probably create major headaches for users in addition to still allowing all addons to access each others data. Therefore, we'll have to keep the current situation until HAos allows more granular permissions, for example to map a particular volume (/config/addon_name) instead... HAos logic requests to avoid doing that and only use the /data folder that is internal to the addon, however this blocks users customization as they don't have easy access to the files without advanced tools such as portainer that are prone to create other issues and are discouraged by the HAos team

**Comment by alexbelgium** [comment]
Thanks, I upvoted. Indeed it should be easy to implement for them and high security value
