### ISSUE TITLE
🐛 [EPIC GAMES FREE] Captcha not working

### ISSUE THREAD

**Issue by ajcorrea** [alexbelgium/hassio-addons#869]
### Description

Just installed and configured addon:
config.json
`
{
    "runOnStartup": true,
    "cronSchedule": "15 18 * * *",
    "logLevel": "info",
    "webPortalConfig": {
        "baseUrl": "http://192.168.0.114:3005",
    },
    "accounts": [
        {
            "email": "my-epic-games-login@gmail.com",
            "password": "my-password"
        },
    ],
    "notifiers": [
    {
        "type": "email", // This indicates the notifier type
        "smtpHost": "smtp.gmail.com",
        "smtpPort": 587,
        "emailSenderAddress": "my-email-gmail-account@gmail.com",
        "emailSenderName": "[HomeAssistant]: Epic Games Captchas",
        "emailRecipientAddress": "my-other-email@gmail.com",
        "secure": true,
        "auth": {
            "user": "my-email-gmail-account@gmail.com",
            "pass": "my-password",
        },
    },
    ],
}
`

and gettings this error:

`
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Epic Games Free
 Automatically login and redeem promotional free games from Epic Games Store
-----------------------------------------------------------
 Add-on version: bullseye-slim-2023-05-03
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.6.0
 Home Assistant Supervisor: 2023.06.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[17:02:02] INFO: Execute /config/addons_autoscripts/epicgamesfree.sh if existing
[17:02:02] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/99-run.sh: executing
[17:02:02] WARNING: The config.json file found in /config/addons_config/epicgamesfree will be used. Please customize according to https://github.com/claabs/epicgames-freegames-node#json-configuration and restart the add-on
 
[17:02:02] INFO: Starting the app
 

> epicgames-freegames-node@4.1.0 entrypoint-config
> node dist/src/entrypoint-config.js

npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.7.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
npm notice Run `npm install -g npm@9.7.1` to update!
npm notice 
Setting timezone: America/Fortaleza
Run on startup: true
[2023-06-12 17:02:04.287 -0300] INFO: Started epicgames-freegames-node
    COMMIT_SHA: "c0dfe30ee94fa609a9efcb5eb2b8fd0c1dafe6e2"
    BRANCH: "master"
    DISTRO: "alpine"
[2023-06-12 17:02:04.634 -0300] INFO: Checking free games for my-epic-games-login@gmail.com 
    user: "my-epic-games-login@gmail.com"
[2023-06-12 17:02:17.542 -0300] INFO: Go to this URL and do something
    user: "my-epic-games-login@gmail.com"
    url: "http://192.168.0.114:3005/?targetId=5EEA09BF70DB4F80A087F595BD04F2F9"
[2023-06-12 17:02:17.858 -0300] ERROR: Error sending email. Please check your configuration
    user: "my-email-gmail-account@gmail.com"
    reason: "LOGIN"
    emailConfig: {
      "type": "email",
      "secure": true,
      "smtpHost": "smtp.gmail.com",
      "smtpPort": 587,
      "emailSenderAddress": "my-email-gmail-account@gmail.com",
      "emailSenderName": "[HomeAssistant]: Epic Games Captchas",
      "emailRecipientAddress": "my-other-email@gmail.com",
      "auth": {
        "user": "my-email-gmail-account@gmail.com",
        "pass": "my-password"
      }
    }
[2023-06-12 17:02:18.024 -0300] ERROR: Encountered an error during browser automation. Saved a screenshot for debugging purposes.
    user: "my-epic-games-login@gmail.com"
    errorFile: "error-2023-06-12T20:02:17.858Z.png"
[2023-06-12 17:02:18.030 -0300] ERROR: 380BC2E4DB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

    user: "my-email-gmail-account@gmail.com"
    err: {
      "type": "Error",
      "message": "380BC2E4DB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n",
      "stack":
          Error: 380BC2E4DB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
          
      "library": "SSL routines",
      "reason": "wrong version number",
      "code": "ESOCKET",
      "command": "CONN"
    }
[2023-06-12 17:02:18.030 -0300] WARN: Current version
    COMMIT_SHA: "c0dfe30ee94fa609a9efcb5eb2b8fd0c1dafe6e2"
    BRANCH: "master"
    DISTRO: "alpine"
[2023-06-12 17:02:18.030 -0300] INFO: Exiting successfully
Run once: false
Setting cron schedule as 15 18 * * *
`

i have a cookie file on the /config folder, using the how-to on read.me (Installed Chrome Extension and dump cookie data).

### Reproduction steps

```bash
Install and configure
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Epic Games Free
 Automatically login and redeem promotional free games from Epic Games Store
-----------------------------------------------------------
 Add-on version: bullseye-slim-2023-05-03
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.6.0
 Home Assistant Supervisor: 2023.06.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[17:02:02] INFO: Execute /config/addons_autoscripts/epicgamesfree.sh if existing
[17:02:02] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/99-run.sh: executing
[17:02:02] WARNING: The config.json file found in /config/addons_config/epicgamesfree will be used. Please customize according to https://github.com/claabs/epicgames-freegames-node#json-configuration and restart the add-on
 
[17:02:02] INFO: Starting the app
 

> epicgames-freegames-node@4.1.0 entrypoint-config
> node dist/src/entrypoint-config.js

npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.7.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
npm notice Run `npm install -g npm@9.7.1` to update!
npm notice 
Setting timezone: America/Fortaleza
Run on startup: true
[2023-06-12 17:02:04.287 -0300] INFO: Started epicgames-freegames-node
    COMMIT_SHA: "c0dfe30ee94fa609a9efcb5eb2b8fd0c1dafe6e2"
    BRANCH: "master"
    DISTRO: "alpine"
[2023-06-12 17:02:04.634 -0300] INFO: Checking free games for my-epic-games-login@gmail.com 
    user: "my-epic-games-login@gmail.com"
[2023-06-12 17:02:17.542 -0300] INFO: Go to this URL and do something
    user: "my-epic-games-login@gmail.com"
    url: "http://192.168.0.114:3005/?targetId=5EEA09BF70DB4F80A087F595BD04F2F9"
[2023-06-12 17:02:17.858 -0300] ERROR: Error sending email. Please check your configuration
    user: "my-email-gmail-account@gmail.com"
    reason: "LOGIN"
    emailConfig: {
      "type": "email",
      "secure": true,
      "smtpHost": "smtp.gmail.com",
      "smtpPort": 587,
      "emailSenderAddress": "my-email-gmail-account@gmail.com",
      "emailSenderName": "[HomeAssistant]: Epic Games Captchas",
      "emailRecipientAddress": "my-other-email@gmail.com",
      "auth": {
        "user": "my-email-gmail-account@gmail.com",
        "pass": "my-password"
      }
    }
[2023-06-12 17:02:18.024 -0300] ERROR: Encountered an error during browser automation. Saved a screenshot for debugging purposes.
    user: "my-epic-games-login@gmail.com"
    errorFile: "error-2023-06-12T20:02:17.858Z.png"
[2023-06-12 17:02:18.030 -0300] ERROR: 380BC2E4DB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

    user: "my-email-gmail-account@gmail.com"
    err: {
      "type": "Error",
      "message": "380BC2E4DB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n",
      "stack":
          Error: 380BC2E4DB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
          
      "library": "SSL routines",
      "reason": "wrong version number",
      "code": "ESOCKET",
      "command": "CONN"
    }
[2023-06-12 17:02:18.030 -0300] WARN: Current version
    COMMIT_SHA: "c0dfe30ee94fa609a9efcb5eb2b8fd0c1dafe6e2"
    BRANCH: "master"
    DISTRO: "alpine"
[2023-06-12 17:02:18.030 -0300] INFO: Exiting successfully
Run once: false
Setting cron schedule as 15 18 * * *
```

**Comment by Teberon** [comment]
There seems to be an update for this issue https://github.com/claabs/epicgames-freegames-node/pull/352
