### ISSUE TITLE
[transmission with openvpn] Transmission doesn't see the .ovpn file

### ISSUE THREAD

**Issue by Stooovie** [alexbelgium/hassio-addons#874]
### Description

I'm getting
`[14:42:15] FATAL: Ovpn file not found at location provided : /config/addons_config/transmission`

config is:
DEBUG: false
DNS_server: 8.8.8.8,1.1.1.1
LOCAL_NETWORK: 192.168.0.0/24
OPENVPN_PASSWORD: redacted
OPENVPN_USERNAME: "REDACTED"
PGID: "0"
PUID: "0"
TRANSMISSION_DOWNLOAD_DIR: /mnt/Public/Downloads
TRANSMISSION_HOME: /config/addons_config/transmission
TRANSMISSION_INCOMPLETE_DIR: /mnt/Public/Downloads
TRANSMISSION_V3_UPDATE: "true"
TRANSMISSION_WATCH_DIR: /share/watch_dir
TRANSMISSION_WEB_UI: flood-for-transmission
OPENVPN_PROVIDER: mullvad
OPENVPN_CUSTOM_PROVIDER: true
networkdisks: //192.168.0.216/Public
cifsusername: stooovie
cifspassword: Sassword2
auto_restart: true
OPENVPN_CONFIG: mullvad_cz_prg.ovpn
OPENVPN_CUSTOM_PROVIDER_OVPN_LOCATION: /config/addons_config/transmission

The file is definitely there :)
![Screenshot 2023-06-15 at 14 44 30](https://github.com/alexbelgium/hassio-addons/assets/10572373/d6914d13-31dc-4b48-bacc-6ba82cf4fa77)

HAOS in Proxmox VM. I use your QBittorrent addon with similar config and the same ovpn file without issue (want to switch to Transmission due to QBittorrent high CPU usage with VPN).

### Reproduction steps

```bash
Set OPENVPN_CUSTOM_PROVIDER_OVPN_LOCATION: /config/addons_config/transmission

copy mullvad_cz_prg.ovpn there, it isn't found
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Transmission Openvpn
 Docker container running Transmission torrent client with WebUI over an OpenVPN tunnel
-----------------------------------------------------------
 Add-on version: v5.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.2  (amd64 / qemux86-64)
 Home Assistant Core: 2023.6.2
 Home Assistant Supervisor: 2023.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
Mounting smb share(s)...
Using PUID 0 and PGID 0
[14:42:08] INFO: ... //192.168.0.216/Public successfully mounted to /mnt/Public with options ,uid=0,gid=0,iocharset=utf8
/etc/cont-init.d/01-custom_script.sh: executing
[14:42:08] INFO: Execute /config/addons_autoscripts/transmission-openvpn.sh if existing
[14:42:08] INFO: ... no script found
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/90-dns_set.sh: executing
[14:42:08] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
/etc/cont-init.d/99-run.sh: executing
[14:42:08] INFO: Updating transmission to v3
[14:42:08] WARNING: If your previous version was v2, remove and add torrents again
--2023-06-15 14:42:08--  https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa37da909ae70535824d82620976b5901365c5ca1
Resolving keyserver.ubuntu.com (keyserver.ubuntu.com)... 162.213.33.9, 162.213.33.8
Connecting to keyserver.ubuntu.com (keyserver.ubuntu.com)|162.213.33.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1804 (1.8K) [text/plain]
Saving to: '976b5901365c5ca1.key'
     0K .                                                     100%  624M=0s
2023-06-15 14:42:08 (624 MB/s) - '976b5901365c5ca1.key' saved [1804/1804]
debconf: delaying package configuration, since apt-utils is not installed
[14:42:12] INFO: Exporting variables
DEBUG=false
DNS_server=8.8.8.8,1.1.1.1
LOCAL_NETWORK=192.168.0.0/24
OPENVPN_CONFIG=mullvad_cz_prg.ovpn
OPENVPN_CUSTOM_PROVIDER=true
OPENVPN_CUSTOM_PROVIDER_OVPN_LOCATION=/config/addons_config/transmission
OPENVPN_PASSWORD=<REDACTED>
OPENVPN_PROVIDER=mullvad
OPENVPN_USERNAME=<REDACTED>
PGID=0
PUID=0
TRANSMISSION_DOWNLOAD_DIR=/mnt/Public/Downloads
TRANSMISSION_HOME=/config/addons_config/transmission
TRANSMISSION_INCOMPLETE_DIR=/mnt/Public/Downloads
TRANSMISSION_V3_UPDATE=true
TRANSMISSION_WATCH_DIR=/share/watch_dir
TRANSMISSION_WEB_UI=flood-for-transmission
auto_restart=true
cifspassword=Sassword2
cifsusername=stooovie
networkdisks=//192.168.0.216/Public
Using PUID 0 and PGID 0
[14:42:15] INFO: Custom openvpn provider selected
[14:42:15] FATAL: Ovpn file not found at location provided : /config/addons_config/transmission
/etc/cont-init.d/99-run.sh: exiting 1
```

### Architecture

armv7

### OS

Virtual Machine

**Comment by alexbelgium** [comment]
Hi, thanks! Please try setting :
`OPENVPN_CUSTOM_PROVIDER_OVPN_LOCATION: /config/addons_config/transmission/mullvad_cz_prg.ovpn`

**Comment by Stooovie** [comment]
When I completely omit the VPN provider field, I get this

`Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
+ [[ 1 == \1 ]]
+ echo 'Modification: Change ca certificate path'
++ dirname /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ config_directory=/etc/openvpn/mullvad_cz_prg
+ sed -i -E 's#ca\s+(.*/)*#ca /etc/openvpn/mullvad_cz_prg/#g' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
Modification: Change ping options
+ [[ 1 == \1 ]]
+ echo 'Modification: Change ping options'
+ sed -i '/^inactive.*$/d' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ sed -i '/^ping.*$/d' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ sed -i '/^keepalive.*$/d' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ sed -i '$q' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ echo 'inactive 3600'
+ echo 'ping 10'
+ echo 'ping-exit 60'
+ [[ 1 == \1 ]]
+ echo 'Modification: Update/set resolv-retry to 15 seconds'
+ sed -i '/^resolv-retry.*$/d' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
Modification: Update/set resolv-retry to 15 seconds
+ sed -i '$q' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ echo 'resolv-retry 15'
Modification: Change tls-crypt keyfile path
+ [[ 1 == \1 ]]
+ echo 'Modification: Change tls-crypt keyfile path'
++ dirname /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ config_directory=/etc/openvpn/mullvad_cz_prg
+ sed -i -E 's#tls-crypt\s+(.*/)*#tls-crypt /etc/openvpn/mullvad_cz_prg/#g' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ [[ 3 -gt 0 ]]
+ [[ 3 -gt 9 ]]
+ echo 'Modification: Set output verbosity to 3'
+ sed -i '/^verb.*$/d' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
Modification: Set output verbosity to 3
+ sed -i '$q' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ echo 'verb 3'
+ [[ 1 == \1 ]]
+ echo 'Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop'
+ sed -i '/^remap-usr1.*$/d' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
+ sed -i '$q' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ echo 'remap-usr1 SIGTERM'
Modification: Updating status for config failure detection
+ [[ 1 == \1 ]]
+ echo 'Modification: Updating status for config failure detection'
++ sed -n 's/^; status \(.*\)/\1/p' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ CONFIG_STATUS=
+ [[ '' == \u\n\k\n\o\w\n ]]
+ [[ '' != \f\a\i\l\u\r\e ]]
+ CONFIG_STATUS=unknown
+ sed -i '/^; status.*$/d' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ sed -i '$q' /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ echo '; status unknown'
+ [[ unknown == \f\a\i\l\u\r\e ]]
+ [[ -x /scripts/openvpn-post-config.sh ]]
+ mkdir -p /config/addons_config/transmission_openvpn
+ [[ -f /run/secrets/openvpn_creds ]]
+ [[ 1770151644487821 == \*\*\N\o\n\e\*\* ]]
Setting OpenVPN credentials...
+ [[ m == \*\*\N\o\n\e\*\* ]]
+ echo 'Setting OpenVPN credentials...'
+ echo -e '1770151644487821\nm'
+ chmod 600 /config/addons_config/transmission_openvpn/openvpn-credentials.txt
+ [[ -f /run/secrets/rpc_creds ]]
+ echo ''
+ echo ''
+ export CONFIG=/etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ CONFIG=/etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
+ python3 /etc/openvpn/persistEnvironment.py /etc/transmission/environment-variables.sh
+ TRANSMISSION_CONTROL_OPTS='--script-security 2 --route-up /etc/openvpn/tunnelUp.sh --route-pre-down /etc/openvpn/tunnelDown.sh'
+ [[ false == \t\r\u\e ]]
+ [[ -n 192.168.0.0/24 ]]
++ /sbin/ip route list match 0.0.0.0
++ awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}'
+ eval GW=172.30.32.1 INT=eth0
++ GW=172.30.32.1
++ INT=eth0
+ [[ false == \t\r\u\e ]]
+ [[ false == \t\r\u\e ]]
+ [[ -n 192.168.0.0/24 ]]
+ [[ -n 172.30.32.1 ]]
+ [[ -n eth0 ]]
+ for localNet in ${LOCAL_NETWORK//,/ }
+ echo 'adding route to local network 192.168.0.0/24 via 172.30.32.1 dev eth0'
adding route to local network 192.168.0.0/24 via 172.30.32.1 dev eth0
+ /sbin/ip route replace 192.168.0.0/24 via 172.30.32.1 dev eth0
+ [[ false == \t\r\u\e ]]
+ [[ -x /scripts/routes-post-start.sh ]]
+ [[ false != \f\a\l\s\e ]]
+ exec openvpn --script-security 2 --route-up /etc/openvpn/tunnelUp.sh --route-pre-down /etc/openvpn/tunnelDown.sh --config /etc/openvpn/mullvad_cz_prg/mullvad_cz_prg.ovpn
2023-06-15 15:10:30 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
2023-06-15 15:10:30 OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
2023-06-15 15:10:30 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
2023-06-15 15:10:30 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-06-15 15:10:30 TCP/UDP: Preserving recently used remote address: [AF_INET]185.216.35.242:1301
2023-06-15 15:10:30 Socket Buffers: R=[212992->1048576] S=[212992->1048576]
2023-06-15 15:10:30 UDP link local: (not bound)
2023-06-15 15:10:30 UDP link remote: [AF_INET]185.216.35.242:1301
2023-06-15 15:11:30 [UNDEF] Inactivity timeout (--ping-exit), exiting
2023-06-15 15:11:30 SIGTERM[soft,ping-exit] received, process exiting`

I get Bad Gateway throughout the entire process (which is probably expected)

**Comment by alexbelgium** [comment]
Great! What was the config that worked in the end ?

**Comment by Stooovie** [comment]
Just yours tip to include the filename in the path. For whatever reason it took a while to start working, but it does, I have checked with IPLeaks and the tunnel indeed works. Thank you so much!
