### ISSUE TITLE
🐛 [Nextcloud] Failed to start addon

### ISSUE THREAD

**Issue by big-jon** [alexbelgium/hassio-addons#878]
### Description

Updated nextcloud addon to 27.0.0. Now, when I select start I get the following error:
"Image ghcr.io/alexbelgium/nextcloud_ocr-amd64:27.0.0 does not exist for addon_db21ed7f_nextcloud_ocr"
Previous nextcloud version was 26.0.2.
I also just updated Home Assistant OS to 10.3, and Supervisor to 2023.06.2.
My hardware is an intel nuc, which reports to home assistant as Generic x86-64.

### Reproduction steps

```bash
1. Update Nextcloud version to 27.0.0.
2. Navigate to the Nextcloud add-on in Home Assistant and select 'Start'
3. See error above
```

### Addon Logs

```bash
The nextcloud log is empty. 
Home Assistant Core log shows:

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 4:04:30 PM (5 occurrences)
Last logged: 8:16:31 PM

Failed to to call /addons/db21ed7f_nextcloud_ocr/start - Image ghcr.io/alexbelgium/nextcloud_ocr-amd64:27.0.0 does not exist for addon_db21ed7f_nextcloud_ocr
```

### Architecture

Aarch64

### OS

Haos

**Comment by alexbelgium** [comment]
Alas this is a supervisor bug. Or didn't download the image for the add-on. You should restore your add-on backup and update again to 27.0. Also, be sure that your nextcloud version is at least v26! There is an iron to disable updates - if it is enabled and you are still on nextcloud 25 or below, you won't be able to start the add-on after installation

**Comment by alexbelgium** [comment]
Other solution : go in the add-on `terminal ssh` and execute the command `docker pull ghcr.io/alexbelgium/nextcloud_ocr-amd64:27.0.0`

**Comment by big-jon** [comment]
The docker pull command worked perfectly. Thanks!
