### ISSUE TITLE
enedisgateway2mqtt : config file indentation is bad

### ISSUE THREAD

**Issue by LittleBigDev** [alexbelgium/hassio-addons#88]
Hello,

In config file, under `enedis_gateway:` some entries are 4 spaces indented, instead of 2 spaces. Makes addon to crash at start with error
```
expected <block end>, but found '<block mapping start>'
  in "/data/config.yaml", line 42, column 5
```
(not exactly this lane, I already started fixing it)

**Comment by alexbelgium** [comment]
that's funny I had tested it on yamllint.com without issue, thanks for reporting!

**Comment by alexbelgium** [comment]
> enedis_gateway:

I don't see 4 spaces though in the template...
https://github.com/alexbelgium/hassio-addons/blob/master/enedisgateway2mqtt/rootfs/templates/config.yaml

**Comment by LittleBigDev** [comment]
I just didn't understand data hierarchy. Indentation was good, and I was wrong.

**Comment by alexbelgium** [comment]
Thanks!
