### ISSUE TITLE
🐛 [paperless_ngx] Updates are not recognised

### ISSUE THREAD

**Issue by rafael298** [alexbelgium/hassio-addons#889]
### Description

I use version 1.15.1 of the paperless_ngx addon. Unfortunately, updates are not recognised by the Home Assistant Supervisor and are not displayed. Version in Repository ist 1.16.5

### Reproduction steps

```bash
1. Go to 'Settings'
2. Click on 'Add-Ons'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
No Errors in Addon-Logs
```

### Architecture

armv7

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, actually it's because the upstream paperless image I'm using (made by linuxserver) is not developed anymore... Migrating to the official image is a big work. Which means that currently I'm living with this discrepancy until I have time to convert the addon to the new official image...

**Comment by rafael298** [comment]
do you have any idea if or when this will happen?

**Comment by alexbelgium** [comment]
Perhaps in a couple weeks when I'll have time... It is a major change the whole logic needs to be rewritten

**Comment by iroQuai** [comment]
I really hope you will find the time! Thanks in advance

**Comment by alexbelgium** [comment]
Well it seems more complicated than expected.  I'm testing in my test repo but it doesn't start yet. So it will again be delayed by a bit

**Comment by iroQuai** [comment]
Thanks for all the efforts!! We'll just keep on hoping and waiting

**Comment by ciB89** [comment]
I am confused, wasn't the linuxserver image deprecated over a year ago? How were you able to update based on that image beforehand?

**Comment by rafael298** [comment]
Is there still work in progress?

**Comment by alexbelgium** [comment]
Hi, indeed I was using the linuxserver paperless ngx image. I've put a version with the official image in my test repo but it was failing. I'll perhaps have time next weekend to check

**Comment by Yax** [comment]
@alexbelgium do you need help to fix this issue? Maybe I can do something to migrate to official docker.

**Comment by ciB89** [comment]
> Hi, indeed I was using the linuxserver paperless ngx image. I've put a version with the official image in my test repo but it was failing. I'll perhaps have time next weekend to check

I still don't get it. According to YOUR changelog you switched to official image on the 2nd of November, 2022. That was version 1.9.2. But now it got stuck on version 1.15.1, so it was working fine before, even after the switch?

**Comment by alexbelgium** [comment]
Hi, I have put a test version here https://github.com/alexbelgium/hassio-addons-test based on 2.0 but it doesn't work yet. Not sure why and alas I don't have much time for the moment

**Comment by iroQuai** [comment]
I noticed there is another repo that offers paperless-ngx as an addon! Its version 1.17.4-dev. 
You can find it here: https://github.com/BenoitAnastay/paperless-home-assistant-addon

Now maybe this is useless for you, but I thought maybe there are some leads in this work to add to your own? (i'm not tech savy enough to know if there is any logic to what I'm saying... sorry if there isn't!)

**Comment by alexbelgium** [comment]
Hi, thanks all. I have a v2.0 ready to test could you please let me know if you can test? It implements the new config system from HA so the data location will change. In theory it is automatic but it will perhaps result in a need for database rebuild

**Comment by iroQuai** [comment]
I just noticed! Updating now :) looking forward using paperless again within my HA setup. Thanks a lot for your persistent work!!

**Comment by ciB89** [comment]
> I just noticed! Updating now :) looking forward using paperless again within my HA setup. Thanks a lot for your persistent work!!

And? I also just updated, it started, but when trying to log in nothing happens..

**Comment by alexbelgium** [comment]
By the way, it implements the new config structure from HA (cf. Changeling). This will allow (once everyone has migrated) to stop giving access to the add-ons the the main HA config directory. Also, it will allow to backup config at the same time as the add-on. The issue is that to access it, the only way is my filebrowser or cloud commander add-ons that map the new config folder to /addons_config. In theory, the file transfer should be automatic

**Comment by ciB89** [comment]
Ah, sorry, I did not realize that I changed my config files not correctly. Now I got the following error though:

```
/etc/cont-init.d/99-run.sh: executing
/.//etc/cont-init.d/99-run.sh: line 5: export: `files/media': not a valid identifier
Error : /etc/cont-init.d/99-run.sh exiting 1
```

I do not see it mounting my network/local disks (which is in my config, and also posted on startup):

```
localdisks='G-Drive'
networkdisks='//192.168.0.177/ciB paperless files'
```

It used to say something like "XXX successfully mounted" in the logs, but now it's not there, hence it cannot find the folder/location.

**Comment by ciB89** [comment]
Why this change?

```
- ARG MODULES="00-banner.sh 01-custom_script.sh 00-local_mounts.sh 00-smb_mounts.sh 01-config_yaml.sh"
+ ARG MODULES="00-banner.sh 01-custom_script.sh"
```

This makes local / remote mounts impossible, no?

**Comment by alexbelgium** [comment]
> Why this change?
> 
> ```
> - ARG MODULES="00-banner.sh 01-custom_script.sh 00-local_mounts.sh 00-smb_mounts.sh 01-config_yaml.sh"
> + ARG MODULES="00-banner.sh 01-custom_script.sh"
> ```
> 
> This makes local / remote mounts impossible, no?

Indeed, readdad and new version pushed

**Comment by alexbelgium** [comment]
"/.//etc/cont-init.d/99-run.sh: line 5: export: `files/media': not a valid identifier" of course there is no code on line 5. To which parameter corresponds files/media?

**Comment by alexbelgium** [comment]
Pushed a v3 I understood the source of error. I think your folders should be absolute in theory and not relative but well if it works... Normal path beeing /config/media instead of /config/addons_config/paperless_ngx/media

**Comment by ciB89** [comment]
ß0i8z6k

> Pushed a v3 I understood the source of error. I think your folders should be absolute in theory and not relative but well if it works... Normal path beeing /config/media instead of /config/addons_config/paperless_ngx/media

it's absolute, as you can see in my config setup, I do not know why the error only outputs part of the path (I presume it has to do with the whitespaces)

**Comment by ciB89** [comment]
So, mounting works, for me the error though persists. My path is:

`PAPERLESS_MEDIA_ROOT='/mnt/ciB paperless files/media'`

It used to work with this, but now it seems it's having trouble resolving the path?

**Comment by ciB89** [comment]
I found a typo (well, I asked chatGPT): 

`echo "$variable=\"$variablecontent\"" >> /etc/environme**m**t`

should be

`echo "$variable=\"$variablecontent\"" >> /etc/environme**n**t`

I think that might fix the problem.

**Comment by alexbelgium** [comment]
I see I need to find a way to deal with whitespace then. Thanks very much for the typo correction it affected all add-ons as it was a  common script!

**Comment by ciB89** [comment]
> I see I need to find a way to deal with whitespace then. Thanks very much for the typo correction it affected all add-ons as it was a common script!

Just to make clear, your previous version of handling the file paths worked fine. The only thing you changed afaik is that you added a loop to iterate the paths.. I don't see any problems there

**Comment by alexbelgium** [comment]
There is an issue : addon options are not passed. I'll check that now https://github.com/alexbelgium/hassio-addons/issues/1078#issuecomment-1818451220

Beware that if you have a CONFIG_LOCATION file with the value "/config/addons_config/paperless_ng/config.yaml" you should change it manually to "/config/config.yaml" (path according to HA new logic system) - this will be done automatically in the next version of the addon

**Comment by ciB89** [comment]
> Hi, I've pushed a new version everything should work now! And I've tested creating a new account on a mounted local drive.

it still does not handle whitespaces in path files correctly. Work around for me would of course the rename the share, but just wanted to let you know.

**Comment by alexbelgium** [comment]
ah - sorry already the success was that paperless was starting ;-) I forgot about your issue I'll check

**Comment by alexbelgium** [comment]
What is your addon options config :
```
localdisk='ciB paperless files'
PAPERLESS_MEDIA_ROOT='/mnt/ciB paperless files/media'
```
?

It shouldn't work as a blank is considered as a separator in the localdisk option... So it would likely try to mount ciB, then paperless, then files...

**Comment by ciB89** [comment]
The problem occurs with the SMB share, not the localdisk. `ciB paperless files` is a SMB share that I successfully mount via the add-on. So the correct path is `/mnt/ciB paperless files/media` for `PAPERLESS_MEDIA_ROOT` - this did work before as I mentioned. But for whatever reason, the path that it tries to access is `files/media` (so the string after the last whitespace).

**Comment by ciB89** [comment]
So this is my output of the logs:

```
PAPERLESS_PRE_CONSUME_SCRIPT='config/addons_config/paperless_ng/scripts/pre_consume.sh'
PAPERLESS_CONSUMPTION_DIR='/mnt/ciB paperless files/media/consumer'
PAPERLESS_MEDIA_ROOT='/mnt/ciB paperless files/media'
PAPERLESS_CONSUMER_ENABLE_BARCODES='true'
PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE='true'
PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT='true'
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/paperless-ng.sh if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
... no script found, exiting
/etc/cont-init.d/20-migration_config.sh: executing
/etc/cont-init.d/31-nginx.sh: executing
[16:07:27] WARNING: Ssl enabled, your site will be available at https://*******.duckdns.org. Don't forget to enable the https alternative port in the addon options.
/etc/cont-init.d/99-run.sh: executing
//etc/cont-init.d/99-run.sh: line 5: export: `files/media': not a valid identifier
//etc/cont-init.d/99-run.sh: line 6: export: `files/media/consumer': not a valid identifier
```

**Comment by alexbelgium** [comment]
I've pushed a test version that should solve it hopefully!

**Comment by ciB89** [comment]
> I've pushed a test version that should solve it hopefully!

Unfortunately not really. This is now my output config in the logs (see the double quotations sometimes):

```
PAPERLESS_DATA_DIR="/config/data"
PAPERLESS_MEDIA_ROOT=""/mnt/ciB paperless files/media""
PAPERLESS_CONSUMPTION_DIR=""/mnt/ciB paperless files/media/consumer""
PAPERLESS_EXPORT_DIR="/config/export"
USERMAP_UID="1000"
USERMAP_GID="1000"
PAPERLESS_TIME_ZONE="Europe/Berlin"
PAPERLESS_URL="https://***.duckdns.org"
PAPERLESS_OCR_LANGUAGES="deu"
PAPERLESS_OCR_MODE=""skip""
PAPERLESS_ADMIN_PASSWORD="admin"
PAPERLESS_ADMIN_USER="admin"
PAPERLESS_DBENGINE="mariadb"
PAPERLESS_DBHOST="core-mariadb"
PAPERLESS_DBPORT="3306"
PAPERLESS_DBNAME="paperless"
PAPERLESS_DBUSER="service"
```

**Comment by alexbelgium** [comment]
Hi, just pushed 2.0.0.1-6 which should be the stable one and allow correct start even if directory contains blanks. It will avoid this error with ""skip""

Now you see why I was hesitant to change the upstream container to this one and kept the 1.15 version for so long :-)

**Comment by ciB89** [comment]
Yeah, I can understand, and thanks for the effort. I try to help as best as I can.

Unfortunately, there is now another issue further downstream, here is the output:

```
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
PAPERLESS_CSRF_TRUSTED_ORIGINS=https://***.duckdns.org:448
PAPERLESS_OCR_PAGES=0
PAPERLESS_THREADS_PER_WORKER=2
PAPERLESS_TASK_WORKERS=1
PAPERLESS_OCR_CLEAN=clean-final
PAPERLESS_OCR_MODE=skip
PAPERLESS_WEBSERVER_WORKERS=1
PAPERLESS_CONSUMER_POLLING=600
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
PAPERLESS_PRE_CONSUME_SCRIPT=config/addons_config/paperless_ng/scripts/pre_consume.sh
PAPERLESS_CONSUMPTION_DIR='/mnt/ciB paperless files/media/consumer'
PAPERLESS_MEDIA_ROOT='/mnt/ciB paperless files/media'
PAPERLESS_CONSUMER_ENABLE_BARCODES=true
PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true
PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT=true
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/paperless-ng.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
---------------------------------------------------------
... no script found, exiting
/etc/cont-init.d/20-migration_config.sh: executing
/etc/cont-init.d/31-nginx.sh: executing
[19:17:27] WARNING: Ssl enabled, your site will be available at https://papierlos.duckdns.org. Don't forget to enable the https alternative port in the addon options.
/etc/cont-init.d/99-run.sh: executing
//etc/cont-init.d/99-run.sh: line 24: n^H55CK: command not found
[19:17:27] INFO: Defining variables
[19:17:28] INFO: Defining database
[19:17:28] INFO: Using MariaDB addon. Requirements : running MariaDB addon. Discovering values...
[19:17:29] WARNING: This addon is using the Maria DB addon
[19:17:29] WARNING: Please ensure this is included in your backups
[19:17:29] WARNING: Uninstalling the MariaDB addon will remove any data

PAPERLESS_DATA_DIR=/config/data
PAPERLESS_MEDIA_ROOT="/mnt/ciB paperless files/media"
PAPERLESS_CONSUMPTION_DIR="/mnt/ciB paperless files/media/consumer"
PAPERLESS_EXPORT_DIR=/config/export
...
[19:17:29] INFO: Starting redis
[19:17:29] INFO: Starting nginx
818:C 22 Nov 2023 19:17:29.109 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
818:C 22 Nov 2023 19:17:29.109 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=818, just started
818:C 22 Nov 2023 19:17:29.109 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
818:M 22 Nov 2023 19:17:29.110 * monotonic clock: POSIX clock_gettime
818:M 22 Nov 2023 19:17:29.111 * Running mode=standalone, port=6379.
818:M 22 Nov 2023 19:17:29.111 # Server initialized
818:M 22 Nov 2023 19:17:29.111 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
818:M 22 Nov 2023 19:17:29.112 * Ready to accept connections
 
Starting the upstream container
 
Paperless-ngx docker container starting...
Installing languages...
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Reading package lists...
Package tesseract-ocr-deu already installed!
Creating directory "/mnt/ciB paperless files/media"
mkdir: cannot create directory ‘"/mnt/ciB paperless files/media"’: No such file or directory
```
Error is `mkdir: cannot create directory ‘"/mnt/ciB paperless files/media"’: No such file or directory`, 
I also found this: `//etc/cont-init.d/99-run.sh: line 24: n^H55CK: command not found`

**Comment by alexbelgium** [comment]
> Yeah, I can understand, and thanks for the effort. I try to help as best as I can.
> 
> Unfortunately, there is now another issue further downstream, here is the output:
> 
> ```
> Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
> PAPERLESS_CSRF_TRUSTED_ORIGINS=https://***.duckdns.org:448
> PAPERLESS_OCR_PAGES=0
> PAPERLESS_THREADS_PER_WORKER=2
> PAPERLESS_TASK_WORKERS=1
> PAPERLESS_OCR_CLEAN=clean-final
> PAPERLESS_OCR_MODE=skip
> PAPERLESS_WEBSERVER_WORKERS=1
> PAPERLESS_CONSUMER_POLLING=600
> PAPERLESS_CONSUMER_RECURSIVE=true
> PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
> PAPERLESS_PRE_CONSUME_SCRIPT=config/addons_config/paperless_ng/scripts/pre_consume.sh
> PAPERLESS_CONSUMPTION_DIR='/mnt/ciB paperless files/media/consumer'
> PAPERLESS_MEDIA_ROOT='/mnt/ciB paperless files/media'
> PAPERLESS_CONSUMER_ENABLE_BARCODES=true
> PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true
> PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT=true
> /etc/cont-init.d/01-custom_script.sh: executing
> Execute /config/paperless-ng.sh if existing
> Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
> ---------------------------------------------------------
> ... no script found, exiting
> /etc/cont-init.d/20-migration_config.sh: executing
> /etc/cont-init.d/31-nginx.sh: executing
> [19:17:27] WARNING: Ssl enabled, your site will be available at https://***.duckdns.org. Don't forget to enable the https alternative port in the addon options.
> /etc/cont-init.d/99-run.sh: executing
> //etc/cont-init.d/99-run.sh: line 24: n^H55CK: command not found
> [19:17:27] INFO: Defining variables
> [19:17:28] INFO: Defining database
> [19:17:28] INFO: Using MariaDB addon. Requirements : running MariaDB addon. Discovering values...
> [19:17:29] WARNING: This addon is using the Maria DB addon
> [19:17:29] WARNING: Please ensure this is included in your backups
> [19:17:29] WARNING: Uninstalling the MariaDB addon will remove any data
> 
> PAPERLESS_DATA_DIR=/config/data
> PAPERLESS_MEDIA_ROOT="/mnt/ciB paperless files/media"
> PAPERLESS_CONSUMPTION_DIR="/mnt/ciB paperless files/media/consumer"
> PAPERLESS_EXPORT_DIR=/config/export
> ...
> [19:17:29] INFO: Starting redis
> [19:17:29] INFO: Starting nginx
> 818:C 22 Nov 2023 19:17:29.109 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 818:C 22 Nov 2023 19:17:29.109 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=818, just started
> 818:C 22 Nov 2023 19:17:29.109 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
> 818:M 22 Nov 2023 19:17:29.110 * monotonic clock: POSIX clock_gettime
> 818:M 22 Nov 2023 19:17:29.111 * Running mode=standalone, port=6379.
> 818:M 22 Nov 2023 19:17:29.111 # Server initialized
> 818:M 22 Nov 2023 19:17:29.111 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> 818:M 22 Nov 2023 19:17:29.112 * Ready to accept connections
>  
> Starting the upstream container
>  
> Paperless-ngx docker container starting...
> Installing languages...
> Hit:1 http://deb.debian.org/debian bookworm InRelease
> Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
> Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
> Reading package lists...
> Package tesseract-ocr-deu already installed!
> Creating directory "/mnt/ciB paperless files/media"
> mkdir: cannot create directory ‘"/mnt/ciB paperless files/media"’: No such file or directory
> ```
> 
> Error is `mkdir: cannot create directory ‘"/mnt/ciB paperless files/media"’: No such file or directory`, I also found this: `//etc/cont-init.d/99-run.sh: line 24: n^H55CK: command not found`

Thanks, pushed again a test version. At least on my system it was able to use a mounted folder with blanks as a data dur, but i'll ne interested to see how it goes for you

**Comment by ciB89** [comment]
It's up and running, so far now more issues. Thanks @alexbelgium

**Comment by alexbelgium** [comment]
Well, I really don't understand that one. Could you please do something for me :-)

With my filebrowser addon, go in /addon_configs/db21ed7f_paperless_ng, and create a file named paperless-ng.sh containing the text :

```
#/bin/bash
echo "cp /etc/cont-init.d/99-run.sh /config/" >> /etc/cont-init.d/99-run.sh
rm /addon_configs/db21ed7f_paperless_ng/paperless-ng.sh
```

When you will start the addon, it will copy your file to /config and you can check what is actually on line 24 :-)
Given several of my scripts are exporting variables (global-var.sh and config_yaml.sh) to the start of this file, this modifies what is actually on line 24 !

Thanks

**Comment by ciB89** [comment]
I got it, it's:

`export cifspassword=******n^H55CK&`

I guess there need to be quotationmarks around the password because of the special characters?

**Comment by alexbelgium** [comment]
ah...................... I see. Thanks very much for raising that. I'll look for the solution

**Comment by ciB89** [comment]
```
env-variables
... no config file, creating one from template. Please customize the file in /config/config.yaml/config.yaml before restarting.
mkdir: cannot create directory ‘/config/config.yaml’: File exists
cp: cannot stat '/config/config.yaml/config.yaml': Not a directory
sed: can't read /tempenv: No such file or directory
sed: can't read /tempenv: No such file or directory
sed: can't read /tempenv: No such file or directory
... no env variables found, exiting
```

**Comment by alexbelgium** [comment]
argh... the code had caused an issue on readarr so I modified it and as it was a global script it caused an issue here now. Ok, I'll look at it

**Comment by alexbelgium** [comment]
Ok, now version 6 should see everything working! Hopefully it's now good for the next couple years unless something changes upstream !

**Comment by ciB89** [comment]
> Ok, now version 6 should see everything working! Hopefully it's now good for the next couple years unless something changes upstream !

Is this 6test5? I because if yes, the issue persists.

**Comment by ciB89** [comment]
For whatever reason it completely reset my config.yaml with my env, but I was able to retrieve them again from a home assistant backup. Everything works fine now. Thank you for your work!

**Comment by alexbelgium** [comment]
Wow such a relief thanks for the feedback! Major updates such as this one are such a pain, it's actually much easier creating a new addon as there are less people impacted by the change. We'll glad everything works now the updates to future versions should be seamless unless they change something upstream (which is less likely)! BTW I have set for automatically weekly updates of my whole HA which is uploaded on a dedicated Google drive account, that saved my system quite a few times ;)

**Comment by HydrelioxGitHub** [comment]
As I use Paperless in production and I'm not the only user I couldn't help to do tests. But thank you both for your time and your work, I'll do the update next week. V2 add greats enhancements.

**Comment by rafael298** [comment]
I'm running Home Assistant on an raspberry pi 4 and if I try to update I get the message, that the architecture ist not supported by your update, only aarch64 and amd64

**Comment by alexbelgium** [comment]
Hi, it's because you have installed the armv7 image of HA on your rpi4 instead of thé arm64 version. More and more add-ons are dropping armv7 support including all the ones based on Linuxserver. For most of my other add-ons I've therefore pinned the armv7 version to the latest working, but I don't think paperless was proposing one. I strongly recommend that you backup your all instance and reinstall HA aarch64... It will take you time now but will allow you to have a more supported system in the future

**Comment by alexbelgium** [comment]
> As I use Paperless in production and I'm not the only user I couldn't help to do tests. But thank you both for your time and your work, I'll do the update next week. V2 add greats enhancements.

Thanks ! HA doesn't allow test versions it is everyone see the new version or no one, so it's not super easy... So I make weekly updates of my all HA just in case ;) and sometimes ha upgrades itself break things

**Comment by alexbelgium** [comment]
> I'm running Home Assistant on an raspberry pi 4 and if I try to update I get the message, that the architecture is not supported by your update, only aarch64 and amd64

Hi, actually I checked that the upstream image supports armv7. I've therefore re-added it

**Comment by rafael298** [comment]
Thank you very much. But I changed the system to arm64 today ;-)

**Comment by alexbelgium** [comment]
It's the longer term choice :-)

**Comment by rafael298** [comment]
any idea why the displayed version at the bottom is 1.17.4?

**Comment by alexbelgium** [comment]
> any idea why the displayed version at the bottom is 1.17.4?

Hehe, it was the latest tag and not the beta! Modified now

**Comment by rafael298** [comment]
while Starting the addon, I get this WARNING:
491:M 27 Nov 2023 09:46:02.698 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

Is it possible to change this?
