### ISSUE TITLE
🐛 [joplin] <Cant get access via mobile app>

### ISSUE THREAD

**Issue by kuduacz** [alexbelgium/hassio-addons#897]
### Description

Hi there.

i istalled joplin addon and configure app base url to my cloudflare domain like https"//joplin.xxx.xx where xxx.xx is my domain.
From computer browser i cant get access to site, but not via mobile app with "Network request failed".

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
2023-07-13 14:27:27: [error] App: 400: GET /api/sessions: ::xxxx:xxxx.xx.xx.x: Not allowed: GET api/sessions
2023-07-13 14:27:27: App: GET /api/sessions (400) (2ms)
```

**Comment by alexbelgium** [comment]
Hi, have you search on the Joplin forums? I search with your error terms and found descriptions of the same issue as you : https://discourse.joplinapp.org/t/joplin-server-not-allowed-get-api-sessions/19747/13

**Comment by kuduacz** [comment]
Unfortunetaly its not same issue. Its not firewall problem. I think its with incorrect addon configuration and cloudflare.

**Comment by kuduacz** [comment]
Do t know why but my mobile devices do t like my free domain xxx.ml but everything work well with TK domain. If anyone know why please let me know.
