### ISSUE TITLE
[Papermerge] Could not create server TCP listening socket *:6379: unable to bind socket, errno: 13

### ISSUE THREAD

**Issue by thundergreen** [alexbelgium/hassio-addons#9]
By installing and starting this Addon i get this serror. Might be the port is already used. Any way to change this port?

**Comment by alexbelgium** [comment]
Thanks! That's strange, this port shouldn't be exposed. It is used internally by the addon so there shouldn't be a conflict... I'm sorry I'm very busy for the moment with work I'll try to find some time to check what could be the issue.

On which system are you? Home Assistant OS? And by any chance would you have a copy of the log just before the issue?

Thanks!

**Comment by alexbelgium** [comment]
Could you try with uid 0 gid 0 in addon options? It is an error code for a lack of permissions. Probably there is an issue with permissions that I need to fix

**Comment by thundergreen** [comment]
@alexbelgium Thanks  but changng uid 0 still https://pastebin.ddns.me/modayepara.cs

**Comment by alexbelgium** [comment]
I haven't had time to look into it yet... The addon is still automatically updated with upstream updates but it is still broken. I'll try to look into it when possible

**Comment by thundergreen** [comment]
Thanks for your feedback

Alexandre <notifications@github.com> schrieb am Sa., 6. März 2021, 09:41:

**Comment by alexbelgium** [comment]
Hi, I just rewrote the code to allow folders modifications. Could you please try the latest version dev6 ? Thanks!

**Comment by alexbelgium** [comment]
Hi, are you still open to test this version? Or I'll simply close the issue. Thanks!
