### ISSUE TITLE
🐛 [bazarr] Cannot update to 1.2.3 - manifest unknown

### ISSUE THREAD

**Issue by ping-localhost** [alexbelgium/hassio-addons#900]
### Description

See title. I saw that there was an update, I tried to update, I was unable to update. Did you tag and then remove the tag or? 

Relevant screenshot:
![image](https://github.com/alexbelgium/hassio-addons/assets/37925797/2d6f3a2f-bcb7-4712-9f6b-9e3e494b79db)

### Reproduction steps

```bash
1. Go to Settings.
2. See an update for Bazarr.
3. Click on Update.
4. Error is shown in Supervisor logs.
```

### Addon Logs

```bash
Can't install ghcr.io/alexbelgium/bazarr-amd64:1.2.3: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=1.2.3&fromImage=ghcr.io%2Falexbelgium%2Fbazarr-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
```

**Comment by lagge78** [comment]
Same issue for me. Uninstalled even and now I see the update still. And when I try to reinstall I get the same issue as before: Manifest unknown

**Comment by ping-localhost** [comment]
Looking at this commit https://github.com/alexbelgium/hassio-addons/commit/21ef3ae6e0682d159338a8e40319fae7eef02328 by @alexbelgium, it seems that the add-on was indeed supposed to be updated, but the images were never pushed due to the Actions failing: https://github.com/alexbelgium/hassio-addons/actions/runs/5559275166/jobs/10155206998

**Comment by alexbelgium** [comment]
Hi, I was off for a few days. Indeed lsio has removed support for all 32 bits build but that prevents also other architectures to build. I'll push a fix a bit later

**Comment by alexbelgium** [comment]
It's building now!

**Comment by ping-localhost** [comment]
> It's building now!

Has it been pushed yet? Just tried to update again, but it doesn't seem to work yet.

**Comment by alexbelgium** [comment]
Doesn't it? The build is completed so version 1.2.3-2 should install. If you don't see it yet you should refresh your repo

**Comment by ping-localhost** [comment]
Worked now. My bad 😅
