### ISSUE TITLE
🐛 [Nextcloud] Addon option `data_directory:` is not working

### ISSUE THREAD

**Issue by Danit2** [alexbelgium/hassio-addons#901]
### Description

When you add the option `data_directory:` to the addon option it does not change the data directory at startup.

The data directory are always the path that you have add at the installation. 

### Reproduction steps

```bash
I have installed Nextcloud with the standart data folder `/share/nextcoud`
After i have add a networkdisk in the addon option and add `data_directory:` with the path to the option.
At startup you see in the logs that the network disk is mountet. But it will always take the old data_directory path.  

Addon Options

Full_Text_Search: false
OCR: false
OCRLANG: deu
PGID: 1000
PUID: 1000
additional_apps: inotify-tools
certfile: fullchain.pem
elasticsearch_server: <ip:port>
keyfile: privkey.pem
trusted_domains: xxxx
use_own_certs: false
data_directory: /mnt/home
cifspassword: xxxxx
cifsusername: xxxxx
networkdisks: //192.168.1.126/home
```
```


### Addon Logs

```bash
[09:48:37] INFO: ... //192.168.1.126/home successfully mounted to /mnt/home with options ,uid=1000,gid=1000,iocharset=utf8
```

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, indeed it is by design : once installed, the data locations are yard coded in the database. Nextcloud does not support changing the data path as I understand it. What this option does is ensure adequate permissions with the data folder uses for installation, and prefill (hopefully) the default data folder during installation template

**Comment by Danit2** [comment]
Hello.
Thank you for the quick reply.
Ahh I understand. This is only for the first setup.
Maybe a small note by the option would be good.
Theoretically you can change the data_directory if you have access to the config.php

**Comment by alexbelgium** [comment]
Honestly I've done it myself and it was a nightmare :) I had to manually edit my sql tables to correct all entries and reminded files. Well it IS possible by using a tool like portainer just not recommended :)

Thanks i'll add a note to the readme

**Comment by Danit2** [comment]
Ok thanks for the note in the readme.

Yes I have now deleted everything again and started from the beginning.

Thanks for your support.
