### ISSUE TITLE
🐛 [gitea] updating versions, but it seems not to be working

### ISSUE THREAD

**Issue by baldarn** [alexbelgium/hassio-addons#904]
### Description

I updated the version of gitea to 1.20.0, but I'm still having an old one.

### Reproduction steps

```bash
1. Update gitea
2. go on you gitea webapp
3. Scroll down to the footer
4. See version
```

### Addon Logs

```bash
nothing
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by alexbelgium** [comment]
Have you refreshed the repo? The build went fine

**Comment by baldarn** [comment]
I updated the addon, but the version of gitea is stale :/

dunno where to check things

**Comment by alexbelgium** [comment]
Ah, the build.json is stuck in 1.18, we could put latest it would be easier. I'll do that now
