### ISSUE TITLE
Failed loading environment

### ISSUE THREAD

**Issue by geigervibe** [alexbelgium/hassio-addons#91]
I don't know if this is normal, but as soon I click on 'primary' I get an 'failed loading environment' error. The docu tells me to unhide the containers, which I did not yet. I only want to take a look at the current installation, I don't want to change anything nor want I install another containers. Beside that, what happens, when I unhide these 9 base containers and why do I not see any add-ons in this hidden list?

![failed_loading_environment](https://user-images.githubusercontent.com/73827253/142776094-b3882da8-c018-499b-82d0-97b0af8f293b.png)

**Comment by alexbelgium** [comment]
Hi, addons are already unhided, you access them by clicking on Primary, the looking at the containers. Perhaps you could try refreshing your page ou the env by clicking on the refresh button on top, or trying with direct access through url instead of using ingress

**Comment by geigervibe** [comment]
Thanks for the hint about ingress. Now I can see the add-ons when using port 9000. Do you know if ingress is problematic in general, because some of installed addons are not loaded when I use the Chrome browser, mostly I get a blank page or the css is not loaded. With Firefox I have less problems. I'm not sure, if only I have these problems or is this a hassio/ingress problem in general? this problem came with an hassio-update around early summer but I could not find any reports about that in the net and could not fix this either...

**Comment by alexbelgium** [comment]
Well actually I've encountered a few time this issue also but usually a simple page refresh did the trick... It also seems to depend on the device used (for ex no problem on my computer, but it often doesn't work on my android device). I'll investigate a bit, but close the issue then if it works!

**Comment by geigervibe** [comment]
Sorry for re-open this issue, but I have still have a question. What happens when I unhide the other hassio containers? Is this step destructive and can't be undone? Do I lose the supported state of supervisor for ever? As I told, I just want to investigate all the containers not just the addons, but not change anything (while this unhide could be a one-way change?).

**Comment by alexbelgium** [comment]
Hi, no problem, you can hide or unhide them as you want. The initial setup hides everything except addons, but you can access as you want. Unhiding is purely internal in portainer, so as long as you access the containers but don't mess up in them the status of your supervisor will stay the same. If you
