### ISSUE TITLE
erreur "Bashio does not exist, executing script"

### ISSUE THREAD

**Issue by schumissimo63** [alexbelgium/hassio-addons#92]
Bonjour lorsque que je lance l'addon j'ai systématiquement ce message d'erreur "Bashio does not exist, executing script" s'en suit l'installation de diffèrent composant, ensuite l'addon se lance correctement. Comment puis je éviter cela? Cordialement.

**Comment by alexbelgium** [comment]
Bonjour, comment éviter que l'addon sea've correctement ?

**Comment by alexbelgium** [comment]
C'est pour quel addon, enedys ? J'ai poussé une nouvelle version qui cache le texte

**Comment by schumissimo63** [comment]
Pardon je n'ai pas précisé l'addon, c'est bien enedis, j'ai fait la mise à jour et j'ai ce message maintenant, mais il fonctionne correctement, merci pour ta réactivité.

Starting...
All addon options were exported as variables
/entrypoint.sh: line 14: jq: command not found
Timezone set from Etc/UTC to Europe/Paris
scripts/00-aaa_dockerfile_backup.sh: executing
Bashio does not exist, executing script
debconf: delaying package configuration, since apt-utils is not installed
Bashio installed
scripts/00-banner.sh: executing
-----------------------------------------------------------

**Comment by alexbelgium** [comment]
Merci je vais encore regarder un peu

**Comment by alexbelgium** [comment]
J'ai poussé une nouvelle version, a priori ça aidera :) un grand merci d'avoir rapporté ça en tout cas car je pense que ça touchais bcp de monde ! C'est invisible sur mes système car je suis en HAos et pas en supervised.

**Comment by schumissimo63** [comment]
Un grand merci à toi pour cet addon, je te dis ce qu'il en est quand je rebooterai.

**Comment by alexbelgium** [comment]
Est-ce que tout va bien maintenant? plus de message d'erreurs?

**Comment by alexbelgium** [comment]
Bon je ne vois pas trop comment changer ça, on va garder ainsi sauf si vous pensez qu'il serait préférable de changez cela

Bonne journée
