### ISSUE TITLE
✨ [REQUEST] Nextcloud

### ISSUE THREAD

**Issue by zuldero** [alexbelgium/hassio-addons#925]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Nextcloud

### Is your feature request related to a problem? Please describe

Kinda, the addon runs just fine, but I am not able to access the Cloud, like HomeAssistant and other Addons, from outside my network. And if I press the button "Open user UI" (in German: Benutzeroberfläche öffnen) in the addon overview where I can also restart, stop, and reinstall it, it opens my HomeAssistant DuckDNS domain with the Nextcloud port, which is not usable. I need to access the cloud by the IP of the server with the port of the cloud.

### Describe the solution you'd like

I would love if it would show up in the sidebar in HomeAssistant, like AdGuard, GoogleDrive Backups, and things like this. I guess if it would be accessible from there, I would also not need to get a domain and certificate just for the cloud, because I already have one for HomeAssistant.

**Comment by alexbelgium** [comment]
Hi, this is not possible due to the way the app is built. Your only solution is to open the port in your router, or use the mobile apps

**Comment by alexbelgium** [comment]
Hi, well I'm using the nextcloud app on iPhone to access my data from the phone. However indeed I spoke too quickly you also need to open the port in the router to access your files from remote...

Last option i see could be to use a vpn to access your local network remotely, like the fritzbox router offers. However it is a slow and complex solution

**Comment by zuldero** [comment]
ok thx you i just thoght there would be a way that i dont know, case im pretty new in this whole networking, home lab szene xD. i guess i stay with the synology vpn than. i just thoght there would be a easy way to change the "open user UI" button to the correct ip / show the addon in the side bar. but thx you for the work on the addon, and these quick reply's

**Comment by alexbelgium** [comment]
Mmh in theory it opens with whatever op you are using to access HA! So if you open HA with your external up then the open ui should open nextcloud, as long as you have opened it's port in the router? Wouldn't it?

**Comment by zuldero** [comment]
i dont want to open the port for it. but atm i acces HA with my duckdns domain. since i have done that i can not acces it with its local ip, just with the duckdns one. i remember that the tutorial mentiont something about the router that they notice, that the domain is actually in your local network and dont evan send it out of your local network. anyways if i press this UI button, i just get the duckdns domain with the nextcloud port. witch is not working. for the nextcloud, i need to acces it with the local IP witch is not working for the HA. i guess it has something to do with the routing (i cant anymore acces HA with its local IP). It is absolutly possible, that it would work with no DNS like mine, but as i just said. i do not fully understand all these networking stuff.

**Comment by alexbelgium** [comment]
Looks complex indeed... I'm lucky to have a server name free with my fritzbox router and everything works out of the box so I don't have to really think about it ;) I would have thought it would work as a redirect to the external ip so all ports opened in the router should be transfered to the duckdns but I've never used it myself so this is perhaps not a correct view... Good luck!

**Comment by zuldero** [comment]
thx for your thoghts. it will definitly be somthing about the routing. the keyword redirects actually helpt me thx man. i figured it out what the actual ip and port is so i am fine. thx

**Comment by alexbelgium** [comment]
Happy it works then! Have fun
