### ISSUE TITLE
❓ [Nextcloud] Can't start Nextcloud ... more than one major version behind

### ISSUE THREAD

**Issue by rawpie2** [alexbelgium/hassio-addons#928]
**Nextcloud**

**Addon**

**Problem after updating**
I am having an issue after updating nextcloud:

I keep getting this error and have no idea how to incremental downgrade to fix the issue

`Can't start Nextcloud because the version of the data (24.0.5.1) is more than one major version behind the docker image version (27.0.1.2) and upgrading more than one major version is not supported. Please run an image tagged for the major version 25 first.`

Is there anyone here that can assist me with this? Nextcloud broke upon updating and I dont wanna lost any of my data from nextcloud

**Comment by rawpie2** [comment]
> Hi, only solution is to restore your backup and update manually through the admin panel. I had put a warning on the changelog but for auto updating systems it might be missed. It's not due to the add-on but due to the upstream image so there is no workaround for this sorry

Is there any help you can give please? I'm super lost and dont quite know my way around docker stuff to well.

**Comment by alexbelgium** [comment]
Hi, you need to restore the add-on's partial backup that should be made automatically unless you refused it while updating. Example guide : https://www.derekseaman.com/2023/04/home-assistant-pt-3-restoring-your-configuration.html#:~:text=If%20any%20of%20your%20add,Click%20on%20your%20backup.

After restoring the backup, you'll be able to start the add-on. You then either need to start it with the "disable_updates" option turned off to make it self update, or if it doesn't work you'll need to update it manually from the admin console : https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#:~:text=Using%20the%20web%20based%20updater&text=Go%20to%20the%20admin%20settings,enabled%20in%20the%20apps%20management.

Let me know how that goes!

**Comment by rawpie2** [comment]
I was able to get version 25 running but trying to restore any further version results in the system going into a "freeze state" and not restoring the backup. I also don't know how to incrementally upgrade to the newest version because there are certain versions i need to have upgraded to first before the next. Is there a way to upgrade version by version?

**Comment by alexbelgium** [comment]
Have you disabled my automatic update feature? It should update sequentially though all major versions at add-on start. The updater  also should do it automatically : update to latest minor version of 24, then to 25, 26, and 27 sequentially

**Comment by rawpie2** [comment]
> Have you disabled my automatic update feature? It should update sequentially though all major versions at add-on start. The updater  also should do it automatically : update to latest minor version of 24, then to 25, 26, and 27 sequentially 

I dont know how it might of gotten disabled or how to re enable it

This might be the issue
The web ui says I'm on version '24.0.5' with an update for '24.0.12' But whenever I go to click the open updater button it says

"Step 3 is currently in process. Please reload this page later.'

I dont know why it says this, it might of gotten stuck somehow

On home assistsnt I'm currently on version '25.0.4' With update for '27.0.1-7' But can't update further because it breaks itself

**Comment by rawpie2** [comment]
It also has warnings but I dont know how to go about fixing these
![Screenshot_20230809-075155_1.png](https://github.com/alexbelgium/hassio-addons/assets/8276063/05c6a44c-f344-403a-9cc2-03a83a738e71)

**Comment by fraintt** [comment]
I have the same issue.. I tried multiple times to restore a partial backup, but it also does not start with an 404 Not Found Error and permission denied in the log. 

I wanted to troubleshoot it today, restarted the addon and now it does not start anymore at all.. 

I´m going to restore a backup again and try the auto_update:disable option.

**Comment by alexbelgium** [comment]
Hi, all these errors messages don't really matter. The key element is to restore the backup of a previously working version of the addon (normally anything prior to v27).

How to update from a working instacen : 
- make sure the `auto_update` is enabled and restart the addon. In theory, it should auto update to latest minor version of 24, then to 25, 26, and 27 sequentially.
- If not, you can go to the admin console and use the online updater here : https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#:~:text=Using%20the%20web%20based%20updater&text=Go%20to%20the%20admin%20settings,enabled%20in%20the%20apps%20management.
- Last option is to connect using portainer and run the `php updater/updater.phar` command manually

If it stuck in an update (such as error with step 3), you can go in your data folder and delete the hidden file `.step` then restart the addon. It will should reset the updater. The addon also tries to solve several issues when starting, so looking at the log should help to know what is exactly the issue

**Comment by rawpie2** [comment]
> Hi, all these errors messages don't really matter. The key element is to restore the backup of a previously working version of the addon (normally anything prior to v27).
> 
> How to update from a working instacen : 
> - make sure the `auto_update` is enabled and restart the addon. In theory, it should auto update to latest minor version of 24, then to 25, 26, and 27 sequentially.
> - If not, you can go to the admin console and use the online updater here : https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#:~:text=Using%20the%20web%20based%20updater&text=Go%20to%20the%20admin%20settings,enabled%20in%20the%20apps%20management.
> - Last option is to connect using portainer and run the `php updater/updater.phar` command manually
> 
> If it stuck in an update (such as error with step 3), you can go in your data folder and delete the hidden file `.step` then restart the addon. It will should reset the updater. The addon also tries to solve several issues when starting, so looking at the log should help to know what is exactly the issue

Do you believe you could give me instructions of where to go to delete this said .step file and enable "auto_update" because I'm lost as of where to go because of the amount of ui to navagate

**Comment by alexbelgium** [comment]
Hi,

For the auto_update part, you need to go in the addons page : https://my.home-assistant.io/redirect/supervisor_addon/?addon=db21ed7f_nextcloud_ocr then click on the "configuration" tab. Here you make sure that the "disable_updates" feature is off. If you don't see it in your addon options, then it means it is already off.
![image](https://github.com/alexbelgium/hassio-addons/assets/44178713/3e9ed3f9-1a0c-4aa6-a735-0c0575c85c24)

For the .step file removal, you need to go in your nextcloud data folder. Normally you know where your data is stored, otherwise it should be said at the beginning of the log when starting your addon. In this folder, you should find a "nextcloud-data" folder, which contains a folder named "updater-randomstring". Randomstring is an actual random string and not a text. In this folder you'll find a file named ".step" that you need to delete.

Could you please post the full log of what you have when you start the addon ? It could help to troubleshoot, thanks.

Hope this is helpful!

**Comment by rawpie2** [comment]
> Hi,
> 
> For the auto_update part, you need to go in the addons page : https://my.home-assistant.io/redirect/supervisor_addon/?addon=db21ed7f_nextcloud_ocr then click on the "configuration" tab. Here you make sure that the "disable_updates" feature is off. If you don't see it in your addon options, then it means it is already off. ![image](https://user-images.githubusercontent.com/44178713/260122055-3e9ed3f9-1a0c-4aa6-a735-0c0575c85c24.png)
> 
> For the .step file removal, you need to go in your nextcloud data folder. Normally you know where your data is stored, otherwise it should be said at the beginning of the log when starting your addon. In this folder, you should find a "nextcloud-data" folder, which contains a folder named "updater-randomstring". Randomstring is an actual random string and not a text. In this folder you'll find a file named ".step" that you need to delete.
> 
> Could you please post the full log of what you have when you start the addon ? It could help to troubleshoot, thanks.
> 
> Hope this is helpful!

```
 Nextcloud for Home Assistant
-----------------------------------------------------------
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
 Add-on version: 25.0.4
 There is an update available for this add-on!
 Latest add-on version: 27.0.1-7
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 10.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.8.2
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[06:18:21] INFO: Execute /config/addons_autoscripts/nextcloud-ocr.sh if existing
[06:18:21] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/01-folders.sh
[06:18:21] INFO: Checking permissions
cont-init: info: /etc/cont-init.d/01-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/02-mariadb_discovery.sh
[06:18:25] WARNING: MariaDB addon was found! It can't be configured automatically due to the way Nextcloud works, but you can configure it manually when running the web UI for the first time using those values :
Database user : [redact]
Database password : [redact]
Database name : [redact]
Host-name : [redact]
cont-init: info: /etc/cont-init.d/02-mariadb_discovery.sh exited 0
cont-init: info: running /etc/cont-init.d/30-ssl.sh
[06:18:27] INFO: Using referenced ssl certificates...
... checking if referenced files exist
cont-init: info: /etc/cont-init.d/30-ssl.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-add_packages.sh
[06:18:28] INFO: Installing additional apps :
... inotify-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
(1/2) Installing inotify-tools-libs (3.22.6.0-r0)
(2/2) Installing inotify-tools (3.22.6.0-r0)
Executing busybox-1.35.0-r29.trigger
OK: 387 MiB in 252 packages
cont-init: info: /etc/cont-init.d/99-add_packages.sh exited 0
cont-init: info: running /etc/cont-init.d/99-elasticsearch.sh
Full_Text_Search option not set
cont-init: info: /etc/cont-init.d/99-elasticsearch.sh exited 0
cont-init: info: running /etc/cont-init.d/99-ocr.sh
cont-init: info: /etc/cont-init.d/99-ocr.sh exited 0
cont-init: info: running /etc/cont-init.d/99-trusted_domains.sh
[06:18:36] INFO: Currently set trusted domains :
nextcloud.[redact]
nextcloud.[redact]
[06:18:38] INFO: Trusted domains set in the configuration. Refreshing domains.
[06:18:38] INFO: ... removing previously added trusted domain (except for first one created)
System config value trusted_domains => 2 deleted
System config value trusted_domains => 3 deleted
System config value trusted_domains => 4 deleted
System config value trusted_domains => 5 deleted
[06:18:46] INFO: ... alignement with trusted domains list : nextcloud.[redact]
[06:18:46] INFO: ... adding nextcloud.[redact]
System config value trusted_domains => 6 set to string nextcloud.[redact]
[06:18:48] INFO: Remaining configurated trusted domains :
[06:18:49] INFO: nextcloud.[redact]
nextcloud.[redact]
cont-init: info: /etc/cont-init.d/99-trusted_domains.sh exited 0
using keys found in /data/config/keys
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/data/config/nginx/site-confs/default
[custom-init] No custom files found, skipping...
services-up: info: copying legacy longrun cron (no readiness notification)
[ls.io-init] done.
```

**Comment by rawpie2** [comment]
Also I deleted the .step and tried again and got this weird error and its back to saying step 3 in progress again
![error](https://github.com/alexbelgium/hassio-addons/assets/8276063/283c64b4-6b8f-419f-bbd1-c540f05ede5a)

**Comment by alexbelgium** [comment]
I understand, you have a super old version of the addon that does not include my auto updater ;-)
Then let's make the code by ourselves.

You need to create a file in `/config/addons_autoscripts/` named `nextcloud-ocr.sh`

In this file, you could put the following code: 
```
#!/bin/bash
echo "Starting to work"
echo "*****************"

echo "... Clean potential errors"
sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/occ maintenance:repair" || true
sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/occ maintenance:repair-share-owner" || true
sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/occ maintenance:mode --off" || true

echo "... Launch initial update"
sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/updater/updater.phar --no-interaction"
sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/occ upgrade"

echo "... Install additional versions"
while [[ $(occ update:check 2>&1) == *"update available"* ]]; do
bashio::log.yellow "-----------------------------------------------------------------------"
bashio::log.yellow "  new version available, updating. Please do not turn off your addon!  "
bashio::log.yellow "-----------------------------------------------------------------------"
        sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/updater/updater.phar --no-interaction"
        sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/occ upgrade"
    done
    
    echo "Checking for apps updates"
echo "*****************************"
sudo -u abc -s /bin/bash -c "php /data/config/www/nextcloud/occ app:update --all"
```

**Comment by alexbelgium** [comment]
I've updated the code, please the one from this thread and not the one you could receive from the email notification ;-)

**Comment by rawpie2** [comment]
> 

I upgraded everything and updated the addon and now i am getting this error:
`Can't start Nextcloud because the version of the data (27.0.2.1) is higher than the docker image version (27.0.1.2) and downgrading is not supported. Are you sure you have pulled the newest image version?`

This looks bad

**Comment by alexbelgium** [comment]
No it's perfect. It means updates succeeded and your data is safe. It also means you now have the same issue as my other nextcloud issue : lsio has not yet issued the add-on version corresponding to latest... As soon as they do i'll update the main add-on and your ordeal will be finished hopefully for good! Big structure changes in add-on logic like that in the upstream images I am based on are very rare

**Comment by rawpie2** [comment]
Okay cool. thanks alot
How long can i expect nextcloud to not work for, and can I turn auto-update in homeassistant on without fear of things breaking?
Thanks again

**Comment by alexbelgium** [comment]
Hi, at least on this add-on :) but I do recommend the add-on I described above that makes each week full backup of HA and uploads it on Google drive. It saves major headaches (such as SD card dying or weird issues that can be solved)

I'll probably push an update this afternoon forcing manually the update to 27.0.2 as I don't think the lsio one will be updated for at least some days as they are waiting for the 27.0.2 to be officially released (it is a rc)

**Comment by alexbelgium** [comment]
I'll close this as the last element is a new issue already tracked here : https://github.com/alexbelgium/hassio-addons/issues/938

It is pinned if people have the same issue with the solution being just above : https://github.com/alexbelgium/hassio-addons/issues/928#issuecomment-1675846194
