### ISSUE TITLE
❓ [All ARR ] Issue connecting to NAS

### ISSUE THREAD

**Issue by Teberon** [alexbelgium/hassio-addons#929]
I have something I have no idea what could be the issue. When starting basically all arr addons except I get the message that they couldn't ping the NAS, but Sonarr doesn't have that issue.

Sonarr
`[migrations] started
[migrations] no migrations found
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Sonarr
 Can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them
-----------------------------------------------------------
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1001
User GID:    1001
───────────────────────────────────────
 Add-on version: 3.0.10.1567-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.7.3
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[20:45:48] INFO: Execute /config/addons_autoscripts/sonarr-nas.sh if existing
[20:45:48] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/20-folders.sh
cont-init: info: /etc/cont-init.d/20-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/32-nginx_ingress.sh
cont-init: info: /etc/cont-init.d/32-nginx_ingress.sh exited 0
cont-init: info: running /etc/cont-init.d/90-disable_ingress.sh
cont-init: info: /etc/cont-init.d/90-disable_ingress.sh exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
Mounting smb share(s)...
Using PUID 1001 and PGID 1001
[20:45:49] INFO: ... //192.168.10.10/arr successfully mounted to /mnt/arr with options 
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.10.1567 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/sonarr] 
[Info] Router: Application mode: Interactive 
[Info] MigrationLogger: *** Checking database for required migrations data source=/config/addons_config/sonarr/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationLogger: *** Checking database for required migrations data source=/config/addons_config/sonarr/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] OwinHostController: Listening on the following URLs: 
[Info] OwinHostController:   http://*:8989/sonarr/ 
[Info] OwinHostController:   http://*:8989/ 
[Info] SonarrBootstrapper: Starting Web Server `

Radarr
`      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1001
User GID:    1001
───────────────────────────────────────
 Add-on version: 4.6.4.7568
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.7.3
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1001
User GID : 1001
-----------------------------------------------------------
Mounting smb share(s)...
Using PUID 1001 and PGID 1001
[20:47:02] FATAL: Your server 192.168.10.10 from //192.168.10.10/arr doesn't ping, is it correct?
[20:47:02] INFO: Execute /config/addons_autoscripts/radarr-nas.sh if existing
[20:47:02] INFO: ... no script found
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.6.4.7568 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/radarr] 
[Info] MigrationController: *** Migrating data source=/config/addons_config/radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/addons_config/radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:7878 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/radarr/bin 
[Error] DownloadClientSortingCheck: Unknown error occurred in DownloadClientSortingCheck HealthCheck 
[v4.6.4.7568] System.Net.Http.HttpRequestException: Connection refused (xxx.xxx.xxx:8083)
 ---> System.Net.Sockets.SocketException (111): Connection refused`

One thing I have noticed is that the ping is before the nas.sh script for Radarr but it runs afterward in Sonarr. Also the connection issue worries me as both have the same network... Any help would be much appreciated

**Comment by Teberon** [comment]
any assistance?

**Comment by alexbelgium** [comment]
Hi, thanks. Actually perhaps it was just because the Sonarr addon used an old version of the mount script… is it still working with the latest versions ? I will disable the ping check in next Radarr version as a test

**Comment by Teberon** [comment]
Hey @alexbelgium, thanks for looking into it. I just updated Radarr and it looks like this now:

`Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Radarr
 A fork of Sonarr to work with movies like Couchpotato
-----------------------------------------------------------
 Add-on version: 4.7.5.7809-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.9.3
 Home Assistant Supervisor: 2023.09.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1001
User GID : 1001
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
PGID='1001'
PUID='1001'
TZ='Europe/Warsaw'
cifspassword='password'
cifsusername='username'
ingress_disabled='false'
networkdisks='//192.168.10.10/arr'
/etc/cont-init.d/00-local_mounts.sh: executing
---------------------------------------------------
[19:48:03] INFO: Available Disks :
NAME        LABEL   SIZE FSTYPE   TYPE RO
├─sda2               24M squashfs part  0
├─sda3              256M squashfs part  0
├─sda4               24M squashfs part  0
---------------------------------------------------
/etc/cont-init.d/00-smb_mounts.sh: executing
Mounting smb share(s)...
Using PUID 1001 and PGID 1001
[19:48:14] WARNING: Your server 192.168.10.10 from //192.168.10.10/arr doesn't ping, is it correct?
[19:48:14] INFO: ... //192.168.10.10/arr successfully mounted to /mnt/arr with options ,uid=1001,gid=1001,iocharset=utf8
/etc/cont-init.d/01-custom_script.sh: executing
[19:48:14] INFO: Execute /config/addons_autoscripts/radarr-nas.sh if existing
[19:48:14] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/90-disable_ingress.sh: executing`

That seems to be working for Radarr, but Readarr does still show this issue

**Comment by alexbelgium** [comment]
Yes, I just updated the code for radarr. Then it means I need to push new versions of all add-ons. I'll think if there is a more efficient manner

**Comment by Teberon** [comment]
@alexbelgium could you please look into the SMB at qbittorrent as it doesn't seem to connect. Looking into the volume, I see mnt and the folders, but on my NAS, the listed files aren't visible, so they are just locally available, causing issues with Radarr and Sonarr as they can't move the files over.
