### ISSUE TITLE
❓ [Immich] Machine Learning features not work

### ISSUE THREAD

**Issue by inowakowski** [alexbelgium/hassio-addons#933]
I have a question about facial recognition and machine learning functions in general.

I installed the addon on HAOS and these functions are not working for me. The question is it an issue with my server or is this feature not working within the HA addon?

In the addon logs I get the message:
Traceback (most recent call last):
  File "/app/immich/machine-learning/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package

**Comment by pen25** [comment]
im getting the same error on a fresh install. i have disabled machine learning and getting this still.

**Comment by txitxo0** [comment]
For me is the same. And even worse, the search box can't work at all
`Search is disabled (400 - Bad Request)`
In logs I got the same others shared:
`File "/app/immich/machine-learning/main.py", line 11, in`
And I don't know if this is happening from my hardware (Raspi 4 4gb and HAOS) or from the addon

**Comment by alexbelgium** [comment]
Hi, the upstream image has removed support to embedded postgres. I've kept a legacy image but it was expected to fail at some point. I can switch to the new upstream image but then you'll have to install my postgres addon and recreate your databases there. Given the burden I had not done it for the moment.

Here is some additional informations : https://github.com/alexbelgium/hassio-addons/issues/892

**Comment by inowakowski** [comment]
@

**Comment by alexbelgium** [comment]
Hi, is your issue solved? Normally to really solve it I need to modify the upstream container I think ?

**Comment by txitxo0** [comment]
> Hi, is your issue solved? Normally to really solve it I need to modify the upstream container I think ?

At least in my side the problem is not solved yet

**Comment by alexbelgium** [comment]
Does it bother you to recreate your database? I don't think we can keep it if we move to the new system with external postgresql

**Comment by txitxo0** [comment]
> Does it bother you to recreate your database? I don't think we can keep it if we move to the new system with external postgresql

Hi! Yes I can do whatever test the development need. Happy to help!

I was trying to directly remove files from my HAOS machine and uninstall addons and then I tried using your external posgres addon enabling and disabling the DISABLE_MACHINE_LEARNING in immich, both gave me the same error in the search box, and the logs:
`Traceback (most recent call last):
  File "/app/immich/machine-learning/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/app/immich/machine-learning/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package`

Using RPI 4 4gb, HAOS under the version:
```
Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.1 - latest
immich: 1.73.0
postgres: 15.3-test6
```

**Comment by hydazz** [comment]
> Hi, the upstream image has removed support to embedded postgres. I've kept a legacy image but it was expected to fail at some point. I can switch to the new upstream image but then you'll have to install my postgres addon and recreate your databases there. Given the burden I had not done it for the moment.
> 
> Here is some additional informations : #892
> 
> Btw I can't guarantee that these functions would work anyway as there might be architectures or image constraints ;-)

The time has come, v1.75.0 of Immich no longer wants to build on jammy, so the `:jammy` branch has been deprecated :(. again, out of our control, as Immich requires the latest debian packages to work.
And as we have moved to a ubuntu lunar postgresql 14 is no longer included/supported (upstream issue...)
you can install postgresql 14 from the postgres repository for amd64, but not aarch64 (I believe), but now only postgres 15+ is installable from the default ubuntu repos

**Comment by alexbelgium** [comment]
Thanks! Then I'll move to the latest tag, and people will have to install a postgres add-on (such as mine) to recreate their database. Or did you manage to transfer yours from within the current add-on to the external one?

**Comment by hydazz** [comment]
> did you manage to transfer yours from within the current add-on to the external one?

wdym?

**Comment by txitxo0** [comment]
I have already recreate the db and, I don't know if this is normal due to the last changes, but the search box in the front is gone. There is no possibility to look for anything. There is no search option

**Comment by txitxo0** [comment]
> I have already recreate the db and, I don't know if this is normal due to the last changes, but the search box in the front is gone. There is no possibility to look for anything. There is no search option

Still the same with the new last version

**Comment by hydazz** [comment]
> > I have already recreate the db and, I don't know if this is normal due to the last changes, but the search box in the front is gone. There is no possibility to look for anything. There is no search option
> 
> Still the same with the new last version

do you have TYPESENSE_ENABLED ticked?

**Comment by txitxo0** [comment]
> > > I have already recreate the db and, I don't know if this is normal due to the last changes, but the search box in the front is gone. There is no possibility to look for anything. There is no search option
> > 
> > Still the same with the new last version
> 
> do you have TYPESENSE_ENABLED ticked?

Mmmm enabling this option I simply got a new 502 bad gateway.

```
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: Timeout {
          _idleTimeout: -1,
          _idlePrev: null,
          _idleNext: null,
          _idleStart: 71380,
          _onTimeout: null,
          _timerArgs: undefined,
          _repeat: null,
          _destroyed: true,
          [Symbol(refed)]: false,
          [Symbol(kHasPrimitive)]: false,
          [Symbol(asyncId)]: 1218,
          [Symbol(triggerId)]: 1212
        },
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 60,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
      },
      _header: 'GET /collections HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'X-TYPESENSE-API-KEY: xyz\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Host: 127.0.0.1:8108\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object: null prototype] { noDelay: true, path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/collections',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *3],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [ 'Accept', 'application/json, text/plain, */*' ],
        'x-typesense-api-key': [ 'X-TYPESENSE-API-KEY', 'xyz' ],
        'content-type': [ 'Content-Type', 'application/json' ],
        'user-agent': [ 'User-Agent', 'axios/0.26.1' ],
        host: [ 'Host', '127.0.0.1:8108' ]
      },
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://127.0.0.1:8108/collections',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Node.js v18.17.1
```

**Comment by txitxo0** [comment]
Apparently everything is working now, but the search box is still missing, is there something should I set up in my settings?
![image](https://github.com/alexbelgium/hassio-addons/assets/12279324/5b2084f0-74d3-4e0b-bb08-3c428dec59a3)

**Comment by hydazz** [comment]
try removing `/config/typesense` and recreate the container, wherever `/config` is mounted to on haos

**Comment by txitxo0** [comment]
Okay, thanks for your efforts!!

The search bar is back again! and apparently it is doing something in the back, but with no results. Could you help me a little bit more?
In the home tabl, if I look for a "man" generic word for my library (a testing one with only 6 photos one of them with a male person" the search gave me a good log:
```
[Nest] 1367  - 09/27/2023, 2:12:38 PM     LOG [TypesenseRepository] Using new schema: (unset) => albums-v2
[09/27/23 14:13:24] INFO     Downloading clip model 'ViT-B-32::openai'.This may 
                             take a while.                                      
  textual.onnx 100.0% • 254.1/254.1 MB • 9.8 MB/s • 0:00:00
                                                           
  visual.onnx 100.0% • 351.5/351.5 MB • 4.2 MB/s • 0:00:00
                                                          
[09/27/23 14:15:23] INFO     Loading clip model 'ViT-B-32::openai'   
```

But then....
![image](https://github.com/alexbelgium/hassio-addons/assets/12279324/0c3d20db-2770-4a38-9a1d-ef3f0d95da20)

And no more logs appears

**Comment by txitxo0** [comment]
Yesterday I was testing it in a 8gb NUC instead of my pi4 4gb and it works like a charm, so I guess this is due to the hardware
