### ISSUE TITLE
🐛MyElectricalData Dev - wrong version

### ISSUE THREAD

**Issue by vingerha** [alexbelgium/hassio-addons#934]
### Description

It shows 0.9.1b12 but in fact is still 0.9.0
The image by MED beta12 is corrupt on docker (manifest issue) so possibly this made it act like that
As m4dm4rtigan is on holiday for weeks, request to downgrade this to b11

### Reproduction steps

```bash
install, run, see that sensors still show version: 0.9.0
```

### Addon Logs

```bash
no logs needed
```

**Comment by alexbelgium** [comment]
Hi, indeed I made a mistake and reference the "latest" tag instead of "latest-dev" ! Please let me know if it works better

**Comment by vingerha** [comment]
Hi, still not fine, see below. 
As I cannot install the docker image (see above), it may divert?
Can I again propose to go for beta11?


![image](https://github.com/alexbelgium/hassio-addons/assets/44190435/0b65561b-09c6-4ec9-864e-837182e2779e)

**Comment by vingerha** [comment]
Or...wait...the update came in a bit later... so it seems, reinstalling -2 now

**Comment by vingerha** [comment]
Thanks, working agan with beta11... as this whole 0.9.1 is buggy now and m4dm4rtig4n returns in weeks...am happy 
Main issue with b11 (12) is that the price values are 1000 too high....awaiting MED to fix
