### ISSUE TITLE
enedisgateway2mqtt : new 0.7.7 version (not dev)

### ISSUE THREAD

**Issue by LittleBigDev** [alexbelgium/hassio-addons#94]
There is a new 0.7.7 stable version (not dev). It's up since yesterday, but still not available in the addon.

How long is it normal to wait before seeing it in supervisor updates ?

**Comment by alexbelgium** [comment]
Hi, the automated script runs every two days, which is usually a good timing for apps in production, and not too frequent to allow owners to pull a version if it causes issues. I've run it manually the past times as this is an app under fast development, and will run it now to update to this version

**Comment by alexbelgium** [comment]
And once it is updated in my repo, the supervisor needs to refresh for you to see it so it can take a couple hours more, except if you force it manually from the supervisor tab

**Comment by LittleBigDev** [comment]
Great news !
I force refreshed the supervisor, still no available update. I guess I have to wait a little more

**Comment by alexbelgium** [comment]
OK it's there :)

**Comment by LittleBigDev** [comment]
Is it possible to change this delay for now (and just for this project) ? We are going back and forth, lots of feedback, trials and errors.  
A shorter delay would make process smoother

**Comment by alexbelgium** [comment]
Well I can't change the supervisor update delay so I can't change a key element of this latency... Anyway for the moment I force the updates, and I suppose in the future it will soon come to a maturity level that will reduce the frequency of versions update. I'll think if there is another alternative (addon updated to 0.7.8-dev)

**Comment by LittleBigDev** [comment]
Yup. The -dev versions must be avoided though. Mostly not stable, addon crashes at start.

**Comment by alexbelgium** [comment]
Other people requested the -dev versions which is why I specifically added those... It's hard to find a one size fits all ;-)

**Comment by LittleBigDev** [comment]
Good idea.

I was also asking for dev at start. But it's actually not a good idea ; I regret asking for it :)

**Comment by alexbelgium** [comment]
Ok I've pushed two versions : even if the addon number is the same, one will build on "latest" and the other on "dev"

**Comment by LittleBigDev** [comment]
Nice. No more issue then :)
