### ISSUE TITLE
🐛 [Repository] Unable to add your repository to HA

### ISSUE THREAD

**Issue by jezyjay** [alexbelgium/hassio-addons#941]
### Description

Unable to add your repository to HA. repository.json is outdated. It should be yaml. see https://developers.home-assistant.io/docs/add-ons/repository/

### Reproduction steps

```bash
1. Go to HA Addons
2. Add a new repository
3. Paste the repository url: https://github.com/alexbelgium/hassio-addons
4. See error: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/alexbelgium/hassio-addon /data/addons/git/181623a7 stderr: 'Cloning into '/data/addons/git/181623a7'... fatal: could not read Username for 'https://github.com': No such device or address '
```

### Addon Logs

```bash
-
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, actually json or yaml should be both supported. Have you tried rebooting your system and adding again the repo? I added recently to my test system and it worked fine! Thanks

**Comment by jezyjay** [comment]
Oh ok, thanks for your help. A reboot helped.
