### ISSUE TITLE
Not showing in HA

### ISSUE THREAD

**Issue by dwvaughn** [alexbelgium/hassio-addons#95]
I've installed the add-on repo per the official instructions but the repo does not show up in the add-on store.  I checked the Supervisor log, per the official instructions and it states that everything is fine and dandy.

21-11-24 19:53:50 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/alexbelgium/hassio-addons repository
21-11-24 19:54:04 INFO (MainThread) [supervisor.store] Loading add-ons from store: 107 all - 0 new - 0 remove

**Comment by tiagomaricate** [comment]
I have the same problem
