### ISSUE TITLE
❓ [addon] refresh cycle

### ISSUE THREAD

**Issue by vingerha** [alexbelgium/hassio-addons#953]
**Which addon?**

MyElectricalData

**Describe the solution you'd like**

This add-on is based on the MyElectricalData repo. The repo gets updated as and when the dev has time.
At present the add-ons seem to follow only when you have time, this is not at all meant as a negative comment but more try ing to see how to reduce this.
Would it be possible to point your add-on always to the [latest] docker repo of the source? 

**Describe alternatives you've considered**

**Additional context**

Even if not feasible...continuing to appreciate your work a lot!

**Comment by alexbelgium** [comment]
Hi, updates are automatically done on saturday. Just wait a couple days ;-)

**Comment by vingerha** [comment]
thanks, I would love to understand the logistics behind all of this but at the moment ... different prio :)

**Comment by alexbelgium** [comment]
Hi, I've built an addon that reads the updater.json file to check if a new version was pushed in the upstream repo, then updates the addon. This addon automatically runs on my HA every saturday. https://github.com/alexbelgium/hassio-addons/tree/master/addons_updater

You can find the full code here : https://github.com/alexbelgium/hassio-addons/blob/master/addons_updater/rootfs/etc/cont-init.d/99-run.sh

**Comment by vingerha** [comment]
Just briefly browser through it ... too much for my current state of knowledge (hacker) ... I did get the idea, just not up-to-speed ith the individual lines

**Comment by alexbelgium** [comment]
Well I'm not a true dev more a tinkerer ;) so it works but it is perhaps not the most beautiful and readable code ever ;)

**Comment by lo97** [comment]
Hi, I don't know if it's the right place but for example Jellyseer has been updated since 3 weeks and your addon hasn't

**Comment by alexbelgium** [comment]
Hi, thanks you are right! It must be a specific bug for jellyseer. I'll check. Let me know if there are others which don't update, otherwise it should work as expected
