### ISSUE TITLE
Jellyseer not updated

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#961]
Hi, I don't know if it's the right place but for example Jellyseer has been updated since 3 weeks and your addon hasn't

_Originally posted by @lo97 in https://github.com/alexbelgium/hassio-addons/issues/953#issuecomment-1693030224_

**Comment by alexbelgium** [comment]
Mmh indeed there is an issue not sure yet why

**Comment by alexbelgium** [comment]
Solved

**Comment by lo97** [comment]
Something is still strange, the addon updated and it's showing both in the version number and in the logs, but inside Jellyseer it says it's the old version:
<img width="625" alt="Screenshot 2023-08-26 at 14 37 42" src="https://github.com/alexbelgium/hassio-addons/assets/56902258/150930d7-a475-4311-a6e7-3899f7d37854
<img width="454" alt="Screenshot 2023-08-26 at 14 37 51" src="https://github.com/alexbelgium/hassio-addons/assets/56902258/a81cca6e-4bd3-4e51-911c-2f246d3f5851">
">
<img width="771" alt="Screenshot 2023-08-26 at 14 37 29" src="https://github.com/alexbelgium/hassio-addons/assets/56902258/4d216d6c-e22b-4af0-83d2-13f97e5b38e8">

**Comment by alexbelgium** [comment]
That's strange it uses fallenbagel/jellyseerr:latest...

**Comment by lo97** [comment]
Hi, can you take another look at this? Because by using docker externally, pulling from fallenbagel/jellyseerr:latest gets me the latest version 1.7, while the addon is still on 1.5 and never updating

**Comment by alexbelgium** [comment]
Hi, updates should occur this night as per weekly update frequency

**Comment by lo97** [comment]
Yeah, but it still hasn't updated to the previous version that has been out for 42 days

**Comment by lo97** [comment]
Today the add on updated to 1.7 but, as you can see in the log, jellyseer is still at 1.5 (in the last lines) ![Screenshot_2023-09-16-11-18-56-24_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/alexbelgium/hassio-addons/assets/56902258/4fc4cfce-5265-4ecf-aa15-4c98c6d3403b)

**Comment by alexbelgium** [comment]
Strange, it pulls the latest tag

**Comment by lo97** [comment]
Still 1.5.0

**Comment by lo97** [comment]
Test 2 doesn't start and doesn't go past this![Screenshot_2023-09-17-01-20-15-89_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/alexbelgium/hassio-addons/assets/56902258/ce1bfac8-c098-4cf1-ac95-fcdc3babfca9)

**Comment by alexbelgium** [comment]
Thanks very much ; test3 should be the real deal

**Comment by lo97** [comment]
Thank you, it's now updated!!
