### ISSUE TITLE
🐛 [Filebrowser] Only listening on IPv6 by default?

### ISSUE THREAD

**Issue by reedy** [alexbelgium/hassio-addons#965]
### Description

Just installed Filebrowser, and it seems to be listening/bound only on IPv6 (to 8080?), by default

### Reproduction steps

```bash
1. Install add on
2. Try and access via http://ipv4address:8080 or http://ipv4address:8384
3. Browser can't connect
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Filebrowser
 filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files
-----------------------------------------------------------
 Add-on version: 2.23.0-5
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.8.4
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[10:51:52] INFO: Execute /config/addons_autoscripts/filebrowser.sh if existing
[10:51:52] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
Creating /config/addons_config/filebrowser
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[10:51:54] WARNING: Auth method change, database reset
[10:51:54] INFO: NoAuth option selected
[10:51:54] INFO: Starting...
2023/08/27 10:51:55 No config file used
2023/08/27 10:51:55 Listening on [::]:8080
[10:51:55] INFO: Started !
```

### Architecture

aarch64

### OS

HAos

**Comment by reedy** [comment]
Seems the embedded `http://ip4address:8123/db21ed7f_filebrowser/ingress` works fine...

**Comment by reedy** [comment]
Or is the mapping purposefully disabled?

https://developers.home-assistant.io/docs/add-ons/configuration/#optional-configuration-options

https://github.com/Poeschl/Hassio-Addons/blame/6bf8849/syncthing/config.yaml#L17

**Comment by reedy** [comment]
`2023/08/27 10:51:55 Listening on [::]:8080`

This seems a bit misleading...

If I override https://github.com/alexbelgium/hassio-addons/blob/9035c33/filebrowser/config.json#L82 by mapping 8080 to 8080...

The log still shows the same

`2023/08/27 12:38:46 Listening on [::]:8080`

**Comment by alexbelgium** [comment]
Hi, by default the port mapping is disabled to increase security in apps using ingress. You can however map the port that you want in the add-on options and this will allow accessing it though up:port

**Comment by reedy** [comment]
Thanks, yeah, I'd worked that out as per my comment above.

But why does it only show that it's (apparently) listening on IPv6 (at least as the `[::]` suggests), on `8080` even if you override that?

**Comment by reedy** [comment]
Oh, and also noting that https://github.com/alexbelgium/hassio-addons/blob/8ba4afb/filebrowser/README.md#configuration is incorrect as per the above...

>Webui can be found at http://your-ip:8080/.

Is not true by default for the HA addon

**Comment by alexbelgium** [comment]
Thanks for the PR

Actually `Listening on [::]:8080` occurs between `INFO: Starting...` and `INFO: Started !` which indicates from the script that it is actually coming from the filebrowser app itself and not my addon : https://github.com/alexbelgium/hassio-addons/blob/16aec59386c15a37631e33550674e18800e4949d/filebrowser/rootfs/etc/cont-init.d/99-run.sh#L93-L98

It has to run also on ipv4 however as the internal docker network managed by HA is in ipv4. So not sure why it has this behavior...

**Comment by alexbelgium** [comment]
BTW I took the opportunity of you looking closer on this add-on to switch the upstream repo to the official container and updating to the latest version ; it doesn't seem to change anything to your observation of listening on :: though

**Comment by reedy** [comment]
Not stale...

**Comment by alexbelgium** [comment]
Hi, actually it is linked to the app not the addon so I am not sure I can help. According to the upstream repo, it is linked to the go library

https://github.com/filebrowser/filebrowser/issues/1914
https://github.com/filebrowser/filebrowser/issues/1901
