### ISSUE TITLE
🐛 GitHub CI workflow is broken

### ISSUE THREAD

**Issue by reedy** [alexbelgium/hassio-addons#967]
### Description

![Screenshot 2023-08-27 at 15 06 38](https://github.com/alexbelgium/hassio-addons/assets/67615/d6f945f6-7d5c-4234-a442-21afd594d704)

![Screenshot 2023-08-27 at 15 05 43](https://github.com/alexbelgium/hassio-addons/assets/67615/425ac298-e140-4446-9636-c7213d9bffae)

```
Invalid workflow file: .github/workflows/onpr_check-pr.yaml#L97
The workflow is not valid. .github/workflows/onpr_check-pr.yaml (Line: 97, Col: 5): Unexpected value 'uses'
```

### Reproduction steps

```bash
Have a PR merged into this repo...
```

### Addon Logs

```bash
n/a
```

**Comment by reedy** [comment]
![Screenshot 2023-08-27 at 15 08 57](https://github.com/alexbelgium/hassio-addons/assets/67615/70f1da21-d868-4a49-8d51-f6a85a339e28)

**Comment by reedy** [comment]
Not sure if you can just remove the `runs-on` from that section...

**Comment by reedy** [comment]
https://github.com/alexbelgium/hassio-addons/commit/b1be295225cfd6d641958c20d834df276c302104

**Comment by alexbelgium** [comment]
Thanks - I've reverted to the code that I had before wednesday as actually the current logic wouldn't have worked anyway ;-) it would have called the build script in a way that would have committed the changes instead of testing it
