### ISSUE TITLE
✨ [REQUEST] Calibre update

### ISSUE THREAD

**Issue by bokkoman** [alexbelgium/hassio-addons#972]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Calibre

### Is your feature request related to a problem? Please describe

Not really a problem. But the used version for the addon is outdated, can you please update this.

On a sidenote to this, how do I add an external nfs share to the addon?

### Describe the solution you'd like

Update the Calibe addon to 6.25.x.

Be able to add external shares to addon.

**Comment by alexbelgium** [comment]
Hi, thanks! I think I had paused it because linuxserver has switched to s6v3 which messes up the guacamole server included and I don't have much time to make it work for the moment... For example the webtop addon has become unusable become of that issue and I couldn't find a way to get back to its normal behavior...

**Comment by bokkoman** [comment]
What do you need the guacamole for?

**Comment by bokkoman** [comment]
> Hi, thanks! I think I had paused it because linuxserver has switched to s6v3 which messes up the guacamole server included and I don't have much time to make it work for the moment... For example the webtop addon has become unusable become of that issue and I couldn't find a way to get back to its normal behavior...

I checked with the LSIO guys, and apparently there is no guacamole in this package anymore
It is kasmnvnc now.

![Screenshot_2023-08-29-17-23-12-20_572064f74bd5f9fa804b05334aa4f912](https://github.com/alexbelgium/hassio-addons/assets/7511367/6ee7651f-5ec8-49c2-a338-fcbf66c099de)

**Comment by alexbelgium** [comment]
Ah, then it's probably the issue... Thanks for investigating, what it sure is that it's not a straightforward update and it requires additional work on my side

**Comment by bokkoman** [comment]
> Ah, then it's probably the issue... Thanks for investigating, what it sure is that it's not a straightforward update and it requires additional work on my side

I have no idea what exactly, but perhaps if you point me in the right direction, i can help out. Or test the addon.

**Comment by alexbelgium** [comment]
I'm working on kasmvnc through the webtop addon once it's done I'll transpose it here

**Comment by alexbelgium** [comment]
Tested working!
