### ISSUE TITLE
Portainer update 2.9.2 to 2.9.3 (and fresh install)

### ISSUE THREAD

**Issue by toddstar** [alexbelgium/hassio-addons#98]
every time i try update Portainer from 2.9.2 to 2.9.3 (it does say " Portainer 2.9.3 **-4** is available " (image at bottom) is the -4 part the issue as portainer latest is just 2.9.3?) I keep getting the following error (been trying for a week or so)

`The command '/bin/bash -o pipefail -c if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi && if [ "${BUILD_ARCH}" = "armhf" ]; then ARCH="arm"; fi && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="arm"; fi && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi && curl -L -s "https://github.com/portainer/portainer/releases/download/${BUILD_UPSTREAM}/portainer-${BUILD_UPSTREAM}-linux-${ARCH}.tar.gz" | tar zxvf - -C /opt/' returned a non-zero code: 1`

removing the addon & doing a fresh install fails with the same error.

issue #24 & the follow up issue on dvershinin/lastversion seems to imply the latest version issue is sorted but same error

![Screenshot 2021-12-01 230222](https://user-images.githubusercontent.com/22575856/144328228-db3593a2-031f-402c-975f-a0f630a56691.png)

**Comment by alexbelgium** [comment]
Hi, thanks! Could you please post the full log? The precise error should arrive a bit below :) thanks!

**Comment by toddstar** [comment]
`
21-12-02 17:22:36 INFO (SyncWorker_6) [supervisor.docker.interface] Updating image db21ed7f/amd64-addon-portainer:2.9.2 to db21ed7f/amd64-addon-portainer:2.9.3-4
21-12-02 17:22:36 INFO (SyncWorker_6) [supervisor.docker.addon] Starting build for db21ed7f/amd64-addon-portainer:2.9.3-4

21-12-02 17:22:43 ERROR (SyncWorker_6) [supervisor.docker.addon] Can't build db21ed7f/amd64-addon-portainer:2.9.3-4: The command '/bin/bash -o pipefail -c if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi     && if [ "${BUILD_ARCH}" = "armhf" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi         && curl -L -s         "https://github.com/portainer/portainer/releases/download/${BUILD_UPSTREAM}/portainer-${BUILD_UPSTREAM}-linux-${ARCH}.tar.gz"         | tar zxvf - -C /opt/' returned a non-zero code: 1
21-12-02 17:22:43 ERROR (SyncWorker_6) [supervisor.docker.addon] Build log: 
Step 1/22 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:9.2.0
Step 2/22 : FROM ${BUILD_FROM}
 ---> bf24ebaa0590
Step 3/22 : ARG BUILD_UPSTREAM="2.9.3"
 ---> Using cache
 ---> 8406a4266b89
Step 4/22 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> 5791205391f4
Step 5/22 : RUN     apk add --no-cache     nginx || true
 ---> Using cache
 ---> 10a308185167
Step 6/22 : ARG BUILD_ARCH
 ---> Using cache
 ---> c158a2bf8840
Step 7/22 : RUN     if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi     && if [ "${BUILD_ARCH}" = "armhf" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi         && curl -L -s         "https://github.com/portainer/portainer/releases/download/${BUILD_UPSTREAM}/portainer-${BUILD_UPSTREAM}-linux-${ARCH}.tar.gz"         | tar zxvf - -C /opt/
 ---> Running in 9e3c7c034ef0
tar: invalid magic
tar: short read

Removing intermediate container `

**Comment by alexbelgium** [comment]
Weird... Its the untar that doesn't work. On which platform are you? It looks like the file is corrupted on portainer's github

**Comment by toddstar** [comment]
Proxmox VM box running Home Assistant OS 6.6 (supervisor-2021.10.8 & core-2021.11.5)

**Comment by alexbelgium** [comment]
That is strange... I've pushed back 2.9.2 could you please try to update? Thanks

**Comment by toddstar** [comment]
21-12-02 23:29:13 INFO (SyncWorker_4) [supervisor.docker.interface] Updating image db21ed7f/amd64-addon-portainer:2.9.2 to db21ed7f/amd64-addon-portainer:2.9.2-2
21-12-02 23:29:13 INFO (SyncWorker_4) [supervisor.docker.addon] Starting build for db21ed7f/amd64-addon-portainer:2.9.2-2
21-12-02 23:29:22 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build db21ed7f/amd64-addon-portainer:2.9.2-2: The command '/bin/bash -o pipefail -c if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi     && if [ "${BUILD_ARCH}" = "armhf" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi         && curl -L -s         "https://github.com/portainer/portainer/releases/download/${BUILD_UPSTREAM}/portainer-${BUILD_UPSTREAM}-linux-${ARCH}.tar.gz"         | tar zxvf - -C /opt/' returned a non-zero code: 1
21-12-02 23:29:22 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/22 : ARG 
BUILD_FROM=ghcr.io/hassio-addons/base/amd64:9.2.0
Step 2/22 : FROM ${BUILD_FROM}
 ---> bf24ebaa0590
Step 3/22 : ARG BUILD_UPSTREAM=2.9.2
 ---> Running in c4b49577bd97
Removing intermediate container c4b49577bd97
 ---> 864a0a4269fa
Step 4/22 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Running in 856c44a67248
Removing intermediate container 856c44a67248
 ---> ab08946cdcc6
Step 5/22 : ARG BUILD_ARCH
 ---> Running in c02ec1d0026b
Removing intermediate container c02ec1d0026b
 ---> 2e05e4e27f9a
Step 6/22 : RUN     if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi     && if [ "${BUILD_ARCH}" = "armhf" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="arm"; fi     && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi         && curl -L -s         "https://github.com/portainer/portainer/releases/download/${BUILD_UPSTREAM}/portainer-${BUILD_UPSTREAM}-linux-${ARCH}.tar.gz"         | tar zxvf - -C /opt/
 ---> Running in c03c786b9da8
tar: invalid magic
tar: short read
Removing intermediate container c03c786b9da8

**Comment by alexbelgium** [comment]
It works on my system and I've tested the download of all types of portainer tar and it works. Are you sure it is not something in your system that has changed and that prevents the Architecture tag from being read?

**Comment by alexbelgium** [comment]
I've made a change to use amd64 as default, perhaps it will help

**Comment by toddstar** [comment]
> It works on my system and I've tested the download of all types of portainer tar and it works. Are you sure it is not something in your system that has changed and that prevents the Architecture tag from being read?

Not that I'm aware of, however just tested trying to install some of your other add-ons and they've all failed so does look like it's something my end (although has just successfully updated nodered add-on from community store). 
Will jump on PC later and do some digging.

**Comment by alexbelgium** [comment]
Very strange if it worked in the past and not anymore. Especially if you try addon such as nextcloud which have fail-safe installation. Do you have enough space? you can run "ha su repair" to remove dangling images. Also, you can try setting manual dns servers in the supervisor if you use a dns ad remover such as adguard

**Comment by toddstar** [comment]
> Very strange if it worked in the past and not anymore. Especially if you try addon such as nextcloud which have fail-safe installation. Do you have enough space? you can run "ha su repair" to remove dangling images. Also, you can try setting manual dns servers in the supervisor if you use a dns ad remover such as adguard

after checking the logs of some of the other add-ons & ruling some other things out, seems I've found the issue (its certainly worked / allowed me to do a fresh install of 2.9.2-2 & test install some of your other addons) although somewhat confused as to why. 

The DNS servers of my HA was set to 192.168.4.100 & 8.8.8.8, the former is my old ISP DNS server; it's still there as such, just have opnsense now as my main gateway rather than ISP router which NATs all 'external' port 53 (dns) traffic requests to adguard (setup as addon within opnsense). 
Trying to update/install your add-ons (and other third parties, same issue with trying fresh installs with https://github.com/jakowenko/double-take addons) with those DNS servers failed, although as per last message did allow nodered from community store to update (???), changing the DNS on HA to my main gateway/adgaurd server has instantly fixed it.

so thankfully working :-) but really not sure why some requests have redirected (could see dns requests on adguard during he portainer upgrade process whilst still set to 192.168.4.100) & others completely failed

**Comment by alexbelgium** [comment]
Great news! Thanks for sharing. Have a nice weekend

**Comment by toddstar** [comment]
> Great news! Thanks for sharing. Have a nice weekend. My addons rely on the build code within ha, perhaps this isn't robust in terms of dns management compared to the rest of HA...

Thanks for the help & apologies for wasting time for something clearly not your issue! (If I can workout where to even report this to HA I will)

**Comment by alexbelgium** [comment]
Oh, no time wasted at all. It's now written in my head and the next time sometime will have an issue when installing I'll tell them also to look first at dns. Knowledge sharing is always a win-win situation both for sender and receiver :)

**Comment by toddstar** [comment]
So where's 2.9.3 already Haha?

(Joke aside, thanks for help & thanks for the add-on! Especially as 'official' portainer is dead)
