### ISSUE TITLE
🐛 [Omadav3] out of memory

### ISSUE THREAD

**Issue by SventeHof** [alexbelgium/hassio-addons#980]
### Description

i install the addon, bit it will not start:

-----------------------------------------------------------
 Add-on: Omada v3.2
 TP-Link Omada Controller
-----------------------------------------------------------
 Add-on version: 5.3-amd64-2023-09-01
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.0b4
 Home Assistant Supervisor: 2023.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
Creating symlink
Updating permissions
[13:54:02] INFO: Execute /config/addons_autoscripts/omada-v3.sh if existing
[13:54:02] INFO: ... no script found
INFO: Validating user/group (omada:omada) exists with correct UID/GID (508:508)
INFO: Group (omada) doesn't exist; creating
INFO: User (omada) doesn't exist; creating
INFO: Time zone set to 'Europe/Berlin'
WARN: ownership not set correctly on '/opt/tplink/EAPController/data'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/logs'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/work'; setting correct ownership (omada:omada)
INFO: userland/kernel check passed
INFO: Starting Omada Controller as user omada
SLF4J: com.tp_link.eap.configuration.b
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: com.tp_link.eap.util.o
library initialization failed - unable to allocate file descriptor table - out of memory

### Reproduction steps

```bash
See error above
```

### Addon Logs

```bash
see above
```

### Architecture

amd64

### OS

HAos, Virtual Machine

**Comment by alexbelgium** [comment]
Hi, shouldn't you allocate more memory to the virtual machine

**Comment by SventeHof** [comment]
Hi, 

memory usage is 52%, the virt. machine has 24GB and 12GB are free.

**Comment by SventeHof** [comment]
i use now the omada addon without v3 and this works

**Comment by alexbelgium** [comment]
It us the most updated version I think
