### ISSUE TITLE
🐛 [POSTGRES] env: can't execute '/ha_entrypoint.sh': No such file or directory

### ISSUE THREAD

**Issue by swap83** [alexbelgium/hassio-addons#983]
### Description

Postgres doesn't start.

### Reproduction steps

```bash
1. Go to 'Add-ons'
2. Click on 'Postgres'
3. See error
```

### Addon Logs

```bash
`env: can't execute '/ha_entrypoint.sh': No such file or directory`
```

### Architecture

amd64

### OS

HAos

**Comment by thrillhouse2342** [comment]
Confirmed for me too. Updated postgres this morning and can't start it due to that error.   Had to roll back

**Comment by swap83** [comment]
I updated but the error persists. (Current version: 15.3-7)

**Comment by alexbelgium** [comment]
Thanks I think it's a crlf vs lf issue i'll check tomorrow

**Comment by alexbelgium** [comment]
Should be good now! Sorry about that it was a major logic update on my whole repo

**Comment by swap83** [comment]
Yes! Now works. Thank you for assistance!
