### ISSUE TITLE
🐛 [gitea] Cannot start after updating to 1.20.4

### ISSUE THREAD

**Issue by bilogic** [alexbelgium/hassio-addons#985]
### Description

```
exec /ha_entrypoint.sh: no such file or directory
```
The latest gitea add-on has 1 line in the logs and can't start

### Reproduction steps

```bash
1. Go to Gita add-on page
2. Click on start, the button spins and stop
3. Click on Logs
4. See error `exec /ha_entrypoint.sh: no such file or directory`
```

### Addon Logs

![image](https://github.com/alexbelgium/hassio-addons/assets/946010/c54925d8-19de-45e4-af35-8ac597c39646)

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Argh I forgot about that thanks I'll push a new version

**Comment by alexbelgium** [comment]
Thanks should be good

**Comment by bilogic** [comment]
fixed! thanks :)
